### ISSUE TITLE
[Bug] Selected block/brick still shows in hand after removing from hotbar

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#100]
If you have a block in hand and remove it from your hotbar while still having the block selected in hand it will still show. (Cannot place with it though)
![untitled](https://user-images.githubusercontent.com/32974671/31848214-a1f3bd34-b5f2-11e7-8f4d-56731d743689.png)

**Comment by Xerma** [comment]
Forgot to mention that scrolling to a new selection fixes the issue

**Comment by tsunamayo** [comment]
Okay thanks a lot for the report, it is now fixed. Cheers
