### ISSUE TITLE
[SUGGESTION] [MISSING BLOCK] Missing a flat wedge window block

### ISSUE THREAD

**Issue by daOyster** [tsunamayo/Skywanderers#1000]
### Short Description of the issue:

If I remember right, there used to be a flat wedge window block in the codex. It could be really useful in the new update now that we have stretchable blocks. If we could please get one back into the game I'm sure many of us would really appreciate it.

### Steps to reproduce the issue:

Play the latest version of the game (18w45a)

### Environment
- Skywanderers version: Experimental (18w45a)
- Graphics Card: Nvidia GeForce 970

### Additional information:

[Picture of Window section in codex](https://cdn.discordapp.com/attachments/416013956331601930/513899813377540106/unknown.png)

Please also include the `output_log.txt` file. You can find your log here: 

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2593580/output_log.txt)

**Comment by JRL101** [comment]
hmm i think you should try ALL the wedge shapes you can see.

**Comment by Tomatart** [comment]
The one missing is a flat side triangle. I used it all the time.

**Comment by Rizzo911** [comment]
The one circled at bottom is the brick version and it doesn't do the same thing as the old large version that was able to be colored and is roughly the size of the third top from right. Current "pre-sided" canopies hit boxes don't work properly and yes, we need the block Toma mentions.

**Comment by JRL101** [comment]
@Tomatart correct that is missing along with a few others. But this is not related to the missing WEDGES, as they seem to be accounted for.

@Rizzo911 Very correct, Seems player collision is broken with all Canopy blocks. 
bricks still seem to be able to be placed inside of the mesh space. Strangely enough. 
but other blocks arent allowed and the player especially.

![image](https://user-images.githubusercontent.com/33255536/48768901-485d0b00-ecf5-11e8-994a-d1cc8e702441.png)

**Comment by tsunamayo** [comment]
Hi guys, sorry I am having a hard time to see which one you need, was it a brick or a block (1m or 0.5m)
Yes collisions with the player is bugged but there is a could update to be done so it will be fixed eventually.
Congrats on #1000 ^^

**Comment by Tomatart** [comment]
It was a block, not a brick. 
It was a vertical-flat triangle shape, basically the side of a wedge.

**Comment by tsunamayo** [comment]
Okay I see, I will include it back. For some reason windows / canopy are a huge pain to design - but this one should be okay. Cheers

**Comment by ZachZent** [comment]
> 
> Also, if i may add, you cannot paint any canopy blocks. or rather, if you try to they do not change color, i don't know if they are actually being painted and just not changing color.

I think this is a holdover from one of the older canopy blocks. Don't remember the name, but when you painted it, it only painted the boarder of the glass without changing the color of the glass itself. Probably the same item, just with the boarder removed

**Comment by tsunamayo** [comment]
We now have side windows tile and a better transparent selection. Thanks
