### ISSUE TITLE
[Experimental][Bug] Hazard block wedge texture needs a small fix

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1002]
The texture on the sides just don't line up properly with the blocks:
![20181121000100_1](https://user-images.githubusercontent.com/32974671/48822127-7c4e2580-ed21-11e8-9952-4e2bff02b416.jpg)

**Comment by ZachZent** [comment]
Literally unplayable

**Comment by tsunamayo** [comment]
I agree, it is the kind of shit that keeps me from sleeping too ;-). But anyways a big stickers update is coming soon, and stripes will be made in a different way, so this should no longer be be an issue. Thanks

**Comment by tsunamayo** [comment]
Hi, this issue should now be fixed. Thanks a lot!
