### ISSUE TITLE
[BUG] [All branches] Screen "Freeze" with RTX 2080 ti 

### ISSUE THREAD

**Issue by kaffeina92** [tsunamayo/Skywanderers#1003]
### Short Description of the issue:

When starting a game the loading screen freezes - however if I press ESC i can see the ingame cursor and hear the sound effect of the mouse wheel scroll, so the game is running but the screen stayes on "Loading". 

### Steps to reproduce the issue:

You might wanna check if the new RTX 2080 ti graphic cards are causing the issues (me and anthor player are having the same problem at the moment) - He also have the new graphic card.

### Environment
- Skywanderers version: 18w45a
- Graphics Card: RTX 2080 TI 11 OC Ventus

### Additional information:
For some strange reasons you cant see the cursor on the image, however its where it freezes the screen
![image](https://user-images.githubusercontent.com/38698217/48854023-11e4c600-edb1-11e8-8d2b-b7dd45ed9000.png)

Please also include the `output_log.txt` file. You can find your log here: 

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2604973/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry I saw the issue, I will keep you posted once I have something new. It might have to wait an unity update. Thanks!

**Comment by tsunamayo** [comment]
Issue was the dreaded RTX issue that was fix a few patches ago. Thanks!
