### ISSUE TITLE
[Bug] Small hotbar bug and suggesiton

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1004]
Bug: Like I said it is a small one. If you look on the top hotbar, you will see the engine image has no boarder. Just a white top

Suggestion: The addition of all three hotbars is great though there is something missing. It would be great if there was some indicator which hotbar our menu is currently on. Just a small arrow on the side would work quite well

https://imgur.com/a/wgarjub

**Comment by tsunamayo** [comment]
Issue was fixed  some time ago, also there is a small indicator of which hotbar is active. Thanks a lot!
