### ISSUE TITLE
[BUG] Deleting hinge disables building.

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#1005]
### Short Description of the issue:
If you delete a hinge you cannot delete or place new blocks. You can highlight and click which will give the animation and sound but not delete/place.
...

### Steps to reproduce the issue: 
Make a hinge then delete it. Then try building.
...

### Environment
- Skywanderers version: 18w47a
- Graphics Card: RTX 2080 Ti

### Additional information:

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2609763/output_log.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, I have deleted plenty of hinge without any issue. It seems related to the collisions somehow, I think I would need you ship in order to reproduce. Are you having this issue all the time? Do I need to do something specific to reproduce?
Thanks!

**Comment by BrickMacklin** [comment]
It appears to happen when using mirror mode with hinges. Another user was able to replicate by doing that.

**Comment by tsunamayo** [comment]
I think this issue should be fixed - tell me if you still manage to reproduce it! Cheers
