### ISSUE TITLE
Glowing is messed up

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1006]
### Short Description of the issue:
The light rod and glow bricks are locked to this odd white color that doesn't glow very brightly.
...

### Steps to reproduce the issue:
place a light rod or glow brick and look at them.
...

### Environment
- Skywanderers version: Experimetal
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Rizzo911** [comment]
I would add engine bloom to this. It seems engines no longer glow or light up properly in the latest build.
Version: 18w47a

**Comment by Tomatart** [comment]
This also effects the flat screens, and instrument bricks.

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
