### ISSUE TITLE
Drones still can't clip

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1007]
### Short Description of the issue:
You stated in the devlog that drones would be able to clip through things now, but they still can't. 
...

### Steps to reproduce the issue:
activate drones and move to where the would travel through blocks.
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Ok indeed something went wrong, I fixed it I push a patch asap (couple hour max) Thanks!
