### ISSUE TITLE
[Experimental] [Bug] Exporting blueprint creates 0 KB file [18w47a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1008]
### Short Description of the issue:
Some blueprints, when exported by either the drone or the Identity Unit in the latest version, will overwrite the old .mps with one that has a filesize of 0 KB.

Attempting to save a world after one of these blueprints has been loaded will save changes in the player's location that have been made, but will not save any instances of the ship that have been loaded into the world. Instead, a new .mps will be created for these ships in the PlayerEntities directory that also has a filesize of 0. Attempting to load a world that has one of these empty .mps files saved to it will result in an infinite load screen until the .mps has been removed.

### Steps to reproduce the issue:
Place the pre-export version of the blueprint in the Blueprints directory, load it in-game, then export it. The resulting .mps should have a size of 0 KB.

### Environment
-Skywanderers version: 18w47a
-Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The blueprint in question before being exported:
[Pre-export blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/2609903/Pre-export.blueprint.zip)

The same blueprint after being exported:
[Post-export blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/2609902/Post-export.blueprint.zip)

The .mps saved to the PlayerEntities directory after loading it into the world:
[Empty mps file.zip](https://github.com/tsunamayo/Skywanderers/files/2609900/Empty.mps.file.zip)

Output log:
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2609904/output_log.zip)

**Comment by tsunamayo** [comment]
Okay I am glad you sent me this, it was actually two issues, one edge case from the save migration and on when a command was linking to a deleted entity. patch coming soon. Thanks!
