### ISSUE TITLE
[Graphical Bug] Block rotation bug

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1009]
### Short Description of the issue:
When rotating any object, brick or block, you are able to drag before the rotation completes giving an interesting graphic mess up which automatically corrects itself when the object is placed.

### Steps to reproduce the issue:
Simply rotate any object and start dragging before the rotation completes.

### Additional information:
https://media.giphy.com/media/5ibjHMVqcn8Rc0P7gp/giphy.gif

**Comment by tsunamayo** [comment]
Thanks for the gif! I am looking into it.

**Comment by tsunamayo** [comment]
No longer applicable as the rotation animation was not compatible with the new building anchor offset feature. Thanks!
