### ISSUE TITLE
[Bug] Multiplayer seems to freak out/crash due to hinge or logic issues

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#101]
I was hosting a session with Mega when using the mini hinge that was connected to a slider and was working just fine until I removed the mini hinge/slider. Mega claimed to be able to delete blocks while I could not and I could move around while not seeing Mega move at all. After a few seconds Mega wasn't able to delete blocks either. We then did a round without building anything and just flew ships around and everything seemed to work fine. So it could be logic or hinge/mini hinge related, at my best guess. 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1404536/output_log.txt)

UPDATE 1: Updated log file from Singleplayer recurrence
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1404550/output_log.txt)

UPDATE 2: Reproduced the bug in a clean install on SP. Seems to happen after clicking the refresh looking arrows and then right clicking the slider to reconnect it

UPDATE 3:  Just tried to reproduce the bug with a button and a slider and the bug still occurred. (Not hinge related)

**Comment by Xerma** [comment]
Updated log file from Singleplayer recurrence
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1404550/output_log.txt)

**Comment by Xerma** [comment]
Reproduced the bug in a clean install on SP. Seems to happen after clicking the refresh looking arrows and then right clicking the slider to reconnect it

**Comment by tsunamayo** [comment]
The bug should be fixed. Tell me if you see it again! Cheers
