### ISSUE TITLE
[Bug] Can't access paint selection

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1011]
### Short Description of the issue:
When holding the paint tool and pressing the button to access the paint selection the cursor appears for a second and disappears while no paint menu shows up.
This is only really an issue because the drone can't paint child entities and you can't see the colour names in the drone so selecting a custom colour is very challenging. 

### Steps to reproduce the issue:
Try to access the colour selection menu.
Try to get the drone to paint a child entity
Open up the drone menu and look at the colour selector, no names are visible.

### Environment
- Skywanderers version: 18w47a
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2610655/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Garrett-C** [comment]
Just an update, after re launching the game the paint menu does now open.

**Comment by tsunamayo** [comment]
Okay, I am not sure to understand, is it several different issues? I am not sure what I need to do to reproduce. Thanks!

**Comment by Garrett-C** [comment]
Yeah it is a tough one. So after messing with it a bit and talking to womble I think it occurs when you have pressed f2. If you haven't pressed f2 at all in a session then you can access the paint menu fine. However, once you have pressed f2 and toggled the UI back on you can not access the paint UI.

Additionaly I was pointing out that in the paint menu you can't actually see the name of the paint you are choosing.

On top of that it appears that the auto painting drone can not paint child entities, I have only tested this with the new rotor though.

**Comment by tsunamayo** [comment]
Okay indeed I reproduced the problem! I keep you posted.

**Comment by Garrett-C** [comment]
No problem, apologies for the poorly worded first report.

**Comment by tsunamayo** [comment]
Okay issue should have been fixed. Thanks!
