### ISSUE TITLE
[BUG] Docking probe is broken

### ISSUE THREAD

**Issue by Elektron72** [tsunamayo/Skywanderers#1012]
### Description:
When I try to place a docking probe in the latest experimental version, it turns invisible. Any attempt to remove it causes an infinite deletion animation that prevents the player from adding or deleting anything.

### Steps to reproduce issue:
To reproduce the issue, place a docking probe.

### Environment
- Skywanderers version: 18w47a
- Graphics Card: NVIDIA GeForce GTX 950M

**Comment by JRL101** [comment]
If im correct the docking probe has yet to be replaced. Tsuna is/was/is going to, be working on a better docking code.

**Comment by tsunamayo** [comment]
No longer applicable, but indeed I need to add that docking feature back. Thanks!
