### ISSUE TITLE
[SUGGESTION] Draggable 1 brick angled line brick

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1013]
This is not a bug, but a suggestion. Prior to Legacy we had a brick that was roughly equivalent to the attached graphic labeled 1. It was a 45 degree angled brick roughly the size of a block. What I am hoping to see is a return of this brick with some added functionality. Essentially, I want to attach one end of this style brick and rather than creating a full triangle, it would create an angled line that is ~1 brick high which could be dragged out to any angle. This would be highly useful framing doors and windows and would also remove the obvious excessive borders that is evident in the attached graphic.

_(Screenshots, Videos, Error logs, Related issues)_
![angled](https://user-images.githubusercontent.com/33043997/48970766-44bfd180-efde-11e8-9f27-2cd003206885.png)

**Comment by ZachZent** [comment]
Hey now, you stole my picture :D

**Comment by Rizzo911** [comment]
Thanks to Zach for reusing his picture and not having to recreate it :)

**Comment by Rizzo911** [comment]
Alternatively, I would accept if these bricks merged better and therefor did not have the seam between the bricks showing and only retained the outer edge highlight as blocks currently do. What makes this ugly is the excessive seam lines where the triangles meet.

**Comment by tsunamayo** [comment]
Yes I agree this brick would be very convenient. It is not possible with the current tech but I wanted to give it a try at one point, I keep you guys posted! Cheers

**Comment by tsunamayo** [comment]
So we have this brick now since a couple builds back. Thanks!
