### ISSUE TITLE
[Bug] Sequencer Controller Settings NOT Retained in Blueprints

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1014]
### Short Description of the issue:
When using the drone to save/load a blueprint, the linkage appears intact, but the controllers value settings reset to default.

### Steps to reproduce the issue:
- Create a structure with child entities
- Add a controller, link to children (in my case new hinges) and set values 
- Use the drone to export the Blueprint
- [Optional] quit to desktop and restart Skywanderers
- Call the drone and load the structure saved above
- Not the controller(s) have reset to default values and need to be redone

### Environment
- Skywanderers version: 18w47a
- Graphics Card: GeForce GTX 960

**Comment by tsunamayo** [comment]
This issue also have been fixed sometime ago. Thanks a lot!
