### ISSUE TITLE
[SUGGESTION] Button Text on Hide Mirror Should Toggle

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1015]
### Short Description of the issue:
The new drones are great but it wasn't immediately obvious to me that the "hide" mirror option was actually a toggle. So when I first hid it, I couldn't figure out how to get them back. Can we have the button text toggle... so when the mirror plane is showing the button reads: "Hide Plane" as it does now and when the mirror plane is hidden the button reads: "Show Plane" to make it clear that you click it to get the result you want.

_(Screenshots, Videos, Error logs, Related issues)_
![20181124122110_1](https://user-images.githubusercontent.com/33043997/48971109-928b0880-efe3-11e8-8d9f-17e5e8efcf76.jpg)

**Comment by tsunamayo** [comment]
Yes actually I must have made that change at one point some time ago! Cheers
