### ISSUE TITLE
[BUG] Toggling Main Drone w/ Symmetry Can Create a Fleet of Orphaned Drone 2's

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1016]
### Short Description of the issue:
Currently when you toggle the main drone F5 (on) and enable a second drone through Symmetry, you can create phantoms of drone 2 by hitting F5 (off) on the main drone, bringing it back via F5 and toggling the symmetry mode. This can be done repeatedly. 

Expected behavior: both drones should disappear and reappear when F5 is hit and Symmetry mode is enabled. There should only be one instance of drone 1 and drone 2 on the screen at any time.

### Steps to reproduce the issue:

1. Call drone 1 via F5 (on)
2. Enable Symmetry via drone 1 (drone 2 appears)
3. Dismiss drone 1 via F5 (off) drone 2 stays in play
4. Enable drone 1 again via F5 (on)
5. Toggle Symmetry off; then on again via checkbox (new drone 2 appears) (there are now two drone 2's)
6. Repeat steps 3-5

### Environment
- Skywanderers version: 18w47a
- Graphics Card: GeForce GTX 960

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20181124124655_1](https://user-images.githubusercontent.com/33043997/48971490-6c1b9c00-efe8-11e8-9133-4f857883753e.jpg)

**Comment by tsunamayo** [comment]
I think this issue was fixed, but anyway it is now longer applicable as symmetry now uses a tool and no longer the drone... Cheers
