### ISSUE TITLE
[BUG] Deleting ship causes screen to bloom out.

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#1017]
### Short Description of the issue:
When deleting a ship from an identity block the screen will create a wacky color and bloom out. Only way to get out of it is reload the game. The ship will also not delete. Gif below shows the issue.
...

### Steps to reproduce the issue:
Delete a ship from an identity block.
...

### Environment
- Skywanderers version: 18w47a
- Graphics Card: RTX 2080 Ti

### Additional information:

GIF: [https://gph.is/2AmP4Vi](https://gph.is/2AmP4Vi)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2612492/output_log.zip)

**Comment by Rizzo911** [comment]
I also see the issue. Color seems to differ (mine was aqua blue) but behavior is the same.

**Comment by Dwarf-LordPangolin** [comment]
This is also happening for me.

Skywanderers version: 18w47a
Graphics Card: NVIDIA GeForce GTX 1060 6GB

Curiously, this is not happening with all ships for some reason. I will try to find out what the difference between ships where this does and doesn't happen is.

**Comment by pinesh** [comment]
still prevalent only I got a more entertaining effect, can be fixed by spawning a drone.
![20181211201010_1](https://user-images.githubusercontent.com/14081996/50066927-49a61a00-0173-11e9-93f9-dceaa9f4c529.jpg)
![20181211202639_1](https://user-images.githubusercontent.com/14081996/50066929-4ad74700-0173-11e9-8151-b4184b64f0eb.jpg)

**Comment by tsunamayo** [comment]
This issue should have been fixed already in current builds (tell me if you still manage to reproduce this!) Cheers!
