### ISSUE TITLE
[BUG] Seat Cushions Not Aligned to Seat Grids

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1018]
### Short Description of the issue:
The seat cushion can no longer be placed properly on either seat block. They are offset.

### Steps to reproduce the issue:
- add a seat to a structure
- try to add a seat cushion to the seat
- note that the seat cushion can not be placed in the proper place on the seat, but only in an offset position.

### Environment
- Skywanderers version: 18w47a
- Graphics Card: GeForce GTX 960

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20181124142009_1](https://user-images.githubusercontent.com/33043997/48972268-f538d000-eff4-11e8-94d9-c8541fb533f5.jpg)

**Comment by tsunamayo** [comment]
Hi, yes you are right, I didnt spent time on it as I will change my approach with regard to cushion: they will be merged with the seat itself. Current approach is now a bit bugged and restrictive in term of art style. Thanks!

**Comment by tsunamayo** [comment]
New seat no longer use cushion. Cheers!
