### ISSUE TITLE
[BUG] Flight Stick Bricks Are Offset 1 Brick on Blocks

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1019]
### Short Description of the issue:
The flight sticks (double and single) are off by 1 Brick when placed on blocks. They can't be centered to the seat in front of them.

### Steps to reproduce the issue:
- Place the console block or the 1/2 block
- Place a seat in front of it for alignment
- Place a flight stick brick (double or single)
- Note that the brick is off by 1 brick from where it should sit on the grid

### Environment
- Skywanderers version: 18w47a
- Graphics Card: GeForce GTX 960

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20181124143833_1](https://user-images.githubusercontent.com/33043997/48972388-1f8b8d00-eff7-11e8-9cc2-c0699d84666e.jpg)

**Comment by tsunamayo** [comment]
Issue was fixed some time ago... Thanks!
