### ISSUE TITLE
[Experimental] [Bug] New Hinge separates/moves 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1020]
The new hinge upon reloading SKY1 will either separate or move into a different position other than when the entity was last saved. Multiple players have had different encounters. 
Some entities remain in place while others do not.

EDIT:   
-After a little playtime and building with new hinges not worrying about the canopy that was indestructible the BUG happened again. 
      -When looking at the canopy that was once indestructible, was now able to have blocks placed on it.
      -Once I noticed that... I quickly deleted those blocks and carried on building on the two hinges I recently placed.
      -I was unable to build on one of the hinges... I decided to restart the game and see if that would fix it. 
      -that particular hinge and the wing/engine that was attached was now not on the ship and replaced the canopy blocks that were recently destroyed.  (Refer to Image)

...

I have tried to reload the original blueprint. (No fix) 
I re-hinged the area affected and it stays with restarts... the problem is the leftover blocks that are indestructible.

...

### Environment
- Skywanderers version: 18w47a
- Graphics Card: Nvidia 1080TI

### Additional information:

The ship to the right in the screenshot was the first iteration of the bug.
While the ship to the left was the most recent.

![20181126192212_1](https://user-images.githubusercontent.com/45324484/49052561-03801b00-f1b2-11e8-9109-c4a2e18a4f65.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2612837/output_log.txt)

**Comment by ExodistSKY1** [comment]
I was able to reproduce the bug by attaching a new hinge and continuing to build what I previously had been working on. 

The screenshot below is the result of saving then loading in the blueprint...

![20181126211425_1](https://user-images.githubusercontent.com/45324484/49056320-ed2d8b80-f1c0-11e8-950f-15e3af0694ba.jpg)

**Comment by tsunamayo** [comment]
There was some issue regarding this, but it should have been fixed. Thanks!
