### ISSUE TITLE
[BUG?] Hinges Can Only Stretch to 2m Max

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1021]
Currently, 2m is the max that the new hinge can be extended. Is this intended? If it is, this will really hinder builds going forward.

Skywanderers version: 18w47b

![711980_20181124221730_1](https://user-images.githubusercontent.com/26584892/48975510-6d27ea00-f037-11e8-9f18-73de08e74995.png)

**Comment by BrickMacklin** [comment]
Further can we have the hinges hold way more than 4000 kg? I've needed hinges to build large sections and can't move them once a few blocks are placed. They also reset on reloads.

**Comment by ZachZent** [comment]
As an aside which I don't believe is a bug, you can paint the middle a different color from the outside parts. Just an observation

**Comment by gmunga5** [comment]
I mean 4000kg is quite good, I believed that is more than the cornelian shuttle for example.

**Comment by ExodistSKY1** [comment]
> 
> 
> The 2m is a limitation of the brick system. I could try to work around that if necessary, you want a longer hinge purely for aesthetic or to get more max weight? I can tweak the weight of course, it was a random number that seems right.

They are wanting to have a higher limit on the max weight for the hinge.

**Comment by BrickMacklin** [comment]
Can we have increase to say 400,000 kg?
![hinge plate](https://user-images.githubusercontent.com/37836252/48986984-acfada00-f0e8-11e8-9bd2-9518b9b426f7.png)

**Comment by tsunamayo** [comment]
Hi, hinge are now limited to 4m. Not sure if it is enough for you. Btw be aware I am still not satisfied with current hinge design, so it might change again in the future. Designing a hinge proved to be a complete nightmare tbh. Maybe thats why you dont get hinge is other game ;)
