### ISSUE TITLE
[Experimental] [bug] UI locks up when loading an existing world

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1023]
### Short Description of the issue:

Whenever I load into an existing world, I am unable to scroll between blocks or hotbars, and the codex GUI will not allow me to pick a block. It is also missing the block preview feature.

Loading into a new world (by deleting the contents of C:\Users\xxx\AppData\LocalLow\TsunamayoCorp\Skywanderers ) does not show this behavior until world saved and reloaded (either form quit to title or quit to desktop)

### Steps to reproduce the issue:

Create new character, save, quit, reload.

### Environment
- Skywanderers version: 18W47a
- Graphics Card: GTX1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![20181125145447_1](https://user-images.githubusercontent.com/40872394/48980584-06e8a900-f0c3-11e8-88df-442f70e3d116.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2613169/output_log.txt)
`

**Comment by Lsutehall** [comment]
Just wanted to post an update on this. 

I am still experiencing this behaviour in version 19w03 (and all the versions in between the initial report and now) but it seems like it can be worked around by deleting the "characters" folder - this allows the game to load correctly.

**Comment by Lsutehall** [comment]
Another quick update: this now seems fixed in version 19w23a.
This issue can be closed.

**Comment by tsunamayo** [comment]
Okay sorry I was busy on the gfx udpate and havent looked at it, glad to see it is closed! Thanks
