### ISSUE TITLE
Mirror drone breaks constantly

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1025]
### Short Description of the issue:
The mirror drone that you use when using symmetry breaks frequently. It will just stop building and spin in circles. this doesn't appear to have a specific cause other than just happening after a building for few minutes.
...

### Steps to reproduce the issue:
activate symmetry, build for a while and the mirror drone will break.
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay this little guys sucks... Do you have a log file? It might be an error in its logic programming that makes it crash... Thanks

**Comment by tsunamayo** [comment]
There is now a new symmetry tool. Thanks
