### ISSUE TITLE
Hinge Issues

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1027]
### Short Description of the issue:
Currently can't place blocks or bricks on hinges currently and then once you delete a hinge the game prevents you from placing any blocks anywhere.

### Steps to reproduce the issue:

Place a new hinge, try to place a block on it. Delete the hinge and then try to place a block elsewhere.

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2642015/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Garrett-C** [comment]
Just did some more testing on this. Building on hinges is working again. No idea why it wasn't working before.

**Comment by Womble-TC** [comment]
Ive been testing this, apparently its dependant on the blueprint. Hinges work on a new starter block, but not on some existing blueprints, even if they were made in the newer builds. I can provide a "broken" blueprint if needed.

**Comment by tsunamayo** [comment]
Hey, yes that could help a lot! I changed a lot of things regarding to children entity, it could be there was a corruption in the old data. Thanks

**Comment by Womble-TC** [comment]
Here is one made in the newest build which has the issue: 
[please fix.zip](https://github.com/tsunamayo/Skywanderers/files/2676921/please.fix.zip)

**Comment by Womble-TC** [comment]
If there is any way that the blueprint can be "fixed", let me know.

**Comment by gmunga5** [comment]
I find that the ability to actually place blocks on hinges can be temperamental. Sometimes you will play and it will work out fine, other times it won’t allow you to build on the hinge. From what I have seen it doesn’t matter if it is a new or old blueprint but there doesn’t seem to be anyway to tell if it is working or not without doing it.

**Comment by tsunamayo** [comment]
I fixed a bug today that I think should explain this one. I loaded the blueprint and I was able to build on new hinge and delete hinge without issues. Very nice build by the way ;-)
