### ISSUE TITLE
[BUG] Child entities do not save in their correct place (sometimes)

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1029]
### Short Description of the issue:

This can be quite hard to replicate, but saving and reloading a ship with a child entities can cause
the child entities to move to a different location. This also usually causes the child entities to become un-intractable.

### Steps to reproduce the issue:

-Make a ship that uses child entities
-Save the ship
-Reload the ship
-See if child entities have been removed.

Here are some examples after reloading: 
Some child entities remain the the correct place... 
![image](https://user-images.githubusercontent.com/29961381/49836576-180c0800-fd9b-11e8-899d-908f8ca0c5e1.png)
However, some move to a set location, and cant be interacted with or even destroyed.
![image](https://user-images.githubusercontent.com/29961381/49836610-3bcf4e00-fd9b-11e8-8999-653d8eca1a0f.png)

### Environment
- Skywanderers version: Experimental 
- Graphics Card: 970

(I can give you the blueprint if you wish to look at this further, as it can be difficult to consistently replicate)

**Comment by tsunamayo** [comment]
I think this bug should have been happening in latest build, I changed the way children entity are indexed to make it more robust. Tell me if it was not the case and you still see some issues! Cheers
