### ISSUE TITLE
[Bug] Placed brick with another off of the first brick. No spot to build off of on the newly placed brick.

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#103]
I placed one brick with another behind it, removed the first one and now there isn't a spot to build off of on the newly placed brick (The brick next to the one missing a building spot is just for reference)
![untitled](https://user-images.githubusercontent.com/32974671/31859044-492e8a60-b6cb-11e7-953f-93343b3789a2.png)

**Comment by tsunamayo** [comment]
This is normal, it is because that spot is taken by the brick itself. There cant be studs on the bottom on the brick where you placed it.
