### ISSUE TITLE
[SUGGESTION] Transparent colour option for new pattern painting.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#1031]
As the title says, if we could pick a transparent colour to allow the natural colour of the block to be the background, this would be a great quality of life change instead of having to remember RGB codes. This would also make using the patterns negatively easier too.

**Comment by Garrett-C** [comment]
You could just use the colour of the base block...

**Comment by schlid** [comment]
i'm not about that life mr munga.
