### ISSUE TITLE
[Bug] Hollow Panels Hitbox and Deletion Issues

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1032]
There are actually two issues with the new hollow panels.
First, when trying to walk over them, you go up and over it as if it was convex, instead of sinking down.
Second, when trying to delete the hollow panel, it deletes the block under it. Afterwards, if you then delete the hollow panel and replace the block under it, it makes square that you can see through blocks with.

- Skywanderers version: 18w50a
![711980_20181213201848_1](https://user-images.githubusercontent.com/26584892/49979511-fc2c7180-ff14-11e8-8c93-1c99593bdca5.png)

**Comment by tsunamayo** [comment]
Ah yes sorry, I wanted to remove it from the codex as it was just a test for now, havent really spend much time on this yet. Thanks

**Comment by tsunamayo** [comment]
Ok fix is uploaded. Thanks
