### ISSUE TITLE
Some Testing Features Got Left In

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1033]
There are a couple of items in the codex that don't seem to belong there, those being the AI Tool and the Crew Order Tool. They show up as white boxes in the menu.

- Skywanderers version: 18w50a 
![711980_20181213201845_1](https://user-images.githubusercontent.com/26584892/49979626-7b21aa00-ff15-11e8-8a5b-e36c8f33664a.png)

**Comment by tsunamayo** [comment]
Yes sorry haha, it was also some experiments from a long time ago, I will remove them from the codex. thanks

**Comment by tsunamayo** [comment]
Ok fix is uploaded. Thanks
