### ISSUE TITLE
[EXPERIMENTAL] Artefacts linked to Max building length.

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#1034]
Hello!

The maximum building length seems to have been updated with yesterday's update. It was previously at 17 and is now at 16.

That seems to create issues with the pre-existent builds that have 17 blocks long parts made out of slopes where said parts are divided such as:
Port side: 17 became 16 + 1 and an artefact is automatically created above the +1.
Starboard side: 17 became 1 + 16 and an artefact is automatically created above the +1.

Which bring us to such a situation: (on the bottom left, the last line has been replaced by multiple single slopes)
![image](https://user-images.githubusercontent.com/33256107/50004278-0434f180-ffa7-11e8-8d8d-77326c74da26.png)

While talking about the max building length, could we build longer lines as we were able to, and see a come back of the counter on the bottom of the screen, please?

Cheers, Name11ess.

**Comment by tsunamayo** [comment]
Yes really sorry for this one, this is unfortunately normal, I had to indeed limit the max stretch to 16.
If you want a more detailed reason: I had to do a refactoring of the way I store block for the paint/stencil update. I had to limit the maximum length to fit into the new format. 16 is 2^4, 17 was a bit wasteful as it required 5 bits, and space packing is really limited in the chunk data...
In case of full block there is no impact but for wedge there is. I hope it does not impact your build too much, sorry if it does... Cheers

**Comment by Name11ess** [comment]
Thank you for the answer @tsunamayo !

1/ Could it be possible to have a higher value for the max strech to allow the building of larger ships to be faster (32?).

2/ Could we see the comeback of the block counting that we used to have when stretching blocks?

**Comment by tsunamayo** [comment]
Hi! 
1) so unfortunately I had to put this limit, so it is not likely I will change it. 32 takes 6 more bits in the block index, which is a lot (3 dimensions for size and offset parameters). I made a lot of design choice not for larger ship but more for detailing, interior with gameplay in mind.
2) yes for sure I will add it back!

**Comment by Name11ess** [comment]
Thank you for the answers, have a good afternoon !
