### ISSUE TITLE
[Suggestion] Paint toggle

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1035]
### Short Description of the issue:
Allow a toggle option in the paint menu that switches between painting individual faces of a block and painting the entire block. While painting each face is amazing and useful, it isn't always needed and having to paint each face the same color takes a lot longer.
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
I agree it is definitely slower, but I think now it is painful because you are used to the older way. For large flat surface it should be the same though.
I will think if/how I can do this, as the problem is that it dont really work nicely like that in the code.

**Comment by gmunga5** [comment]
I do agree with tom it would be nice to be able to paint a whole block. For example if you are painting something that is 1 block thick and you can see 3 or 4 faces of it like say a wing or wingybit then you would need to paint the same block the same colour 3 or 4 times which is a massive pain. I noticed that when you paint bricks the whole brick paints. I imagine it’s a result of the different systems in place there but could it potentially be possible to find a way to use that or something. No ideas on how it works just spitballing.

**Comment by tsunamayo** [comment]
Yes the tech is different. For bricks the paint information is baked into the vertex (the geometry information). For block, as now a block can stretch over several voxel and I still wanted to allow you to paint per voxel, the paint info is looked depending on the surface position. I will see if I can do it neatly in code and UX. Thanks!

**Comment by tsunamayo** [comment]
So I removed the single face paint feature. Now you paint full voxel as before, I am actually happy as it is much simplier in code. You must use a stencil to paint a full face - so it will be a bit slower. I was reluctant to do this at first to not have a high number of stencil but it seems you guys wont use this that much, and I will increase the limit also. Thanks!
