### ISSUE TITLE
hot bar selection issue

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1036]
### Short Description of the issue:
After adding a new item to the hotbar, if you use a number key to switch to a different slot it replaces the slot you selected with the newest added block. It does this across all hotbars and with any/all slots you select with number keys.
...

### Steps to reproduce the issue:
Fill your hot bar with items, replace one of the items with something else, then press a number key in order to switch to a different hotbar slot.
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, does the test case look like this? 
https://github.com/tsunamayo/Skywanderers/issues/1040

Have slot x selected
Add different items to slot x and slot x+1
Close codex
Press x+1 to access that slot
Item in x+1 becomes the same as item in x.

Thanks!

**Comment by Tomatart** [comment]
Yes that is exactly it.

**Comment by tsunamayo** [comment]
Cannot reproduce the issue. Thanks
