### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#1037]
### Short Description of the issue:
Since the update I have been unable to play Skywanders. There is no lag when I load up the game, but as soon as I load a world there is so much lag that it nearly crashed my computer

### Environment
- Skywanderers version: 18w50b
- Graphics Card: GTX 1050 TI

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2682977/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for reporting the issue, sorry to hear that. How many FPS are you running at? 
Could you please send me your save folder?
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data

**Comment by TheCuriousSkeleton** [comment]
I am unable to send the file on GitHub as the file type inst supported. To send it to you via Git hub I would have to send what I can assume to be more than 100+ files.

**Comment by TheCuriousSkeleton** [comment]
This issue is still a problem in version RotC

**Comment by tsunamayo** [comment]
Hi, could you please tell me the following:
 - Processor and RAM spec.
 - Can you backup your save folder - and then delete it to start a fresh world?
 - You can send me your save backup by simply zipping all the files, no need to send all the file one by one.
Thanks!

**Comment by TheCuriousSkeleton** [comment]
- Intel Core i5-4440 CPU @ 3.10GHz and 8GB of ram

- [Skywanderers.zip](https://github.com/tsunamayo/Skywanderers/files/3218238/Skywanderers.zip)

I think that is everything.

**Comment by tsunamayo** [comment]
I think it could be linked to your PC running out of RAM - as your GFX card
have a lot of RAM compared to the system.
Could you look at your RAM usage when starting a new game?
Thanks

**Comment by TheCuriousSkeleton** [comment]
When loading a world, less than 50% of my memory is being used, but 100% of my disk is.

**Comment by tsunamayo** [comment]
hey sorry @TheCuriousSkeleton as I saw you are still being active, I just want to confirm if you saw that issue again or not? Thanks

**Comment by TheCuriousSkeleton** [comment]
No everything is running fine, I’m getting 60+ FPS

**Comment by tsunamayo** [comment]
Ok great!
