### ISSUE TITLE
Update on Stream

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1038]
This is just a question about if another Q&A is planned. You replied to the forum post that there was a Q&A planned after the big update about a month ago. I know that many of us, myself included have quite a few questions about the game and future developments.

https://www.skywanderersgame.com/forum/viewtopic.php?f=5&t=41937
![tsuna1](https://user-images.githubusercontent.com/36980446/50048485-2142f080-008b-11e9-9016-6b335abb9c8a.png)

**Comment by tsunamayo** [comment]
Sure you are right, I am flying back to check out the familly so lets do something toward the beginning of the year! Cheers

**Comment by tsunamayo** [comment]
Q&A was done after that, I could do another soon if you want also. Thanks!
