### ISSUE TITLE
everything turned pink

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1039]
### Short Description of the issue:
after activating drone, the entire project turned pink, all lights, engine colors reactor lights, the lot. 

Only the default colour was changed. Paints that had been applied post update were fine.
...

### Steps to reproduce the issue:
activate a drone mirror
...

### Environment
- Skywanderers version: Experimental (Paint update)
- Graphics Card: rx vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684469/output_log.txt)
![20181214031335_1](https://user-images.githubusercontent.com/14081996/50066498-1a8ea900-0171-11e9-9b83-787e15b7f19a.jpg)
![20181214013613_1](https://user-images.githubusercontent.com/14081996/50066506-1e223000-0171-11e9-9b92-0088c56a6ccd.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi! So I cant reproduce this issue. It seems there is a few issue with your build, could you please send me your save file? Not sure if it is related to that, but this is the only issue in the log.
Is there some specific step I might need to do to reproduce? Thanks

**Comment by pinesh** [comment]
Thanks for getting back to me so quick! it seems at least 3 others have had the same issue. has something to do with painting old builds in new colours then loading it up then using the drone.

anyway, here is my save, since everything was still pink last time I checked 
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/2688665/Save_Data.zip)
this should help.

**Comment by tsunamayo** [comment]
Okay it is a really weird one, I still cant reproduce though. I will keep you posted!

**Comment by pinesh** [comment]
i have a potential coding idea as to why it is happening. could the screen where you can view the current entity and drag it around, be somehow conflicting with the color spectrum slider? they are sorta in the same place, maybe the drone or entity preview screen are using the same code? maybe the player is interacting with both?

**Comment by tsunamayo** [comment]
Okay I fixed the issue, yes you where right it was the paint customization that was active in the shadow. Also it was overriding the paint 0, which is the default paint that should not be customizable, so I made fix so this color is restored to its bluish gray glory instead of pink. Thanks!
