### ISSUE TITLE
[Suggestion] Hold right mouse button and drag to move hinges (Instead of sliders, etc)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#104]
Using sliders and values works just fine but this might speed things up a bit for people :)

**Comment by Bejasc** [comment]
+1

**Comment by tsunamayo** [comment]
I see you guys are already using hinges too much haha! But more seriously it is a design issue on the technical side, having super fast hinge setting would mean "go ahead, put as many as you want - they are free", which they are not.

**Comment by Xerma** [comment]
Yea you have a point. Building ships shouldn't be based on loads of hinges
