### ISSUE TITLE
hotbar duplicates slection

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1040]
### Short Description of the issue:
sometimes when changing bar, after placing an item in from the codex, that item will replace whatever number I press next to change the current block, 
...

### Steps to reproduce the issue:
mess around with codex
...

### Environment
- Skywanderers version: Experimental (pre-paint and post paint update)
- Graphics Card: Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684474/output_log.txt)
)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, not sure to understand exactly the test case, if you could detail me so I am sure I am doing it okay:
1) change bar
2) place item X in row
3) ect ...

Thanks for your help!

**Comment by gmunga5** [comment]
Yeah I have noticed this myself. It’s kind of an odd one to try and explain. When it has happened to me it generally goes like this.

1. Have slot x selected
2. Add different items to slot x and slot x+1
3. Close codex
4. Press x+1 to access that slot
5. Item in x+1 becomes the same as item in x.

It’s odd though because I haven’t got it to work everytime.

**Comment by tsunamayo** [comment]
Hum I cant reproduce this one, is it something you get often? Thanks

**Comment by pinesh** [comment]
yeah, it happens very often, unless I am careful with scrolling through the hot bar and pressing numbers after replacing an item in there, it happens every time. i will see about recording it happening for you

**Comment by pinesh** [comment]
hello! sorry i didn't capture the moments leading up to it, i think i tried placing something from the codex onto my hotbar then pressing a number for a slot caused it to switch, here is a video that better shows it.
[Skywanderers 1_5_2019 12_38_23 AM.zip](https://github.com/tsunamayo/Skywanderers/files/2729341/Skywanderers.1_5_2019.12_38_23.AM.zip)

**Comment by tsunamayo** [comment]
Cannot reproduce the issue. Thanks
