### ISSUE TITLE
Placing certain stencils causes game crash

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1041]
### Short Description of the issue:
After placing the line stencil my game immediately froze, it failed to crash as I had to force close.
I saved after placing it the first time and as a result, when I tried to load in the game, it froze again. 

it happened again when i tried the corner but did not happen with the hazard paint.
had to delete save entirely.

attached is that broken save data.
...

### Steps to reproduce the issue:
place a line stencil or try to load save data
...

### Environment
- Skywanderers version: Experimental (Paint update)
- Graphics Card: Vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684479/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

[broken save.zip](https://github.com/tsunamayo/Skywanderers/files/2684478/broken.save.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi @pinesh ! Did you had still trouble in the latest version of the game? Thanks!

**Comment by tsunamayo** [comment]
Hi, this issue should now be fixed as decals tech has been replaced. Thanks!
