### ISSUE TITLE
Placing a rotor breaks game

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1042]
### Short Description of the issue:
placing a rotor will cause you to be unable to break or place blocks until restart.
...

### Steps to reproduce the issue:
place a rotor
...

### Environment
- Skywanderers version: Experimental - Pre Paint
- Graphics Card: Vega 56
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684480/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Thanks, issue is fixed! Cheers
