### ISSUE TITLE
Hinge teleports to origin on restart, becomes invincible

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1043]
### Short Description of the issue:
Placed a hinge on a ship, on load in I found it had teleported to the origin and become invincible.
...

### Steps to reproduce the issue:
place a hinge somewhere, get it working then save and reload the game a few times.
...

### Environment
- Skywanderers version: Experimental -Pre Paint (broken hinge still there post paint)
- Graphics Card: Vega 56
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684484/output_log.txt)
![20181210182324_1](https://user-images.githubusercontent.com/14081996/50066809-ba006b80-0172-11e9-9368-58cff8ac986a.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by pinesh** [comment]
ship blueprint()
[broken save (2).zip](https://github.com/tsunamayo/Skywanderers/files/2684487/broken.save.2.zip)

**Comment by tsunamayo** [comment]
I think this issue should be fixed, as I fixed today an issue regarding children entity on that exact same ship. Thanks for reporting all the issue lately! It is really usefull. Cheers!
