### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1049]
### Short Description of the issue:
game froze and promptly crashed.
...

### Steps to reproduce the issue:
not sure, 
...

### Environment
- Skywanderers version: Experimental Hotfix
- Graphics Card: Vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2697281/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by pinesh** [comment]
removed triangle stencils, havent crashed yet, might have tried to place a block on one

**Comment by pinesh** [comment]
can confirm, definitely has something to do with repeated stencil use, tried adding some onto a landing pad and not 5 mins later I experience the same freeze. once again I reverted to an earlier build, removed them and haven't had another crash,

Unsure of the cause but it seems to happen on trying to place a block.

**Comment by tsunamayo** [comment]
Hi, this issue should now be fixed as decals tech has been replaced. Thanks!
