### ISSUE TITLE
Child entity spawn glitch

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#105]
![image](https://user-images.githubusercontent.com/25937107/31860761-a10340c2-b717-11e7-824c-a82cc844fb47.png)
Sometimes when you load a saved ship some of the child entities will spawn copies of themselves around the middle of the ship.

**Comment by tsunamayo** [comment]
Thanks for reporting the bug! Could you please also give me your blueprint to see if I can reproduce?

**Comment by gmunga5** [comment]
[PlayerEntities.zip](https://github.com/tsunamayo/Skywanderers/files/1405244/PlayerEntities.zip)
One of those 2. I think MK 1 should be it.

**Comment by tsunamayo** [comment]
Deprecated. Thanks!
