### ISSUE TITLE
[BUG]Paint number input number is incorrectly inputted

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1052]
### Short Description of the issue:
Numbers are incorrectly registered when typing in the digits. into the paint tool with the number 4 impossible to use. 

For example, 

Setting R FIRST #
typing 0 enters 0
typing 1 yields 0 <---ISSUE
typing 2 enters 1<---ISSUE
typing 3 enters 2<---ISSUE
typing 4 enters 3<---ISSUE
<4 not possible>
typing 5 enters 5
typing 6 enters 6
typing 7 = 7 and so on till 9

this causes issues on all other numbers following the first, removing the last digit from a 2 digit number will change the remaining digit if the digit was any of the mentioned issue keys.

for example, if the number 31 is entered (by having to press 4 and 2 ) when the 1 is removed, the 3 will change to a 2. 

<MY EXPECTATION FOR BUG CAUSE>

Code for inputing the keys was probably copy and pasted and you forgot to change the number it passes into the paint customiser for at least 4 keys. (at least thats what i think you might have done based on bug behaviour)

I belive this because you are re-using the input numbers code and the number that is left is put back into the system as a new number coming from the corresponding key press. thus the 3 that is left is treated as though someone entered 3. this returns it as 2 due to the bug.  

...

### Steps to reproduce the issue:

follow my example in the above section.
for example, if the number 31 is entered (by having to press 4 and 2 ) when the 1 is removed, the 3 will change to a 2. 
...

### Environment
- Skywanderers version: Experimental (Paint Hotfix)
- Graphics Card: Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Skywanderers 12_20_2018 5_44_38 PM.zip](https://github.com/tsunamayo/Skywanderers/files/2701184/Skywanderers.12_20_2018.5_44_38.PM.zip)
(video footage of bug)
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2701188/output_log.txt)

**Comment by Tomatart** [comment]
Can confirm this is still an issue in the latest patch as of December 22nd.

**Comment by pinesh** [comment]
bumping since it is still a pain to deal with

**Comment by tsunamayo** [comment]
Okay fixed. It was artifact from a RGB <-> HSV conversion. Cheers
