### ISSUE TITLE
[BUG]Painting lights doesn't use correct light

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1053]
### Short Description of the issue:
as the title says, lights do not correspond to colour properly. for example, painting light with 255 255 255 white will turn it red, black will turn it pink. while the middle colours seem to work ok, white or gray is not possible to achieve.

the light emitted from the light will also not change color when the actual light color is adjusted,

as shown by the attached video

...

### Steps to reproduce the issue:
play around with light colour, as shown in the video.
...

### Environment
- Skywanderers version: Experimental Paint post hotfix
- Graphics Card: Vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2701225/output_log.txt)
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[Skywanderers 12_20_2018 6_03_17 PM (2).zip](https://github.com/tsunamayo/Skywanderers/files/2701222/Skywanderers.12_20_2018.6_03_17.PM.2.zip)

**Comment by tsunamayo** [comment]
Okay I fixed the issue, thanks!
