### ISSUE TITLE
[BUG]Blocks painting adjacent blocks 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1054]
### Short Description of the issue:
painting a block in all video recorded cases doesn't only paint that side or (in the case of the pipe) painting an adjacent block side is the only way to paint the target block.

...

### Steps to reproduce the issue:
repeat steps that were taken in the case video.
...

### Environment
- Skywanderers version: Experimental (Paint post hotfix)
- Graphics Card: Vega 56

### Additional information:
[CASE 1.zip](https://github.com/tsunamayo/Skywanderers/files/2701245/CASE.1.zip)
[CASE 2.zip](https://github.com/tsunamayo/Skywanderers/files/2701246/CASE.2.zip)
[CASE 3.zip](https://github.com/tsunamayo/Skywanderers/files/2701247/CASE.3.zip)

_(Screenshots, Videos, Error logs, Related issue
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2701230/output_log.txt)
s)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Tomatart** [comment]
![screenshot 359](https://user-images.githubusercontent.com/26846110/50379086-05dc6600-05f4-11e9-8509-91a428cd689e.png)
Same issue here, painting either circled face paints the other face as well.

**Comment by tsunamayo** [comment]
Thanks. It kinda sucks a bit, this case is indeed a case where the paint system will break. I can add a special stencil to deal with this case or remove the side painting entirely as it seems people are unhappy about it. 
I need more thinking on the best approach. 
I added the feature so that people dont have to use a square stencil everywhere to get side paint which could have them run out of stencil quickly.

**Comment by ProPeach** [comment]
Overall players are very happy with the side painting, no other comparable game has this feature (as far as I'm aware) and it opens up loads of new opportunities. Some have issues with the speed of painting now however, as it can be a lot slower go when you want to paint multiple faces of the same block the same colour. As others have suggested, a way to easily switch between the two modes would be ideal, perhaps by holding a keybind, or an area paint tool. These are more quality of life tools than necessity I think though, so it's understandable if they're not top of your list.
Thanks for considering our ideas as always o/

**Comment by tsunamayo** [comment]
So I removed the single face paint feature. Now you paint full voxel as before, I am actually happy as it is much simplier in code. You must use a stencil to paint a full face. I was reluctant to do this at first to not have a high number of stencil but it seems you guys wont use this that much, and I will increase the limit also. Thanks!
