### ISSUE TITLE
[Suggestion] [Feature Request] New Stylish Stickers?

### ISSUE THREAD

**Issue by GadyZ** [tsunamayo/Skywanderers#1055]
![stickers](https://user-images.githubusercontent.com/19417832/50323098-20a0c480-04a6-11e9-8b24-0b766eb73407.png)
Hey tsuna. Hope you're doing well. I wanted to suggest these two types of stickers to add some very stylish futuristic tactical punctured ventilation holes.

**Comment by tsunamayo** [comment]
Yes you are exactly right this actually what I want to add and much more. I will actually drop the idea of having different style for hull. 
Style will now come from stencil and pattern (hull line = pattern), I think it will give more freedom and wont force the player to use a specific hull block just for the look. Also you guys will have much more freedom.
Hull look will be more gameplay driven:
texture + border look = armor rating
slight hue = crafting recipe
What do you think of the new approach? Cheers

**Comment by schlid** [comment]
It'd be nice if the hue could be applied after building a la the current paint. This was a big limitation with starmade and other games as if you wished to recolour a ship you'd have to break and replace every individual block - forgive me if I've misunderstood the hue as something in addition to current "paint"

**Comment by tsunamayo** [comment]
So I havent had time to make all the variations I wanted but I have the tech in place, and an update with more stickers is coming soon. They are normal based and fit well in the new graphical style. Cheers
