### ISSUE TITLE
[Suggestion] Give the ability to stretch bricks further/alternative shapes

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1056]
Just a suggestion, do you think it would be possible to stretch the bricks beyond 2 blocks (maybe raise this to 4) to allow more subtle slopes and angles.
However, if this limit cannot be raised, how about a brick alternative to this shape: 
![image](https://user-images.githubusercontent.com/29961381/50357861-53eb5e00-054f-11e9-8d03-298d3426cd9d.png)
preferably including it corresponding corner counterparts

**Comment by Womble-TC** [comment]
(When I say brick alternative, I mean a brick wedge 1 brick long, and half a brick tall)

**Comment by ProPeach** [comment]
I fully support a 4m max brick length. This would bring it in line with the max block length max of 16 as both would have a maximum slope ratio of 1/16. For reference, the beautifully subtle slope of the X Wing nose is exactly a 1/16 slope ratio

**Comment by tsunamayo** [comment]
4m stretch make sense, I like your arguments, it make it 1:4 of blocks which is the implicit rule with bricks. I could make it work indeed, I will work on that. I will see for the half width, thats something I could add also. Cheers

**Comment by tsunamayo** [comment]
Okay 4m limit has been in the game for a bit now. Thanks!
