### ISSUE TITLE
Symmetry no longer applies paint

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1057]
### Short Description of the issue:
When using symmetry paint will not mirror.
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay pretty bad bug, unfortunately I am visiting family so fix will have to wait a bit...
I keep you guys posted.

**Comment by tsunamayo** [comment]
Okay actually I removed the singe face paint feature. Code is simplier and you guy can paint as fast as before. To paint a single face I will add a full quad stencil, so it should be all good in case you need single face. This issue is fixed, cheers!
