### ISSUE TITLE
Brick Border Removal

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1058]
### Short Description of the issue:
Brick boarder texture

### Additional information:
Lot of us building with the bricks are rather annoyed with the borderon the brick textures. Makes the ships look... well like bricks and not a smooth texture which it should be. Here is a small brick-made ship by Bruce. The top one is the un-edited picture. The bottom is an edited version of what the ship would look like without the brick borders. A clear improvement over the former.

The only plus side of the borders are that it makes a good brick texture. Perhaps remove the border for bricks, but add a paint-texture of the border. Like the camo texture

![boarder21](https://user-images.githubusercontent.com/36980446/50462297-8fb46800-0941-11e9-8250-352f0f9ef945.png)

**Comment by BruceLeedleLeedleLeedleLee** [comment]
I think my ship (and probably many other projects, be it interiors, mechs, or just a bit of greebling) could profit a lot from that. its irritating to paint something a dark tone, and have this tiley white border everywhere. Ships shouldnt look like they are made from plaster plates.

**Comment by tsunamayo** [comment]
Yes I agree it is not looking good. I wanted a border mainly so that player dont stack an orgie of bricks like I saw on several build but instead use the stretch feature.
I will try to make them more subtle, if it still crappy I will remove them entirely.
Second picture is not possible though, bricks are not aware of neighbor bricks, so it is no borders or border everywhere unlike blocks. Cheers

**Comment by tsunamayo** [comment]
Okay border look changed as it is now more normal base, but I will still tone down the border a bit once you send me some build so I can have a better idea of how bad it is @ZachZent @BruceLeedleLeedleLeedleLee . Thanks!

**Comment by tsunamayo** [comment]
Okay I hope you are okay with the new normal based system. Thanks
