### ISSUE TITLE
Multi Mirror Axes (When will we get this feature back?)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1059]
This isn't so much a bug but I wanted to check and see if you have an idea when we might be able to have multiple mirror planes again. It was a very good thing to have and it would be a shame to see it gone forever.

**Comment by tsunamayo** [comment]
Yes symmetry sucks atm, I need to find a nice and elegant solution. Not sure for the multi plane, it is a nest of potential bugs, I am now super careful about this aspect now. I only want to pay that price for things that really matter, multi plane seems to be only for station building which is gonna be very different (I will update you on that).

**Comment by gmunga5** [comment]
Multi axis is really useful for ships aswell. A lot of ships are mostly symmetrical from left to right and at the top and bottom.

**Comment by ProPeach** [comment]
Agreed, many ships have multiple planes of symmetry, it's an extremely useful tool in cutting down build time significantly.

**Comment by tsunamayo** [comment]
closing this as duplicated of #1555. Thanks
