### ISSUE TITLE
Canopy Wedge Slab Doesn't Mirror Correctly

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#106]
As seen in the picture, the mirror doesn't work correctly on this block, or the hull variant of it.
![2017-10-22](https://user-images.githubusercontent.com/26584892/31868453-b412d1f8-b764-11e7-857d-30ebbabb29e6.png)

**Comment by tsunamayo** [comment]
Ah indeed make sense, and it will be a bit painful to fix, I will keep you posted when I do this!

**Comment by tsunamayo** [comment]
Deprecated now. Thanks!
