### ISSUE TITLE
[Suggestion] Enhancing the small canopies

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1060]
![image](https://user-images.githubusercontent.com/29961381/50548169-f6869980-0c3f-11e9-8188-69a6a535b610.png)
To make these canopies more useful, maybe give them the ability to stretch. Also, giving these bricks a corner brick/canopy in the same size would help builders make more detailed canopies for small ships.

**Comment by tsunamayo** [comment]
Yes for sure I will add more. Believe it or not canopy have been the hardest blocks to make, I must have tried half a dozen approach already, but you guys deserve the best possible canopy :p

**Comment by tsunamayo** [comment]
So we now have new windows tile. Thanks!
