### ISSUE TITLE
[Suggestion] Max ship volume

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#1061]
So I think we all know that it is unavoidable that you plan to put a limit on the ship sizes at some point. This got me thinking, if you were to just set maximum dimensions like 500x400x400 or something then you are kind of limiting people to a certain ship shape. It could mean that for people to build an effective ship they have to build it a certain way which I think you want to avoid. As such I think a volume based limit could be slightly better. Taking the previous dimension I mentioned that would have a volume of 80,000,000 so if you were to make that the limit then there are various other configurations of sizes that can meet this limit. For example 1000x500x160 or 300x400x600 for examples. An approach like this could allow someone to build a long thin ship or a wide tall ship or anything like that. I don’t know how much it would take to code that but it the game already measures length, width and height surely volume should be a major issue to measure.  Just a suggestion to allow a fair bit of creativity in designs while still allowing you to set up a limit. 

One side note is that it might be nice to have the size limit be configurable for example in a config file. That way you could add some sort of warning saying “The game may not be optimised to handle ships past the current size limit.” Or something like that while still allowing people to change the limit if they want to risk it. You would be able to make your reasoning clear while still ensuring that people who want to risk it can. Granted the questions would then be things like is it applied to servers etc. One other benefit would be if someone wanted to run a server where people have to use smaller ships they could. Another thing is you would be able to just change the default value fairly easily if your recommended limit changed down the line.

**Comment by tsunamayo** [comment]
So I need a fixed size because we will build inside shipyards, shipyard having a maximum size.
Also it is for career mode, I will give no such limit for creative (there still might be a technical limit of some sort after graphic optimization, but limit would be much higher). And in career mode you need to earn each block, so ship of these size would be for very late game ship, not everybody would have time and commitment to build one.

**Comment by gmunga5** [comment]
True. I guess it would depend on things like how the shipyards are built i.e are they kind of dry dock esc or are they more just an empty space. So if you build a ship in creative would there the any way to construct it in survival and if so does that mean that there won’t be any way to bring in your bigger creative ships to survival? I understand and agree that ships like these would be late game but if you imagine a large faction on a multiplayer server could create a 1k ship without it being some impossibly consuming task. We did have some ideas for perhaps some super rare maybe like 4 in a game or something shipyards that could say build 1k maybe 1.5k ships but they would maybe have a limited number of uses or maybe would need some really rare resource to power them. Now obviously these super shipyards could be a feature later in the dev cycle when more optimisation has been done etc. The idea of them was to add some extra exploration and gameplay elements with the possibility of larger ships however keeping the number of large ships lower. Kind of just an idea.

**Comment by tsunamayo** [comment]
1.5km is 64 time bigger than 500m... I dont think that would be possible performance wise.

**Comment by gmunga5** [comment]
I mean honestly I think it can technically handle a 2k ship fine atm, granted that’s with nothing else happeneing. Not to mention that was just a value I picked out. If there were only 10 of them in the galaxy I think the game would handle quite well tbh. Sure if they all bring them to one system there could be issues but that’s their choice. I think players will want to dream big so adding a really rare spawning structure that allows them to do that, even if it’s got a limited number of uses, would add a reason to explore. Limiting survival ships to 500 just kind of feels like a slap on the wrist to anyone wanting to go bigger. What if a group decided their goal  in the game was to build something insane in survival like a 1km ship, a 500m hard cap that has no way to be adjusted kind of kills that possibility.

**Comment by tsunamayo** [comment]
So at the end the limit will be equal on all side, so people dont feel limited by the form factor.
Ship over the maximum shipyard limit will be called "mothership", and will have a special place in the gameplay, they wont be serviceable in normal station. But I will find a way to make them possible, if you have any ideas. Cheers
