### ISSUE TITLE
Game crashes when trying to load blueprint with hinge

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1062]
### Short Description of the issue:
so yeah, can't spawn this ship in though others don't seem to have an issue with it, I have had to have people remove hinges so I can spawn it myself, 

video of the crash is in the zip

the issue is not world related as i loaded up tomatarts world too. i could use it fine until i looked at where that ship was. even if it was behind a wall my game froze in the same manner. (some sort of rendering issue?)

EDIT - when trying to find the blueprint, I found I

 was able to load it just fine. don't know what has changed since the 31st of December but the blueprint is no longer crashing my game.
...

### Steps to reproduce the issue:
be me
spawn it in
enjoy the crash
...

### Environment
- Skywanderers version: paint hotfix (Dec 2018)

- Graphics Card: Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
THE BLUEPRINT
[Tsuna_shuttle_done.zip](https://github.com/tsunamayo/Skywanderers/files/2729360/Tsuna_shuttle_done.zip)

[Skywanderers 12_31_2018 11_48_42 AM_Trim.zip](https://github.com/tsunamayo/Skywanderers/files/2729343/Skywanderers.12_31_2018.11_48_42.AM_Trim.zip)

don't know if this is the same crash but it is A crash

[Crash_2018-05-29_172928.zip](https://github.com/tsunamayo/Skywanderers/files/2729344/Crash_2018-05-29_172928.zip)

don't have an output from crash
but here is current
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2729345/output_log.txt)
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, sorry for only spotting this now... I tried the ship and it is loading in latest patch. Nice to see my little shuttle in an updated version ;)
Thanks!
