### ISSUE TITLE
[SUGGESTION] Brick Offests (0.125m, 0.06125m)

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1064]
With the game moving on from the old stud based system, we lost the ability to place bricks in increments of a half, quarter and eighth of a brick. These were an incredible tool in elevating brick builds that one step further, and the lack of a way to center bricks to the middle of a block especially is challenging. Here's an example in the old stud system, some bricks offset in steps of a quarter brick:
![studs](https://user-images.githubusercontent.com/27857711/50866746-256ce000-13a3-11e9-9b99-84aefb717377.png)
These bricks (4 to 1, 2 to 1) also have no use in the new, studless system, as they no longer offset bricks:
![studless](https://user-images.githubusercontent.com/27857711/50866751-2ef64800-13a3-11e9-84d4-24cdd7b76443.png)

(The 4-to-1 looks correct, but that's only because that brick itself is misaligned when placed)

 We'd really love a way to offset bricks in the new studless system, and hope to hear your reply : )

**Comment by tsunamayo** [comment]
Okay this will be finally back in 19w28a, albeit with only a half brick increment, which hopefully is a good ratio between freedom / complexity. Thanks!
