### ISSUE TITLE
[Suggestion] Increase freeform line limit from 16 to 20

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#1065]
### Short Description of the issue: 17 to 16 screwed up a lot of my builds. Especially with angles. Could increasing from 16 to something higher be feasible? 16 seems short too.

...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: RTX 2080 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, sorry I am only seeing this now. Actually the limit is build in deeply the data structure, so unfortunately it is not really possible to change it. Also there is a bunch of other factor linked to the fact that bricks / blocks belong to a chunk, and changing them to a high value would be less optimum in some regards. Thanks!
