### ISSUE TITLE
Pipe placement

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1067]
### Short Description of the issue:
The new pipe model doesn't allow adjacent placing of more pipes.
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![screenshot 389](https://user-images.githubusercontent.com/26846110/51367204-410c7080-1a9e-11e9-9a53-5a664b30a32b.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
That issue was fixed some time ago. Thanks!
