### ISSUE TITLE
[BUG] Load menu shows "Spaceship 1" for all available files

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1068]
The Load menu does not show the actual ship name, just "Spaceship 1"
![image](https://user-images.githubusercontent.com/27857711/51426925-12e77780-1be9-11e9-9e8a-07f7e2edbb67.png)

How to reproduce:
Spawn the drone with F5
Enter the Load menu

Environment
- Skywanderers version: 19w03a
- Graphics Card: GTX 1050M

This log shows me loading up the game, then loading a ship that was called Spaceship 1 in menu, but A-Wing in the files.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2775545/output_log.txt)

**Comment by ProPeach** [comment]
Seems like this has been reported already as issue #990, if there's anything else that could help you solve this I'd be happy to oblige.

**Comment by tsunamayo** [comment]
I remember having fixed this  bug a while ago. If not please dont hesitate to tell me! Thanks!
