### ISSUE TITLE
The game crashes at startup

### ISSUE THREAD

**Issue by Xenaxgen** [tsunamayo/Skywanderers#1069]
### Short Description of the issue:

The game crashes at startup after the unity splash screen

### Steps to reproduce the issue:

1.Start the game

### Environment
- Skywanderers version: v17w45o2
- Graphics Card: NVIDIA GeForce 615

### Additional information:

[error.log](https://github.com/tsunamayo/Skywanderers/files/2785613/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2785614/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/2785615/error.log)

**Comment by tsunamayo** [comment]
Is it working on newer version? Also your gfx card is very old and low weak, below recommended specs. Thanks
