### ISSUE TITLE
[Experimental] [BUG] Invisible/not placed stretch blocks

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1070]
Short Description of the issue:
     Stretch blocks will either be non existent or partially existent yet invisible.
...

Steps to reproduce the issue:
     -From a build place a block
     -Stretch the block to its max (I was using 2x3x16)
     -Block will be in one of three states:
             -completely invisible with a few block outlines (not fully encompassing the blocks entirety)
             -Not placed (unable to tell if block is just invisible or even placed at all)
             -Placed in its entirety
...

- Skywanderers version: 19w03a
- Graphics Card: GeForce GTX 1080TI

Additional information:
      Each screenshot should be in order of: 
            -CLICK, 
            -press Q and expand, 
            -STRETCH, 
            -PLACE
            -Check to see if placed at all

![20190123094150_1](https://user-images.githubusercontent.com/45324484/51619439-f2bffd00-1ef5-11e9-9d03-b46aba99ff69.jpg)
![20190123094153_1](https://user-images.githubusercontent.com/45324484/51619440-f2bffd00-1ef5-11e9-85b9-833ef60412c5.jpg)
![20190123094159_1](https://user-images.githubusercontent.com/45324484/51619441-f2bffd00-1ef5-11e9-8918-9418aefd0d82.jpg)
![20190123094205_1](https://user-images.githubusercontent.com/45324484/51619443-f2bffd00-1ef5-11e9-9a02-3803bda94b7d.jpg)
![20190123094220_1](https://user-images.githubusercontent.com/45324484/51619444-f2bffd00-1ef5-11e9-9ec1-1ebda1111da5.jpg)
![20190123094222_1](https://user-images.githubusercontent.com/45324484/51619445-f2bffd00-1ef5-11e9-9395-27a90046e543.jpg)
![20190123094239_1](https://user-images.githubusercontent.com/45324484/51619446-f2bffd00-1ef5-11e9-89cc-5146bfe8afb4.jpg)
![20190123094247_1](https://user-images.githubusercontent.com/45324484/51619448-f2bffd00-1ef5-11e9-9f3a-055b2b58662c.jpg)
![20190123094307_1](https://user-images.githubusercontent.com/45324484/51619449-f3589380-1ef5-11e9-85fd-1cae3aba3704.jpg)
![20190123094309_1](https://user-images.githubusercontent.com/45324484/51619450-f3589380-1ef5-11e9-89e8-7cfc9a0af753.jpg)
![20190123094317_1](https://user-images.githubusercontent.com/45324484/51619451-f3589380-1ef5-11e9-9cd4-d0f91405c98c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2788102/output_log.txt)

**Comment by TheCuriousSkeleton** [comment]
I've had the same trouble (when the game worked)
Skywanderers version: 19w03a
Graphics Card: GeForce GTX 1050TI

**Comment by Lsutehall** [comment]
I've seen this as well. The attached blueprint loads in with invisible blocks, (see attached screenshot), and I've also managed to force it to happen (along with drop of frame rate from ~120 to ~19 FPS) after placing a rotor block.

Version 19w03a, GTX1060

![20181226211104_1](https://user-images.githubusercontent.com/40872394/51630352-dc3f9300-1f41-11e9-83f5-8d04af5f6cb8.jpg)
![Uploading 20181226211104_1.jpg…]()

[type XT.zip](https://github.com/tsunamayo/Skywanderers/files/2788777/type.XT.zip)

**Comment by ZachZent** [comment]
Also has appeared when placing the starter block

**Comment by JRL101** [comment]
Im having an identical issue, but i cant figure out why its happening. Using the Wedge and stretching it in one of these spaces, then placing blocks within its space causes the sides to become transparent.

The "invisible block" seems to happen in specific grid locations. sometimes the block can not be deleted, some times it can, i can not find a consistency to the bug to be more specific.
This was not happening before the current version.

**Comment by Xerma** [comment]
I too have been having this issue lately. Hope it gets fixed in the next batch because I seriously can't build with this bug. Found this in my output.log so hopefully it sheds some light. I mostly suspect the grid not matching up how it should/hitboxes.

![asdfasfd](https://user-images.githubusercontent.com/32974671/52934133-29cdd680-331b-11e9-97f6-4d763bfdc0b8.png)

**Comment by JRL101** [comment]
Agreed its making building no fun. If building is possible with the invisi blocks getting in the way.

**Comment by JRL101** [comment]
This is weird.. I cant figure it out. 
![image](https://user-images.githubusercontent.com/33255536/53287583-20c88380-37b9-11e9-9be2-b7086887a2f8.png)

I pressed escape and clicked the [X] and it placed another block on the starting block but invisible, but then reviled part of the starting block...
![image](https://user-images.githubusercontent.com/33255536/53287596-55d4d600-37b9-11e9-8306-0bfeb8ca39c4.png)

Its like the side culling has gone crazy. But this is from the last patch for sure.

I deleted everything and anything just to try and get it working, but nothings changed. 
So heres a sequence of actions
![image](https://user-images.githubusercontent.com/33255536/53287610-96345400-37b9-11e9-94b2-0fdbd5566986.png)
![image](https://user-images.githubusercontent.com/33255536/53287611-a0565280-37b9-11e9-9e6e-4072f8612116.png)
![image](https://user-images.githubusercontent.com/33255536/53287614-aa785100-37b9-11e9-832d-3c4c154d9ed2.png)

As i clicked the X button it placed a block. its just weird this would suddenly make it work..

**Comment by JRL101** [comment]
![image](https://user-images.githubusercontent.com/33255536/53287637-0cd15180-37ba-11e9-8cd8-a8b10a070a13.png)
Sometimes deleting blocks brings them back.. but also makes them have no collision with placing other blocks inside the stretched shapes. 
![image](https://user-images.githubusercontent.com/33255536/53287657-5cb01880-37ba-11e9-9e4b-513039586943.png)
But then deleting the whole stretched shape deleted the blocks inside of it.

**Comment by JRL101** [comment]
Impossible to delete 
![image](https://user-images.githubusercontent.com/33255536/53287688-caf4db00-37ba-11e9-876a-36ae4e6c0f8e.png)
![image](https://user-images.githubusercontent.com/33255536/53287699-de07ab00-37ba-11e9-801c-1245b7b89f07.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2896880/output_log.txt)

**Comment by JRL101** [comment]
Any updates about this? everything seems extremely dead.

**Comment by tsunamayo** [comment]
Hey sorry guy I was busy with the gfx update. Is this something you still get in newer update? So many things changed on the tech side. I am cleaning up older issues. Thanks!

**Comment by JRL101** [comment]
Has Experimental been updated with the current or newer version?
19w24a Does not experience this bug.

**Comment by JRL101** [comment]
Considering how long its been since this version of the game i would say
its safe to close tickets older than 19w24a

**Comment by tsunamayo** [comment]
Okay issue closed then if you are no longer seing this! Cheers
