### ISSUE TITLE
building around rockets breaks character

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#1071]
### Short Description of the issue:
it seems when trying to build around these rockets i become unable to place or delete blocks. if i try to relog the character they will be unable to move to different numbers on the hotbar, -PLEASE FIX- I have lost at least 4 characters to this.

gif of break is included. use the character "another" and repeat the steps in the gif

 to see the break
![ezgif-1-bb00d777a59b](https://user-images.githubusercontent.com/14081996/51735092-44be6b00-203b-11e9-8d4f-5573f96ddbd1.gif)
...

### Steps to reproduce the issue:
try building around the rockets or load any of my characters, (yes and no are old ones but the others are all confirmed to be broken)
...

### Environment
- Skywanderers version: 19w03a

- Graphics Card: Vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2795307/output_log.txt)
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/2795268/Save_Data.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
