### ISSUE TITLE
[Exp.] Freezes when building on a large build

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#1072]
### Short Description of the issue:
Since the last update, I'm experiencing a freezing/loading time when building and deleting blocks on a fairly large project.

It doesn't happen when building bricks, only blocks.

I didn't have any issue before this update.

### Steps to reproduce the issue:
- Load the Acclamator blueprint in a world.
- Build a block on the Acclamator.

### Environment
- Skywanderers version: pre-alpha 19w03a
- Graphics Card: GeForce GTX 980

### Additional information:
Here is a gfycat of the issue where I'm building a single block then delete it. I've captured three freezes (Block built, block mirrored, block deleted). Each freeze last around 1.3s.
https://gfycat.com/blissfulfavoritearmadillo

### Output Log
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2807616/output_log.txt)

**Comment by TheCuriousSkeleton** [comment]
There seem to be a lot of problems from people who have a GTX. I can't load up a character without my computer dying on me for 30min, even then it lags so much that it's unplayable.

**Comment by tsunamayo** [comment]
Hi, I know exactly what is the issue in the case of Name11ess. Your ship is such a massive beast, every time you place a block you re-push the massive light texture (must be more than 300mb...). I should be able to fix that, pb is that I am undergoing some big change atm on the visual side so next update is gonna be in a long time...
@TheCuriousSkeleton not sure if it is the same issue though, are you building massive ship also? What is your GTX? cheers

**Comment by TheCuriousSkeleton** [comment]
GTX 1050TI - there have been a few, mainly performance issues, from people with GTXs. Which only started after the refactoring. I don't know if its just a coincidence, but it is suspicious.

**Comment by Name11ess** [comment]
> I should be able to fix that, pb is that I am undergoing some big change atm on the visual side so next update is gonna be in a long time...

You are breaking my heart, I was finally close to start building the interesting things! 😄

**Comment by tsunamayo** [comment]
Okay in the last build Rotc it takes forever to load but it finally load, and there is now hiccup when working on it. God it is massive... Gonna use it for testing when I fix the loading time issue.
