### ISSUE TITLE
cream on the torus

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1073]
### Short Description of the issue:
Loaded up my torus today and found this no idea what has happened lol.

### Environment
- Skywanderers version: experimental
- Graphics Card: gtx1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/52183366-1ee55300-27ff-11e9-8afd-734d66c13e1a.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
No longer applicable, torus will be back with a vengeance. Cheers
