### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by NathanInThailand** [tsunamayo/Skywanderers#1075]
### Short Description of the issue:
Game crashes when I start a new game. (Freezes on loading game)
...

### Steps to reproduce the issue:
Start a new game
...

### Environment
- Skywanderers version: 18w20a
- Graphics Card: RTX 2060
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2893128/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Sorry I missed this one, but it seems related to the RTX. I keep you posted! Thanks

**Comment by tsunamayo** [comment]
@NathanInThailand 
So you can check 19w23d, bug should be fixed! Tell me if it works.
Thanks for your patience! Cheers

**Comment by tsunamayo** [comment]
RTX bug has been fixed. Thanks
