### ISSUE TITLE
Symetry plane not showing up

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1076]
### Short Description of the issue:
Tried using the symmetry robot. When you first turn symmetry on no plane is shown so I tried toggling symmetry visibility and no symmetry plane showed up again. This mean's I can't move or turn it. It is also hard to know if the issue is with the symmetry plane or with the button because there is no indicator that confirms if the symmetry plane should be visible or not at the moment.

### Steps to reproduce the issue:

Try to build using symmetry. 

### Environment
- Skywanderers version: experimental
- Graphics Card: GTX10G0

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2894487/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
This issue should no longer happens with the new workflow. Thanks!
