### ISSUE TITLE
[EXPERIMENTAL][BUG/SUGGESTION]Codex UHD/4k display issue (too small)

### ISSUE THREAD

**Issue by LazyZarra** [tsunamayo/Skywanderers#1081]
### Short Description of the issue:

... I'm playing on a 43" 4k UHD display at a resolution setting of 3840x2160, (windows scaling set to 150%) and the codex and the hot key boxes are painfully small.

### Steps to reproduce the issue:

... N\A

### Environment
- Skywanderers version: 19w03a
- Graphics Card: GTX 970

### Additional information:

all other UI elements (main menu, Options menu and the individual options themselves) are scaled just fine.

![skywanrders hd](https://user-images.githubusercontent.com/39645615/55527251-7df90400-5698-11e9-8727-ee7ba1e7e968.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3041595/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I should have fixed this issue. I can only confirm for lower resolution screen though (I only have access to 1080p screen), dont hesitate to ping me back if issue was not actually fixed. Thanks a lot! Cheers

**Comment by tsunamayo** [comment]
Fix will be in 19w31b.
