### ISSUE TITLE
[Suggestion] Companion shape to "small corner block"

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1082]
Coming off your most recent Kickstarter Update (Very exciting!), you mentioned suggestions for brick/block shapes.
![image](https://user-images.githubusercontent.com/27857711/57141239-b122d600-6db1-11e9-8c95-7c34c8c02f96.png)

Here is my suggestion (marked in red).
When combined with the current "small corner brick" (in green) and stretchy tech, you can create many awesome shapes such as pillars angled in 2 directions (in yellow) and complex adding bevels to complex edges.
I hope the image above shows off this proposed shape well, I'll be happy to provide better angles if needed.

Best of luck with the refactors!

**Comment by tsunamayo** [comment]
Hi, thanks for suggestion, sorry I am only peeking it now... Yes could you please provide more angle? Did I made some already with the half corner left / right? I think I get the yellow, for now it is not possible in the current tech but I might try to make it works, it could be really cool especially for micro glass block. Thanks!

**Comment by ProPeach** [comment]
This was actually the same shape as the twisted tetra that Sen and I asked for a while back and you added, thanks for checking in though!

**Comment by tsunamayo** [comment]
Okay cool!
