### ISSUE TITLE
[RotC] Lighting Issue and no border on wood block

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1083]
![20190522223016_1](https://user-images.githubusercontent.com/32974671/58223968-7a214f80-7ce1-11e9-9434-90bdfcd3fe69.jpg)
As previously shown there is some random shenanigans with the lighting, my thought is that it's related to the starter block. I placed one, broke it, placed another, broke it and repeated that for a little while and got this result:
![20190522222234_1](https://user-images.githubusercontent.com/32974671/58223958-7261ab00-7ce1-11e9-87ba-fa7730528fe6.jpg)
Relogging seems to fix the issue until you repeat that process

Might also be worth looking into the blocks being a tad lighter on faces that should be darker than the rest:
![20190522222923_1](https://user-images.githubusercontent.com/32974671/58224105-f025b680-7ce1-11e9-9071-a8a542dc3329.jpg)
### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190522223000_1](https://user-images.githubusercontent.com/32974671/58224131-03388680-7ce2-11e9-9282-17415284fd75.jpg)
![20190522221034_1](https://user-images.githubusercontent.com/32974671/58224137-0a5f9480-7ce2-11e9-95f5-0a83cb4f1405.jpg)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3210152/output_log.txt) (Is 387 KB)

**Comment by tsunamayo** [comment]
Okay I can reproduce the issue. Actually there is two issue at play here.
Will keep you posted, thanks for checking the new version!
Cheers

**Comment by tsunamayo** [comment]
Okay issue are fixed! Thanks ^^
