### ISSUE TITLE
[RotC] Changing player models in 3rd person breaks camera POV

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1084]
### Short Description of the issue:
Changing player models in 3rd person view shifts the players camera POV when switching back to 1st person after selecting a new model
...

### Steps to reproduce the issue:
1. F4
2. ESC (change player model)
3. F4
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190522231322_1](https://user-images.githubusercontent.com/32974671/58225445-b192fa80-7ce7-11e9-8fa4-5d7cdc5437ce.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3210229/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue is fixed! Thanks for your help
