### ISSUE TITLE
[RotC] Hull bevel is offset

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1085]
### Short Description of the issue:
The beveled edge for the hull seems to be offset oddly, placing a strip on the block/area fixes the issue. Placing hull on the wood also fixes the no border issue.
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190522232326_1](https://user-images.githubusercontent.com/32974671/58225702-f8352480-7ce8-11e9-9fd7-8908f331df64.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3210240/output_log.txt)

**Comment by tsunamayo** [comment]
The border issue on new entity should be fixed now. Thanks!
