### ISSUE TITLE
[RotC] More funky bevel offset

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1086]
### Short Description of the issue:
The bevel seems quite wonky with the stretch tech
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190522232958_1](https://user-images.githubusercontent.com/32974671/58225859-ae990980-7ce9-11e9-91ed-84314e5502c2.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3210252/output_log.txt)

Also, it seems fresh installs don't add a Blueprints folder in the Save_Data path

**Comment by tsunamayo** [comment]
The border issue on new entity should be fixed now. Thanks!
