### ISSUE TITLE
[RotC] Sticker placement not working correctly on stretched blocks

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1087]
### Short Description of the issue:
When trying to place a sticker on a stretched block, no matter where you click, it will place the sticker on the "origin" of the stretched block. 
![image](https://user-images.githubusercontent.com/29961381/58271228-7ba35400-7d83-11e9-9df9-9125a4e0cf0d.png)

...

### Steps to reproduce the issue:
-Get a normal hull block and stretch it.
-try and place a sticker anywhere except the 1x1x1 space where you started dragging the block from
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/58273755-469a0000-7d89-11e9-9d11-7fbb11d6b4fe.png)

This also seems to happen on the side of blocks especially, even on a single placed block

**Comment by tsunamayo** [comment]
Okay issue is fixed. Thanks!
