### ISSUE TITLE
[RotC] "Instrument A"is slightly offset

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1088]
### Short Description of the issue:

"Instrument A"is slightly offset
![image](https://user-images.githubusercontent.com/29961381/58271653-6b3fa900-7d84-11e9-8c46-9b56c83bab97.png)

### Steps to reproduce the issue:

- Try and place "Instrument A" 
- Realize it is slightly offset
...

### Environment
- Skywanderers version: [RotC]
- Graphics Card:  GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay good spot! It is now fixed. Cheers
