### ISSUE TITLE
[RotC] Rounded blocks are spooky 

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1089]
### Short Description of the issue:

Rounded Blocks and Rounded block corners are very offset when placed 
![image](https://user-images.githubusercontent.com/29961381/58274666-384ce380-7d8b-11e9-9b46-0bc7abec6691.png)

### Steps to reproduce the issue:
- Place Rounded Blocks/Rounded Block Corners
- Cry in fear
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay no more cry - this one is fixed ;) Cheers
