### ISSUE TITLE
Vignette in 3rd person

### ISSUE THREAD

**Issue by Darkwright** [tsunamayo/Skywanderers#109]
When you are in 3rd person in space a circular semi-transparent  vignette shows up slightly darkening the edges of the screen.
![bug 1](https://user-images.githubusercontent.com/33014971/31871540-bea82bfc-b77a-11e7-9332-dbd388258d68.PNG)

**Comment by tsunamayo** [comment]
Hi! Are you sure you didnt activated the vignette in the graphical options? When entering in first person does it switch back to no vignette? Thanks!

**Comment by Darkwright** [comment]
Yeah, I've tried turning it on and off, one thing I've noticed is that the main menu option doesn't affect saved games. I had it off in the main menu but in game it was on. Also if you apply it while in a save, it doesn't save unless you hit f1.  I play at FOV 100 so that may also affect it. Here is a screenshot when I turned it off in the menu and game, and then save and completely reloaded the game. 
![bug 2](https://user-images.githubusercontent.com/33014971/31923428-09255612-b840-11e7-8641-0925fa265c51.PNG)

**Comment by Darkwright** [comment]
Also as you can see, it persists across 1st and 3rd person, I just didn't notice it at first in 1st person.

**Comment by tsunamayo** [comment]
What happen after you turn it off and reload the game? I am not reproducing at all your issue, also these settings are not related to the game F1 save. Could you please check the file C:\Users\[YOUR_USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\SETTINGS.ini and send it to me?

On a side note, 100 FOV are not working with the star background.

**Comment by Darkwright** [comment]
[audio]

masterLevel=100											; Can only be 0 - 100
musicLevel=100											; Can only be 0 - 100

[CONTROLS]

MouseSensitivity=100										; Can only be 0 - 200
MouseInverted=False										; Can only be 0 - 200
MoveForward=w
MoveBackward=s
MoveRight=d
MoveLeft=a
Jump/Moveup=space
Crouch/Movedown=left ctrl
Delete/UseItem1=Mouse Button 0
Build/UseItem2=Mouse Button 1
Activate/Enter=f
Inventory/Codex=tab
HeadLight=l
SwitchDrive=left alt
Drive+=]
Drive-=[
Pitch+=w
Pitch-=s
Roll+=d
Roll-=a
Yaw+=q
Yaw-=e
Hotkey1=1
Hotkey2=2
Hotkey3=3
Hotkey4=4
PickBlock=Mouse Button 2

[graphic]

FOV=100													; Can only be 1 - 179
Ambiant Occlusion=True									; True or false.
V-Sync=True												; True or false.
Vignetting=False											; True or false.

[player]

playerName=
head=Dave
torso=Futuron_b
hair=Spike

**Comment by Darkwright** [comment]
Also it does change with my FOV if I go to 80 it looks like this. 
![fov80](https://user-images.githubusercontent.com/33014971/31944111-9aa637fa-b890-11e7-8247-f33ddae53113.PNG)

But if I go any higher it stops drawing the starmap outside of that circle. 
![fov100](https://user-images.githubusercontent.com/33014971/31944164-c84f30d0-b890-11e7-8676-21b2a14b2e05.PNG)

**Comment by tsunamayo** [comment]
Yes there is issues with stars and high FOV, it needs a fix =(
But back to the Vignette issue, just to be sure to understand your test case, could you please try the following:
1) You put vignette ON inside the graphical option in the start menu, and validate the change
2) Go back to the same menu: is the vignette still at ON?
3) load a character: do you see the vignette? Is vignette at ON inside the graphical options?
4) Restart the game, is vignette still at ON inside the start menu options?

Then could you do the same with OFF.

Cheers!

**Comment by tsunamayo** [comment]
Hi, I think the issue was fixed - Cheers!
