### ISSUE TITLE
capacitors top texture

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1090]
### Short Description of the issue:
if the capacitor is more than 3 blocks tall this happens
...
![image](https://user-images.githubusercontent.com/43644633/58286211-2593d800-7da6-11e9-8b5d-8ca3aa75a99b.png)

### Steps to reproduce the issue:

build a tall capacitor

**Comment by tsunamayo** [comment]
Okay this is fixed. Thanks for testing! Cheers
