### ISSUE TITLE
[RotC] Looking in Codex Crashes Game and Sometimes Windows

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1091]
I'm getting a couple hitches when trying to build, but when looking in the codex, the game crashes, and sometimes windows does as well. Hopefully the output_log will be of some help.

Windows 10 64bit
i5-4670k 3.40ghz
GTX 1060 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3214164/output_log.txt)

**Comment by tsunamayo** [comment]
Hi Sen - so it seems related to a DLL the game need but cannot find. Could you delete your game install and re-install again?
That is not the first time we saw this error - for a long term solution I will get rid of that DLL entirely. 
Cheers

**Comment by Senakysam** [comment]
Yep, that fixed it

**Comment by tsunamayo** [comment]
Okay good to hear.
