### ISSUE TITLE
[RotC] Can't See Ship in Window in Ship Computer Menu

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1092]
As the title says, when trying to customize the orientation of your ship in the spaceship core, you can't see your ship at all.

**Comment by tsunamayo** [comment]
Yes, and the holomap and target cam will be broken too, I havent time to upgrade them following the rendering tech change. Also I will remove this "feature" and use the joystick direction instead, that will be less confusing. Might still keep it as an optional override.

**Comment by tsunamayo** [comment]
Okay issue is fixed. Cheers
