### ISSUE TITLE
[RotC] No way to delete entities

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1094]
### Short Description of the issue:
The codex seems to be missing the id block (for removing unwanted entities)
-Edit- We are also missing paint from the codex
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Yes indeed! I will put a separate tab for paint and stickers. For deleting the entity I will use the F5 drone. F5 will be the shipyard menu when shipyard will be implemented. Cheers

**Comment by tsunamayo** [comment]
Okay I added a delete button to the drone menu. Thanks
