### ISSUE TITLE
[RotC] Can look around while codex is open

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1095]
### Short Description of the issue:
If you keep your mouse moving while opening the codex, the codex will open and you'll still be able to look around instead of seeing the cursor and using the codex
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3214969/output_log.txt)

**Comment by tsunamayo** [comment]
This annoying issue is fixed. Thanks!
