### ISSUE TITLE
[RotC] Lighting not centered on source object

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1096]
### Short Description of the issue:
The center of the actual light doesn't seem to stay centered with it's source location
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190523223635_1](https://user-images.githubusercontent.com/32974671/58301257-5aeef480-7dab-11e9-8550-6f178ce9dfd8.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3214981/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, unfortunately it is a weakness of the current light design that use the voxel grid to store light value. So it wont be fixed (unless I decide to switch my lighting tech one day). Specular reflection are okay though. Cheers
