### ISSUE TITLE
[RotC] Hiding UI then moving reveals cursor

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1097]
### Short Description of the issue:
After pressing F2 to hide the UI and moving around you see the cursor along with the crosshair

Also with the UI hidden if you hit ESC you are stuck hovering on Help until you hit ESC again and reveal the UI again
...

### Steps to reproduce the issue:
1. Press F2
2. Move
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190523224801_1](https://user-images.githubusercontent.com/32974671/58301685-0a789680-7dad-11e9-929c-762272f86b48.jpg)
![20190523225018_1](https://user-images.githubusercontent.com/32974671/58301749-604d3e80-7dad-11e9-935c-382c433e9d65.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3215033/output_log.txt)

**Comment by tsunamayo** [comment]
Okay it is fixed, except for the main menu as this will be fixed when the migration to the new UI is completed. Cheers
