### ISSUE TITLE
[RotC] "Button" and "Button" do not function as buttons

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1099]
Here, both bricks painted red labelled "button" cannot be linked by the link tool. Are these just decorative panels? In the codex they are labelled as buttons and are said to work as buttons too.
![image](https://user-images.githubusercontent.com/27857711/58335836-61787d00-7e3a-11e9-9072-e8d7be6bf5d1.png)
![image](https://user-images.githubusercontent.com/27857711/58335926-984e9300-7e3a-11e9-8bc7-d7e5fbfbb2cc.png)

 Steps to reproduce the issue:
Place bricks "Button" and "Button" and attempt to link them

- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Okay fixed.Thanks!
