### ISSUE TITLE
Switches & other stuff have weird offsets, don't know how to reproduce

### ISSUE THREAD

**Issue by ForsakenHarmony** [tsunamayo/Skywanderers#110]
![](https://i.imgur.com/WTiFj8V.png)

Started to build off of this building

![](https://i.imgur.com/aNzGy12.png)

**Comment by ForsakenHarmony** [comment]
![](https://i.imgur.com/Snc9GUi.png)

Not just switches it seems

**Comment by ForsakenHarmony** [comment]
just that one grid of blocks as well

**Comment by tsunamayo** [comment]
Thanks for reporting this! The bug was fix, fix will be included in the next build. Cheers
