### ISSUE TITLE
[RotC] Emissive textures colour

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1100]
All emissive textures run through the colours of the rainbow, and can't be painted. This includes engines, logic bricks, "core" bricks, void reactors, screens etc.

...

### Steps to reproduce the issue:
Place any block/brick with an emissive texture, not the colour change. Try and paint it
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

![Skywanderers Emissive Rainbow](https://user-images.githubusercontent.com/27857711/58336867-7fdf7800-7e3c-11e9-91b8-17387cdf2742.gif)

**Comment by tsunamayo** [comment]
Okay issue fixed! Cheers
