### ISSUE TITLE
[RotC] Mouse cursor appears during flight

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1102]
When you enter a ship core via a yoke, the mouse cursor is visible alongside the regular crosshairs.

Weirdly, it does not show up on any screenshots I take, so you'll just have to believe me 😛 
![image](https://user-images.githubusercontent.com/27857711/58338052-039a6400-7e3f-11e9-9800-faa01a9f1a30.png)

Steps to reproduce the issue:
Connect yoke to ship core
Press F on yoke
Observe cursor

Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Issue is fixed! Thanks
