### ISSUE TITLE
[RotC] Some bricks do not show the link effect while linking

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1103]
When linking some bricks (like lasers and the camera), the link "rope" does not show until you complete the link. 

If you turn up the sound, you can still hear the link effect playing as I try to link this laser.
[Skywanderers Missing Link Report.zip](https://github.com/tsunamayo/Skywanderers/files/3217575/Skywanderers.Missing.Link.Report.zip)

...

### Steps to reproduce the issue:
Place laser/camera
Attempt to link it to another logic brick
Observe the lack of link "rope"
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Thanks for the vid! Okay actually you are not supposed to be able to link from laser / camera, it was a bug relative to that. It is now fixed. Thanks!
