### ISSUE TITLE
[RotC] Spaceship 1

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1104]
All blueprints on the Load list of the drone display as "Spaceship 1", not the actual file name of the blueprint
...

### Steps to reproduce the issue:
Press F5 to spawn the drone
Navigate to the drone's Load options
Observe the list of "Spaceship 1"
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

Additional information:
Here's the log file - This shows me loading up the game, spawning in a blueprint called Spaceship 1, saving and then quitting
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3217610/output_log.txt)

**Comment by tsunamayo** [comment]
Okay it is seems it is completely unrelated bug on the character side. Name of save are fine on my side - but your log file is full of error. Are you able to play normally? Cheers

**Comment by Xerma** [comment]
I too have the Spaceship 1 issue, everything seems to run just fine for me

**Comment by ProPeach** [comment]
Yes, I've had no trouble loading up the game and playing apart from the bugs that we've already reported. Everyone I've talked to has had this Spaceship 1 bug. Is there anything else we could do to help single this bug out?

**Comment by ProPeach** [comment]
This Spaceship 1 bug is also present in the experimental branch as per #1068. 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3219271/output_log.txt)
Here's a log file of me loading the game, spawning the drone and loading in a blueprint that is named "Spaceship 1" in the experimental branch, it might be useful to cross reference the errors

**Comment by tsunamayo** [comment]
Okay could one of you send me a zip file of their custom blueprint? It might have to be something with it (I dont reproduce this one...) Thanks!

**Comment by Senakysam** [comment]
Here's an old save of the current ship I'm working on.



[Goblin_Mk2 WIP01.zip](https://github.com/tsunamayo/Skywanderers/files/3233634/Goblin_Mk2.WIP01.zip)

**Comment by ProPeach** [comment]
Here are the .mps files currently in my BLueprints folder, it's worth nothing that every single .mps file has shown as Spaceship 1 in the Load menu
[ProPeach Spaceship 1 Blueprints.zip](https://github.com/tsunamayo/Skywanderers/files/3234873/ProPeach.Spaceship.1.Blueprints.zip)

**Comment by tsunamayo** [comment]
Okay I finally reproduced the issue and fixed it. It was a runtime only issue, editor was okay. Thanks!
