### ISSUE TITLE
[RotC] Hull block bevel error

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1105]
On the first stretched block that is placed on a newly created grid, the bevel effect does not show correctly
This is one stretched block, not two
![image](https://user-images.githubusercontent.com/27857711/58340120-06975380-7e43-11e9-9a10-43cdfc5fb9de.png)
You can see by the outline that it is one block
![image](https://user-images.githubusercontent.com/27857711/58340270-5249fd00-7e43-11e9-8a2e-91e948247698.png)

This error is only present on the very first stretched block placed on a new grid

### Steps to reproduce the issue:
Create a new grid with the starter block
Place a stretched block on the new grid
Observe bevel error

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Actually it is a duplicate that has already been fixed. Thanks!
