### ISSUE TITLE
[RotC] Miss match between head position and camera position

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1106]
When sitting on a chair, your head is much further down than your first person view partly because of the sitting down animation. The first person few would ideally follow the head down during the animation.
Exterior view, low head
![image](https://user-images.githubusercontent.com/27857711/58341415-11071c80-7e46-11e9-90c4-e006839bc151.png)

First person view, high head
![image](https://user-images.githubusercontent.com/27857711/58341452-23815600-7e46-11e9-8cdf-aa997f7f79c1.png)

### Steps to reproduce the issue:
Sit down in a chair with some kind of marker for reference like this canopy piece
Switch between 1st and 3rd person, noting the difference in where your head is, and where the first person camera is

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050 M

**Comment by tsunamayo** [comment]
Okay this is fixed, thanks for noticing it! Cheers
