### ISSUE TITLE
[RotC] Brick stretching

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1107]
### Short Description of the issue:
Not sure if this is a bug, or just a feature that has not been implemented yet, but basic bricks don't stretch past 4m as you said in your recent discord message: "max scale for small brick 0.25cm is 4mx4m"

### Steps to reproduce the issue:
- Try and stretch bricks 4m
- They only go to 2m
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay indeed I now bumped the limit to 4m. Thanks!
