### ISSUE TITLE
[RotC] Mirror drone builds even if the result clips

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1108]
### Short Description of the issue:
The mirror drone will place down bricks/blocks even when its result clips (and creates 2 of anything in the center of the mirror plane)
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190524210440_1](https://user-images.githubusercontent.com/32974671/58363322-b54d8b00-7e67-11e9-9e18-081d1d8bf6e5.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3219021/output_log.txt)

**Comment by tsunamayo** [comment]
This is fixed in 20w13a. Thanks!
