### ISSUE TITLE
[RotC] Bolt has odd placement

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1109]
### Short Description of the issue:
The bolt sticker/carve/normal doesn't want to place around the entire stretched brick and sometimes displays in a different location than where you're aiming
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190524224713_1](https://user-images.githubusercontent.com/32974671/58364207-30b63900-7e76-11e9-9c0a-cba6ae39d8fa.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3219100/output_log.txt)

**Comment by tsunamayo** [comment]
Duplicate, already fixed. I will push a new build soon. Thanks!
