### ISSUE TITLE
Fullscreen to windowed mode sometimes causes game window to semi-vanish.

### ISSUE THREAD

**Issue by ZeroNovaSai** [tsunamayo/Skywanderers#111]
When switching from fullscreen to windowed mode in-game the game window sometimes vanishes and the game needs to be restarted to see it again. It also sets your screen res to a lower setting when you relaunch.      (It seems to start after exiting the first tutorial room because i was able to exit to windowed mode no problem before leaving the room.)

What settings look like when game is first launched.
![bug01-1](https://user-images.githubusercontent.com/33015338/31872530-7d9776ee-b771-11e7-9320-68cc2bd5f0d9.png)

In-game settings. 
![bug01-4](https://user-images.githubusercontent.com/33015338/31872563-d858b7c8-b771-11e7-8940-4c479c5742d7.png)

Switching to windowed mode.
![bug01-5](https://user-images.githubusercontent.com/33015338/31872595-fcd0c1ae-b771-11e7-902f-0247baf8a05c.png)

Result.
![bug01-3](https://user-images.githubusercontent.com/33015338/31872608-18be5a3e-b772-11e7-9f28-421f0e28bc1e.png)

When game is re-launched
![bug01-2](https://user-images.githubusercontent.com/33015338/31872616-2ba71a6e-b772-11e7-8d68-8cd31d50379e.png)

first bug report sorry if there's any confusion.

**Comment by tsunamayo** [comment]
Thanks for reporting this! I will have to force a game restart to change this setting. Cheers

**Comment by tsunamayo** [comment]
Thanks, the issue was fixed and will be available in upcoming build (17w45a). Cheers
