### ISSUE TITLE
[Suggestion] Degree of customisation for brick bevels

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1110]
The new brick bevel effect is a great addition to the game overall, but I feel that in some cases it can cause problems. When you paint bricks lighter colours like white, the bevels remain very dark and it creates a grid pattern. Usually when builders use lighter colours they want a sleek, bland look to contrast some greebles for example.

![unknown (4)](https://user-images.githubusercontent.com/27857711/58367046-288be700-7ed2-11e9-86b8-6300169a68aa.png)
Here the dark bevel looks great with darker colours
![image](https://user-images.githubusercontent.com/27857711/58367760-8f150300-7eda-11e9-9363-e4881ade0662.png)

While in this image the bevels stick out and slice up an otherwise smooth shape
After talking through with some other testers we came up with a few additions that we think could reduce this effect.

- Bevel colour changes to a a lighter darker hue of the base colour. If you painted a brick white, the bevel colour would change to a very light grey rather than stay dark as it does now

- "Paint" tool to change the colour of bevels separately, or remove/add the effect to the whole brick. This way those who prefer the current, darker bevels could keep them, while others who would like a different coloured bevel are also happy

Update - Womble kindly pointed out that the bevel effect is a normal map rather than a flat texture. Perhaps softening/brightening the shadows on the edge could help reduce the effect.

We look forward to hearing from you!

**Comment by Garrett-C** [comment]
Yeah I agree. I like the bevel for makin areas look plated. It does provide an easy way to add some subtle detail but on area you want to make smooth where you have  I use a lot of bricks it does kind of ruin the smooth design. I agree that some way of adding/removing bevels on blocks would be nice.

**Comment by Xerma** [comment]
In some situations I would prefer beveled edges and in others no bevel would be fantastique. Would it be possible to keep the beveled bricks and have another set of bricks that have no bevel?

**Comment by schlid** [comment]
^ the choice would be nice

**Comment by GadyZ** [comment]
I agree with everyone here. Inner bevels don't really make a lot of sense, and kind of look like some other game.

**Comment by tsunamayo** [comment]
Okay, if you guys can send me some of your ship so I can get a feel on how bad it looks on real ship and how I could improve it. I still want to keep bevel so people have to use stretch, otherwise it could lead to perf issues (I know it sucks).
Thanks!
