### ISSUE TITLE
[Suggestion] Make the placement preview easier to see

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1111]
In some cases, especially where there is a lot of natural light, the block placement hologram can be difficult to see
![image](https://user-images.githubusercontent.com/27857711/58367797-5164aa00-7edb-11e9-8549-d115893a79ba.png)
Here I'm placing a brick, but it is too faded to see which orientation it will place in. Perhaps lowering the transparency of the hologram  would help.

As a side note, when can we expect all these great bug fixes to be pushed to the testing branch of RotC? It would help a lot to combat duplicate reports. Thanks as always o/

**Comment by tsunamayo** [comment]
Build is just pushed. Yes I need to improve this, the main issue is that the edge post process dont work well with two colors (the white of the targetted block and the blue of the preview)

**Comment by tsunamayo** [comment]
Okay I improved it and fixed the outline issue. Thanks!
