### ISSUE TITLE
[Multiplayer] player model issues

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1112]
### Short Description of the issue:
Clients cannot see any character animations from the host, while the host cannot see any of the other clients in the game

### Steps to reproduce the issue:
Join/host multiplayer 
Meet up with the other player and compare how you see eachother 

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Issue is fixed, but I still to fix the animation. Thanks!
