### ISSUE TITLE
[RotC] Random bits of stuttering lag

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1115]
### Short Description of the issue:
Not sure how else to describe it besides some semi frequent stuttering
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3219948/output_log.txt)

**Comment by tsunamayo** [comment]
Is this something you just got in the build uploaded a few hours ago?

**Comment by Xerma** [comment]
Indeed, I wouldn't go as far to say its game breaking but it's bothersome. Happens maybe every 10 - 20 seconds

**Comment by Xerma** [comment]
Seems the stuttering was due to me having an instance from the first release of the new build while running the new build. Creating a new instance fixed this issue
