### ISSUE TITLE
[RotC] Building drones stick around after their parent blueprint has been deleted

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1116]
After you Unspawn an entity via the building drone, both the yellow and grey drones are left. If you then press F5 to despawn them, the yellow drone dissappears but the grey (mirror) drone remains which you then can't get rid of
...

### Steps to reproduce the issue:
Spawn a blueprint with the building drone and enable mirror
Unspawn the entity (Two dones now remain)
Press F5 (One drone now remains)

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
It should be fixed! Thanks
