### ISSUE TITLE
[RotC] "Small Corner Brick" does not stretch

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1117]
Just a quick, this brick does not stretch in any direction;
![image](https://user-images.githubusercontent.com/27857711/58384513-53616280-7fda-11e9-81ab-af66d71dc02a.png)

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by Xerma** [comment]
Would be a fantastique stretchy bricc

**Comment by Womble-TC** [comment]
can we get a corner version of it too at some point? Doesn't have to be right away.

**Comment by tsunamayo** [comment]
Okay that one is fixed. Thanks!
