### ISSUE TITLE
[RotC] Mirror drone "gives up" on mirroring after a time

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1118]
### Short Description of the issue:
When using the mirror drone, after some time of building (2-10 minutes) the grey mirror drone stops placing blocks and painting, just to spin on the spot
...

### Steps to reproduce the issue:
Enable mirror drone
Place blocks/paint for a few minutes, it shouldn't take long before the grey drone starts dancing
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050

Video of the drone and Log file:
[Skywanderers Dancing Mirror Drone Bug.zip](https://github.com/tsunamayo/Skywanderers/files/3220520/Skywanderers.Dancing.Mirror.Drone.Bug.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3220522/output_log.txt)

**Comment by tsunamayo** [comment]
This should (hopefully) be fixed. Dont hesitate to re-open / book another case if it is not the case, as there was a lot of AnimatorIK in the log file I might have missed something. Thanks!

**Comment by Senakysam** [comment]
Happened to me a couple times in the newest build.
