### ISSUE TITLE
[RotC] Head lamp stopped working after the latest patch 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1119]
### Short Description of the issue:
As the title says, when you try to turn the head light on, you hear the sound effect but no light comes on
...

### Steps to reproduce the issue:
Try to turn on the headlamp
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Okay bug is fixed. Thanks!
