### ISSUE TITLE
Canopy Long Tetras can't be coloured

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#112]
![20171023010816_1](https://user-images.githubusercontent.com/33016249/31873183-a47c5f9a-b78f-11e7-8a3f-136b21c8cd5e.jpg)

All of the other canopy blocks have been coloured red, but the long tetras are not.

**Comment by AfterRebelion** [comment]
This is still "valid" to some point in recent versions (19w23b). New cannopy no longer let's you color the window, but the edges. But currently tetra don't have the new models/ textures, so the still can't be colored.

**Comment by tsunamayo** [comment]
Yes, I think I will either add dual brick coloring or borderless canopy at one point. Thanks for going through all the older issues! Cheers

**Comment by tsunamayo** [comment]
Okay as of 20w12a we now can paint the frame and the transparency. I still need to improve the primary / secondary targeting logic a bit. 
Thanks!
