### ISSUE TITLE
[Rotc] Unable to access drone UI

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1120]
### Short Description of the issue:
Cannot press F to open up the drone UI. As Peach informed me you have to place a block/starter block before being able to open it.

I'd also like to recommend adding the ability to hit ESC to close any UI that is currently open. As in if you hit ESC while the codex is open it should just close out rather than going to the ESC menu. It would also be nice for the drone UI since I've had to use my cursor to close it out. Would make the UI feel easier and faster to use.
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3220996/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I agree, I added the escape key press. Also fixed this bug when I face it yesterday. Thanks!
