### ISSUE TITLE
[RotC] Loaded blueprints are invisible

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1121]
### Short Description of the issue:
After using the drone UI to load in a blueprint, it's invisible but still able to build on it, however any added blocks are also invisible
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190526134811_1](https://user-images.githubusercontent.com/32974671/58385901-35d1d000-7fbd-11e9-810b-0a6fd27280c1.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3220998/output_log.txt)

**Comment by Xerma** [comment]
Reloading after saving reveals the invisible blueprint(s)

**Comment by tsunamayo** [comment]
Maybe it was something weird with your blueprint, if you can forward it to me? Thanks

**Comment by Xerma** [comment]
Just tried spawning the same blueprint in a few times and it does seem to work just fine now with some minor issues: Some strange painting glitch in the same location for each of the spawned entities and then this odd brick visual bug:
![20190527200518_1](https://user-images.githubusercontent.com/32974671/58443960-2d5fbf00-80bb-11e9-802b-d5b567bf7222.png)
![20190527200524_1](https://user-images.githubusercontent.com/32974671/58443963-305aaf80-80bb-11e9-95ad-3fabd35bc474.jpg)
It also seems that the painted normals (bolt) have not saved/loaded with a new spawn

**Comment by tsunamayo** [comment]
Okay new build - tell me if that fixed the issue! Thanks

**Comment by tsunamayo** [comment]
Okay so did you faced the issue again? Not sure if it was the same as the invisible block... Thanks

**Comment by Xerma** [comment]
Unsure at the moment as I'm unable to spawn the drone via F5

**Comment by Xerma** [comment]
Blueprints seem to be loading all their blocks/bricks for me now
