### ISSUE TITLE
[RotC] Unable to fly ships after the hotfix 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1122]
### Short Description of the issue:
When controlling a ship through a yoke, I can't turn the ship, or move in any direction. This has only started happening after the recent push of RotC bug fixes 

### Steps to reproduce the issue:
Enter a ship via a yoke and try to move the ship or turn it.
...

### Environment
- Skywanderers version: RotC
- Graphics Card: 1050M

**Comment by tsunamayo** [comment]
Okay it is working again. Cheers
