### ISSUE TITLE
[RotC] Painting sometimes creates random invisible bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1123]
### Short Description of the issue:
In these pictures I tired painting that little panel and it made that wedge on the side completely invisible
...

### Steps to reproduce the issue:
Not sure how else to replicate it. Seems to happen somewhat randomly
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190526163242_1](https://user-images.githubusercontent.com/32974671/58387476-5b1e0880-7fd4-11e9-8663-ac76ca2dcd65.jpg)
![20190526163246_1](https://user-images.githubusercontent.com/32974671/58387477-5d806280-7fd4-11e9-8a53-bd8a6f9f10ce.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3221120/output_log.txt)

**Comment by Xerma** [comment]
Could be related to #1121 as reloading fixes this issue as well

**Comment by tsunamayo** [comment]
Yes there seems to be random issues with rendering - very annoying to debug. Your trade federation tank is looking neat ^^. I will see what I can do to make the seams less apparent. Thanks

**Comment by tsunamayo** [comment]
Okay new build - tell me if that fixed the issue! Thanks
