### ISSUE TITLE
[RotC] F1 doesn't save the direction the player is looking

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1124]
### Short Description of the issue:
After saving and reloading the camera doesn't face the same way as when you pressed F1. After a few tests, each time seems to make the camera looking position different
...

### Steps to reproduce the issue:
Save
Reload
Save
Reload
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Thanks for noticing that one, I was only save player body orientation, now I am also saving camera/head orientation. Cheers
