### ISSUE TITLE
[Suggestion] Bring back placement rulers

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1125]
With stretchy tech being such a wide spread feature now, a tool to keep track of the dimensions of a current stretch would be more helpful than ever. Just like the old days of mass placing blocks, a length/width/depth measurement that pops up whenever you stretch a block/brick would be much appreciated.

As a side note, do you still plan to reimplement brick offsets?

Thanks for everything as always o/

**Comment by Xerma** [comment]
YesYesYesYesYesYes I've been missing this for so long. It makes building so very fluid with being able to see selection sizes instead of having to count in your head.

I'd really love to also have the offset back. A current build of mine requires either the 2x2 rotator brick or to have the new one offset to the center

**Comment by Womble-TC** [comment]
Yeah, the ruler was nice, however brick offset was nicer, it would really help with stuff like the small rotor, right now this is the only way to make an r2 unit >:( 
![image](https://user-images.githubusercontent.com/29961381/58388208-bd4a2e00-8013-11e9-8a18-106acad988a5.png)

**Comment by tsunamayo** [comment]
Yes I will definitely add these back. Reason I have been holding on UI is now that I moved away from pixel art I will be able to get rid of the crappy pixel UI (a pain to make and work with), to a more minimal sleek modern UI. Also for the offset I still needs to find a way to make it neatly, but I will add it back for sure. 
Sorry I have been breaking things all around the place but now I feel much more confident in the tech. Thanks

**Comment by tsunamayo** [comment]
So I have put back both the ruler (I still want to make it a bit better looking), and the brick offset feature. Thanks!
