### ISSUE TITLE
[RotC] Reloading custom color issues

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1126]
### Short Description of the issue:
Reloading sometimes causes other entities to show default colors instead of custom colors.
The only way it gets fixed is if you update the paint on the entity manually

This may be an entirely different issue but my log file is filled with these:

NullReferenceException: Object reference not set to an instance of an object
  at Game.CharacterSwappableBody.OnAnimatorIK (System.Int32 layerIndex) [0x00000] in <6c19256ac166472880c30fc7163041bc>:0 
 
(Filename: <6c19256ac166472880c30fc7163041bc> Line: 0)

...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190526182823_1](https://user-images.githubusercontent.com/32974671/58388449-9f190980-7fe4-11e9-83ae-468741330c6a.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3221312/output_log.txt)

**Comment by tsunamayo** [comment]
Custom colors... How mad/sad would you guys be if I replace custom colors with both:
 - way more colors (rn we have 32, but I could have a 1000)
 - colors that have physical property, like gold, carbon fiber ect. Wont work on hull as I want hull to have the look and feel of their base material, but for the rest should be ok.

Custom colors have just been a pain to make work - it could make my life easier to get of it, just wanted to check up with you. I change my tech in several place so the above is now possible.

**Comment by ProPeach** [comment]
Personally the biggest benefit of custom colours is the ability to change the colour on your whole ship without needing to repaint it, if we could keep that functionality I wouldn't mind losing them for a library of set colours

**Comment by Xerma** [comment]
I would gladly trade 32 custom colors for 1000 global colors along with painting with physical properties like you mentioned. That would certainly allow for some very cool things. As Peach said it would be very handy if we were able to replace one color on a ship with another but I'd still go for the 1000 colors and physical property paint, PPP, regardless because it sounds amazing \o/ Do you think we could get a quick example of that? And how long do you think refactoring the paint like that would take?

**Comment by Dwarf-LordPangolin** [comment]
> Custom colors... How mad/sad would you guys be if I replace custom colors with both:
> 
>     way more colors (rn we have 32, but I could have a 1000)
>     colors that have physical property, like gold, carbon fiber ect. Wont work on hull as I want hull to have the look and feel of their base material, but for the rest should be ok.

If custom colors are causing that many problems, it might be prudent to drop them. 1000 colors would cover any possible colors anyone could want; as long as players don't have to unlock any of the colors, that would be fine. And physical property paints sound really cool.

I agree with ProPeach: the best thing about the custom colors is being able to change the colors of paints that are already placed. It saves a huge amount of time when designing things. If it would be possible to take a blueprint, and say "take all blocks painted X color and repaint them with Y color" that would be awesome.

**Comment by tsunamayo** [comment]
This issue should no longer happens as custom color are deprecated. Thanks!
