### ISSUE TITLE
[RotC] [Inquiry?] Torus

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1127]
What's the news on bringing the torus back? I know the textures will need changed and I also know you want to change the mountains on it as well. Just curious because it's cool to have a large ring to get a sense of scale sometimes

**Comment by tsunamayo** [comment]
I still see the Torus on my side - you are not seing it? Yes it will need an upgrade, but that was one of the reason I wanted that gfx switch, I am gonna be able to make a better looking one, with better perfs and much simplier code - as blocks were a nightmare.

**Comment by ProPeach** [comment]
It seems that the torus is not spawning when we create a fresh world.
Just out of curiosity, do you have any theories as to why there are often odd ifferences between your version and the test version?

**Comment by Xerma** [comment]
I haven't seen the torus for quite some time T_T

**Comment by tsunamayo** [comment]
Sen see the torus... The way the Torus is spawning is a dirty hack, I will make it more robust for sure. I talked a bit about before it but stations / torus build are gonna work completely differently.

**Comment by Senakysam** [comment]
Torus only halfway loaded when I first spawned the world, took a little bit for the rest of it to spawn in. Then there were a couple chunks that were glitched and floating for a bit, but then they went away as well.

**Comment by Senakysam** [comment]
This seems to be a common bug for people in the latest build as well.

**Comment by tsunamayo** [comment]
We now have a new torus and torus spawning is cleaner. Thanks!
