### ISSUE TITLE
[RotC] Mirror plane shows false placement size

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1129]
### Short Description of the issue:
If the mirror plane is not hidden and you drag into the plane and begin dragging it, it "saves" your selection size and previews it to you after you release the mirror plane.
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190526210152_1](https://user-images.githubusercontent.com/32974671/58391050-b4e4f980-7ff9-11e9-81ea-83d9b5893c7f.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3221535/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I think I fixed this bug already. Mirroring sucks so bad ... I am still not convinced at all by the usability of the plane. Also it dont make sense to mirror on children entity. I need to put more thinking into that, if you have some ideas. I could go back to something item base, like a tool, but not a brick (so you dont have to find were you put the brick, that was weird). Thanks!

**Comment by ProPeach** [comment]
How about a brick that is linked to a global hotkey, so you can just hit the hotkey wherever you are and it toggles on and off.
Alternatively you could create a tool that places the plane outright as a hologram, then a hotkey that toggles it on and off
