### ISSUE TITLE
[Bug] Placing then using starship core on ringworld makes game unplayable.

### ISSUE THREAD

**Issue by ZeroNovaSai** [tsunamayo/Skywanderers#113]
If you place a Starship Core on a Ringworld and then use it you will no longer be able move, place blocks, open menu's, or see your HUD even if you press F again. 

The only way to get out of the game is to Alt-Tab or Ctrl-Alt-Del.

**Comment by bananatrooper52** [comment]
Did you try pressing F while not looking at anything on the ship?

**Comment by tsunamayo** [comment]
Nice spot!  I am fixing the issue by simply preventing you to put that block on a torus. Thanks for reporting that!
