### ISSUE TITLE
[RotC] More stuttering

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1130]
### Short Description of the issue:
Guess the stuttering might not be related to having an old instance in a new build. Am now getting more stuttering and task manage shows Skywanderers using 86% to 100% of my GPU.

Log is full of this:

NullReferenceException: Object reference not set to an instance of an object
  at Game.CharacterSwappableBody.OnAnimatorIK (System.Int32 layerIndex) [0x00000] in <6c19256ac166472880c30fc7163041bc>:0 
 
(Filename: <6c19256ac166472880c30fc7163041bc> Line: 0)
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3225071/output_log.txt)
Only had 2 very small builds loaded in

**Comment by tsunamayo** [comment]
Okay I will try to fix the OnAnimatorIK first, and see if this could explain your stuttering - I keep you posted. In the meantime could you activate v-sync? Without v-sync it is normal if your GPU run full throttle if your are GPU bound. What is the rest of your PC config? Thanks

**Comment by Xerma** [comment]
V-sync does indeed drop GPU usage to about 50% but the game still stutters as before. 

Intel i7-7700K CPU @ 4.20GHz (quad core hyper threaded)
GTX 970
32GB RAM
64-bit

**Comment by tsunamayo** [comment]
I just fix the OnAnimatorIK error. It didnt appears in the editor for some reason, only in standalone. I will push a build soon, you will tell me if that makes things better - I keep you posted. Thanks!

**Comment by tsunamayo** [comment]
Okay new build - tell me if that fixed the issue! Thanks

**Comment by Xerma** [comment]
So far I haven't seen any stuttering however it didn't show up for a while last time

**Comment by Xerma** [comment]
Output log seems to be much smaller now too. Down to about 20 KB from about 400 KB in the last build

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks
