### ISSUE TITLE
[RotC] Activating Child Entity with Switch/Button/Slider then Toggling Manually Breaks Everything

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1132]
Alright, so to replicate this, place down any child entity, any control brick, then link them. Activate the control brick, then try to activate the child entity by clicking on it directly. This causes you to be unable to break, build, or activate anything, and also possibly teleport all child entities on a ship to the one you just activated.

**Comment by tsunamayo** [comment]
Okay  I tried your test case and it was working fine on my side. You think I might be doing something wrong? Thanks

**Comment by Senakysam** [comment]
I made a video showing what I did to reproduce it. You can skip the first 40 seconds of the loading screen, I just left it in for completeness sake. I've also attached the output_log. https://youtu.be/ZbbevXGZqSs
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3227979/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I understood, it is an issue linked to the hotkey system. What do you think of the new way of doing hotkey? I kinda preferred the old way with the old brick, it takes one more step but I think it was just more straightforward.

**Comment by Senakysam** [comment]
I think the old way has less issues with key bindings overlapping. Right now I use [e] to activate things, but it also messes with their hotkeys. 

Also, in the future, I think people will really want more hotkeys to set up stuff on their ship that animates when they press keys.

**Comment by tsunamayo** [comment]
yeah gotcha, I will revert it back to the old dedicated key with a UI. I think it is yet another example of the (faster / lest step) != (easier / better) fallacy.

**Comment by tsunamayo** [comment]
Okay I put an old school hotkey gate back in the game, for now UI is lame it will have to wait UI refresh. Thanks!
