### ISSUE TITLE
[RotC] Ship Sometimes Loads With Invisible Bricks

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1133]
Been working on a ship to test out the new build with, and every time it loads in, either by starting the world or loading it in by drone, there will sometimes be invisible bricks. Here are a couple pictures of the most recent instance.
![20190527223208_1](https://user-images.githubusercontent.com/26584892/58449110-bc76d200-80cf-11e9-82c1-824ad2744f06.jpg)
![20190527223217_1](https://user-images.githubusercontent.com/26584892/58449111-bc76d200-80cf-11e9-9f75-9ad5358036e9.jpg)
I'll private message you the ship file in Discord.

**Comment by tsunamayo** [comment]
This one is tricky - I see it sometime but I cant reproduce it often. Do you find it was entire brick or sometime just a few triangles from potential several bricks? Thanks

**Comment by Senakysam** [comment]
It seems to be the entire brick. Most of the time it happens, it's one of the hepta bricks on the front, but twice now I've seen a basic cube brick do it. Also, just now when looking for it in game, I saw a tetra piece do it as well. 
![20190528083023_1](https://user-images.githubusercontent.com/26584892/58482100-5d42ad00-8123-11e9-8804-4ff128c83b21.jpg)

**Comment by tsunamayo** [comment]
Okay new build - tell me if that fixed the issue! Thanks

**Comment by Senakysam** [comment]
Seems to be fixed now, I'll keep building and see if it comes up again.
