### ISSUE TITLE
[SUGGESTION] New Brick Shape

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1135]
So currently I'm working on wings for a ship, and I'm trying to get them angled without using any child entities. I can get them close, but it leaves an ugly gap. So, I'm asking for a new shape that could fill it in. Here are some pics of the wings where I need the block to fill in:
![20190529082012_1](https://user-images.githubusercontent.com/26584892/58565247-00fb8e00-81f4-11e9-8f74-5037bd86ba00.jpg)
![20190529082020_1](https://user-images.githubusercontent.com/26584892/58565248-00fb8e00-81f4-11e9-8ca7-ee54f301b8dd.jpg)
![20190529083344_1](https://user-images.githubusercontent.com/26584892/58565249-00fb8e00-81f4-11e9-8761-454544d154c2.jpg)
And here's a picture of a space I need the block for on the nozzle for the engines:
![20190529082026_1](https://user-images.githubusercontent.com/26584892/58565292-11ac0400-81f4-11e9-90f1-37838e10ab5a.jpg)

**Comment by ProPeach** [comment]
This would be great! I requested it before in #1082

**Comment by tsunamayo** [comment]
Gotcha, I am gonna need a name for this shape...

**Comment by ProPeach** [comment]
Tetra Twisted? Maybe Tetra Edge, I can't find the exact name for it other than a  "Triangular polyhedron, but that's a bit long :D

**Comment by Senakysam** [comment]
This sounds like something we would need a mathematician or some other high level education to know the correct name of. Or we can make one up.

**Comment by tsunamayo** [comment]
I like Twisted tetra ^^
Btw did you had the missing brick issue again?

**Comment by Senakysam** [comment]
Not so far, I'm keeping an eye out for it though.

**Comment by tsunamayo** [comment]
Okay I made those bricks. I realized we need two as they are not symmetric, and the two combined makes a corner brick. So I called them half corner left and half corner right so it would hopefully make sense. 
Works like a usb plug: first you try the left and it dont work, so you try the right and it dont work, then you try left again and this time it works...
