### ISSUE TITLE
[RotC] Entity still shows in drone UI after removal

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1136]
### Short Description of the issue:
After deleting an entity via drone, it still shows the stats and preview of the unspawned entity
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190530093701_1](https://user-images.githubusercontent.com/32974671/58640468-c14da880-82be-11e9-99e1-20fa74f41e88.jpg)

**Comment by tsunamayo** [comment]
Okay it is fixed! Thanks for catching all these issues! Cheers
