### ISSUE TITLE
[RotC] Stickers are still slightly wonky in some sloped areas

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1137]
### Short Description of the issue:
In some angles I either can place a sticker that gets stretched because of the positioning and angle of the brick (and cant seem to remove it) or I can't place a sticker and it instead places it on the surface behind what I'm aiming for. This isn't exactly a big issue to be honest, just funky but otherwise it works just fine
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190530103205_1](https://user-images.githubusercontent.com/32974671/58644485-f827bc80-82c6-11e9-9f2a-82c8ad7ac6f8.jpg)
![20190530103430_1](https://user-images.githubusercontent.com/32974671/58644493-fa8a1680-82c6-11e9-9fbd-df9f152cbe6a.jpg)

**Comment by tsunamayo** [comment]
Hi, this issue should now be fixed as decals tech has been replaced. Thanks!
