### ISSUE TITLE
[19w22b] Paint tool still not present in codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1139]
Just a simple one as the title says, the paint tool is only accessible by sampling the colour of a block though the middle mouse button wheel as it is not in the codex

![image](https://user-images.githubusercontent.com/27857711/58696202-00e3c580-838f-11e9-940e-688ff55cf74d.png)

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Yes indeed, glad you reminded me! It is now added back. Thanks!
