### ISSUE TITLE
[19w22b] Ships cannot move, only turn

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1140]
### Short Description of the issue:
When piloting a ship, you can turn it around with the mouse or keys, but it will not go forward/backwards in either manoeuvre or boost mode

### Steps to reproduce the issue:
Pilot a ship
Attempt to fly forwards or backwards

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1050M

**Comment by ZachZent** [comment]
Partially related, but for a very long time, the speed when flying the ship have been stuck on max. Either full speed or no speed. Thrusters=100. I was wonder when or if we will get it back as well as a hotkey for changes in ship thrust

**Comment by tsunamayo** [comment]
Okay fixed, it was just a simple miss I did when I updated the thruster block. Thanks!
