### ISSUE TITLE
[Suggestion] Move 19w22b to the Experimental branch, not Stable

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1141]
Although we have reported a lot of bugs and most have been fixed, there are still lots of small issues and missing features in 19w22b
Because of this, wouldn't it be more suitable to keep it in experimental for now? Especially as it will be the first experience of Skywanderers that many people will have with the coming backing wave.

**Comment by tsunamayo** [comment]
Yes, I dont want them to start building in the old build, only to loose their ship when migrating to the new one...
It dont make sense for them to learn the old way at this point.
As for the bug well I need to fix those...
If it is too bad then yep I will have to have them build on the old one (LEGACY is still there)

**Comment by tsunamayo** [comment]
Also to give you more color, the goal for me is to what difficulty newcomer have and how I could improve things. And have more bug reports to fix ;)
Cheers

**Comment by ProPeach** [comment]
You make good points, I was surprised to find you were publishing the build so early! I was mostly concerned about the game's image, it could reflect badly on development if a new players experience is hampered by many bugs. But then again, that's what this period is for, I'm glad you're using this to your advantage. Thanks for the response, we'll do our best over on Discord to help players out :)
