### ISSUE TITLE
[19w22b] Unable to access drone #1120

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1142]
### Short Description of the issue:
When the drone first spawns, the menu does not show when you press F on it until you place a block down. Looks to be a return on #1120 
...

### Steps to reproduce the issue:
Spawn the drone when a ship is present
Try to access it via F
Place a block on the ship
You can now access the drone
...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1050

**Comment by tsunamayo** [comment]
Sorry miss on my part, it is now fixed. Thanks!
