### ISSUE TITLE
[19w22b] Symmetry does not "Mirror" the placed blocks

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1143]
### Short Description of the issue:

The symmetry tool will place the blocks in the correct spot yet not mirror correctly

This is a ported Experimental era ship

...

### Steps to reproduce the issue:

Activate Symmetry 
place desired A-symmetrical entity 
inspect the opposite side  

...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1080ti

**Comment by tsunamayo** [comment]
Hi, thanks for booking the bug! So you mean the orientation of the block is incorrect while position is fine? If yes could you please tell me the block used? Thanks!

**Comment by ExodistSKY1** [comment]
Yes, the orientation is not correct.

It is the hepta, tetra, and corner blocks. (the big ones) 

The small half corner bricks do not place on the other side of symmetry (Just tested it)

![20190531051156_1](https://user-images.githubusercontent.com/45324484/58701231-f530d880-8367-11e9-93a1-80ab0a50e4a0.jpg)

![20190531051200_1](https://user-images.githubusercontent.com/45324484/58701237-f9f58c80-8367-11e9-8686-542dba199d7f.jpg)

![20190531051212_1](https://user-images.githubusercontent.com/45324484/58701242-fc57e680-8367-11e9-9b94-775b8da038e4.jpg)

![20190531054615_1](https://user-images.githubusercontent.com/45324484/58701244-feba4080-8367-11e9-82ab-7a6fee26f39b.jpg)

Hopefully this helps

**Comment by tsunamayo** [comment]
Thanks for the screen! Yes it helped, the hull block are now fixed. Thanks!
