### ISSUE TITLE
my game started to lag out and crash on the new build i was told to copy my output here

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Skywanderers#1144]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3240932/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that. So you launched the game, did nothing and it crashed? Or did you managed to do something before the crash? Also could you please tell me your PC spec, (CPU, RAM) and if your drivers are up to date, that could explain some issues. Thanks!

**Comment by tsunamayo** [comment]
Cannot investigate.
