### ISSUE TITLE
All blocks are invisible

### ISSUE THREAD

**Issue by Xxxsquidlover101xxX** [tsunamayo/Skywanderers#1145]
### Short Description of the issue:

...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay, thanks for booking the issue, could you please send me your output.log and your blueprint? Thanks

**Comment by Xxxsquidlover101xxX** [comment]
it's in another one, accidentally submited it while writing the report, and it's on all blueprints

**Comment by tsunamayo** [comment]
Gotcha I will close this one then. Cheers
