### ISSUE TITLE
[19w22b] exit to title screen causes scroll wheel to not work

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1148]
### Short Description of the issue:

When in game, if you exit to title screen and then enter the game again, the scroll wheel will not work. and you must restart the game

...

### Steps to reproduce the issue:

enter game
exit to title screen
re-enter game
scroll wheel will not work

...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1080ti

**Comment by tsunamayo** [comment]
This issue is now fixed. Thanks!
