### ISSUE TITLE
[19w22b] Sliding brick messes up with bricks

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1149]
### Short Description of the issue:

The sliding brick when used with Blocks is good. 

When you try to place bricks on the movement platform, the bricks act weird, then when deleted and replaced, the brick will be placed at another location and the sliding brick will have to be destroyed

...

### Steps to reproduce the issue:

place sliding brick
place brick on mounting platform
delete brick
retry placing brick on mounting platform 
the brick will be in another location 

...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1080ti

### Additional information:

This was after the brick was replaced...
![20190531091811_1](https://user-images.githubusercontent.com/45324484/58712839-fcb3aa00-8386-11e9-9bf6-64220d92d267.jpg)

**Comment by tsunamayo** [comment]
This slider was hacky and has been replaced with a small and large slider. This issue is no longer applicable, sorry for the inconvenience! Thanks!
