### ISSUE TITLE
[BUG] One side of mesh not updating when removing a block from other side using mirrors

### ISSUE THREAD

**Issue by bananatrooper52** [tsunamayo/Skywanderers#115]
It only happens on one side of the mirror, but when removing a block from that side, the mesh does not regenerate the block face on the other side in the removed region. This works for all blocks I have tested, but again, only from one side. When removing from the other side, the mesh does update correctly.

Before removing block from right side:
![screenshot_59](https://user-images.githubusercontent.com/16554889/31876966-6219b37e-b770-11e7-875a-58eefe2d5193.png)

After:
![screenshot_60](https://user-images.githubusercontent.com/16554889/31876970-68a6049a-b770-11e7-8952-a5231b245a5d.png)

**Comment by tsunamayo** [comment]
Thanks, it is an old known bug =( ! I will be refactoring the rendering pipeline at one point, it should be fixed then!

**Comment by bananatrooper52** [comment]
Well then I wish you luck on this one, whenever you decide to tackle it.

**Comment by tsunamayo** [comment]
This should be fixed now, cheers!
