### ISSUE TITLE
[19w22c] Starting new game creates ghost player model

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1150]
### Short Description of the issue:
A double of the player's model appears when first starting a new game. Editing player appearance causes it to disappear.

### Steps to reproduce the issue:
Create a new single player game. The ghost model should be nearby.

### Environment
- Skywanderers version: 19w22c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190531094803_1](https://user-images.githubusercontent.com/33041786/58713953-4dc49d80-8389-11e9-971f-db882dd43c43.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3241718/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed! Thanks a lot
