### ISSUE TITLE
[Bug] Mirror drone breaks during mirroring.

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Skywanderers#1151]
### Short Description of the issue:
When using the mirror drone it sometimes places a block on itself or tries to fly through a block. This causes it to stop, and spin in place, no longer working. There is a quick fix where you reset the mirror drone manually through the drone menu. 

...

### Steps to reproduce the issue: 
Use the mirror drone
Let it get stuck within a block
...

### Environment
- Skywanderers version: Newest update stable branch
- Graphics Card: GTX 1080 Ti 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by AsageSoftworks** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3241891/output_log.txt)

**Comment by tsunamayo** [comment]
Symmetry is now working differently with a new tool, so this issue is no longer valid. Thanks!
