### ISSUE TITLE
New Game - Floating in space and can't place blocks

### ISSUE THREAD

**Issue by kieran-s** [tsunamayo/Skywanderers#1153]
### Short Description of the issue:

Just downloaded the game, started it up, and I'm floating in space (although cant look down), the up/down movement hotkeys move me forward and back, there is a character model next to me, I can't swap blocks on my toolbar, and I can't place any block other than the starter block (and can't see where its going to be placed, and can place it multiple times in the same spot)

After saving and reloading, I can swap the selected block on the toolbar, but all other issues remain.
Pressing ESC removes the character model, but nothing else.
A steam file validation also changed nothing

...

### Steps to reproduce the issue:

Start a game
(Am available on skywanderers discord if needed to try things)

...

### Environment
- Skywanderers version: 19w22c
- Graphics Card: Nvidea GTX980

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://cdn.discordapp.com/attachments/342383722185883648/584172179998900244/unknown.png

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243205/output_log.txt)

**Comment by crash639** [comment]
I'm having the same issue

**Comment by Senakysam** [comment]
If you're having the same issue, link a copy of your output_log. It could help him identify the problem.

**Comment by kieran-s** [comment]
Tried out the "Legacy" branch on the betas page in steam, and am have the same issue

**Comment by Senakysam** [comment]
Legacy branch is for converting old ship blueprints from before october 2018 to the new save format. There isn't much of a reason to use it otherwise.

**Comment by kieran-s** [comment]
> Legacy branch is for converting old ship blueprints from before october 2018 to the new save format. There isn't much of a reason to use it otherwise.

Figured it was worth a shot, just to see if anything changed! :)

**Comment by crash639** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243219/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that. It seems there is a mix of several known issues (some of which are fixed, waiting to be pushed), plus a newer one. 
Could you: restart the game completely (quit to windows), then load, and send me the log file?
I just fixed quitting to main screen and reloading,  I will push a fix soon. Thanks

**Comment by crash639** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243225/output_log.txt)

**Comment by kieran-s** [comment]
This is a clean output log from starting the game (in main menu)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243224/output_log.txt)

**Comment by kieran-s** [comment]
This is the output log from immediately after starting a new game
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243226/output_log.txt)

**Comment by kieran-s** [comment]
Once it finishes processing, a video of the issue - https://www.youtube.com/watch?v=qYiwOPt2JNE

**Comment by CustomGraphix1** [comment]
Same issue, spawn floating in space, tried all 3 branches and reinstalled multiple times, dont have issue placing blocks though.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243241/output_log.txt)
![unknown](https://user-images.githubusercontent.com/51251519/58741546-0df5c880-8412-11e9-8a4c-53a90d790fd5.png)

**Comment by tsunamayo** [comment]
Okay I just pushed a new build, 19w22d. It fixes the fresh start issue. Could you please delete your save_data folder and recreate a new player?
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
Tell me how it worked. 
Cheers!

**Comment by kieran-s** [comment]
I can now look around properly, there are asteroids around, blocks seem to be placing properly, no dual model... All in all, looks like its working!

**Comment by KillerX32** [comment]
My game crashes when I place a starter.

**Comment by KillerX32** [comment]
hello?

**Comment by tsunamayo** [comment]
Hi, sorry to see that. So could you please join the output.log so I can investigate the issue? ( works fine for me) . Are you doing anything else beside placing a starter block? Thanks

**Comment by KillerX32** [comment]
i spawn, i can look around, but cannot move, and the game crashes when i attempt to place a starter block https://github.com/tsunamayo/Skywanderers/files/3243281/output_log.txt

**Comment by Senakysam** [comment]
What are your computer specs by the way?

**Comment by KillerX32** [comment]
> What are your computer specs by the way?

Intel(R) Celeron(R) CPU N3050 @ 1.60GHz 1.60GHg
4.00 Gb Ram

**Comment by KillerX32** [comment]
*Cough*

**Comment by tsunamayo** [comment]
Sorry I am away from my computer atm. What is your Gpu? Thanks

**Comment by KillerX32** [comment]
> Sorry I am away from my computer atm. What is your Gpu? Thanks Le 2019/06/01 à 12:06, KillerX32 <notifications@github.com> a écrit :
> […](#)
> Cough — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

is the GPU the processor? if so then it is: Intel(R) Celeron(R) CPU N3050 @ 1.60GHz 1.60GHg

**Comment by tsunamayo** [comment]
@KillerX32 Look like your spec is way below minimum spec. Do you have another computer to play to game on? Also what kind of other game do you play on this computer? Thanks

**Comment by crash639** [comment]
I have updated and deleted save data and tried again
Now spawning in a different location in space 
blocks are still invisible 
character now dose not persist after longing out
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243453/output_log.txt)

**Comment by crash639** [comment]
I trust that your working very hard on this problem and will try to be patient :)

**Comment by tsunamayo** [comment]
@crash639 So you are in game, you place an identity block and it become invisible? If yes could you please press F3, then deselect enable Occlusion. Thanks

**Comment by tsunamayo** [comment]
Okay guys, so there is a new patch 19w23d that should have fixed the issue. Thanks for your patience! Cheers
