### ISSUE TITLE
[Bug] Switch/Button and Holomap Interactivity Issue

### ISSUE THREAD

**Issue by TrueBeachBoy** [tsunamayo/Skywanderers#1155]
### Short Description of the issue:
Activating a switch or button attached to a holomap proceeds to make a constant clicking noise and make either holomap or switch undeletable.
This created lag, inability to turn head past certain angles, and the inability to view descriptions of blocks and studs in the inventory screen.
...

### Steps to reproduce the issue:
-Link any sized switch with any sized holomap
-Activate the switch (once for small and flat type and twice for the new slanted switch)
-Glitch/bug occurs
...

### Environment
- Skywanderers version: 19w22d
- Graphics Card: GTX 1050

**Comment by tsunamayo** [comment]
This issue is fixed for 19w31a. Thanks a lot! Cheers
