### ISSUE TITLE
[BUG]Scolling through hotbar randomly decides to replace selected blocks with some other block

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1156]
Short Description of the issue:
Game replaces items on hotbar with one of the other blocks in it
Basically, if your on engine block, and you scroll to brick wedge, it will change brick wedge in hotbar to engine, and this happens to any other part of the hotbar
You fix this by removing whatever block your scrolled on

Steps to reproduce the issue:
Im unsure, but just build and maybe alt-tab?
It tends to just... happen randomly

Environment
- Skywanderers version: 19w22d, the latest one
- Graphics Card: AMD Raedon HD 7500 Series

Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![Uploading 20190601150849_1.jpg…]()

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243331/output_log.txt)

**Comment by tsunamayo** [comment]
You had an issue with he drone that has since been fixed. Could you please tell me if you saw that happening again? Thanks!

**Comment by tsunamayo** [comment]
Okay this issue should be fixed in 19w32b. Thanks a lot!
