### ISSUE TITLE
[BUG]You can't place blocks on the side of an engine block

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1157]
Short Description of the issue:
The title says it all, you cant place blocks on engine block sides, bricks work though

Steps to reproduce the issue:
Place engine block
Try place block on the side of engine block (Bricks work)

also round engines and glowblocks return when

Environment
Skywanderers version: 19w22d, the latest one
Graphics Card: AMD Raedon HD 7500 Series

Additional information:
![20190601151421_1](https://user-images.githubusercontent.com/43084360/58743093-4ed7f680-847f-11e9-81c5-891063eb3016.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243334/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I dont have such issue, but by the look of the log file (thanks for including it) it is related to a previous drone issue. Could you please tell me if you still see the issue? Thanks for being an active tester ^^!
