### ISSUE TITLE
[BUG]Pressing F5 for drone makes drone invisible, and also breaks building

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1158]
### Short Description of the issue:
When I press F5 to summon the drone, its invisible, Not only this but I can no longer build

### Steps to reproduce the issue:
Press F5 to summon drone
You may be able to see "press E to (look at drone UI)
Also, building just doesnt work after this
...

Environment
Skywanderers version: 19w22d, the latest one
Graphics Card: AMD Raedon HD 7500 Series

 Additional information:
Notice how there is no blue outline
![20190601153335_1](https://user-images.githubusercontent.com/43084360/58743240-f3f3ce80-8481-11e9-92f4-f80cca548495.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243339/output_log.txt)

**Comment by tsunamayo** [comment]
Sorry mistake on me, I made a regression for a previous build. It is now fixed, in 19w22f. Thanks!
