### ISSUE TITLE
[BUG]Game freezes screen, but things can still be done 

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1159]
Short Description of the issue:
Screen freezes randomly, completely locking me out of doing anything else. However you can still technically do stuff, for example save the game, its just that nothing but the frozen screen is displayed
Has been going on for months

Steps to reproduce the issue:
Load up skywanderers
Play said skywanderers, and just do anything - after a random time your screen will freeze

Environment
- Skywanderers version: 19w22d, the latest one
- Graphics Card: AMD Raedon HD 7500 Series

Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243356/output_log.txt)

**Comment by tsunamayo** [comment]
Okay not sure to be able to reproduce. Could you please tell me if:
 - are you able to move at all - or is the screen completely still?
 - how are you sure you can save?
Also I need to make sure the output.log sent is the right one, this one doesnt seems to contains any issue. Thanks!

**Comment by tsunamayo** [comment]
Cannot investigate that issue.
