### ISSUE TITLE
[BUG]Cant play in windowed mode/screen issues after game closes

### ISSUE THREAD

**Issue by Corvixin** [tsunamayo/Skywanderers#116]
When I had launched the game for the first time I found that when I chose windowed mode, it would open the game and the unity logo would show and then the game would stop responding followed by an error message. I tried this several times and even uninstalled and reinstalled the game. At one point I did restart my computer and even then was faced with the same error. I was able to run the game in fullscreen mode however so I don't believe this is my computer. Also, I have started to notice that after the game is closed, I start to get some screen glitches where parts of the screen will just be squares and strips of light. This usually lasts between 1 and 5 minutes.
Files provided are from the crash report minus the dmp file as github doesn't support that file type.
[error.log](https://github.com/tsunamayo/Skywanderers/files/1406133/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1406134/output_log.txt)

**Comment by Corvixin** [comment]
So I was further able to find what the problem is. It seems that when I have Google Chrome open, this happens regardless of windowed or not.

**Comment by tsunamayo** [comment]
Hello, sorry to getting late on this, do you still have the bug? Could you please tell me your GFX card model, and also make sure that your graphical driver are up to date. Also in chrome do you have Hardware Acceleration enabled? Thanks
