### ISSUE TITLE
[NEW BUILD - DEFAULT / 19w22e] RTX hotfix

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Skywanderers#1160]
Tentative fix for High memory RTX cards. Thanks!

**Comment by Tommyg930** [comment]
No joy on RTX hotfix.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243431/output_log.txt)

**Comment by tsunamayo** [comment]
Are you a new backer (want to know if your save folder is empty or not)? I pushed a new version, the g, with an even lower buffer threshold. What I am not sure is why I only seems to see 3gb from within Unity. Sorry as I dont have a RTX it will be a bit painful to fix with a lot of back and forth, but we will figure it out! Thanks

**Comment by Tommyg930** [comment]
No, I'm not a new backer, but the save folder is empty. I reinstalled my computer from the ground up when I upgraded to the RTX card

**Comment by grumpysqirl** [comment]
New Backer... Experiencing the same problems.  hanging on the Loading Screen and or Crash to Desktop.
RTX 2080ti owner.

**Comment by tsunamayo** [comment]
So you can check 19w23d, bug should be fixed! Tell me if it works.
Thanks for your patience! Cheers

**Comment by grumpysqirl** [comment]
I was able to load in now.

**Comment by tsunamayo** [comment]
Okay great! Thanks for your patience, cheers!
