### ISSUE TITLE
Odd paint issue when loading an entity

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1162]
### Short Description of the issue:
As you can see there are some random spots of paint missing and showing the default color. Custom colors are loading in now too however the painted normals, such as the bolt, are not
...

### Environment
- Skywanderers version: 19w22f
- Graphics Card: GTX 970

### Additional information:
![20190601004834_1](https://user-images.githubusercontent.com/32974671/58744373-65426b80-8407-11e9-99ba-7b38a8468365.jpg)
(With a cheeky preview of the WIP MTT)

**Comment by tsunamayo** [comment]
Hum weird, could you please send me the blueprint? Thanks

**Comment by Xerma** [comment]
[Legal AAT MK1.zip](https://github.com/tsunamayo/Skywanderers/files/3244460/Legal.AAT.MK1.zip)

**Comment by tsunamayo** [comment]
This issue should be fixed with the new decals + paint workflow. Thanks!
