### ISSUE TITLE
[Suggestion/Bug/Request] Automatic Hull Type Conversion of Blueprints

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1165]
### Short Description of the issue:

When loading in the blueprints from older versions of the game, if they included any hull type other than the Basic Hull, the hull gets removed from the ship/blueprint when it is spawned in.

### Steps to reproduce the issue:

Spawn in a ship with any hull such as smooth, modern, tech or tiled hull into the new version of the game and note that all those hull types are removed.

### Environment
- Skywanderers version: 19W22G
- Graphics Card: Nvidia GTX 980Ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243476/output_log.txt)

### Additional information:
My suggestion is, simply as you have already done with replacing Basic hull in old builds with the new standard Hull, do the same with all other hulls. That is, have the blueprint/blocks automatically be converted from modern/tech/tiled/smooth hull, and have them be replaced with the new standard hull. So All hull types from the older version of the game gets replaced with the newer standard hull.
This will allow people to be stuck with only the task of perhaps repainting the hull blocks to something more suitable as opposed to potentially losing half their ship and needing to build it over again. A sort of automatic conversion when the blueprint is spawned. :)

Of course, if this is too tedious a task or won't work, this is understandable, I just think it would be helpful to those trying to transfer ships from an older version of the game with limited loss of actual ship hull/shape.
Thanks Tsuna <3

**Comment by tsunamayo** [comment]
Actually I already coded that auto-conversion, so there must be a bug. It is quite tricky as there are several format migration, typically now there is no blocks only bricks, so I must convert all block format to new brick format. Could you please send me one such blueprint so I can have a look at it? Thanks

**Comment by Sullos** [comment]
Hi tsuna, its a relatively medium-large ship, about 100m long from memory, but quite barebones. There seems to be a problem loading in the truly original blueprint which was built in Experimental. When spawned in, it is entirely invisible and doesn't seem to gain its visibility through a restart or waiting for it. And so I flew over to the invisible blocks, selected the ship, and using the drone re-exported the ship in game. Then I am able to spawn in the new ship after restarting the game. A bit tedious But I will attach two blueprint files, one which contains the original blueprint, straight from experimental, and the blueprint which actually successfully spawns in-game. "rapturerebuild14experimental" came from experimental, and the other file is the one that will spawn in-game and be visible.

[Ship Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/3243492/Ship.Blueprint.zip)

**Comment by tsunamayo** [comment]
Hi, so I tested and I can see both ship loading the same on my side. On this ship all non hull basic are removed? I dont know what it looked before. Thanks!

**Comment by Sullos** [comment]
Hi Tsuna, so yes the ship was originally supposed to have floors made of smooth hull, a few areas had tech and tiled hull as well, but only in very small quantities. Currently when loaded in game, the ship is mostly just a hollow hull, when it should have about 3 different floors mapped out with smooth hull. I will try and get some pictures together of what it used to look like :)

**Comment by Sullos** [comment]
Here's some pictures from what it looked like in Experimental before the change over.
From Above:
<img width="1920" alt="Skywanderers 2019-05-12 15-10-32-091" src="https://user-images.githubusercontent.com/33239800/58754677-2b618a00-8519-11e9-90e3-bb4a4c44dc26.png">

From the Red Airlock on the Port side of the ship:
<img width="1920" alt="Skywanderers 2019-06-02 09-34-56-824" src="https://user-images.githubusercontent.com/33239800/58754723-091c3c00-851a-11e9-8527-49781db77bba.png">

And various other shots of what the main floor of the ship looked like as it was made from the smooth hull, it is no longer there in the new version. 
<img width="1920" alt="Skywanderers 2019-06-02 09-35-19-337" src="https://user-images.githubusercontent.com/33239800/58754729-2fda7280-851a-11e9-9a89-5c8860dfac75.png">
<img width="1920" alt="Skywanderers 2019-06-02 09-35-42-993" src="https://user-images.githubusercontent.com/33239800/58754732-3c5ecb00-851a-11e9-92e7-a1009c6bf14a.png">

**Comment by tsunamayo** [comment]
Okay I fixed it, I can see the floor now. Will be in next update (the 22j or 23a) Thanks!
