### ISSUE TITLE
[19w22g] Bricks clipping into engine block

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1166]
### Short Description of the issue:
Bricks can be placed partially into the engine block.

### Steps to reproduce the issue:
Place an engine block, then select a brick. It can be placed on the sides of the engine block, clipping into the block.

### Environment
- Skywanderers version: 19w22g
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190601014800_1](https://user-images.githubusercontent.com/33041786/58744969-a8084180-840f-11e9-866d-8e578e2af244.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243504/output_log.txt)

**Comment by tsunamayo** [comment]
This one is actually fixed. Thanks!
