### ISSUE TITLE
repair tool broke all inrteraction

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Skywanderers#1167]
### Short Description of the issue:

...when I selected the repair tool I lost the ability to use the tool at all

### Steps to reproduce the issue:

...have the link tool in the slot behind the repair tool and scroll to the repair tool

### Environment
- Skywanderers version: 
- Graphics Card: Nvidia Geforce 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243518/output_log.txt)

**Comment by tsunamayo** [comment]
Issue will be fixed in next build. Thanks!
