### ISSUE TITLE
[19w22g] unable to build bricks on sliding door mechanism

### ISSUE THREAD

**Issue by David184** [tsunamayo/Skywanderers#1168]
it's dificuilt to build bricks on the sliding door mechanism because the game can't decide whenever it wants to interact with the sliding door or place the brick

...
How to reproduce bug.
Place down a sliding door mechanism and try placing a brick on it.

...

- Skywanderers version: 19w22g

![Slidingdoorbug](https://user-images.githubusercontent.com/51233566/58745619-45389980-8453-11e9-9a68-13c046bf21df.gif)

**Comment by tsunamayo** [comment]
Yes it is crappy, this whole brick is basically a hack. I will get rid of it to make a more straightforward sliding block (2 actually, a large and a small one). I keep you posted, thanks!

**Comment by tsunamayo** [comment]
This brick design is now deprecated, it should be much easier to build on the newer design. Thanks!
