### ISSUE TITLE
[Bug][19w22g] Block tetra has wierd texture glitch

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1169]
Short Description of the issue:
I simply placed and stretched out a block tetra, and it had a wierd texture
...

Steps to reproduce the issue:
Place down a brick tetra

Environment
- Skywanderers version: The latest hotfix? 19w22g?
- Graphics Card: AMD Raedon HD 7500 Series
Additional information:
_(Screenshots, Videos, Error logs, Related issues)_
![20190601195913_1](https://user-images.githubusercontent.com/43084360/58745677-cde12500-84a7-11e9-9e2f-a3b72fccd235.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243565/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue fixed including the other shapes. Thanks!
