### ISSUE TITLE
Ship Core Block lacks Directional Feedback

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#117]
The current ship-core block texture lacks any feedback to the player to indicate if it is in the correct alignment. It took multiple attempts before I managed to match the alignment of the pre-built ships in the Tutorial world, each time requiring a manual take over of ship controls to test.

I know learning a whole new control scheme and a new build system is difficult, but it would be nice to be given a little assistance on the orientation on some blocks visually. Just a little " ^ " indicator on the texture on the back would suffice

**Comment by tsunamayo** [comment]
Yes you are right, I wanted to come up with something different at some point: Either look at the direction of the engine (or the most common direction), or have menu where you can change it, or a mini holo of the ship that you can tilt. For now I will just update the texture.

**Comment by AfterRebelion** [comment]
The new core block tells you direction information, and even change them, so this issue is no longer valid in recent versions (19w23b)
