### ISSUE TITLE
Antivirus blocks Game.exe 

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#1170]
### Short Description of the issue:

1st of June, 2019, I tried to launch the game but Avast antivirus first ran a scan because the file was "behaving suspiciously" , then reported it to be clean, then quaranteened it anyway.
...

### Steps to reproduce the issue:
-Use Avast Antivirus (don't; it's crap :D )
-Let the game update to the latest patch
-Launch the game
...

### Environment
- Skywanderers version: 3879009
- Graphics Card: AMD R9 290

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ProPeach** [comment]
This isn't really a problem with Skywanderers, this is Avast being overly cautious. You'll need to create an exception in your Avast Antivirus software, there will be plenty of tutorials on their websites on how to do this, luckily it's very easy

**Comment by tsunamayo** [comment]
Hi, interesting, thanks for letting me know! I wonder if it is linked to the connection with Steam. But like ProPeach said there isnt much things I can do as it seems it is more on avast side as other player dont have issues. Thanks!
