### ISSUE TITLE
Massive Problem when you are too fast

### ISSUE THREAD

**Issue by Jokerplayer** [tsunamayo/Skywanderers#1173]
when you too fast in creative with you charackter
 (i used [-] or ß-´) your game will have some massive problems.

(Ships can't fly at the moment so i tried to explore the world with my charackter)

1. Go in creative
2. Click many many times on -´- or -]-
3. Press -W-
4. There should be some Graphic problems

i7 6700k 4,00 ghz
Asus GTX 1070 Strix OC
16gb RAM
250gb SSD

![20190601104247_1](https://user-images.githubusercontent.com/51260622/58748691-db34ea00-847c-11e9-93da-c6a1142e0b28.jpg)
![20190601104454_1](https://user-images.githubusercontent.com/51260622/58748692-dbcd8080-847c-11e9-8fbf-235980da680a.jpg)

**Comment by tsunamayo** [comment]
Ha I see, it is because you went waaay too far away. Renderer handle very large position but not ridiculously large position ;)
Now as the speed up / down are debug things that will be removed when the game is out, I wont really fix the issue. Thanks!
