### ISSUE TITLE
Ships don't fly, they only rotate

### ISSUE THREAD

**Issue by SilentHawk1** [tsunamayo/Skywanderers#1174]
### Short Description of the issue:
when I finish building a ship and connect the joystick to the control panel, it only allows me to rotate the ship, but it does not go anywhere
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: pre-alpha 19w22h
- Graphics Card: 1050ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Thanks, I fixed the issue and it will be up in the next patch today. Cheers!

**Comment by SilentHawk1** [comment]
Happy to Hear!! You're doing a great job man!
