### ISSUE TITLE
Ship core won't allign

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1175]
### Short Description of the issue: Ship Core won't ''rotate around forward'' won't work as intended in all axis.

...

### Steps to reproduce the issue: When i placed the ship core, no matter how much i try to align it to my ''forward'', it won't do it. I believe its an error in the move axis around forward. The only way i can make it face forward is upside down, and when i try to ''rotate around forward, it won't work as intended''
...

### Environment
- Skywanderers version: Sorry i don't know how to check it. 
- Graphics Card: GTX 1080 TI

### Additional information: 
After i get it to face forward its upside down.
https://ibb.co/HHV7Sfw

Then i click on rotate around forward and this happens.
https://ibb.co/DbMNGqf

Please also include the `output_log.txt` file. You can find your log here: 
https://mega.nz/#!wsokCQSI!MENZ2ObMXznoTsZQ2DsOhZDXoQV3wsaF6ArqbRT4uRo

**Comment by ExodistSKY1** [comment]
This is a transfer from the previous update

Tsuna, when in game using the reverse feature it reverses and flips the ship rather than pointing the ship in the opposite direction.

**Comment by tsunamayo** [comment]
Hum I dont get the same behaviour, it seems to work normally on my ship. Could you please send me your blueprint so I can investigate further? Thanks!

**Comment by Zeuscp1** [comment]
https://mega.nz/#!o4wmzQ6R!CtrALZyQ3O9C1OQxkDsashRb-985IXeOwudPl2ovIEU 

This is my blueprint, by the way many people are having this issue (we talk about it on discord ) and i think its related with the reverse feature too but there you go check it out

**Comment by tsunamayo** [comment]
Okay I finally fixed it! Thanks for your help, I :heart: my testers...
