### ISSUE TITLE
[19w22h] Symmetry Drone breaks and spins.

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Skywanderers#1176]
### Short Description of the issue:
Similar issue to what I had previously. Mirror drone starts spinning in place when placing blocks using the mirror mode. Occurred after about 100 blocks. 
The secondary issue, mirror drone will not remove free form blocks of any kind.

...

### Steps to reproduce the issue:
To reproduce drone breaking bug, just have to use the drone for awhile. I think it gets confused due to it not wanting to break free form blocks.

to reproduce drone not deleting free form, place down free form with mirror plane, then delete on one side. the drone will not delete the mirrored block.

...

### Environment
- Skywanderers version: 19w22h
- Graphics Card: GTX 1080 TI

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243980/output_log.txt)

**Comment by Xerma** [comment]
Just now experiencing this bug after the latest hotfix

**Comment by tsunamayo** [comment]
Symmetry is now working differently with the tool, so this issue is no longer valid. Thanks!
