### ISSUE TITLE
Back of small tile does not render

### ISSUE THREAD

**Issue by kieran1234** [tsunamayo/Skywanderers#1177]
### Short Description of the issue:
The back side of small tile bricks do not render
...

### Steps to reproduce the issue:
...

### Environment
- Skywanderers version: 19w22h
- Graphics Card: GTX 970

### Additional information:
![20190601173642_1](https://user-images.githubusercontent.com/9012239/58751236-07a83080-8494-11e9-9d70-882139f6ed81.jpg)
![20190601173646_1](https://user-images.githubusercontent.com/9012239/58751237-0840c700-8494-11e9-9750-f8dae6658be2.jpg)

[Tile Bug.zip](https://github.com/tsunamayo/Skywanderers/files/3243999/Tile.Bug.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3244001/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this brick is fixed now. Thanks
