### ISSUE TITLE
[19w22b] random paint on spawned in ship

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1178]
### Short Description of the issue:

When loading in a ship it will have random spots of color 
(Ship was fully made in the new update)

...

### Steps to reproduce the issue:

using the drone spawn in a ship made completely in the new update
look at results 

...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: GTX 1080ti

![20190601113039_1](https://user-images.githubusercontent.com/45324484/58751867-6d7fc280-846a-11e9-91d6-3562df6d4f29.jpg)

**Comment by tsunamayo** [comment]
Looks good ^^ Could you please send me the blueprint so I can see what is wrong with this one?
You can press F5 to toggle the drone, then build a brick and open the drone, then click save to create the blueprint.
Blueprint will be located in:
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Blueprints
 Thanks

**Comment by ExodistSKY1** [comment]
Ill send it via Email

**Comment by ExodistSKY1** [comment]
Tsuna,

Attached is the BP for the ship…

It happens from time to time and I cant find a pattern to it.


ALSO… I have had the game since the kickstarter and I am loving this new update! Thank you for continuing your progress and going in this direction! I am extremely pleased and excited to see where you take this.

Respectfully,
                  Kevin (Exodist)

________________________________

**Comment by tsunamayo** [comment]
This issue should be fixed with the new workflow (tell me if it is actually not the case!) Cheers!
