### ISSUE TITLE
[Suggestion] Brick-sized Rail block

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Skywanderers#1179]
Because the new rail has a 4x2 attach point it can no longer be used in a 1m configuration, for things like very small ship landing gear, because it cannot move unless it is at least 2 meters long. I'd reccommend a brick scale rail to bridge the gap, since there's nothing inherently wrong with the block one.

**Comment by tsunamayo** [comment]
Yes correct, so the plan for slider is I will replace current one with a 1m one and a 0.25cm one, like for everything else. It should allow you to do smaller moving mechanism. I keep you posted. Thanks!

**Comment by AfterRebelion** [comment]
This was made avaliable in 19w29a

**Comment by tsunamayo** [comment]
Yes this brick has been added. Thanks a lot!
