### ISSUE TITLE
MOTOR AND LOGIC DONT WORK

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1180]
I the motor and the logic dont work.

I can turn on me with ship but i cant move with them.
The logic dont work you dont have make all logic.

...

idk

...

Cordialement 🏮𝓖𝖆𝖒𝖇𝖎𝘁❻

**Comment by Sullos** [comment]
Are you saying you can’t fly a ship forward with the engines?
As well as logic not working? If so what parts of logic are you using that aren’t working?

**Comment by tsunamayo** [comment]
Hello / bonjour,
Issue with engine/thruster is fixed (will be in next patch)
I would need a test case for the logic though, what is not working exactly?
Le probleme avec le moteur est fixe et sera bientot dispo.
Pour le probleme de logique, peut-tu m expliquer plus en detail ce qui ne marche pas?
Merci!

**Comment by Gambit06** [comment]
thank you sorry for my very bad english.

**Comment by Gambit06** [comment]
> Voulez-vous dire que vous ne pouvez pas faire avancer un navire avec les moteurs? 
> Ainsi que la logique ne fonctionne pas? Si oui, quelles parties de la logique utilisez-vous qui ne fonctionnent pas?

Sorry for not responding Sullos.
