### ISSUE TITLE
Mass of bricks/blocks stays constant even when stretching

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1182]
Mass and volume of stretched blocks/bricks does not scale as you'd think, a placed block will have the same massif it is 1m^3 or 16m^3

1 block placed
![image](https://user-images.githubusercontent.com/27857711/58754575-34c40580-84cb-11e9-9f1a-3d6501b4240e.png)
Block stretched to 16mx16mx1m
![image](https://user-images.githubusercontent.com/27857711/58754581-4efde380-84cb-11e9-8d50-8a0063b99acd.png)

### Steps to reproduce the issue:
Check the mass added to a ship through the ship core/drone when you place different sized stretched blocks/bricks
...

### Environment
- Skywanderers version: 19w22h
- Graphics Card: GTX 1050M

**Comment by MormegiI** [comment]
Can confirm. Actually I was the one to find it and asked in Discord whether it was intended. Thanks for reporting ProPeach!

**Comment by tsunamayo** [comment]
Good catch, thanks you both I just fixed the issue. Cheers!
