### ISSUE TITLE
GPU usage spikes every few seconds, causing lag

### ISSUE THREAD

**Issue by Daomephsta** [tsunamayo/Skywanderers#1183]
### Short Description of the issue:

Upon opening SkyWanderers, FPS and GPU usage are normal.  
Once any save is loaded GPU usage begins spiking every few seconds. Spikes continue even if the save is unloaded and I return to the title screen. While in a save GPU usage spikes from ~66% to 100%. When not in a save, but one has been loaded in the current session, GPU usage spikes from ~20% to ~35%.  
The spikes occur whether V-Sync is on or off.

### Environment
- Skywanderers version: 19w22h
- CPU: Intel i5-4460 @ 3.20 Ghz
- Graphics Card: Nvidia GTX 750
- RAM: 16GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3244366/output_log.txt)

**Comment by Daomephsta** [comment]
Still occurs in 19w22i

**Comment by tsunamayo** [comment]
Hello! Does this happens randomly or  does it depend on what you are looking at? 
Could you please send me a screenshot of the FPS counter? To activate it press F3 and hit Show FPS stats, let it run for a bit and then take the screenshot.
Thanks!

**Comment by Daomephsta** [comment]
It happens consistently every few seconds, as long as any save has been loaded during the current session, even if no save is currently loaded. What I'm looking at doesn't seem to matter.
![FPS Counter](https://user-images.githubusercontent.com/10936237/58759517-862dcc80-857f-11e9-918e-7d8f1afb43e9.jpg)

**Comment by Daomephsta** [comment]
As of 19w23a, my game no longer lags every few seconds. FPS varies between ~35-60, which is also good. Thanks for the quick improvement!

However GPU usage is nearly 100% all the time.   
Here's another screenshot of the FPS counter. I think the minimum of 17 is from just after save load, because it doesn't get nearly that low the rest of the time.
![20190604173522_1](https://user-images.githubusercontent.com/10936237/58853699-30783200-86ef-11e9-856f-7df41494a6aa.jpg)

**Comment by tsunamayo** [comment]
Have you activated V-sync? Thanks

**Comment by Daomephsta** [comment]
V-Sync is on yes. I've tried tinkering with all of the ingame graphics settings, none of them stop the 100% GPU usage.

**Comment by tsunamayo** [comment]
I think you are being simply GPU bound, your GPU is quite low-end.

**Comment by Daomephsta** [comment]
Seems so, thanks for investigating. I have found a workaround though. The issue now **does** depend on where I look. Flying out of the ring system has decreased GPU usage down to 70-80%, which makes sense, the rings contain a lot of asteroids, so not having to render them makes a big difference.

I'll close this now then.

**Comment by tsunamayo** [comment]
Yes, and actually because my asteroid tech is so specific it could put a bit of strain on older GPU. I will switch my tech to something standard soon. Thanks!
