### ISSUE TITLE
Extreme Lag, GPU Maxed

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1185]
After a crash, the game is now extremely laggy. 10, 15 frames per second. A complete wipe of the game and all its files have not fixed it

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3244403/output_log.txt)

**Comment by tsunamayo** [comment]
Hum looks bad. Do you have backuped and cleared you save file also? Did you made something special that could have lead to the crash? Is it still happening after a reboot? Thanks!

**Comment by tsunamayo** [comment]
Hi @ZachZent , is this something you still get as of recently? Thanks!

**Comment by ZachZent** [comment]
No it isn't. I don't remember what fixed it, but it was one of those simple IT generic suggestions, the ones after turn it on and off.
