### ISSUE TITLE
Character Blink when movin

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1186]
### Short Description of the issue:
Character blinks (teleports) when moving
...

### Steps to reproduce the issue:
I don't know how to reproduce it since for me at least seems to be randomly but now it won't stop. 
...

### Environment
- Skywanderers version: Last Build
- Graphics Card: GTX 1080TI

**Comment by tsunamayo** [comment]
Did you press the ] key? Could you press the [ key a few time to see if it fixes it? [ is to move slower and ] is to move faster. Thanks!

**Comment by Zeuscp1** [comment]
I just tested this, and no. It doesn't fix it sadly. By the way i'm sorry to bother you but would you review my report on the ship core?

**Comment by tsunamayo** [comment]
Hum I am not sure I understand the case, are you in first person or in third? How far the character jump? (like a few meter, or much more?) Thanks

**Comment by Zeuscp1** [comment]
Update. This only happens when i have google chrome Netflix open and playing while listening to a show im watching. (NETFLIX) Witch its weird. its the only time that happens and it jumps lets say like a few meter or less, the more the speed you have the more aggressive it is, but again when netflix is not open this won't happen

**Comment by tsunamayo** [comment]
Is it because the game is somehow lagging? Thanks

**Comment by Zeuscp1** [comment]
Probably
