### ISSUE TITLE
Piloting a ship moves the player camera, when player is seated.

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Skywanderers#1187]
When you activate the yoke, your view will change slightly, going towards the yoke. You can see it in 
[these screenshots.](https://imgur.com/a/hJ9xF7t)

Steps to reproduce:
Enter a seat
Activate a yoke (tied to ship core)
Camera view will change noticeably, especially when exiting control of the yoke.

NOTES:
The jump doesn't happen if the player is not sitting. It is tied to sitting in a pilot chair.

**Comment by Starwhip** [comment]
Slight correction. View moves upwards, not towards the yoke.

**Comment by Dwarf-LordPangolin** [comment]
Question: is the camera aligning with the [ship's forward direction](https://github.com/tsunamayo/Skywanderers/issues/538)?

**Comment by tsunamayo** [comment]
Good catch, issue is now fixed. Thanks!

**Comment by tsunamayo** [comment]
Thanks for the screenshot btw!
