### ISSUE TITLE
[19w22b] curved block does not place correctly

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1188]
### Short Description of the issue:

the curved block does not place correctly and is half inside of the area it is placed

...

### Steps to reproduce the issue:
place the curved block
...

### Environment
- Skywanderers version: 19w22b
- Graphics Card: 1080ti

### Additional information:

![20190601230656_1](https://user-images.githubusercontent.com/45324484/58756669-24a82800-84c3-11e9-9528-46e39114c1f0.jpg)

**Comment by Breezebuilder** [comment]
Issue is also present in 19w22i (latest).

**Comment by tsunamayo** [comment]
Issue is now fixed! Thanks
