### ISSUE TITLE
[Suggestion]Change drag axis for bricks

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1191]
It gets pretty annoying when you need to place a block behind something to use stretchy blocks and bricks correctly, so why not when you press some button like [shift] it changes the way/axis you drag out the blocks? So if placing a brick on a surface and stretching it out now stretches it horizontally, pressing [Shift](for example) stretches freeform vertically relative to the block your placing on. It also has to be an intutive method, so if shift doesnt fill that role, then maybe some other easy key

**Comment by tsunamayo** [comment]
Not sure if it is exactly what you are asking for but when you hold the mouse button you can press q (or your  rotation key) to switch expand plane. Thanks

**Comment by ultrak2k** [comment]
Oh.

**Comment by tsunamayo** [comment]
Does that fill the need you were having? I like the idea of doing the setting before holding, but I dont like to add keybind ;) cheers
