### ISSUE TITLE
[19w22b] cockpit suggestion 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1192]
Suggestion:

     I am not sure if you plan on keeping these windows in game or updating their look while keeping the same footprint. I would like to suggest that they stay in game!

![20190602112452_1](https://user-images.githubusercontent.com/45324484/58764247-851e8000-852a-11e9-94b6-6541b7b7d7b8.jpg)

I do find these blocks useful for many things including a different cockpit style over the new rounded cockpits recently implemented.

![20190602112316_1](https://user-images.githubusercontent.com/45324484/58764276-d3338380-852a-11e9-89a0-c11b7f663eb1.jpg)

![20190602112331_1](https://user-images.githubusercontent.com/45324484/58764277-d62e7400-852a-11e9-8daf-08c19bea462a.jpg)

![20190602112350_1](https://user-images.githubusercontent.com/45324484/58764278-d9296480-852a-11e9-8c5e-a09a2105c01b.jpg)

**Comment by tsunamayo** [comment]
I am not sure to understand, what is the suggestion, me not removing those block? I will add/improve cockpit to give more option for sure. Thanks!

**Comment by ExodistSKY1** [comment]
Correct I apologize for not being clear. I noticed they looked the same as the previous update and was not sure what your plans were for them.

Suggestion:

Keep those blocks please!



On Jun 2, 2019, at 8:20 PM, Francois Duret <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure to understand, what is the suggestion, me not removing those block? I will add/improve cockpit to give more option for sure. Thanks!

**Comment by tsunamayo** [comment]
Ah okay, yes I dont plan on removing them! Thanks
