### ISSUE TITLE
[Bug/Missing error message] Blueprint export fails due to certain characters

### ISSUE THREAD

**Issue by MormegiI** [tsunamayo/Skywanderers#1195]
### Short Description of the issue:
If the Blueprint name contains characters that are not allowed for Windows filed (e.g. / \ ? * etc.)
the blueprint will not be created and the user will not get any notification/error message. Therefore the Export button seems to be dead. 

### Steps to reproduce the issue:

Save a blueprint containing any of the non-allowed characters. No file will be created.

### Environment
- Skywanderers version: current
- Graphics Card: GTX770

### Additional information:
Not a bug per se, but an error message would be nice to avoid loss of blueprints.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3245123/output_log.txt)

**Comment by MormegiI** [comment]
Actually found a second bug connected to this: All Blueprints are named "Spaceship1",2,3,4 when loading them ingame, even when the Blueprint had a different name when saved. Refer to attached screenshot...

![Loading Blueprints](https://user-images.githubusercontent.com/51251532/58767624-82ee0d00-858e-11e9-8c4b-2a222047e3e4.png)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3245258/output_log.txt)

**Comment by tsunamayo** [comment]
I fixed the first bug but I cant reproduce the Spaceship 1 one - but it was also reported by other people. Is this something you get all the time? Thanks

**Comment by tsunamayo** [comment]
Okay I finally reproduced the issue and fixed it. Thanks!
