### ISSUE TITLE
Hinge angles are off by factor 2.

### ISSUE THREAD

**Issue by MormegiI** [tsunamayo/Skywanderers#1196]
### Short Description of the issue:

When using hinges they only move by half the angle defined in the sequencer. When looking at the hinge they show double the actual angle.

### Steps to reproduce the issue:
Use hinge at let it move. Check angle.

### Environment
- Skywanderers version: current
- Graphics Card: GTX770

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3245291/output_log.txt)
![Angle-Bug](https://user-images.githubusercontent.com/51251532/58767961-656f7200-8593-11e9-87d3-274e82e2dd95.png)

**Comment by MormegiI** [comment]
Additional bug: The sequencer does not save its values. If you define angles (e.g. 0 and 180), save the world (F1), close and reload, the sequencer will be set to 0 and 0 again.

**Comment by tsunamayo** [comment]
Thanks for reporting the bug, issue is now fixed! Cheers
