### ISSUE TITLE
Window Wedge/Hull Trans graphical issue

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1197]
### Short Description of the issue:
It seems window wedges have an odd grey spot in the center when stretched to 2x2 or greater and the same goes for Hull Trans. Another thing with Hull Trans is I'm getting a very peculiar hitbox with it when it comes to placing thing on it
...

### Environment
- Skywanderers version: 19w22i
- Graphics Card: GTX 970

### Additional information:
![20190602193657_1](https://user-images.githubusercontent.com/32974671/58769644-72c63580-856e-11e9-823f-851c81661ef3.jpg)
![20190602194253_1](https://user-images.githubusercontent.com/32974671/58769697-07309800-856f-11e9-8c83-f871a468f5fc.jpg)
![20190602194500_1](https://user-images.githubusercontent.com/32974671/58769700-0992f200-856f-11e9-86f6-fe6630c5030d.jpg)
![20190602194502_1](https://user-images.githubusercontent.com/32974671/58769702-0dbf0f80-856f-11e9-9620-037c9fb15b7e.jpg)
![20190602194511_1](https://user-images.githubusercontent.com/32974671/58769703-10216980-856f-11e9-9685-bc7c1deaddc4.jpg)

**Comment by Xerma** [comment]
Forgot another graphical issue regarding windows: The new window with a rounded trim has an odd graphical thing going on in the corners when stretched in any fashion
![20190602195020_1](https://user-images.githubusercontent.com/32974671/58769762-c7b67b80-856f-11e9-914c-329ca3abead3.jpg)

**Comment by tsunamayo** [comment]
Okay all issues are fixed. Thanks!
