### ISSUE TITLE
Blocks and Mirror issue

### ISSUE THREAD

**Issue by HyperPlut0** [tsunamayo/Skywanderers#1198]
### Short Description of the issue:

When mirror is on, if blocks are deleted too fast there will be blocks that you can walk through and not delete, also when the entire ship entity is deleted the (F5) robot still mirrors my blocks. 

### Steps to reproduce the issue:

Build a lot of blocks with mirror on and delete them quickly.

### Environment
- Skywanderers version: pre-alpha 19w22i
- Graphics Card: Geforce Nvidia GTX 1050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
So mirroring is working differently now, so this issue is no longer valid. Thanks!
