### ISSUE TITLE
[Suggestion] Drone suggestions

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1199]
I and other people have heard quite a lot of people complain about the drones where it either is too slow or too janky, and whatnot, or that the mirror block didnt need to be removed
Maybe the drone should be quite alot faster, if not be able to short range teleport?
It should have a little bit more reach
And/or... just bring the mirror block back since it worked flawlessly and allowed multi plane mirroring

Also the fact that people have to ask how to use it instead of figuring out means its less then intuitive, perhaps make it a key more easy to find, or display on screen the key.

**Comment by tsunamayo** [comment]
Yes I will change the way symmetry works. I dont like having a brick, cause you might forget were it is ect, but it will be an item, so close to what we had before and instantaneous. I did a lot of change relative to symmetry, issue are linked to the stretching tech more than the new drone (like the delete issue).
Also yes I need to improve the overall usability. 
My plan for the drone was just to start working on AI and see the potential difficulty.
But the plan is to have shipyards, people will build inside shipyard, buy blocks here, and respawn their ship when getting destroyed. The shipyard menu will be either F5, TAB or else, and will always be accessible.
Thanks

**Comment by ultrak2k** [comment]
> Yes I will change the way symmetry works. I dont like having a brick, cause you might forget were it is ect, but it will be an item, so close to what we had before and instantaneous. I did a lot of change relative to symmetry, issue are linked to the stretching tech more than the new drone (like the delete issue).
> Also yes I need to improve the overall usability.
> My plan for the drone was just to start working on AI and see the potential difficulty.
> But the plan is to have shipyards, people will build inside shipyard, buy blocks here, and respawn their ship when getting destroyed. The shipyard menu will be either F5, TAB or else, and will always be accessible.
> Thanks

When can we expect a mirror tool?

**Comment by tsunamayo** [comment]
Note sure, but I will try to do it asap... There is just tons of bug to fix these days... I keep you guy posted.

**Comment by tsunamayo** [comment]
Okay it is live in 19w23d. Hope you like it! Cheers
