### ISSUE TITLE
[Med] New structures not saved

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Skywanderers#12]
I found that new structures built with a starter block are not saved.
To reproduce, I made a small change to the big ship and created 2 new structures near by. With the first I kept the start block and the second I removed that after placing some other blocks. Neither of these new structures was there when reloading the save but my changes to the big ship were. I lost all my work on my ship from this morning Neutral
David

Arf really sorry for that, I wanted to separate the new block functionnality to the save / identity one because you might want to move the save block in other position in you ship after you started it. I did not save new build by default because during testing we constantly create new dummy build and it was cluttering the save folder, but maybe I will do the following :
* Ask for a name when using the starter block
* Leave an option to just start building without saving.

**Comment by AfterRebelion** [comment]
This no longer happens in recent versions (19w23b)
