### ISSUE TITLE
Game can ignore character inputs, and ESC menu tracks with Mouse

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#120]
I dont know what key did this, might have been one of the F1-12 keys. But after pressing it I lost control of the character for left/right (A+D) strafe movement and could only use mouse to aim and forward/back. 

When I pressed the Escape key, the menu followed the mouse pointer and was unable to select options via the mouse.
Eventually spamming a few keys got the control back, but lack of indication (And no deeper full keyboard control schematic visible so I know what the cool buttons are / ones that will destroy my world are) as to what I just did wrong to mess up my character can be frustrating.

**Comment by tsunamayo** [comment]
Hello, sorry for that indeed I think you just pressed F12, which is a mode I coded to take screenshot with the character as it freeze time and let you have an out of body trip. 
I will remove this functionality as it is a confusing - maybe one I will add a proper user friendly "photo mode".

**Comment by Napther** [comment]
It also conflicts with the Steam Screen shot feature. So f12 is a little redundant in that regard when Steam is the main product platform.

**Comment by tsunamayo** [comment]
Agreed, I should also try to use F keys the way they are commonly used in other game. I was thinking in changing F4 (3rd person) to F5 like minecraft.

**Comment by tsunamayo** [comment]
Fixed (or removed to be fair), it will be in the next build.
