### ISSUE TITLE
[Bug] Graphical Bug - Back of Engine Block Texture Warp

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1200]
### Short Description of the issue:

The back of the engine block, when placed as a relatively large single engine block, has a weird graphical issue on the back of the engines. Not the glowing side but the technical side.

### Steps to reproduce the issue:

Place a 'wall' of engines and look at the back of them.

### Environment
- Skywanderers version: Most recent
- Graphics Card: 980Ti

### Additional information:

<img width="1920" alt="Skywanderers 2019-06-02 09-43-08-889" src="https://user-images.githubusercontent.com/33239800/58776074-0c8ff000-860c-11e9-8756-e18af86d36e4.png">

**Comment by tsunamayo** [comment]
thats _weird_ ...

**Comment by tsunamayo** [comment]
Okay indeed, I will just put a simple for now, until I get more time to do a proper texture (back of block is not really high priority atm ...) Thanks!
