### ISSUE TITLE
[Suggestion] Bring back window corners

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1202]
### _Uuuuuse my knowledge, I beg you_ ###

I've only just noticed the new codex doesn't include the good ol' window corners/flat tetras as you can see here:

![20190603003505_1](https://user-images.githubusercontent.com/32974671/58778422-27288180-8598-11e9-8274-76f01f020854.jpg)

Would be much appreciated to have these back, thanks!

**Comment by tsunamayo** [comment]
Noted. Hum this piping work is sexy ...

**Comment by tsunamayo** [comment]
Okay I added this brick a couple of update back! Thanks
