### ISSUE TITLE
[Bug] Can't Build off the side of an engine block

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1203]
### Short Description of the issue:

I was trying to build a panel of engine blocks and placed an engine block as a bit of scaffolding, then noticed that when you look at the inner part of the side of an engine block that you can't build off of it, because it thinks you're trying to place another block inside of it.

<img width="1920" alt="Skywanderers 2019-06-03 21-00-58-826" src="https://user-images.githubusercontent.com/33239800/58797285-f81b1a00-8642-11e9-91d4-1dfc202a69c7.png">

As shown above. If I aim at the inner, more technical looking face of an engine block, it thinks I'm trying to build inside of it, rather than off of it.

Whereas (shown below) If I aim right at the bevelled edge of the engine block, it correctly thinks I'm trying to build off the side of it as normal. I think it's just a hitbox issue, but something I figured worth reporting.
<img width="1920" alt="Skywanderers 2019-06-03 21-01-03-169" src="https://user-images.githubusercontent.com/33239800/58797334-1a149c80-8643-11e9-8a8a-25f8e1c57b56.png">

### Environment
- Skywanderers version: Most recent
- Graphics Card: 980Ti

Thanks, Tsuna, also might we able to get the next Hotfix of bug fixes sent out ;P
As always keep up the great work

Edit: I just saw that someone posted a similar bug that’s already been closed, hoping mine might offer more insight into the issue if it wasn’t fixed before.

**Comment by tsunamayo** [comment]
Okay I think I didnt not understood / reproduce correctly he first time. Now it is fixed. Thanks!
