### ISSUE TITLE
[Bug] Game crashes when enabling vsync

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1204]
### Short Description of the issue:

The game crashed when enabling v-sync in the graphics options menu. 
I will try to reproduce again, however, now the game will no longer open at all. I launch it and the game says active then disappears almost immediately.

### Steps to reproduce the issue:

As far as I know, enable vsync.
I will do a fresh install and try again.

### Environment
- Skywanderers version: Most recent
- Graphics Card: 980Ti

### Additional information:

I would include the output log, however, I checked it and it didn't have any useful info. I will still include it.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3247287/output_log.txt)

Edit: Fresh install didn't fix, nor did deleting the Skywanderers folder in AppData.
Edit Again: Restarting PC fixes problem allowing the game to be started again. My guess is when the game crashes a background process utilised by Skywanderers is left open and as it remains open the game won't open again. I tried enabling v-sync again, and the crash didn't repeat. However, earlier today when playing a similar situation when unticking a box in the F3 menu crashed my game and only restarting the PC fixed it. So sadly I can't yet truly recreate the issue.

**Comment by tsunamayo** [comment]
Hum sounds bad... When you say you cant relaunch, were does it bug? Could you send a log of you trying to relaunch next time you see a crash? Also could you please send me your crash info (there must be a Crash folder in \AppData\LocalLow\TsunamayoCorp\Skywanderers)? The log is empty.

**Comment by Sullos** [comment]
I am still unable to forcefully recreate the crash, but if it does happen again I will let you know. 
As for the crash folder, sadly there isn't one, and it wasn't generated on either of the two occasions.
If one does generate in future, I will include it here.

When the game did crash though, Skywanderers was no longer running, and I was brought back to my Steam Library. I try running Skywanderers from steam, steam tells me that the game is running for a few seconds and then goes back to letting me try to open it again.
No skywanderers windows open at all after trying to run the game again.
It's very strange, I will update you if I find any cause.

**Comment by tsunamayo** [comment]
It might be steam related, or it might be because of the network host created on a port that is not freed during the crash...

**Comment by tsunamayo** [comment]
Cannot investigate.
