### ISSUE TITLE
RTX 2080 Crash/Hang on Character Creation

### ISSUE THREAD

**Issue by SmOOvDoGG** [tsunamayo/Skywanderers#1205]
### Short Description of the issue:

Game fails to load and hangs after creating a new SP character

### Steps to reproduce the issue:

- Click Play
- Click Single Player
- Click Create a new character
- Enter a name
- Click play with this character

### Environment

- Skywanderers version: 
- Graphics Card: MSI RTX 2080
- Win10
- DxDiag.txt attached

### Additional information:

**Video of Reproduced Steps - https://youtu.be/63-rvRDl5FU**
You can hear the exact moment the game crashes during the loading screen. There is a distinct sound of sand or a hi-hat being stuck quickly. The loading glow also stops a this momen

**Application Log - AppLog.txt (attached)**
This was captured at the exact moment the game crashes. This is only a information lvl log captured by eventvwr. This log also links to an xml file created by windows I have attached this xml - (WERB64F.tmp.WERInternalMetadata.txt

**Please also include the `output_log.txt` file. You can find your log here:** `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

I have also attached the output_log.txt file as requested above.

Hope this helps with bug tracking, please do not hesitate to contact me for futher testing if required

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3247930/output_log.txt)
[AppLog.txt](https://github.com/tsunamayo/Skywanderers/files/3247931/AppLog.txt)
[WERB64F.tmp.WERInternalMetadata.txt](https://github.com/tsunamayo/Skywanderers/files/3247932/WERB64F.tmp.WERInternalMetadata.txt)
[DxDiag.txt](https://github.com/tsunamayo/Skywanderers/files/3247941/DxDiag.txt)

**Comment by Leadershinji** [comment]
I also have RTX2080 and I can confirm this issue.

**Comment by Doehg** [comment]
I've got a EVGA 2080, and haven't been able to play for months.

**Comment by tsunamayo** [comment]
@Doehg @Leadershinji @SmOOvDoGG 
So you can check 19w23d, bug should be fixed! Tell me if it works.
Thanks for your patience! Cheers
