### ISSUE TITLE
Key mapping Broken

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1206]
Bonjour.

Lorsque je reparamétre mes touche, souvent je ne peux plus bouger ou switché d'outil. 

...

Paramétré les touches.

...

Cordialement 🏮𝓖𝖆𝖒𝖇𝖎𝘁❻

**Comment by tsunamayo** [comment]
Bonjour, pourrai tu me joindre le fichier output.log?

%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\

Merci!

**Comment by Gambit06** [comment]
resolved.

**Comment by tsunamayo** [comment]
Bonjour, je voudrai etre sur qu il ny a pas de probleme avec le jeu. Comment le probleme a t il ete resolu? 
Il y a t il certaine touche qui faisait bugger le jeu? 
Merci
