### ISSUE TITLE
Mirror Drone does not break blocks/bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1208]
### Short Description of the issue:
When you delete a block or brick it seems the mirror drone goes to the spot to delete the mirrored block/brick but it does not break it. This is quite painful on larger builds because you have to manually break the mirrored block then fly back to where you were and wait for the drone to fly to break the other side, which is what you broke in the first place, and then fly back to where it was before
...

### Environment
- Skywanderers version: 19w22i
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Yes the delete issue. Symmetry is hard, because of some issue I have to do complex math to get the right block... But I will fix that issue.

**Comment by tsunamayo** [comment]
Okay I fixed this one. One down, many to go... Cheers
