### ISSUE TITLE
Spawning a ship removes configuration from Sequence Controller

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1209]
### Short Description of the issue:
Basically when you spawn a new ship the sequence controller its not configured, maybe the problem comes from the saving process 
...

### Steps to reproduce the issue:
make a new ship, configure a sequence controller, save it, and spawn it again with the drone
...

### Environment
- Skywanderers version: lastest
- Graphics Card: GTX 1080TI

**Comment by Sullos** [comment]
Hi, possibly the same as issue #1196 ?
Was closed recently and the fix hasn’t been pushed to the game yet.

**Comment by tsunamayo** [comment]
Actually I fixed this issue recently, and it is live in 19w23a! Thanks!
