### ISSUE TITLE
Ship core weird orientation axis 

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1210]
### Bonsoir. Le réalignement de l'axe du vaisseau (Ship Core) fonctionne bizarrement, ce qui m’empêche d'utiliser normalement mon vaisseau.  

Good evening. Realignment of the Ship Core is oddly functional, which prevents me from using my ship normally.

### Steps to reproduce the issue:
Realignement on ship core.

Please help :_(

![20190603213650_1](https://user-images.githubusercontent.com/51275504/58829676-bdb47b80-8648-11e9-9653-30e8b9bd9cc5.jpg)
![20190603213654_1](https://user-images.githubusercontent.com/51275504/58829677-bdb47b80-8648-11e9-9d48-a5f83f11c6ce.jpg)
![20190603213656_1](https://user-images.githubusercontent.com/51275504/58829679-bdb47b80-8648-11e9-850d-dd4484d0cf5e.jpg)

Cordialement 🏮𝓖𝖆𝖒𝖇𝖎𝘁❻

**Comment by Sullos** [comment]
Same as issue #1175 I believe. 
I too have the same issue when trying to set my ship core to have forward actually be forward. If I do make forward the right direction then either left/right facing of the ship is wrong, or the top/bottom direction of ship is wrong too.

**Comment by Gambit06** [comment]
Indeed. Rigth like you, and this is so sad.

**Comment by Zeuscp1** [comment]
We all are crazy about this xD

**Comment by tsunamayo** [comment]
Okay I finally fixed it! Thanks for your help, I :heart: my testers...
