### ISSUE TITLE
Cant save a ship blueprint

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1211]
Hi i cant save ship blueprint with drone.

i tried save world F1 and use F5 export, but nothing happen.

Cordialement 🏮𝓖𝖆𝖒𝖇𝖎𝘁❻

**Comment by Senakysam** [comment]
Can you post your output_log from a game session where you tried to save a blueprint?

**Comment by Gambit06** [comment]
how can i get them?

**Comment by Gambit06** [comment]
how do I proceed?

**Comment by Senakysam** [comment]
if you go to %UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\ you can find the output_log there. Copy the file to here so tsuna can look at it.

**Comment by Gambit06** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3249646/output_log.txt)

**Comment by Gambit06** [comment]
k done. Thx Senak. ^^

**Comment by ProPeach** [comment]
Did you check your Blueprint folder to make sure it didn't create a file of your ship? There's no feedback confirming that you Be saved something so it can be easy to think nothing has happened

**Comment by Gambit06** [comment]
Vide...

**Comment by tsunamayo** [comment]
There is a lot of issue in the log, so I think it must be previous issue that just simply broke the game, likely not a save issue. I need investigate further. Thanks!
