### ISSUE TITLE
Blocks use the starter block texture after 1000m

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1212]
### Short Description of the issue:
When you build a ship 1000m long the end begins to use the starter block texture.

### Steps to reproduce the issue:

build a long stick that's 1000m Long

### Environment
- Skywanderers version: Stable
- Graphics Card: 1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/58837034-484da880-8652-11e9-8717-6c5357809f35.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay, I put a higher new limit. 100 000m ^^.
