### ISSUE TITLE
[Bug] Alternate Hull types still arent converted into the new hull

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1214]
### Short Description of the issue:

Sorry to be back here again, but it seems that even in the new version of the game I am unable to load my ship in with all hull blocks intact. Any hull blocks that are not basic hull get deleted from a blueprint once loaded into the game. 

What I do see when loading in the blueprint is this:
<img width="1920" alt="Skywanderers 2019-06-04 15-02-07-361" src="https://user-images.githubusercontent.com/33239800/58852413-cd2fd500-86d9-11e9-9bba-7f53f6bdc8b3.png">

When I should be seeing is something like this:
<img width="1920" alt="Skywanderers 2019-06-02 09-34-56-824" src="https://user-images.githubusercontent.com/33239800/58852429-dfaa0e80-86d9-11e9-91b2-7c8c83bcbcb0.png">

### Steps to reproduce the issue:

Here is the blueprint I'm trying to spawn in, the same as last time, and its file size is roughly 93kb. Once it is spawned in the game the file size is 75kb. This indicates it is deleting the hull blocks rather than substituting them with the new hull block.
[Ship Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/3250596/Ship.Blueprint.zip)

### Environment
- Skywanderers version: 19W23A
- Graphics Card: 980Ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3250594/output_log.txt)

**Comment by tsunamayo** [comment]
Deprecated Issue.
