### ISSUE TITLE
Choosing hair style for alien race is confusing

### ISSUE THREAD

**Issue by Plonk42** [tsunamayo/Skywanderers#1215]
### Short Description of the issue:

In the Player Customization panel, if you select an hair style, then change you race for an alien (E or C), the hair style is not changed automatically to "no hair". So it feels you can choose an hair style even for an alien race, then the next time you click the left or right arrow it picks "no hair", and you cannot change it anymore. I initially thought the hair style selector was stalled until I realize the only choice for aliens is "no hair".

### Steps to reproduce the issue:

Start the game, open the  Player Customization panel, choose an hair style, then choose an alien race.

### Environment
- Skywanderers version: pre-alpha 19w23a
- Graphics Card: Nvidia GTX   960

**Comment by tsunamayo** [comment]
Hehe ca va cousin? ;) Yes it is confusion, the whole UI will be redone for the new tech and to allow deeper customization. So that would be not fixed for the time being ^^
Jolie photo, j aurai du te demander de me faire un portrait aussi... A+
