### ISSUE TITLE
[19w23a] Click-dragging allows clipping of bricks

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1218]
### Short Description of the issue:
Bricks can be dragged into each other during placement.

### Steps to reproduce the issue:
Start placing a brick near another brick or a block; click-drag it into the neighboring brick/block. Trying to place a block into bricks sometimes shows the blue ghost images indicating valid placement, but these blocks cannot be clipped into bricks or other blocks.

### Environment
- Skywanderers version: 19w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190604204737_1](https://user-images.githubusercontent.com/33041786/58924981-793de400-870b-11e9-9693-4ce60eaafeb4.jpg)

![20190604204739_1](https://user-images.githubusercontent.com/33041786/58924982-7e029800-870b-11e9-99ab-54d93b8f4c77.jpg)

![20190604205624_1](https://user-images.githubusercontent.com/33041786/58924991-81961f00-870b-11e9-8626-02076ed93d9d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3255184/output_log.txt)

**Comment by tsunamayo** [comment]
This should be fixed in recent version. If not please tell me! Thanks
