### ISSUE TITLE
[19w23a] Slider Control bricks' handle models offset

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1219]
**- Description of the issue:**
The models for the slider brick handles are offset from the parent brick, floating a ways away. Clicking and dragging on the parent brick causes handle to snap back towards parent brick and follows cursor as expected, but still with a small offset and added quivering. Letting go of the handle returns it to floating.

**- Steps to reproduce:** 
1. Place down any slider brick (1x2x0.5 flat or 2x1x2 sloped) [to produce floating handle model nearby].
2. Click and drag from any point on the brick along the intended handle path [to produce snap-back and quivering].
3. Release mouse [to produce handle model's return to floating position].

**- Skywanderers version:**
19w23a

**- Graphics Card:**
Nvidia GeForce GTX 1060 6GB

**- Additional information:**
![20190604192103_1_LI](https://user-images.githubusercontent.com/51390907/58926843-8a422180-871a-11e9-8af2-1296ea8f3173.jpg)
![20190604192109_1_LI](https://user-images.githubusercontent.com/51390907/58926852-8e6e3f00-871a-11e9-9b49-c1a89163688f.jpg)
![20190604211745_1_LI](https://user-images.githubusercontent.com/51390907/58926855-91692f80-871a-11e9-8920-b6504f1b76fd.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3255292/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I do not reproduce this issue. Is there something more that you did? Is this something you can reproduce all the time, on all brick you place? Thanks

**Comment by Majikmonster** [comment]
It looks like after a restart of the game, most models are back where they should be, except on a few new ones I place near the center of my build. The sliders above are still buggy, just not all of them. Depending on where they are placed and what orientation they are placed, they could be OK or not. I'm not sure how it's replicated, or why it's only some that are affected.
![20190605045149_1](https://user-images.githubusercontent.com/51390907/58943713-508b0e00-874e-11e9-862d-522986778f03.jpg)
Some bricks on my structure are clipping through each other, and the planet nearby has disappeared. Those are the only unusual things that I could think of about my current game and universe.

**Comment by tsunamayo** [comment]
Hello, could you send me your blueprint file so I can reproduce and fix this issue? Many thanks?

blueprint located in (after exporting your build with the drone):
%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\PlayerEntities

**Comment by tsunamayo** [comment]
Hi @Majikmonster! Hi think this issue should be solved in current 19w28a. Could you please tell me if you see confirm this or still see the issue? Thanks!

**Comment by Majikmonster** [comment]
I have not seen this issue since the update.

**Comment by tsunamayo** [comment]
Okay great! Cheers
