### ISSUE TITLE
Stuck to chairs if 'F' pressed repeatedly

### ISSUE THREAD

**Issue by Shinyhevb** [tsunamayo/Skywanderers#122]
If the 'F' key (to sit in chairs etc) is pressed during the transition between moving from your standing position to the chair's position, then the character becomes stuck to the chair such that they can't move more than 2 blocks away from the chair. This is most easily recreated by standing at a distance from the chair, looking towards the chair so that you can still interact with it and double tapping the 'F' key. The hotbar at the bottom of the screen will reappear (even though you're 'sitting') and you will be unable to move more than 2 blocks away in any direction. Pressing 'F' again does nothing and you can't try and sit in another chair. This seems to only work on chairs with space around them as trying them on mechs ejected you from being stuck.

The only way to fix it that I've found is just opening a menu. You will see the player move towards the chair again and when they're on the normal position of sitting they will suddenly go back towards the initial position the character was in before 'sitting' down. However, you can't close the menu before your character has made its way back on top of the chair. Otherwise, they just stay stuck until you wait when you do it.

**Comment by tsunamayo** [comment]
Oh nice spot indeed, I face this bug a couple time without realizing the test case. It is fixed now! Will be in the next update. Cheers
