### ISSUE TITLE
Ship Orientation buggy in Ship Core block

### ISSUE THREAD

**Issue by EmceeAlpin** [tsunamayo/Skywanderers#1220]
### Short Description of the issue:
When trying to orient my ship via the ship core, I cannot get it to orient forward and right side up. No combination of "Switch axis", "Rotate around axis", or "Reversed" works. It feels like some orientations are missing.
...

### Steps to reproduce the issue:
Realign ship inside ship core block.
...

### Environment
- Skywanderers version: 19w23a
- Graphics Card: Nvidia GTX1080

### Additional information:
![20190604231904_1](https://user-images.githubusercontent.com/51394074/58930646-e5c3dd80-8721-11e9-8441-5a814a8c6dd2.jpg)
![20190604231913_1](https://user-images.githubusercontent.com/51394074/58930656-eb212800-8721-11e9-867c-9b1ba2c7e6e5.jpg)
![20190604231933_1](https://user-images.githubusercontent.com/51394074/58930668-f83e1700-8721-11e9-98c5-dc6724bd2288.jpg)
![20190604231931_1](https://user-images.githubusercontent.com/51394074/58930671-fbd19e00-8721-11e9-822d-828f9f974f51.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3255523/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ExodistSKY1** [comment]
Tsuna, 
     I am still having this problem as well.

What I have found is that if you do not make sure you are aligned properly with the original starter block you will not be able to align it correctly on the ship core

**Comment by Sullos** [comment]
I do believe it has been fixed but not yet pushed to our side via hotfix. Should be in the next hotfix. :)

**Comment by EmceeAlpin** [comment]
I see, I see. I shall wait for the hotfix then!

**Comment by tsunamayo** [comment]
Yes it should have been fixed. I am upping a new version now.

**Comment by EmceeAlpin** [comment]
It works! Thanks Tsuna!
