### ISSUE TITLE
[19w23a] Child entities showing as detached in drone preview

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1221]
### Short Description of the issue:
Some ships with child entities, when viewing their menu on the builder drone, will show some of the child entities detached from their proper positions, and instead floating near the point on the ship that the starter block was initially placed at.

### Steps to reproduce the issue:
Create a ship, attach a small rotator to it, then attach something to that rotator. Preview the ship in the drone menu. I can't reliably reproduce the bug, so I'm attaching the blueprint it's present on.

It resembles [this](https://github.com/tsunamayo/Skywanderers/issues/980) bug, except that it only occurs in the drone menu, not in-game.

### Environment
- Skywanderers version: 19w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
What the ship looks like in-game:
![20190605133141_1](https://user-images.githubusercontent.com/33041786/58980574-4a208480-8796-11e9-9f5b-eb2b6e1f9f77.jpg)

What the ship looks like in the drone preview:
![20190605131717_1](https://user-images.githubusercontent.com/33041786/58979779-6de2cb00-8794-11e9-9fa1-1fb89bfd77a8.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3258488/output_log.txt)

[Mako Fighter.zip](https://github.com/tsunamayo/Skywanderers/files/3258500/Mako.Fighter.zip)

**Comment by tsunamayo** [comment]
Issue fixed, will be available in 19w23c. (soon as I need to fix messed up cockpit texture...) Thanks!
