### ISSUE TITLE
Game crashes when creating a new character

### ISSUE THREAD

**Issue by Pepanda** [tsunamayo/Skywanderers#1223]
### Short Description of the issue
Just bought the game, when creating a new character for single player the game crashes. Can confirm its 100% of the time. Tried switching to windowed mode, and playing with graphic settings but no change. Game still crashes
...

### Steps to reproduce the issue:
Creating a new character for single player
...

### Environment
- Skywanderers version: 19w23a
- Graphics Card: Nvidia RTX 2070

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3258595/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
@Pepanda 
So you can check 19w23d, bug should be fixed! Tell me if it works.
Thanks for your patience! Cheers

**Comment by Pepanda** [comment]
@tsunamayo
Works great! Thanks for the quick fix! Can’t wait to test out everything
