### ISSUE TITLE
[19W23A] Stripey paint not stripey

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1224]
### Short Description of the issue:

Attempted to use the textured paints, but they don't seem to display the secondary colour. I'm pretty sure I've got it setup correctly, tried with both variants of red and white striped paint and the black and yellow.

### Steps to reproduce the issue:

Paint blocks with textured paint.

### Environment
- Skywanderers version: 19w23a
- Graphics Card: GTX 1060

### Additional information:

![20190604213736_1](https://user-images.githubusercontent.com/40872394/58985207-bb7e2880-87d2-11e9-9ca3-6dbf3c824100.jpg)

**Comment by tsunamayo** [comment]
This issue should now be fixed, stripes paints are now back. Thanks!
