### ISSUE TITLE
[19w23a] Custom paint marker not moving

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1225]
### Short Description of the issue:

When selecting a custom paint colour, the white brackets don't move when dragging over the paint spectrum.

### Steps to reproduce the issue:

Select custom colour, drag around in the colour selection spectrum.

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:
![20190604215649_1](https://user-images.githubusercontent.com/40872394/58985467-465f2300-87d3-11e9-9a4d-40ed5a2dc49e.jpg)

**Comment by tsunamayo** [comment]
Could you please send your output.log, I cant reproduce the issue I want to see if you have error. Is this something you get 100% of the time? Thanks!

**Comment by Lsutehall** [comment]
Output log attached. This does seem to happen all of the time, but I've realised that I'm also missing the object preview window from the codex - might they be related? Pretty sure the preview pane was showing when i updated to 19w22.

This logfile from 19w23d:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3269986/output_log.txt)

Screenshot of missing preview pane:
![20190609223658_1](https://user-images.githubusercontent.com/40872394/59164644-9c9bd100-8b07-11e9-8873-81d9c50bc74c.jpg)

**Comment by tsunamayo** [comment]
Custom paint have been deprecated, so this issue is no longer applicable. (thats one way to solve issues ;)) Cheers!
