### ISSUE TITLE
[19w23a] Fragments of the GUI appear in the skybox

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1226]
### Short Description of the issue:
This one is super fun, as you can see in the video below, parts of the GUI appear way off in space in the skybox. 

[Skywanderers Ship core hologram bug.zip](https://github.com/tsunamayo/Skywanderers/files/3258878/Skywanderers.Ship.core.hologram.bug.zip)
If you hide your HUD with F2 it dissapears
![image](https://user-images.githubusercontent.com/27857711/58987705-fa62ad00-87d7-11e9-9569-bf53d0f4aaa8.png)
(Zoom in to the middle of the screen, it's quite faint)

### Steps to reproduce the issue:
I haven't been able to accurately reproduce this one in different ships, but if I quit and restart a different part of the GUI will appear in the same part of the sky, so I'm guessing/hoping my instance file will help

### Environment
- Skywanderers version: 19w23a
- Graphics Card: GTX 1050M

### Additional information:

[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3258910/Save_Data.zip)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3258890/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, this is really weird indeed. It seems to be the old UI, which will be replace by the new tech soon, so I wont spend time fixing this one as it is not really game breaking and will be fixed naturally. Thanks!
