### ISSUE TITLE
[19w23a] Engines can be placed in other engines

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1227]
### Short Description of the issue:
Engine blocks can be placed such that they occupy the same voxel space.

### Steps to reproduce the issue:
Drag a line of engine blocks. With the engine block still selected in the toolbar, mouse over the blocks until the ghost image turns blue. Click to place until a block appears there; you may need to spam the mouse to get one to place, but it will eventually do it.

### Environment
- Skywanderers version: 19w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190605170938_1](https://user-images.githubusercontent.com/33041786/58994203-4ea86580-87b5-11e9-9d27-1fef117312d3.jpg)

![20190605171226_1](https://user-images.githubusercontent.com/33041786/58994212-536d1980-87b5-11e9-9554-18b4d9e6610c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3259235/output_log.txt)

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/58994512-a90ee980-87e8-11e9-9276-acf72d84ac62.png)
This seems to happen with most blocks. It could stem from the concave nature of the engine model

**Comment by tsunamayo** [comment]
Could you please tell if you see this in 19w23b (live), this should have been fixed. Thanks

**Comment by Dwarf-LordPangolin** [comment]
Being able to place them directly into engines has been fixed, but sadly things can still be dragged through engines.

![20190605204853_1](https://user-images.githubusercontent.com/33041786/59001179-5c6ce380-87d3-11e9-848c-679e0c60969a.jpg)

**Comment by tsunamayo** [comment]
Yes, this is another issue I need to look into, collision will get a total revamp at one point, still writting the spec. Thanks!
