### ISSUE TITLE
[19w23a] Bricks clipping into engine block: The Clip Awakens

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1228]
### Short Description of the issue:
Bricks can be clipped into the engine block.

### Steps to reproduce the issue:
Mouse over an engine block with a brick selected and place a brick on the surface of the block; this brick is normal, and is where it should be. Mouse over the placed brick, and the ghost image of the next brick will appear clipped halfway into the engine block.

### Environment
- Skywanderers version: 19w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190605171539_1](https://user-images.githubusercontent.com/33041786/58994356-d7270600-87b5-11e9-82af-612fd9f5c9ab.jpg)

![20190605171543_1](https://user-images.githubusercontent.com/33041786/58994365-dc845080-87b5-11e9-973c-d40a80210292.jpg)

![20190605171546_1](https://user-images.githubusercontent.com/33041786/58994372-e1490480-87b5-11e9-9112-b692b8adb5e4.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3259243/output_log.txt)

**Comment by tsunamayo** [comment]
I cant reproduce this on the latest build, do you confirm it is not fine (should be related to the other bug) Thanks!

**Comment by Dwarf-LordPangolin** [comment]
I can't reproduce this anymore either, so it looks like 19w23b fixed it!

**Comment by tsunamayo** [comment]
Good, thanks!
