### ISSUE TITLE
Extreme bloom affects UI readability

### ISSUE THREAD

**Issue by otherCob** [tsunamayo/Skywanderers#123]
![skywanderers_2017-10-23_15-56-05](https://user-images.githubusercontent.com/28826531/31897650-541176fc-b817-11e7-859c-6d05a4d30747.png)

![skywanderers_2017-10-23_17-29-39](https://user-images.githubusercontent.com/28826531/31897857-dcbb543c-b817-11e7-9083-b53fd1ee8ada.jpg)

I doubt players are meant to get this close to stars in the final game, but this might be worth looking into. Maybe you can exempt UI elements from the bloom effect.

**Comment by tsunamayo** [comment]
Yes, the problem I had is that I wanted to have bloom on the 3D preview of the block. Not sure if/when I change this one, I will see what I can find a way to work around this!

**Comment by AfterRebelion** [comment]
Bloom no longer seems to affect UI elements, so this issue is no longer valid in recent versions (19w23b)
