### ISSUE TITLE
[19w23b] 1/16 meter plate offset by half its height

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1230]
### Short Description of the issue:
The thinnest brick piece is offset by half its height into whatever it's placed on.

### Steps to reproduce the issue:
Place a 1/16 meter plate somewhere you can see its edge; it will be sunk half its height into whatever it's placed on.

### Environment
- Skywanderers version: 19w23b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190605213514_1](https://user-images.githubusercontent.com/33041786/59003040-05b6d800-87da-11e9-8ee4-439aa69c4e34.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3259731/output_log.txt)

**Comment by tsunamayo** [comment]
Issue will be fixed in 19w23c. Btw very cool looking ship! Could you send it to me when you are done, I want to calibrate the small brick bevel. 
Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Thank you! I finished it; here it is.

[AAM Mako Interceptor Mk. I.zip](https://github.com/tsunamayo/Skywanderers/files/3269166/AAM.Mako.Interceptor.Mk.I.zip)
