### ISSUE TITLE
[19w23b] Canopy texture issue

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1231]
### Short Description of the issue:
The canopy block has some odd texture issues.

### Steps to reproduce the issue:
Place canopy block, or use existing blueprint. Bug is present on ships from previous versions and new versions.

### Environment
- Skywanderers version: 19w23b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190605214243_1](https://user-images.githubusercontent.com/33041786/59003328-22074480-87db-11e9-974b-da05c1b12d03.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3259747/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I messed up something, it is fixed for 19w23c. Thanks!
