### ISSUE TITLE
[19w23b] Small tile clipping issue

### ISSUE THREAD

**Issue by abdulucthuluzulu** [tsunamayo/Skywanderers#1232]
### Short Description of the issue:

Small tiles will clip halfway into any block or brick you place them on.
### Steps to reproduce the issue:

Try to place a small tile, both the ghost and the placed tile itself will clip into the surface.

### Environment
- Skywanderers version: 19w23b
- Graphics Card: Geforce GTX 750 Ti

### Additional information:
![20190606011114_1](https://user-images.githubusercontent.com/51438428/59018916-dadd7b80-87fb-11e9-88e2-5223a0357750.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3260738/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this issue will be fixed for 19w23c. Thanks!
