### ISSUE TITLE
Missing Planet

### ISSUE THREAD

**Issue by Jokerplayer** [tsunamayo/Skywanderers#1234]
In the middle of the asteroid field is no planet.

GTX 1070 
i7-6700K 4,00 ghz
16 gb RAM
1 TB HDD
250 gb SSD

![20190606153053_1](https://user-images.githubusercontent.com/51260622/59036899-77d9fc00-8870-11e9-879b-ec99568c7064.jpg)
![20190606153054_1](https://user-images.githubusercontent.com/51260622/59036900-77d9fc00-8870-11e9-802d-d9158c046aea.jpg)

**Comment by AfterRebelion** [comment]
This seems to be fixed in 19w23d.
![imagen](https://user-images.githubusercontent.com/559819/59157775-d68db880-8ab0-11e9-8557-2528d449d271.png)

**Comment by tsunamayo** [comment]
Yes sorry this should be fixed in current version. @Jokerplayer do you confirm? Thanks!

**Comment by Jokerplayer** [comment]
@tsunamayo it works fine! :)

**Comment by tsunamayo** [comment]
Great!
