### ISSUE TITLE
Window side textures are broken

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1235]
### Short Description of the issue:
Window side textures are broken
...

### Steps to reproduce the issue:
load into new world, place them
...

### Environment
- Skywanderers version: lastest
- Graphics Card: GTX 1080Ti

### Additional information:

<a href="https://ibb.co/r7JJpDX"><img src="https://i.ibb.co/xCQQgxr/image.png" alt="image" border="0"></a>

**Comment by tsunamayo** [comment]
Yes this issue will be fixed for 19w23c. Thanks!
