### ISSUE TITLE
[Bug] Panel Bevelled doesn't stretch to 4m

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1236]
### Short Description of the issue:
Just a quick one, "Panel Bevelled" only stretches to a max size of 2mx2m, not 4mx4m as other bricks do
...

### Steps to reproduce the issue:
Stretch a Panel Bevelled to mmax size
...

### Environment
- Skywanderers version: 19w23b
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Will be fixed in 19w23c. Thanks!
