### ISSUE TITLE
[Bug] Small tile places halfway inside itself

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1237]
### Short Description of the issue:
Looks like small tile bricks place halfway down its own height so it clips a little
![image](https://user-images.githubusercontent.com/27857711/59068537-44b55e00-88ac-11e9-8e14-9924bf5f1c22.png)

### Steps to reproduce the issue:
Place some small tiles, preferably over a ledge so you can see the edge

### Environment
- Skywanderers version: 19w23b
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Yes this issue will be fixed for 19w23c. Thanks!
