### ISSUE TITLE
Endless Loading Bug

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1239]
### Short Description of the issue:
All I know is that my game has an infinite loading bug and the boring standard fixes like on and off is not working and I don't want to delete my world because I have a ship whose blueprint is unsaved so here is the output_log.txt

### Steps to reproduce the issue:
Bugger if I know, but it was something to do with hinges I think

### Environment
- Skywanderers version: 19W23B
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3265254/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, so you can send me your SaveData folder so I can see if I reproduce. To load separately an unsaved ship, you can try to find the right .mps in Save_Data\PlayerEntities (the hardest part, look for size and last updated time), then copy it to blueprint. Thanks!

**Comment by ZachZent** [comment]
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3268204/Save_Data.zip)

Here you go. Sorry for the delay I was at work.

Did you know for about 95% of updates/devlogs, I am away from my computer/game? Lol

**Comment by ZachZent** [comment]
Also it appears when loading this ship, I can't build anything on this one


[Stubby.zip](https://github.com/tsunamayo/Skywanderers/files/3268212/Stubby.zip)

**Comment by Majikmonster** [comment]
I experienced this bug as well, but only after exiting the game with a phantom block left on one of my ships. I had to wipe everything, and when I loaded the blueprint that gave me grief the phantom block was no longer ghostly. I had also used hinges on my ship that session, so I'm not certain of the true cause.

**Comment by tsunamayo** [comment]
haha, I guess we are just on the opposite side of the globe ;) So I fixed your issue, it will be available in 19w24a. It was something with the hotkey. Thanks!
