### ISSUE TITLE
Teleport Block (teleport still available after block has been destroyed)

### ISSUE THREAD

**Issue by ChuckieGee** [tsunamayo/Skywanderers#124]
Placing a Teleport Block allows the user to use the block with the correct functionality, with the teleport location appearing in the F7 teleport menu
Issues:

- Once the teleport block is destroyed by the player (holding right click until it disappears) the teleport location is still available within the F7 menu

- Teleport blocks are also unable to be renamed? so once placing several teleport blocks down the F7 menu can become cluttered and confusing if multiple new teleport locations are created.

- The teleport locations also exceed the bounds of the teleport menu box, this is more of an aesthetic issue but a bug none the less.

**Comment by tsunamayo** [comment]
Thanks, I will fix that and indeed add the ability to rename them. I keep you posted!

**Comment by tsunamayo** [comment]
Okay I fixed the main issue, and also the windows clip bound. For the naming I agree, this is something that will be added down the line when I get to refactor this (not very high priority atm). Thanks!
