### ISSUE TITLE
[IDEA] Block Deletion confirmation

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#1241]
IDEA

Block deletion:
So i always have the problem of right clicking and removing the wrong block, i got a possible simple fix for it. 
```
target block 
Right click highlights block red or with an effect
Left click/ESC cancels highlight/selection
Right click confirms deletion of highlighted block.

```
This would also be handy for highlighting blocks before deletion and checking inside the ship to see if it affects anything inside.

**Comment by tsunamayo** [comment]
If you right click and hold you will see a preview of what you are gonna delete. If you dont want to delete it, just look elsewhere before releasing the mosue button. Does that works for what you want? Thanks

**Comment by JRL101** [comment]
Oh yea perfectly! i didnt realise holding right click was a feature. did you add that in the newest update?

**Comment by tsunamayo** [comment]
Not sure when I did add that haha ;) Sorry I am only seeing the reply now... Cheers
