### ISSUE TITLE
[Bug] When Flying Ship [Tab] doesnt disengage ship direction head lock

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1242]
### Short Description of the issue:

Originally when you pressed the Tab key when flying a ship, the ship HUD would disappear and you would be free to look about the cabin without having an effect on the way ship points. Now, pressing tab removes the HUD but looking around causes the ship to still change direction as if TAB doesn't work anymore.

### Steps to reproduce the issue:

Fly your favourite ship of any sort and press TAB to remove HUD and look around the cabin. The ship will start wildly spinning.

### Environment
- Skywanderers version: Most recent 
- Graphics Card: 980Ti

**Comment by tsunamayo** [comment]
Hi, I cant reproduce this issue for some reason. What version did you used? Thanks!

**Comment by tsunamayo** [comment]
Sorry I am not sure if this issue is still valid or not at this point. If it is still happening ping me! Cheers
