### ISSUE TITLE
Ghost symmetry plane

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1243]
### Short Description of the issue:
Sometimes, when you fly around, you can see these ghost symmetry planes.
![20190608140114_1](https://user-images.githubusercontent.com/559819/59147014-fb712580-89f5-11e9-929e-499f2872cc31.jpg)
They move alongs you, so I can't take a closer look.
This happened in earlier versions (19w22h comes to mind), so it doesn't have anything to do with the new symmetry tool released in 19w23c, ~~and if you take a closer look, you can see that it has the previuous symmetry texture.~~ Nevermind, got a liiiittle bit closer, and it is now the new symmetry plane texture.
![20190608142115_1](https://user-images.githubusercontent.com/559819/59147172-bd293580-89f8-11e9-98e0-b708af77296e.jpg)
Also noticed that it dissapears if you disable the UI with F2, and it comes back if you reenable it.

### Steps to reproduce the issue:
   

  1. Load this save: [Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3268500/Save_Data.zip)
  2. You should see it right in front of you.

I can reproduce it 100% of the time as I load this save.
And as you can see, there are no ships in the save.

### Environment
- Skywanderers version: 19w23c
- Graphics Card: AMD RX 580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3268491/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, yes indeed I saw it too, it is now fixed in 19w23d (will arrive today). Cheers
