### ISSUE TITLE
Blocks can be build inside long slopes

### ISSUE THREAD

**Issue by thecold1** [tsunamayo/Skywanderers#1244]
### Short Description of the issue:
Blocks can be placed inside long slopes.

### Steps to reproduce the issue:
1. Building a long slope (10+ blocks)
2. You can now build another block in some of the slope blocks (not all)
3. You can even build another long slope inside the slope but if it's too long it will be build ontop of it

### Environment
- Skywanderers version: 19w23c
- Graphics Card: GeForce GTX 970

### Additional information:

![image_000185](https://user-images.githubusercontent.com/5357826/59148493-fa49f380-8a09-11e9-8675-9a4d84003643.png)
![image_000206](https://user-images.githubusercontent.com/5357826/59148494-fa49f380-8a09-11e9-85ed-c0503a514096.png)
![image_000379](https://user-images.githubusercontent.com/5357826/59148495-fa49f380-8a09-11e9-9531-494a375e7943.png)
![image_000410](https://user-images.githubusercontent.com/5357826/59148496-fae28a00-8a09-11e9-986f-8efd5de70c9f.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3268633/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for spotting this, my slope check wasnt small enough for steep slope. It will be fixed in 19w24a. Thanks!
