### ISSUE TITLE
[19w23c] Ships loaded seem to inherit paint colors from nearby ships

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1245]
### Short Description of the issue:
Ships loaded sometimes have paint colors they were not saved with if spawned from the drone near other ships.

### Steps to reproduce the issue:
Go to an area near one ship, then load another ship from the drone. Sometimes the loaded ship will spawn with paint colors that are or were used on the first ship. If ships are loaded far from other ships, this does not seem to happen. It is also hard to reproduce; when trying to make it happen it doesn't, and when not trying to it does.

### Environment
- Skywanderers version: 19w23c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190608223358_1](https://user-images.githubusercontent.com/33041786/59154773-d99c9080-8a3f-11e9-9fa4-a4213a9ad88b.jpg)

![20190608223947_1](https://user-images.githubusercontent.com/33041786/59154777-051f7b00-8a40-11e9-8fa9-575346c0699c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3269173/output_log.txt)

**Comment by ZachZent** [comment]
STD. Ship transmitted dye

**Comment by tsunamayo** [comment]
Hah, custom colors. I think I will get rid of that, to make something simplier to deal with. I keep you posted, I will work a bit on gameplay first. Nice looking ship btw, I like your style.

**Comment by tsunamayo** [comment]
So custom colors is now a thing from the past (sorry =( ), so this issues can no longer happen! Cheers
