### ISSUE TITLE
Missing asteroids

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1247]
### Short Description of the issue:
![imagen](https://user-images.githubusercontent.com/559819/59162492-3e182800-8af2-11e9-8acd-690cf69d1deb.png)
At first I though they were simply removed, but some people on Discord had screenshots with them, so this is clearly bugged.
If you go a little off the ring, you can see them, but as you get close they dissapear.
![imagen](https://user-images.githubusercontent.com/559819/59162583-ab788880-8af3-11e9-8f7f-b1bbd7db61b6.png)

### Steps to reproduce the issue:
Just load a world on the planet ring, and you can appreciate their absence.
### Environment
- Skywanderers version: 19w23d
- Graphics Card: AMD RX 580

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3269815/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, unfortunately I dont have a RX 5xx to reproduce this issue.
The good news is that I will change my asteroid tech, it is quite special atm and I move to something much more conventional. Bad news is that it will take a bit of time until I make the switch. Thanks!

**Comment by Starwhip** [comment]
Another user with an RX 580 here, asteroids are also missing for me. Could be an AMD driver specific issue.

**Comment by AfterRebelion** [comment]
Updating the drivers to 19.7.1 fixed the problem.
![imagen](https://user-images.githubusercontent.com/559819/61293031-12641e00-a7d3-11e9-9b5c-69597b968d03.png)
