### ISSUE TITLE
Mirror placement can be off at times

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1249]
### Short Description of the issue:
The placement for the mirror plane isn't 100% accurate with where I'm aiming and likes to offset itself in some specific spots. And in the last picture you can see the build is on par with the larger grid
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3270547/output_log.txt)
![20190609231007_1](https://user-images.githubusercontent.com/32974671/59172129-0918cf00-8b0c-11e9-91ff-1f8eef89d95a.jpg)
![20190609230949_1](https://user-images.githubusercontent.com/32974671/59172131-0ae29280-8b0c-11e9-9bc0-9cfcfb94de99.jpg)
![20190609230946_1](https://user-images.githubusercontent.com/32974671/59172132-0d44ec80-8b0c-11e9-858e-fed5499ffe86.jpg)
![20190609230928_1](https://user-images.githubusercontent.com/32974671/59172138-0f0eb000-8b0c-11e9-9174-d86b5746496f.jpg)
![20190609231441_1](https://user-images.githubusercontent.com/32974671/59172201-644ac180-8b0c-11e9-9957-13d34f0394e0.jpg)

**Comment by Xerma** [comment]
Hmm, seems that restarting fixed it for the time being

**Comment by tsunamayo** [comment]
Hum actually I think I saw that as well, let me check in detail. Thanks

**Comment by tsunamayo** [comment]
I think I fixed this issue, it was when looking towards the center of the ship. Dont hesitate to tell me if actually it was not fixed (fix in 19w24a) Thanks!
