### ISSUE TITLE
Impossible to delete Logic Blocks with inverted build/destroy

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#125]
So flailing for QUITE some time on this one, On game start I set my game controls to Starmade right click destroy, but changing these around has far greater implications on Linkables like Logic. It over-rights Shift+Destroy meaning that using inverted mouse buttons they can not be removed from the ship. Period.

Because we have freedom to map our buttons as we should, the appropriate commands for extra actions should logically re-map with them

**Comment by tsunamayo** [comment]
Agreed it should also remap the activate action - let me change that asap.

**Comment by tsunamayo** [comment]
Okay fixed, it will be on an upcoming hotfix patch today or tomorrow. Thanks for actively testing and reporting issues!
