### ISSUE TITLE
Tooltip displays in loading screen

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1250]
### Short Description of the issue:
Just a small little thing and it might be irrelevant if you'll be changing up saving/loading at some point but figured it's worth a report
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
![20190609231334_1](https://user-images.githubusercontent.com/32974671/59172273-c3a8d180-8b0c-11e9-90b2-caeac2e07d0d.jpg)

**Comment by tsunamayo** [comment]
Thanks, I updated the loading screen, now it is cleaner. Cheers
