### ISSUE TITLE
Mirror creates an extra block along axis point

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1252]
### Short Description of the issue:
When you place a block/brick along the center of the mirror plane it creates 2 in the same spot. If you delete one you can see a graphic of the other block but it has no bevels and you cannot destroy it. Saving and reloading after breaking the first block does then display the bevel and you can then break it.
...

### Steps to reproduce the issue:
1. Place mirror axis
2. Drag blocks along the axis plane
3. Destroy what you just placed
4. See the second, bugged, block
5. Save and reload
6. Break the corrected second block
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
![20190610002940_1](https://user-images.githubusercontent.com/32974671/59174632-b513e780-8b17-11e9-8da3-be30ae0500f5.jpg)

**Comment by Xerma** [comment]
Not sure what's going on but after loading back up, after reporting this bug, it doesn't seem to be happening anymore... very odd

**Comment by Majikmonster** [comment]
I also have this bug. Only once has it resulted in a phantom block for me.

**Comment by tsunamayo** [comment]
This should be fixed in current 20w13a. Thanks
