### ISSUE TITLE
Hull Basic Corners don't have bevels

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1253]
### Short Description of the issue:
Pretty straightforward, they stand out like a sore thumb
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
![20190610004917_1](https://user-images.githubusercontent.com/32974671/59175088-d4137900-8b19-11e9-82a3-44bed88b79ee.jpg)

**Comment by tsunamayo** [comment]
Ok fixed in 19w24a! Thanks for being so active ;)
