### ISSUE TITLE
Block suggestion

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1254]
A 2x1 or 2x2x1 rotor so that we can have our stuff in the middle of blocks

**Comment by tsunamayo** [comment]
You mean a small size rotor (like 0.5m), or a larger one (2m)?
For small size actually for this I will introduce back a feature we had before when the stud tech was live, which is the ability to offset bricks by half their size. Thanks

**Comment by Zeuscp1** [comment]
What you said i think will work pretty well. Basically a small rotor that can work in the middle of hull block

**Comment by tsunamayo** [comment]
So we have the small rotor and the brick offset mechanism. Thanks!
