### ISSUE TITLE
Blocks disapearing

### ISSUE THREAD

**Issue by KillerX32** [tsunamayo/Skywanderers#1256]
I am able to fly atound and place blocks but if I move about 2 to 3 blocks away from it the entire ship disappears. Able to see it when i get close again

**Comment by KillerX32** [comment]
Anyone?

**Comment by tsunamayo** [comment]
Okay could you please press F3 then deactivate Occlusion ? Enable Occlusion should be unchecked) Tell me if after that you see the block or not. Could you also give me your log? Thanks

**Comment by tsunamayo** [comment]
Cannot investigate.
