### ISSUE TITLE
[19w23d] Symmetry mode allows clipping

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1259]
### Short Description of the issue:
When symmetry mode is enabled, placing a brick that would not clip on the clipping side allows the game to place its mirror image through objects on the other side.

### Steps to reproduce the issue:
Build something asymmetric, then turn on symmetry mode. Place a brick in a space that is open on one side but has something in it on the other. The brick placed on the open side will be duplicated on the other side even though there's already something there.

### Environment
- Skywanderers version: 19w23d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190612214758_1](https://user-images.githubusercontent.com/33041786/59400212-4d9aa980-8d5c-11e9-84ce-f7e66aad7f2a.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3283916/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I have yet to code this. This is one of the reason I wanted to hold back on more symmetry plane, as dragging block x 8 can be a lot of computation to do in real time... Thanks

**Comment by tsunamayo** [comment]
This should be fixed in current update. Thanks!
