### ISSUE TITLE
Selecting point on Galaxy Holo Map then zooming causes crash

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#126]
Twice now Ive been sent back to desktop from this, but both times were when attempting to use the Holomap... I still cant go do my first jump...

double right click near the centre to set view marker, then mousewheel in but crash after the first "zoom" in onto the map.
Crash occurred on both Block and Brick Holomaps

**Comment by tsunamayo** [comment]
Okay, I know there is some crash issue on the Holomap, but only when being used like a maniac... Your test case seems a pretty straightforward and a reproducible issue, so I fear it might be related to your GFX card as holomap is GPU intensive (compute shader).
Could you please send me your error and output_log after the crash?

**Comment by Napther** [comment]
The crash style is similar to my other problem with booting the game. Black then blue "No Device" screen as the GPU conks out. Skywanderers becomes little tiny rectangle in the corner, and doesnt get a chance to output an error log as far as I know.

**Comment by Napther** [comment]
Just retested and no dice. Not even my Overclocked variant of my GPU was able to survive the Holomap zooming in onto middle of the galaxy area. I can zoom in 1x which geenrates a larger scale area of the place you put the marker, but zooming 1 more closer in gives me a "no Input" blue screen and sends me to desktop with no error log output text, etc.

**Comment by tsunamayo** [comment]
Deprecated, holomap will get a complete refactor with the galaxy update. Thanks!
