### ISSUE TITLE
[19w23d] Symmetry mode jumps over center of ship.

### ISSUE THREAD

**Issue by Javidac** [tsunamayo/Skywanderers#1261]
### Short Description of the issue:

Symmetry doesn't want to be placed in the center of the ship. 

### Steps to reproduce the issue:

Mess around with symmetry.

### Environment
- Skywanderers version: [19w23d]
- Graphics Card: AMD Sapphire

### Additional information:

![20190613063127_1](https://user-images.githubusercontent.com/33093843/59404084-83b04b80-8da5-11e9-8173-a38c27a82afb.jpg)
![20190613063129_1](https://user-images.githubusercontent.com/33093843/59404092-86ab3c00-8da5-11e9-8ca2-9e5179bb6075.jpg)
![20190613063131_1](https://user-images.githubusercontent.com/33093843/59404095-890d9600-8da5-11e9-90dc-e1409d852bf9.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3284223/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I fixed this bug, will be in 19w24a. Thanks!
