### ISSUE TITLE
Hotkeys always active when connected to piloted yoke (rapid repeat activations)

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1262]
When a yoke is connected to a hotkey, and that hotkey is connected to logic, the logic will be sent signals every tick.

...

Connect a yoke to a ship core and hotkey.
Connect that hotkey to a button or switch.
Connect the button or switch to any other logic or system.
Pilot the yoke.

...

- Skywanderers version: 19w23d
- Graphics Card: Nvidia GeForce GTX 1060

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3287276/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, god I plugged a laser and almost made an heart attack... I keep you posted!

**Comment by tsunamayo** [comment]
Okay issue will be fixed in 19w24a. I fixed hotkey for network also. Cheers!
