### ISSUE TITLE
[SUGGESTION] of block and other.

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1264]
Tractor Beam.
Smal windowed block.
Blink logic.
Magnet Small block.
Custom Stickers.
Infinit sliding rail.
Flat hinge.
Long flat hinge.
Painting one face of block.

Cordialement 🍻𝓖𝖆𝖒𝖇𝖎𝘁❻

**Comment by Gambit06** [comment]
Paintable block (pixel by pixel)

**Comment by Gambit06** [comment]
A double sequencer (Go and Return) to facilitate doors for example or landing gear.

**Comment by tsunamayo** [comment]
Thanks! so my quick answer:

tractor Beam: Maybe one day, if there is a use for gameplay
Smal windowed block. : yes will do
Blink logic. : not sure what it is?
Magnet Small block.: not sure, maybe depending on other factors
Custom Stickers. : not sure what they are, you mean from an external picture?
Infinit sliding rail: maybe when I have time, I will first refactor the current rail.
Flat hinge: nope, I did that before it was a nightmare
Long flat hinge: nope, I did that before it was a nightmare
Painting one face of block: nope, I did that before it was a nightmare and people didnt like it.
Paintable block (pixel by pixel): not likely
A double sequencer (Go and Return) to facilitate doors for example or landing gear. -> yes the sequencer gate will be improved to do that.
Cheers

**Comment by Gambit06** [comment]
Blinker: a logic block sending a signal on / off, adjustable in time triggered by an extern signal.
Custom stickers: i think an external pic or an internal game, like a drawing tool, I do not know how to explain it to you.

Thanks for your respond.

**Comment by talrey** [comment]
I like the idea of text stickers. We can use text screens for now but physical painted text is cool, like "NO STEP" signs on aircraft wings.

We don't need a "Blinker", that's completely doable within the current capabilities of the logic system. I would argue that adding custom bricks for this sort of thing is a slippery slope towards "do-everything" bricks that take the fun out of the wiring. Play around with the logic gates a bit! I wrote a guide on the forums if you get stuck, but coming up with your own solutions can be fun and rewarding.

**Comment by Gambit06** [comment]
i'm gonna look that. thank you Talrey.

An insigna creator in game with simple geometrical form will be very cool.
And a Gun, Armor, Suit workshop for customize your stuff will cool too.
