### ISSUE TITLE
[Bug] Mirror tool does not mirror paint on blocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1265]
### Short Description of the issue:
The recently implemented mirror tool will mirror painted bricks, but when you paint blocks the colour is not mirrored
...

### Steps to reproduce the issue:
Setup a mirror plane with the mirror tool
Paint some blocks and see if it mirrored
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Yes indeed, issue will be fixed in 19w24a! Cheers
