### ISSUE TITLE
[19w24a] Centered bricks placed in symmetry mode can only be deleted in that mode

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1268]
### Short Description of the issue:
Bricks that are centered when placed in symmetry mode can only be deleted while in symmetry mode.

### Steps to reproduce the issue:
In symmetry mode, place a brick that straddles the symmetry plane so that only one brick is placed. Turn symmetry mode off, then attempt to delete that brick.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190614011420_1](https://user-images.githubusercontent.com/33041786/59487279-cc1d4700-8e41-11e9-9730-0e154e51cd33.jpg)

![20190614011423_1](https://user-images.githubusercontent.com/33041786/59487287-d0e1fb00-8e41-11e9-8d8f-06b29236ea60.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3289259/output_log.txt)

**Comment by Tommyg930** [comment]
I've also noticed that on centered block Symmetry (AKA odd Symmetry) that if I place a block in the center of the symmetry plane, it will place two blocks over lapping each other. this is most obvious when placing hinges and rotors.

**Comment by Dwarf-LordPangolin** [comment]
Yeah, that started happening for me today too. Noticed it when I went to paint a brick and it showed one of them as one white and the other as black.

**Comment by tsunamayo** [comment]
This issue is fixed in 20w13a. Thanks
