### ISSUE TITLE
[19w24a] some stretched blocks use brick texture

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1269]
Some of the blocks that were fine before the update from 19w23d to 19w24a have had their textures replaced with the ones bricks use. Breaking and replacing the blocks does not change their texture back. It is pseudo-random.
...
Place normal and stretched corner block (try others as well)
...
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 1060 6gb
...
![20190614135059_1](https://user-images.githubusercontent.com/51390907/59529902-3e2c7500-8eb0-11e9-8b25-332bcbcc9b0c.jpg)
...
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3291774/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue will be fixed in 19w27a! Thanks a lot, cheers
