### ISSUE TITLE
No Static Spawn Point

### ISSUE THREAD

**Issue by DukeDigby** [tsunamayo/Skywanderers#127]
Flew a Ship into Space and ejected. Ship flew off and i lacked a teleport beacon to return to Ship/Ringworld. Creating a new character made me spawn in space, even after uninstalling and clearing Skywanderers from Appdata (Windows 10) and deleting the Character file.

**Comment by tsunamayo** [comment]
Did you try to come back to an existing beacon with F7?

Alternatively, you can simply create a new character, you should come back at the same place.

But clearing the the appdata should also have worked...
Also are you sure you cleared the following location?
C:\Users\{YOUR_USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
It should reset your position and all change. 

Thanks

**Comment by DukeDigby** [comment]
No existing Beacon when i tried F7. A New character resulted in still being spawned in Space.
Deleted entire Folder in Appdata in LocalLow. Only thing that completely reset the game was removing SW from Appdata AND deleting the leftover SW Folder in Steamapps after Uninstall.

**Comment by tsunamayo** [comment]
Now you can spawn to any ship, even without beacon.
Thanks!
