### ISSUE TITLE
Basic hull has the same texture as Starter Block after 1km

### ISSUE THREAD

**Issue by HyperPlut0** [tsunamayo/Skywanderers#1271]
### Short Description of the issue:

... Basic hull has the same texture as Starter Block after 1km

### Steps to reproduce the issue:

...Build past 1km

### Environment
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GTX 1050

### Additional information: Building a ship that pushes the games limits

_(Screenshots, Videos, Error logs, Related issues)_
![bug](https://user-images.githubusercontent.com/51304056/59543488-86ac5880-8ed9-11e9-8af2-c9f1973bb103.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3292472/output_log.txt)
`

**Comment by tsunamayo** [comment]
Hi, could you please give me your blueprint so I can check this out? Thanks a lot!

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks!
