### ISSUE TITLE
Query Gate Wiring Backwards

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#1272]
### Short Description of the issue:

Expected: The Query gate's GUI displays the "System Information" of whatever sliding brick, hinge, or rotor it is getting input from.
Currently: The Query gate's GUI only displays the "System Information" of whatever it is sending output to.

### Steps to reproduce the issue:

1. Place a Sliding Brick and two Query gates ("A" and "B")
2. Using the Wire Tool, drag a wire from the Sliding Brick into Query gate "A".
3. Drag a wire from Query gate "B" into the Sliding Brick.
4. Open the GUI of both Query gates with the "Activate" key bind.
  A: Should display the Sliding Brick's position. Currently does nothing, or if wired to another logic command, it displays "unknown system".
  B: Should display "unknown system" or do nothing. Currently displays the Sliding Brick's position.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 970

**Comment by tsunamayo** [comment]
Yes indeed. Issue will be fixed for 19w26a. Thanks!
