### ISSUE TITLE
[19w24a] Graphical Glitch when placing angled blocks near square blocks

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1273]
Graphical issue that results in a hazy static effect on the blocks and causing lines to be drawn between them
...

It was only happening on the larger build I am working on.
Place a large wall section using regular blocks
place an angled block with the angle touching the wall and drag to reproduce

Hopefully the screenshots help to explain:

![20190614140819_1](https://user-images.githubusercontent.com/45324484/59546715-5f18b880-8ef8-11e9-96d9-f9982cc2d3fb.jpg)
![20190614140831_1](https://user-images.githubusercontent.com/45324484/59546717-650e9980-8ef8-11e9-9c04-35bc792ba33e.jpg)
![20190614140837_1](https://user-images.githubusercontent.com/45324484/59546719-693ab700-8ef8-11e9-8f33-d33a169d4627.jpg)

...

### Environment
- Skywanderers version: 19w24a
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
Could you please send me your blueprint? How big is it? It might be related to some precision issue of some sort. Thanks!

**Comment by ExodistSKY1** [comment]
Sent via E-mail

**Comment by tsunamayo** [comment]
Okay I fixed the issue, it was a floating point issue. Massive massive beast you have here... Keep me posted when you make progress on that one! Cheers
