### ISSUE TITLE
Light bricks cannot be turned off or dimmed

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1274]
Light bricks' light intensity cannot be changed with sliders, nor can they be turned off.
...
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 1060 6gb
...
Slider 0%
![20190615001013_1](https://user-images.githubusercontent.com/51390907/59546821-4f9e6d00-8f02-11e9-9562-270d488104a9.jpg)
Slider 50%
![20190615001022_1](https://user-images.githubusercontent.com/51390907/59546823-53ca8a80-8f02-11e9-9794-293282db05fc.jpg)
Slider 100%
![20190615001031_1](https://user-images.githubusercontent.com/51390907/59546826-57f6a800-8f02-11e9-89ec-80f66b07a8d1.jpg)
Switch On
![20190615001106_1](https://user-images.githubusercontent.com/51390907/59546828-5d53f280-8f02-11e9-957b-8e9c213909e2.jpg)
Switch Off
![20190615001108_1](https://user-images.githubusercontent.com/51390907/59546831-63e26a00-8f02-11e9-816b-16144d4008f1.jpg)
On this last couple of images, you can see on the long brick shape on the left that there is a slight difference in the amount of red reflected. That is as much of an indication that the light is "off" as I can get. Even using the F key to manually toggle the light doesn't work.

**Comment by tsunamayo** [comment]
Yes I had to remove it while doing some heavy refactoring of the data model. It should be back at one point - I just want to make sure I can deliver fast updating light as I had to also change a few things for the graphic update. Thanks for being so active! Cheers
