### ISSUE TITLE
Emissive textures on switches and indicator lights displays invalid colors, stuck behavior

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1275]
The emissive lights on switches and indicator lights sometimes shows up deep blue, deep green, yellow or deep red instead of the normal off state red. Bricks affected by this flash the normal red or green color when switching states, but only for a moment. They then go back to having the color they started with.
...
Place down as many switches and indicator lights on a ship as needed until one or more of the bricks shows an odd color on the light.
Connect a bugged switch to a bugged indicator light.
Activate the switch. Activate it once more.
...
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 1060 6gb
...
On state:
![20190615002036_1](https://user-images.githubusercontent.com/51390907/59547377-eb80a680-8f0b-11e9-95c0-84f3d6fe25d4.jpg)
Flash while state is changing:
![20190615002038_1](https://user-images.githubusercontent.com/51390907/59547378-f0ddf100-8f0b-11e9-8b4c-b947523b007c.jpg)
Off state:
![20190615002042_1](https://user-images.githubusercontent.com/51390907/59547380-f63b3b80-8f0b-11e9-8ce4-4daf2d7efe90.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3292747/output_log.txt)

**Comment by Majikmonster** [comment]
The far right indicator light brick is normal. The rest of those bricks are bugged. It sometimes fixes itself on restart of the game/reload of world, but it pops up again and again while building.

**Comment by tsunamayo** [comment]
I think it is the same issue as #1276  - so it should be fixed in 19w25a. Cheers
