### ISSUE TITLE
[19w24a] Symmetry painting glitchy results.

### ISSUE THREAD

**Issue by Tommyg930** [tsunamayo/Skywanderers#1277]
The red line represents the symmetry plane and the two 10x10 hull sections have been created with symmetry mode. the hull section on the right was painted manually. while particle effects of the block being painted do happen on either side of the symmetry plane, the effects of this action isn't consistent.
![20190615200820_1](https://user-images.githubusercontent.com/33021337/59554846-da867280-8fa9-11e9-8b42-bafba09ec911.jpg)

oh and if I then paint over the left side with another color, a different pattern will show on the right side.
![20190615201957_1](https://user-images.githubusercontent.com/33021337/59554919-fa6a6600-8faa-11e9-8014-f4ab9e036a92.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3293414/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for reporting the bug! Issue will be fixed in upcoming 19w27a. Cheers
