### ISSUE TITLE
[19w24a] Sometimes when pressing F5 ships despawn

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1279]
### Short Description of the issue:

Pressing F5 will sometimes delete the ship being worked on (unspawn)

...

### Steps to reproduce the issue:
I am not sure it has only happened once thus far and completely deleted the ship I was working on. 

### Environment
- Skywanderers version: 19w24a
- Graphics Card: 1080ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3293811/output_log.txt)

**Comment by Majikmonster** [comment]
I had that happen as well. It was only once, but I'm now a little paranoid. I save the game each time I save a ship, right before I dismiss Fr3n.

**Comment by ExodistSKY1** [comment]
UPDATE:   

Happened again:

-What happened?-
     Everything but one ship disappeared upon calling in the drone with F5

-Possible Steps to reproduce-

    - Spawn in ship
    - soon after dismiss the drone 
    - call the drone back quickly after
    - the game kind of hiccups and then most if not everything will disappear

LOGS: 

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3294521/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I should have fixed the issue of drone fast repeated calling. Fix will be in 19w27a. Thanks for your help!
