### ISSUE TITLE
Q button problem

### ISSUE THREAD

**Issue by tatsunbou** [tsunamayo/Skywanderers#128]
if you assign inventory to q and then try to re-align yourself, you get a permanent mouse cursor on your screen and cannot open the inventory, even when the game is restarted and the files are verified

**Comment by tsunamayo** [comment]
Hi! Did you also reassign Crouch to something else? Re-align is in fact Double Crouch. 
I tried your test case and it when fine even when Q was assigned to Inventory and Crouch.
Are you able to reproduce the test case?

**Comment by tatsunbou** [comment]
I reassigned crouch to ctrl actually. My game broke when I double tapped Q
after that. maybe that helps?

**Comment by tsunamayo** [comment]
Okay, is it something that you are reproducing all the time? I cant seem to reproduce on my side.

**Comment by tsunamayo** [comment]
Okay I think this bug was fixed a few versions ago. Thanks
