### ISSUE TITLE
[19w24a] Sitting in chair on child entity causes tearing & shaking when flying

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1280]
### Short Description of the issue:
If the player is using a chair attached to a child entity while the ship is flying, the ship's appearance will begin to shake and tear, becoming much worse over time. This does not occur when using a chair that is directly attached to the ship itself. The graphical bug disappears on leaving the seat.

### Steps to reproduce the issue:
Create a new ship with two seats, one attached to the ship itself, one to a child entity. Fly the ship from each chair (preferably in Hyper mode, as this bug appears more quickly the faster the ship is going). The shaking/tearing effect will appear while seated in the chair attached to the child entity, but not the one attached to the ship itself.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
View while seated in a chair attached to a hinge after flying a long distance:
![20190616012322_1](https://user-images.githubusercontent.com/33041786/59560468-fdc81680-8fd7-11e9-88f2-e06e1a5d4bf7.jpg)

View while seated in a chair attached to the main ship after flying a long distance:
![20190616014858_1](https://user-images.githubusercontent.com/33041786/59560525-0b31d080-8fd9-11e9-9cda-72a810cdd09b.jpg)

Using this test ship, the seat attached to the main ship did not experience the shaking/tearing. The seat on the hinge did.
![20190616014542_1](https://user-images.githubusercontent.com/33041786/59560530-21d82780-8fd9-11e9-9d79-d71fb1902a44.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3293897/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
This appears to be the same issue as these two things:

https://github.com/tsunamayo/Skywanderers/issues/901
https://github.com/tsunamayo/Skywanderers/issues/863

**Comment by ZachZent** [comment]
Now I want the in-game "drug" item (spice, death sticks, etc) to be called Chair and have this same visual effect

**Comment by tsunamayo** [comment]
Okay issue is fixed in 19w25a. Thanks for spotting that one! Cheers
