### ISSUE TITLE
[19w24a] Exiting HYP then ending boost allows high-speed "coasting"

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1281]
### Short Description of the issue:
If a ship is flying with the HYP mode, when it is exited the player can also quickly turn BOOST mode off, allowing them to "coast" at multiple km/sec while only very slowly decelerating. If the player is fast enough, they can coast at about whatever speed they left HYP at.

### Steps to reproduce the issue:
Get in a ship, press H to enter HYP mode. Once in HYP and moving at a good speed, press H immediately followed by SHIFT to leave first HYP then BOOST in quick succession. This leaves the ship coasting while in neither HYP nor BOOST. WASD input will slowly decelerate the ship, but in the absence of input it will go back to coasting. Importantly, the ship can turn **much** faster while "coasting" than it can while traveling in either HYP or BOOST.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190616205829_1](https://user-images.githubusercontent.com/33041786/59573747-1b4dbc80-907a-11e9-9ea3-8f6f2725e873.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3294990/output_log.txt)

**Comment by CGS-Thomas-Fahey** [comment]
nice ship

**Comment by CGS-Thomas-Fahey** [comment]
i saw it in the gallery

**Comment by CGS-Thomas-Fahey** [comment]
before i was unfairly banned

**Comment by ZachZent** [comment]
Related to this, in hyperspeed, the "dust" particles that fly by your screen that are supposed to go from front to back goes from right to left

**Comment by tsunamayo** [comment]
Actually I fixed both bug already, I am reworking supercruise / hyperspeed (we got to find a name). I added lock and auto dropoff, and will add autopilot.
