### ISSUE TITLE
[19w24a] Stickers do not show on ships when first loaded in world

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1284]
### Short Description of the issue:
When a ship is loaded from the drone, it initially does not have its stickers on it. Saving and reloading the world fixes this.

### Steps to reproduce the issue:
Load a ship into the world that has stickers on its design. They will be missing until the world is saved & reloaded.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Stickers on a ship already in world when loaded:
![20190617222208_1](https://user-images.githubusercontent.com/33041786/59651273-e19ab580-914e-11e9-91ca-7899ec8b6fac.jpg)

Different copy of the ship, no stickers on the same place when loaded from drone before save & reload:
![20190617222314_1](https://user-images.githubusercontent.com/33041786/59651300-f6774900-914e-11e9-85c9-e5d78cc70326.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3299651/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue will be fixed in 19w27a. Cheers!
