### ISSUE TITLE
[19w24a] Half-blocks in same voxel share paint color

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1285]
### Short Description of the issue:
If two half-hull blocks are used to fill the same voxel, they can only be painted one color; painting one applies that color to the other.

### Steps to reproduce the issue:
Place two half-blocks next to each other so that together they fill 1 block's worth of space. Paint one of them in a color; the other will change color to reflect that.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190618165728_1](https://user-images.githubusercontent.com/33041786/59722953-b1a0f000-91ea-11e9-85d4-2911a5bbc39a.jpg)

![20190618165731_1](https://user-images.githubusercontent.com/33041786/59722958-b49be080-91ea-11e9-8a9f-0700f9f6d239.jpg)

![20190618165734_1](https://user-images.githubusercontent.com/33041786/59722961-b665a400-91ea-11e9-8175-821480a34088.jpg)

![20190618165736_1](https://user-images.githubusercontent.com/33041786/59722963-ba91c180-91ea-11e9-8080-b4bcacb67101.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3303593/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I guess now this is confusing as you can put two half block in the same space, but it is working as expected. Paint on 1m block is working at the voxel level, you paint a 1m cube of space, which allow you to more detailing as opposed to paint the full stretched block as it is working with bricks. I might prevent putting two block on the same voxel if it gets too confusing, as there is not utility of doing so at the moment (there might be some special real useful case with corner/tetra actually), we will see. Thanks!
