### ISSUE TITLE
[19w24a] Ship preview model cut off

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1286]
### Short Description of the issue:
For larger ships (this ship is 150m long) the ship preview in the drone/ship core UI does not show the full length of the ship and slices off the end closest to you.
Note that this also happens on other ships of similar/larger size so it's not related to this specific blueprint.
![ezgif-3-a831fc71ed8a](https://user-images.githubusercontent.com/27857711/59726935-84c0fd00-922b-11e9-8a5b-7aef84ef3ac0.gif)

### Steps to reproduce the issue:
Load the attached blueprint and access the drone with the ship highlighted.
Spin the preview so the ship is pointing towards/away from you.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: GTX 1050M

### Additional information:
[CR90 Ship Preview Bug - ProPeach.zip](https://github.com/tsunamayo/Skywanderers/files/3303848/CR90.Ship.Preview.Bug.-.ProPeach.zip)

**Comment by tsunamayo** [comment]
Nice tantive IV ;) This issue is fixed, release for 19w27a. Thanks!
