### ISSUE TITLE
[19w24a] Armature can be dragged through blocks

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1289]
### Short Description of the issue:
Armature blocks can be dragged through other blocks.

### Steps to reproduce the issue:
Click-drag armature block through already existing blocks.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Could be part of the same collision issue as this? https://github.com/tsunamayo/Skywanderers/issues/1227

![20190620230535_1](https://user-images.githubusercontent.com/33041786/59897666-50784880-93b3-11e9-909e-fef9db284ac2.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3312994/output_log.txt)

**Comment by Majikmonster** [comment]
I can do the same thing with half-cubes, placing them perpendicular to each other in the same block space (making an L shape when they clip).

**Comment by tsunamayo** [comment]
Okay issue will be fixed in 19w27a. Thanks!
