### ISSUE TITLE
[BUG] Lights colored with custom color not recognizing color change

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#129]
If a light brick is placed and colored with a custom paint color, when that custom color is changed, the light does not update with that change. For example, if I color a light brick with a green custom color, and then change that custom color to a red, the light remains the old color. The appearance of the brick itself changes, but the light emitted by the brick does not.

Edit: updated with picture to illustrate bug.

![20171023165640_1](https://user-images.githubusercontent.com/33041786/31915192-299335b8-b813-11e7-94c5-bf7425e102fb.jpg)

**Comment by tsunamayo** [comment]
Oh indeed, thanks for reporting that. Okay I will be able to make light compatible with custom color, but when you update a color you will need to repush that color to all the light you need. I will keep you posted!

**Comment by Dwarf-LordPangolin** [comment]
Thank you! BTW, I just noticed that this also applies to hoses.

**Comment by tsunamayo** [comment]
Now light use custom color, but you still need to repaint your brick to make it update (this I wont fix it). Cheers
