### ISSUE TITLE
[Suggestion] A couple new blocks

### ISSUE THREAD

**Issue by OverSavior** [tsunamayo/Skywanderers#1290]
Drawings are somewhat poorly made, but I hope it's enough to explain the idea.
First one is Grid Change Block. Theoretically it should eliminate the need in clipping. It works the similar way as blocks/bricks that you can stretch, but instead of stretching  you pick the angle (you still can stretch it in two dimensions tho). Step value can be whatever you consider reasonable. I think 10 degree would be optimal. Basically when you place it somewhere it creates new grid that I marked with green on the picture. This grid then can be used to place blocks on it. With such a block building circles and round objects in general should become as easy as possible. 

Why I think such a block is important is, when we get to the actual combat, I assume hinges probably won't be too strong in terms of integrity. By destroying the hinge one can easily cut huge part of the ship. This block on the other side has larger surface on which you can place stuff and also has higher integrity
![image](https://user-images.githubusercontent.com/31092530/59919060-1ea4c780-942f-11e9-8cd8-c8847c202281.png)

Another one is Bridging Block. How it works is you place it somewhere and then click on the other block you want to connect it with. Depending on where you placed it, it will create a new block that connects two different surfaces. The only problem I can see so far is that you won't be able to place any other blocks on top of it. Mass and integrity of these blocks should be calculated depending on volume. The only problem I can see so far is that you won't be able to place any other blocks on top of it and most likely it will mess the textures unless you can find a workaround
![image](https://user-images.githubusercontent.com/31092530/59919114-4562fe00-942f-11e9-8eba-f1fc9b1c7382.png)

**Comment by tsunamayo** [comment]
Hi, thanks for the suggestion! First your drawing is great ;). 
So what we have to keep in mind is that new grid = new children entity. Yes they will be weaker in gameplay, this is why children entity should be reserved for landing gear, hangar door ect, not to be used for decorative purpose. They have a big cost in term of performance (rendering and collision). So it sucks but I need to find way to make their use not interesting for the player :( ... 

The second block also presented like that would be challenging to make, but I have a block in mind that works a bit like that, (I refer to it as the bridging block also). It is a freeform block a bit like yours except that the yellow surface is either flat or vertical (not 45deg). Dont sure when it will come, it is actually a bit tricky to make. 
Hope it makes sense!
