### ISSUE TITLE
[19w24a] Stencil arrows turn into colored lines and blobs 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1293]
The stencil arrow turns into a line and then a colored block as you move farther away from them. 
If this is not a bug, could you change it to blend to the dominant color rather than expanding the color of the arrow. 

![20190620121003_1](https://user-images.githubusercontent.com/45324484/59960271-db2c7680-948b-11e9-8dc3-521cf56adf8b.jpg)
![20190620121019_1](https://user-images.githubusercontent.com/45324484/59960273-e089c100-948b-11e9-9579-be2bf49c5b1c.jpg)

- Skywanderers version:  19w24a
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
Yes indeed. It will be fixed in upcoming patch 19w26a. Thanks for being so active over here! Cheers
