### ISSUE TITLE
Drone measurements completely off

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Skywanderers#1294]
### Short Description of the issue:
Hello. Recently, I have been building my ships, but after I realized that something was off about the drone's measurements of the X Y and Z sizes, I spawned a new starter block ship and a drone. The block was 1x1x1, as expected. I then placed a block down, which put it at 2x1x1, and then removed the block. Even after it being removed, the drone showed the ship to be at 2x1x1, despite calculating the mass correctly. I repeated the test for every axis, and every time it was as if the drone counted a phantom block that did not exist.

Skywanderers version: 19w24a

Graphic Card: NVIDIA GeForce GTX 970

Edit: Apparently I didn't post this in the Bug section, is there any way to change this?

**Comment by tsunamayo** [comment]
Okay this issue is fixed for 19w26a! It is okay I deal with labels myself, it allows me to see which issues I have checked yet or not. Thanks for your help! Cheers
