### ISSUE TITLE
[19w24a] Brick doesn't stretch

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1295]
![bug](https://user-images.githubusercontent.com/36980446/59997225-5bc8af80-9611-11e9-9741-cbefb220e5e4.png)

This brick doesn't stretch like the others. Not sure if it is intentional

**Comment by tsunamayo** [comment]
Yes it is a miss from my side. I think it was already reported. I keep you posted.

**Comment by tsunamayo** [comment]
Okay it should be fixed in 19w27a! Cheers
