### ISSUE TITLE
[19w24a] Left & right side specific shapes not mirroring

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1296]
### Short Description of the issue:
The (incredibly useful) "small half corner left" and "small half corner right" bricks are not mirroring; placing one of them does not place its counterpart on the other side of the symmetry plane.

### Steps to reproduce the issue:
Enable symmetry mode on a creation, then place one of the bricks. Its opposite number is not placed.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Placing the one ...
![20190624231440_1](https://user-images.githubusercontent.com/33041786/60069048-f63ef680-96d6-11e9-89d8-523bfec66858.jpg)

... does not place the other.
![20190624231442_1](https://user-images.githubusercontent.com/33041786/60069057-0060f500-96d7-11e9-8f54-0d4643fcf2b7.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3323549/output_log.txt)

**Comment by tsunamayo** [comment]
Yes they cant be mirrored. I dont think I will have time to add that feature, so I am gonna close that for now. I will add something in the description, like a small icon or something. Thanks!
