### ISSUE TITLE
[Med] Rockets will not detonate against sliding blocks, but are still stopped by them.

### ISSUE THREAD

**Issue by Personan-N** [tsunamayo/Skywanderers#13]
Description of Issue: 

Rockets will just stop moving when they hit a sliding block. 
Here's a screenshot: http://imgur.com/a/BO2QD

It seems to be related to sliding blocks being impossible to destroy under some circumstances. A similar bug report was filed 4 days ago.

**Comment by tsunamayo** [comment]
Ok I tried and I dont reproduce this one. Will do further investigation.  Was the game broken after it happened ? (like were you able to place block and play normally ?)

**Comment by Personan-N** [comment]
I was still able to place blocks and play normally, except for on the
affected sections of blocks. If I spot the bug again I'll do a better job
of recording the circumstances.

**Comment by tsunamayo** [comment]
No problem, I know already that they wont destroy two different entity even if they are both hit, but I cant reproduce the stuck floating in air issue. I will check with other tester. Thanks for your help !

**Comment by IronicMollusk** [comment]
If it helps, i noticed that after i used a lot of rockets to destroy a ship, the ship began to "slide" or float away, in a direction not inline with the trajectory of the rockets. it was in this state the rockets began to behave in this way. about every other rocket would do this, the others would detonate. once the sliding blocks moved clear of the rockets trajectory, the rocket would continue on its path. I only noticed this bug today, so i will hunt down a for sure method to reproduce it.

**Comment by tsunamayo** [comment]
Fixed!
