### ISSUE TITLE
[19w24a] Mirroring paint near angled blocks is qwerky 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1300]
When painting in Mirror mode, the paint will mess up if it is near angled blocks... in some instances not paint or paint the wrong thing. 

...

use mirror mode and paint multiple surfaces to include angled blocks 

...

- Skywanderers version: 19w24a
- Graphics Card: 1080ti
vvv Original side vvv
![20190625233237_1](https://user-images.githubusercontent.com/45324484/60282460-a6298500-98cc-11e9-805d-709b30eaee55.jpg)
vvv Mirrored side vvv
![20190625233230_1](https://user-images.githubusercontent.com/45324484/60282463-a88bdf00-98cc-11e9-8a8c-0f5340a3d7a5.jpg)
vvv Original side vvv
![20190625232946_1](https://user-images.githubusercontent.com/45324484/60282467-ab86cf80-98cc-11e9-81cb-04540ce9fa98.jpg)
vvv Mirrored side vvv
![20190625232936_1](https://user-images.githubusercontent.com/45324484/60282470-ad509300-98cc-11e9-94ba-0874b27e1b4c.jpg)

**Comment by tsunamayo** [comment]
I cant see it well, are you painting on blocks or on bricks? I fixed an issue on mirroring block paint yesterday, it could be the same issue. Thanks

**Comment by ExodistSKY1** [comment]
This is on blocks. I will double check when the update comes out and give an update to the issue

**Comment by tsunamayo** [comment]
I think issue was fixed. Thanks
