### ISSUE TITLE
[19w24a] Continious saving screen cant exit game or force save

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1302]
Continious saving screen (Top left icon in image) cant exit game or force save. Will revert to last saved game before the infinite save icon appeared. 

-you can still save your blueprints but it will revert as stated above
-you cannot exit the game and must exit to title screen 

...

It has happened 4 times today and I have yet to find what is causing it.
...

### Environment
- Skywanderers version: 19w24a
- Graphics Card: 1080ti

![20190629164716_1](https://user-images.githubusercontent.com/45324484/60389801-306d1700-9a8e-11e9-8ed7-30e332e681b7.jpg)

EDIT:    I was not able to reproduce the issue, but you might be able to still use the Output logs since then.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3344210/output_log.txt)

**Comment by ProPeach** [comment]
I think an Output log would be super helpful for this kind of thing

**Comment by ExodistSKY1** [comment]
Just got back home, Ill see if I can get it to happen again and then update the original post

**Comment by tsunamayo** [comment]
Hi, yes I would need the proper log to really investigate. Did it happens when you pressed F5 repeatly to spawn / unspawn the drone (I think I saw an issue with this and save). Thanks!

**Comment by ExodistSKY1** [comment]
I think it did. I have not been able to reproduce the issue just yet. I will update when I can

**Comment by tsunamayo** [comment]
Okay hopefully this was fixed! If not could you please ping me? Thanks
