### ISSUE TITLE
[19w24a] Slider shows random textures on baseplate sometimes

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1303]
### Short Description of the issue:
You've said you're going to replace the slider block anyway, so this may not be an issue, but just in case: the slider block sometimes loads random textures on the non-moving part.

### Steps to reproduce the issue:
Place multiple slider blocks stretched to at least 2m (so the interior of the base can be seen). One of them will probably show an odd texture.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190629230512_1](https://user-images.githubusercontent.com/33041786/60392138-ee11fd00-9ac2-11e9-9200-51206ff0d927.jpg)

![20190628200558_1](https://user-images.githubusercontent.com/33041786/60392152-0d108f00-9ac3-11e9-981a-bc1020eae9ba.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3342508/output_log.txt)

**Comment by Cpt-Fortius** [comment]
Probably connected; 

I don't see bits of old textures there, my game draws the texture of the slidey part where the rail should be. Sometimes. They also flicker.

19w24a, Radeon R9 290

**Comment by tsunamayo** [comment]
Hi, I fixed a bug that could have also explained this one. Could you please tell me if you see this in the new 19w28a patch or if it seems it is fixed? Thanks

**Comment by Cpt-Fortius** [comment]
Seems it was nicely fixed.
Good job!

**Comment by tsunamayo** [comment]
Okay great! Cheers
