### ISSUE TITLE
[19w24a] Slider acts weird with bricks... Placement hologram is not correct

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1308]
Block slider is not in correct position with bricks

-Place a slider and scroll over it with a block
-you will see the placement hologram is not correct and just hovering over the slider with the mouse shows the hologram 
...

### Environment
- Skywanderers version: 19w24a
- Graphics Card: GTX 1080ti

![20190701003443_1](https://user-images.githubusercontent.com/45324484/60415977-5683db80-9ba2-11e9-8176-d271bf9c6d57.jpg)
![20190701003455_1](https://user-images.githubusercontent.com/45324484/60415984-584d9f00-9ba2-11e9-8475-0d03a1af3a96.jpg)
![20190701003455_2](https://user-images.githubusercontent.com/45324484/60415988-597ecc00-9ba2-11e9-9ca6-568296820d45.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3344198/output_log.txt)

**Comment by tsunamayo** [comment]
Yes, this is a duplicate issue. This slider unfortunately will be removed, as it is too hacky and lead to too many headaches :(. I will do a small and mini slider instead. Thanks!

**Comment by ProPeach** [comment]
Have you considered a "sticker" slider instead? With normal maps it could look 3D, and have no awkward hitbox issues

**Comment by tsunamayo** [comment]
Stickers slider would a hack with its own slew of bugs / workaround to do... I will give the new slider very soon.

**Comment by tsunamayo** [comment]
I dont get this issue in 19w28a. Do you confirm it is okay for you? Thanks

**Comment by ExodistSKY1** [comment]
I can confirm it is working smoothly now and tried it on multiple ships
