### ISSUE TITLE
[19w24a] Studs 4 to 1, 1 to 4, 2 to 1, 1 to 2 don't work

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#1309]
### Short Description of the issue:

Studs 4 to 1, 1 to 4, 2 to 1, 1 to 2 used to be able to offset bricks attached to them by 1/2 bricks from the basic grid. Now when bricks are attached on top of these, they remain arranged according to the basic brick grid.

Can they be restored? They were neat and useful.

### Steps to reproduce the issue:

1. - Place down some "4 to 1", "1 to 4", "2 to 1", "1 to 2" bricks anywhere.
2.- Attempt to build on them.

### Environment
- Skywanderers version:  19w24a
- Graphics Card: Radeon R9 290

### Additional information:

https://cdn.discordapp.com/attachments/416013956331601930/595653327396536320/20190702181703_1.jpg

https://cdn.discordapp.com/attachments/416013956331601930/595653344996098049/20190702181857_1.jpg

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

Initialize engine version: 2018.3.14f1 (d0e9f15437b1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon R9 200 Series (ID=0x67b1)
    Vendor:   
    VRAM:     4071 MB
    Driver:   25.20.15017.1010
Begin MonoManager ReloadAssembly
- Completed reload, in  0.986 seconds
OnLevelWasLoaded was found on ResourceManager
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 356)

<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'LinkCommand') is missing!
 
(Filename:  Line: 294)

UnloadTime: 10.983210 ms
SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

RESTARTING THE GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Skywanderers Version: pre-alpha 19w24a
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System GFX memory 4071 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System memory 16283 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Suport sparse texture?  False
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Fonctionnal Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Logic Items
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Hull Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Block for interior building.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Construction Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Pipes
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Windows and Cockpits
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Legacy Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading all textures
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Shape Mesh Data Buffer Count: 47526
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

TOTAL TEXTURES :420
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Voxel Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Chunk Resources: 49694
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Clusters Resources: 1590234
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Brick Data Resources: 7269643
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
No localization data present
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 1695 unused Assets to reduce memory usage. Loaded Objects now: 13894.
Total: 20.492553 ms (FindLiveObjects: 1.539946 ms CreateObjectMapping: 0.275792 ms MarkObjects: 17.892555 ms  DeleteObjects: 0.783750 ms)

Level 0 computation finished 105559
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Level 0 computation finished 106145
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading Character : Metalman
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

network adress 0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

OnPlayerConnected
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 7.316272 ms
Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Voxel Light Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

There has been an awakening. From the Block Entity Manager.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Local player Start sequence: 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 259 unused Assets to reduce memory usage. Loaded Objects now: 26804.
Total: 34.675819 ms (FindLiveObjects: 2.278028 ms CreateObjectMapping: 0.638072 ms MarkObjects: 31.439025 ms  DeleteObjects: 0.320184 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
NEW SYSTEM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOAD c[64 0 30]l0n0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/yuQf-rUSU0iJGJck8QQ0eQ.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 29 unused Assets to reduce memory usage. Loaded Objects now: 27465.
Total: 35.702195 ms (FindLiveObjects: 2.484170 ms CreateObjectMapping: 1.051633 ms MarkObjects: 31.986272 ms  DeleteObjects: 0.179609 ms)

Correlian Shuttle loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/xP2fTeXYfkG7ov98WTnDbQ.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Corsair_T1 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/LogdmAnhgU-wHoRnCTaGIg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Banshee loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/T37l3e3hkUGPLPaQDJWPvg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mini Mech loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/9j1Rrz5y6U-kGjb-24xKqg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
knightmask loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/Rsllab8jaUmUPRSn5ZsZnA.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Torus loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/4eBPw7rK-kKNxP-MqbrtNQ.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mech02_WIP_FD2 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/ebt5QaARnEWjXGIKoxTgTg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Hound_70_T3 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/0gXjJ4_3z0CBVtoY8nnSSQ.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LongrangeFighter01_T1 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/x5a6sERB_kCm_eQkCsEEdg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27523.
Total: 37.806481 ms (FindLiveObjects: 2.732919 ms CreateObjectMapping: 0.707212 ms MarkObjects: 34.309202 ms  DeleteObjects: 0.056893 ms)

AI Pilot loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589763
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/PGocxGF9mkCUA9kMcxhp-A.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

total stars 12994
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

AI Pilot loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

RADIUS 10430,38 | DEPTH 2048
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/y0mTIaN_PUuFJr3qqJiOUg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Speeder01_WIP05 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/Eh9_l36LU0KhCUNp79IXlg.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Goblin_T02_FD2 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/FG8t4kxFhkmBxnd5FT2bwQ.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589771
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589770
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589770
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589776
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589776
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

AI Pilot loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589782
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589782
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Command already existing 1589771
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/BMj1F5-WTEaNC_oLfkzv6Q.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Knight_Titan02 loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/xXpH_ZjJKEOKX9-8HL9HoA.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

AI Pilot loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/738ACD67-2CA4B.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

New Entity loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

LOADING C:/Users/Metalman/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities/4BB6DA92-7DA1C.mps
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

New Entity loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Galaxy Skybox compute finished
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Activating all camera
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Activating all camera
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading sequence completed in 51,74879 seconds
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

CommandBuffer: built-in render texture type 13 not found while executing Rings Particles Rings(Clone) (SetRenderTarget color buffer)
 
(Filename:  Line: 0)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by Majikmonster** [comment]
@Cpt-Fortius you can drag and drop the log file itself into the text box, instead of copy/pasting text from the file. Github will automatically make a text link to the uploaded file so the initial bug report isn't a mile long.

**Comment by Cpt-Fortius** [comment]
Tried that and gave me an error message,  for the log files and the screenshots as well. In hindsight, I doubt the log file was actually necessary this time.

**Comment by tsunamayo** [comment]
Hi, yes logfile is not really necessary, this was something removed when I made the switch to kill studs (which I think was a good call), but I will put this feature back. Thanks

**Comment by tsunamayo** [comment]
Okay this feature and a new feature of brick grid offset aligning will be in 19w28a. Thanks!
