### ISSUE TITLE
[19w24a] Tooltips disappeared

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#1311]
### Short Description of the issue:

I launched the game a couple of times, played for a couple of hours; On the third launch in-game tooltips (hover over stuff in inventory) first flickered, then later failed to appear entirely.

### Steps to reproduce the issue:

?

### Environment
- Skywanderers version: 19w24a
- Graphics Card: R9 290

**Comment by ZachZent** [comment]
yea, this has been an issue for a bit. It will return, updated eventually

**Comment by tsunamayo** [comment]
Hi, you mean the 3d item preview on the side? (cant see the preview atm, it is also broken, but I can see the UI). Thanks

**Comment by tsunamayo** [comment]
This should be fine now.
