### ISSUE TITLE
[Suggestion] Hyperspeed

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1312]
As combat gameplay is coming soon, I thought I'd throw my suggestion into the ring for hyperspeed... space... cruise... going really fast.

Hyperspeed should work near the same way we have now. It can be used at all times at all positions. All that requires is a pause then it activates. Eventually once gameplay is added, this time should be increased to prevent ships from instantly escaping. The time it takes should depend on the hyperspeed reactor and upgrades, but that and fuel will be ignored for now.
 
After activation there should be a few options for the player. First the player should be able to fly in hyperspeed manually like we can now. Of course, fuel and maybe a variable range would be good constraints, but again that will be ignored for now. The second way to use hyperspeed is though an autopilot. Either before entering hyperspeed or in hyperspeed, you would be able to select and “lock on” to another ship, station, or other detectable object. When in hyperspeed, the ship will auto navigate to the object. You can take control of the ship again by deselecting the object. The final way would be to use the holographic star system map. In the map, you can select a detectable object or a random point in the star system. With the last two, there would have to be a button to reselect the detectable object or point in space. That way you can switch to manual then return to auto pilot without going through the entire process again. That would be a nuisance.
 
Currently when in hyperspeed, you will continue to accelerate infinitely (red graph.) This shouldn’t be the case in game for obvious reasons. The speed should be the opposite (blue graph) and have a set max speed. High but not infinite. This can be variable with engines/reactors.
![graphs](https://user-images.githubusercontent.com/36980446/60704347-0e71fb00-9eb9-11e9-8611-eb1fee37dac1.png)

What is vital regardless of what combination is chosen is how your ship comes out of hyperspace. There should be a manual button to stop like we have now. What is needed is how the ship would interact with other objects, like ships or asteroids. Awhile back, a ship in hyperspeed would slow down slightly when approaching a planet or other object. This is fine but what also needs to happen is when you are x km away from an object, the ship would be forced out of hyperspeed. It must be far enough away so you can’t jump right on top of someone, but not too far that it would take a long time to fly to the target. I’d personally start at 5km away and work from there. Combining this with the autopilot will let the ship exit hyperspeed on its own. This will prevent collisions and make it easier to come out of hyperspeed near the target. Currently it is very difficult to come out of hyperspeed at the perfect time. Chances are you will overshoot or undershoot it by a large margin. As a bonus, this can lead to interdictors which is always a fun gameplay element, but again that will be ignored.

**Comment by tsunamayo** [comment]
Hah, funny things is actually I was working on that for gameplay, update will be live soonish (tm).
Yes I wanted to make space travel easier to deal with, and I made change like you suggested:
Auto lock : you control the direction, but will auto drop off near target. Maybe will be changed to auto drop-off near any target (not just the one locked). Pretty rad to dropoff just in front of your target!
Auto pilot: You assign the target and can grab a cup of coffee at the back of your ship, ship will get to the target on it is own.

The way we select and assign the target is very likely to change, also yes it will be compatible with the holomap. 

I also added a bunch of other stuff like auto land (might add an option if people wants to do it manually).

As for the speed it works like the blue curve (it is not exponential), max speed depends on your ship ratio and how far from a planet you are. I am quite happy with that system, it allows to travel to other planet in a decent time. 

Still need to find a solid name ;)

**Comment by ZachZent** [comment]
Well lucky for you, we created a small list of names

(This is my graph because it is my post :D )
![mygraph](https://user-images.githubusercontent.com/36980446/60706031-70346400-9ebd-11e9-8fbe-30558108ba53.png)

(This is a public graph of names)
![mygraph2](https://user-images.githubusercontent.com/36980446/60706108-9528d700-9ebd-11e9-9da4-28d6cd8f9ef5.png)

**Comment by TheCuriousSkeleton** [comment]
For Hyperspeed you could have Helios (Greek sun god) Drive

**Comment by ZachZent** [comment]
I'd stay away from Greek/Roman names, especially ones from mythology. One because there is no Earth in this universe and two that Greek/Roman mythology names are everywhere. Very, very common. Why not go with something at least more unique, more personalized?

**Comment by tsunamayo** [comment]
So the new name is finally Lightcruise. Dont know why, it just sounded good... Cheers
