### ISSUE TITLE
[19w24a] Painting angled blocks offset by 1 block

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1314]
### Short Description of the issue:
I can't tell if this is the same as [this issue](https://github.com/tsunamayo/Skywanderers/issues/1277), but I don't think it is. That one was causing blocks painted on one side to get skipped on the other. For this one, angled blocks, when painted with mirroring on, sometimes get the adjacent block painted.

### Steps to reproduce the issue:
Place multiple angled blocks in symmetry mode (a "stepped" arrangement seems to show this more easily). Paint a block on one side; there's a good chance the block painted on the other side will be "vertically" offset by one block.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Painting this block on one side:
![20190707140632_1](https://user-images.githubusercontent.com/33041786/60772785-dfc67100-a0c0-11e9-8daf-8a8ece9c6627.jpg)

Instead paints a block 1m up on the other side:
![20190707140634_1](https://user-images.githubusercontent.com/33041786/60772791-ef45ba00-a0c0-11e9-9c79-c910ef1dcab2.jpg)

![20190707140638_1](https://user-images.githubusercontent.com/33041786/60772792-f10f7d80-a0c0-11e9-9092-db72c30ebf3f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3366013/output_log.txt)

**Comment by tsunamayo** [comment]
Patch is not yet live but will be very soon, I think it should also fix this issue. Thanks!

**Comment by tsunamayo** [comment]
Okay I think this was fixed. If not please ping me! Cheers
