### ISSUE TITLE
[19w28a] Icons in codex have white texture

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1316]
### Short Description of the issue:
Small bevel, Pipe and Pipe corner have no icon in the codex, only a white square
![image](https://user-images.githubusercontent.com/27857711/60811767-dce28380-a187-11e9-9b04-1eb3e82612e3.png)

...

### Steps to reproduce the issue:
Open the codex in 19w28a
...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Thanks I forgot to generate the sprites. It is now fixed. Cheers
