### ISSUE TITLE
[19w28a] Brick offset not working (Possible User Error)

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1317]
### Short Description of the issue:
You mentioned that players should now be able to offset brick by a half brick. How do we do this? I've tried using the old 4 to 1 "jumper plates" as well as the regular half bricks but can't work out how to use the offset. 

![image](https://user-images.githubusercontent.com/27857711/60812103-a0fbee00-a188-11e9-86ce-f28b3a5101f2.png)

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Hi, sorry I must have done a mishap with github, but the change is not live in the latest patch. It will be on the next one ;) 19w28b... Thanks!

**Comment by ProPeach** [comment]
Thanks for clearing that up, I can't wait to use it!
