### ISSUE TITLE
[19w28a] Unable to switch ship allignment in ship core

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1318]
### Short Description of the issue:
As the title says, the Rotate and Reverse buttons are missing from the ship core GUI so we are unable to choose an orientation for our ship. (Unless a new method now exists?)
...
![image](https://user-images.githubusercontent.com/27857711/60812250-fe903a80-a188-11e9-8c0e-be1cbbffb903.png)

Autopilot is super fun though!

### Steps to reproduce the issue:
Attempt to reorient your ship core in the GUI
...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Sorry my fault again, I forgot to mention in the patch note I removed that feature. Now the shipcore will look at your yoke orientation, which I think is a lot more easier and logical. Downside (not a big one), is now you can only plug a single yoke per shipcore. Also I had to screw a the yoke orientation... So you will have to rebuild and reassign your yoke... Thanks
