### ISSUE TITLE
[19w28a] Brick on build drone impossibly stretched

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1319]
### Short Description of the issue:
Build drone renders one of it's bricks as elongated in the wrong direction

### Steps to reproduce the issue:
Spawn thew build drone

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190708083744_1](https://user-images.githubusercontent.com/51390907/60812459-8b260300-a15f-11e9-87f7-b52c02b604a8.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368458/output_log.txt)

**Comment by tsunamayo** [comment]
It is fixed and will be in next patch (19w28b). Cheers
