### ISSUE TITLE
Rotating Brick Wrong Block Description

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#132]
Currently the rotating brick uses the same block description as the sliding brick. This is confusing. The text should be updated to reflect what it actually does:

OLD
Use this brick as a base to create sliding construction. Use a sliding extension brick to get longer motion range.

NEW
Use this brick as a base to create a rotating construction. Use control and logic bricks to limit or extend range of motion.

**Comment by tsunamayo** [comment]
Thanks for reporting this. Descriptions will be updated in the next build!
