### ISSUE TITLE
[19w28a] Ships spawn in with misaligned yoke+orientation

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1320]
### Short Description of the issue:
I spawned in a ship that had been built on a starter block sideways. I spawn the ship in to find its orientation reset to the starter block's, and the yoke twisted sideways to match that orientation, as was the flight direction. No connections were broken from the yoke. Opening and closing the ship core UI fixed the orientation. I had to break and replace the yoke.

### Steps to reproduce the issue:
Spawn in a ship that was build in a direction other than that of the starter block's rotation. 

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20190708083947_1](https://user-images.githubusercontent.com/51390907/60812902-90378200-a160-11e9-9594-c3ed822b9865.jpg)
![20190708084207_1](https://user-images.githubusercontent.com/51390907/60812924-962d6300-a160-11e9-9a64-235ae981647e.jpg)
![20190708102556_1](https://user-images.githubusercontent.com/51390907/60826239-69d31000-a17b-11e9-8db9-7e13cdead896.jpg)
![20190708102641_1](https://user-images.githubusercontent.com/51390907/60826243-6c356a00-a17b-11e9-92e0-bd269dc11e02.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368481/output_log.txt)

**Comment by khowhl** [comment]
Same happened to me, with the exception that opening/closing the ship core UI didn't fix anything. My yokes being on a child entitiy changed the ship orientation again, now I fly backyards and on the side :P

**Comment by tsunamayo** [comment]
Sorry my fault again, I forgot to mention in the patch note I removed that feature. Now the shipcore will look at your yoke orientation, which I think is a lot more easier and logical. Downside (not a big one), is now you can only plug a single yoke per shipcore. Also I had to screw a the yoke orientation... So you will have to rebuild and reassign your yoke... Thanks
