### ISSUE TITLE
[19w28a] Blocks/bricks are supersize when placed on shipyards

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1321]
### Short Description of the issue:
A bit of a fun one here. The larger the shipyard is, the larger the blocks appear when you place them on it
...
![image](https://user-images.githubusercontent.com/27857711/60812870-64c98d00-a18a-11e9-9713-fbc0c7875f45.png)

### Steps to reproduce the issue:
Place any block/brick on the shipyard
...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Haha, yes I need to prevent player from building on them. Shipyard tech uses large voxel grid, so I will able to spawn massive stations in space and on torus. I will update you guys soon on that. Thanks!

**Comment by tsunamayo** [comment]
Okay it is now fixed, many thanks!
