### ISSUE TITLE
[19w28a] UI graphical anomalies/odd fracturing

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1322]
### Short Description of the issue:
Game menu UI and Action wheel UI have banding/z-fighting on grey overlays, selected entities in bottom right only show in window when you are physically close to them.

### Steps to reproduce the issue:
Open the game menu [ESC] or the action wheel and observe for a few seconds.

- Select one of the stations with middle mouse button and look at selection window
- Fly within visual range of the station and look again as you approach.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190708083744_1](https://user-images.githubusercontent.com/51390907/60813317-79455f80-a161-11e9-9a82-1962c9dbe937.jpg)
![20190708083925_1](https://user-images.githubusercontent.com/51390907/60813322-7cd8e680-a161-11e9-8f80-791554d29a46.jpg)

![20190708084909_1](https://user-images.githubusercontent.com/51390907/60813372-94b06a80-a161-11e9-9da6-1f4ebc78f2ca.jpg)
![20190708085145_1](https://user-images.githubusercontent.com/51390907/60813378-9a0db500-a161-11e9-925c-febf27e7da0c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368518/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this will be fixed in 19w29b. Thanks a lot!
