### ISSUE TITLE
[19w28a] Planetary Ring Shader Error

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1323]
### Short Description of the issue:
Best to watch the gif rather than listen to an explanation really.
...
![Skywanderers Planetary Ring Bug](https://user-images.githubusercontent.com/27857711/60814178-0d78ec00-a18d-11e9-9efd-0777926d13a2.gif)

### Steps to reproduce the issue:
I'm having trouble reproducing this one. I experienced it after loading up a world after generating a new one and playing around with the shipyards, then saving. After saving and reloading the issue resolved itself. I'll update this thread if I find anything else
...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1050M

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368556/output_log.txt)

**Comment by tsunamayo** [comment]
Weird... From the log it seems there is an issue with the tracking cam... Tell me if you see this again! Thanks for being so active on the new build ;)

**Comment by tsunamayo** [comment]
There is a new fog workflow, so this should not happen. Thanks!
