### ISSUE TITLE
[19w28a] All entities are invisible on world load, names of all entities are "ship name"

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1324]
### Short Description of the issue:
I loaded up my world after saving while docked to a shipyard. After exiting the world and reloading it, all entities were transparent except for the text on my ship's speedometer. When mousing over an entity in building/interaction range, the white selection outline appears. Other than that, they are entirely invisible. The name of an entity selected with the middle mouse is always "ship name" regardless if it's a station or named ship. However, the action wheel still correctly references the names.

### Steps to reproduce the issue:
Save, exit, and re-load your world.
Look around for any floating text from screens and speedometers.
Mouse over an entity to see the default outline.
Middle-mouse select an entity to see "ship name" in the selection window, absent of image.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190708092711_1](https://user-images.githubusercontent.com/51390907/60814704-1f926480-a164-11e9-9b77-accc849be7e5.jpg)
![20190708092830_1](https://user-images.githubusercontent.com/51390907/60814730-2ae59000-a164-11e9-9698-c15a6e0c3682.jpg)
![20190708092843_1](https://user-images.githubusercontent.com/51390907/60814738-31740780-a164-11e9-980c-dc914e550a2f.jpg)
![20190708093003_1](https://user-images.githubusercontent.com/51390907/60814776-4781c800-a164-11e9-997d-b3eb4716973c.jpg)

**Comment by tsunamayo** [comment]
Okay I fixed that issue. Exit and reload are for some reason tricky to do. Fix will be in next update 19w28b. Thanks!
