### ISSUE TITLE
[19w28a] Ship docked on world exit is undocked on reload

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1325]
### Short Description of the issue:
A ship docked to a shipyard when the world is exited will be undocked on reload.

### Steps to reproduce the issue:

1. Dock a ship to a shipyard
2. Save game
3. Exit world
4. Reload world

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368743/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed I need to add this to the save. I keep you posted, thanks

**Comment by tsunamayo** [comment]
Okay I added that feature for 19w28a. Thanks!
