### ISSUE TITLE
[19w28a] phantom hostiles, very spooky

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1327]
### Short Description of the issue:
3? "HOSTILE"s showed up on the bottom right selection screen out of nowhere, and disappeared seconds after.

### Steps to reproduce the issue:

- Pilot a ship/be able to see indicators for entities
- Exist

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190708094316_1](https://user-images.githubusercontent.com/51390907/60817630-0ab8cf80-a16a-11e9-95d7-458ca0ca8713.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368793/output_log.txt)

**Comment by tsunamayo** [comment]
Yes haha it was a small bug where the tracking cam data is showing even on ship control. It is now fixed for 19w28b. Thanks!
