### ISSUE TITLE
[19w28a] child portion of hinges and rotors of existing ships offset from parent, loop their movement soundbite

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1328]
### Short Description of the issue:
Hinges and rotors of ships already in-world have any and all hinges and rotor child entities offset by a portion of a brick's length from center, and create a horrible noise loop from the motion soundbite of hinges/rotors/rails (rails don't look affected, may be emitting noise as well).

### Steps to reproduce the issue:

- Press F7 to teleport to existing ships (with rails/hinges/rotors on them) and look at the hinges and rotors.
- Reset the position of the rotor heads and hinge parts by changing their angle/activating/deactivating.
- Listen to the terrible noise that didn't go away.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190708102409_1](https://user-images.githubusercontent.com/51390907/60818758-4a80b680-a16c-11e9-9776-0cb80ca124d5.jpg)
![20190708102437_1](https://user-images.githubusercontent.com/51390907/60818767-4c4a7a00-a16c-11e9-9366-8c4f7ac9d499.jpg)
![20190708102654_1](https://user-images.githubusercontent.com/51390907/60818791-566c7880-a16c-11e9-8217-e76cc588cdd4.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368867/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I dont really see this, could you please give me your ship blueprint? Thanks!

**Comment by Majikmonster** [comment]
It happened on all 3 ships in the area, but here is the blueprint where it's most noticeable:
[2019-7-8_bricc fighter.zip](https://github.com/tsunamayo/Skywanderers/files/3371480/2019-7-8_bricc.fighter.zip)

**Comment by tsunamayo** [comment]
Okay I fixed this issue, it was a floating point error. Please tell me if after 19w29b if it is not fixed on your side (I didnt had the clicking noise issue). Cheers!
