### ISSUE TITLE
[19w28a] Joystick disappeared from codex and world

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1329]
### Short Description of the issue:
The joystick control brick has vanished completely.

### Environment
- Skywanderers version: 19w28a

### Additional information:
![Inked20190708102715_1_LI](https://user-images.githubusercontent.com/51390907/60819795-39d14000-a16e-11e9-8816-2432fd6db796.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3368937/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I removed it as the design was not making sense as now joystick orientation is important to determine ship control orientation. But I plan to create a new design (it was not yet updated to the new style), it will take a bit of time though... Thanks

**Comment by Majikmonster** [comment]
I hope this gets re-added once the design is ready 🤞
