### ISSUE TITLE
Hinge Bricks Not Centered

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#133]
When placing hinge bricks on normal blocks, the other side of the hinge is offset from center. When attaching the same size grid, the attached blocks aren't centered. This has the effect that one side is clipped while the other has a small space. See attached image for reference where the attached blue blocks have a space on the right but are clipping on the left of this doorway.

![20171023200702_1](https://user-images.githubusercontent.com/33043997/31919046-d9b38942-b82d-11e7-847a-852382d327c2.jpg)

**Comment by Rizzo911** [comment]
NOTE: I discovered that this only occurs when you build a structure directly from the torus. If you build the structure from the starter block, this doesn't occur. It should be possible to build on the ground without the starter block, since the game allows it, but the behavior changes when you do this.

**Comment by tsunamayo** [comment]
No longer applicable.
