### ISSUE TITLE
Custom paint color on ships resets to default paint color on reload (Can be corrected in-game)

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1330]
### Short Description of the issue:
Custom paint color will reset in the tool UI and on all ships that have a custom color on reload of world.

### Steps to reproduce the issue:

1. Customize any color in the paint tool UI and apply it to a ship
2. Save and exit world
3. Reload world

### The "fix"

1. Paint or remove paint on any affected ship
2. Open the paint UI and switch selected paint
3. Exit UI

### Environment
- Skywanderers version: 19w28a, 19w24a, possibly earlier versions as well
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
Before exit:
![20190623084034_1](https://user-images.githubusercontent.com/51390907/60820867-5cfcef00-a170-11e9-971f-2aa41f1604e0.jpg)
After reload:
![20190624013050_1](https://user-images.githubusercontent.com/51390907/60820871-60907600-a170-11e9-8c41-3a1ba5bd9e57.jpg)
After using the 'fix':
![20190624014713_1](https://user-images.githubusercontent.com/51390907/60820992-a0eff400-a170-11e9-9fcf-f92da1293708.jpg)

**Comment by tsunamayo** [comment]
Hum, custom color are just proven to be huge pain to make work properly. I think I will remove them one day, and instead give you plenty of color options (like 256 or more) as now I can have larger paint data. Cheers

**Comment by ExodistSKY1** [comment]
I think If it will help clean up the paint and allow for no mess ups it will be well accepted. As long as there is a decent amount of options available to the builders it wont be a problem.

**Comment by Majikmonster** [comment]
Paint issue resolved with paint system overhaul 👍
