### ISSUE TITLE
[19w28a] Deleting docked ship shows landing pad as still "Taken"

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1333]
### Short Description of the issue:
If a ship is deleted while docked to the landing pad, the pad still shows as being taken. Saving and reloading fixes the issue.

### Steps to reproduce the issue:
Dock ship, delete ship, check pad status.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190708155208_1](https://user-images.githubusercontent.com/33041786/60842088-f213de00-a198-11e9-9b64-116c2c7247ce.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3370228/output_log.txt)

BTW, I just wanted to let you know that the new autopilot options and the docking system are great! :D I really like the new mouse and HUD elements style too.

**Comment by tsunamayo** [comment]
Yes I didnt think about that, thanks! Also I the build drone in upcoming update will be linked to the shipyard, that was the plan all along... Thanks!

**Comment by tsunamayo** [comment]
Okay this case is dealt with in 19w28b. Glad you like the new features ;)
Thanks
