### ISSUE TITLE
[19w28a] Large landing pad says max size is 90m

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1334]
### Short Description of the issue:
Not sure if this is a bug, but the large landing pad says it has a maximum size of 90m. It seems to be able to handle 100m ships just fine, and since the backer ships include a number of 100m ships, I wondered if this was a typo.

### Steps to reproduce the issue:
See above.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190708161108_1](https://user-images.githubusercontent.com/33041786/60843065-31432e80-a19b-11e9-9abe-979c3794f65f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3370249/output_log.txt)

**Comment by tsunamayo** [comment]
Not sure about the size 100% yet, yes I would prefer to put a 100m in that that would be nice ;). But it was 128 - 32 = 96 rounded down = 90. 
For backers no pb I will just round up all reward to the upper category once they are fixed.
Current (temporary) cat would be:
cat 5: 30m
cat 4: 90m
cat 3: 150m
cat 2: 210m
cat 1: 340m
cat 0: 470m.

Jump to cat 5 to cat 4 is a bit steep, but honestly not a big deal, people should be able to switch to cat 4 pretty fast, and cat 5 will be more to make small fighter ect.
Bigger shipyard will be only on Torus, so they will be more rare.

Also one day I would like to put cat 5 shipyard like feature inside bigger ship, to make carrier, or exploration shuttle ect. We shall see.

Bigger than that it is gonna be mother ship size, they wont be serviceable by standard stations. I will have to come up with some interesting mechanic for them, for it is not the priority for now. If you have some cool idea of what I could do with mothership, please shoot! Also I might drop the latest category and say mothership is > 340m, we shall see.

 Cheers
