### ISSUE TITLE
[19w28a] White squares in codex for some blocks

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1335]
### Short Description of the issue:
Edit: [already spotted by ProPeach!](https://github.com/tsunamayo/Skywanderers/issues/1316)

The icons for the Small Bevel, Pipe Corner, and Pipe in the codex are white squares. The preview images still work though.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190708170403_1](https://user-images.githubusercontent.com/33041786/60845917-63588e80-a1a3-11e9-95db-1a305d401010.jpg)

![20190708170404_1](https://user-images.githubusercontent.com/33041786/60845922-65bae880-a1a3-11e9-8193-920bc22520a5.jpg)

![20190708170407_1](https://user-images.githubusercontent.com/33041786/60845927-6784ac00-a1a3-11e9-9816-7f7430cdc139.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3370378/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this will be fixed in upcoming 19w28a! Cheers
