### ISSUE TITLE
[19w28a] Build drone's antenna is stretched

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1336]
### Short Description of the issue:
The build drone's "antenna" brick is stretched back in a way I didn't know was possible. It's also shorter than it was, almost like the game took the value for its Height and swapped it with the value for its Length.

### Steps to reproduce the issue:
Summon drone, look at antenna. Might have to move quicker than the drone can rotate to see it clearly.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190708171457_1](https://user-images.githubusercontent.com/33041786/60846165-3658ab80-a1a4-11e9-882e-3b1d7e1a9f5d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3370391/output_log.txt)

**Comment by ZachZent** [comment]
FR-3N is just happy to see you

**Comment by tsunamayo** [comment]
Yes, I made some refactor on the scaling side to make things cleaner in code, but unfortunately it messed up some build. It should have messed up your build also I think, do you confirm if you used that brick? Cheers

**Comment by Majikmonster** [comment]
#1319 
I haven't seen the issue elsewhere, at least not yet.

**Comment by tsunamayo** [comment]
Okay I fixed the FR-3N! Will be in next patch 19w28b. Cheers
