### ISSUE TITLE
[19w28a] Engine trails travel through ship

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1338]
Engine trails travel through ship from all placed engines.

...

-spawn ship with multiple engines (some blocked by ship) 

-start flying 

...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: 1080ti

![20190708152454_1](https://user-images.githubusercontent.com/45324484/60855750-919d9480-a1ca-11e9-9bec-55d901c614ba.jpg)

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint so I can see the use you are making with engine? Why would some engine be blocked by the ship? (are they completely enclose, or not pointing to the rear?) Cheers

**Comment by ExodistSKY1** [comment]
Sending BP via email as it is for the Exploration competition

**Comment by tsunamayo** [comment]
Sure.

**Comment by tsunamayo** [comment]
Deprecated. Thanks!
