### ISSUE TITLE
Managed to not be able to de-select controls and am still parented to it, respawn didn't fix

### ISSUE THREAD

**Issue by ForsakenHarmony** [tsunamayo/Skywanderers#134]
Don't know what exactly I did, but I somehow exited the seat of the hovercraft thing and am still moving with it & controlling it, but it also moves my character

**Comment by tsunamayo** [comment]
Hello, was it the base hovercraft of the starting area or one that you build yourself?

**Comment by ForsakenHarmony** [comment]
Starting area hovercraft

**Comment by tsunamayo** [comment]
I made a few change regarding system controls. I will close the issue as it should no longer happens. Should it still happens could you re-opened it? Cheers
