### ISSUE TITLE
[18w28a] Fade through shipyard platform 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1340]
When running on the shipyard platform your character will fall through it towards the edge... of what I think to be the actual edge of the 90m's    on the 30m platform you are stooped above the beveled edge in some cases but fall through in others.

...

Run around forcing yourself to stay on the platform

...

### Environment
- Skywanderers version: 18w28a
- Graphics Card: 1080ti

![20190708232508_1](https://user-images.githubusercontent.com/45324484/60859359-e693d780-a1d7-11e9-865f-ba5fabfedd3d.jpg)
![20190708232426_1](https://user-images.githubusercontent.com/45324484/60859360-e72c6e00-a1d7-11e9-8a3b-300101b1389c.jpg)
![20190708232445_1](https://user-images.githubusercontent.com/45324484/60859361-e72c6e00-a1d7-11e9-8824-06a6038b6a08.jpg)

**Comment by tsunamayo** [comment]
Yes this is a bug because of the current collision engine. It will be fixed when I update the engine. Thanks!

**Comment by tsunamayo** [comment]
Issue is now fixed. Thanks!
