### ISSUE TITLE
[19w28a] are the ships supposed to float a specified distance above the landing pad?

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1341]
Not sure if a bug or not... are the ships supposed to float a specified distance above the landing pad?

...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: 1080ti

![20190708235034_1](https://user-images.githubusercontent.com/45324484/60861111-dc290c00-a1de-11e9-998b-ef1be5410193.jpg)

**Comment by tsunamayo** [comment]
Not really, they should descend down until contact. Could you give me your blueprint so I can have a closer look at it? Thanks

**Comment by Majikmonster** [comment]
Interestingly enough, mine stops almost exactly far enough to allow the landing gear to make contact when extended, without having to extend them first. Is there part of your ship that is able to angle/extend that far down?

**Comment by ExodistSKY1** [comment]
yes, i have tried multiple, My ship with landing gear stops perfectly for the landing gear to touch. My drop ship hovers (which, now thinking about it a little I would not mind in some cases. Tsuna, if an anti gravity/ gravity repelling type landing block/brick for those of us that might not want to create landing gear on some ship styles could be added) that might be pretty sweet and give some of us a way of not making elaborate lag endusing brick landing gear ;) ;)    Just a thought

**Comment by tsunamayo** [comment]
This should be fixed now. I will think about that gravity repelling thing... Or I might add another landing pad type. Cheers
