### ISSUE TITLE
[Missing Feature] Exiting the landing pad menu

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1342]
Don't know if this is intentional but when you land at a pad, the only way to get out of the menu is to leave the joystick/chair. An exit button would be a nice feature to add. Even if it also get you out of your seat, still a nicer system then just holding F.

![Undock](https://user-images.githubusercontent.com/36980446/60865156-45f2e700-a1da-11e9-9b41-1b65c8cbfb3f.png)

**Comment by tsunamayo** [comment]
Yes I agree 100%, I wanted to add it. This whole menu was very wip, I will add more functionality here. Also the building drone will be orbiting shipyard now, and will be spawn ship from here! Cheers

**Comment by tsunamayo** [comment]
Okay actually I added that feature a couple of build back. Thanks!
