### ISSUE TITLE
[19w28a] Exiting game will cause logic to un-link

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1345]
when opening the game or spawning in most logic and buttons that were linked will be un-linked

...

-spawn in ship with logic
-try to use it

...

### Environment
- Skywanderers version: 18w28a
- Graphics Card: 1080ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3379034/output_log.txt)

**Comment by khowhl** [comment]
I noticed this happens on buttons and or linkable items that are on children entities

**Comment by tsunamayo** [comment]
Okay I fixed this issue, fix will be on 19w29a. Thanks!
