### ISSUE TITLE
[19w28a] Capacitor can only be placed at one rotation

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1347]
### Short Description of the issue:
When attempting to attach a capacitor block to a reactor block, if the capacitor block is rotated before placing it, the ghost image will disappear and the block cannot be placed. Only one of the four possible rotations will show the capacitor as visible and allow it to be placed.

### Steps to reproduce the issue:
Place some reactor blocks, then select the capacitor block. Hold the ghost image over the reactor block, then press Q or E to rotate it.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Before rotating the capacitor:
![20190711221500_1](https://user-images.githubusercontent.com/33041786/61099971-e68b1600-a429-11e9-84ed-c3ce16f54ea3.jpg)

After rotating it. Capacitor block is still selected and waiting to be placed, but is invisible.
![20190711221505_1](https://user-images.githubusercontent.com/33041786/61100000-002c5d80-a42a-11e9-8692-2f1a3fb37ac4.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3384850/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed. Issue is now fixed for 19w29a. Thanks!
