### ISSUE TITLE
[19w28a] Placing a rotator block on a rail prevents the rail from functioning properly

### ISSUE THREAD

**Issue by khowhl** [tsunamayo/Skywanderers#1348]
### Short Description of the issue:
Placing a rotator block on a rail prevents the rail from functioning properly. Some small hiccups can happen but the full movment is impossible
...

### Steps to reproduce the issue:
- Create a new ship
- place a few hull blocks and then a rail on them
- add a hull block onto the rail and place a rotator block on that
- try activating the rail
...

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GeForce 1060 3 Gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![rotatorblockonrail](https://user-images.githubusercontent.com/29357401/61126461-c94b5b80-a4ac-11e9-8047-939943a6af60.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3386330/output_log.txt)

**Comment by tsunamayo** [comment]
Issue seems fixed. Thanks!
