### ISSUE TITLE
[BUG] Exiting cockpit from structure built from the ground (no starter block)

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#135]
When sitting (or standing) in a cockpit and you press F to exit from a structure you've built from the ground of the torus (i.e. not from the starter block, but by placing blocks directly on the ground and then removing the spaces to create a ship), the character becomes stuck and the menu options disappear. There is no way to move around and repeatedly hitting F or trying to interact with nearby items has no effect. I think the game still thinks you are in the seat because you can see some of the ship information if you pan around. Only way to end this is to restart the game. Presumably, bases would not have a cockpit, but I didn't realize that the starter block was more critical and therefore started my first ship by directly placing blocks on the ground and then removing them once the ship was built.

**Comment by tsunamayo** [comment]
Okay this is not how you create a new ship unfortunately ;-). Did you only used a seat, or did you also activated a Spaceship core? There was a bug with spaceship core on Torus, but I have fix it (will be in next update)

**Comment by Rizzo911** [comment]
There was a core and a seat and a control yoke. The yoke was attached to the core. Sitting in the seat was fine. It was when I tried to take control of the structure via the yoke that it locked up.

**Comment by tsunamayo** [comment]
Okay this bug was fixed a few days ago. Cheers!
