### ISSUE TITLE
[19w28a] Switches on child entites

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1351]
In my game, I have a door with the switch on the child entity of a door. It is linked to a gate and so on. Every time I turn off and on the game, the link will delete. It is only the child entity switches that reset each time. That's about it

**Comment by khowhl** [comment]
https://github.com/tsunamayo/Skywanderers/issues/1345

**Comment by tsunamayo** [comment]
Yes it seems the same issue as #1345 . I keep you posted.

**Comment by tsunamayo** [comment]
Okay I fixed this issue, fix will be on 19w29a. Thanks!
