### ISSUE TITLE
[Question] Any idea how large 20m blueprint file sizes should be?

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1352]
Hi Tsuna! Some of us were trying to figure out if we were putting too much detail on our ships, and wanted to know if you have any idea yet of how many kilobytes you want smaller ship blueprints (the Cat 5 ones like fighters, shuttles, etc.) to be.

**Comment by tsunamayo** [comment]
Dont really have any requirement of course, you build as you want ;) Size should not be an issue, especially on small build. Large ship might be a different story though, but it should be fine. Cheers

**Comment by Dwarf-LordPangolin** [comment]
That's awesome! Thanks for the info. :)
