### ISSUE TITLE
[19w28a] Game seems to be drawing invisible block/brick faces

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1354]
### Short Description of the issue:
If two blocks or bricks are placed next to each other, the game seems to still be drawing the surfaces of both even though they are invisible. This is presumably degrading the game's performance, as it must be using system resources texturing and (possibly lighting) things that will never be seen.

### Steps to reproduce the issue:
Place two or more blocks next to each other, press F10 to enter spectate mode, move the camera so it is inside one of the blocks; the side of the other block will be visible, even though it cannot be seen by any of the players.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
As an example: if I build a 3x3x3 cube of blocks ...
![20190713225251_1](https://user-images.githubusercontent.com/33041786/61179089-09036780-a5c1-11e9-8c46-bebf47056d33.jpg)

... and then spectate inside of it, the game draws **all** of the block faces, including ones that nobody that isn't spectating could ever see. This is probably very performance unfriendly, since the computer is drawing 162 block faces when it only needs to draw the 54 exterior ones.
![20190713225308_1](https://user-images.githubusercontent.com/33041786/61179095-1b7da100-a5c1-11e9-9329-5a2bcc0687c0.jpg)

**Comment by tsunamayo** [comment]
Yes it is not really a bug, just a tech choice that was made when I fully committed to the new rescale tech. The thing with the new rescale tech is that it when you spawn a 10x10 wide block for example, you dont get a 200 tri for the large face, you only get 2. 
So:
 1) you save a lot of tri in those case, 
2) it makes the check for the hidden face much harder to do and more importantly yield much less potential gain, as very often you wont be able to remove the face at all.
3) if people really use the stretchering tech then it works well, but if people build minecraft style (one by one) then it will be much more inefficient.

Yes hidden face are very inefficient from a fill rate point of view. This is why I had to do the new rendering refactor, to draw a lot less - which is working very well. Older ship build with the old tech like the basalisk where lagging a lot, but with the new tech it render just fine.
I had to do this anyway as when you look from a ship from the outside there is a lot hidden face from the ship inside room and opposite side (stretching tech or not), potentially 10s of layers depending on ship size and how many room are inside.
You can press F3 if you are curious, there is a few options that shows how the new rendering tech works. You can choose view Overdraw for example. I will do a video one day, it is a great tech, it also greatly reduce memory and CPU overhead to build the geo.
Cheers
