### ISSUE TITLE
[19w28a] All blocks are invisible

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1356]
### Short Description of the issue:

I loaded into 19w28a ok once or maybe twice, but now consistently see all of my ship's block as invisible.

### Steps to reproduce the issue:

Load skywanderers

### Environment
- Skywanderers version: 19w28a
- Graphics Card: GTX 1060

### Additional information:
![invisible](https://user-images.githubusercontent.com/40872394/61328799-bb326d80-a813-11e9-8265-227453522ed5.gif)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3399070/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, could you please Zip your save folder so I can try to reproduce locally? It seems there is a big issue looking at your log file. Thanks!

**Comment by Xxxsquidlover101xxX** [comment]
This is the exact same issua i have

**Comment by Lsutehall** [comment]
zipped "save_data" folder attached.

to clarify: i've not tried creating a new character or deleting the instances folder to prompt generation of a new world, because I wanted to get an output log in the error state.

I'll update this issue after updating the game to19w29a

[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3402874/Save_Data.zip)

**Comment by Lsutehall** [comment]
19w29a - this now loads correctly and i can see everything ok. I don't appear to have "tooltips" in the codex, and bug #1298 still occurs. Newest output_log attached

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3402915/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed I can see some error related to the codex preview...

**Comment by tsunamayo** [comment]
Okay issue was fixed.
