### ISSUE TITLE
[19w29a] Slider Block and hinges have incorrect names

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1360]
### Short Description of the issue:
Just a simple one, the Sliding Block is called "Sliding Brick" in the codex and the description is wrong.
Also, all hinges are named "Hinge" rather than "Hinge Block" and "Hinge Brick"
...

### Steps to reproduce the issue:
Open the codex, find the Sliding Block and hinges
...

### Environment
- Skywanderers version: 19w29a
- Graphics Card: GTX 1050M
![image](https://user-images.githubusercontent.com/27857711/61393777-9f81a280-a8b9-11e9-887e-92c621a09fd1.png)

**Comment by tsunamayo** [comment]
Thanks! I updated the name. I also remove the old slider from the codex... Dont hate me ;)
