### ISSUE TITLE
[19w29a] Canopies show incorrect values on the placement ruler

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1361]
### Short Description of the issue:
When dragging canopies and canopy wedges their placement size start at 0.25m^3 rather than 1m^3
![image](https://user-images.githubusercontent.com/27857711/61394424-f63bac00-a8ba-11e9-8d73-62ae447d86ac.png)

...

### Steps to reproduce the issue:
Attempt to drag the canopy or canopy wedge and note the values on the placement ruler
...

### Environment
- Skywanderers version: 19w29a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Right I noticed that and I forgot to fix it...

**Comment by tsunamayo** [comment]
Okay it will be fixed for 19w29b. Cheers!
