### ISSUE TITLE
[Suggestion] Keeping both types of brick hinges

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1362]
I am suggesting that we keep both types of the brick hinges. 
      -the older version with the cylindrical hinge appearance 
                                     and
      -the newly added squared hinge appearance 

Due to the nature of the game and builders "usually" looking for specific aesthetics in their builds. I feel having two choices of brick hinges (due to the vastly differing appearance of the two) would be a benefit to the game and future builds from the community.

Thank you

**Comment by tsunamayo** [comment]
Hi, by cylindrical you mean the current one (not the one before that, that was more cylindrical?) Is it only a question of style? Thanks

**Comment by ExodistSKY1** [comment]
Yes I mean the current two that are in game. (i should have posted a screenshot for clarity)

![20190717195913_1](https://user-images.githubusercontent.com/45324484/61421707-d5308680-a8cd-11e9-83b4-e7474530c9d2.jpg)

I like both styles visually and can see a use for both on builds from ships to mechs.

But... if the older hinge will make things more difficult on the code side and make it "less clean" then it is not a big deal to only have the new hinge.

**Comment by tsunamayo** [comment]
Okay sorry I got rid of the older hinge as it was not clean code-wise. Thanks!
