### ISSUE TITLE
[19w29a] Ship core paint not changing HUD color

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1363]
### Short Description of the issue:
Painting the ship core no longer changes the HUD color.

### Steps to reproduce the issue:
Make a new ship, place a ship core, paint it, and fly it through a yoke. The HUD will still be white.

### Environment
- Skywanderers version: 19w29a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3403633/output_log.txt)

**Comment by tsunamayo** [comment]
Yeah sorry this is something I am not sure I will keep... I will have to start working with color to give player information, so I am not sure it was the smartest idea. We will see how it goes!

**Comment by tsunamayo** [comment]
Okay this feature is deprecated. Thanks!
