### ISSUE TITLE
[19w29a] Lines on windows in sunlight

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1364]
### Short Description of the issue:
Weird lines appear on the sides of the angled windows when glare from the star is on them.

### Steps to reproduce the issue:
Turn a ship with the angled windows so that the reflection from the star's light is coming off it.

### Environment
- Skywanderers version: 19w29a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190717145015_1](https://user-images.githubusercontent.com/33041786/61407585-b4ebd200-a8a3-11e9-838f-526154be4b38.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3403639/output_log.txt)

**Comment by Majikmonster** [comment]
I get this too, but all the time on every canopy of that type.
Same graphics card and game version as above.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3403895/output_log.txt)

**Comment by tsunamayo** [comment]
This issue will be fixed in upcoming 19w29b (hopefully soon) Cheers
