### ISSUE TITLE
[19w28a+29a] collision detection makes some bricks unable to placed/place-able only on full meter grid

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1365]
- Some flowers cannot be placed at all, thinking there is a collision on the base where it is supposedly clear.
- The new flat switches can only be placed on a face that is on the edge of a full cube (on meter grid only)

### Steps to reproduce the issue:

- Attempt to place Plant B (triple white flower, double pink flower) onto any surface on any meter grid or offset from meter grid.
- Attempt to place Pant B (triple white flower, double pink flower, double purple flower) onto any surface with any offset from meter grid.
- Attempt to place flat switch brick onto any surface with any offset from meter grid.

### Environment
- Skywanderers version: 19w29a (game still says 19w28a on the main menu 😋 )
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20190717175517_1](https://user-images.githubusercontent.com/51390907/61414950-69462200-a8bd-11e9-8482-4add4e0fa4b2.jpg)
![20190717175521_1](https://user-images.githubusercontent.com/51390907/61414951-69462200-a8bd-11e9-80aa-18f05b399075.jpg)
![20190717175536_1](https://user-images.githubusercontent.com/51390907/61414952-69462200-a8bd-11e9-847c-69002c116e99.jpg)
![20190717175538_1](https://user-images.githubusercontent.com/51390907/61414953-69462200-a8bd-11e9-8546-b125861d139b.jpg)
![20190717175541_1](https://user-images.githubusercontent.com/51390907/61414954-69462200-a8bd-11e9-9bbe-6ec534a0797f.jpg)
![20190717175551_1](https://user-images.githubusercontent.com/51390907/61414955-69462200-a8bd-11e9-858f-e25d92d35fec.jpg)
![20190717175638_1](https://user-images.githubusercontent.com/51390907/61414956-69462200-a8bd-11e9-9517-ef71a0dbf047.jpg)
![20190717175640_1](https://user-images.githubusercontent.com/51390907/61414957-69462200-a8bd-11e9-93c8-46034fd9599f.jpg)
![20190717175642_1](https://user-images.githubusercontent.com/51390907/61414958-69462200-a8bd-11e9-8e1c-7a6989a11eaf.jpg)
![20190717175653_1](https://user-images.githubusercontent.com/51390907/61414959-69deb880-a8bd-11e9-9a8e-1e40ead27e8a.jpg)
![20190717175706_1](https://user-images.githubusercontent.com/51390907/61414960-69deb880-a8bd-11e9-932c-e555ed702718.jpg)
![20190717175733_1](https://user-images.githubusercontent.com/51390907/61414949-69462200-a8bd-11e9-837c-a7831b26c752.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3403990/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for the screens! I fixed all issue, will be line on 19w29b. Thanks!
