### ISSUE TITLE
[19w29a] thruster trails only produced by some engines on multi-engine ship

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1366]
I have a ship with 34 separate engines, all but 6 of which no longer produce trails in the current version. The trail color is also washed out from before.

### Steps to reproduce the issue:
Place 2-3 dozen separate engines on a ship. Fly with said ship until trails appear (if at all).

### Environment
- Skywanderers version: 19w29a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3404017/output_log.txt)

**will message you the BP and screencap because it's my competition ship**

**Comment by tsunamayo** [comment]
Okay, yes I will need the blueprint to investigate. Thanks!

**Comment by Majikmonster** [comment]
BP+pics sent via email ✉️📬

**Comment by tsunamayo** [comment]
Deprecated as trail is no longer used. If it come back that will be a custom solution! Thanks
