### ISSUE TITLE
[19w29a] thruster emissive texture dim, reflects light like plastic

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1367]
Thruster glow is dim, looking like they have been turned off, and the light-producing parts reflect light as if they were plastic

- Skywanderers version: 19w29a
- Graphics Card: Nvidia GeForce GTX1060 6gb

![20190717193405_1](https://user-images.githubusercontent.com/51390907/61419418-2b042f00-a8cc-11e9-9aaa-382a5c87a77f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3404168/output_log.txt)

**Comment by tsunamayo** [comment]
Okay good spot, it is now fixed for 19w29b! Cheers
