### ISSUE TITLE
Character model "Alien C" does not hold multitool properly

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1368]
Alien C's handling of the multitool model is broken in 3rd person (appears fine in 1st person)

- Switch from any other playermodel to Alien C
- Hold the multitool as all playermodels

- Skywanderers version: 19w29a
- Graphics Card: Nvidia GeForce GTX1060 6gb

This is not a new bug. It has existed since the player model update*
![20190717143544_1](https://user-images.githubusercontent.com/51390907/61419734-897ddd00-a8cd-11e9-8abc-43380057acb6.jpg)
![20190717143504_1](https://user-images.githubusercontent.com/51390907/61419735-8a167380-a8cd-11e9-84cf-6841974075ae.jpg)
![20190717143517_1](https://user-images.githubusercontent.com/51390907/61419736-8a167380-a8cd-11e9-9bce-846eba360a73.jpg)
![20190717143531_1](https://user-images.githubusercontent.com/51390907/61419737-8a167380-a8cd-11e9-851e-ff99d9b6ae3e.jpg)

*as far as I know

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3404178/output_log.txt)

**Comment by tsunamayo** [comment]
Okay nice spot, thanks for the screenshot. Will be fixed for 19w29b. Thanks!
