### ISSUE TITLE
[19w29a] Deleting old rails crashes game

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1369]
Trying to delete the old rails on a ship will crash the game to the desktop. 

...

Load a pre 19w29a blueprint with old rail
try to delete the old rail
watch game crash to windows 

:::EDIT:::
It seems to only be effecting two of my builds that were in the world previously. Although it will not let me delete them. I am sure a new world would fix the problem for me

...

- Skywanderers version: 19w29a
- Graphics Card: 1080ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3404578/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, could you please send me one of those blueprint so I can reproduce? Thanks!

**Comment by ExodistSKY1** [comment]
Sent Via Email

**Comment by tsunamayo** [comment]
Okay issue is fixed for 19w29b. Cheers
