### ISSUE TITLE
[Startup] First Time Startup

### ISSUE THREAD

**Issue by powerbrik** [tsunamayo/Skywanderers#137]
[b]Description of issue:[/b]
Game crashes on start-up, I am not able to start the game.
[b]Frequency of issue:[/b]
I have attempted to start the game 4 times and each time the game has crashed after the 'Made with Unity' screen.
[b]Steps to replicate issue:[/b] //THIS IS VERY IMPORTANT//
Activate the .exe , press play, and let the game start up.
[b]Possible Workaround:[/b]
I haven't been able to play.
[b]Images/video/logs:[/b]
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409650/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409651/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409652/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409653/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409654/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409655/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409656/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409657/output_log.txt)

[b]Hardware Configuration:[/b] //FOR CRASHES ONLY//
OS: Windows 10 Pro
CPU: Intel Core i5-4300U
GPU: Haswell GT2
RAM: 4.00 GB

**Comment by powerbrik** [comment]
Tried to start the game 2 more times.
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409701/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409702/output_log.txt)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409703/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1409704/error.log)
What am I doing wrong?

**Comment by tsunamayo** [comment]
Hello, sorry to hear that! Could you please give me more info on your GPU? It seems already clearly below minimum specs, as it is an old low end integrated CPU. Do you run any recent game on your computer?
Francois

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by powerbrik** [comment]
I went into the Skywanderers folder. I do not have a Save_Data folder at all. I think you were right in your previous post. My laptop is quite low-end and I am below minimum specs. I was so excited to play, I forgot to check my specs.
