### ISSUE TITLE
[Bug] Logic pulses upon connection

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1371]
Whenever you connect buttons, switches, gates, etc. it will automatically pulse it as in the video added.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3405628/output_log.txt)
https://youtu.be/qBa6TIL6MJA

**Comment by tsunamayo** [comment]
Yes that is actually a feature! You dont have to think in term of pulse anymore with the "new" logic system, it should behave like it is constantly sending 0 or 1 down the link chain. Of course behind the scene I send pulse only when something change, but for the player it should be transparent. So if now you plug a 0 into your system then it will adapt to it.
 Cheers.
