### ISSUE TITLE
[Bug] Painted Shapes are off by half a brick on child entities / [Suggestion] Let us place the Paint schemes freely

### ISSUE THREAD

**Issue by MormegiI** [tsunamayo/Skywanderers#1373]
### Short Description of the issue:
The paint schemes (line etc) are off by half a brick (see image) on child entities

### Steps to reproduce the issue:

Create child entity by using a new hinge,, use paint tool on it.

### Environment
- Skywanderers version: current
- Graphics Card: GTX 770

### Additional information:

Main Entity: 
![grafik](https://user-images.githubusercontent.com/51251532/61472386-9f9aa480-a984-11e9-9461-ff702d476270.png)

Child Entitiy:
![grafik](https://user-images.githubusercontent.com/51251532/61472376-990c2d00-a984-11e9-98c2-064c767d9d7c.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3407340/output_log.txt)

Suggestion:
It would also be really cool if the paint schemes were only taking up the space they actually use. I.e. it would be nice to be able to place them freely, e.g. several lines next to each other (touching on the long side) or similar..

**Comment by tsunamayo** [comment]
Right now stencils use a radically different tech than bricks so it wont be possible, but I wanted to try to move them to a tech much closer to the brick, I still need a bit of testing to see if it is possible. In the meantime I can try to fix the hinge issue. Cheers

**Comment by tsunamayo** [comment]
Okay I fixed this issue, but you are not gonna like it because it will mess up with your existing children entity (it will lower them down quite a bit so they will stuck...). Trying on your suggestion was already on my todo list for the coming weeks. Thanks!
