### ISSUE TITLE
[19w29a] Canopy blocks placement in whole voxel

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1374]
### Short Description of the issue:
Dragging the canopy by .25m increments (which is awesome BTW) prevents things from being placed in the 1m voxel that the canopy partially extends into. This also goes the other way; placing a brick in a 1m voxel prevents the canopy from being dragged into that voxel, even if it would not clip into the brick.

### Steps to reproduce the issue:
Place a brick at one edge of a 1m voxel space, then place a canopy outside it, and try to drag it up to that brick. The placement indicator will turn red as soon as it enters the voxel the brick is in.

### Environment
- Skywanderers version: 19w29a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190718163802_1](https://user-images.githubusercontent.com/33041786/61493930-6fe69f00-a97a-11e9-9286-94a7c8867d9b.jpg)

![20190718163803_1](https://user-images.githubusercontent.com/33041786/61493933-7248f900-a97a-11e9-9844-44a96f806111.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3408531/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, issue is fixed! I will push it with 19w29b tonight. Cheers!
