### ISSUE TITLE
[19w29a] rotors adopt the child entities of other rotors, confuse mass, movement time, ratios

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1375]
A couple rotors on my ship (ones that were placed last if I remember correctly) have somehow taken the child entities of previously placed rotors (after ditching their own child entities from the existing ship and blueprint). The original rotors still show the weight of their original children, but no longer have control over them. If I delete the newer rotors, they delete their stolen entities. If I move the rotors, they snap the stolen entities into different positions depending on angle of the new parent rotor (since the rotor is overloaded, it can't move them normally). The movement time of the new parent is "infinite", and the ratio is 258%.

### Steps to reproduce the issue:
1. Load in my blueprint
2. Go to the rear of the ship and locate the middle turret structure on the outside
3. Remove one of the plates on the turret head to access the small bugged rotor
4. Delete the rotor and see the ship's upper left engine disappear
5. Activate the small rotor to delete the upper left engine and snap the lower left engine out of place

- Skywanderers version: 19w29a
- Graphics Card: Nvidia GeForce GTX

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3408774/output_log.txt)

**BP and pics sent via email (contest ship again 😕)**

**Comment by tsunamayo** [comment]
Yes I saw that on the pb you sent me yesterday... I fixed that issue already yesterday when I saw it, but I would like to know if you can manage to build a stealing rotor in current version (this I am not sure).
I did some refactoring a long time ago on children entity indexing, as there was bug (similar to yours). 
How old are you ship?
Cheers

**Comment by Majikmonster** [comment]
I will attempt to reproduce the bug.
I began building the ship in version 19w24a.

**Comment by tsunamayo** [comment]
You remember anything special when building those rotor? Did you add / delete them often? Thanks

**Comment by Majikmonster** [comment]
There were (and are) instances where some of the rotors fail to stop at the exact angle set by a sequencer. However, that issue isn't exclusive to the bugged rotors. I did not frequently add or delete them, as far as I remember. There was nothing outstanding about them, until this update.

**Comment by tsunamayo** [comment]
This issue should be fixed for a while now. Did you encounter that recently? Thanks
