### ISSUE TITLE
[Suggestion] Indicate direction of rail and hinge ghost placement

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1378]
### Short Description of the issue:
Right now, you can't see what direction rails and hinges are facing, so placing them the way you want is like trial and error.
This comes in two variants of the same problem:
For rails, even if you are placing it on the same axis, rotation indicates whenever the starting position is at the start, or at the end of the of the draging. This is better exemplied in the new brick rail, that due to how cubic it is, is really hard to see even in which axis you are building, until you try to stretch it.
For Hinges, even if the axis is the same, rotation indicates in what direction de 0º position is.
### Additional information:
Two rails placed on the same plane, both builded top to bottom (Starting where the ghost image is), but facing opposite directions.
![imagen](https://user-images.githubusercontent.com/559819/61544300-74c45500-aa45-11e9-9d68-9f031d35c610.png)
Two hinges placed on the same plane, at the 0,0 degree angle, placed on opposite directions.
![imagen](https://user-images.githubusercontent.com/559819/61544332-8148ad80-aa45-11e9-89e6-2f2dc478138d.png)

**Comment by tsunamayo** [comment]
Yes I 100% agree with that it was on my to do list. Thanks!

**Comment by AfterRebelion** [comment]
Indicator now avaliable in 20w09a :D
![imagen](https://user-images.githubusercontent.com/559819/75260980-b6db2380-57ea-11ea-851b-f58affd8496b.png)
