### ISSUE TITLE
early game crash

### ISSUE THREAD

**Issue by MrMantheMagicMann** [tsunamayo/Skywanderers#138]
Alright, so when I try to start a new game, the app just crashes. Seems to be linked to my video card, as that crashes almost immediately beforehand. Error logs included.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1409745/output_log.txt)

[error.log](https://github.com/tsunamayo/Skywanderers/files/1409746/error.log)

**Comment by tsunamayo** [comment]
Hi! Can I ask what are your specs, especially your GFX card? Also did you updated your GFX drivers?

**Comment by MrMantheMagicMann** [comment]
Alright, so I should probably mention that I'm using a potato laptop.
Anyway, the graphics card I"m stuck with is an Intel HD 4400. Updating it
did nothing, I'm afraid to say.

as for the rest of the system, 6g of RAM and 500g of storage should be more
than enough

Godspeed
  -Alex

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Yes it is clearly coming from the GFX card. no pb with RAM or storage!

Thanks

**Comment by MrMantheMagicMann** [comment]
Hey Francois! I have good news! The save files for Empty and Asteroids work
wonderfully, holy crap. Unfortunately, Torus crashes every time I try to
approach the ring's surface. Now, I get farther with every attempt, and I'm
gonna keep throwing myself at it until I get there. I'll send you a crash
report once it's done crashing.

Good Luck!

**Comment by CyaNox** [comment]
In #317 I found that there is a dependency lacking for the MSVC Runtime 2015 as per: https://github.com/tsunamayo/Skywanderers/issues/317#issuecomment-344861361

You can try downloading and installing it from https://www.microsoft.com/en-gb/download/details.aspx?id=48145 and see if that helps.
