### ISSUE TITLE
[19w29a 7/19 HOTFIX]  New Hinge Bricks Offset  

### ISSUE THREAD

**Issue by DarthPeter0** [tsunamayo/Skywanderers#1380]
### Short Description of the issue:
It seems like the new hinges, placed before the hotfix or loaded in, are broken.  New hinges placed by the player function properly, but hinges placed before this hotfix or ones spawned in on blueprints have an offset between the parent-entity piece and the child-entity piece.  This offsets the entire child entity, which often clips the child entity into the rest of the construct.  The resulting clipping causes the hinge to no longer work at all, due to the clipping between the child and parent entities. 
I think this is unique to the new hotfix, as my hinges were working fine last night.
...

### Steps to reproduce the issue:
Step 1:  Find a ship in your world with the new brick hinges that was built before the hotfix.  Examine the hinge to see that it has offset its child entity.

Step 2:  Load in a ship blueprint which was created before the hotfix.  Repeat Step 1.
...

### Environment
- Skywanderers version: 19w29a 7/19/19 hotfix
- Graphics Card: GTX 1060

### Additional information:

Here are some examples of the clipping with my landing gear:
![20190719113855_1](https://user-images.githubusercontent.com/33942288/61557751-ee464e00-aa19-11e9-8572-f16ac1c9b180.jpg)
![20190719113903_1](https://user-images.githubusercontent.com/33942288/61557752-ee464e00-aa19-11e9-8d09-19b24335b840.jpg)
![20190719113910_1](https://user-images.githubusercontent.com/33942288/61557753-ee464e00-aa19-11e9-9ef6-8f2de56b2f32.jpg)
![20190719113919_1](https://user-images.githubusercontent.com/33942288/61557754-ee464e00-aa19-11e9-92bf-0725c132f3bb.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3412297/output_log.txt)

**Comment by Majikmonster** [comment]
Same here
![20190719144051_1](https://user-images.githubusercontent.com/51390907/61559793-83f0d600-aa38-11e9-9922-0f57348d240e.jpg)
![20190719144055_1](https://user-images.githubusercontent.com/51390907/61559794-83f0d600-aa38-11e9-8afb-16b45c841b28.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3412425/output_log.txt)

**Comment by tsunamayo** [comment]
Yes guy really sorry, I had to make a fix for #1373 that messed up with that - I forgot to put in the bugfix description... I hope it wont be too much of a hassle to rebuild... Cheers
