### ISSUE TITLE
[19w29b] Rails will not extend in a specific direction

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1381]
When trying to place the rail on the new brick hinge... the rail will not stretch in some directions. 

...

![20190719224035_1](https://user-images.githubusercontent.com/45324484/61574092-66932a80-aa7f-11e9-9d2e-488246ea24e3.jpg)

![20190719224036_1](https://user-images.githubusercontent.com/45324484/61574094-672bc100-aa7f-11e9-831f-91f5a94514e6.jpg)

In the image below I was trying to stretch the brick rail upward
![20190719224040_1](https://user-images.githubusercontent.com/45324484/61574096-685cee00-aa7f-11e9-93fe-53274e30395e.jpg)

- Skywanderers version: 19w29b
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
I cant really reproduce this, could you send me your bp? Thanks

**Comment by ExodistSKY1** [comment]
Will send it Via Email within the next two minutes.

**Comment by tsunamayo** [comment]
I still cant really reproduce the issue... Are you doing something specific I might be missing? Thanks

**Comment by tsunamayo** [comment]
incredible ship btw.

**Comment by ExodistSKY1** [comment]
I did a complete reinstall of the game and wiped everything but blueprints and I can no longer reproduce the issue. I take it that's a good thing! 

Thank you!
