### ISSUE TITLE
Despawn problems after update

### ISSUE THREAD

**Issue by Mantis2k19** [tsunamayo/Skywanderers#1382]
### Short Description of the issue:
Unable to despawn vehicles using drone. Drone menu shows the vehicle as disappearing, but the vehicle remains and can be built on. Despawning (saving world and restarting program is a found workaround)
...

### Steps to reproduce the issue:
Despawn a vehicle with the drone?
...

### Environment
- Skywanderers version: cannot find this in Steam menu
- Graphics Card: Nvidia GeForce GTX 650
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3413257/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay issue is fixed (for 19w30a), thanks for your help! Cheers
