### ISSUE TITLE
Slider Disappears When Connected as Input to Query Gate [19w29B]

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1383]
### Short Description of the issue:
When attempting to connect a new slider as an input to the query gate, the slider will disappear. I have been able to reproduce this consistently on this build. 

Update: this also occurs when using a hinge as the input: its base also gets deleted.

Also, once this occurs you can no longer place or delete blocks or bricks.

I use this method frequently to better time events for ramps and landing gear.

### Steps to reproduce the issue:
- Place a slider block (in my case 2M length)
- Place a query gate logic brick
- Using the logic connection tool, drag from the slider block to the query gate to connect as input
- The base of the slider disappears entirely

### Environment
- Skywanderers version: 19w29B
- Graphics Card: GeForce GTX960

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
BEFORE:
![image](https://user-images.githubusercontent.com/33043997/61578176-e2fa2d80-aac0-11e9-895c-48a71a1088e5.png)
AFTER:
![image](https://user-images.githubusercontent.com/33043997/61578188-fefdcf00-aac0-11e9-8ec3-991c594b01c6.png)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3413538/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I fixed this one, will be in 19w30a. Cheers!
