### ISSUE TITLE
[19w29b] Sequencer cannot be linked to lights

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1384]
### Short Description of the issue:
The sequencer brick cannot link to lights.

### Steps to reproduce the issue:
Place a light and a sequencer, then try to link the sequencer to the light.

### Environment
- Skywanderers version: 19w29b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3413863/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this one is fixed, will be in 19w30a. Thanks!
