### ISSUE TITLE
[19w29b] Deleting a light can blind player

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1385]
### Short Description of the issue:
After placing a light, connecting it to a slider control, and playing around with the slider, I then deleted the light, which cause the screen to turn bright yellow.

### Steps to reproduce the issue:
I've included the output.log from the session this occurred on, and hopefully the cause can be seen in that, but I haven't been able to reproduce it yet in a new session. Just placing and deleting a light doesn't do it, nor does deleting a light after it's been connected to a slider control. I'll post again if I figure out precisely what causes it.

### Environment
- Skywanderers version: 19w29b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190720123648_1](https://user-images.githubusercontent.com/33041786/61582085-e060fd80-aaeb-11e9-95bc-dceac4266cf6.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3413866/output_log.txt)

**Comment by tsunamayo** [comment]
Not sure exactly how it was triggered indeed, but I added a safe guard so it cant mess up this way again. Will be in 19w30a. Thanks!
