### ISSUE TITLE
[19w29b] Power generation is "-1.525879E-05" o.O

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1386]
### Short Description of the issue:
I seem to have broken math, because the energy generation of this ship makes no sense.

### Steps to reproduce the issue:
See attached blueprint, because I have no clue at all how to duplicate this. It happens when the reactor and all three engines are off.

### Environment
- Skywanderers version: 19w29b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190720221501_1](https://user-images.githubusercontent.com/33041786/61586524-2940a280-ab3c-11e9-8ef7-9c90ad50e8f1.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3414225/output_log.txt)

[AAM Mako Interceptor Mk. II.zip](https://github.com/tsunamayo/Skywanderers/files/3414226/AAM.Mako.Interceptor.Mk.II.zip)

**Comment by tsunamayo** [comment]
Actually I am working on energy balance for the next update, this issue was fixed already. Cheers
