### ISSUE TITLE
Infinite loading screen.

### ISSUE THREAD

**Issue by Gambit06** [tsunamayo/Skywanderers#1387]
### Short Description of the issue: 
When launching a game (new or saved) the loading is infinite.
Quite and restarted, uninstall and reinstall the game does not change anything.

Cordialemant: ComradGambit

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3414709/output_log.txt)

**Comment by Gambit06** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3414707/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear this.
Could you please send me your full save data folder so I can reproduce? Thanks!

**Comment by Gambit06** [comment]
Sorry to not have respond. the bug was corrected by suppression of player data. Thx Propeach.

**Comment by tsunamayo** [comment]
Did you keep a backup of your player data? If there are some issue I need to fix them, suppressing the player data is not an acceptable solution... Cheers
