### ISSUE TITLE
[19w29b] "Align to" command does not precisely align

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1389]
### Short Description of the issue:
When the player tries to align themselves to an entity in the game, the alignment is slightly off.

### Steps to reproduce the issue:
Align the player to an object, then fly the player over a flat area on the object, and press the down movement key. The play character will slowly start sliding over the flat area to one side, because there is a slight misalignment when using the align command.

### Environment
- Skywanderers version: 19w29b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3423931/output_log.txt)

**Comment by tsunamayo** [comment]
Good spot, issue is fixed for 19w30a. Cheers
