### ISSUE TITLE
Block seams are not connecting

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1395]
### Short Description of the issue:
It _seems_ that the block borders aren't connecting anymore. In the last two pictures it almost looks as if the tech for connecting borders is just offset in some places. Some spots do have connected borders but the majority looks like it isn't connecting at all
...

### Steps to reproduce the issue:
Update and load up
...

### Environment
- Skywanderers version: 19w31a
- Graphics Card: GTX 970

### Additional information:
![20190729161848_1](https://user-images.githubusercontent.com/32974671/62083507-b6f74e80-b21c-11e9-94a1-df0d3450a733.jpg)
![20190729161837_1](https://user-images.githubusercontent.com/32974671/62083508-b78fe500-b21c-11e9-823b-ab24642dd2f7.jpg)
![20190729162146_1](https://user-images.githubusercontent.com/32974671/62083622-ff167100-b21c-11e9-9eb5-ea2ccaa08aae.jpg)
![20190729162145_1](https://user-images.githubusercontent.com/32974671/62083623-ff167100-b21c-11e9-9f2b-dc32d78e95d5.jpg)

**Comment by Xerma** [comment]
Honestly though this could make a decent texture for another hull for people that like the large paneled look
![20190729162504_1](https://user-images.githubusercontent.com/32974671/62083869-89f76b80-b21d-11e9-969b-7829682b9a88.jpg)

**Comment by Majikmonster** [comment]
I'm getting this, too, but only on some parts that were placed separately. I thought it might be like with bricks, where everything placed separately has a seam between them, but it's really inconsistent with the blocks 🤔

**Comment by tsunamayo** [comment]
Hum I dont have any issue on my side, but yes I made some change on the way border are computed to make faster and smoother loading. Could you guys send me some blueprint so I can have a look? (@Xerma if you have something smaller in store haha ^^) Cheers

**Comment by Xerma** [comment]
Yep, here's a smaller build and some screenshots
![20190801152527_1](https://user-images.githubusercontent.com/32974671/62325226-d4bcf180-b470-11e9-999d-ff0d1e5065f4.jpg)
![20190801152537_1](https://user-images.githubusercontent.com/32974671/62325235-d71f4b80-b470-11e9-9395-5fbfa453b78b.jpg)
![20190801152547_1](https://user-images.githubusercontent.com/32974671/62325237-d8e90f00-b470-11e9-9b82-e5842b6d5d42.jpg)
![20190801152602_1](https://user-images.githubusercontent.com/32974671/62325242-dab2d280-b470-11e9-91de-7d520fb0b103.jpg)

[Curvy ship.zip](https://github.com/tsunamayo/Skywanderers/files/3458538/Curvy.ship.zip)

**Comment by tsunamayo** [comment]
Thanks I am gonna have a look at it.

**Comment by tsunamayo** [comment]
Okay great I was finally able to track down the issue and fix it. Fix will be in 19w31b. Thanks!
