### ISSUE TITLE
[19w30a] creating a logic loop crashes game to desktop

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1396]
### Short Description of the issue:
Linking a logic gate/switch/button to a timer, back to a gate/switch/button, causes lag spikes and a crash seconds later.

### Environment
- Skywanderers version: 19w30a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3444520/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed! Issue is fixed, and will be available in 19w31b. Thanks!
