### ISSUE TITLE
[Low] When moving window in Window mode, it disapears off screen.

### ISSUE THREAD

**Issue by Conniverd** [tsunamayo/Skywanderers#14]
**Description of issue:**
If you try to move the Skywanderers window in window mode (after loading or starting a game), 
It will jump down, and to the edge of the screen, You cannot drag it back, as it keeps pulling down.

**Frequency of issue:**
Every time. (I think)

**Steps to replicate issue:**
Start game, new or load. Move window.

**Possible Workaround:**
Exit, and restart, move window when in menu.

**Comment by AfterRebelion** [comment]
This issue seems to be no longer valid in recent versions (19w23b)
