### ISSUE TITLE
In-game graphics, full screen bug

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#140]
Pre-game menu, select windowed option
Once in game, select graphics, then full screen - cursor is visible, but it's a blank screen & there is no obvious solution to get to a menu or rectify situation.

**Comment by tsunamayo** [comment]
Thanks for the clear test case - issue can be reproduced easily. I will have to force a game restart to solve it.
Cheers

**Comment by tsunamayo** [comment]
Okay I finally fixed this issue. Fix will be in 17w45a. Thanks!
