### ISSUE TITLE
Rotator/Hinge/Slider Odd behavior

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1401]
### Short Description of the issue:
If you link a rotator, hinge, or a slider to anything while it is moving/running it's animation, it immediately cancels the animation and sets the object to 1, or 0 depending which direction it's going and ignores all collisions.
...

### Environment
- Skywanderers version: 19w31a
- Graphics Card: GTX 970

### Additional information:
![20190801185038_1](https://user-images.githubusercontent.com/32974671/62334435-47d46100-b48d-11e9-8ac4-3ab6e2fbcc15.jpg)

**Comment by tsunamayo** [comment]
Okay very nice spotting, issue is fixed for 19w31b. Thanks!
