### ISSUE TITLE
[19w31a] Hotkey brick Press function not saving

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1402]
### Short Description of the issue:
The hotkey brick only functions as a Switch; trying to change it to Press function does not save the change.

### Steps to reproduce the issue:
Set a hotkey up, then interact with it to change its function to Press, then exit the menu and interact with it again. It will have changed back to Switch function.

### Environment
- Skywanderers version: 19w31a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190801213723_1](https://user-images.githubusercontent.com/33041786/62400979-dbb63380-b546-11e9-878d-9c56e9150aac.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3463013/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, fix will be available in 19w32b. Cheers!
