### ISSUE TITLE
Player character reaches for button each time its state updates

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1403]
### Short Description of the issue:
Whenever a button is activated, the player model will reach out for the button on first activation then relax the arm (expected). It will reach out again when the button is released and its state is updated back to 0 (like it would do with a manual toggle such as the switch).

### Steps to reproduce the issue:
1. Place and link button to anything.
2. Enter third person view
3. Press the button by tapping and/or holding F

### Environment
- Skywanderers version: 19w31a
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/3463155/output_log.zip)
(raw output log larger than max file size for github 😕 )

**Comment by tsunamayo** [comment]
Okay I fixed this issue for 19w32b. Thanks!
