### ISSUE TITLE
[19w31a] Requesting landing on station pad results in broken ship behavior

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1404]
### Short Description of the issue:

- After flying to a station and requesting docking, flying the ship into position for the pad to grab it forces hyperspeed to activate, and drops out in the same moment.
- The pad is then stuck thinking the request hasn't been fulfilled.
- Moving the ship manually afterwards results in loss of thrust and steering control. The mouse no longer works to change direction despite being able to move it.
- The ship also becomes stuck flying at a constant  speed (one ship flew at 35m/s, the other at 15m/s) and will not stop even if the player exits control, the yoke is broken, the engines are deleted, and the reactors are removed.
- The only way to stop the ship is to unspawn it with the drone, leaving the landing pad locked out.

### Steps to reproduce the issue:

1. Fly ship to pad and request docking.
2. Fly ship above pad to land.
3. Move ship around when it fails.
4. Break the ship's systems when it becomes stuck flying away.

### Environment
- Skywanderers version: 19w31a

### Additional information:
-First ship flying away on its own
![20190802044933_1](https://user-images.githubusercontent.com/51390907/62404181-59d30400-b560-11e9-88c1-49d6e2edddeb.jpg)
-Pad locked now that the ship was unspawned without landing
![20190802045744_1](https://user-images.githubusercontent.com/51390907/62404214-90a91a00-b560-11e9-8ccb-d789effb1dda.jpg)
-Larger pad requested. The ship automatically activated hyperspeed. I was not pressing any keys at the time.
![20190802045821_1](https://user-images.githubusercontent.com/51390907/62404218-943ca100-b560-11e9-98d9-933445f99dc4.jpg)
-The ship drops out of hyperspeed in the same spot it activated it. It never moved at all.
![20190802045825_1](https://user-images.githubusercontent.com/51390907/62404219-956dce00-b560-11e9-9208-e24e1493631f.jpg)
-I flew the ship trying to position it above the pad. It has become stuck flying forward at 15m/s and I can no longer control it.
![20190802045852_1](https://user-images.githubusercontent.com/51390907/62404224-9bfc4580-b560-11e9-9cb9-f5af9f2ced9b.jpg)
-Here I have exited the yoke, and you can see it is still travelling at 15m/s.
![20190802045911_1](https://user-images.githubusercontent.com/51390907/62404230-a3235380-b560-11e9-977f-675d54943159.jpg)
-I've gotten out of the ship entirely, and it's still flying on its own.
![20190802050125_1](https://user-images.githubusercontent.com/51390907/62404243-bafad780-b560-11e9-8479-f92cb130c4c6.jpg)
-I delete all of its systems, and it is still moving steady at 15m/s.
![20190802050407_1](https://user-images.githubusercontent.com/51390907/62404252-c948f380-b560-11e9-866f-9de4630c31f5.jpg)
-I activate the drone (which is now very far away from the ship because the ship has flown off) to see that the ship should not be operational, but despite that is still flying away.
![20190802050458_1](https://user-images.githubusercontent.com/51390907/62404276-d9f96980-b560-11e9-8a21-6d594cb89d6c.jpg)
I unspawn the ship, and now both pads at the station are locked.

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/3463169/output_log.zip)
(raw output log larger than max file size for github 😕 )

**Comment by tsunamayo** [comment]
Okay I slept on that one, but it would be fixed in upcoming 19w38a. Thanks!
