### ISSUE TITLE
[19w31b] Normal map stickers incorrect, other stickers mismatched

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1407]
As you can see, when you place the Triangular crease sticker it takes up a whole block space as well as being locked to a bright white colour
...
On second look, it's both 3D stickers(this and the bolt) that produce this problem.
### Steps to reproduce the issue:
Place a Triangular Crease sticker
...

### Environment
- Skywanderers version: 19w31b
- Graphics Card: GTX 1050M
![image](https://user-images.githubusercontent.com/27857711/62423779-fe6a5880-b6bc-11e9-8fe0-2284bd4307b5.png)

**Comment by Rizzo911** [comment]
This appears to be an issue with all stickers. Also, when placing a sticker, I get the place icon for the triange when in fact I have a line and all of my line stickers have been replaced by the triangle. I think there may be a mismatch between the alpha channel, collision shape and possibly the objects... like they aren't in proper order.

![image](https://user-images.githubusercontent.com/33043997/62423793-76bc2400-b693-11e9-8d7d-ca32d7b86a62.png)

**Comment by Rizzo911** [comment]
This is the hash sticker selected, but is placing the L sticker:

![image](https://user-images.githubusercontent.com/33043997/62423798-9b180080-b693-11e9-9070-5e7fcadca1ba.png)

**Comment by Dwarf-LordPangolin** [comment]
The same issue is affecting the small arrow sticker; it turns into a thin line sticker.

![20190804141913_1](https://user-images.githubusercontent.com/33041786/62428077-ea295a00-b6c2-11e9-85e8-4da60e0de0d7.jpg)

**Comment by tsunamayo** [comment]
Issue is fixed for 19w32a. Thanks a lot!
