### ISSUE TITLE
Snapping issue with sail Blocks

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#141]
I'm currently trying to use sail blocks on one of my builds but I'm having an alignment issue.  I have built a wing frame from tile long thin stand blocks, when trying to attach sail blocks to the snap points on the wing frame the Sail tile wont snap to the mount points but rather it snaps to the bottom edge of the wing frame block. the sail slab wedge, sail wedge and sail slab all snap properly. link to picture to show you what I mean. 

https://steamuserimages-a.akamaihd.net/ugc/865115034094754795/8373E9540EF890D5DF38E2DFC6DE2DAE3BB30C3D/

**Comment by tsunamayo** [comment]
Hello! So the full sail is actually a voxel block, it means that it have to comply to a grid. The smaller one are actually bricks, so they can be positioned more freely as soon as you have studs to built on.

The full sails has studs on its side so you can put the smaller one on top, I advice to simple build first with the full sail, then put the smaller one on a second time.
