### ISSUE TITLE
Paint and the block grid

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1411]
Since we can place two wedges together in the same space to form a block would it be possible to make it so it only paints one of those wedges at a time instead of painting the whole block within the grid? This would allow for some fancy painting for floors and walls or whatever details people want to do
![20190811173519_1](https://user-images.githubusercontent.com/32974671/62840384-70afdf80-bc5f-11e9-9c67-b32a80119fba.jpg)

**Comment by Majikmonster** [comment]
I've been working around this by having one half be stretched small wedge, but it would be nice to not have to do that.

**Comment by tsunamayo** [comment]
Actually dont cont too much on it:
 - first the hull block are using voxel paint, not shape paint like brick. If you dont like voxel paint it is another issue (voxel paint is much more complicated to deal with - so we could talk)
 - then I am working on the collision refactor, and I will likely have to restrict it back at one hull per voxel to make the thing run faster.

But it should be okay, as you can simply put a full block, and then use a stencil to do the job. Dont spend too much time on stencil, I will likely nuke them while doing a refactor (I am sick of refactor haha), that would make them stretchable (and simplier to deal in code also)

**Comment by Xerma** [comment]
Honestly yea, stretchy stencils should solve the issue entirely and the more stencils the better, in theory anyways lol. I haven't messed with stencils much at all because I know they'll get refactored at some point so I kinda forgot about them.

Would it be possible however when you break a painted block to remove the paint from the grid too? Or perhaps even have that as a setting somewhere. This isn't very necessary either honestly

**Comment by tsunamayo** [comment]
I remember somebody posted a suggestion where he wanted to have paint stayed in place when removing the block, to not have to repaint everything when deleting a large block to make a windows for example...
But I agree it is not too clean...

**Comment by tsunamayo** [comment]
Okay the paint / decal refactor is around the corner - you will have rescalable decals for your custom paint job. But I had to remove custom paint (sorry), I will explain all that soon once I push the build... Cheers
