### ISSUE TITLE
"Grating A" placement

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1413]
Could you change where we need to point to in order to place the armature panel/grating A? The easiest workaround would probably just make the placement/pivot point on one of the pegs. It would also be amazing if the drag limit for this could get changed to 16 to match with the armature block. Plus it might be good to rename it and give it a new description
![20190812175141_1](https://user-images.githubusercontent.com/32974671/62904048-6d355a80-bd2a-11e9-834f-e532217acc63.jpg)

**Comment by tsunamayo** [comment]
I agree, I keep you posted. Cheers

**Comment by tsunamayo** [comment]
Okay I made the changes - thanks for reporting that! But unfortunately I had to update the model to make it clean, which means you will have to destroy and rebuild them at the correct position... (They will have an offset when loading old save file...). Thanks a lot!
