### ISSUE TITLE
[Suggestion] Glow paint

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1417]
Just a small suggestion, for custom paints there should be a glow value you may want to set (maybe even a paint transparency if you want some of the metal sheen, but that’s a different topc), so that the paint can glow and be applied to any applicable blocks.

The glow paint wouldn’t make light to save on performance which is why you removed the OG glowblock, and could be applied to any standard freeform like all paints, meaning you wouldn’t need to add more glow blocks when add them back

**Comment by tsunamayo** [comment]
Hi, so unfortunately it wont be added as I am removing custom paint sadly (in next update). Replace with a lot more color and metal coating. It was too complicated to integrate neatly. Cheers
