### ISSUE TITLE
[BUG] Stickers Do Not Mirror Correctly

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1420]
Stickers don't rotate correctly when mirrored.

Build: 19x38a

![20190918074838_1](https://user-images.githubusercontent.com/26584892/65153231-053ff700-d9ef-11e9-8bf3-4a59535d2db1.jpg)
![20190918074911_1](https://user-images.githubusercontent.com/26584892/65153233-05d88d80-d9ef-11e9-84c0-f117356dc268.jpg)

**Comment by tsunamayo** [comment]
Okay it will be fixed in 19w38b! Thanks
