### ISSUE TITLE
[BUG] Can't Change Entity Name

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1421]
We can't edit the name of the entity. We can click on the edit button, but can't actually select the text to change it.

Build: 19w38a

![20190918082857_1](https://user-images.githubusercontent.com/26584892/65153366-3d473a00-d9ef-11e9-9eab-78aae0ab287e.jpg)

**Comment by tsunamayo** [comment]
Okay issue is now fixed. Will be in 19w38b soon. Thanks!

**Comment by Senakysam** [comment]
Sweet! Once it's live, I'll send you this new fighter with the new paints and stickers. I'm loving the metallic colors!
