### ISSUE TITLE
[BUG] Stickers Can't Be Placed On Double-Angled Slopes

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1422]
We can place stickers on wedges just fine, but can't place them on the tetras or heptas.

Build: 19w38a

![20190918075153_1](https://user-images.githubusercontent.com/26584892/65153483-74b5e680-d9ef-11e9-9ea7-5d23840df6d4.jpg)

**Comment by tsunamayo** [comment]
Okay this issue will be fixed in 19w38b. Thanks!
