### ISSUE TITLE
[BUG] Hollow Wedge bug

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1427]
When you begin place the hollow wedge (best brick), it instantly stretches one brick lower making it impossible to place
https://cdn.discordapp.com/attachments/406664114249793536/624175569365499904/unknown.png
It also seems that the hollow wedge is one of the last bricks to not have the improved textures along with three round tiles and can't be painted

**Comment by ZachZent** [comment]
Also the fence can't be painted

**Comment by tsunamayo** [comment]
I fixed the fence one, for the hollow wedge I am not sure what to do with this brick, it is problematic in too many ways - easiest solution would be to get rid of it... Thanks

**Comment by ZachZent** [comment]
That's a shame. That was as close as we got to this Lego brick.  One of the best ones
https://img.bricklink.com/ItemImage/PN/7/61409.png

**Comment by tsunamayo** [comment]
Yes LEGO was the inspiration when I designed that brick (it was a different one though, but close enough)! Not sure yet what I will do yet, I am just running out of time to lose a day on a small detail like this... Thanks

**Comment by tsunamayo** [comment]
Okay that issue is now fixed in current version! Thanks
