### ISSUE TITLE
Clicking with sticker in hand deletes blocks/bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1428]
### Short Description of the issue:
It used to be clicking while holding stickers only removed stickers but now it seems we can accidentally break blocks as well
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Yes you are right, I should add the same behaviour as before. It is because now stickers are just bricks with a specific shader... Crazy now blocks are also bricks, I only have bricks to manage ;) Cheers

**Comment by tsunamayo** [comment]
Okay issue is fixed for 19w38b. Thanks!
