### ISSUE TITLE
[BUG] On Reload, Rail Extender Changes Direction Rendering It Inoperable

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1430]
I'm using a rail extender on my cockpit, and whenever I reloading the world or loading in the ship, the rail extender will be rotated the opposite direction and not act as an extender. 

Build: 19x38a

![20190919193719_1](https://user-images.githubusercontent.com/26584892/65290530-42060e00-db15-11e9-80cf-83945ec43cba.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3633685/output_log.txt)
[Fighter11_WIP03.zip](https://github.com/tsunamayo/Skywanderers/files/3633689/Fighter11_WIP03.zip)

**Comment by tsunamayo** [comment]
Thanks for reporting this, issue will be fixed in 19w38b. Nice ship ;) 
Cheers
