### ISSUE TITLE
[BUG] Turrets locked to one plane of movement

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1431]
### Short Description of the issue:
**EDIT** This only happens when both axis are locked to the same horizontal/vertical setting. Sorry! I didn't realise you could press F on the rotors to change this :D
Feel free to close this issue as it was a misunderstanding on my part.

No matter how you move your mouse, turret axis are locked to one (usually diagonal) plane of movement. Here I am moving my mouse horizontally from side to side, and then vertically up and down while the turret behaves in the same way for both instances.
![Skywanderers Turret Axis Bug](https://user-images.githubusercontent.com/27857711/65317193-41ac5800-db93-11e9-856a-8a25b755e7b7.gif)
Interestingly, this only occurs when both the horizontal and vertical rotors are linked up. If only the base (horizontal) rotor is linked, it behaves as you'd expect.

### Steps to reproduce the issue:
Construct a turret using the turret core, yoke and a camera
Move your mouse in a few different directions and note the turrets actual movement.

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 1050M

### Additional information:
As a side note, it seems that a turret won't work unless the yoke that is linked to a turret core is also linked to a camera. I would treat this as a bug as there are instances where I don't want to have to look through a camera in order to control a turret. (This Millennium Falcon style moving seats for the turret)

**Comment by tsunamayo** [comment]
Yes, it is still a bit wip, I wanted to talk about in a youtube video to explain. As I will have to add more setting in the rotor, I figured that putting that setting in the rotor itself not the turret was the way to go. Cheers!
