### ISSUE TITLE
[BUG] Gimbal on brick sized weapons are non-functional

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1432]
### Short Description of the issue:
In the latest devlog we see that the laser brick follows your mouse when firing with a gimbal. This behaviour is not present in the version we have available to us. I realise this might not be a bug and you just haven't implemented it into the public version yet, but I thought I'd just check.

### Steps to reproduce the issue:
Enter a yoke with laser bricks attached and fire, the projectile will always fire straight ahead rather than follow the mouse reticle as shown in the latest devlog.

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 1050M

I really like the new visual and sound effects though! Makes me exited to start modding the fire rate etc with barrels/capacitors. The faster projectile speed is also a very nice touch.

**Comment by tsunamayo** [comment]
Yes I am working on it, I just need to make it work with AI and over the network. To do it proper I would need some big command / player refactoring - so it would have to wait a bit. Thanks!

**Comment by tsunamayo** [comment]
So the plan is to make a gimbal barrel addon. But first I want to make sure it would work for mp. Cheers
