### ISSUE TITLE
Window Wedge's default color is blue

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1433]
### Short Description of the issue:
Pretty straightforward, the base color for Window Wedge is blue
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920220604_1](https://user-images.githubusercontent.com/32974671/65367179-4acd1180-dbf3-11e9-90dd-27ced865ad45.jpg)

**Comment by Xerma** [comment]
This actually seems to be the case for anything colorful in the codex

![20190920223104_1](https://user-images.githubusercontent.com/32974671/65367389-638af680-dbf6-11e9-9c62-0d1bc6b9e3b1.jpg)

**Comment by tsunamayo** [comment]
Yes I agree for that particular block it looked weird. I fixed it and put it at steel. I kept the canopy at blue though. Thanks!
