### ISSUE TITLE
Holding a light displays light around you

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1434]
### Short Description of the issue:
This isn't necessarily a bad thing per se but it just doesn't feel right
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920221254_1](https://user-images.githubusercontent.com/32974671/65367240-01c98d00-dbf4-11e9-84a1-acd53068c4f3.jpg)
![20190920221302_1](https://user-images.githubusercontent.com/32974671/65367241-03935080-dbf4-11e9-914d-3c2fcbe3e341.jpg)

**Comment by ProPeach** [comment]
Honestly this would make a cool feature for some handheld lights

**Comment by tsunamayo** [comment]
Yes haha I never fixed that one...

**Comment by tsunamayo** [comment]
Okay issue will be fixed in 19w40a. Thanks!
