### ISSUE TITLE
[Suggestion] Add a slight black outline to the ruler text

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1435]
### Short Description of the issue:
Sometimes it can be hard or near impossible to see the text displayed by the ruler. Adding a little black or dark grey outline around it should easily fix that
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920222006_1](https://user-images.githubusercontent.com/32974671/65367320-0a6e9300-dbf5-11e9-9e7b-564d1923a8bb.jpg)

**Comment by ProPeach** [comment]
This could definitely help, it's a little hard to see especially in bright lighting conditions like when you have the torch on.

**Comment by tsunamayo** [comment]
Okay I change the tech behind to allow the outline, it will be more visible in 19w40a. Thanks!
