### ISSUE TITLE
Bars in Armature are messed up

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1436]
### Short Description of the issue:
Not sure what's going on here but the little supporting arms are all sorts of messed up
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920223326_1](https://user-images.githubusercontent.com/32974671/65367410-c8dee780-dbf6-11e9-9230-50e381f51714.jpg)

**Comment by tsunamayo** [comment]
Yes indeed, I messed up while working on the other rail block. It is now fixed, for 19w40a. Thanks!
