### ISSUE TITLE
Pressing ESC for the first time does nothing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1437]
### Short Description of the issue:
Each time you load into the game hitting escape once does nothing; you have to hit escape a second time to bring up the menu. The same thing happens when you try to open the paint menu while paint is selected in the hotbar.
...

### Steps to reproduce the issue:
Load up, hit escape, nothing happens, hit escape again, menu appears as normal.

(I rebound my paint menu key to shift)
Select paint in hotbar, hit shift, nothing happens, hit shift again, paint menu appears as normal
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3638277/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, issue will be fixed in 19w40a. Thanks!
