### ISSUE TITLE
Odd bounce light on first placement

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1439]
### Short Description of the issue:
When you place new lights they have a strange bounce light that doesn't mimic the correct default color of the light. However clicking on the light with paint to restore default color seems to fix the issue and it's also just fine when painted in general.
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920225645_1](https://user-images.githubusercontent.com/32974671/65367648-36d8de00-dbfa-11e9-892f-eeab11ce1534.jpg)
![20190920225707_1](https://user-images.githubusercontent.com/32974671/65367650-380a0b00-dbfa-11e9-9643-76dd638ab637.jpg)

**Comment by tsunamayo** [comment]
Hum I dont manage to reproduce this issue. Is it something you get also in the last patch (19w38b), and is it something you can reproduce? Thanks!

**Comment by Xerma** [comment]
This no longer happens in 19w38b, must have been something funky
