### ISSUE TITLE
[SHOWCASE] We Built Some Ships in 19w38a

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1441]
You mentioned in the build release notes that you were interested in the ships we made with the new system, so here we are! For me, I have the Goblin Mk2, the Lancer, and the Vampyr!

Goblin Mk2
https://www.skywa.re/blueprint/goblin-mk2

Lancer (You can open the cockpit with one of the buttons inside the starboard intake)
https://www.skywa.re/blueprint/lancer

Vampyr
https://www.skywa.re/blueprint/vampyr

The new paints are great, and I'm having a ton of fun with the new metallic options. They really make things pop!

**Comment by ZachZent** [comment]
https://www.skywa.re/blueprint/mf-01-humbolt-microfighter
https://www.skywa.re/blueprint/mf-02-mobula-microfighter

Two of my Microfighters. 5.5 and 7 meters respectively. MF-01 you have to break the canopy.

**Comment by DarthPeter0** [comment]
I have been enjoying the new paints, too!  I especially like the darker steel paint.

Wolverine Interceptor:
https://www.skywa.re/blueprint/wolverine

Honeybadger Fighter/Attack Craft:
https://www.skywa.re/blueprint/honeybadger

**Comment by tsunamayo** [comment]
Thanks to all of you! Your ship really looks cool - I have featured them (Briefly) over here ;)
https://www.youtube.com/watch?v=ix10gJ0Ivvc
A new phase is starting soon, I will have to balance system and weapons for combat and game progression, so your help will be always needed! (I will start with bigger ship though - as smaller fighter will be special case for various reason) Cheers

**Comment by ZachZent** [comment]
Glad you showed them off. What has been missing from the dev logs is a number of new builds. Something to show what people can build besides your shuttle. If we post new ships before the next dev log, could you show them off? Maybe at the end of each dev log, show just one ship and give a quick fly around. Show off what people have built

**Comment by Senakysam** [comment]
Glad you liked em! Can't wait to actually fight with them in the future.

**Comment by tsunamayo** [comment]
Yes sure I want to resume ship showcase, then we will have to start working back on faction and kickstarter reward, so lots of building in perspective for people motivated!
