### ISSUE TITLE
Light hitbox doesn't cover the whole thing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1444]
### Short Description of the issue:
When painting lights if you paint from this point to the edge you miss the light entirely and paint the block behind/below
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

### Additional information:
![20190922145104_1](https://user-images.githubusercontent.com/32974671/65393629-9f35d580-dd48-11e9-8ce6-a93dfc7fc5f6.jpg)

**Comment by tsunamayo** [comment]
Okay thanks for pointing that out - you are doing an amazing job to spot and report those sloppy things. It will be fixed in 19w40a. Cheers!
