### ISSUE TITLE
[BUG] Placing blocks on a mirror plane creates two clipped blocks

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1446]
### Short Description of the issue:
When you place a block on a mirror plane, it creates two on the same space.
...

### Steps to reproduce the issue:
Set up mirror 
Place block on where you set t
There will be 2 clipping blocks 
...

### Environment
- Skywanderers version: 19w38b(and before)
- Graphics Card: AMD raedon HD 7500 series

**Comment by tsunamayo** [comment]
Issue fixed in 20w13a. Cheers
