### ISSUE TITLE
(Moving)Child entity frame drops

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1448]
### Short Description of the issue:
I have 2 very simple "blast" doors in my ship, which didn't use to cause this issue, that will cause a drop in fps ranging from -5 to -12 or sometimes no drop at all
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

![20190923002412_1](https://user-images.githubusercontent.com/32974671/65403440-59edc400-dd99-11e9-9f97-4b5d87a70c34.jpg)
![20190923002419_1](https://user-images.githubusercontent.com/32974671/65403445-5b1ef100-dd99-11e9-900f-c737ca58401c.jpg)

**Comment by ProPeach** [comment]
I also noticed this on relatively simple mechanisms. Here's a U-Wing blueprint I've been working on, if you activate the switch inside to toggle the wings you might experience something similar.
[U-Wing ProPeach.zip](https://github.com/tsunamayo/Skywanderers/files/3644464/U-Wing.ProPeach.zip)

**Comment by tsunamayo** [comment]
Yes the collision engine is laggy... I will improve it, the bad news being some of your mecanism might be stuck if they rely on small tetris like locking mecanism... I will keep you posted.

**Comment by tsunamayo** [comment]
Okay the new system was in a previous update, it is not 100% finished in term of speed gain but at least the big bottleneck are gone, so it should be a lot better. Tell me if you still see some issues! Thanks guys!
