### ISSUE TITLE
[Suggestion] New option for paint tool

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1449]
### Short Description of the issue:
Would it be possible to get some simple additions for the paint tool such as a "line mode" or a "rectangle mode" so we could paint large lines or sections much quicker than becoming a human printer and going side to side?

**Comment by tsunamayo** [comment]
Okay so that would mean that holding LMB would no longer paint what you target, but start a stretch paint selection? Thanks

**Comment by Xerma** [comment]
Something like that might work

**Comment by tsunamayo** [comment]
Okay sorry for being late, on this I would prefer to stick to the current paint flow. If you had to press and release LMB it would be much painfull and slower for normal sized build. 
I guess it get tiring on very large build like you do, but on the other side if you go big you are willing to commit to spend a lot of time doing this. Doing the hull of a very large build is always relatively fast, but when it comes to making interior, detailing, painting, you will easily spend 10X more time, so size can be deceiving...
Cheers
