### ISSUE TITLE
Rail block doesn't mirror properly

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1450]
### Short Description of the issue:
When trying to mirror with a rail block, it appears to not mirror correctly and clips into blocks
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

![20190923143503_1](https://user-images.githubusercontent.com/32974671/65456712-8c3a0880-de0f-11e9-936d-325ae59a8896.jpg)
![20190923143517_1](https://user-images.githubusercontent.com/32974671/65456716-8e03cc00-de0f-11e9-9a79-75ae6a5aa363.jpg)

**Comment by tsunamayo** [comment]
I see, this is because of the change I made to this block, which is now assymetrical. I will have to broke it again, and change my approach... Keep you posted!

**Comment by tsunamayo** [comment]
Okay somehow I slept on that one - will fix it asap.

**Comment by tsunamayo** [comment]
Okay, it will be in 20w12b or later. But the rail will be broken again. The initial issue was a placement one, but I have solved this with the raybast collider that is now a cube, so it is easy to stack them up.
Thanks!
