### ISSUE TITLE
Breaking blocks that clip paints the surviving block

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1451]
### Short Description of the issue:
If blocks happen to clip via mirroring issues or other mishaps, it paints the remaining block copper where they intersected but if you pick the color with middle mouse it still picks steel.
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

![20190923144022_1](https://user-images.githubusercontent.com/32974671/65457202-a6c0b180-de10-11e9-93b9-f2b2b630453a.jpg)

**Comment by Xerma** [comment]
This issue also breaks the connecting borders of the blocks and separates them/removes the border entirely for the surviving block(s)
![20190923145043_1](https://user-images.githubusercontent.com/32974671/65457660-a83ea980-de11-11e9-8576-a52ce0642b39.jpg)

**Comment by Xerma** [comment]
Now that I notice it, it seems whenever you break a block, the block flickers with the same copper before disappearing

**Comment by tsunamayo** [comment]
Yes the engine expect to only have a single block per voxel, so if not the case weird stuff will happens... I will fix the mirroring issue. Thanks!

**Comment by tsunamayo** [comment]
Mirroring issue fixed, this should no longer happens. Thanks
