### ISSUE TITLE
[Suggestion] Stretchy round engines

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#1452]
### Short Description of the suggestion:

I know that we have a lot more stretchy blocks and bricks in the game, but it would be great if the current stretchy engines could get a round version of the engine, like in the old versions of the game. 

Attached below is a skillfully drawn mspaint rendition of how the stretchy might work:
![image](https://user-images.githubusercontent.com/37738021/65457083-1358a200-de4b-11e9-82d1-3e75bd57431c.png)

**Comment by ZachZent** [comment]
Yes please. I miss them a lot

**Comment by ProPeach** [comment]
Stretchy brick engines would be absolutely wonderful too, especially with the surge in fighter builds likely to come from AI dogfights

**Comment by Incapelli** [comment]
Yes please. The round engines were really good.

**Comment by Xerma** [comment]
I'm just overall curious about brick systems as a whole

**Comment by ultrak2k** [comment]
Yes. We need round engines, and perhaps a reliable way to encase them

**Comment by Creepthefrenchpastery** [comment]
indeed these would be great, also completely off topic but please get rid of brick borders tsuna im begging you

**Comment by tsunamayo** [comment]
Okay I have added round engine as of late, you can scale them up to 4m like other small brick. They are not Lightcruise capable though, but they provide lateral thrust and angular speed when placed sideway. Thanks!
