### ISSUE TITLE
Blurry screen on load

### ISSUE THREAD

**Issue by KevinTerranR** [tsunamayo/Skywanderers#1454]
### Short Description of the issue:
My screen is incredibly blurry when playing, fixed by exiting and restarting the game entirely
...

### Steps to reproduce the issue:
Load up any world once, leave to the main menu, load it up again, world becomes blurry 100% of the time on second load.
...

### Environment
- Skywanderers version: Pre-alpha 19w38b
- Graphics Card: 3071MB NVIDIA GeForce GTX 1060 3GB (MSI)

### Additional information:
Pictures of the bug, before and after the second load
https://imgur.com/a/qem4L9n

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3649641/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for noticing this, issue is now fixed. Cheers!
