### ISSUE TITLE
Sloped windows glass can't be tinted

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Skywanderers#1455]
### Short Description of the issue:

The sloped windows glass can't be tinted like regular windows.

### Steps to reproduce the issue:

Place sloped windows and use the paint tool, you won't be able to change the glass color.

### Environment
- Skywanderers version: pre-alpha 19w38b
- Graphics Card: Nvidia GTX Geforce 1060

### Additional information:

![20190926194127_1](https://user-images.githubusercontent.com/33103748/65716329-32e80880-e09f-11e9-9fd8-530750a4c187.jpg)

**Comment by tsunamayo** [comment]
Yes, it is not really a bug as is now impossible with the way the wedge is made. I want to make a new wedge brick, that would take that into account. Thanks!

**Comment by tsunamayo** [comment]
Okay this is now fixed with the new window tile wedge. But you have to hit the side to paint the frame!
Thanks!
