### ISSUE TITLE
Stickers can and can't be layered

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1456]
### Short Description of the issue:
For some reason I can't layer stickers in some rotations on top of other stickers.

After deleting the square layers I can see the triangle layers below them. Perhaps they aren't layering correctly?
...

### Steps to reproduce the issue:
1. Use square sticker
2. Add square layer
3. Add triangle on top of second square layer
4. Attempt to add triangle on the same square layer
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

### Additional information:
![20190926180716_1](https://user-images.githubusercontent.com/32974671/65730933-530ccd00-e089-11e9-9834-309c6c78756a.jpg)
![20190926180720_1](https://user-images.githubusercontent.com/32974671/65730934-543dfa00-e089-11e9-9767-395f9c235f5a.jpg)
![20190926180724_1](https://user-images.githubusercontent.com/32974671/65730935-556f2700-e089-11e9-837c-236d17fb587d.jpg)
![20190926181007_1](https://user-images.githubusercontent.com/32974671/65730936-56a05400-e089-11e9-9938-0f65064586c8.jpg)
![20190926181009_1](https://user-images.githubusercontent.com/32974671/65730941-586a1780-e089-11e9-8fc0-bcd171e7c181.jpg)
![20190926181010_1](https://user-images.githubusercontent.com/32974671/65730942-599b4480-e089-11e9-927c-03838a7cdef4.jpg)
![20190926181012_1](https://user-images.githubusercontent.com/32974671/65730944-5acc7180-e089-11e9-9644-8a402f650697.jpg)

**Comment by tsunamayo** [comment]
Yes actually we cant add two at the same position and rotation. I should be able to address that in the future. There is also one edge case when decals are on different chunk. Thanks!

**Comment by Xerma** [comment]
It actually seems like sometimes stickers start getting placed in the very back layer instead of the very front

**Comment by tsunamayo** [comment]
Okay I should have fixed the issue for 19w40a. If not could you tell me? (was fine for my test case). Issue on chunk is not fixed though, but it should happens a lot more rarely. Thanks!
