### ISSUE TITLE
Rail extenders have starter block texture when activated

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1458]
### Short Description of the issue:
I can't accurately say why or when this happens, it just does. Especially when the starting rail is 16m and you have 2 extensions that are also 16m each. It happens with less too but again I can't exactly say why or when it happens
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

### Additional information:
![20190927201140_1](https://user-images.githubusercontent.com/32974671/65809564-1e217880-e164-11e9-997f-c1d77d371b3a.jpg)

**Comment by tsunamayo** [comment]
Thanks for noticing this, issue will be fixed in 19w40a. Cheers
