### ISSUE TITLE
Lost Control of Character, Camera Bug, Vehicle De-sync

### ISSUE THREAD

**Issue by JLAMontoya** [tsunamayo/Skywanderers#146]
Hello, this bug is hard for me to define.

I was in 3rd person view and attempted to exit one of the mechs that were in the starting area. It did not let me leave the vehicle, control the vehicle or go back into 1st person view. Upon reloading the save, the camera was inside the player's head (I could see his hair), and was invisible in 3rd person view. It was impossible to exit the vehicle and it would not respond to controls. As well, I noticed the larger mech in the background was now standing with it's arms straight out like a "T." The spacecraft nearby were all flickering like holograms.

I made a new game, and it too was broken. The camera was working again and the player was visible, but did not respond to controls and was standing like a "T." Relaunching the game from desktop fixed the bug.

**Comment by tsunamayo** [comment]
Hi, I think you just pressed F12 and entered debug photo mode. This mode was bugged, and I removed it already as key was conflicting with steam. It will be fixed in the next build! Thanks
