### ISSUE TITLE
19w40b Ship is invisible until a block is placed in the chunk

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1463]
### Short Description of the issue:

I am currently trying to load a large ship I have been working on. It does seem to load however it seems to have issues where the blocks are invisible. However when you place a block on the invisible blocks some of them become visible. It is possibly just an issue caused by the size of the ship because from what I can see it's only this one having the issue.

### Steps to reproduce the issue:

Try and load the ship attached. 
Once the block outlines are visible place blocks on some of the invisible blocks.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3694499/output_log.txt)
[Venator.zip](https://github.com/tsunamayo/Skywanderers/files/3694501/Venator.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Lsutehall** [comment]
I've seen this as well. My most recent ships spawn OK, but older blueprints seem to exhibit this problem.

**Comment by Zeuscp1** [comment]
I'm having the same problem

**Comment by tsunamayo** [comment]
@Lsutehall @Zeuscp1 are your ship large also? Could you please share the blueprint with me? Thanks!

**Comment by Zeuscp1** [comment]
Hello, is there any private method to share the blueprint? i want to keep my designs exclusive to me

**Comment by Lsutehall** [comment]
Blueprint attached. 

Actually this is quite old, from before the artstyle refactor. it still has a previous generation of slider on it as well, I think ; hence my thoughts about it being related to old BPs. 

[PRODUCTION SUPPORT SHIP.zip](https://github.com/tsunamayo/Skywanderers/files/3726265/PRODUCTION.SUPPORT.SHIP.zip)

Screenshots: ship just spawned by the drone - you can see the HUD markers, but the ship is invisible
![20191014210857_1](https://user-images.githubusercontent.com/40872394/66779950-7d52ed00-eec7-11e9-9e1f-52b5d7cb7d4c.jpg)

After finding it and placing some blocks - blocks preview OK, and then the chunk pops into view when they are placed. In this case I placed a few single blocks and then a stretched one before the chunk appeared.
![20191014210946_1](https://user-images.githubusercontent.com/40872394/66779970-9065bd00-eec7-11e9-88b2-5eb1fbebeb89.jpg)

**Comment by tsunamayo** [comment]
I no longer had any issue with this ship. Please tell me if you still have issue in recent build! Thanks
