### ISSUE TITLE
Drone explodes when spawned

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1465]
### Short Description of the issue:
So uh, drone goes big boom and plays the audio repeatedly and as peach said, becomes a sparkler.
...

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 970

### Additional information:
![20191006132542_1](https://user-images.githubusercontent.com/32974671/66273845-6c5a0a00-e83d-11e9-8eeb-50c248be9177.jpg)

**Comment by tsunamayo** [comment]
;) Okay I was not able to reproduce this (maybe I didnt waited enough?) but I should have fixed anyway... would be in 19w40c. Cheers!
