### ISSUE TITLE
Small blocks have no heat flow and way too much mass

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Skywanderers#1466]
### Short Description of the issue:

Main issues: 1. Heat flow of construction bricks is 0. 
                    2. Small blocks have way too much mass.
### Steps to reproduce the issue:

Build something without big Blocks, like a small pretty fighter. You cant balance it because "small blocks" have now heat flow and way too much mass. ->Also the mass of small blocks is too high by the factor 64(compared with the big blocks) so its impossible to heatbalance the small fighters  on the pictures.

For example: If Iplace the first big blocks to one of the fighters on the pictures, and the block number I place ist below 30 or so, the ships overheating immediately.

[3. Also the Stackbonus for Reactors and Thrusters is missing.]
### Environment
- Skywanderers version: 19w40b
- Graphics Card: gtx1070(mobile)

### Additional information:

![20191007183824_1](https://user-images.githubusercontent.com/43222403/66332542-4879ef80-e935-11e9-9b8d-51497ba52cbe.jpg)

![20191007183930_1](https://user-images.githubusercontent.com/43222403/66332557-4f086700-e935-11e9-8cb0-ff284ba28a7d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3698624/output_log.txt)

Keep up the good work!<3

**Comment by Xerma** [comment]
Tsuna did say in the recent devlog to not worry about balancing fighters or small ships just yet as brick systems aren't a thing yet. So I wouldn't worry that bricks don't absorb any heat, that's intended for now.

**Comment by Battlepixel** [comment]
Okey thanks. So its no issue, just something that will be probably added soon.
