### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by SpazmaticVoid** [tsunamayo/Skywanderers#147]
GPU: Asus Strix RX 480 8GB 
CPU: AMD FX-8370e 4GHz 
RAM: 16GB DDR3 

[error.log](https://github.com/tsunamayo/Skywanderers/files/1412049/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1412050/output_log.txt)

EDIT: Restarted PC and the game launches again.

**Comment by tsunamayo** [comment]
Okay thanks for reporting this, tell me if you see that often or not! Cheers

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by tsunamayo** [comment]
Hi, I will close this for now, if you have issues again please re-open the case of book another one! Thanks
