### ISSUE TITLE
[19w40b] Laser unit fires through other laser units

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1471]
### Short Description of the issue:
If two laser units are placed end to end, and the rearmost one is fired, the "bolt" from it clips through the forward one without hitting it. This is true for both the block and brick versions.

### Steps to reproduce the issue:
Place two laser units end to end, fire the one in the back.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3709006/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Oops; apparently, this is only true for the laser unit immediately in front of the firing one; stacking three deep results in this:

![20191009142001_1](https://user-images.githubusercontent.com/33041786/66513111-fa352f80-ea9f-11e9-8e49-b3aa0061dbca.jpg)

**Comment by tsunamayo** [comment]
Yes there is minimum hit distance, needed otherwise self hit would be too frequent. I dont think this much of an issue as this is not really something player will do. Thanks!
