### ISSUE TITLE
[19w40b] Destroyed voxels "remembered" after block is replaced

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1472]
### Short Description of the issue:
If a block has some of its voxels destroyed, and that block is then deleted and replaced by another, the voxels that were destroyed for the old block are remembered for the new block; so, even though the new block has never taken any damage, the voxels still need to be repaired.

### Steps to reproduce the issue:
Shoot some voxels till they break, then delete the block they're part of and replace it with a different one that occupies the same voxels. The voxels destroyed on the previous block will still be destroyed here until they are repaired.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20191009144257_1](https://user-images.githubusercontent.com/33041786/66515073-03280000-eaa4-11e9-96c0-ae039a945af2.jpg)

![20191009144310_1](https://user-images.githubusercontent.com/33041786/66515081-058a5a00-eaa4-11e9-810e-3ef2f4bf0480.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3709174/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I see. I think the proper thing to do would be to prevent block to be deleted once destroyed.
Otherwise I see a lot of potential "cheating" to not have to repair your block.
I keep you posted - should be in next update.

**Comment by tsunamayo** [comment]
Okay I prevented that. I also added the warning message, I am gonna add a lot more warning popup so the player understand better when he wants to do something that cant work. Thanks!
