### ISSUE TITLE
[Suggestion] Revamped Paints

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1473]
Switching from custom paint per ship to standardized colors was a smart move but myself and many others do wish we had a wider selection of colors and grays. I was working on building a palette image in Photoshop but completely forgot I had an image from when I was messing with pixel art.

**Here is the suggested palette:**
![palette](https://user-images.githubusercontent.com/32974671/66514967-cb20bd00-eaa3-11e9-967c-19222217ea65.png)

I know it's far more colors than what we currently have but this is something that should get tweaked early on while it has much less of an impact on builders rather than wait to change up the paint selection later only to make everyone redo what they already have. Some of the colors do look fairly close to one another but I have found myself in situations where I wish there was an "in between" color. 

All in all I do believe tackling the paints earlier rather than later will be far more beneficial, as well as having a wider selection. This is also another thing Skywanderers could hold over other voxel/building games because not many of them have a wide selection of colors, at all. One other important thing with the paints is that we need to have those vivid colors as well as less saturated colors. That part alone gives loads of creative freedom for builders.

If you have doubts on these changes or would like to discuss it more, please do stop by in discord whenever you've got the time. Everyone would love to see and talk to you again :D

**Comment by ZachZent** [comment]
Especially the greys. There is currently a large jump between black and the light grays. No good dark greys

**Comment by ExodistSKY1** [comment]
I agree with Xerma and ZachZent.    It is a good idea to switch from custom colors and have set ones... but there is not much variation with the current pallet in game. 

Xermas pallet will be the best choice from creative freedom through satisfying most if not all builders/players.

**Comment by Dwarf-LordPangolin** [comment]
I like this idea. The new paint and sticker system is awesome, but I feel we need a bit more variety than the current palette allows. For example, the current palette does have a dark blue -- but it's a purple-blue, whereas I'm looking for more of a gray-blue. Xerma's palette has enough variety to suit all needs I can think of, without being overwhelming.

**Comment by tsunamayo** [comment]
I like your palette, just be aware I have a limit for how many colors I can use (256), and I need to keep a lot of colors for metal, patterns, and more stuff. I think it is a bit overkill to be honest, like I would have trouble to remember which color I used, some seems way too similar.

I would prefer to simply tweak the current one a bit:
 - I also noticed the deep blue was a bit purple, this is the kind of things I can fix.
 - I can add more grays also.
What are other things you dont like with the current palette?

**Comment by Xerma** [comment]
This was an image I found on Google a few years ago but I can more than likely trim parts of it out and make the selection wayyyyy slimmer

**Comment by Xerma** [comment]
The biggest concerns I have with the current palette is, there aren't many grays but you said you could fix that, the colors we have should be more true or vibrant RGB colors, but we also need differently saturated colors as well

**Comment by tsunamayo** [comment]
Yes I could address all that.
I play with saturation and brightness:
This is the 5 current shades (from the code) :
      private static readonly ColorVariation[] COLOR_VARIATIONS = 
        {
            new ColorVariation { name = "Faded", saturation     = 0.4f, value = 0.8f},
            new ColorVariation { name = "Light", saturation     = 0.6f, value = 0.9f},
            new ColorVariation { name = "Saturated", saturation = 0.9f, value = 0.9f},
            new ColorVariation { name = "", saturation          = 0.9f, value = 0.65f},
            new ColorVariation { name = "Dark", saturation      = 0.8f, value = 0.4f}
        };

**Comment by Xerma** [comment]
Would you be able to share the RGB codes for the colors that are currently in the game? I removed half of the colors from the previous image so this one would be far more manageable but there are still some colors in there that are extremely similar. If I had the RGB values I could tweak this to match the current palette, unless you'd prefer to do it yourself which is understandable
![palette](https://user-images.githubusercontent.com/32974671/66530488-97f32380-eacd-11e9-8c95-4099340afb22.png)

**Comment by ZachZent** [comment]
https://imgur.com/a/5zFpH7S
Comparing what we have now to the one Xerma posted, its quite obvious which one is better. Row 5 is completely wasted, the two greens are very similar, few very bright colors, etc. Though the charts hex values are just extracted from the game and not the code, I defiantly agree that this should be redone sooner then later

**Comment by tsunamayo** [comment]
Okay @Xerma @ZachZent would it be possible to get the colors you would to have in the following structure (I thing the proposed pattern looks too destructured)
* a list of hue 
* a list of value and saturation.

Then every hue have the same value and saturation. Or maybe it is that constrain that make it dont look ok to you...

**Comment by Xerma** [comment]
Just to clarify are you asking for those values from the second picture I posted? (The 8x16 color grid)

**Comment by tsunamayo** [comment]
No because they dont have constant hue color by column and constant value/saturation by row.
I am trying to build a neat palette with a constant hue for each column, and a constant value / saturation pair for each row. 
I dont know if that would be too restrictive.

**Comment by Xerma** [comment]
Hmmm, well I don't know what it's like to code them within Unity so I don't know what level of difficulty it is but I feel that keeping constant hues and saturation all throughout keeps the palette pretty plain and a little too vibrant. A lot of value, pun intended, could come with having a wider range. of colors and more earthy tones

**Comment by ZachZent** [comment]
After testing a few things in MS paint, yeah not very fancy but it has manipulable hue and saturation values, I couldn't find a better combination that is already in game. Not without using the third value, luminosity. I would be surprised if Unity didn't have some sort of system to help adding the right colors. Xerma's color chart may not be as clean with their values (RGB, hue-sat-lum,) but I believe it would be worth the trouble. Assuming it is even possible in the code, I'm not a programmer.

**Comment by SageThe13th** [comment]
![CoH_color_palette_edit2](https://user-images.githubusercontent.com/58193603/73131888-6f3d5e00-3fd8-11ea-82bd-ef8d567908a1.png)

Here's a palette that's 150 colors. Leaving 106 for other things.

**Comment by tsunamayo** [comment]
Okay there is some new paint in the laster build 20w12a. If you have some comment on them lets open a new post! But you wont like it as there is less. Less is more!
