### ISSUE TITLE
[19w40b] Small Half Corner Left brick has collision issues

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1474]
### Short Description of the issue:
The Small Half Corner Left brick seems to be clipping into objects beyond its shape. This problem does not seem to be affecting the Small Half Corner Right brick. This only happens when the brick is in a specific orientation, and only when it is immediately next to the parent entity.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Example: the turret pictured gets stuck while rotating unless the red brick is removed. Changing the brick to any other orientation allows the turret to move: only in this position does it collide.
![20191009225837_1](https://user-images.githubusercontent.com/33041786/66538049-6b98d080-eae8-11e9-90ac-2903d1677838.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3710447/output_log.txt)

**Comment by tsunamayo** [comment]
Not applicable as I removed this brick. For that reason (and symmetry ;) ). I will put them back once I I manage to fix those issues.
