### ISSUE TITLE
[19w40b] Turret cores cannot be linked to hinges

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1475]
### Short Description of the issue:
Turret cores cannot be linked to the hinge block and brick. However, the turret axis menu can be accessed from the with the F key.

### Steps to reproduce the issue:
Place hinge and turret core, use link tool to try to link core to hinge.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20191010002744_1](https://user-images.githubusercontent.com/33041786/66541657-a5bc9f00-eaf5-11e9-8e00-d51e9103edeb.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3710624/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed I dont see any reason it should not be allowed on hinge. Thanks

**Comment by tsunamayo** [comment]
Okay this should be available in 19w43a. Thanks!
