### ISSUE TITLE
[Bug?] Capacitor can only attach to 1 face of shield generator [19w40b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1476]
### Short Description of the issue:
If the new shield gens only have one spot for capacitors, this probably isn't a bug, but just in case: capacitors can only attach to a single face on the shield gen.

### Environment
- Skywanderers version: [19w40b]
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Yes actually the final design will only have one slot face, I still need to work on the 3d model. Thanks!
