### ISSUE TITLE
[Suggestion] Faster-moving shots for the laser unit

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1478]
The speed of the shots fired by the laser unit should be much higher.

1. At the current speed of 300m/sec, it's very difficult to hit targets -- even large, 100m-long targets --that are only a few hundred meters away.
2. If the ship turns while firing, the projectile is slow enough that it may not clear the ship before the turning makes it bump into the projectile, damaging itself.
3. Since shot speed seems to be relative to ship speed, a ship moving between 300-400m/sec will have shots moving twice as fast as those of a stationary ship, giving it an unfair advantage.
4. Similarly, a ship running away might have a higher speed than that of shots fired at it, making it impossible to catch.
5. The slow-moving shots look too peaceful. ;)

A speed of 1km/sec would be a good starting point.

**Comment by ProPeach** [comment]
To add to this (which I totally agree with), I suggest tying projectile velocity with barrel length. Increase the base projectile velocity to ~500m/s, with a linear scale up to 1km/s the longer you stretch the barrel.

I vaguely remember you mentioning that various traits of a gun (damage, rate of fire, projectile velocity) will be dependant on how you build you gun so it could be this is just not implemented yet, if so then yay!

**Comment by tsunamayo** [comment]
Yes I need to increase the base speed.
Also I am not sure if I will keep the additive speed, it mess a bit with the AI shot accurary % when your ship is turning. I will do some more testing.
But yes you are also correct I will add addons, including a "sniping" barrel that would increase velocity and range, so the base velocity has to stay on the too side.
Btw if you have some addons type in mind, please share! There will be barrel addon, in which you can only put one but can rescale, and then side addon, that dont rescale but that you can mix up.

**Comment by tsunamayo** [comment]
So now we have faster shot and a range barrel that increase velocity! Thanks
