### ISSUE TITLE
GPU holds at 100%

### ISSUE THREAD

**Issue by GiinTak** [tsunamayo/Skywanderers#148]
GPU holds at 100% once I load into a world. No unusual behavior in title screen or launcher. Holds there regardless of where I'm looking or where I am.

AMD RX470 4GB OC ROX

-Giin

**Comment by tsunamayo** [comment]
Thanks! Could you please activate vsync - game is GPU bound. Just to understand, there is no freeze, the GPU is just running at 100% right?
Also how did you check your GPU % (just curious)
Cheers
