### ISSUE TITLE
Can't break damaged/repaired blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1481]
### Short Description of the issue:
Similar to issue #1472 but in this case I can't seem to break the laser shown here both when it was damaged and after I repaired it.
...

### Steps to reproduce the issue:
1. Damage laser/block
2. Attempt to destroy it
3. Repair damage laser/block
4. Attempt to destroy it
...

### Environment
- Skywanderers version: GTX 970
- Graphics Card: 19w40b

### Additional information:
![20191011171925_1](https://user-images.githubusercontent.com/32974671/66688304-a9fad080-ec4b-11e9-82a6-adfe7816e547.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3719804/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue is fixed, will be in 19w43a soon. Thanks!
