### ISSUE TITLE
[Suggestion] Reduce Laser Unit Block's Heat Damage

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1483]
Currently, the laser unit block gives the target that it hits so much heat damage that all the NPC ships I've shot with it have been destroyed from overheating; as far as I can tell, none have been destroyed from loss of structural integrity. The heat mechanic is a good balancing mechanic; it's just that ships should be more likely to blow up from damage than from heat.

**Comment by OverSavior** [comment]
I think what would balance it better is if heat would cause gradual lose of structural integrity with random blocks or blocks around systems that generate heat being destructed.

**Comment by Dwarf-LordPangolin** [comment]
Note:This seems to be a particular problem with laser unit blocks that have been stretched to increase their damage.

At the moment, even a single block laser unit is powerful enough to destroy a voxel with one shot. Since shots, no matter how strong, can currently only destroy one block at a time, this means that making weapons bigger so they do more damage has no effect on the amount of structural damage they do to a target per shot -- but it **does** have an effect on how much damage they do to shields, and to heat.


![20191012095959_1](https://user-images.githubusercontent.com/33041786/66703327-15d64b00-ecd7-11e9-8f8e-11e9f4c367de.jpg)
The laser units above all do exactly the same amount of damage to structural integrity; making them bigger has no effect there (which is highly counterintuitive). But the bigger ones **do** cause more damage to target shields, and to target heat. This means ships will usually blow up from loss of heat first, and especially when being shot by large ships with big guns.

A solution would be to allow shots from weapons to destroy more than one block at a time, which should be implemented for other reasons anyway.

**Comment by ZachZent** [comment]
Hitting basic hull should not do massive amounts of heat damage, rather raise the ship's base heat value due to the loss of hull. At most a small spike depending on the weapon

**Comment by Dwarf-LordPangolin** [comment]
Folks on the Discord prevailed on me to make a graph to illustrate the issue:

![Damage Graph](https://user-images.githubusercontent.com/33041786/66703790-ec6bee00-ecdb-11e9-9b3f-17e12ba2b08f.JPG)

**Nominal Hull Damage**
This is how much damage the tooltip says a laser unit will cause to a ship's hull, and theoretically increases by 100 for every meter of laser unit length. So in theory, a laser unit 10 meters long should do x10 the damage to hull integrity as a unit 1 meter long.

**Actual Hull Damage**
However, because even a single laser unit can destroy one block per shot, and never destroys more than one block per shot, the actual damage to hull integrity stays exactly the same, no matter how big the gun gets. This means there is a cap to how much hull damage can be done per shot; any damage greater than the HP of the individual block just disappears.

**Shield/Heat Damage**
Unlike hull damage, there is no cap to how much heat or shield damage can be done per shot. This means that shield and heat damage scale, while damage hull integrity stays static.

Again, the solution is to allow weapons to destroy more than one block per shot.

**Comment by tsunamayo** [comment]
Yes you are 100% correct, I haven't had time to code it yet. I will work on it for a near laser update though, to see if it helps a bit (it should of course). But the way I see it is
 * Laser ; balanced hull / heat. So laser is a good starting weapon. good for smaller ship that can afford just a single weapon too.
 * beam: more focused on heat.
 * kinetic / shell weapon. Better for hull damage.

So yes I want to balance the thing so that laser get heat and hull kill in a similar ratio.
=> have you tried with my ship or one of your own NPC ship? Also what do you think about the time to kill, is fast or too long?
Cheers

**Comment by ZachZent** [comment]
>     * Laser ; balanced hull / heat. So laser is a good starting weapon. good for smaller ship that can afford just a single weapon too.
>     * beam: more focused on heat.
>     * kinetic / shell weapon. Better for hull damage.

If I may say so personally, I would like to see variants of each weapon. You buy/craft the standard weapon then though some system, add modifiers to the weapon. Get a standard laser, modify it with "heat." More heat damage, but less damage overall. Or modifying it with "ion" which does more damage to shield but less to hull. Standard is still very useful, just not specialized. This allows all weapons (missiles are a different story) to be bought and used at any time based on the player's personal choice. The three can have their differences like said above, but I'd rather in the end weapons not be single purpose but rather expansive and player choice oriented.

**Comment by tsunamayo** [comment]
Yes I will add addons in an upcoming update, (#1478) , btw your idea of addon are cool please share more! There is two type of addon: barrel (can rescale, but just a single addon), side addon (cant rescale, but you can mix several). Also the trick is to have addon that can mix to other weapon type.
Tier 1 laser will have a single face with addon slot (so 1:1 addon),
Tier 2 laser will have two face (so 1:2 addon)
Tier 3 laser will have four face (so 1:4 addon)

This is all following the discussion we had a decade ago on the forum...

![image](https://user-images.githubusercontent.com/6604318/66709523-294de880-eda1-11e9-96c1-5001b0095201.png)
So it would look like that: white main weapon core, gold is barrel, blue/green is side addon.

**Comment by Dwarf-LordPangolin** [comment]
That all sounds awesome!!

I've tried combat with a couple different ships so far. The issue above is definitely more of a problem with ships with big guns (16 blocks long); it's a lot less noticeable with smaller guns, since the difference between heat damage and hull damage is much smaller. I do think the time to kill feels a bit short, but I can't tell if that's just the result of the [shield bug](https://github.com/tsunamayo/Skywanderers/issues/1479) making ships weaker than they should be; that might be the only reason it feels they're dying too fast (it's at least part of it).

On the subject of addons, I agree with Zach that the difference of whether a weapon is better against hull, shields, etc., should come more from the addons than from the base weapon itself. That would give players the greatest creative freedom, since a lot of people will have very specific ideas about what kinds of weapons they want their ships to have.

**Comment by tsunamayo** [comment]
Okay I have added the voxel piercing with the new update, should be live soon - check out for the patch note, there will be a first batch of barrel addons! Cheers
