### ISSUE TITLE
Awkward small grid hitbox/placement

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1488]
### Short Description of the issue:
The first half of the issue is that there seems to be something funky going on when placing the small rotator with other bricks (hitbox shows I can place it within another brick but can't obviously)

The other half is that some logic seems to have very peculiar areas for activation. It used to be that we could activate logic from further away but now we have to be much closer, which makes sense, but linking logic and trying to activate the logic has very weird and wrong hitboxes.
...

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 970

### Additional information:
1st half:
![20191014155125_1](https://user-images.githubusercontent.com/32974671/66782823-38659100-ee9c-11e9-8061-eab91adab9ca.jpg)
![20191014155131_1](https://user-images.githubusercontent.com/32974671/66782825-3a2f5480-ee9c-11e9-85b1-a747e2291153.jpg)

2nd half:
![20191014155503_1](https://user-images.githubusercontent.com/32974671/66782839-3ef40880-ee9c-11e9-9abe-9b91f182fa1b.jpg)
![20191014155506_1](https://user-images.githubusercontent.com/32974671/66782844-41566280-ee9c-11e9-933f-8e7a7b40a7c1.jpg)
![20191014155524_1](https://user-images.githubusercontent.com/32974671/66782848-43b8bc80-ee9c-11e9-99c6-0393b4a60dd5.jpg)
![20191014155529_1](https://user-images.githubusercontent.com/32974671/66782851-45828000-ee9c-11e9-814f-3ef39d84ea5c.jpg)
![20191014155532_1](https://user-images.githubusercontent.com/32974671/66782855-474c4380-ee9c-11e9-94f2-0029b8bf37a5.jpg)

**Comment by Dwarf-LordPangolin** [comment]
The placement issue seems to be cropping up with bricks in general. I think it might be related to the angle one tries to place the brick from. Placing it from off to the side doesn't work:
![20191008121617_1](https://user-images.githubusercontent.com/33041786/66787941-39ea8580-eeab-11e9-9e2e-a2968f1699ac.jpg)

But moving more directly across from it does:
![20191008121619_1](https://user-images.githubusercontent.com/33041786/66787943-3bb44900-eeab-11e9-979d-56e63a626326.jpg)

Again, placing it at a low angle doesn't work:
![20191008235352_1](https://user-images.githubusercontent.com/33041786/66787976-5b4b7180-eeab-11e9-8606-62857cf3e704.jpg)

But placing it from directly above does:
![20191008235358_1](https://user-images.githubusercontent.com/33041786/66787984-69998d80-eeab-11e9-8a74-98c4bd466399.jpg)

**Comment by tsunamayo** [comment]
Brick placement are much better now. Thanks!
