### ISSUE TITLE
Suggestion - Brick Clear slopes

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1490]
Just wanted to suggest the addition of some more clear brick options. Currently we only have the foggy one and the pattern one if you want to do small windows. It would be nice to expand this with the addition of some more clear bricks. Some that resemble the block variants would be nice. Having some transparent cubes and slopes at a brick scale would add some extra options for building custom cockpits and interiors.

**Comment by tsunamayo** [comment]
Yes this was definitely in my to-do list, actually I wanted to remove the current block one and replace them with brick one. I just need some dev precisely because of the wedge one, they are a bit trickier to make. I keep you posted!

**Comment by tsunamayo** [comment]
So I added some window tile, with wedge and tetra variant. That should get you covered! Thanks
