### ISSUE TITLE
[BUG] Handle brick clips into itself [19w40b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1491]
### Short Description of the issue:
The handle brick can be placed so that it clips into other bricks.

### Steps to reproduce the issue:
Place a handle brick, then place another brick on it.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20191014213629_1](https://user-images.githubusercontent.com/33041786/66795635-ceb0ab80-eeca-11e9-8fc9-f5b85d8c3be4.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3727165/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, issue will be fixed in 19w43a. Thanks!
