### ISSUE TITLE
[BUG] Ship will not load in new update [19w40b]

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1493]
### Short Description of the issue:

the "Destroyer" BP was converted over to the stretchy block system from previous builds and had no problem being spawned in before this new update. I also tried to load in 4 other ships which also received a null in the output logs.

I traded ship BP's with Rizzo through discord (another player ion the community having the same issues) and we both tried to load each others ships, with no luck. 

Please let me know if you need my BP's and I will email them to you within the day of a response.

### Steps to reproduce the issue:

-Spawn in (my BP or any other BP) that has been having issues
-It will not be spawned in game. 

### Environment
- Skywanderers version: 19w40b
- Graphics Card: 1080ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3731593/output_log.txt)

**Comment by Rizzo911** [comment]
I'm also having this same issue with several blueprints. Attaching some examples for reference.
[blueprints.zip](https://github.com/tsunamayo/Skywanderers/files/3746062/blueprints.zip)

**Comment by tsunamayo** [comment]
How old where those blueprint? Seems they are super old! did you load them in a recent version and then save them? (or just load them and do nothing). At one point it just gets too complicated to support blueprint several versions older, I recommend loading and saving your blueprint regularly. 
If you could send me that Destroyer blueprint so I can have a look that would be great!
Cheers!

**Comment by Rizzo911** [comment]
@ExodistSKY1 he's waiting on you for the destroyer blueprint you describe.

@tsunamayo, I thought I had loaded AND saved them, but given the dates you might be right. The strange thing is they were loading fairly recently and worked. I found it as I was going through ALL my blueprints to do just what you described, but it was also trying to determine which blueprints weren't working.

**Comment by ExodistSKY1** [comment]
BP was sent Via E-mail Oct 24th

same thing, when they would load in I did not see the need to re-save if I did not change anything. (I will be saving more often from now on)

**Comment by tsunamayo** [comment]
Okay sorry for this guys! Closing this for now.
