### ISSUE TITLE
[Suggestion] Faster Shield Bloom Effect

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1494]
Following your request for feedback on the visuals of combat in the last devlog, I suggest speeding up the shield hit effect, as well as the shield collapse effect.
While the current effect looks great (especially with the recent improvements) it lacks urgency and "wow" factor in my opinion. This gif is just a regular shield hit sped up by 400%
![Skywanderers 4x Shield Effect](https://user-images.githubusercontent.com/27857711/66940563-0e97a000-f03d-11e9-8340-c0b6d0e0e46f.gif)
This also reduces the visual impact from inside the cockpit, meaning the pilot is less likely to be blinded by the effect.
Through some discussion of Discord, the idea that the "splash" diameter could scale depending on the incoming damage came up. This would give further visual feedback on the magnitude of the damage you are receiving and could look quite spectacular.

**Comment by ZachZent** [comment]
Also I wonder if a "expanding ring" would be better then the current "blob." If the weapon's intensity determines the range of the effect, which should totally be a thing, a large shield blob effect would not be great for viability for the short time.
https://media.giphy.com/media/hHvwvuC9jwssU/giphy.gif
A ring however, like a single ripple in a pond, would remove that minor issue, allow for the range determined by weapon damage, and still look awesome as hell.

The other stuff like speed of effect and shield collapse should absolutely be a thing. It is the little effects

**Comment by Xerma** [comment]
I do also agree that the effect should be sped up. I'm obviously a fan of Star Wars stuff so yes speeding it up would do just fine but what if the effect appears more "solid" similar to how the Clone Wars does it: https://youtu.be/ufsq0hKGvGc?t=127

**Comment by tsunamayo** [comment]
Sorry I have been quite busy (working or having torus back).
Yes I agree 100% I will speed it up. It is already supposed to be looking like a ring, but I guess the way it is tweaked it looks like a blob. 
Actually I wanted to change to design to a hexasphere if you can give me your feedback:
https://www.pond5.com/after-effect/46783712/hitech-hexasphere-glitch.html
The idea would be:
  - more tile for larger ship,
  - each function is computed at the tile level, (in the vertex shader, not the pixel shader), so it will have a discontinuous feel, making it more lisible I hope
 - also I will play with each tile position and scale. For example I could have a wave effect by displacing the tile height on impact. Or have them scale magically on activate / desactivate, or other cool stuff. Cool think is that the shader would be faster.

Cheers

**Comment by ZachZent** [comment]
Based on the link, I am not a fan of a pure hexasphere if you will. I like hexes, but to be they are best when they are subtle. In the background. 
https://cdn1.epicgames.com/ue/product/Screenshot/HighresScreenshot00003-1920x1080-0f979e5a32a3443cd6421c35c0b04ee5.png
You keep the ring effect we have now, well improving the blob, and include some hex graphical elements. In my opinion only hex just looks cheesy and comical.

**Comment by tsunamayo** [comment]
So the link I sent is not how I want to make them, I want to have a constant color / opacity per tile. No tile border whatsoever. Also I can use some hex graphical element like that, mapping things onto a sphere is a real pain.

**Comment by ProPeach** [comment]
Personally I would prefer an improved "ripple" effect rather than hexagonal, they're a lot more neutral in look whilst still maintaining that classic sci-fi game feel. 

I do know that some people have been asking about hex shields for a while though. If you were planning for different shield types (not sure if this is something you want to do), why not give a different shield the hex effect? Say for example the ripple effect is good at protecting against energy weapons, while the hex which looks a bit more solid and hefty is better for kinetic protection.

**Comment by tsunamayo** [comment]
Okay the new shield being live, if you guy have any feedback please shoot!

**Comment by ProPeach** [comment]
Thanks for following up! I was actually about to write another post this evening with feedback but this fine too.

Personally, I *much* prefer the old shield design to the new hex shields. I can see the direction you're going with them but I don't think mixing the "bounce" and overlapping effect when the shield is hit with the hexagon shapes is successful. To me a hex shield should feel very solid, I'd expect that a group of hexagons would flash into existence when the shield is hit and then fade after a very short time, maybe just a fraction of a second.
Part of the problem might be that the shield is made up of individual shapes with nothing between them, perhaps having a coloured background would help. The shield collapse animation is also a step down in my opinion, it lacks the urgency needed for a mid-battle event and again the ripple effect feels odd.

I would recommend reverting back to the original shield with the improvements talked about here, namely increasing the speed of the animation and tying projectile damage to ripple radius. It's a simple, clean, crisp and professional looking effect that feels satisfying and logical in the heat of battle. The frosted glass effect that you applied to it before changing to the hex effect was amazing. The only other improvement to the previous shield effect would be to tone down the spots (outlined in red), or create a smoother blend between them
![image](https://user-images.githubusercontent.com/27857711/72944810-ff2d9e80-3d71-11ea-8c50-f6f40f7940a3.png)


If you're set on the hex shield, perhaps try something more rigid and strong looking, as if the hexes are armour plates that will flash up to protect you and then disappear a moment later.
https://deadlyprintstudio.com/wp-content/uploads/2019/04/DSC00260_retocada.jpg

**Comment by ZachZent** [comment]
Honestly I don't like it. Not that it would ruin "MAH IMMERSION" but it is just really silly. The hexes seem cartoonish and disconnected especially when it bounces. The shield dispersal effect has the same silly feel to it literally scattering to the wind. The old shield may have been comparatively uninteresting and even generic, but it worked well and looked good.

I agree with peach, the first step is to go back to the old model of a nice faded glass effect. You can then mix the two, hexes in faded glass similar to the picture above or this one below. Peache's suggestion on how it could look works so I won't repeat what he said beyond the need to speed up the animations compared to the old shield. It is not an immediate problem, but should be addressed at least before steam release.
![image](https://user-images.githubusercontent.com/36980446/72946046-f9689680-3d3a-11ea-9ef5-e8ee25d0e37a.png)

**Comment by FelixGold** [comment]
Is there any way to make the effect one sided? Like allow people on the outside to see the shield hit but to keep the pilot's view clear?

**Comment by ExodistSKY1** [comment]
Personally, the new shield is fine with me. If it is better on system performance then I would say it is okay... but if you could implement ProPeach's second idea with the more rigid styled hexagons I feel that would be a really neat addition and make it feel sturdy and that it could actually do its intended purpose.   Just my 2 cents.

Keep up the awesome work!

**Comment by ProPeach** [comment]
I like the fact that you can see the effect from inside the shield as it's a great visual feedback to the damage you're taking, but I do agree in its current state it can be obstructive. I think that speeding up the effect will help with that.

As an alternative shield collapse animation for the hex shields, perhaps try an effect similar to the old style.

**Comment by tsunamayo** [comment]
Actually I liked the idea of having organic tiles that displace themselves. That gives me an axis to play with on the effect.
Just found this video, I havent watched it yet, but he got the same idea: https://www.youtube.com/watch?v=hTJqo1HeEOs
And it is looking 10x better than mine, I didnt really had much time to spend on the fanciness...
I dont think I will have time to update it really before early access...

**Comment by ProPeach** [comment]
The video you linked does have a very nice effect yeah. I think the main difference is that while the current shield has individual hexagons of uniform colour that bounce, the one the video has no bouncing hexagons and the hit effect is shown by a smooth ripple in the opacity and intensity of the shield rather than the plates actually moving. The plates don't move, but you still get that cool flashing effect when the shield is hit.

Would it be too much to ask to have both shield types (old and hex) available in game perhaps with different properties, or perhaps a wider poll be carried out? This seems like quite a divisive issue

**Comment by Aiwii** [comment]
The current hex shield effect is ok but having proportional hexagons that aren't stretched would be nice

**Comment by tsunamayo** [comment]
Okay so I finally backpedaled on that one lol... Cheers
