### ISSUE TITLE
[BUG] Blocks changed color after working on ship for a while [19w40b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1495]
### Short Description of the issue:
After a lot of placing and deleting of blocks to figure out a design, a bunch of the blocks spontaneously changed color.

### Steps to reproduce the issue:
This might happen after placing/deleting/placing a bunch of blocks.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20191017234106_1](https://user-images.githubusercontent.com/33041786/67066393-053f2e00-f138-11e9-89c1-24a2db164e51.jpg)

[Odd Orange Blocks Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/3742346/Odd.Orange.Blocks.Blueprint.zip)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3742345/output_log.txt)

**Comment by Senakysam** [comment]
I've seen that happen only when the symmetry bugs out and doesn't delete blocks. I'll delete a block on one side, it won't delete on the other, and then I'll place a new block clipping in that space. If I go to the other side and delete either of those blocks, it will make anything overlapping turn that color.

**Comment by tsunamayo** [comment]
I think Sen was correct, as I fixed the symmetry clipping issue this should no longer appears. Thanks!
