### ISSUE TITLE
Turret cores don't link across child entities

### ISSUE THREAD

**Issue by hl2shadowslayer** [tsunamayo/Skywanderers#1498]
### Short Description of the issue:
It appears that if you place a turret computer on a child entity, and your yoke on either another child entity or the base entity, [or vice-versa] it's not possible to link them together.
...

### Steps to reproduce the issue:
put a child entity on your ship big enough to fit logic components
place a turret core on the child entity, and a yoke on the base entity
try to link them together

...

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 750ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3765333/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue. Yes indeed, it was a restriction valid only for for spaceship core (they need an orientation). Issue is now fixed, will be available in 19w43a, cheers!
