### ISSUE TITLE
A suggestion for kinetic weapons

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1499]
https://docs.google.com/document/d/1QOtGWgWAWBWcwGDiLACchb76HMJvgCr_DVrpby4B9fw/edit?usp=sharing

^This document
Summary:

Kinetic weapons would have two types, railgun type and modern type that would fill different roles
They would have a heat and energy capacity, along with an ammo capacity

Railguns would specialise in armour piercing, range, damage, but would tend to be slower fire rate due to large heat and energy costs

Normal bullets would be like your explosives, or flak, or genetic bullets, and would be suited for rapid fire, or small armour piercing weapons

Honestly just read the document, im not sure how to summarise it lol

**Comment by tsunamayo** [comment]
Thanks for your suggestion, there is some cool things in there.
Just be aware:
 - You will only be able to rescale weapon on the up axis
 - There is several barrels type
 - I want to have projectile revolve around shell crafting. You choose a shell size (larger = more payload but slower), and type (piercing, explose on impact ect), and put a payload inside, and there you go.
Cheers

**Comment by ultrak2k** [comment]
Ah okay, that makes sense
do you mean up axis as length?
Also will the different barrel types be different widths? because wouldnt having a big ass shell from a smaller gun be wierd

**Comment by tsunamayo** [comment]
Yes length only.
No barrel will have a standardized diameter.
Big shell will be like 20cm large, normal shell 10cm, but thats just an example. They will both fits and looks alright. Dont expect 1m large shell though...
