### ISSUE TITLE
[Med/High] Brick remnants after destroying other bricks, especially with moving bricks

### ISSUE THREAD

**Issue by clmd58** [tsunamayo/Skywanderers#15]
generally, when building sliding bricks, as well as any of the other little modular brick pieces, if you delete one that was built prior to others, the others become trapped in a weird limbo state and cannot be deleted sometimes. The slider on the primary sliding brick parent piece is a good example. if you build a slider brick, then slider extensions, then delete any of it when the slider is not in its home position, everything gets stuck. any blocks or bricks that were attached to the slider piece are frozen as well.

**Comment by tsunamayo** [comment]
Sliding issue will be fixed in next update : children entity is deleted. Thanks !
