### ISSUE TITLE
Tutorial doesn't reset

### ISSUE THREAD

**Issue by CyboLP** [tsunamayo/Skywanderers#150]
on New game. Even not after uninstalling and re-installing the game.

**Comment by tsunamayo** [comment]
Hello, you need to go to completely clear the following location:
C:\Users\{YOUR_USER}\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
Please do a backup first if you want to keep any existing blueprint.
I will add a "restore starting area" option in the menu to make it more user friendly.

**Comment by CyboLP** [comment]
Deleting that folder worked fine for me! THX!
