### ISSUE TITLE
[BUG] Can't get turrets to work [19w43a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1502]
### Short Description of the issue:
I've linked a targeting computer to a turret core, and the turret core to a rotator, hinge, and the guns, but the turret never fires on hostile ships. What am I doing wrong? :(

### Environment
- Skywanderers version: 19w43a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20191025122212_1](https://user-images.githubusercontent.com/33041786/67591173-6c557780-f722-11e9-9dae-5122ed1b2557.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3773102/output_log.txt)

**Comment by ProPeach** [comment]
I have the same issue. The turret works fine when using a yoke hooked up the the turret core, but if I switch the yoke for a targeting computer the turret doesn't function when under attack from an AI ship.

**Comment by Majikmonster** [comment]
Does the targeting computer need to be linked to the ship yoke or ship core? I saw that the AI ships have them linked to the yoke.

**Comment by ProPeach** [comment]
I believe that linking the targeting computer is needed to make the whole ship AI controlled, not just the turret

**Comment by Dwarf-LordPangolin** [comment]
So, I'm an idiot. Now I understand what I've been doing wrong. It's two things. Posting this in case any of the rest of you are still struggling with this.

1. In Tsuna's video with the turret setup, he says "you **can** link it [the pilot's yoke]" to your targeting computer -- so I figured that meant it was optional. And, since I always have the pilot handling fixed weaponry and missiles, and all turrets are either automated or handled by a dedicated gunner, I decided not to use that option, and linked them to a gunner's yoke instead. But it's not an option; it's not a "can," it's a "must."

So, the correct setup is: **Pilot's** Yoke > Target Computer > Turret Core > rotators and stuff for one or more turrets.

2. You have to target the hostile ship yourself. This one really threw me, particularly coming from Space Engineers where turrets handle their own targeting independently. You have to manually designate the target for the turrets.

Not sure how I feel about that. It _does_ make the turrets better suited for DPSing single targets, but it also makes them much worse for point defense against fighters, etc. Going to have to test it to see how I feel about it. It's possible that it will function differently with, for example, NPC gunners; they might be able to target independently (which would actually be a grand way to balance auto turrets vs crewed turrets).

**Comment by tsunamayo** [comment]
So I will improve the turret link experience a bit - to add a few feature like auto targeting for small defensive turret, auto-fire option, and automatic targeting of pilot target instead of having to link it from the pilot yoke. I keep you guys posted.

**Comment by tsunamayo** [comment]
Turret config is now more streamlined, I think you made them work ;)
