### ISSUE TITLE
[BUG] Build tool has turned invisible [19w43a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1503]
### Short Description of the issue:
The build tool is no longer visible when the player has something selected.

### Environment
- Skywanderers version: 19w43a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Pictured: the infinite majesty of space!
Not pictured: the build tool! ;)
![20191025122207_1](https://user-images.githubusercontent.com/33041786/67592323-07e7e780-f725-11e9-873b-f9caa7f3d4c8.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3773154/output_log.txt)

**Comment by Lsutehall** [comment]
I can confirm this as well. It's still present in the external player model, however.

![20191025225730_1](https://user-images.githubusercontent.com/40872394/67606988-ee718a80-f77a-11e9-981e-203170d221a0.jpg)
![20191025225723_1](https://user-images.githubusercontent.com/40872394/67606992-f03b4e00-f77a-11e9-99b7-fb999720021b.jpg)

**Comment by tsunamayo** [comment]
Hello,
Yes I was working on updating the model, it is now there for next update (19w46a or later)
Thanks!
