### ISSUE TITLE
Invisible mirrored blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1504]
### Short Description of the issue:
It seems that anything that isn't part of the block "family" does not appear when placed while having an active mirror. They are there but they are invisible until updated when something else gets place in the same grid. If you break one the mirrored counterpart becomes visible and stays there until the grid gets updated again. This applies to just about everything except paint.
...

### Steps to reproduce the issue:
1. Mirror
2. Place a non-block
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

### Additional information:
![20191027030110_1](https://user-images.githubusercontent.com/32974671/67631655-38d03580-f867-11e9-801c-5c6d7dd77e8c.jpg)
![20191027030112_1](https://user-images.githubusercontent.com/32974671/67631656-3a99f900-f867-11e9-87c5-a3d27c32b7b7.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3775618/output_log.txt)

**Comment by tsunamayo** [comment]
This issue is fixed in 20w13a. Thanks!
