### ISSUE TITLE
Drone still explodes

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1505]
### Short Description of the issue:
The building drone still explodes constantly while moving but does not explode while staying still. This might just be due to it being made from bricks, that's my best guess anyways.
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

### Additional information:
![20191027031532_1](https://user-images.githubusercontent.com/32974671/67631746-49cd7680-f868-11e9-8c6e-77de079f1ada.jpg)
![20191027031542_1](https://user-images.githubusercontent.com/32974671/67631749-4afea380-f868-11e9-9c2c-81203c50cf1c.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3775624/output_log.txt)

**Comment by ProPeach** [comment]
I don't have this issue when using the drone with any of my ships. Does this only happen when the drone is linked to one blueprint or all of them?

**Comment by Xerma** [comment]
Tried a with a fresh install, seems to be fixed after deleting all files and reinstalling
