### ISSUE TITLE
Unnecessary "repairs needed" tip

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1507]
### Short Description of the issue:
Left clicking at nothing displays the repairs needed tooltip
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

### Additional information:
![20191027033044_1](https://user-images.githubusercontent.com/32974671/67631895-5bb01900-f86a-11e9-986e-4d46b6bdabaf.jpg)

**Comment by tsunamayo** [comment]
Okay this bug is fixed, will be in the next update (19w47a or later.) Cheers
