### ISSUE TITLE
Symmetry - breaking blocks breaks game

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1508]
### Short Description of the issue:
While using symmetry, if you break too many blocks the game appears to break : repetitive issues in log file
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3775639/output_log.txt)

**Comment by tsunamayo** [comment]
Okay sorry for missing that one, but the issue should now be fixed. Thanks!
