### ISSUE TITLE
V-sync does nothing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1511]
### Short Description of the issue:
Having v-sync enabled does not cap my frame rate. This is a fresh install. Normally my frames are capped at 60 and sometimes linger to 59 but then snap back to 60.
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

### Additional information:
![20191029223403_1](https://user-images.githubusercontent.com/32974671/67827116-d06a9980-fa9c-11e9-8195-c2a09bda5573.jpg)

**Comment by tsunamayo** [comment]
Thanks, this issue should be fixed in the next update (19w47a or later).
