### ISSUE TITLE
Pressing escape on options menu blacks out game

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1512]
Short Description of the issue:
Game will only display blackness and version number if you hit [ESC] (clicking the X doesnt do anything wierd)

Steps to reproduce the issue:
Enter options menu in the main menu
Press ESC
Black screen, only way to exit is alt F4
Environment
- Skywanderers version: 19w43a
- Graphics Card: AMD Raedon 7500 HD graphics

**Comment by tsunamayo** [comment]
Yes indeed sir! This is fix for next update (19w47a or later) Thanks!
