### ISSUE TITLE
Undeleteable bricks and other brick weirdness 

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1513]
### Short Description of the issue:
I have been working on a ship recently and have noticed a few weird things to do with bricks. Firstly occasionally you will place a brick and the game will decide that your brick can't be deleted. However, it still knows that there is a brick there because you can't build on it.

Brick hitboxes, in general, seem to be bugged. Often you are unable to interact with a brick unless you look at it from a certain angle. This does make building with them pretty tough. 

### Steps to reproduce the issue:
It's hard to say what causes this issue. I have included a blueprint where I am having this issue and have tried to highlight some areas where these bugs are occurring. I find that the placing issue occurs near the front and there is an example of one of the indestructible bricks on the top. There doesn't seem to be anything funky in the output log but I have included it for reference.

### Additional information:

Placing a brick on the side:
_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/43644633/68077661-9f9da380-fdbf-11e9-9171-8dbf37f61e13.png)

Trying to place one on the top:
![image](https://user-images.githubusercontent.com/43644633/68077667-b2b07380-fdbf-11e9-962f-81d67c7ea751.png)

Unbreakable brick:
![image](https://user-images.githubusercontent.com/43644633/68077677-e1c6e500-fdbf-11e9-9283-5530713d43c9.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3801018/output_log.txt)

Ship:
[VCX 100 Ghost brick bugs.zip](https://github.com/tsunamayo/Skywanderers/files/3801019/VCX.100.Ghost.brick.bugs.zip)

**Comment by Garrett-C** [comment]
Quick side note. I did some testing and I think the invincible brick was caused by the sticker.

**Comment by tsunamayo** [comment]
Thanks, yes I would say it is sticker related. If there is a sticker I think you cant delete it, I should not prevent it. I keep you posted once I make the change. Thanks!

**Comment by tsunamayo** [comment]
Okay so I changed the behaviour a bit, now if  you have a brick you can delete the sticker, but if you have a sticker equiped, you cant trash bricks. Seams less accident prone that way! Thanks
