### ISSUE TITLE
[Suggestion] Add a way to delete multiple blocks at the same time.

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1515]
So I am currently working on updating one of my older larger ships to the current build so that I can test out some of the power and heat stuff. In order to do this though I need to convert it to the new systems tech. When I first built it all the systems were individual so now they are all individual again. 

It would be nice if there was a way to delete more blocks at once like before. 

Here is an image showcasing what I mean about the system blocks.
![image](https://user-images.githubusercontent.com/43644633/68237874-fabdd900-ffff-11e9-9f59-d5cf982ed2a0.png)
![image](https://user-images.githubusercontent.com/43644633/68238292-cb5b9c00-0000-11ea-92fc-d1e10ab8edea.png)
![image](https://user-images.githubusercontent.com/43644633/68238311-d4e50400-0000-11ea-9325-040f2e4353c9.png)
![image](https://user-images.githubusercontent.com/43644633/68238333-e0382f80-0000-11ea-8f45-0d0518cb05f9.png)
![image](https://user-images.githubusercontent.com/43644633/68238349-ea5a2e00-0000-11ea-8e9a-6e19df465345.png)
![image](https://user-images.githubusercontent.com/43644633/68238386-fcd46780-0000-11ea-8461-92d6472b421d.png)

So a lot of system blocks to go.

**Comment by tsunamayo** [comment]
Damn, that ship is a monster! Unfortunately (and I feel your pain), I dont really plan to add this as it would not match the current logic. I want add and remove action to be perfectly symmetrical as this is what is making sense player-wise and code-wise. (code now is completely different and fully embrace stretch block, not multi-block)
I should have make a blueprint conversion algo smarter, or create a new block id... Now it is a bit too late =(
Thanks, sorry for this...
