### ISSUE TITLE
19w43a [BUG] Deleting block from an exploded ship = bad

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1517]
When deleting a block from an exploded ship. everything but that ship will turn black (refer to screenshots) 

Then...

When pressing F5 to bring the drone in it will spontaneously explode and continue exploding as seen in the screenshots.  

...

-delete block from an exploded ship

-Press F5 to bring in the drone and watch the fireworks

...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: 1080ti

![20191107120747_1](https://user-images.githubusercontent.com/45324484/68415542-3966a700-0158-11ea-982b-43248b719644.jpg)
![20191107120816_1](https://user-images.githubusercontent.com/45324484/68415543-3966a700-0158-11ea-811a-c075b50e493b.jpg)
![20191107120821_1](https://user-images.githubusercontent.com/45324484/68415545-3966a700-0158-11ea-93b3-ecaa3ce43511.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3821109/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I am not able to reproduce this one, I am not sure if I am missing something or if I already fixed the issue. Do you reproduce 100% of the time? We will see in next update if it is still there. Thanks!
