### ISSUE TITLE
[Question] Land generation

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1519]
What is the plan for land generation, first on the torus then on planets?

The three usual styles
1. Minecraft - All blocks
2. Smooth Minecraft - Still voxel blocks, but smoothed, http://www.9minecraft.net/nocubes-mod/
3. Space Engineers/Astroneer/No Man's Sky - Non-voxel terrain

The old torus was a mix of all three of these. The mountains were the first option. The rest were a mix of two and three. None of these are a bad option, just wondering which one will be how the torus is generated.

**Comment by tsunamayo** [comment]
Hi, sorry I am not too active these day, I am really busy on tons of stuff - including terrain for the torus. 
So I go clearly for 3), it was one of the big motivation behind the new art style, to move away from the terrain block, it was not working very well and a nightmare to work with in many regards.
Things should get smoother with the new tech ;)
But it might still be voxel based at one point (typically with asteroid, I will use voxels then marching-cubes), just with smooth surfaces.
Cheers
