### ISSUE TITLE
Docking a hovercraft on a torus fights the gravity effect

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#152]
Early on in Raibens stream on Tuesday the 24th of October, he was trying to get a hovercraft to dock with an arm above it, but as the hovercraft drifted up to dock, it would jitter up and down as if fighting the "gravity" effect of the torus and was unable to dock.

He tried the same setup out in space, with the docking arm above the hovercraft and it worked as intended, so it looks like it was the torus gravity that was causing the jittering effect.

Of course a hovercraft shouldn't be able to just float up against gravity, the issue I'm reporting is the jittering.

Hope this helps!

**Comment by tsunamayo** [comment]
Okay good spot thanks a lot for reporting that! You even reporting issue that are not yours, you are an amazing tester ;-)

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
