### ISSUE TITLE
[Suggestion] Clipping. 

### ISSUE THREAD

**Issue by Zeuscp1** [tsunamayo/Skywanderers#1522]
Hello, this is a suggestion. Me and many other players would like to have some sort of controlled clipping in the game as it allows us to have a lot of creativity and make some unique things that would't be possible otherwise 
 
like this chair
![20190607152828_1](https://user-images.githubusercontent.com/35397831/69933028-48145580-149b-11ea-9c95-e2b5bc8f49a2.jpg)

**Comment by ExodistSKY1** [comment]
I think Tsuna had expressed interest on bringing in a "blank" chair allowing us to create our own

**Comment by Zeuscp1** [comment]
That would be nice, altho a chair is not the only thing that can be customizable by a lot with clipping

**Comment by tsunamayo** [comment]
Yes I want to give a minimalistic chair, unfortunately I dont plan on bringing back clipping... Thanks!
