### ISSUE TITLE
[Suggestion] Clear glass brick

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1524]
We already have the faded glass brick and the hexagon glass brick, but is there anyway we can get a brick that works like the two others, but is simply clear? No patterns or anything

**Comment by tsunamayo** [comment]
Yes, actually I want to move all glass / frame (not the canopy or window) block to mini scale, but I need to work on something for wedge and tetra... Thanks

**Comment by ExodistSKY1** [comment]
Would it be possible to get half brick or 1/4 brick versions of the two glass window blocks currently in the game?

**Comment by tsunamayo** [comment]
@ExodistSKY1 You mean a 1/4 of 1/4m = 6.25cm? If yes thats tiny! What do you want to do with this?
Cheers

**Comment by ExodistSKY1** [comment]
Myself and a few other testers are big fans of the squared industrial Canopy look. 

![20200113201150_1](https://user-images.githubusercontent.com/45324484/72308550-54ff9980-3642-11ea-8986-c07f690465d0.jpg)

    I should have worded my original question better, What I would like and feel would help with variety in the canopy area of the game would be:

     -A half brick that is very similar to the currently implemented window block that can be placed on the brick grid. The two current windows are nice for larger builds but with smaller ones it gets a little more tricky especially without clipping. 
![20200113201627_1](https://user-images.githubusercontent.com/45324484/72308568-5c26a780-3642-11ea-833c-3e44f803b89e.jpg)
     -In the image above to the left I added the 45 degree block that I think should also be added into the game in the same form factor as the block windows. (this would be the same 1/2 thickness of a regular brick but scaled on the block side of things) 
     -Also a similar one in brick form as you can see to the right, at the same thickness of 1/2 brick but able to be placed and stretched on the brick scale. 

![20200113201900_1](https://user-images.githubusercontent.com/45324484/72309017-4ebded00-3643-11ea-88d6-a9ea6e0b0d50.jpg)
     -In this image above the block to the top left is the window wedge that I think would also help if there was brick version added. 

My reason for requesting these is to help with Aesthetics that is not just the regular canopy blocks in game giving a more diverse feel and adding to the tools that builders can use. Cutting down on possible forced clipping just to get the look they would want and prettier more unique cockpits and other possibilities that builders could come up with.

**Comment by tsunamayo** [comment]
Okay now you have a good selection of brick size windows. I will add even more with more transparent version (no frame) Thanks!
