### ISSUE TITLE
[BUG] Unable to break/place anything after using mirror

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1529]
### Short Description of the issue:
When mirror mode is enabled, there is a seemingly random chance that after breaking a block, you will then be unable to break or place a block, paint or sticker on any ship. Below is a video of the bug and the Output_log, you can see that when I try to place/break a brick the placement hologram pulses but does not place/break the brick. The only way to fix this that I've found is to reload the world. From what I've heard speaking to others, it's a very common bug.

[Skywanderers Mirror Casuing Unresponsive Game Bug.zip](https://github.com/tsunamayo/Skywanderers/files/3976225/Skywanderers.Mirror.Casuing.Unresponsive.Game.Bug.zip)

### Steps to reproduce the issue:
Place a mirror plane with the mirror tool
Break some blocks/bricks. The number of blocks you need to break varies from one time to another. Sometimes it happens on the first few breaks, sometimes you can be building for 10 minutes with no problem before it strikes

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 1050M

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3976221/output_log.txt)

**Comment by ExodistSKY1** [comment]
This also occurs at times when painting: so far thrusters and lights have caused this but it is intermittent.

As far as mirror mode, when I break a block that does not have a corresponding block mirrored to it, that will create this bug

**Comment by tsunamayo** [comment]
Okay this bug should have been fixed. Thanks for reporting it! Will be in xmas build. Cheers!
