### ISSUE TITLE
[BUG] Control mapping menu overlaps

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1530]
### Short Description of the issue:
As you can see, all the options to remap your keys in the new GUI are overlapping, making it troublesome to use
![image](https://user-images.githubusercontent.com/27857711/71129946-938f6900-21e8-11ea-9557-857935803ec7.png)

### Steps to reproduce the issue:
Open the control mapping menu

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Okay issue is fixed. Cheers

**Comment by tsunamayo** [comment]
Will be in 20w02b or later!
