### ISSUE TITLE
[Suggestion] Reduce brick mass

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1532]
Just a quick suggestion following up this months (awesome) Kickstarter update. Currently bricks are 14.2 times denser than blocks which is far, far too much. I understand that their current mass was probably just a placeholder value but with brick thrusters and surface area heating - which sounds amazing by the way, - this very large mass is even more detrimental to brick performance. 

To bring them more in line with blocks I'd suggest giving them a similar density stat, so 1m^3 of block has a similar mass as 1m^3 of bricks. This does not make bricks more powerful than blocks so large brick ships won't be better than large block ships causing lag issues.

As blocks currently have a density of 9kg/m^3, a single brick (25cm^3) would need a mass of 0.0703125kg to have the same density as a block. This isn't a very friendly number, so perhaps we could round it up to 0.08kg. This means that bricks will have a density of 10.24kg/m^3, a much better alternative to the current 128kg/m^3 value and closer to the 9kg/m^3 of blocks.

Using this new mass of 0.08kg for each 25cm cube, bricks will actually still be marginally heavier than blocks meaning that players are actively discouraged to build large brick ships as they will be heavier than a comparable block ship.

As a side note, currently all shapes have the same mass meaning tetras, slopes and all other shapes weigh much more than they should. I imagine this is just a temporary thing but it'd be great to have their mass be more accurate to help balance ships.

Looking forward to hearing everyone's opinions!

**Comment by ExodistSKY1** [comment]
I like the simplicity behind it. Its simple to implement, scales with the size of ship and will softly push builders to choose blocks over bricks if possible. 

This including the new heat system implemented could possibly make smaller ships actually viable!

**Comment by AfterRebelion** [comment]
One thing to consider is not only density per block, but also related to volume.
When someone builds a ship, the outline can be as low as just one block or brick.

**So one example here:**
One ship with dimensions 10 x 5 x 20, 1000m3 total.

With one block outline, 568 blocks, at 9kg each it adds to 5112kg
With one brick outline, 10.648 bricks, at 0.08kg each it adds to 851,84kg

So 6 times more massive with blocks, with the same surface area covered.

Of course, this is only talking about mass, there are others things that can make bricks inviable for that 20m shuttle, like the fact that right now bricks don't dissipate heat.

[20m Shuttle Mass testing.zip](https://github.com/tsunamayo/Skywanderers/files/4022545/20m.Shuttle.Mass.testing.zip)

**Comment by tsunamayo** [comment]
Yes I will tweak value more now. I have increase hull mass a bit, but I want brick to still be quite heavy compared to hull. Hull are hollow, there is a lot of empty space inside ;)
We will tweak everything once I get more blueprint to get a better idea on how things fits together - do small figther needs more speed and maniability compared to larger one? ect ect

**Comment by tsunamayo** [comment]
Okay we now have a new mechanism to make brick more interesting, please see #1571 for feedback.
Thanks!
