### ISSUE TITLE
[BUG] Double Menu Interface

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1536]
I think the picture explains it quite well
![image](https://user-images.githubusercontent.com/36980446/72025626-f5665000-3235-11ea-9f38-f1ded9d1dd38.png)

**Comment by ProPeach** [comment]
Looks like the same issue as #1530

**Comment by tsunamayo** [comment]
Okay issue is fixed. Thanks for testing out the new build! cheers

**Comment by tsunamayo** [comment]
Will be in 20w02b or later!
