### ISSUE TITLE
Return of the Mirror bug

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1538]
### Short Description of the issue:
After a prolonged time of using the mirror I'm getting the same issues that we all have been in the previous mirror bugs. Such as randomly not being able to break or place blocks.
...

### Environment
- Skywanderers version: 20w02a
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4039435/output_log.txt)

**Comment by ProPeach** [comment]
#1529

**Comment by tsunamayo** [comment]
Okay cool I fixed that one too, to be available in 20w03a. It was  when working on a chunk that was only existing on one side. Thanks for being so active!
