### ISSUE TITLE
[BUG] Heat Dissipation and Heat Generation are backwards

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1539]
### Short Description of the issue:
In the ship info section, Heat Dissipated represents the ammount of heat generated, and Heat Generated the heat you dissipate.
### Steps to reproduce the issue:

1. Create a ship
2. Add blocks to any of it's axis, so that volume of the ship increases.
3. Observe as the stat that increases is Heat Generated.

### Environment
- Skywanderers version: 20w02a
- Graphics Card: AMD RX 580

**Comment by tsunamayo** [comment]
Thanks indeed, I just made the fix. What do you think of the new stats display widget? Is there any stats you would like to see? Cheers

**Comment by ExodistSKY1** [comment]
Something I would like to see in the future would be stats for weapon systems on the ship and if possible stats for turrets

**Comment by tsunamayo** [comment]
Yes I have a tab and weapon icon already made, I just need to big weapon update.
Also for more detailed stats you will check the turret / own weapon tab.

**Comment by ExodistSKY1** [comment]
AWESOME!!!  Truly loving the update you pushed! I think balancing should wait until everything you would like to be in game is in as that would give everyone a better idea on what should be changed

**Comment by AfterRebelion** [comment]
Fixed in 20w02b
