### ISSUE TITLE
Firing guided missiles while flying too fast sometimes hit your own ship

### ISSUE THREAD

**Issue by PsyCommando** [tsunamayo/Skywanderers#154]
I was flying fairly fast in 3rd person, in HYP mode, and fired some missiles, and everything seemed fine, until at one point most of the launchers and wings just vanished just as I was firing some more missiles.

**Comment by tsunamayo** [comment]
Thanks, this is well known issue :-) ... It will be fixed, I will keep you posted.

**Comment by PsyCommando** [comment]
Alright!

**Comment by tsunamayo** [comment]
Alright issue was fixed - it might needs a bit of tweaking for each different kind of projectile as we continue testing. Cheers
