### ISSUE TITLE
[BUG] Middle Click 'Align to Entity' Function is broken

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1541]
### Short Description of the issue:
When attempting to realign the character via the middle click menu it doesn't work. Along with this issue, the icon for it is also missing and is replaced with a white box as pictured below.
![alignissue](https://user-images.githubusercontent.com/53021785/72092639-f8158380-32cf-11ea-8e5b-c7b5f661967a.png)
This issue persists on all movement modes
...

### Steps to reproduce the issue:
1) Un align yourself with something
2) Middle-click and attempt to realign the character
3) ...
4) Issue

...

### Environment
- Skywanderers version: 20w02a
- Graphics Card: 
	AMD Radeon(TM) RX Vega 11 Graphics

	Driver version:	24.20.11016.4
	Driver date:	2018-05-16
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 56, device 0, function 0

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4041831/output_log.txt)

**Comment by tsunamayo** [comment]
Okay so this function has been removed from the game, it was my plan for a long time. The new locomotion mode replace this - now the player automatically align to the current gravity field except for the 6-dof mode where he gets full control.
I clean that screen though as it was not up-to-date.
Thanks a lot!
