### ISSUE TITLE
[Bug] Sliding on Ringworld Terrain [20w02a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1542]
### Short Description of the issue:
The ringworld surface has very little friction, so if you stand on a hill you eventually slide down it.

### Steps to reproduce the issue:
Stand on ringworld, then wait a while. It's very slow, so I didn't notice it until I'd been AFK for about 10 minutes and came back to find myself downhill from where I was.

### Environment
- Skywanderers version: 20w02a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The ringworlds look _**freakin' awesome!**_

![20200109150011_1](https://user-images.githubusercontent.com/33041786/72106075-548a9a00-32f4-11ea-8b8a-34c30fb41199.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/4042574/output_log.zip)

**Comment by tsunamayo** [comment]
Yes indeed there is no friction for the player body yet. But there is friction for the other rigidbody, you can spawn my little physics debugging box with F6 to check it out!
I keep you posted when I fix this.
Cheers

**Comment by tsunamayo** [comment]
Okay it was fixed in 20w04a! Thanks
