### ISSUE TITLE
[Bug] Building drone cannot fly

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1543]
### Short Description of the issue:
The F5 building drone stays stationary when you spawn it in space, and the poor guy can't fly in gravity and falls on his face. It might need thrusters now
![image](https://user-images.githubusercontent.com/27857711/72106930-3a6aaf00-3328-11ea-894d-a62a7354fd9a.png)

### Steps to reproduce the issue:
Spawn the building drone with F5 in space, and on the ring. Notice how it can't move
...

### Environment
- Skywanderers version: 20w02a
- Graphics Card: RX 580

**Comment by Dwarf-LordPangolin** [comment]
Go home FR-3N, you're drunk.
![20200109154629_1](https://user-images.githubusercontent.com/33041786/72107683-75082380-32f7-11ea-993c-1e3d5e2872c9.jpg)


As an addendum, if the drone is spawned too close to the ringworld's surface, the collision between the drone and the ground yeets the drone into orbit. At first I thought the drone wasn't spawning, until I saw a flicker right after pressing F5, and looked up to see him vanishing into the distance.

**Comment by tsunamayo** [comment]
Yes - unfortunately I will have to kill that sucker for the release...
Too much issues, I think it gets in the way of the experience a bit...
The plan is to get the same menu as an additional Tabs called "Shipyard Services" at, you guessed it, shipyard (my inital plan was to have drone only at shipyard - no F5 to spawn a drone).
But I want them back for immersion / fun purpose, so I will spawn a mini fleet of maintenance drone that will work on your ship, so this way I dont have collision issue ect.
Cheers
