### ISSUE TITLE
[Bug] Save>Exit to Title>Reload Black Screen [20w02a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1544]
### Short Description of the issue:
Saving, exiting to menu, then reloading causes a black screen.

### Steps to reproduce the issue:
Save the game, exit to the menu, then reload the save. The game will show a black screen. Sometimes the version number in the upper left corner will show a different value. Interestingly, sometimes the black screen can be gotten out of by using F7 to teleport elsewhere, but this does not always remove the black screen.

### Environment
- Skywanderers version: 20w02a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200109210801_1](https://user-images.githubusercontent.com/33041786/72123120-e8288e80-3325-11ea-86df-2611b427808c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4043771/output_log.txt)

**Comment by tsunamayo** [comment]
Okay thanks indeed, this get broken easily. It is now fixed, for 20w03a. Cheers!
