### ISSUE TITLE
[Suggestion] Larger ship gravity fields

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1546]
Would it be possible to increase the max size of the current gravity generator? For larger ships it may get tedious to place a bunch of these all over the ship to make sure your interior has proper gravity. Or could there be new gravity generator that affects 'x' size depending on how big the generator itself is? The dragging could work like the new repulsors where as you drag it, the whole model gets proportionally larger. So lets say a simple 1m version could support a ship with a max size of 50m, 2m could be 75m, etc. (Can obviously be more complex as needed) The difference between this one and the current gravity generator might be power consumption and heat since larger ships can take advantage of the outer surface area calculations more so than smaller ships.

-Here is my current WIP of a smoother sphere (250m diameter)-
![20200110085650_1](https://user-images.githubusercontent.com/32974671/72162225-2904bf80-3387-11ea-9412-8100e7402934.jpg)

Loving all of the new and returning content in these recent updates tsuna, keep up the good work!

**Comment by tsunamayo** [comment]
Hum I am not sure on that one, let see how it turn out with normal ship as a 250m spherical station is not the standard things I guess (and yes making very large ship / station is gonna be tedious anyway ;) )

**Comment by ZachZent** [comment]
A larger gravity gen is very much needed. Yes the bol isn't exactly standard, but standard larger ships that are 200+ meters would require many grav gens. ~13 for the length of the 200m ship alone. Then add width and height and you may have to put down around 50 just to cover most of the ship. 16x16x16 will not cut it. A gravity block that encompasses the enough ship all at once, something something bounding boxes, for an amount of power would solve this problem while keeping the current grav gens for more special gravity projects. For example...
https://cdn.discordapp.com/attachments/416013956331601930/664956980213055509/Skywanderers_2020-01-09_15-20-58.mp4
A gravity jail cell. I just don't want to go around my ship spamming these just to be able to walk

**Comment by tsunamayo** [comment]
What I dont get is that, yes, you have to put blocks to get a functional ship. How many light you have to place in a 200m ship? A thousand? I had like a 100 on my old 40m ship. What I agree is the design actually suck and wont look good in most interior, so I am thinking in moving it to a smaller format like the jump-pad. 
But as I add more gameplay it will take more and more effort to make a truly functional ship, I dont see it as a bad thing.

With the current tech I cant really make the box any larger, it has some performance issue the game  would lag when you put it down. I would have to do a new dev, not sure I will have the time.
Thanks for the discussion!

**Comment by tsunamayo** [comment]
By the way that gravity jail cell is such an amazing idea, is it yours? Thanks

**Comment by tsunamayo** [comment]
I made smaller and more fitting gravity block, it should be less intrusive to fit in your design. Thanks!
