### ISSUE TITLE
Children Entity collision Issue.

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1547]
### Short Description of the issue:
The new blast doors have no collisions whether open or closed. Closed should 100% have collisions but having the open door able to have entities go through it could be a cool feature, unless you'd rather these be used for interior purposes.
...

### Environment
- Skywanderers version: 20w02b
- Graphics Card: GTX 970

### Additional information:
![20200110090602_1](https://user-images.githubusercontent.com/32974671/72163067-b8f73900-3388-11ea-900c-e897699680e1.jpg)
![20200110090514_1](https://user-images.githubusercontent.com/32974671/72163070-bac0fc80-3388-11ea-9444-127190c1b267.jpg)

**Comment by tsunamayo** [comment]
I dont think it is a blast door issue, it is actually a children entity issue one. I need to take a big look at this, I will keep you posted! Thanks for reporting this.

**Comment by tsunamayo** [comment]
So I had a go with all the recent children entity improvements, and this case is now working as expected. Thanks!
