### ISSUE TITLE
[BUG] Ship Shakes Violently when Flying

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1549]
### Short Description of the issue:
One of my ships that I finished updating to fly with the new system shakes rapidly up and down when I take control of it. Not sure if anyone else has had this problem but here is the video of what I'm talking about. 

https://streamable.com/fclkb

Interestingly enough it was flying ok when I only had a few side thrusters on it so that may be linked to the issue.

EDIT: Exodist tried loading up my shaky ship and didn't find any issues so the problem is likely not with the ship but more the client. We then attempted to fix it by saving a non-shaky version on Exodist's client and loading it up on my own which did not solve the issue sadly.

...

### Steps to reproduce the issue:
Might just be this specific ship in question but
1) Load a ship
2) Fly it
3) ...
4) Issue

### Environment
- Skywanderers version: 20w02b
- Graphics Card: 
	AMD Radeon(TM) RX Vega 11 Graphics

	Driver version:	24.20.11016.4
	Driver date:	2018-05-16
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 56, device 0, function 0

### Additional information:

This is the ship in question
![Skywanderers 2020-01-10 2_13_25 PM](https://user-images.githubusercontent.com/53021785/72186850-697a3280-33b3-11ea-813d-093b2edf01cc.png)

[AC16 Atlus.zip](https://github.com/tsunamayo/Skywanderers/files/4047996/AC16.Atlus.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4048001/output_log.txt)

**Comment by ExodistSKY1** [comment]
I loaded in Aiwii's ship and was able to fly it perfectly fine with no vibration. 

Also, I started to have this bug on one of my ships. I deleted all of the thrusters and added new ones and the vibrations stopped.

**Comment by tsunamayo** [comment]
Okay I have made some change that should prevent the jittering at high agility rating, even if I didnt reproduced the bug I guess it was the root cause (it might depends on your frame rate also)
Thanks!
