### ISSUE TITLE
[Bug] Cannot repair or delete blocks [20w02b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1550]
### Short Description of the issue:
Some blocks that have been damaged cannot be repaired, and thus cannot be deleted.

### Steps to reproduce the issue:
Can't reproduce yet, since I'm not sure precisely how this happened in the first place, so I've included the blueprint in question.

While trying to change the front of the ship, I found some blocks that said they were damaged; however, after deleting all the blocks around them, I couldn't find any damage decals on them. Hitting them with the repair tool from all angles didn't solve the issue either. The affected blocks are at the front end of the ship, and have been painted bright pink to make them easier to find. I suspect they were damaged by the ship's own weapons; don't know if that's significant.

[100m Combat Ship Prototype [Bugged].zip](https://github.com/tsunamayo/Skywanderers/files/4048992/100m.Combat.Ship.Prototype.Bugged.zip)

### Environment
- Skywanderers version: [20w02b]
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200110224717_1](https://user-images.githubusercontent.com/33041786/72199056-f5b04800-33fb-11ea-86c1-fba42e5a5a4c.jpg)

![20200110225240_1](https://user-images.githubusercontent.com/33041786/72199058-f8ab3880-33fb-11ea-828b-f33cb8d6106c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4048986/output_log.txt)

**Comment by ExodistSKY1** [comment]
A workaround I found for this:
    
      - Use multi-tool to break the barrier of the destroyed block
      - shoot the repair tool
      - It should push you out and the block should be partly repaired.
      - From there it should be normal now and you should be able to repair all the way

**Comment by Dwarf-LordPangolin** [comment]
Thank you!! I couldn't quite get that exact method to work (not sure what the "barrier" is), but a slightly modified version worked. The block seemed to think it was fully repaired, but kept insisting it needed repairs. So I shot it with a fighter, then repaired it. Repairing the new damage seemed to reset whatever the bug was concerning the earlier damage, and let me delete it.

**Comment by ExodistSKY1** [comment]
"(not sure what the "barrier" is)"  I apologize I should have been clearer:   What I mean by "barrier" is the green areas indicating where the damage is while having the repair tool selected

**Comment by tsunamayo** [comment]
Okay I fixed this issue, it should check for any mismatch and patch itself on blueprint load. Thanks!
