### ISSUE TITLE
Can't change vector in hyperspeed mode

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Skywanderers#1551]
Even with a sideways main engine, hyperspeed locks you in one vector no matter what direction you are facing after you engage the mode. To adjust course you have to disengage, aim, and re-engage. Is this intentional?

**Comment by tsunamayo** [comment]
No it is not! Thanks for reporting the issue, I am working on it.

**Comment by Starwhip** [comment]
I noticed that you actually can steer in hyperspeed, but not in 3rd person mode. First person works just fine, 3rd person mode will rotate the ship but you keep going along your original vector.

**Comment by tsunamayo** [comment]
Okay I fixed the issue. Will be available in upcoming patch 20w02c. (likely today) Thanks!
