### ISSUE TITLE
[BUG] Landing on docking pads is broken [20w02b]

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1554]
Landing on both the station docking pads and the pads you can place via the pick up block tool are broken 

-The stations will put your ship in a perpetual bounce until you exit the craft
-The pads you can place will allow you to dock but you are not "landed" see reference screenshots.
...

Land on any docking station.

...

### Environment
- Skywanderers version: 20w02b
- Graphics Card: GTX 1080ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4049973/output_log.txt)

![20200111160933_1](https://user-images.githubusercontent.com/45324484/72211287-62742280-348e-11ea-9e54-fcf12f3cb0c6.jpg)
![20200111160944_1](https://user-images.githubusercontent.com/45324484/72211288-62742280-348e-11ea-9306-c86fff19aa9e.jpg)
![20200111161115_1](https://user-images.githubusercontent.com/45324484/72211289-62742280-348e-11ea-8e48-986a6163f70c.jpg)
![20200111161116_1](https://user-images.githubusercontent.com/45324484/72211290-62742280-348e-11ea-96ca-16fdf98a3f37.jpg)
![20200111161119_1](https://user-images.githubusercontent.com/45324484/72211291-62742280-348e-11ea-8e27-e47745e5ca6c.jpg)

**Comment by tsunamayo** [comment]
The bug is that you should not be able to pick them, they are made to work with a shipyard.
I will keep you posted, in the meantime I think you better remove them!
Cheers

**Comment by tsunamayo** [comment]
Okay I fixed the issue, now you cant pick up shipyard or block you dont see in the codex. I will add back docking of course though!
Cheers
