### ISSUE TITLE
[BUG] Grass renders in stripes along patch centers

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1559]
### Short Description of the issue:
![20200113145856_1](https://user-images.githubusercontent.com/559819/72261634-7b5b1000-3615-11ea-8639-559e340d987a.jpg)

### Steps to reproduce the issue:
1. Get near a habitat
2. Open F3 menu to enable "View props patch center" (Also to disable rock rendering, since this seems related to https://github.com/tsunamayo/Skywanderers/issues/1537)
3. View as grass is exactly rendered in lines from those red points.

### Environment
- Skywanderers version: 20w02c
- Graphics Card: AMD RX 580

### Additional information:

[2020.01.13-15.11.mp4.zip](https://github.com/tsunamayo/Skywanderers/files/4053957/2020.01.13-15.11.mp4.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4053960/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks thats usefull! Indeed it seems there is some issue with scale and placing on AMD, this should have the same root cause as #1537. I will keep you posted, thanks!

**Comment by AfterRebelion** [comment]
Same as https://github.com/tsunamayo/Skywanderers/issues/1537 , seems fixed now.
