### ISSUE TITLE
Logic circuit multiplying signals

### ISSUE THREAD

**Issue by PsyCommando** [tsunamayo/Skywanderers#156]
If you link a mouse input part to a clock circuit (NOT gate 's input and output tied to a delay gate output and input) each time you'll press the mouse button an extra "signal" will be created and the clock will start ticking erratically because there's more than one signal in the circuit. Its like some sort of feedback loop..
I don't know if its by design or a bug, but I thought I should mention it, because there's currently no way to purge a circuit like that from those rogue signals.

**Comment by tsunamayo** [comment]
Okay nice spot indeed, this is not specific to a mouse input and can be reproduce with any signal. I need to wrap my head a bit around that, on the best way to prevent it as I cannot let player do that. I guess I will simply prevent the delay from accepting an input if it already received one before its period is over.

**Comment by Cec00** [comment]
I'm having difficulties with the logical components:
The button doesn't seem to give a impulse signal I mean: once pushed for the first time it gives a continuous 1 signal and I suppose that pushing it again will give a small 0 input but, 
if you connect a NOT gate and try to push the button to have a 1 input it does not work.

When you start and stop a 1 signal on a NOT gate, OR gate or an AND gate, with a switch or a button the system seems to retain the signal on the input pins of the gates and it doesn't go back to 0 after stopped, it doesn't change the status even if you brake the Switch. The only way to put it back on 0 is to connect a new switch on it and put it back on 0 or replace the gate and reconnect all the pins.

Is this part of the same bug?
if you need I'll post images of the circuits I've been making (I was trying to design a machine gun with laser and logic gates)
and by the way: the delay gate works perfeclty

**Comment by tsunamayo** [comment]
Button will always send 1. If you want to flip flop between 0 and 1, you need to use a switch.
What do you mean start and stop?
 In the game you only send impulse, and the signal propagate instantly along with a given value between 0 and 1 - this might be a bit confusing at first, but you can always send 0 or 1 it will work the same as binary system.
There is no stopping a signal I am afraid (although you can filter it with a router command). 
Please post anything, but maybe the forum is a better place as other tester are also likely to help you!
Thanks

**Comment by tsunamayo** [comment]
Okay I did the fix. Thanks a lot!
