### ISSUE TITLE
[Suggestion] Engine, cruise, and warp adjustments

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1562]
The current engine system is that placing block engines will allow you to cruise (I know that is not the name, but the naming scheme has been quite liquid so for simplicity sake cruise will be the name) while just brick engines alone limits you to normal flight. This works but is rather annoying for people building smaller ships who just want to travel intersystem. Especially for players who just built their first ship and want to leave their staring planet but not want to spend half an hour just to get to the next closest one. Instead, let me suggest an alternative system.

•	Warp requires…
      o	Warp core
      o	Block engines
•	Cruise requires…
      o	Cruise core (brick)
      o	Any engine

This allows small ships that may not have the space for block engines to have the freedom to fly intersystem without needing a larger carrier just to travel from planet to planet. Intrasystem rather would require a comparatively larger ship with enough block engines, a warp core, and enough power which makes much more sense. It also adds an element of progression. Starting with a starship that can fly around the starting planet to unlocking the entire star system to unlocking the galaxy. Balances can be added for the number of engines versus weight equaling max cruise speed.

**Comment by ExodistSKY1** [comment]
I like the idea, especially the stepping stone for game play reasons.

**Comment by tsunamayo** [comment]
So yes after various try I settled on Lightcruise drive for the planet drive!
I just dont like the idea of having a 1m wide scooter being able to zap through planets...
I have seen a lot of small fighters, they all manage to squeeze several thrusters block before the mini-one was there. I think the goblin had 4, and that was a really tiny craft. 
Now you will only have to have a single one for limited space travel, that seems fair!

Also I dont see player starting with a figther, they will start with a shuttle like craft.

**Comment by ZachZent** [comment]
I guess that makes sense, though seeing a scooter flying at lightcruse speed would be funny.

One more thing about flying though, it was suggested in the Discord that you would have to be flying at lightcruise to enter warp (or name equivalent) rather then pop to another system from a standstill

**Comment by ExodistSKY1** [comment]
I have to agree, seeing a scooter zoom in and out would be the unwanted annoying meta that would come from it. I did not think that deeply into it.  

I agree that a single block thruster for limited space travel does seem fair.

**Comment by Aiwii** [comment]
It's not even that much of a sacrifice so I'll accept it

**Comment by tsunamayo** [comment]
Okay great I manage to convince you for once ;)
