### ISSUE TITLE
[Bug] Typo in Codex [20w02c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1565]
### Short Description of the issue:
"Mecanisms" should be "Mechanisms."

### Environment
- Skywanderers version: 20w02c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200116145916_1](https://user-images.githubusercontent.com/33041786/72562690-9b870b00-3871-11ea-94db-211c2e69f8ca.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4073774/output_log.txt)

**Comment by tsunamayo** [comment]
You are right! It is correct ;)
