### ISSUE TITLE
[Bug] Mirror De-sync

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1566]
### Short Description of the issue:
Mirror places block/bricks one block in the past. https://streamable.com/0fbwr 
It seems pretty random and it eventually fixed itself as shown in the video.
...

### Steps to reproduce the issue:
- Use mirror
- ???
- Issue

Not really sure how to reproduce the issue yet. Hopefully, someone else figures it out. Kinda just happened randomly for me.
...

### Environment
- Skywanderers version: 20w02c
- Graphics Card: AMD Radeon(TM) RX Vega 11 Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4081787/output_log.txt)

**Comment by ExodistSKY1** [comment]
to add to the steps to reproduce 

    - in mirror mode, place bricks within a few blocks of the mirrored line
    - This should reproduce the issue

**Comment by tsunamayo** [comment]
This issue should now be fixed. Thanks!
