### ISSUE TITLE
Suggestion: Highlight the stud you're looking at when placing parts

### ISSUE THREAD

**Issue by PsyCommando** [tsunamayo/Skywanderers#157]
Since the current system will let you clip bricks it becomes hard to tell what stud you're interacting with. Highlighting the one you're "using"/looking at in red or yellow or something else for example could really help avoiding to hold the right mouse all the time to place something.

**Comment by tsunamayo** [comment]
Hello, nice suggestion indeed - I think I will add that. Are you having trouble with multi-stud bricks?

**Comment by PsyCommando** [comment]
Thanks! And nope, Its just that sometimes I'll build something out of bricks and I'd hear the brick placement sound and the brick would end up being placed inside an existing brick, or on some hidden part on the other side of the spaceship ^^;

**Comment by tsunamayo** [comment]
I fixed the bug you where referring to - and now targeted stud is displayed in red. I still want to do another pass to improve the look of studs but that will do it for now. Cheers
