### ISSUE TITLE
[Bug] Block highlight depends on range/angle [20w02c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1570]
### Short Description of the issue:
Blocks cannot be highlighted for placement/deletion unless at the right angle or range.

### Steps to reproduce the issue:
Not sure yet what causes this, but at some point the game stops being able to tell when you're highlighting a block with the crosshair. You need to move from side to side to get to the right angle, and move back and forth to get the right range, in order to get the game to correctly allow placement/deletion. The problem seems to come and go.

### Environment
- Skywanderers version: 20w02c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Wrong angle:
![20200123180423_1](https://user-images.githubusercontent.com/33041786/73034899-f4bfe300-3e0b-11ea-86c9-cb8600ce0c16.jpg)

Right angle:
![20200123180418_1](https://user-images.githubusercontent.com/33041786/73034903-f689a680-3e0b-11ea-9c12-db0c264b951c.jpg)

Wrong angle:
![20200116211234_1](https://user-images.githubusercontent.com/33041786/73034960-29cc3580-3e0c-11ea-9633-03d7e4460ffe.jpg)

Right angle:
![20200116211236_1](https://user-images.githubusercontent.com/33041786/73034953-23d65480-3e0c-11ea-944b-14622414172c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4106238/output_log.txt)

**Comment by tsunamayo** [comment]
Once it start happening, does it happens all the time? Or just at a few selected place. Also Did you build for a long time before it happens? I cant reproduce, so it is difficult for me to fix!
Thanks

**Comment by Dwarf-LordPangolin** [comment]
It seems to happen most of the time in most places on most ships. There's some variability to it, but once it started, it has never gone away. The only reliable way to get around it is to move the player's head very close to what you're trying to highlight. I can't remember, but I don't think I'd been building for a terribly long time prior to it happening.

**Comment by tsunamayo** [comment]
Okay I think I have been able to fix the issue. It was linked to some Unity physics bug, but I was able to work around that. Tell me in case you still see this in 20w05a. Thanks!
