### ISSUE TITLE
Placing capacitors on stretched shield generators is fiddly 

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1573]
When trying to place capacitors on stretched shield generators (larger than 1x1x1), the placement of the capacitors doesn't match the cross-hair: 
![image](https://user-images.githubusercontent.com/29961381/73079913-e087ee80-3ebc-11ea-9c72-3f252c3dbb76.png)

**Comment by tsunamayo** [comment]
Okay I was able to reproduce also - issue will be fixed for 20w04b or later. Thanks!
