### ISSUE TITLE
The New Anti-Recoil Barrel have no animation for it's "texture spots" 

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Skywanderers#1574]
The newly added anti-recoil barrel have no animation of it's "texture spots"/grain when it fire / slide

...

Put the specific barrel on a laser base and every time you fire you can see it

...

### Environment
- Skywanderers version: latest update (20w04a)
- Graphics Card: Geforce 1160 ti

### Additional information:

![Skywandere gun](https://user-images.githubusercontent.com/33103748/73080174-b38c0980-3ec5-11ea-8447-470b25a8229a.png)

**Comment by tsunamayo** [comment]
Nice catch, should be an easy fix.

**Comment by tsunamayo** [comment]
Okay it will be fixed in 20w04b or later. Thanks!
