### ISSUE TITLE
[Bug] Incorrect labeling on the laser GUI

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1575]
### Short Description of the issue:
Just a quick one, "Heat Generated" and "Heat Generated per Second" should be "Heat Damage" and "Heat Damage per Second" to prevent confusion
...

### Steps to reproduce the issue:
Place a laser block, look at the GUI

### Environment
- Skywanderers version: 20w04a
- Graphics Card: RX 580

![image](https://user-images.githubusercontent.com/27857711/73080885-75d7b280-3ebe-11ea-96ae-4ae6993c8d5f.png)

**Comment by tsunamayo** [comment]
Yes you are 100% right, it is now fixed!  Cheers
