### ISSUE TITLE
[Bug] Kickback stat does not update in laser GUI

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1576]
### Short Description of the issue:
The Self Force Kickback statistic does not update in the laser GUI when you add an Anti Recoil Barrel to your laser. The actual stat of the gun does change as the barrel reduces recoil as intended, but the GUI does not reflect that.

Also, can I suggest you change the Self Force Kickback statistic to just "Recoil Force?" It's a little more intuitive and easier to say and type.
...

### Steps to reproduce the issue:
Place a laser and check the Kickback statistic
Place an Anti-Recoil Barrel on the laser and check the stat again
...

### Environment
- Skywanderers version: 20w04a
- Graphics Card: RX 580

### Additional information:
With Anti-Recoil
![image](https://user-images.githubusercontent.com/27857711/73082365-3fe7fd80-3ec1-11ea-83a9-783fd655b666.png)

Without Anti-Recoil
![image](https://user-images.githubusercontent.com/27857711/73082380-47a7a200-3ec1-11ea-8272-99fc3623f4fd.png)

**Comment by tsunamayo** [comment]
Yes indeed it was showing the force damage and not recoil, It is now fixed!  
It is now called recoil force. Force kick-back is call Impact force, hope it make sense!
It is a bit painfull having that force btw, and it procude too much result on smaller ship, and no result at all on larger one, so I guess I will give up on that and find a new usage for the recoil addon...
If you have any suggestion (I have a few ideas)
Cheers

**Comment by ProPeach** [comment]
That does make more sense, thank you!
Is it painful in terms of code? I can see the recoil addon being much more useful on a hovercraft than a ship as the hovercraft will rock back and forth with the power of each shot, maybe even flip your hovercraft if you're not careful with where you place your thrusters. It might also be useful in a mech later down the line for the same reasons.
I do agree that it's a very niche barrel right now though, maybe it just needs to wait for it's time to shine.
