### ISSUE TITLE
[Bug] Large FPS loss when using auto turrets [20w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1577]
### Short Description of the issue:
Controlling a ship with auto-targeting turrets brings FPS from ~70 to ~30 or lower.

### Steps to reproduce the issue:
Spawn ship with turrets, with the turret core set up to use auto targeting, then take control of the ship. Additionally, the turrets will not fire on anything like this, and instead follow where the player is looking.

### Environment
- Skywanderers version: 20w04a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4111322/output_log.txt)

**Comment by tsunamayo** [comment]
I see, you get a big collision issue. Could you send me your blueprint so I can check, I need to improve that. And tell me which turret is it if it is hard to find ;)
Cheers

**Comment by Dwarf-LordPangolin** [comment]
I think it might actually be _all_ the turrets; they should be pretty easy to spot. Here's the blueprint:
[Tempest-Class Destroyer Mk. I.zip](https://github.com/tsunamayo/Skywanderers/files/4111610/Tempest-Class.Destroyer.Mk.I.zip)


Also: you'd asked me earlier to send you a blueprint with a 2m interior so you could take another look at it. This one has a 2m interior, and it should give you a good idea of what I was talking about.

I haven't finished gutting the interior on this one to get it ready for testing purposes, so it's got a lot more bricks and other detailing than it will have when I send it to you for testing. I'd been using this blueprint to practice making ships look spiffy for later, so don't worry; the stuff I send you for testing won't have anywhere near as much detailing. :+1:

**Comment by tsunamayo** [comment]
That issue should be fixed in latest 20w06a patch. FPS will still drop a bit though, I might need to code a fast turret collision system (with baked max angle) to get better fps though, we will see how it goes!
Cheers, and massive thanks for being so active!
