### ISSUE TITLE
breaking control sticks.

### ISSUE THREAD

**Issue by ThatGenericName** [tsunamayo/Skywanderers#158]
when controlling a ship, if you break your control stick while still operating the ship. You will be unable to stop controlling the ship even if you leave the control seat.

**Comment by tsunamayo** [comment]
Hello. Can I ask you how did you break the control? You just delete it with the mouse control?
Thanks!

**Comment by ThatGenericName** [comment]
yes, I was using LMB to accelerate the Banshee while in 3rd person and managed to destroy the controls by accident.

**Comment by tsunamayo** [comment]
Okay you should not be able to destroy brick while flying, if you recall any special thing you did or that happens I would very much ear them to be able to reproduce. Thanks!

**Comment by tsunamayo** [comment]
Okay this issue should be fixed now! Cheers
