### ISSUE TITLE
[Bug] Deleting Laser Unit with Barrel can leave phantom barrel [20w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1580]
### Short Description of the issue:
Deleting and replacing a laser unit does not always properly delete attached barrels.

### Steps to reproduce the issue:
Place a laser unit, give it a barrel, then delete the unit. Place a new unit that ends (barrel end) in the same place and alignment as the old one.

### Environment
- Skywanderers version: 20w04a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200125040517_1](https://user-images.githubusercontent.com/33041786/73119491-55dcd900-3f28-11ea-94c0-6e4827d8cc43.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4111903/output_log.txt)

**Comment by tsunamayo** [comment]
I cant reproduce. Do you manage to reproduce with any barrel or a specific one? Thanks!

**Comment by Dwarf-LordPangolin** [comment]
So I have no idea why it happens when it does, but I wasn't able to reproduce it, and then it just happened again. So far it's just been the gatling barrel. This time I exported the blueprint. It doesn't appear distorted like that after saving and reloading, but the BP might be able to tell you what's going on. It's the WIP turret on the topside, shown here. 
![20200128013145_1](https://user-images.githubusercontent.com/33041786/73243993-857d2280-416e-11ea-87b7-952ad19aac7a.jpg)

Blueprint:
[Frigate Prototype.zip](https://github.com/tsunamayo/Skywanderers/files/4121135/Frigate.Prototype.zip)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4121124/output_log.txt)

**Comment by tsunamayo** [comment]
Okay indeed I can see the issue. For some reason the barrel was not destroyed once when this laser was removed, which is the real issue. If you understand how you reproduce this one please tell me, as I cant seems to reproduce. Did you used mirroring? The fact of it being flat is not really the problem, it is should simply not be there at the first place!
Thanks!

**Comment by tsunamayo** [comment]
I think it might have been linked to mirroring in a way, as your turret is mirrored. I fixed a few issue with mirroring and addon block that should have explained this.
 Cheers
