### ISSUE TITLE
[BUG] Destroying a Child Entity with Grand Child Entity Breaks Lighting

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1581]
### Short Description of the issue:
Destroying a Child Entity that has Grand Children Entities and Great Grand Children Entities breaks the game lighting and some rendering. https://streamable.com/nujso
![Skywanderers 2020-01-25 2_15_18 PM](https://user-images.githubusercontent.com/53021785/73127422-34f2a300-3f7d-11ea-9a0d-99bbc7013124.png)
![Skywanderers 2020-01-25 2_15_05 PM](https://user-images.githubusercontent.com/53021785/73127423-34f2a300-3f7d-11ea-8fd0-7bdfd9bfe824.png)

### Steps to reproduce the issue:
1. Create a Child Entity
2. Create a Child Entity on the previously stated Child Entity
3. Create a Child Entity on the previously stated Child Entity
4. Break the main Child Entity
5. ...
6. Issue

...

### Environment
- Skywanderers version: 20w04a
- Graphics Card: AMD Radeon(TM) RX Vega 11 Graphics

### Additional information:
Github Won't let me upload my output log as is, sorry that it zipped up
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/4112836/output_log.zip)

**Comment by tsunamayo** [comment]
Okay thanks for reporting that one. It will be fixed in next update 20w05a.
Cheers
