### ISSUE TITLE
[Suggestion] 1x1x1 Gravity Block and/or change mesh?

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1584]
First, the gravity unit is awesome. I'm particularly excited about the fact that you can change the dimensions of its field on _both_ sides of it. Even the Space Engineers gravity generator can't do that, so I can't wait to see the cool gravity fields people make using this.

However, its height makes it a little tricky to put in ships; since it requires a larger space, it can be hard to find a place to put it. Also, regardless of whether it's 2m or 1m tall, while the mesh for it definitely looks really cool, it might be better for it to be more like blocky, like the reactors or shield units. Those blend into the blocks used for walls pretty well; more complicated shapes look a little out-of-place.

This looks like part of the wall:
![20200130163610_1](https://user-images.githubusercontent.com/33041786/73497320-255dca80-4380-11ea-9dbd-d8bbf2eb5780.jpg)

This looks kind of funny, and would need a lot of bricks to make less-funny:
![20200130163630_1](https://user-images.githubusercontent.com/33041786/73497018-6dc8b880-437f-11ea-9c4a-f9ce7b58b427.jpg)

**Comment by tsunamayo** [comment]
Yes I agree 100%. I am just mad about myself, I wanted to make an original design, but it is clear that I have to make a non-original one that blends well... I knew it but I cant stop myself... 
How are you liking the shield block?

**Comment by Dwarf-LordPangolin** [comment]
The shield block is awesome! It's actually probably my favorite of the system blocks. In particular, the texture on the sides really goes well with the texture on the top.

**Comment by tsunamayo** [comment]
Okay I made a new block for the anti-grav, which is much smaller (0.25x1x1) and easier to blend in (currently live). I experimented a bit the screen, I will use that effect for the computer and gate.
Also I will switch to a fixed cost for grav, it will be easier to manage and understand for the player.
Thanks!
