### ISSUE TITLE
[Bug] Fence textures broken [20w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1585]
### Short Description of the issue:
The straight fence and corner fence both have broken textures.

### Steps to reproduce the issue:
Place fence blocks. :)

### Environment
- Skywanderers version: 20w04a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200131004012_1](https://user-images.githubusercontent.com/33041786/73521169-f0c33080-43ca-11ea-9171-862a439844f7.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4138099/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue will be fixed in upcoming 20w05a. Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Just noticed this applies to the switches too.

![20200201024020_1](https://user-images.githubusercontent.com/33041786/73589464-461b4280-449c-11ea-9762-5e336418217c.jpg)
