### ISSUE TITLE
[Bug] Bouncing Docking Pads Returns [20w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1588]
### Short Description of the issue:
The bug mentioned in [this issue](https://github.com/tsunamayo/Skywanderers/issues/1554) still seems to be around; attempting to dock on landing pads results in a lot of bouncing up and down. Docking can eventually happen despite this, but it may be sideways.

### Steps to reproduce the issue:
Seems to happen with all ships when attempting to dock.

### Environment
- Skywanderers version: 20w04a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200201011411_1](https://user-images.githubusercontent.com/33041786/73588593-9be9ed80-4490-11ea-9bda-9ec984ed52f2.jpg)

![20200201010812_1](https://user-images.githubusercontent.com/33041786/73588594-9ee4de00-4490-11ea-876d-48fe4c5c3bea.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4142283/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I am having some trouble since the new control + new physics is in place. Will keep you posted!

**Comment by tsunamayo** [comment]
I have improved that a lot in the last update (currently live). Please tell should not be the case, it might be a ship dependent thing! Cheers
