### ISSUE TITLE
Title screen character customization is useless

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#159]
On the title screen, go to Options > Game > Player Customization and customize a character.
Then go to Play > Singleplayer and the character doesn't appear on the list. After naming a character in the singleplayer menu and playing as them, the character does not have the same appearance as the character created in the title screen options.

Title screen character customization settings also don't seem to save.

**Comment by tsunamayo** [comment]
Thanks for reporting this. For now this should customize you appearance, not create a new character save. But it seems indeed that the title screen  character customization is not working (there is one in-game also)

**Comment by tsunamayo** [comment]
It have been fixed. Thanks!
