### ISSUE TITLE
(BUG)cant move 

### ISSUE THREAD

**Issue by Hugbee1** [tsunamayo/Skywanderers#1592]
### Short Description of the issue:
load in to new game and i cant move (wasd,arrows,numpad) none work just mouse 
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: latest steam 
- Graphics Card: 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Lsutehall** [comment]
Sounds like you are in the "walking" movement mode. Try opening the codex and choosing the a different jetpack option from the movement menu.

**Comment by tsunamayo** [comment]
Yes I think @Lsutehall might be right! Was it your problem? In any case I must indeed show a little help message to show this. Now when stranded in space you go nowhere with the standard mode!

**Comment by Hugbee1** [comment]
Yes it did turn out to be that. Sadly there is no key info or any help in game  I've had the game since the 2060 issues and every time I've gone to play been meet with issues I know it EA but I regret buying this one :(

**Comment by tsunamayo** [comment]
Sad to hear that, btw it is not EA it is a closed pre-alpha... Yes I need to work on a help / info system. Cheers

**Comment by Hugbee1** [comment]
Yes a help system or info would of been good in you even could of done this in  video or text doc
