### ISSUE TITLE
[BUG] Collisions treat all blocks as fullblock

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1593]
### Short Description of the issue:
![imagen](https://user-images.githubusercontent.com/559819/73700144-05166e80-46e6-11ea-8474-aa50bcf371e6.png)
Tried closing a hinge, and it stops too soon. Added the black block to measure, and it perfectly aligns with the point the slope stops.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: AMD RX 580

**Comment by tsunamayo** [comment]
So it is not really a bug atm as it is expected from the engine. I use proxy volume, in your case with a block the proxy is always gonna be a 1m x 1m cube!
I pnig you if I manage to improve this (like said in other case I am considering switching to a baked one). Cheers

**Comment by AfterRebelion** [comment]
If not a bug, at least it's unexpected behaviour. This change makes collisions work completely different to earlier versions.

**Comment by tsunamayo** [comment]
Yes sorry for that! The change was made quite a few update before, was it working fine for you in the previous update (all collisions should have been broken)?

**Comment by AfterRebelion** [comment]
Yes, collisions were missing for a couple of updates (I think since 20w02?), really surprised nobody reported it.
Maybe it was so obviusly broken that everybody though it was purposedly left out.

**Comment by tsunamayo** [comment]
There was an issue reported but that was mistaken out for a collision issue with the new blast door - it was in fact linked to children entity. It must have been since the big update 20w02 indeed, as it was following the physics refactor. Thanks!

**Comment by AfterRebelion** [comment]
Now that I know this is expected, I can track down really broken scenarios, like this one:
[BrokenBrickCollisions.zip](https://github.com/tsunamayo/Skywanderers/files/4151451/BrokenBrickCollisions.zip)
Block seem consistent, but bricks on the other case...

**Comment by tsunamayo** [comment]
Okay in upcoming 20w07a this should works. A few example will still be a bit bugged (a long wedge for example), but situtation should be much better, at the expanse of a much higher fps cost...
