### ISSUE TITLE
[Suggestion] Light Emission "Tag" Tool

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1595]
I know there are other suggestions for added paint colors and glowing blocks/bricks, but this is a little different in application. I suggest having the ability to "tag" any paint-able block/brick/decal to use one of the glowing effects already present in game.

There exist two types of glow that I know of: low intensity (lights on shield generators, reactors, small thrusters, etc.) and high intensity with bloom (engine glow, sun, laser, etc.) Lights and the shield bubble seem to use something different that doesn't really "glow", so I've excluded them.

This "tagging" function would allow the addition of glowing elements without the need for a separate block or paint. It would only make a non-glowing element glow with whatever color they are painted in the same way that existing glowing elements emit their painted color.

The tagging tool could be a selection in the TAB menu like the other build tools (symmetry, logic connector, etc.)

What do you think of this idea?

**Comment by tsunamayo** [comment]
Hi, I am not sure to get 100%, but in any case that is not how the engine works! First there is no glow in the engine, it is just a strong emissive color, then HDR and bloom will do the job. Then I cant really tag object like that, it seems overkill!
Then lastly I dont really want to give glow, I think glowing things should be reserved for system for gameplay reason... 
Cheers!
