### ISSUE TITLE
[Bug] Sloped glass block can only be painted on frame

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1596]
Sloped glass block can only be painted on its frame. Trying to target the glass itself does not work.

1. Place sloped glass block. Stretch in any direction or leave as single block.
2. Paint with nay color. Try aiming for the middle with the glass.

- Skywanderers version: 20w04a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200203004110_X](https://user-images.githubusercontent.com/51390907/73820906-c1dcfe00-47c0-11ea-914b-8c0da8bda6b3.jpg)
(!)The sloped panes are all the ones with gold frames except the one in the top middle
(my output log is over 1 million Kb so I couldn't attach it for this report, sorry)

**Comment by tsunamayo** [comment]
Okay it is a real bug, but as I will remove this block it wont apply. But I still have the same issue for the new wedge #1622 (for a different technical reason but who cares ;) ) 
Cheers
