### ISSUE TITLE
[Bug] "Grandchild" entity collision issue [20w06a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1597]
### Short Description of the issue:
The space needed for blocks on "grandchild" entities (not sure what the proper name is; child entities on child entities) is larger than that needed for the same volume of blocks on the child entity.

### Steps to reproduce the issue:
Make a setup like this:
![20200205223508_1](https://user-images.githubusercontent.com/33041786/73906233-d1635200-4867-11ea-9ecd-0af850a1b6b9.jpg)

The first hinge will not be able to move once the block is placed on the second hinge; something is blocking it. However deleting the block on the "grandchild" entity allows it to move freely:
![20200205223623_1](https://user-images.githubusercontent.com/33041786/73906269-f22ba780-4867-11ea-8f67-28893d7f5e93.jpg)

The first hinge will still move freely even if the hinge and block are replaced with two blocks, which should take up exactly the same space:
![20200205224011_1](https://user-images.githubusercontent.com/33041786/73906478-a2011500-4868-11ea-9105-ef880cc9d202.jpg)

The conclusion seems to be that the collision box of "grandchild" entities is taking up more space than the same volume of blocks would on a single child entity.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
I found this when I was trying to make simpler landing gear for the Tornado that would work with the current collision setup, and noticed that something was off. Pictures of the original landing gear for further illustration. This gets stuck, and cannot move unless the single block on the second hinge is deleted:
![20200205222653_1](https://user-images.githubusercontent.com/33041786/73906099-4da96580-4867-11ea-8e58-445b1b697478.jpg)

This should require precisely the same clearance, but for some reason can fold up just fine:
![20200205222659_1](https://user-images.githubusercontent.com/33041786/73906096-4bdfa200-4867-11ea-931d-f0d7042069c5.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4163689/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: this might not just be restricted to grandchild entities. A similar issue regarding the space required for bricks happens on child entities as well. 

![20200206003719_1](https://user-images.githubusercontent.com/33041786/73914377-ccf66380-487e-11ea-9b27-b1c5a189ed72.jpg)

These pipes are meant to move up and stop **below** the level of the white area -- they won't reach into the cutouts, which I made to double-check that I hadn't misjudged how far up they needed to go -- but something invisible is blocking them.

**Comment by Dwarf-LordPangolin** [comment]
Based on AfterRebelion's post, this might be the same issue as #1599.

**Comment by tsunamayo** [comment]
Okay I have made a lot of improvement, it will be available on next patch 20w07a. Now your complex landing gear on your starwave are working! cheers
