### ISSUE TITLE
[BUG] Bricks have incorrect collisions

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1599]
### Short Description of the issue:
I already talked about this in #1593 , but here it comes it's own issue report.
Bricks have incorrect collisions.
You can see this in the example here:
![imagen](https://user-images.githubusercontent.com/559819/74087600-3b5d4080-4a8e-11ea-9b62-ac39e7ff4030.png)

Two identical hinges, with the same block on top. The two hinges are exacly in the same position and rotation, the only thing different between the two is that one is translated three blocks away from the other.
The blocks are the same type, one nonstreched fullblock (As in.. not a slope or any other shape) brick. The only difference in the block on top of the hinge is that the right one was placed bottom to top, and the left one placed left to right.
The one on the **left moves** when activating the switch, the one on the **right doesn't**.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: AMD RX 580

### Additional information:
[BrokenBrickCollisions2 - 20w06a.zip](https://github.com/tsunamayo/Skywanderers/files/4174496/BrokenBrickCollisions2.-.20w06a.zip)

**Comment by tsunamayo** [comment]
Okay thanks a lot for this test case, it was precious to fix a hard to track issue.
I made a lot of change again, to improve the quality of the collision. That make them slower, but hopefully I can bake them with an improved sequencer. It will be in next update, thanks!
