### ISSUE TITLE
[Low] Ships/vessels unable to fly into gravity field

### ISSUE THREAD

**Issue by clmd58** [tsunamayo/Skywanderers#16]
see the image below to get an idea... 
![image](https://cloud.githubusercontent.com/assets/12486156/22172600/2cc64246-df71-11e6-8a7d-b7b3acb398fc.png)

made a hangar style structure to test gravity behavior. turns out you cannot fly a vessel into a gravity field. the field acts like a shield or forcefield, and will block the craft from throttling up while pointed at any vector that is any less than parallel to the field. The photo I've posted depicts the starfighter as it ran into said field, although I turned it around backwards to look cool.. it's worth noting that the grav-gen in the hangar was turned off during this test, as well as the initial test. results were the same. 
Starfighter is the same one from the Francois save, and does not have its own grav-gen to my knowledge. It's unclear what part of the craft was actually the stopping point, as it seemed like the wing tips made it inside the hangar most of the way. perhaps the spaceship core is the object that is colliding with the gravity field. more testing will be done.

**Comment by tsunamayo** [comment]
Hello, I suspect it is simply a collision issue. Collision entity/entity are still very wip , you can refer to this post to check the progress : http://skywanderers.forumjap.com/t32-collisions-status-and-progress

**Comment by tsunamayo** [comment]
Confirmed as a collision current behavior
