### ISSUE TITLE
Having to press a key for the title screen buttons to appear could be confusing

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#160]
I assume this is intended; when you first start the game the title screen lacks buttons until pressing any key.

That isn't unusual in games, but most games have a "Press any key to continue" message on the screen informing players that they need to press a key.

Not having that message could be confusing to some new players.

**Comment by tsunamayo** [comment]
Hah indeed, there use to be a "Press any Key" message, that is no longer working - I will fix it. Thanks for spotting that, I NMS myself on this one!

**Comment by tsunamayo** [comment]
Okay fixed! Cheers.
