### ISSUE TITLE
[Bug] Ringworld Atmospheric Effect Causing FPS Loss & Stronger [20w06a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1602]
### Short Description of the issue:
The atmospheric haze around the ringworld now reduces FPS. The effect seems to have been introduced in the most recent patch; I didn't notice any FPS change around the ringworlds before.

The haze also looks like it's a much stronger effect than before; now the haze kicks in so early that it makes it harder to see to the end of a hallway.

### Steps to reproduce the issue:
Compare FPS while in ringworld atmosphere with FPS outside it.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200211181852_1](https://user-images.githubusercontent.com/33041786/74291643-25a08300-4cfb-11ea-8c4d-ea044c05468a.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4189244/output_log.txt)

**Comment by tsunamayo** [comment]
I am not sure to view this. You have a fairly good card, it should be fine. You can desactivate the torus fog in F3 Menu (under habitat). Could you tell me your fps jump once you desactivate it?
Thanks

**Comment by tsunamayo** [comment]
Okay, I am not 100% sure it was the issue, but it was taking 4ms on my card, which was indeed too much. I am now rendering it at half res, so it takes 1ms. It is still an expensive atmospheric effect with raymarching, so it is always gonna cost a bit. I might downsample even more for lower config when I have time to work on that.
Tell me if you still have issue in the next patch!
Cheers
