### ISSUE TITLE
[Question] what kind of humor do you like

### ISSUE THREAD

**Issue by Aboleth** [tsunamayo/Skywanderers#1603]
I'm curious :)

**Comment by Aiwii** [comment]
Dark Humour is pretty good but I also like Self-deprecating and Surreal Humour

**Comment by PopkaAkula** [comment]
What does this have to do with skywanderers

**Comment by schlid** [comment]
How to close an issue for someone else

**Comment by Aboleth** [comment]
Trolled epicly!!!
