### ISSUE TITLE
[Bug] Trap Door texture "slides" when moving [20w06a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1605]
### Short Description of the issue:
When the trap door moves, the texture on the hatch moves across it (technically maybe the door is moving and the texture is stationary, but whatever ;) ).

### Steps to reproduce the issue:
Place trap door, toggle open and closed. It can be hard to see, so painting the door a light color first might help.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
You can see the scratch marks "moving" across the surface of the door here:
https://gfycat.com/testysimilaramericanbittern

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4208832/output_log.txt)

**Comment by tsunamayo** [comment]
Indeed, I think I fixed this bug in the last update (currently live). Thanks!
