### ISSUE TITLE
[Suggestion] Increase Shield & Weapon Block Mass

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1607]
While comparing a corvette built to be fast but weak with a corvette built to be tough but slow, I realized that I couldn't. This is because the player does not actually have to make a compromise between any of these design elements. This is because shield generators have almost no mass. The same appears to be true for weapon blocks.

![20200220182817_1](https://user-images.githubusercontent.com/33041786/74992902-039bb480-540f-11ea-85e0-e871cb46902c.jpg)
_Above: Both ships have about the same Engine/Mass ratio, and have about the same top speed. But Orange is 33% more massive than white, with tons of shielding and many more guns._

As you know, it's generally a good rule in terms of game balance to force players to either focus on damage, health, or speed -- at the expense of the others -- or to compromise with some combination of the three. The current setup, however, allows players to have all three at the same time with no compromise; and while building a ship like this might be more expensive in terms of whatever the game's resources end up being, beyond the issue of cost there really is no reason not to.

Imagine an Overwatch character with Tracer's speed, Reinhardt's durability, and Sentry Bastion's damage; that's basically what the current setup allows. Yikes! :scream: 

So, in light of how much protection shield blocks provide, my suggestion is that they should probably have much more mass than they currently do, with the capacitors being even more massive than the generators. Tougher ships should be slower, regardless of whether their toughness comes from Hull blocks or Shield blocks.

The same concern applies for weapon blocks.

**Comment by ProPeach** [comment]
I completely agree, at the moment combat systems to not cost your ship much to mount them so you aren't encouraged to choose your priority, you can just have all of them in large amounts. I also think that the energy requirements of weapons and shields should be increased by at least a factor of two for the same reasons.

**Comment by tsunamayo** [comment]
Oh yes 100%, I will do a big weight pass. System are gonna be 4x heavier at the beginning. Bricks will be also quite dense.
Whats this orange ship? I like it! Cheers

**Comment by tsunamayo** [comment]
Okay new mass are updated! System are 4x heavier, we will see if we need to tone that down. Thanks!
