### ISSUE TITLE
[Suggestion] Triangular Windows / Non-Frosted Glass Bricks

### ISSUE THREAD

**Issue by Sofa499** [tsunamayo/Skywanderers#1608]
Triangular window blocks, or non-frosted window bricks of different shapes, would be useful in creating these sorts of shapes (see attached images), particularly for cockpits and bridge windows.

![skw_triangleglass](https://user-images.githubusercontent.com/43046590/75083794-be43b980-54d8-11ea-930f-6deda5a860d3.jpg)
![skw_triangleglass02](https://user-images.githubusercontent.com/43046590/75083795-c00d7d00-54d8-11ea-840d-989f9d67b6bf.jpg)

**Comment by tsunamayo** [comment]
Actually I just made that in the currently live update! Cheers
