### ISSUE TITLE
[BUG] Ghost switches and buttons

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#1609]
### Short Description of the issue:
tried to destroy a switch and a ghost switch appeared.

### Steps to reproduce the issue:
I do not know how it happened, I just destroyed the small slider it was linked to and tried to destroy the switch and it ended up like (see 1st picture below).

### Environment
- Skywanderers version: 20w06a
- Graphics Card: GTX 1050 ti

### Additional information:

After restarting my game, the switch was still there as a ghost. But when I placed a button in the same place, the button replaced the switch and became a ghost block (see 2nd picture). I was then able to place an infinite amount of switches in that spot, which I could then delete all at one and merge the ghost switch and button together (see 3rd picture). 
(By this point the output log became more than 10MB and wasn't able to upload, the one below is from before I placed an infinite amount of switches I think)

![20200223185442_1](https://user-images.githubusercontent.com/39653820/75118049-7191e700-566e-11ea-9932-b76df75e2d5d.jpg)

![20200223194927_1](https://user-images.githubusercontent.com/39653820/75118844-9dfd3180-5675-11ea-8cf2-d0fe913df14d.jpg)

![20200223195303_1](https://user-images.githubusercontent.com/39653820/75118924-735fa880-5676-11ea-8e81-dbd4b9361d9e.jpg)

![20200223195251_1](https://user-images.githubusercontent.com/39653820/75118931-7e1a3d80-5676-11ea-82c8-1ffbe5e17f1c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4242294/output_log.txt)

Edit: through random chance, I was able to create another ghost block by putting buttons like this:
![20200223201417_1](https://user-images.githubusercontent.com/39653820/75119293-5a0c2b80-5679-11ea-9315-b3a68e88cb48.jpg)
after that, I was able to place infinite buttons on the spot highlighted. After deleting all of the buttons there I was left with
![20200223201436_1](https://user-images.githubusercontent.com/39653820/75119306-888a0680-5679-11ea-9879-05f4cff07a81.jpg)
![20200223202107_1](https://user-images.githubusercontent.com/39653820/75119349-12d26a80-567a-11ea-9e7b-56bb97a52380.jpg)
(all ghost blocks)

I think it might be due to Issue #1604

**Comment by TheCuriousSkeleton** [comment]
placing 3 buttons in one place was unnecessary, you can do it with 2
![20200223202539_1](https://user-images.githubusercontent.com/39653820/75119429-b6bc1600-567a-11ea-98bd-6ec5599e3cfd.jpg)
![20200223202548_1](https://user-images.githubusercontent.com/39653820/75119432-b9b70680-567a-11ea-965c-edeac1c325f7.jpg)

**Comment by TheCuriousSkeleton** [comment]
Can do it with one
![20200223203936_1](https://user-images.githubusercontent.com/39653820/75119638-a4db7280-567c-11ea-856b-79554c54d540.jpg)

**Comment by TheCuriousSkeleton** [comment]
After destroying and repairing a ghost block, I was unable to place, destroy or interact with anything
![20200223205025_1](https://user-images.githubusercontent.com/39653820/75119901-0b619000-567f-11ea-92eb-10d46f93e8af.jpg)
![20200223205041_1](https://user-images.githubusercontent.com/39653820/75119902-0c92bd00-567f-11ea-828e-5c9de739d2a8.jpg)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the bug. What happens after the issue is of little help, no need to spend too much time investigate this. 
What is of real importance on the other side is how the bug happens! I was not able to reproduce your test case. Are you able to reproduce? Is there any more info I could get to reproduce?
Is the log file from the session where you first deleted the block or is it after a restart?

Cheers

**Comment by TheCuriousSkeleton** [comment]
1. Place a brick down
![20200229154127_1](https://user-images.githubusercontent.com/39653820/75610576-66c1d100-5b0a-11ea-835c-359c21984ad5.jpg)

2. Place a button above you (This is important)
![20200229154134_1](https://user-images.githubusercontent.com/39653820/75610583-793c0a80-5b0a-11ea-9c0b-ea997e0240b0.jpg)

3. Go below the button, and place another button on top of the previous button.
![20200229154147_1](https://user-images.githubusercontent.com/39653820/75610600-94a71580-5b0a-11ea-9651-d6bcf5db1c6f.jpg)
As you can see, if you aren't below it, it won't work
![20200229154142_1](https://user-images.githubusercontent.com/39653820/75610633-ce781c00-5b0a-11ea-9ead-dbf65ef2a2a9.jpg)

4. Delete the button
![20200229154211_1](https://user-images.githubusercontent.com/39653820/75610659-10a15d80-5b0b-11ea-8cda-33c96900bb38.jpg)
If it works correctly the button won't disappear.

5. Try and delete it again
![20200229155143_1](https://user-images.githubusercontent.com/39653820/75610707-6bd35000-5b0b-11ea-8c63-28b739bb947b.jpg)
You can't see it, but it won't allow me to delete it. I just stay in the delete animation until I click/update.

Note: I have been trying to send the output_log but its either too big to upload or it is in the wrong format. It works sometimes, like the one above.

**Comment by tsunamayo** [comment]
Thanks for the test case, unfortunately I still cant reproduce it! I cant place one button inside the other one.
Are you able to reproduce 100% of the time? I made some change to the collision / raycast system, maybe this is why, you will tell me if you reproduce in next upcoming version. Thanks!
Thanks

**Comment by TheCuriousSkeleton** [comment]
Sorry for the late reply. Yes, it still happens and yes I can reproduce it 100% of the time.

**Comment by TheCuriousSkeleton** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4332639/output_log.txt)

**Comment by tsunamayo** [comment]
Okay could you please send me your blueprint? There might be something fishy with it.
I just cant manage to place a button inside another one like you do. Thanks!

**Comment by tsunamayo** [comment]
Could you also do the following test:
1) Start the game from windows (do not go back the main screen and restart)
2) create a new build
3) do your button placement trick.

=> do you confirm in that case you still see the issue?
Thanks!

**Comment by TheCuriousSkeleton** [comment]
I did the test. It still happened
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4339308/output_log.txt)

(This was on a completely different ship/build/entity. I don't know the word for it)

**Comment by tsunamayo** [comment]
Okay there is a new build 20w12a. Tell me if you still reproduce with the new build! If yes I will ask you to send your save-data in full, there might be some other ship loaded that provoke the issue. Thanks!

**Comment by TheCuriousSkeleton** [comment]
I could not recreate the issue in the new version

**Comment by tsunamayo** [comment]
Okay great! This one was a though one, glad it is gone. Thanks a lot!
