### ISSUE TITLE
Pressing Escape in the singleplayer player customization menu leaves a floating character image on the screen.

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#161]
I'd post a screenshot, but Skywanderers hates Gyazo and Steam won't take screenshots in Skywanderers. Just see for yourself.

Also, reopening the Player Customization menu and closing it by clicking Done will make the floating character image disappear.

This bug doesn't occur in the title screen customization menu because pressing escape in that menu does nothing.

**Comment by tsunamayo** [comment]
Derp! Indeed thanks a lot for this one, I will fix it asap. Cheers

**Comment by tsunamayo** [comment]
Okay fixed! Thanks.
