### ISSUE TITLE
[Bug] Turrets sometimes clipping, sometimes not [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1611]
### Short Description of the issue:
Sometimes the turrets respect the collision system; when this happens, they behave excellently. Sometimes, however, they seem to ignore it.

### Steps to reproduce the issue:
I just noticed this, and I haven't yet pinned down what causes it. I noticed that turrets are still trying to follow where the player is looking a lot of the time, even when they're set to be fully automated. I'm wondering if it's connected to that somehow (even if it's not, that should probably be fixed too).

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Here, you can see that two of the turrets closest to the camera are respecting clipping by "bumping" into the hull. If you look at the third turret, on the far left and furthest from the camera, you can see that it is clipping into the same area that the others cannot clip into.
![20200224145105_1](https://user-images.githubusercontent.com/33041786/75199010-a0b85f00-5727-11ea-9614-8efbf3056642.jpg)

Here you can see the small turrets respecting the clipping; their barrels are being stopped by the turret's internal structure.
![20200224171925_1](https://user-images.githubusercontent.com/33041786/75199876-e1b17300-5729-11ea-8aea-e577b774f16a.jpg)

Here you can see the turrets clipping into the hull to try to follow the target.
![20200224165556_1](https://user-images.githubusercontent.com/33041786/75199087-cba2b300-5727-11ea-93ec-53cfb74b4ac6.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4247277/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update:

I've found that one factor is that clipping depends on whether the ship's turrets have targeted an enemy ship or not.

To test this bug, I took the Tornado and connected its turrets to the yoke (since they'd been disconnected for the previous version). Then I took control of the ship. The turrets followed the pilot's view, but did not clip into the hull; the collision detection worked.

Then I spawned an enemy ship and moved closer to it. The turrets began to fire on it, but now that they had a target, they started clipping. So, the clipping began as soon as the turrets were set to automatically target thigs (Tracking Mode: Auto, Auto Fire: On), and had something to shoot at. Hopefully that's some help in finding what's causing this.

Also, the turrets are doing something really weird. They're following the player's view, but firing on their own whenever the player looks close to the target. It's very weird and hard to explain, so here's a gif to show it as it happens. At the start the turrets are respecting the collision system (one of them's acting kind of weird, I need to look into that bug too, but it's not clipping), but then after the target spawns they begin to clip.

https://gfycat.com/limpinferiorkrill

So whatever is causing this turret clipping seems to be connected to the turrets trying to follow a target.

**Comment by tsunamayo** [comment]
Actually I deactivated collision for now, it was lagging too much. 
For now I will expose some constrain parameter the player will be able to input, but ultimately I would like to be able to generate those constrain automatically. 
That way I will just have turret stay within constrain without the expensive collision check.

I keep you posted.

**Comment by tsunamayo** [comment]
I now coded the baking collision map feature. It takes a bit of time to bake once you get in the ship on the Whirlwind (2sec), but as it is multithreaded it is transparent. You can debug the map on each rotator UI, this is temporary I will hide better ;).
Now we get collision for very cheap in real-time!
It is likely to do garbage for tricky turret though, like turret with unused slider / rotator in their chain.

Cheers
