### ISSUE TITLE
[Suggestion] Please Retain the Slab Block

### ISSUE THREAD

**Issue by Sofa499** [tsunamayo/Skywanderers#1612]
It has come to my attention that Tsuna has plans to remove the slab (half-height) block. Unless these blocks present some major issue behind the scenes, I would prefer to retain them. I find them very useful for surfaces and shapes for which standard sized blocks are too large, but where using bricks would be too tedious or are otherwise not visually appropriate (eg, corridors and decks, bulkheads, external plating, truss parts, and others).

If the slab is too problematic to keep, what exactly is that problem?

**Comment by tsunamayo** [comment]
There is a bunch of issue with light ect, I prefer if people would rather use full block for what you described. Plus it dont really make sense, if I give half width (which you can always achieve with bricks if you really need it), then why no half wedge ect ect?
