### ISSUE TITLE
[Bug] Reactors generate no power when first placed [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1613]
### Short Description of the issue:
Generators don't make energy when they're first placed; save and reload is needed to get them working.

### Steps to reproduce the issue:
Place a generator, check the power. Save, reload, check again.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200224222010_1](https://user-images.githubusercontent.com/33041786/75215099-4cc46f00-5755-11ea-8618-524f78f19d3f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4248061/output_log.txt)

**Comment by ProPeach** [comment]
When you first place them, can you use a switch to turn them on and get them to generate power? A while ago a similar thing happened to thrusters when they were first placed

**Comment by tsunamayo** [comment]
Yes indeed, it is now fixed! Cheers
