### ISSUE TITLE
Awkward brick hitboxes

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1614]
### Short Description of the issue:
At certain angles you can place bricks through other bricks or essentially 'miss' the target brick.
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional information:
![20200225133807_1](https://user-images.githubusercontent.com/32974671/75281111-4b865700-57d4-11ea-9c03-4132956aa497.jpg)
![20200225133810_1](https://user-images.githubusercontent.com/32974671/75281115-4cb78400-57d4-11ea-95b6-088e96cc9cd4.jpg)

**Comment by Xerma** [comment]
At times, when trying to place on a rotor/hinge/slider, you can also 'miss' the target and then it will build as if it's just part of the parent entity instead of on the child entity.

**Comment by Dwarf-LordPangolin** [comment]
Might be the same thing as [this issue](https://github.com/tsunamayo/Skywanderers/issues/1604) (your title is better tho ;) ).

**Comment by tsunamayo** [comment]
Okay I cant reproduce this, could you send me a bp? Are you able to reproduce 100% of the time when at the right angle? Thanks

**Comment by tsunamayo** [comment]
Okay I made a fix to the raycast that should have fix what you saw, will be in 20w11a. Tell me if you still see issue after this! Cheers
