### ISSUE TITLE
[bug] Can't Enter Camera Block through Yoke.

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1615]
### Short Description of the issue:
When linking a yoke to a camera you can't enter the yoke, and if you link the camera to the yoke you don't get a new view from the camera block. Seems like you just made changes to the system unless this was unintended. 
...

### Steps to reproduce the issue:
1. Place yoke
2. Place Camera
3. Link them up Yoke to Camera
4. Issue: can't enter yoke
-
1. Place yoke
2. Place Camera
3. Link them up Camera to Yoke
4. Issue: can enter yoke but no camera view
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: AMD Integrated Graphics (Vega 11, Ryzen 2600g)

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4252163/output_log.txt)

**Comment by tsunamayo** [comment]
Okay indeed, issue is now fixed! Thanks
