### ISSUE TITLE
[Bug] Beam Unit not firing Beams [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1616]
### Short Description of the issue:
Not quite sure if this is an actual bug or if this just isn't fully implemented yet, but the Large Beam Unit fires the same energy bolt thingy as the Laser Unit.

### Steps to reproduce the issue:
Place Beam Unit and connect to weapon hotkey or button, then fire.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4257576/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is still wip, it is just a placeholder atm. Cheers

**Comment by tsunamayo** [comment]
We have the beam since the last update, 20w13a. Thanks!
