### ISSUE TITLE
[Bug] Hinge placement overlap [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1617]
### Short Description of the issue:
It is currently tricky to place something on the moving part of the hinge, as the highlighted area is usually the base of the hinge instead.

### Steps to reproduce the issue:
Place large hinge, then try to stick something on the moving part. The highlighted area for placement will rapidly switch between the base and the moving part, heavily favoring the base.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
You can see here that the hinge base is highlighted, but at first glance it looks as though the gun has been placed on the moving part:
![20200226130613_1](https://user-images.githubusercontent.com/33041786/75378479-6078ee00-5899-11ea-9dac-074ed320f0ba.jpg)

After moving it, the problem becomes clear:
![20200226130622_1](https://user-images.githubusercontent.com/33041786/75378488-64a50b80-5899-11ea-8895-ace8c97f51bf.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4257699/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Note: this also applies to the small hinge.

**Comment by tsunamayo** [comment]
Okay this issue will be fixed in upcoming update! Thanks a lot!
