### ISSUE TITLE
Capacitors generate heat

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#1619]
Currently having one bit of reactor and one bit of capacitor is the same

... uh This should absolutely not be the case, they surely wouldn't produce heat or produce a tiny amount - currently there's little reason to have more then one capacitor brick or block

**Comment by tsunamayo** [comment]
Okay not sure to understand:
1) capacitor have twice the stock of a reactor (but obviously dont produce power), so it is not the same.
2) If I put 0 heat production, then there would be no reason to not put the max number of capacitor per reactor, essentially making power stock a non-variable.

What you might suggest instead is maybe increase their efficiency, aka capacity / heat ratio. Which I am likely to do. Or maybe did I miss something?
Thanks

**Comment by ultrak2k** [comment]
> Okay not sure to understand:
> 
> 1. capacitor have twice the stock of a reactor (but obviously dont produce power), so it is not the same.
> 2. If I put 0 heat production, then there would be no reason to not put the max number of capacitor per reactor, essentially making power stock a non-variable.
> 
> What you might suggest instead is maybe increase their efficiency, aka capacity / heat ratio. Which I am likely to do. Or maybe did I miss something?
> Thanks

I think that maybe yeah increase capacity or half heat production, also it seemed to me that not having any capacitors meant you couldn’t store power at all, but I’ll have to check ahaib
