### ISSUE TITLE
[Bug] Window wedge doesn't mirror properly [20w09a]

### ISSUE THREAD

**Issue by Javidac** [tsunamayo/Skywanderers#1620]
![20200226232231_1](https://user-images.githubusercontent.com/33093843/75452662-ffbde400-5972-11ea-8a5a-e2d115615fd3.jpg)

### Environment
- Skywanderers version: 
- Graphics Card: 20w09a

**Comment by tsunamayo** [comment]
Okay it will be fixed in next update. Also this should be called tetra and not wedge, so I fixed that also  ;)
