### ISSUE TITLE
[Suggestion] Stickers should have an option to overlap windows.

### ISSUE THREAD

**Issue by Javidac** [tsunamayo/Skywanderers#1621]
This is what i'm trying to mimic with stickers, if they overlapped the transparent part of the window then it would look nearly identical.

![20200226230306_1](https://user-images.githubusercontent.com/33093843/75453038-9094bf80-5973-11ea-8403-3a752cb193d4.jpg)

This would definitely be a welcome addition to an otherwise great sandbox, and allow for much more visual freedom in cockpit shapes.

![20200226232045_1](https://user-images.githubusercontent.com/33093843/75453052-95597380-5973-11ea-9459-02006e8e085b.jpg)

**Comment by tsunamayo** [comment]
I understand you request and it made a lot of sense indeed, but unfortunately the stickers tech is not compatible with transparent surface. It needs something opaque to render, thats a limit of the tech... So I wont be able to do it... 
Cheers
