### ISSUE TITLE
Can't paint border on Window Tile Wedge

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1622]
### Short Description of the issue:
Pretty straightforward, simply can't paint the border on the Window Tile Wedges. Unsure if this was just left out or not but being able to paint the border is a necessity
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional information:
![20200227121909_1](https://user-images.githubusercontent.com/32974671/75473934-ac8c6700-595b-11ea-890b-231e2fad69e9.jpg)

**Comment by tsunamayo** [comment]
Yes indeed, I reworked on the raycast tech and it not dealt with multi-paint... I keep you posted, thanks

**Comment by tsunamayo** [comment]
Okay I finally close the gap with the new raycast system, this will be possible in new update. Thanks!
