### ISSUE TITLE
Replacing blocks with bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1626]
I can sort of understand where you're coming from when replacing some blocks with brick versions but doing so limits building a lot, primarily in any medium to large ship. The perfect example is window tile wedge/tetra and how it replaced the block version. There were many instances where myself and others used those block versions but now we only have a smaller version where we would have to place multiple of them to cover the same area as the block versions, that or just have smaller windows.

I would greatly suggest bringing back the vast majority of blocks that got replaced by their brick counterparts, but keep the brick versions as well. Both have great areas of use. That or I would say the dragging limits for those would need to be increased to 16m.

A few other examples are block window wedges that got replaced with a brick version and can only drag in 2 directions. Practically all of the old block canopy blocks got replaced with the new brick versions but as I previously stated it's very limiting. The next one is one I know you want to get rid of but I have to keep pushing to keep it. The slab. Sure we can use bricks to get the same shape but more bricks turns into more processing since the brick is limited to a 4m drag in each direction where the block is at 16m. Plus bricks have borders whereas blocks do not and that can make builds very ugly very fast if we are forced to use those instead. Before you were against people using bricks where they could have been using blocks to build ships and now it feels like the exact opposite.

**Comment by Dwarf-LordPangolin** [comment]
Agreed. While the brick-scale windows are awesome and much-needed, losing the block-size ones makes some structures impossible or at least rather tricky.

**Comment by ProPeach** [comment]
Absolutely. The brick canopy and other shapes are incredible for small ships, but really quite limiting on large ships. In a game with such wide differences in scale as Skywanderers, you really need a block and brick version of most things. I recognize that you like to keep the codex clean, but a bricks only tab is a much better option than simply removing important aspects of the build system.

Again with slabs, these are an integral part of any block game. They're so incredibly versatile it's difficult to come up with specific use for them, but they will be very, very sorely missed and are likely to just get requested again when the game hits EA or sooner. Sure you can use a brick, but the textures don't match so the brick slab will stick out like a sore thumb, and you'll end up having to place more stretched bricks than just the one stretched block. If they cause problems with the lighting, does that not mean that there is an improvement to be made there instead of removing the problem? This is a similar debate to the one about removing the left/right half corners, and I'm sure there will be other times this crops up too

**Comment by tsunamayo** [comment]
Thanks for the suggestion.
You really need a 16m wide wedge windows? Also there was no triangle block size windows before.
If I add back block size windows it will be block size, aka 1m thick.
People will use slab for interior door / wall for sure, and it has a lot of negative impacts. Like what is your use case really other than that?
Also if I want to add more block for interior decoration (I have quite a few in mind, like the wood one), then people will be "I need that in slab version" ect ect.

**Comment by Xerma** [comment]
We don't necessarily use 16m wide wedge windows. It's more so of losing the ability, or freedom, to build larger windows for builds that want a more open view. I personally feel like the old canopy blocks were perfect for the build system

**Comment by Majikmonster** [comment]
How could the half slab **_NOT_** be useful? It's a block that blends with other blocks in texture, usable in heat dissipation as hull, and thinner in profile for both interior and exterior uses.
      I frequently use it on ship hulls as a great way to step down a slope without using an exorbitant amount of bricks for things like engines, docking tubes, weapon housings, and other elements that would be unnecessary for bricks and too bloated with blocks. I typically use it as a 0.5 block ceiling, so the top remains flat 1m and the space below has an extra bit of head room. I use it for thinner walls. I use it to make finer patterns with half-block gaps, such as logos and window openings, or thinner appliances on a full block wall. It's a less bulky greeble than full blocks and not as pointy or bulbous as the wedges or curved hull.
      I also use it for adding depth in hulls while using less bricks in the process. I use it in larger vents when I want slats or gaps instead of mesh like the grates have, and this makes much more sense on large ships given LOD transitions from a distance don't favor the fine details of bricks, while the slab remains boldly visible and readable in shape (essential to any huge ship or medium ship in passing). It's a perfect middle between diversity of shape and consistency, as bricks do not blend with blocks, and it takes more bricks and stretching to achieve what the slab can do in one or two placements. It is a way to add depth and detail without resorting to using bricks for everything (and this is coming from me, who would use bricks to make a 300m ship if it weren't such a bad idea).

      This concept also extends to the block canopies. Yes, they are a pain on smaller vessels and nearly unusable on fighters, but scale has everything to do with that. As soon as you go up to medium or large ships, more space can be allocated to more windows, and larger ones. Making a dome or observation deck with a view is far more tedious when you have to use 4 times as many canopies to get a straight slope, and it breaks up the view with all the lines and supports that smaller window pieces have or need. It would be much better to allow the smaller brick canopies help in smaller designs and patch in difficult spots in larger designs, than making the entirety of glass structures from tiny pieces. That would be like using hand mirrors for the Hubble's reflector disk.

      The argument over "if you give a mouse a crumb, it will want the whole loaf" is a tired one. I know it's tempting to use that to justify not adding ANY of a certain feature, but consider that asking and demanding does not equal to making it happen. You are as free to not implement a request as players are to make those requests, but denying ALL of those requests because of looming feature creep or inflation of a feature is not a valid excuse. After all, we the players have seen you tackle such issues with good compromises for this long. I trust we can come to a compromise on _this_ issue.

      Additionally, you say you want to add more interior decoration items that players have been making substitutes for with bricks since day 1. Wouldn't adding those elements fall under the same argument of extra variants? Players made their own chairs and couches before the new ones were added, and made doors before those were turned into their own feature. I'm sure if you can have jump pads, a handful of flowers and plants, plus interior decor... a few slabs aren't going to ruin anything.

**Comment by tsunamayo** [comment]
@Majikmonster you missed the point, see #1648 where I explain the rational.
I am sorry, I have to do a big push on the cleaning, if I am to remove blocks it have to be before early access. I mean you being pissed off it the exact reason I have to remove those blocks now, as to piss off less people on the future. These block might come back when the new tech is out and when I have more bandwidth...
For the large canopy, I will likely add large wedge / tetra block to go along the 1m transparent cube. It should cover the need for super large build. Or I might add a 1m version of the new brick also.
In any case the current canopy had to disappear as its build logic and collision was outdated, so if it was about losing your current build it is unfortunately a lost cause I am sorry...
