### ISSUE TITLE
Can't build off round bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1628]
### Short Description of the issue:
I'm not sure if this is linked to how we can place through blocks or not but it seems we can no longer build off of round or cylindrical bricks
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional information:
![20200228151453_1](https://user-images.githubusercontent.com/32974671/75587945-3e1fd580-5a3d-11ea-9914-4c277a5d8381.jpg)
![20200228151454_1](https://user-images.githubusercontent.com/32974671/75587947-3f510280-5a3d-11ea-9617-f5874b7d1408.jpg)
![20200228151455_2](https://user-images.githubusercontent.com/32974671/75587951-40822f80-5a3d-11ea-8f20-6eb5052283ae.jpg)
![20200228151455_1](https://user-images.githubusercontent.com/32974671/75587954-41b35c80-5a3d-11ea-83ac-5b17bf3e0a95.jpg)
![20200228151456_1](https://user-images.githubusercontent.com/32974671/75587957-437d2000-5a3d-11ea-8028-81fdd62ce16b.jpg)
![20200228151457_1](https://user-images.githubusercontent.com/32974671/75587961-4546e380-5a3d-11ea-8bc7-ede697a91223.jpg)

**Comment by tsunamayo** [comment]
Yes indeed I can reproduce! I am fixing this asap, thanks for reporting that.
Cheers!

**Comment by tsunamayo** [comment]
Okay great, issue is now fixed, will be in next patch! Thanks
