### ISSUE TITLE
[Bug] NPC Turrets always pointing at own center of mass [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1629]
### Short Description of the issue:
The NPC ships' turrets are always pointing at their own ships, at what appears to be the center of mass.

### Steps to reproduce the issue:
It seems to happen with every hostile NPC ship that is spawned. It takes a few seconds after spawning sometimes for the turrets to do this.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200229005352_1](https://user-images.githubusercontent.com/33041786/75602805-f83f2d80-5a8d-11ea-943c-2c4b04aa695d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4270008/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I noticed that also, the bug was already fixed and will be in next update. Thanks!
