### ISSUE TITLE
Lightcruise and landing gear bound to the same key

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1630]
### Short Description of the issue:
As the title: lightcruise and landing gear hotkey share a keyboard bind, resulting in jumping to hyperspeed when trying to deploy the landing gear!
...

### Steps to reproduce the issue:
Fly ship with hotkey bound landing gear. Press L
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: gtx1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
You are right, I have updated the setting, it is now set at G by default. But you still have to do the assignment on your own in your case, that only apply with a fresh install!
Cheers
