### ISSUE TITLE
[BUG] Blocks are not attaching to sliders

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#1633]
### Short Description of the issue:
Blocks are not attaching to sliders

### Steps to reproduce the issue:
1. Place down a slider
![20200229161845_1](https://user-images.githubusercontent.com/39653820/75630996-0eaccc80-5be7-11ea-958b-2d0423182d92.jpg)

2. Place a block on the slider
![20200229161850_1](https://user-images.githubusercontent.com/39653820/75630998-19676180-5be7-11ea-9309-716f8e9ec8b1.jpg)

3. Move the slider
![20200229161857_1](https://user-images.githubusercontent.com/39653820/75631000-22f0c980-5be7-11ea-8799-061dc806622d.jpg)

### Environment
- Skywanderers version: 20w09a
- Graphics Card: 1050 ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4272199/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this issue will be fixed in upcoming update! Thanks a lot!
