### ISSUE TITLE
[Bug] Docked ship starts out invisible [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1634]
### Short Description of the issue:
Docked ships can turn invisible on loading the world. Placing blocks on them restores visibility to them in chunks. Also, the ship was unable to undock while in this state.

### Steps to reproduce the issue:
Dock a ship, save, quit, and reload. I didn't notice this immediately, so I don't think it's happening every time.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200301133045_1](https://user-images.githubusercontent.com/33041786/75632399-46a11900-5bc1-11ea-9994-b68b30f7ad62.jpg)

![20200301133048_1](https://user-images.githubusercontent.com/33041786/75632400-499c0980-5bc1-11ea-8100-bcb0bf609803.jpg)

![20200301133052_1](https://user-images.githubusercontent.com/33041786/75632402-4b65cd00-5bc1-11ea-8665-ed83867f482e.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4272312/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this issue is now fixed! Will be in 20w11a. Thanks!
