### ISSUE TITLE
[Bug] Turret hinge moved itself to -88 degrees [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1635]
### Short Description of the issue:
Hinges on turrets can move beyond their constraints.

### Steps to reproduce the issue:
This happened at some point when targeting NPC ships with turrets.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200301143645_1](https://user-images.githubusercontent.com/33041786/75633405-18740700-5bca-11ea-93b9-9797c9770718.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4272414/output_log.txt)

**Comment by tsunamayo** [comment]
Okay indeed, I now fixed that one. Will be in 20w12b or later. Thanks!
