### ISSUE TITLE
[Bug] Deleting moving part of hinge causes hinge to disappear on save/reload[29w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1636]
### Short Description of the issue:
If the moving part of a hinge is deleted, the rest of the hinge will be missing after the game is saved and reloaded.

### Steps to reproduce the issue:
Place hinge.
Deleting moving part.
Save/reload.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Placed:
![20200301174509_1](https://user-images.githubusercontent.com/33041786/75636473-baa0e880-5be4-11ea-8795-a1bd82b947bc.jpg)

Deleted:
![20200301174512_1](https://user-images.githubusercontent.com/33041786/75636474-bb397f00-5be4-11ea-877d-7e15d8a10560.jpg)

After save & reload:
![20200301174554_1](https://user-images.githubusercontent.com/33041786/75636475-bc6aac00-5be4-11ea-954f-a2d7731b7931.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4272785/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I do a cleanup pass when loading a ship, to delete children-less mecanism. I think the cleaner thing would be to delete both at the same time. Thanks

**Comment by tsunamayo** [comment]
Okay actually I prevented this brick to be deleted, which is in line with what I did for other mechanism. Thanks!
