### ISSUE TITLE
[Suggestion] Cube Small Thruster Mesh?

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1638]
Would it be possible eventually (since this is just a cosmetic issue, it's very low-priority) to change the mesh of the small thruster to a cube like the large thruster (or possibly make a cube-shaped variant)? The current cylinder looks very nice on its own, but it leaves gaps around it, as it is literally a round peg in a square hole.
![20200302141217_1](https://user-images.githubusercontent.com/33041786/75714489-6ef84880-5c91-11ea-908b-9e90399a61d7.jpg)

Previously it was possible to add bricks in the gaps to make it look a bit better, but the new collision system precludes this.
![20200302141212_1](https://user-images.githubusercontent.com/33041786/75714551-8b948080-5c91-11ea-8fab-b9f455fe85c2.jpg)

**Comment by tsunamayo** [comment]
Hum I wanted to give something a bit different than the normal thruster.
If I am not satisfied with something it is more with the texture stretch on this one. I was thinking on adding a uniform scaling constrains. 
To be honest I really loved how you integrated your side thruster on your design!
I leave the suggestion open to see what other people think of.
Thanks!

**Comment by ProPeach** [comment]
I agree with Pangolin. The round thruster is perfect for some applications, but other times it can be awkward to fit in to the otherwise blocky shapes we have available to us. Like back in the old days when we had round and square thrusters, a choice between them would be much appreciated!

Before this patch the collision mesh on the round thruster was tighter as Pangolin pointed out which did help, if that change could be reverted that'd be awesome too.

**Comment by Aiwii** [comment]
If meshing won't work out, I would really like the old collision back

**Comment by ProPeach** [comment]
I agree, it's a little awkward to design round thruster cowling around a visually round thruster that is actually a cube in terms of collision mesh

**Comment by tsunamayo** [comment]
I am now dealing with cylinder a bit better, and you can decorate around them as before like in your build. Still not working is greedy packing of cylinder though, it will take a bit more time. 
Will be in 20w14a.
Thanks!

**Comment by ProPeach** [comment]
Thanks for the follow up! Looking forward to trying it out
