### ISSUE TITLE
[Bug] Saving when in a seat traps you in said seat on world reload.

### ISSUE THREAD

**Issue by AlexJHockley** [tsunamayo/Skywanderers#164]
I was using the small yellow mech on the starting dock, and I saved the game while in the seat on the mech. When I reloaded the world, I could not leave the seat, but could "re-enter" it by clicking F, which did nothing.

**Comment by tsunamayo** [comment]
Okay this is an interesting case indeed, I am still scratching my head on the best way to solve that. I might have to refactor the way we exit seat, I am not satisfied with that anyway.

**Comment by tsunamayo** [comment]
Now saving while using commands / seat is restored as load. Thanks!
