### ISSUE TITLE
[Bug] Barrel add-ons have the same name across sizes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1642]
### Short Description of the issue:
Large barrel add-ons and their new small counterparts are both named the same thing, causing confusion when you try and pick one out of the codex

Separate although related to this, the naming scheme is inconsistent across the codex. "Small Thruster" and "Capacitor Small" for example, in this case the capacitor should be renamed to "Small Capacitor", or the thruster to "Thruster Small" so that they match.

### Steps to reproduce the issue:
Open the codex, mouse over the barrel add-ons and notice their names and descriptions 

### Environment
- Skywanderers version: 20w09a
- Graphics Card: RX 580 8GB

**Comment by tsunamayo** [comment]
Yes I will be doing a much need big cleanup soon! Decription also are to be updated.

**Comment by tsunamayo** [comment]
Okay this is now cleaned up. Next update will have a tidier codex! Icon now looks great too.
Thanks!
