### ISSUE TITLE
[Bug] Free-look Orientation Misaligned

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1643]
### Short Description of the issue:
The Free-look Mode (Tab when in a ship) aligns by default with the orientation of the player, rather than the ship.
...

### Steps to reproduce the issue:
Fly up to a ship and control it, make sure that your player is misaligned (it usually is)
Switch to 3rd person with F4
Switch to Free-look with tab, and move the mouse around a bit. The view will be aligned with the plane of the player, not the ship as it should be
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: RX 580 8GB

### Additional information:

https://i.imgur.com/fcAwhGa.mp4

**Comment by tsunamayo** [comment]
Okay it was harder than expected but that bug is now fixed ;) Will be in next update. Thanks a lot!

**Comment by ProPeach** [comment]
Thanks as always!
