### ISSUE TITLE
[Bug] Can't place on the brick grid.

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1646]
### Short Description of the issue:
There are some bricks that only can be placed aligned with the block grid, and nowhere else.
Only items affected that I tested was the yoke, and the flat switch.

I used the wood block in the example because it's easier to see that it only works on the block grid, as there is no brick wood variant.

### Steps to reproduce the issue:

1. Place a hull block (Or any kind of complete block, like wood block)
2. Place a hull brick
3. Try to place a yoke or a flat switch on top of the brick
4. See the same result as the image above

### Environment
- Skywanderers version: 20w10a
- Graphics Card: AMD RX 580

### Additional information:
![imagen](https://user-images.githubusercontent.com/559819/76056446-d99dd280-5f76-11ea-9cd4-23e75fe6c3cb.png)
![imagen](https://user-images.githubusercontent.com/559819/76056362-a78c7080-5f76-11ea-865e-112efaff75f3.png)

**Comment by tsunamayo** [comment]
Okay great spot, this will be fixed in next update. Thanks!
