### ISSUE TITLE
[bug] Capacitor bounding boxes are incorrect

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1649]
### Short Description of the issue:

It looks like the bounding box on the capacitor block is too large. It incorrectly detects a collision with neighbouring blocks when the graphical model shows that it should fit.

### Steps to reproduce the issue:

Place a "stretch" of capacitors so they end against a wall: the model goes red and disallows placement when it looks like it ought to fit.

### Environment
- Skywanderers version: 20w10a
- Graphics Card: GTX1060

### Additional information:

![20200310225050_1](https://user-images.githubusercontent.com/40872394/76461243-70371d00-63d7-11ea-9653-14365fbe53ca.jpg)
![20200310225120_1](https://user-images.githubusercontent.com/40872394/76461249-72997700-63d7-11ea-8a05-bc6032a83aa7.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4320756/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay nice spot, this issue will be fixed in 20w11a. Thanks a lot!
