### ISSUE TITLE
[Bug] Lightcruise rating

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1651]
### Short Description of the issue:
Lightcruise rating and a ships ability to travel at lightcruise is not affected by block thrusters on child entities. Even if you have block engines pointing backwards on your ship, you can't travel at lightcruise if they're on a child entity .

### Steps to reproduce the issue:
Create a new ship with a yoke and ship core
Place a block thruster pointing backwards on the ship, check the ship core and see that the lightcruise rating increased
Delete the thruster, then try placing one on a child entity pointing backwards and check the ship core

### Environment
- Skywanderers version: 20w10a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Okay indeed, it should now be counted correctly. Will be in 20w11a. Thanks!

**Comment by ProPeach** [comment]
Great, thank you!
On another note, have you managed to stay safe during the current Covid 19 scare? 
Best wishes from the community o/

**Comment by tsunamayo** [comment]
Thanks mate, yes I guess so in Japan it is not as bad as France or Italy. But I had a bit of fever for a week now, but nothing big. I hope you guys are all safe! And managed to get some toilet paper ;)
