### ISSUE TITLE
[Bug] Unable to place starter block

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1654]
As the title says, I am unable to place the starting block to make a new ship in this new update.

Also here is a funny pic of one of my ships after the color change. It looks like a banana
https://cdn.discordapp.com/attachments/416013956331601930/689318677505638449/unknown.png

**Comment by ZachZent** [comment]
Never mind, wrong keybind

**Comment by tsunamayo** [comment]
but your ship still look like a banana right? what color was it?

**Comment by ZachZent** [comment]
Default grey. I had not got around to painting it. All default grey has turned to yellow and another grey to green
https://cdn.discordapp.com/attachments/416013956331601930/689315105099218998/unknown.png
https://cdn.discordapp.com/attachments/271723356795961345/689313297149067264/20200316222436_1.jpg
https://cdn.discordapp.com/attachments/271723356795961345/689313352115027976/unknown.png
https://cdn.discordapp.com/attachments/271723356795961345/689313460714209314/unknown.png

**Comment by tsunamayo** [comment]
Okay let me fix that real quick... Dont save your build!

**Comment by tsunamayo** [comment]
okay issue is fixed! Thanks
