### ISSUE TITLE
[BUG] Getting inside a ring world create pixelised rainbows

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Skywanderers#1655]
if you get far enought in the ground of e ring world (but not too much) you can see two rainbows ( following each ends of the rings)

Get stuck in the ground using the jetpack but don't go deeper than "water"

...

### Environment
- Skywanderers version: latest version 
- Graphics Card: Nvidia 1660ti

### Additional information:
![711980_20200317112104_1](https://user-images.githubusercontent.com/33103748/76848409-e9a19600-6843-11ea-809e-b01d5849be15.png)
![711980_20200317111647_1](https://user-images.githubusercontent.com/33103748/76848428-f1f9d100-6843-11ea-8bf5-2a7379ce1e00.png)

**Comment by tsunamayo** [comment]
Yes haha, the real bug is that you went beneath the terrain. It should not happen! So I wont really fix the rainbow... Cheers
