### ISSUE TITLE
[BUG] Wrong weight values

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1656]
### Short Description of the issue:
[The update notes for 20w12a mention](https://github.com/tsunamayo/Skywanderers/issues/1653): "All weights are being re-adjusted (except for Hull). Everything is much heavier now. It should be okay as everything was too fast already ;)"

But this is not what we can experience when loading 20w12a.
Block Hull weight has been adjusted up to 200kg, but there are some blocks like the Laser Weapon Block still weight 8kg.
![imagen](https://user-images.githubusercontent.com/559819/76887407-8b47d800-6882-11ea-9789-50f4451bf4b3.png)

### Steps to reproduce the issue:

1. Open the game, and use TAB to open the codex
2. Thanks to the new weight indicator in the codex (Really, really, really THANK YOU for this), you can ser that some blocks weight a lot less than they should.

To make sure that this is not related to a bug in the codex display itself, and it doesn't display incorrect values, I spawned a ship with only the blocks specified, and the drone displays the expected values.

### Environment
- Skywanderers version: 20w12a
- Graphics Card: AMD RX 580

### Additional notes:
Thank you again for adding all the info to the codex. The small S for bricks, the weight info, the power and heat stats... best update!

**Comment by tsunamayo** [comment]
Okay indeed I missed the weapons, it will be fixed for 20w12b! Glad you like the new info! Cheers
