### ISSUE TITLE
[Bug(?)] Rotor/hinge/slider max mass

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1659]
### Short Description of the issue:
With the recent changes to mass of a lot of blocks, it looks like the maximum mass that a child entity can move didn't increase with it so it feels much too low. Guessing you just forgot to update them : ) I'd suggest increasing them by at least the same factor as you did for the hull blocks.
...

### Environment
- Skywanderers version: 20w12a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Hull block were at that mass for quite some time, but yes I will increase the limit. Thanks!

**Comment by tsunamayo** [comment]
Okay I made the following changes:
Large => 50 000 kg
Small => 10 000 kg
Cheers

**Comment by ProPeach** [comment]
Thanks for implementing these changes, the slider and hinge are now much more workable.

I think that a different set of values are needed for the rotors, as they can't be stretched so the base mass of 50,000kg for example can't be scaled up like the hinge or slider (which is a great mechanic for them and should definitely stay). 
This is all that one block rotor can move currently
![image](https://user-images.githubusercontent.com/27857711/77923896-f5a54300-729a-11ea-8285-cd8b6937add2.png)
I'd suggest at least a 4x or 5x increase in their mass limits. Bricks are also still much too heavy as illustrated in that picture and are hurting the maneuverability of smaller ships, but that's an issue for another thread.
