### ISSUE TITLE
[Bug] Clipping still present [20w12a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1661]
### Short Description of the issue:
Turrets will still ignore collision detection and clip into the hull while tracking targets.

### Steps to reproduce the issue:
Spawn enemy ship for turrets to target.

### Environment
- Skywanderers version: 20w12a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Not _entirely_ sure this is a bug, since you previously mentioned grandchild collision detection would take a while to sort out, and the bit that's clipping is a grandchild entity, but I wanted to make sure it was known.

![20200319151257_1](https://user-images.githubusercontent.com/33041786/77110926-61162780-69f4-11ea-9f61-d63a041e7faa.jpg)

![20200319151308_1](https://user-images.githubusercontent.com/33041786/77110931-62dfeb00-69f4-11ea-9ba4-f0906b385ebb.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4356726/output_log.txt)

**Comment by tsunamayo** [comment]
Not really a bug at this point, I deactivated collision on turrets, it was too costly to perform in real time when using many turret like on your whirlwind ship (which was super useful to me to test combat).
But I still need to add a maximum range option in the turret menu. I keep you posted once I did that!
Cheers

**Comment by tsunamayo** [comment]
Okay the baking feature is live in the current version. But it seems we are still having some tracking issue nonetheless. Thanks!
