### ISSUE TITLE
[BUG] Lights not stretchy and Frosty Windows not frosty

### ISSUE THREAD

**Issue by BFett2000** [tsunamayo/Skywanderers#1662]
### Short Description of the issue:

Frosted Glass not frosty and lights not stretchy

### Steps to reproduce the issue:
Place Light Tube, Light Flat or Light Wedge on hull block and attempt to stretch in any direction.

Select either Frosted Window or Frosted Pattern Window and drag out a sufficiently sized sheet and look through the transparent section.
...

### Environment
- Skywanderers version: 
- Graphics Card: GeForce GTX 1060 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4362400/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I removed the stretch on the light, it was making my life harder on the light side. 
The frosted windows are fine on my side, could you please confirm that you have the distort post effect active? Press F3 and then look for [Post-effects / Enabled & Blur Effect] 
Thanks!

**Comment by BFett2000** [comment]
@tsunamayo I checked and the option is selected.

![20200327231021_1](https://user-images.githubusercontent.com/62455810/77816503-59075900-7080-11ea-8ce0-240ea4fcd917.jpg)

**Comment by tsunamayo** [comment]
Okay indeed I just reproduced the issue, it is one of those thing that popup only in build not in the editor.

**Comment by tsunamayo** [comment]
This issue will be fixed in 20w14a. Thanks!
