### ISSUE TITLE
[Suggestion] Reduce the menu/codex fuzz

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1663]
Let me just preface this by saying I love the improvements to the menu/codex. Though there are still improvements to be made, such as a few more categories for the codex (separate logic and decoration), it is very good with one exception.

When you open the menu or codex you get this blur fuzz effect. I do like the effect in principle, but seeing how often you open and close the menu and codex it gets a little distracting. It feels like you are taking off and on your glasses for a second. I'd keep the effect, but make it a bit more subtle. Something less distracting when you are opening and closing the codex frequently.
https://imgur.com/a/QbxfZp7

**Comment by ProPeach** [comment]
The same effect also makes the scaling ruler when you stretch blocks difficult to read when it fuzzes, I'd recommend either toning it down or removing the repetitive effect, so it only fuzzes when you open/close a menu rather than when one is already open and you're trying to read it

**Comment by tsunamayo** [comment]
Yes I do agree with that, I was planning to tweak it a bit further.
- Random intensity when opening a menu, so you would get the fuzzle only sometime
- maybe no fuzzle for codex or lower probability for codex
- in game less or no fuzzle, but still a bit of chromatic aberation and scanline effect as it is does not impact readability. 
Thanks!

**Comment by ProPeach** [comment]
Sounds good!

**Comment by SageThe13th** [comment]
I can't say I really like the effect at all. I'd just as soon see it removed entirely.

**Comment by tsunamayo** [comment]
You can remove it already in the options.

**Comment by tsunamayo** [comment]
Okay I made the change, hopefully it wont get in the way too much. Thanks
