### ISSUE TITLE
[Bug] NPC Pilots not in chairs [20w12a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1664]
### Short Description of the issue:
When NPC ships are spawned, the pilot does not sit in the chair near the yoke, but instead spawns somewhere random on the ship.

### Steps to reproduce the issue:
Spawn NPC ship, check location of pilot.

### Environment
- Skywanderers version: 20w12a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200322143101_1](https://user-images.githubusercontent.com/33041786/77258680-38876b00-6c4a-11ea-9aff-3bb26e425b21.jpg)

This one ended up Naruto-running!
![20200322143740_1](https://user-images.githubusercontent.com/33041786/77258793-ec88f600-6c4a-11ea-80fc-4b27ba3b2c5d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4366163/output_log.txt)

**Comment by tsunamayo** [comment]
Indeed, it was due to a loading sequence issue. It is fixed, for 20w14b. Thanks a lot!
