### ISSUE TITLE
[Bug] Game becomes unresponsive when loading a ship from Identity Unit while in a seat

### ISSUE THREAD

**Issue by AlexJHockley** [tsunamayo/Skywanderers#167]
I was sitting in a seat on my ship next to the Identity Unit, but wanted to reload my past blueprint to undo some changes. I reloaded the ship (The same blueprint ship I was in, but older) while in said seat, and the game became unresponsive.

Clicking the "escape" button to load the menu made the mouse appear on screen in response, but other than this no other controls were usable.

Also quick unrelated side note, the game is great, and I'm glad I can help out development by reporting bugs and suggestions :) Keep up the good work

**Comment by tsunamayo** [comment]
Nice find indeed! I can easily reproduce on my side. Actually I think having that option in the identity block doesn't make any sense, so I will remove it, and give another way of loading blueprint with a special starter block.

**Comment by tsunamayo** [comment]
Okay the issue is fixed! Thanks a lot!

**Comment by AlexJHockley** [comment]
Awesome, glad I could help! I'll keep posting here if I find anything else.
