### ISSUE TITLE
[Suggestion] Default Block Color

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1670]
For some objects in the codex I'd recommend changing their default colors (when placed and how they look in the codex) to the standard grey that most other things are. Namely for the sense of survival because it wouldn't really make sense to craft up some things and have their color be red/yellow/blue/green/etc. Now for some things it's perfectly fine. Examples being anything that can be painted with 2 colors like potentially the doors (once we can eventually paint their frames as well). It also just makes building more sensical from my point of view because it can be pretty distracting or a little annoying to be building in greys then have to paint pipe to match the grey. Now sure players will possibly want to paint pipes in different colors but then the survival argument could be made.
![20200328232300_1](https://user-images.githubusercontent.com/32974671/77840331-e5328280-714b-11ea-8312-b26b8e439a97.jpg)

**Comment by tsunamayo** [comment]
Yes I made myself the same remark, I need to separate the Icon paint from the default paint. Will do.

**Comment by tsunamayo** [comment]
Okay this will be fixed for next update! Cheers
