### ISSUE TITLE
[Inquiry/Suggestion] Build/Break Reach

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1671]
### Short Description of the issue:
In the latest build(s) did you change how far/close the player has to be in order to place or break blocks? To me it feels as if it got a lot shorter and that kind of makes stretching more of a pain
...

### Environment
- Skywanderers version: 20w13b
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Okay indeed, I increase the range by 50%. WIll be in 20w14a. Thanks
