### ISSUE TITLE
[BUG] Rename Entity Icon

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1672]
### Short Description of the issue:
Previously the icon outlined in red was a pencil, indicating that it was for renaming your ship. Now it's a white square, which is not obvious as a button.
![image](https://user-images.githubusercontent.com/27857711/77957355-459bfe00-72cb-11ea-9b7b-9b841f917c92.png)

### Steps to reproduce the issue:
Open up the drone menu with a ship selected
...

### Environment
- Skywanderers version: 20w13b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Thanks indeed, this will be fixed in next update. Thanks!
