### ISSUE TITLE
[BUG] Random red and green dot

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#1676]
### Short Description of the issue:
While I was testing the speed of my ship, I noticed a red and green dot just randomly out in space. I flew around and it followed my ship.

### Steps to reproduce the issue:
It's just there

### Environment
- Skywanderers version: 20w13b
- Graphics Card: 1050 ti

### Additional information:

![20200401123701_1](https://user-images.githubusercontent.com/39653820/78133042-ac2d3300-7415-11ea-9dd2-e28a8880a718.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4414798/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I saw that too ;)

**Comment by tsunamayo** [comment]
This issue will be fixed in next patch, 20w14b or latest. Thanks!
