### ISSUE TITLE
Player customization shows default torso image after restarting the game

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#168]
![20171025004219_1](https://user-images.githubusercontent.com/5714543/31982337-0e29e78e-b91e-11e7-8145-4a9457ca9fff.jpg)

Tested this after the new build.

Notice how the torso says Imperial but the image is the default blue torso. The other bodyparts save and display correctly. This happens in the title screen customization and the single player customization.

**Comment by tsunamayo** [comment]
Hi, I dont reproduce this issue. Could please tell me if you get this again, and if you could you please send me your output_log file inside the game steam install folder? Thanks!

**Comment by ike709** [comment]
I can still reproduce it. Just customize a character, click Done, close the game, reopen it, and go to character customization and will have the default torso instead of the one you select.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1416598/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I got the test case right, we had to click once on Done and then exit. It is fixed now! Thanks!
