### ISSUE TITLE
[Bug] Ship Core categories

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1680]
### Short Description of the issue:
There are two duplicate Heat categories in the Ship Core
![image](https://user-images.githubusercontent.com/27857711/78208211-be51b480-749b-11ea-9e8b-0f36a650c1af.png)

### Steps to reproduce the issue:
Open up the ship core and count the Heat categories

### Environment
- Skywanderers version: 20w14a
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
Yes it was a placeholder for shield. Will do it for next patch!

**Comment by ProPeach** [comment]
Great!

**Comment by tsunamayo** [comment]
Will be live in upcoming 20w14b. Thanks!
