### ISSUE TITLE
[Bug] Turret targeting broken

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1682]
It seems that the turret is not wanting to target the new target. I have tried this with both rotator-hinge turrets and rotator-rotator. The former's rotator failed to turn while the latter did this...
https://cdn.discordapp.com/attachments/271723356795961345/695112253703192637/Skywanderers_2020-04-01_20-27-19.mp4
After trying to fix it, I could no longer fly the ship. I could enter the yoke, but no HUD came up. Not sure if this is related to the issue above or is another problem

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4418759/output_log.txt)

**Comment by Aiwii** [comment]
![image](https://user-images.githubusercontent.com/53021785/78208654-21265a00-7462-11ea-9b2c-c6b295d94ec9.png)
Rotor menu also has some issues

**Comment by tsunamayo** [comment]
@ZachZent could you please send me your blueprint? There is a new collision baking feature for turret, so we have better FPS during combat. The small map is just a debugging tool, still wip. If you check a rotator linked to a turret you will see a 1D or 2D map of allowed positions.

**Comment by tsunamayo** [comment]
Okay looking at your video it seems like a different issue. Definitely need your bp to investigate! Cheers

**Comment by ZachZent** [comment]
[Prototype 1.zip](https://github.com/tsunamayo/Skywanderers/files/4419065/Prototype.1.zip)

Here you go

**Comment by tsunamayo** [comment]
I fixed the issue, will be available in 20w14b. Thanks a lot!
