### ISSUE TITLE
[Bug] Inconsistent collision of brick thrusters

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1685]
### Short Description of the issue:
Thanks to the improved collisions on the brick thrusters, we can build bricks nice and close to the curvature of the thruster. Thanks so much for this!
This is a 2m diameter brick thruster.
![image](https://user-images.githubusercontent.com/27857711/78365804-893a8480-75b7-11ea-883c-60c58c0fbd89.png)

Wedges can be build close to the thruster, following the curve nicely.
![image](https://user-images.githubusercontent.com/27857711/78365873-9d7e8180-75b7-11ea-8edc-4fb3e6ecfdc9.png)

However, there are some spots which behave strangely. Here I try to place a brick in a space which should be unobstructed by the thruster, especially as the wedges are closer to it.
![image](https://user-images.githubusercontent.com/27857711/78365891-a3746280-75b7-11ea-8f18-ad6ab2ed87c8.png)

I can place a tetra this way up...
![image](https://user-images.githubusercontent.com/27857711/78366377-51800c80-75b8-11ea-90d7-1a7132e2fc6f.png)

But if I try placing one rotated 180 degrees to the previous position, I can't.
![image](https://user-images.githubusercontent.com/27857711/78366409-5d6bce80-75b8-11ea-98dc-9e872ba4220a.png)

Without the thruster there all placement behaves as expected.
![image](https://user-images.githubusercontent.com/27857711/78365900-a707e980-75b7-11ea-928c-620772984d92.png)

Other than this, their collision meshes are perfect.

### Environment
- Skywanderers version: 20w14a
- Graphics Card: RX 580

**Comment by ProPeach** [comment]
Did a little more testing, this is a 4m diameter thruster.
As before, I can't place a cube brick anywhere inside the thruster boundary box, even when there is plenty of room visually and these wedges work fine.
![image](https://user-images.githubusercontent.com/27857711/78367073-6c9f4c00-75b9-11ea-8c8e-31c05efe75e1.png)
But wedges don't always work, it seems they can only be placed in that one orientation. same with tetras and any brick with an angled face
![image](https://user-images.githubusercontent.com/27857711/78367280-b5570500-75b9-11ea-9789-5b801f9a0a7f.png)

**Comment by tsunamayo** [comment]
Okay, I think I understand why - I am on it. Thanks

**Comment by tsunamayo** [comment]
I have added the remaining feature for the cylinder shape, now these case are working as expected! Will be in 20w14b. Thanks!
