### ISSUE TITLE
[Bug] Scanline effect when HUD is hidden

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1687]
### Short Description of the issue:
Sometimes hitting F2 to hide your HUD also applies a scanline effect similar to the old camera overlay or the white/red placement hologram. Hitting F2 again to show the HUD disables it.
![image](https://user-images.githubusercontent.com/27857711/78373464-8abd7a00-75c2-11ea-9a74-d4d4153e5ab2.png)
You can see it applied to this screenshot, it's most noticeable when you toggle it.

### Steps to reproduce the issue:
Sadly I haven't been able to find a method yet to reproduce this 100% of the time, it seems random at least for now. I'll update this thread if I do find a concrete cause.

### Environment
- Skywanderers version: 20w14a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Thanks mate, you are on a roll bug report wise!

**Comment by tsunamayo** [comment]
This issue will be fixed for 20w14b. Thanks a lot!
