### ISSUE TITLE
[Bug] Timer Gate Decimals

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#1688]
Hello,

It seems like the Timer Gate doesn't accept decimals anymore, any modification that uses a dot will not be saved.

Commas can not be used either.

- Skywanderers version: 20w14a
- Graphics Card: GTX 980
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4429050/output_log.txt)

**Comment by tsunamayo** [comment]
I cant reproduce this issue, I can type decimal and it will work as expected. 
I did fix an error where you input nothing and it would spit an error as seen in your log. 
You confirm the issue on a fresh entity?
If someone could try also that would be great.
I wonder if it could be linked to your locale...

**Comment by ProPeach** [comment]
I'm able to input decimals into the Timer Gate using the "." key as expected and it saves, which kind of keyboard are you using Name11ess?

**Comment by Name11ess** [comment]
For some reason I also have the issue with the other command blocks. 
I've got a pretty standard [DasKeyboard](https://m.media-amazon.com/images/S/aplus-media/vc/b765dd9d-e27c-432c-a5c5-ad4429a78d22._SR970,300_.jpg). Using the dot key either from the numpad or standard one doesn't change anything.

In this video, I'm setting 1.2 seconds delay, close the Timer Window, and reopen it twice without making any change.
1st time: "01" has automatically replaced "1.2"
2nd time: "1" has automatically replaced "01"

https://youtu.be/xnVlBFJQlPE

**Comment by tsunamayo** [comment]
@Name11ess what is your computer locale? (french?) Thanks

**Comment by Name11ess** [comment]
My computer is indeed in french and the keyboard is set in FRA INTL (Qwerty US International).

**Comment by tsunamayo** [comment]
@Name11ess okay desole pour le temps que ca a pris.
J ai pu reproduire, apparement le local Francais n accepte que des virgules ( , ) a la place du point ( . ) pour les decimaux...
J ai pu contourner le probleme, maintenant ca marche avec virgule et point.
Fix dispo en 20w16d. Merci ;) !

**Comment by Name11ess** [comment]
Merci !
