### ISSUE TITLE
Bugs/Suggestions

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#169]
Couple of hours messing in start area, some suggestions, found some bugs & other issues.

- Steam game id 711980
- Page Down button isn't recognised when trying to remap keys
- Hovercar - no access to menu when in space (Yeah... more on that later)
- coordinates required on Ring; found a lake on dark side which glitches through ring into space
- Gravity for character on Ring, please
- Consolidate the 'use' buttons, please

- After spending time in Hovercar in 3rd person, the cam has a weird 'slightly leaning to the left' glitch, as if there is a roll that hasn't stablised & recentred itself. This is evident in character but manifests in Hovercar as well.
- 3rd person camera modifier to look in same direction as travel; as it is, it gets confusing very quickly with the dual free look/direction set up & figuring out which direction you're traveling at high speed.
- Park/full stop for Hovercar - mine retained momentum even if I tried to make it stop, it keeps crawling along. Something like double tap the back button to stop all movement?
- Hovercars will quite happily skip out of the Ring using the wall hill terrain & head off into deep space, as I found out. Similarly, high speed terrain jumping launches you into a high trajectory (a fun thing!) especially at high speed. Fun, great, brilliant, but maybe a gravity binding to prevent deep space travel high jinx occurring?

**Comment by Gadget100** [comment]
Re hovercar: I also found it very hard to control - a bit like trying to drive a car on ice - in that it was very difficult to stop or manoeuvre with any accuracy.

Driving over hills is quite good fun, but the lack of control makes it hard to recover afterwards.

I too have also fallen through water into space on occasion.

**Comment by tsunamayo** [comment]
@Nexusdog glad to see you in the game at last! Thanks for reporting the bugs. Could you please book a single issue per github issue - as this tool is made for me to track which issue are fixed and yet to be fixed, and it will make any potential discussion either to follow. Cheers

**Comment by Nexusdog** [comment]
Ah, my apologies Francois - I shall make amends. 

@Gadget100 I enjoyed the drifting, felt really natural for the vehicle. Also reminded me of riding my motorcycle back in the day, so might be the reason I felt comfortable with the way it handled.
