### ISSUE TITLE
[Bug] Sticky Mirror Planes

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1693]
### Short Description of the issue:
1. Unspawning an entity with a mirror plane leaves the mirror plane stuck in the world
2. Mirror planes move around with you if you teleport to another ship while they are on
...

### Steps to reproduce the issue:
For issue 1:
- Create an Entity
- Turn on Mirror
- Use bot to unspawn entity while mirror is still on
- Issue

For issue 2:
- Create an entity and put mirror on it
- Press F7 and teleport to another ship
- Issue
...

### Environment
- Skywanderers version: 20w14a
- Graphics Card: Integrated Graphics

### Additional information:
![Skywanderers 2020-04-06 9_23_08 PM](https://user-images.githubusercontent.com/53021785/78626968-88bb1b80-784d-11ea-884e-7e5bfa3a7264.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4441881/output_log.txt)

**Comment by tsunamayo** [comment]
For 1) do you confirm it was stuck only for a few seconds and then gone? Thanks

**Comment by tsunamayo** [comment]
I cant reproduce both issue... Weird, as both issue should have been fixed for 20w14a... If somebody else could confirm the test case that would help.
Thanks

**Comment by Aiwii** [comment]
For issue number one it seems to be stuck permanently https://streamable.com/giubdn

**Comment by Xerma** [comment]
For myself at least I found that restarting the game takes care of those ghost mirrors

**Comment by tsunamayo** [comment]
@Xerma of course it does, but thats not a valid fix ;) So you also reproduce this issue in 20w14a ? Thanks

**Comment by Xerma** [comment]
I can confirm that I'm getting this bug in 20w14a - You can at least delete them with the mirror tool itself.
![20200407214335_1](https://user-images.githubusercontent.com/32974671/78739012-f2542c00-7918-11ea-9d8b-6fd07cbde29a.jpg)

**Comment by tsunamayo** [comment]
So could you confirm:
1) you load and jump in the game
2) put a mirror on a ship
3) delete the ship
4) observe that the mirror is still there.

Because it works fine for me. If you could send me your output.log while doing this test case that would be great! 
Thanks

**Comment by tsunamayo** [comment]
Ah okay, I think the issue might not be live yet, please wait for the next build. I forgot to tell on which build the fix would be live, and I guess I fixed it just after the latest build. Thanks!

**Comment by Xerma** [comment]
Ah ok, I'll give it a look when that comes out

**Comment by tsunamayo** [comment]
20w15a is live! Thanks

**Comment by tsunamayo** [comment]
@Xerma @Aiwii was it fine at the end? Cheers
