### ISSUE TITLE
[Multiplayer Bug] No seating animation and skin mismatch.

### ISSUE THREAD

**Issue by Arschpollo13** [tsunamayo/Skywanderers#1697]
I often build with a friend in skywanderes and we noticed that we never see the others sitting on the seat but always hovering over them. The other always looks through blocks.

And the characters are displayed differently, for me my friend is a girl and for him he is a boy.

his view
![Skywanderers_2020_04_08_19_01_54_366](https://user-images.githubusercontent.com/63169168/78813193-ede94b00-79cc-11ea-973e-225b1645a522.jpg)

my view
![Screenshot (16)](https://user-images.githubusercontent.com/63169168/78813203-f0e43b80-79cc-11ea-83dc-405304fa50a6.png)

**Comment by tsunamayo** [comment]
Both issue will be fixed for 20w15c. Thanks!
