### ISSUE TITLE
[Multiplayer Bug] Spawned blueprints are invisible for other players

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Skywanderers#1699]
### Short Description of the issue:
spawned blueprints are invisible for other players

### Steps to reproduce the issue:
let a second player join your server. He can see everything you spawned before he joined. However, if after joining you or the second player spawned a blueprint, this is only visible to those who spawned the blueprint

### Environment
- Skywanderers version: 20w14a
- Graphics Card: 1070 (Mobile)

### Additional information:
Me and my mate have seen the same error, also after restart or reset,

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4452034/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w15c. Thanks a lot for testing out multiplayer!
