### ISSUE TITLE
Singleplayer Game Options is easily broken

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#170]
![20171025005556_1](https://user-images.githubusercontent.com/5714543/31982685-92daaad0-b91f-11e7-83e7-dfbeb1f6e073.jpg)

Tested after the lasted build.

Repro steps once you're in singleplayer:
Escape > Options > Game > Player Customization > Done > Done > Escape (Closes menu) > Escape (Reopens menu) > Game

Doesn't occur in the title screen menu.

**Comment by tsunamayo** [comment]
It should be fixed in the next version. Thanks a lot - you are a very precious bug hunter so far!

**Comment by HadesDeadlyTom** [comment]
Yep, don't know how i got this but i think it's the same 
![ss 2017-10-25 at 01 44 01](https://user-images.githubusercontent.com/33090879/31997229-7bf1da48-b98b-11e7-9dab-20b8a945b464.jpg)

**Comment by ike709** [comment]
Based on #194 and #195, this still seems to occur in the latest build.

**Comment by AssIn9** [comment]
![image](https://user-images.githubusercontent.com/6031455/32026922-2fd7d418-b9b4-11e7-80aa-7f51bb0a9c11.png)

**Comment by tsunamayo** [comment]
I fixed the issue - but you will only see it in the next build. Thanks for your help!
