### ISSUE TITLE
[Bug] Mass calculation for stretched blocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1703]
### Short Description of the issue:
Mass no longer calculated correctly for stretched bricks and blocks, the mass is always the same as the base block/brick no matter how large you stretch it. Thank you for implementing accurate masses for different block shapes though!

One block - 200kg
![image](https://user-images.githubusercontent.com/27857711/78915919-94dcee00-7a84-11ea-86ce-ddea69e6b5e9.png)

One stretched block - 200kg
![image](https://user-images.githubusercontent.com/27857711/78915941-9c03fc00-7a84-11ea-8445-4e374ce71a60.png)
The masses in the codex still show the mass of a full block too

### Steps to reproduce the issue:
Place different sized blocks on a rotor to easily show their mass

### Environment
- Skywanderers version: 20w15a
- Graphics Card: RX 580

**Comment by Battlepixel** [comment]
The mass was previously only correctly calculated for cubic blocks. (SmallBlockmass was much too big, among other things) We have the same bug that resulted from the recent fixed attempt. Regardless: Great praise to the dev for the quick reaction to the bugposts in this regard! Keep it up*

**Comment by tsunamayo** [comment]
Okay it was a miss on my part - this is a pretty big one. It is fixed. I am closing a bunch more issue and I push a new build today 20w15b. Thanks!

**Comment by ProPeach** [comment]
Amazing, thank you!
