### ISSUE TITLE
[Suggestion] Velocity unit

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1705]
Personally I feel that meters per second is a more appropriate unit for space games as it ties neatly into other units of measurement used across the game that also use seconds. Most other space games I have played also use m/s too so it's more useful for comparison sake, as well as not feel comfortable to other players starting to play Skywanderers. 
I suggest that you revert the unit back to meters per second, and then include an option to change it to km/s in the settings as that provides the best of both worlds and brings Skywanderers in line with other games as they also have m/s as the standard with an optional toggle between them.

**Comment by tsunamayo** [comment]
Fair enough, if that s the standard then I am sticking to it. I wont have time for a toggle though. Will be in 20w15b. Thanks!

**Comment by ProPeach** [comment]
Great!
