### ISSUE TITLE
[Bug] Beam effect stays if beam is destroyed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1707]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/27857711/78938524-4b06fe80-7aaa-11ea-9b9f-47bfb50e242a.png)

If you break a beam block while it is firing, the beam stays forever

### Steps to reproduce the issue:
Fire a beam, then break the beam block

### Environment
- Skywanderers version: 20w15a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 20w15b. Thanks!
