### ISSUE TITLE
[Bug] Gravity Unit default value

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1708]
### Short Description of the issue:
When you place a Gravity Unit, the default value for gravity strength is -1 rather than 1. This means that the field is actually being generated in the opposite direction to the placement guide arrow and the falling apple icon - both of which are awesome.

### Steps to reproduce the issue:
Place a gravity generator and check the default gravity strength

### Environment
- Skywanderers version: 20w15a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Thanks for being so active! Issue fixed for 20w15b. Cheers
