### ISSUE TITLE
[BUG] Player model has to be changed on MP in order for animations to work

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1709]
When a client joins the server, they see the host in the flying pose, even when in walking mode: 
![image](https://user-images.githubusercontent.com/29961381/78940333-92db5500-7aad-11ea-927f-288316532e4a.png)
This is only fixed once the host changes their player model.

**Comment by tsunamayo** [comment]
Yes I noticed that also, I am on it. Thanks!

**Comment by tsunamayo** [comment]
This will be fixed for 20w15c. Thanks a lot!
