### ISSUE TITLE
[Suggestion] Display a version number we can submit when creating bug reports

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#171]
Put the game's version number in one of the corners so we can report which version of the game a bug occurs on.

Unless, of course, I'm dumb and this information is already available.

**Comment by tsunamayo** [comment]
Yes I agree I was looking on a non manual way of doing this, I will also setup experimental build for the bravest out there. Thanks

**Comment by AfterRebelion** [comment]
There is a version number in the title screen now, so this issue is no longer valid in recent versions (19w23b haha, I posted a version number in a open issue about not having a version number 💃 )

**Comment by tsunamayo** [comment]
I added also a version number game overlay in 19w30a. Thanks
