### ISSUE TITLE
[BUG] In multiplayer, the player stays in the sitting animation 

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1710]
When in multiplayer, if a client sits down in a chair and gets up again, their player model doesn't change from the sitting pose: 

![image](https://user-images.githubusercontent.com/29961381/78941128-fade6b00-7aae-11ea-8ca4-850bf0cd6633.png)
![image](https://user-images.githubusercontent.com/29961381/78941148-016ce280-7aaf-11ea-94b6-612a452552b2.png)

**Comment by tsunamayo** [comment]
Lol, yes I also noticed that, I am on it. Cheers

**Comment by tsunamayo** [comment]
Issue fixed for 20w15c. Thanks a lot!
