### ISSUE TITLE
[BUG] Multiplayer ship interaction issues

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1712]
When in multiplayer, only the host of the game can be seen flying ships by all clients. If a client attempts to fly a ship, only the them and the host can see that ship move.

**Comment by tsunamayo** [comment]
Okay thanks, that will be hard for me to reproduce, I dont know if my pc will handle 3 sessions... I keep you posted.

**Comment by Womble-TC** [comment]
If you need anyone to help test this, I'm willing to help out.

**Comment by tsunamayo** [comment]
I manage to reproduce and fix the issue! We will be able to shoot soon ;)
