### ISSUE TITLE
[BUG] Multiplayer Blueprint spawning issue 

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#1713]
Well, hello tsuna, welcome to another multiplayer github post.

When in multiplayer, if the host spawns in a blueprint, no clients can see or interact with the blueprint in any way. This issue is fixed when the server is restarted. Clients cannot spawn blueprints by themselves, as they have no drones.

Thanks, and see you in the next one.

**Comment by Battlepixel** [comment]
#1699

**Comment by tsunamayo** [comment]
Issue fixed for 20w15c. Thanks a lot for testing out multiplayer ;)!
