### ISSUE TITLE
[Bug] Multiplayer Clears World Files and Creates New Character. 

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1717]
### Short Description of the issue:
After a short multiplayer session when I came back to the game to work on some builds I found two character files. One of which is mine and the other blank with no name. The blank one loaded up my last position in the multiplayer session and the ship I was interacting with. When I tried to load MY game file my character loaded in the right position but none of the ships I left in the world were still there.
...

### Steps to reproduce the issue:
- Create a character and put some ships in the world
- Join a multiplayer game (as a client, not as host)
- Do stuff
- Leave session and try to load the local world file
...

### Environment
- Skywanderers version: 20w15b
- Graphics Card: Integrated Graphics

### Additional information:
![image](https://user-images.githubusercontent.com/53021785/79020637-9961df00-7b36-11ea-9f9b-4b437d65af08.png)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4463285/output_log.txt)

**Comment by PopkaAkula** [comment]
I also experienced this

**Comment by Womble-TC** [comment]
This happened a few people on the server yesterday, according to some (propeach) it only happened when you press F1 in the server.

**Comment by tsunamayo** [comment]
So F1 on the server are you sure? Not F1 on the client? Anyway I will do two changes, 1) auto-save and 2) Instance by players, which both should fix naturally this issue.
Thanks

**Comment by Womble-TC** [comment]
sorry, F1 while _connected_ to the serer, so the client.

**Comment by tsunamayo** [comment]
Yes okay make sense. I am fixing this, the normal behaviour should be no save in multiplayer. Is that what other game are doing?

**Comment by ProPeach** [comment]
In my experience only the host can save the world in other games, but clients can still save blueprints of individual ships etc

**Comment by Aiwii** [comment]
I don't think clientside should have multiplayer sessions save over their worlds. Only the host should be able to save and it should be to their file only. I don't think any other games have mp where the client saves the host's world.

**Comment by Xerma** [comment]
In all other games it tends to be a dedicated server that hosts the game while clients connect and the server saves their characters but the players have no need or option to save while in the server. Disconnecting from a server usually saves that persons character/progress.

So only the host should be saving

**Comment by tsunamayo** [comment]
So starting from 20w16a only the host can save. But you can still export any bp on the client side. Thanks!
