### ISSUE TITLE
Supercharger won't delete

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1719]
### Short Description of the issue:
As I was testing out what items didn't mirror properly, I tried placing a supercharger on a laser weapon ==while it was mirrored incorrectly== but then it started making constant particles so I tried restarting (I saved my game out of habit before exiting) Once I loaded in again it seems the supercharger did in fact mirror once I reloaded into the game. And turns out the supercharger will remain on the build now even though the laser weapon is gone and I cannot delete the supercharger(s). Respawning the ship via drone does not fix either and going near these superchargers causes extreme FPS drops.

I don't know if a bug fix will fix my problem entirely or not but if not, could you manually remove the superchargers? The ship save file will be included below for you to check out as well

I'll keep looking at the things that don't mirror correctly.
...

### Environment
- Skywanderers version: 20w15b
- Graphics Card: GTX 970

### Additional information:
Incorrectly mirrored laser weapons
![20200410185043_1](https://user-images.githubusercontent.com/32974671/79030337-279d8b80-7b5e-11ea-9d83-b0e3985079a4.jpg)
Seemingly fine mirroring of the supercharger seeing as the spot across the mirror does not have a slot right there
![20200410185219_1](https://user-images.githubusercontent.com/32974671/79030359-40a63c80-7b5e-11ea-9179-ee1ac1f5a753.jpg)
Constant particles and cannot delete
![20200410185256_1](https://user-images.githubusercontent.com/32974671/79030371-4b60d180-7b5e-11ea-9985-f7dbb3308457.jpg)
Reload and the supercharger mirrored
![20200410185351_1](https://user-images.githubusercontent.com/32974671/79030384-5582d000-7b5e-11ea-8ba5-c463791cfbd6.jpg)
No laser weapon and the superchargers remain
![20200410185403_1](https://user-images.githubusercontent.com/32974671/79030405-692e3680-7b5e-11ea-917a-36f4cd42c266.jpg)
Respawned ship
![20200410185702_1](https://user-images.githubusercontent.com/32974671/79030412-6e8b8100-7b5e-11ea-81e1-ea1546852f8b.jpg)

**Comment by Xerma** [comment]
The ship:
[Manta - X - BUGGED.zip](https://github.com/tsunamayo/Skywanderers/files/4463761/Manta.-.X.-.BUGGED.zip)

**Comment by Aiwii** [comment]
[SK38 Aphrysus.zip](https://github.com/tsunamayo/Skywanderers/files/4463786/SK38.Aphrysus.zip)
I got one too

**Comment by tsunamayo** [comment]
Thanks, this save corruption is a serious one, I am not it!

**Comment by Aiwii** [comment]
![image](https://user-images.githubusercontent.com/53021785/79031307-2c147500-7b5b-11ea-9c83-e9f64d65b704.png)
Just to add mirrors and superchargers are not going well together. I think it causes the lasers aren't properly mirroring orientation.

**Comment by tsunamayo** [comment]
All issue are fixed: addon now cannot be build if there is no addon slot in symmetry, beam / laser symmetry, and your save will load correctly.
Available in 20w15d.
Thanks!
