### ISSUE TITLE
Mouse cursor issues with the menu UIs

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Skywanderers#172]
Holding one of the WASD keys or one of the arrow keys for a couple seconds with seemingly any menu open has odd effects.

In the title screen menus, the cursor vanishes. It will reappear in the center after you move the mouse.

In the singleplayer menus, the cursor jumps to the center of the screen but doesn't vanish.

**Comment by tsunamayo** [comment]
Oh thanks for pointing that one - it was a weird behaviour of my UI Unity plugin. It is now fixed! Thanks
