### ISSUE TITLE
All that doesn't mirror correctly

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1721]
### Short Description of the issue:
As the title implies, this is just to let you know about all that doesn't mirror correctly:

### Blocks/bricks
- All weapons (and addons since weapons don't mirror correctly)
- Yoke
- Fence Corner
### Markings
- Triangle
- Quarter Disk
- Stripes
- Cricle Lines
### Details
- Creased Triangle
- Creased Vert Triangle
- Vent Holes
- Creased Rectangle
### Painting items
- Thruster (If they're larger than 1x1x1m)
- Power Reactor (If they're larger than 1x1x1m)
- Shield Unit (If they're larger than 1x1x1m)
...

### Environment
- Skywanderers version: 20w15c
- Graphics Card: GTX 970

### Additional information:
![20200410192937_1](https://user-images.githubusercontent.com/32974671/79031474-8534d680-7b64-11ea-94da-c13947f41412.jpg)
![20200410193030_1](https://user-images.githubusercontent.com/32974671/79031475-86fe9a00-7b64-11ea-8f91-429272e086f4.jpg)
![20200410193240_1](https://user-images.githubusercontent.com/32974671/79031476-88c85d80-7b64-11ea-86ee-ebb8b6c48433.jpg)
![20200410193308_1](https://user-images.githubusercontent.com/32974671/79031477-8b2ab780-7b64-11ea-8e4c-434e1ac2d3bc.jpg)
![20200410193349_1](https://user-images.githubusercontent.com/32974671/79031480-8cf47b00-7b64-11ea-95a4-82231dc6c867.jpg)
![20200410193400_1](https://user-images.githubusercontent.com/32974671/79031481-8e25a800-7b64-11ea-87d9-151b1613a153.jpg)
![20200410193504_1](https://user-images.githubusercontent.com/32974671/79031482-8fef6b80-7b64-11ea-9787-bd4bb9ce9c63.jpg)
![20200410193519_1](https://user-images.githubusercontent.com/32974671/79031483-91209880-7b64-11ea-914f-63bb6fd0c3e4.jpg)
![20200410193715_1](https://user-images.githubusercontent.com/32974671/79031484-9251c580-7b64-11ea-9448-01c8bbf0c61f.jpg)
![20200410193804_1](https://user-images.githubusercontent.com/32974671/79031486-941b8900-7b64-11ea-8299-e01601fa592d.jpg)
![20200410195143_1](https://user-images.githubusercontent.com/32974671/79031510-bc0aec80-7b64-11ea-9259-83fc942c4cbe.jpg)

**Comment by tsunamayo** [comment]
Yay, thanks a lot for the list, the last one was a bug with paint and symmetry. It is all fixed, 20w15d incoming! Cheers mate, glad to have guy like you on the big push to ea!
