### ISSUE TITLE
[Suggestion/Visual Bug] Weapon Addon Visuals

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1722]
### Short Description of the issue:
In the picture below you can see the addon visually clip into the notch where it's attached. This is by no means an important thing to fix but I might suggest changing that to a cylinder connecting notch instead just to make it visually connect without being a large pain. Although the addons don't rotate but also don't stretch or take a large amount of room so rotating isn't all that necessary.
...

### Environment
- Skywanderers version: 20w15c
- Graphics Card: GTX 970

### Additional information:
![20200411020924_1](https://user-images.githubusercontent.com/32974671/79037807-e9be5880-7b99-11ea-96bb-b6ad16943534.jpg)

**Comment by tsunamayo** [comment]
Hoh yes it is a bug, rotation should lock to match the addon slot.

**Comment by tsunamayo** [comment]
Issue fixed for 20w16a! Thanks ;)
