### ISSUE TITLE
[Bug] Turret movement in multiplayer

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#1725]
### Short Description of the issue:

Turret movement is client-side in a server

### Steps to reproduce the issue:

Have someone control a turret in a server and observe the lack of movement

### Environment
- Skywanderers version: 20w15c

**Comment by tsunamayo** [comment]
Turret are now functional in mp in all the numerous case. Will be on 20w16d.
Cheers!
