### ISSUE TITLE
[BUG] Paint Tab in Blocks Codex remembers previous tab scroll

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#173]
When in the blocks codex, if the user scrolls down a long distance in one tab, then clicks on the paint tab, the paint tab remembers the distance scrolled down in the previous tab. This means that the paints are outside the bounds of the selection window and cannot be seen. This can only be fixed by either returning to another tab and scrolling up there, then going back to the paint tab, or by finding the paint tab's scroll bar, which will only be a few pixels high when this bug is active.

![20171025011956_1](https://user-images.githubusercontent.com/33041786/31983381-b22d09ca-b922-11e7-9b13-4e4145606ce3.jpg)

**Comment by tsunamayo** [comment]
Thanks for that one, it is now fixed! Cheers
