### ISSUE TITLE
[Bug] Velocity Unit in Ship Core

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1730]
### Short Description of the issue:
The unit used in the ship core is still km/h although the game now uses m/s to measure velocity. Sorry for making more work for you 😝 
![image](https://user-images.githubusercontent.com/27857711/79045018-c4b10080-7c00-11ea-90f3-8bc9f5e733a1.png)

### Steps to reproduce the issue:
Open up the ship core and check the stats relating to velocity

### Environment
- Skywanderers version: 20w15d
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Hehe no pb, thats an easy change ;)

**Comment by tsunamayo** [comment]
Fixed, will be in 20w15e. Cheers
