### ISSUE TITLE
[Bug] Codex labeling 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1731]
### Short Description of the issue:
The mass values for different shaped blocks are all labeled as the same for their full block counterparts, despite the game now calculating mass more accurately now.
Here, the wedge should have a mass of 75kg rather than 150kg like the cube.
![image](https://user-images.githubusercontent.com/27857711/79045115-54ef4580-7c01-11ea-9394-2968bf34962d.png)

On another note, not all brick shapes are labeled with the "S" symbol for bricks. I think that this would help new players understand the codex a little better.
![image](https://user-images.githubusercontent.com/27857711/79045213-d5ae4180-7c01-11ea-9513-1eec5294efae.png)

### Steps to reproduce the issue:
Open up the codex and check the mass values as well as the labeling of bricks.

### Environment
- Skywanderers version: 20w15d
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
So initially the on the icon was to make a different when two similar block exist. So its not necessarily for new player... Otherwise I would have to put [s] on all block, including gate, button ect, it seems overkill... 
Not sure yet about this. I will fix the mass though.

**Comment by tsunamayo** [comment]
Mass fixed, I give more thinking for the other one, cheers
