### ISSUE TITLE
[Suggestion] Blueprint repair

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1732]
As we test combat more and more, repairing our ships after testing is becoming a large time sink.
At the moment damage to a ship persists if you save the damaged blueprint and spawn it again, I suggest that newly spawned blueprints are completely undamaged. This makes sense to me as the newly spawned blueprint is a whole new ship with the same design as the first, rather than the exact ship spawned again.

While the repair function of a shipyard can be used to repair a ship totally, it's not always practical if you're a distance away from the shipyard or have to repair multiple ships quickly.

Another thing that would help a lot is if the repair tool had a higher penetration on its beam, and perhaps if the damaged green areas showed through hull

**Comment by ExodistSKY1** [comment]
I wrote a report a little bit ago about the repair tool not repairing all the blocks when shooting at a target. 
   Having the repair tools penetration increased and possibly making it so that all close and interior damage is repaired first as opposed to missing a small brick on the interior of a ship and that remaining damaged would help.

**Comment by tsunamayo** [comment]
Yes it is buggy I also noticed that, it is bugged - I will fix it. 
Not sure yet about the best approach, as I have big plan for the future, with crew and potentially mini drones.
For now I think I will add a repair button in the drone menu, (will will change to a simple menu on TAB), that will only be there in creative - so we can test more easily.

**Comment by tsunamayo** [comment]
I added the repair feature to the drone UI - will be available in 20w16a. Thanks!
