### ISSUE TITLE
Older blueprint entities not moving

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1733]
### Short Description of the issue:
I began working on this new MTT build some time ago and built the functioning hatches on the front of it and they worked just fine back then so I'm not sure if they somehow 'clip' now due to reworking child entity collision or what. I did try re-linking the switches to the rotors but to no avail.

Newly placed and linked entities work on this build.

Would it be possible to get this fixed or might I need to build the child entities all over again?
...

### Environment
- Skywanderers version: 20w15d
- Graphics Card: GTX 970

### Additional information:
![20200411185822_1](https://user-images.githubusercontent.com/32974671/79060746-79254380-7c4e-11ea-9b97-c3f0d9e267fc.jpg)

[Legal MTT.zip](https://github.com/tsunamayo/Skywanderers/files/4465852/Legal.MTT.zip)

**Comment by Xerma** [comment]
Turns out it was just those two left/right corner wedge bricks that ended up having hitboxes the size of a standard brick so it was then "clipping" into the main hatch, therefore not opening

**Comment by tsunamayo** [comment]
Yes I just noticed this also. But after having made an improvement to the engine, where if it is stuck on open, but become less stuck the frame after, it continue to move.
Yes that was the reason  I removed those bricks, collision shape is not functional (as symmetry).
Thanks!
