### ISSUE TITLE
Tools in active hotbar hide mirror plane

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1736]
### Short Description of the issue:
This is basically as the title says, if you have any tool other than the symmetry tool in your active slot, the mirror plane gets hidden.
...

### Environment
- Skywanderers version: 20w15d
- Graphics Card: GTX 970

### Additional information:
![20200412025821_1](https://user-images.githubusercontent.com/32974671/79063831-cd89ec80-7c69-11ea-930a-4655e1224c92.jpg)
![20200412025824_1](https://user-images.githubusercontent.com/32974671/79063832-cebb1980-7c69-11ea-8e90-6859b57e35b4.jpg)
![20200412025831_1](https://user-images.githubusercontent.com/32974671/79063835-cfec4680-7c69-11ea-9294-4dea85d24672.jpg)
![20200412025837_1](https://user-images.githubusercontent.com/32974671/79063836-d1b60a00-7c69-11ea-92eb-4b376e0f94ba.jpg)

**Comment by tsunamayo** [comment]
Yes, this is on purpose, as those tool are not impacted by symmetry. When you hold nothing it also not shown - it just shown for brick and paint.

**Comment by Xerma** [comment]
Yep that makes sense, it just felt odd and I got confused on what changed then realized the mirror plane disappeared

**Comment by tsunamayo** [comment]
yeah I am not sure about that one, it is just so that people can forget about them when they stop building. Like you dont need to clean them, you just move on. thx
