### ISSUE TITLE
[I'm so sorry, I felt obligated to do this] Trap Queen for #1738

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1738]
[Intro]
RGF productions
Remy Boyz, yah-ah
1738, ayy

[Refrain]
I'm like "Hey, what's up? Hello" (Ayy)
Seen yo pretty ass soon as you came in the door
I just wanna chill, got a sack for us to roll
Married to the money, introduced her to my stove
Showed her how to whip it, now she remixin' for low
She my trap queen, let her hit the bando
We be countin' up, watch how far them bands go
We just set a goal, talkin' matchin' Lambos
At 56 a gram, 5 a hundred grams though
Man, I swear I love her, how she work the damn pole
Hit the strip club, we be lettin' bands go
Everybody hatin', we just call them fans, though
In love with the money, I ain't never lettin' go

[Chorus]
And I get high with my baby (My baby)
I just left the mall, I'm gettin' fly with my baby, yeah
And I can ride with my baby (My baby)
I be in the kitchen cookin' pies with my baby, yeah
And I can ride with my baby (My baby)
I just left the mall, I'm gettin' fly with my baby, yeah
And I can ride with my baby
I be in the kitchen cookin' pies

[Verse 1]
I'm like, "Hey, what's up? Hello"
I hit the strip with my trap queen, 'cause all we know is bands
I just might snatch up a 'Rari and buy my boo a Lamb'
I just might snatch her a necklace, drop a couple on a ring
She ain't wantin' for nothin' because I got her everything
It's big ZooWap from the bando
Remind me where I can't go
Remy Boyz got the stamp though
Count up hella them bands though
Boy how far can your bands go?
Fetty Wap, I'm livin' 50 thousand K how I stand though
If you checkin' for my pockets I'm like…

[Chorus]
And I get high with my baby (My baby)
I just left the mall, I'm gettin' fly with my baby, yeah
And I can ride with my baby (My baby)
I be in the kitchen cookin' pies with my baby, yeah
And I can ride with my baby (My baby)
I just left the mall, I'm gettin' fly with my baby, yeah
And I can ride with my baby (My baby)
I be in the kitchen cookin' pies

[Refrain]
I'm like, "Hey, what's up? Hello"
Seen yo pretty ass soon as you came in the door
I just wanna chill, got a sack for us to roll
Married to the money, introduced her to my stove
Showed her how to whip it, now she remixin' for low
She my trap queen, let her hit the bando
We be countin' up, watch how far them bands go
We just set a goal, talkin' matchin' Lambos
At 56 a gram, 5 a hundred grams though
Man, I swear I love her how she work the damn pole
Hit the strip club, we be lettin' bands go
Everybody hatin', we just call them fans though
In love with the money, I ain't never lettin' go

[Verse 2]
I be smokin' dope and you know Backwoods what I roll
Remy Boyz, Fetty eatin' shit up, that's fasho
I'll run in ya house, then I'll fuck your ho
'Cause Remy Boyz or nothin'
Re-Re-Remy Boyz or nothin', yeah

[Outro: Nitt Da Gritt]
Yeah, you hear my boy
Soundin' like a zillion bucks on the track
I got whatever on my boy, whatever
Put your money where your mouth is
Money on the wood make the game go good
Money out of sight cause fights
Put up or shut up, huh?
Nitt Da Gritt, RGF Productions
Squad

**Comment by ultrak2k** [comment]
delet this

**Comment by tsunamayo** [comment]
lol, I feel too old, I dont even know what it is...
