### ISSUE TITLE
[Bug] Mysterious heat dissipation changes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1739]
### Short Description of the issue:
While working on a ship (just painting it and adding stickers), it blew up due to heat. A little confused but assuming I'd miss-balanced some stats I spawned in the ship again and checked the stats -
Original heat values
![image](https://user-images.githubusercontent.com/27857711/79070369-466e6000-7ccd-11ea-9132-276c13562d21.png)
To me this looked fine; I was generating more power than I needed, and dissipating more heat than I was producing. So I continued painting and placing stickers until it blew up again. Something was wrong!

I spawned the original ship again and continued painting, but this time I checked the ship core a few minutes later. The values for heat dissipation had changed
![image](https://user-images.githubusercontent.com/27857711/79070345-1c1ca280-7ccd-11ea-9803-a6595adf8eac.png)

Later again after more painting and a few stickers placed they had changed so much that the ship blew up due to heat
![image](https://user-images.githubusercontent.com/27857711/79070381-66058880-7ccd-11ea-878b-73f6fef444d7.png)

### Steps to reproduce the issue:
Spawn the attached blueprint, check the heat values and do some painting (I was painting the wings)
After painting a few bricks, check the values again

I suspect this might be a difficult one to reproduce so I'll update this thread if I find anything else

### Environment
- Skywanderers version: 20w15d
- Graphics Card: RX 580
[Zeta-class Shuttle.zip](https://github.com/tsunamayo/Skywanderers/files/4466474/Zeta-class.Shuttle.zip)

**Comment by ProPeach** [comment]
Looks like the heat dissipation values only change when you place a sticker on the wings which are child entities, paint does not affect the dissipation value. Could this be due to the recent changes to surface area calculations?

**Comment by tsunamayo** [comment]
Okay, it seems a serious one, I am on it.

**Comment by tsunamayo** [comment]
Okay it was linked to children entity indeed - it is now all fixed. Fix in 20w16a - build is coming soon. Thanks!

**Comment by ProPeach** [comment]
Wow that was quick, thank you!
