### ISSUE TITLE
Unable to interact with logic, block menus, or entry systems

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#174]
The only thing working is building and breaking.

Loaded a save on the starter Torus, was able to navigate the block codex as well as place and destroy blocks.

Clicking on any button, seat, or core did nothing and didn't have the usual pink box.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1413609/output_log.txt)

**Comment by talrey** [comment]
Confirmed as working fine again for me, the latest patch fixed it.

**Comment by tsunamayo** [comment]
Hehe sorry Marc I did a bit of hotfixception in the last hour, it was fixed indeed. Thanks!
