### ISSUE TITLE
[Bug] Normal map sticker placement guide

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1740]
### Short Description of the issue:
The Creased Triangle normal map sticker has a square placement guide, despite being triangular in shape.
![image](https://user-images.githubusercontent.com/27857711/79072158-70c51b00-7cd7-11ea-991f-7f8ee27000b4.png)
Similarly the Bolt and Simple Hole stickers also have a square placement guide even though they're round.

The Creased Vert Triangle for example has a triangular guide which is useful to orient the sticker before placing.
![image](https://user-images.githubusercontent.com/27857711/79072161-73c00b80-7cd7-11ea-9d72-788939c1166b.png)

### Steps to reproduce the issue:
Grab a Creased Triangle sticker and have a look at the placement guide.

### Environment
- Skywanderers version: 20w15d
- Graphics Card: RX 580

**Comment by Aiwii** [comment]
I feel that all of them should have square placement guides to help with scaling

**Comment by ExodistSKY1** [comment]
Square (or possibly corner) placement guides paired with the specific sticker shape in the center?

**Comment by ProPeach** [comment]
That would be ideal!

**Comment by tsunamayo** [comment]
Issue fixed for 20w16a. There is a small 3d box to help for scaling - should get you covered! Thanks
