### ISSUE TITLE
[Bug] Paint colour labels

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1741]
### Short Description of the issue:
In the regular codex, the name of each colour is displayed when you roll your mouse over it
![image](https://user-images.githubusercontent.com/27857711/79072762-c0f1ac80-7cda-11ea-846d-c3cf207c3960.png)

When you do the same thing in the paint menu opened with the Q key, there is no label
![image](https://user-images.githubusercontent.com/27857711/79072785-d23ab900-7cda-11ea-8465-f895025dba75.png)

### Steps to reproduce the issue:
Roll over a paint in the codex and the paint menu

### Environment
- Skywanderers version: 20w15d
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Yes, but it is a bit silly as there is nothing in the 3d preview... But I will add it, thanks

**Comment by tsunamayo** [comment]
Issue fixed for 20w16a. Thanks ;)
