### ISSUE TITLE
[Bug] Brick Side Addons can't be placed.

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1744]
### Short Description of the issue:
In certain positions and orientations for a brick laser or beam weapon addons can't be placed on them.
...

### Steps to reproduce the issue:
- Place multiple weapons each rotated in a different orientation and positions
- Try to place addons
- Issue
...

### Environment
- Skywanderers version: 20w15d
- Graphics Card: Integrated Graphics

### Additional information:
![image](https://user-images.githubusercontent.com/53021785/79083255-61030200-7cea-11ea-84af-971a496a9d4e.png)
![Skywanderers 2020-04-12 6_20_52 PM](https://user-images.githubusercontent.com/53021785/79083258-67917980-7cea-11ea-8001-a9e6fbb1b17f.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4467442/output_log.txt)

**Comment by tsunamayo** [comment]
Issue will be fixed in 20w16a. Thanks for building and reporting a lot! Cheers
