### ISSUE TITLE
[Bug] Drone Menu Screen

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1747]
### Short Description of the issue:
Drone Menu screen displays Common.IntEventVariable instead of surface area value
...

### Steps to reproduce the issue:
Select an Entity and Open Drone Menu
...

### Environment
- Skywanderers version: 20w16a
- Graphics Card: Integrated Graphics 

### Additional information:
![Skywanderers 2020-04-13 1_00_29 PM](https://user-images.githubusercontent.com/53021785/79151398-93167180-7d87-11ea-8f7b-dc00f01e2c99.png)
![image](https://user-images.githubusercontent.com/53021785/79151434-a9243200-7d87-11ea-8dfa-67fbdf41f3e1.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4471311/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, I also noticed that but forgot to correct it before pushing the build. Will be fixed for 20w16b. Thanks!
