### ISSUE TITLE
[Bug] Lightcruise and brick thrusters

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1748]
### Short Description of the issue:
If your ship does not have any block thrusters (so it doesn't have any Lightcruise thrust), entering and exiting Lightcruise can cause the ship to get stuck - it won't be able to enter Boost mode or move in Maneuver mode and the Lightcruise effect keeps playing.

Also if you enter autopilot in the same ship, you will be stuck with no way to move or disengage autopilot/Lightcruise

### Steps to reproduce the issue:
Build a ship with no block thrusters
Engage Lightcruise
Separately, engage autopilot in a ship without block thursters

This might be a good time to utilize your new error message tech with a "Block thrusters are required to enter Lightcruise" notification popping up should the player attempt to do either of these things.

### Environment
- Skywanderers version: 20w16a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Yes indeed that is a perfect example of why I made the warning system - I just fixed the issue and made the warning. I am gonna create a post so people can suggest warning, I have too few for now.
Will be in 20w16b. Cheers
