### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SuperSer80** [tsunamayo/Skywanderers#175]
[error.log](https://github.com/tsunamayo/Skywanderers/files/1413810/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1413811/output_log.txt)

[crash.zip](https://github.com/tsunamayo/Skywanderers/files/1413814/crash.zip)
#118

**Comment by tsunamayo** [comment]
Hi, could you make sure you updated your GFX drivers? What kind of recent game do you run on your card? Thanks

**Comment by SuperSer80** [comment]
the driver is up to date, this is report for crash on startup after driver update
[2017-10-25_110058.zip](https://github.com/tsunamayo/Skywanderers/files/1413943/2017-10-25_110058.zip)

**Comment by tsunamayo** [comment]
Hi, you are just at the limit of the minimum configuration on the gfx card, but I want to make sure if it is that or not. Do you happen to have a multi-screen? What resolution are you using?

**Comment by SuperSer80** [comment]
yes is my secondary pc :P but i view a test in this and then on main pc with gtx 1070  16gb,
This poor pc has 2 screen each with 1920x1080 resolution

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by tsunamayo** [comment]
Hi, I made some change to make startup easier on low-end configuration. Could you please activate the debug version inside steam (right click on the game, then properties, then betas, then choose debug), and tell me if the game boot correctly? Thanks!
