### ISSUE TITLE
[Bug] multiple yoke connection

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#1756]
### Short Description of the issue:

Connection of multiple yokes to one ship core is not possible

### Steps to reproduce the issue:

just try and connect multiple yokes to one core

### Environment
- Skywanderers version: 20w16a

**Comment by tsunamayo** [comment]
Yes it is because the computer needs the yoke orientation. But I will allow it only when orientation is the same. Cheers

**Comment by tsunamayo** [comment]
Okay issue is fixed. Thanks!
