### ISSUE TITLE
[Suggestion] Lighting and shadows

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1758]
As it stands in the game the current shadows are far too bright and make it so the player doesn't have much of a use for the built in flashlight. Plus without any lights you can still see perfectly fine which makes using lights slightly pointless, but still useful in proper interior areas.

Here's how it looks in-game without any added lights on a ship/build:
![20200410182430_1](https://user-images.githubusercontent.com/32974671/79285332-e15c6b00-7e82-11ea-900a-b56fdd2a5bbd.jpg)
That picture should be much darker than it currently is. Shadows shouldn't be totally dark but it should be dark enough to where lights or the player's flashlight are necessary.

Here is an example of how complete darkness looks in Starmade:
![20200414012224_1](https://user-images.githubusercontent.com/32974671/79285409-1d8fcb80-7e83-11ea-9c9f-c912c7f104c4.jpg)

And here is an example from Space Engineers and how the game looks during the planet's night cycle:
![image](https://user-images.githubusercontent.com/32974671/79285456-38624000-7e83-11ea-97a9-6959866d3d6e.png)

All in all, the game will look much nicer if the shadows have much more contrast instead of having them mostly visible.

**Comment by Womble-TC** [comment]
I agree, a nice contrast between light and dark can help make the game look even prettier (and make you feel like you are really in space). There are some good examples of darker shadows in some older builds/videos: 
![image](https://user-images.githubusercontent.com/29961381/79285995-24383600-7eb7-11ea-9c8d-e77f8d69dc09.png)

**Comment by ProPeach** [comment]
Yes, some deeper shadows would really improve the ambiance of the game and give it a more realistic feel. The darker shadows that we had previously were excellent, although I understand that lighting has been refactored many times

**Comment by ZachZent** [comment]
I do what shadows and color back into the lighting, though I would still want the shadows to be not so dark as the old dark side of the ring was pitch black. But when in the shipyard, could there be an option for "universal lighting." No shadows, just normal light on all sides of the block and ship. That way building won't be too difficult even when dark.

**Comment by tsunamayo** [comment]
Okay I can reduce ambient indeed, and it makes interior lighting much better. 
On the Torus we have a separate ambiant lighting also, so it wont be pitch black, so no pb.
For the "universal lighting", not sure yet. I wanted to have a drone follow you with a big ass light...

**Comment by ProPeach** [comment]
That sounds wonderful 😄

**Comment by Womble-TC** [comment]
That drone light sounds cool, you don't want to waste that lovely flashlight effect!

**Comment by tsunamayo** [comment]
Okay, I reduced ambient and specular env map (the new component in the new lighting system) significantly - should be almost pitch black. In patch 20w16b, tell me if you like it. Cheers

**Comment by Womble-TC** [comment]
The new lighting looks great, thanks! Many people on the discord server seem to be enjoying it along side the new AO too.

**Comment by tsunamayo** [comment]
Great! AO is bugged, I have issues with asteroids fog for example. And it is a bit too strong ;) - but thats an easy tweak.
