### ISSUE TITLE
Can't make line with Fence block

### ISSUE THREAD

**Issue by ghost** [tsunamayo/Skywanderers#176]
Unlike making line with other blocks it doesn't seem to work on this block

**Comment by tsunamayo** [comment]
It is because it is in fact a brick... But I agree having the line command for this one would make sense.

**Comment by David184** [comment]
also the stair scafolding block's model seems to be bugged when i put it next to each other

**Comment by Harlekin13** [comment]
I assume the slider extension is a brick too? I have to admit, that i use way more of them than fences. this weekend i placed about 1.5k slider extensions, only few where not part of the same mechanism. I hereby request the line command for it too.

**Comment by AfterRebelion** [comment]
This is no longer an issue in recent versions (19w23b)
