### ISSUE TITLE
Save Problem

### ISSUE THREAD

**Issue by Arschpollo13** [tsunamayo/Skywanderers#1765]
Yesterday i deleted all my old save files to start building on an empty world. Then I created a new world in the game as normal and started to build, but when I pressed F1 to save, closed the game and opened it again today,  I noticed that my world was not saved.

I tried it several times again but it never worked. The next step was that I reinstalled the game and tried it again but though that did not worked.
At least a friend sent me his complete "Skywanderers folder" where the save files are located and I replaced my own with them.

Now I have his world and I can save on it but I still can not save my own created world.

Sry for bad english.

**Comment by Womble-TC** [comment]
I have the same issue, F1 doesnt seem to work on any new character

**Comment by Battlepixel** [comment]
Same problem here.

**Comment by tsunamayo** [comment]
okay let me check, it was fine on my side...

**Comment by tsunamayo** [comment]
Fixed for 20w16c. Cheers
