### ISSUE TITLE
[crash] crash on startup

### ISSUE THREAD

**Issue by GoWithTheFro** [tsunamayo/Skywanderers#177]
[b]logs:[/b]
[Crash logs.zip](https://github.com/tsunamayo/Skywanderers/files/1413952/Crash.logs.zip)

[b]Hardware Configuration:[/b]
OS: Windows 7 64 bit
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
GPU:  NVIDIA GeForce GT 635M (most recent drivers)
RAM: 8GB
laptop reference:  3259CTO (Lenovo E560) 
(Yes I know my specs are terrible)

**Comment by tsunamayo** [comment]
Hello, could you please tell me the resolution you used? Yes the config is def on the low-end I want to make sure it is linked to that.

**Comment by GoWithTheFro** [comment]
I've tried in 1366x768 fullscreen and 1280x720 windowed.

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by tsunamayo** [comment]
Hi, I made some change to make startup easier on low-end GFX card. Could you please activate the debug version inside steam (right click on the game, then properties, then betas, then choose debug), and tell me if the game boot correctly? Thanks!
