### ISSUE TITLE
Key mapping is ignored if changed ingame

### ISSUE THREAD

**Issue by TheShinriel** [tsunamayo/Skywanderers#178]
First of all thank you for this game and good luck to continue.

I had, and I like change the keys because I use an azerty keyboard.
This bug is about the key mapping is ignored in game for those keys already mapped from the launcher.

So you could change direction, for example for azerty, I tried with other keys like **uhjk** but don't care
![image](https://user-images.githubusercontent.com/23140387/31991587-6a8d4d5e-b978-11e7-9a0f-1d56a0855faa.png)

The key used still those selected on the launcher
![image](https://user-images.githubusercontent.com/23140387/31991647-8765fe9e-b978-11e7-9b62-efb38733c24b.png)

So is it possible to linked those 2 configs?

**Comment by tsunamayo** [comment]
Sorry this is a bit confusing, this something impossible to do with unity for now - I plan to do a dev to simply remove the launcher command assignment and do everything in game. I keep you posted.

**Comment by AfterRebelion** [comment]
Since the game now launches directly, and there is no longer a default unity launcher, this issue is no longer valid in recent versions (19w23b)
