### ISSUE TITLE
Pilot getting stuck in flight mode

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#1781]
### Short Description of the issue:

I've started experimenting with turrets, and soon this happened: Upon exiting the yoke or pilot seat, the player character got stuck in what looked like spaceship flight mode;
Once, I was able to move forward, but all other commands just flipped the character around. The character was playing walking animation.
The second time, the character was stuck in the sitting animation, and the movement keys only slightly shifted it's position before snapping back to the pilot seat upon key release.

The problem persisted through a save and reload of the game, but by breaking the chair I was able to get free.
After getting stuck the second time, I wasn't able to break any blocks, and the game eventually started slowing down and lagging.

I tried taking screenshots, but I found out Steam didn't react, so no pics were created.

On the next reload, I was stuck at the chair, completely unable to move or break anything, but able to turn around, and get in and out of the chair. I was able to make a screenshot this time.
...

### Steps to reproduce the issue:

Build simple frame with poorly made turrets. I had several rotators stacked on top of each other, and tried connecting different ones to the turret computer, which in turn was connected to the yoke. Try getting in and out a few times.
...
Good luck with the Steam release! I'm rooting for you!
...

### Environment
- Skywanderers version:  20w16c
- Graphics Card: R9 290

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
![20200421165608_1](https://user-images.githubusercontent.com/38191224/79881753-eaed5200-83f1-11ea-9080-dd2a62b6622c.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4510817/output_log.txt)

**Comment by tsunamayo** [comment]
Sounds bad! Could you please send me your blueprint, there might be something with it.
Thanks for the cheer up ;)

**Comment by Cpt-Fortius** [comment]
I'm sorry. The world got deleted, and I wasn't able to make a blueprint of this contraption ( couldn't reach drone  )
I tried recreating the problem today, but I don't have anything conclusive.
