### ISSUE TITLE
[Game Broken] Newest Game Change Build Won't Launch

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#1789]
This is a big important issue, as with the new name change, the game won't natively launch on steam anymore.
<img width="1151" alt="sevo break" src="https://user-images.githubusercontent.com/33239800/79954228-61f11c00-84c0-11ea-9fae-6e03b717ed31.PNG">

I have done nothing except let the update install and try clicking play. I will test uninstalling the game to see if a full fresh reinstall fixes it.

**Comment by Sullos** [comment]
Update, a whole fresh install including deleting skywanderers folder does not fix the problem. I believe the issue is that Steam is looking for the Skywanderers.exe. And with the name change but Steam still officially having it as Skywanderers, its looking for the wrong name of exe file.

<img width="737" alt="fresh" src="https://user-images.githubusercontent.com/33239800/79955065-99ac9380-84c1-11ea-94dd-c767ddf18caf.PNG">

**Comment by Sullos** [comment]
Recently found out this from a community member
If you rename the exe to Skywanderers.exe and rename the "Starship EVO_Data" folder to "Skywanderers_Data" it will let you launch the game
Hope this helps diagnose the problem

**Comment by tsunamayo** [comment]
Yep I am looking into that... I keep you guys posted!

**Comment by tsunamayo** [comment]
It should be good now! Tell me if anything is not working...
Cheers

**Comment by Sullos** [comment]
Appears to be working! Thanks Tsuna!

**Comment by tsunamayo** [comment]
Great!
