### ISSUE TITLE
[Low] Spaceship core on rails breaks everything

### ISSUE THREAD

**Issue by sverbist** [tsunamayo/Skywanderers#18]
In another attempt to making a train, I attached a spaceship core to a rails. When I interact with the spaceship core, I can't control anything anymore. Can't destroy blocks, can't build things or activate switches.

Marked low priority even though it breaks everything because...who would place spaceship cores on rails....

**Comment by tsunamayo** [comment]
Fixed, in upcoming build it will no be possible to place them on children entity. Thanks !
