### ISSUE TITLE
Connecting to a bugged hose locks several controls until restart

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#180]
**To reproduce:**
[https://www.youtube.com/watch?v=7Xz5BszTITU](url)
Place down two hose pieces, and link them together, then delete the second piece (the end where the link was completed). The base is deleted, but the hose will remain in place. Next, place a new hose piece and attempt to link the original hose to it (The order of pieces clicked is important here, you must start the link with the base that has the bugged hose).
This puts the player in a state where all inventory and menu controls do not respond, but saving and player movement still function properly. I have not yet found a way to exit this state other than forcing the program to exit and restarting it.

As a side note, deleting the first piece of a hose (where the link was started) removes the hose properly, but also takes the other end piece with it

**Comment by tsunamayo** [comment]
Thanks, this was a regression. It is fixed now - fix will be available in the next build. Cheers!
