### ISSUE TITLE
Hovercraft not re-aligns to the surface

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#181]
After spending time in Hovercar in 3rd person, the cam has a weird 'slightly leaning to the left' glitch, as if there is a roll that hasn't stablised & recentred itself. 

This is evident in character but manifests in Hovercar as well.

**Comment by tsunamayo** [comment]
Okay I think I understood what is the issue.

**Comment by tsunamayo** [comment]
Okay it is not happening with the new hovercraft tech. Thanks!
