### ISSUE TITLE
Bug - Ring Lake On Dark Side Glitches Through To Space

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#183]
found a lake on dark side which glitches through ring into space but no idea where it is specifically as it's dark & no co-ordinates or marker option.

Suggest coordinates &/or marker option (be useful for other things as well, tbh)

**Comment by AfterRebelion** [comment]
Ring is being reworked, so this issue no longer valid in recent versions (19w23b)
