### ISSUE TITLE
Bug - Hovercars in Deep Spaaaaace

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#184]
Hovercars will quite happily skip out of the Ring using the wall hill terrain & head off into deep space. 

Similarly, high speed terrain jumping launches you into a high trajectory (a fun thing!) especially at high speed. 

Fun, great, brilliant, but maybe a gravity binding at certain altitude to prevent deep space travel high jinx occurring?

**Comment by tsunamayo** [comment]
Thanks, this will be somewhat fixed with a better gravity system. Cheers
