### ISSUE TITLE
Bug - Page Down Key Not Recognised/Arrow key dual function?

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#185]
Page Down button isn't recognised when trying to remap keys. There may also be an issue with arrow keys; although I don't recall seeing them listed (apologies if wrong, I'm doing this from memory), they were over riding the function I'd assigned them & still acting as directional keys.

**Comment by tsunamayo** [comment]
It might related to them being assigned on the launcher from outside unity. I planned to remove this launcher and have all the assigment from inside the game (for now it is not possible). 
Will check page down.
Thanks

**Comment by tsunamayo** [comment]
Page up and Page down can now be assign (sorry I dont have those keys on my keyboard ...) Cheers
