### ISSUE TITLE
Request - Consolidate 'use' buttons

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#188]
Already mentioned by others - there are 2 use buttons, so could these be consolidated into one, please?

Many thanks!

**Comment by tsunamayo** [comment]
Rational behind having a different button is that activate and enter are two different thing. I want to prevent player to exit a seat / control by mis-clicking on a command. Also there is the problem of studs on chair, you might want to put cushion or just seat on the chair - having RMB would make the player always do one and not the other if we try to get rid of F enter key. 

Anyway I agree it is not very elegant, I will explore other possibility, like a hold n time Enter seat to not mis-click them. I will open a post on the forum soon to continue the discussion.
