### ISSUE TITLE
Request - 3rd Person camera modifier

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#189]
A 3rd person camera modifier, preferably a toggle, to look in same direction as travel; as it is, it gets confusing very quickly with the dual free look/direction set up & figuring out which direction you're traveling at high speed.

Many thanks!

**Comment by tsunamayo** [comment]
Yes I agree, it will most likely come during the spaceship control scheme refactoring. 

PS: I am closing these case because I agree with them and they where already on my roadmap, hence I dont really need keep track of them ;). Cheers
