### ISSUE TITLE
[Low][Visual] Lighting color remains sometimes when changing the color of light block

### ISSUE THREAD

**Issue by clmd58** [tsunamayo/Skywanderers#19]
This is the first time I've noticed this- blue light persisting after switching from 'blue lagoon' to a dark grey or brown paint color for the light block here's a picture... looks kind of cool. but definitely a bug. 

EDIT: It does appear to be solved by a reloading of game. 

![image](https://cloud.githubusercontent.com/assets/12486156/22181433/0607049c-e052-11e6-8cd1-75de36fc9987.png)

**Comment by tsunamayo** [comment]
Hi, this issues should have been fixed with the new Light update. Thanks!
