### ISSUE TITLE
[Crash] Terrain render glitch (Screenshot included)

### ISSUE THREAD

**Issue by Aredis** [tsunamayo/Skywanderers#190]
![skyboxglitch](https://user-images.githubusercontent.com/20936202/32003370-16b256a8-b99f-11e7-8d92-78a28a8ddfad.png)
This thing spawned to the left of the initial player spawn and is causing the game to freeze whenever I look in it's general direction. (Tried reloading and creating new world several times - issue present everytime)

EDIT: It's the ring. It appears that only half of it spawned in. Looking left of the initial spawn point still causes freezing, but I managed to take a couple screenshots of the right part. 
![20171025163652_1](https://user-images.githubusercontent.com/20936202/32004790-e7da7c3a-b9a2-11e7-861e-6c4549efc769.jpg)
![20171025163653_1](https://user-images.githubusercontent.com/20936202/32004795-e9f915b2-b9a2-11e7-8923-6b05dbc064f8.jpg)
![20171025163656_1](https://user-images.githubusercontent.com/20936202/32004799-ed48363a-b9a2-11e7-888f-aec7f9217dde.jpg)
Edit 2:

My machine: 
GTX 1070
16GB DDR3 RAM
I5 4670k @ 3.4 GHz
Windows 7 64bit

**Comment by Tiepilot1138** [comment]
Tsuna, this is the same thing mine is doing on 2 different machines, report #149.

Aredis, if you continue to not look that way, can you move around and interact?  I can, until I mistakenly glance that way...

**Comment by Aredis** [comment]
Yeah, I can move around if I don't look that way and stay under the glitched surface.

**Comment by tsunamayo** [comment]
Okay, are your GFX driver up to date? Also could you please send me your output_log file inside the steam install folder of the game? Regards
Francois

**Comment by Aredis** [comment]
Yes, they're up to date. Here's the file:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1418465/output_log.txt)

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by Aredis** [comment]
The latest update fixed the issue for me. (I'm pretty sure I was missing the entire PlayerEntities folder for some reason...) Do you still need me to check those world files?
![20171027140522_1](https://user-images.githubusercontent.com/20936202/32103299-16260086-bb20-11e7-8407-505e22630263.jpg)

**Comment by tsunamayo** [comment]
Glad to hear that! When you first start the game there is nothing in playerentities, this is okay. It will only get populated when you build a new ship, or you change an existing one. Still I would like to know if you did anything specific, as I have a few other people that had a similar issue. Cheers

**Comment by Aredis** [comment]
Nope, nothing specific - I just downloaded the update.

**Comment by tsunamayo** [comment]
Okay, let me close the issue then! Cheers

**Comment by CyaNox** [comment]
In #317 I found that there is a dependency lacking for the MSVC Runtime 2015 as per: https://github.com/tsunamayo/Skywanderers/issues/317#issuecomment-344861361

If you have this issue again you can try downloading and installing it from https://www.microsoft.com/en-gb/download/details.aspx?id=48145 and see if that helps.
