### ISSUE TITLE
Unable to leave seat (relog required)

### ISSUE THREAD

**Issue by ChuckieGee** [tsunamayo/Skywanderers#191]
Whilst flying in a space craft, firing unguided rockets can sometimes cause them to detonate as soon as they're fired which causes the ship to destroy itself. (seems to be more frequent at 100m/s+)

If the pilots seat is destroyed in the explosion, the player is still able to control the ship, but they are unable to leave the now destroyed pilots seat ( in this case the ships core was still intact), even when pressing F, can however press "ESC" in order to leave the game and relog into the world.

upon relogging camera is restricted to 180 degree of movement, but the player can now move freely otherwise.

Game restart unlocks the camera
possible fixes:
Prevent rockets from being fired above 100m/s
Ensure that the speed of the fired rocket is greater than the speed of the ship that fired it?
Turn rocket hit boxes of until said rockets have been flying for 0.5s

**Comment by CyboLP** [comment]
LOL! But maybe a look on the ground could do it... Else you've to wait for the Dev... ^^

**Comment by tsunamayo** [comment]
Okay very interesting test case indeed. The rocket issue is well known, but the seat and then the view lock on relog are definitely new - I am looking into that and keep you posted.

**Comment by tsunamayo** [comment]
The relog lock issue is fixed, seat is gonna take a bit more time to be fixed though.

**Comment by tsunamayo** [comment]
Okay I have a temporary fix for seat, now you will be able to simply press F once and you will exit your now destroyed seat. Real fix will take a bit more time before being up - but now it is no longer blocking.
Rocket case is already booked in another case.
Thanks
