### ISSUE TITLE
Lost Character Movement Control

### ISSUE THREAD

**Issue by Erk1701e** [tsunamayo/Skywanderers#192]
Hello!

I am having an issue moving the character. At the start of the game, I re-configured my keys and managed to lose all movement control. I can still scroll with the mouse wheel, open the menu with TAB, turn on the Lights, but I cannot move in any direction with the keys or mouse. I quit the game and attempted to create a new character, only to find that I could not move the new one either. I seems altering the keys disabled all movement controls

**Comment by tsunamayo** [comment]
Okay sorry it is confusing as of now but yes the key control assignment for character forward/backward and strafing are not working from inside the game. You need to configure axis from the launcher outside the game in order to do this. It will be fixed in an upcoming build.

**Comment by HadesDeadlyTom** [comment]
I can reproduce that when i try to use the same keybind for 'Crouch' and 'Drive -' when in game.
You lose all movement, til you change the keybind.

**Comment by tsunamayo** [comment]
Okay the bindable key for in-game control is in build 17w44b. Thanks
