### ISSUE TITLE
Rebinding default delete key prevent multi-block deletion.

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#196]
After swapping Mouse 1 and Mouse 2, attempting to delete multiple blocks only deletes one at a time even when Ctrl is pressed. Placing blocks does not have this issue.

**Comment by tsunamayo** [comment]
Sorry it is confusing for delete you need to press SHIFT. It will be updated.

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
