### ISSUE TITLE
[CRASH] Crash on world creation

### ISSUE THREAD

**Issue by Redstorm134** [tsunamayo/Skywanderers#197]
Installed game, tried making a world, of the six times I attempted this, I crashed 4 times during the loading screen and two more times having gotten through the load screen only to crash a few seconds later.

[error.log](https://github.com/tsunamayo/Skywanderers/files/1415939/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1415940/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1415974/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1415975/output_log.txt)

**Comment by tsunamayo** [comment]
Hello, sorry to hear that. Could you please give me your gfx card model, and make sure your drivers are up to date? Thanks

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks
