### ISSUE TITLE
Destroying a control block of a vehicle you're in then exiting ejects your body but you stay in control of the gun

### ISSUE THREAD

**Issue by ggrdk5478** [tsunamayo/Skywanderers#198]
I got into one of the mechs and was playing around with the guns.  First thing I did was seeing what could be destroyed and ended up blowing up a sizable chunk of my mech.  When I went to exit, I watched my character's body fly out and hover, but control stayed with the gun.

Steps to reproduce (with the short of the two mechs to the left of the starting location):
1. Sit in the mech
2. Take control of the guns
3. Shoot the control block unit it's destroyed
4. Hit 'F' to exit

Result:
Your character's body flies out and hovers, you retain control of the gun without the ability to exit

![20171025155353_1](https://user-images.githubusercontent.com/33104013/32023052-d047a4da-b99d-11e7-9958-efd4997a5c52.jpg)

![20171025155425_1](https://user-images.githubusercontent.com/33104013/32023077-dece355a-b99d-11e7-9465-0f18e266fcfc.jpg)

![20171025155129_1](https://user-images.githubusercontent.com/33104013/32023085-e3b3aed8-b99d-11e7-8af9-f68256e5ed25.jpg)

**Comment by Cornflakes91** [comment]
can confirm, had the same problem.
shot out the connective electronics for the turret and couldnt leave it anymore afterwards

**Comment by tsunamayo** [comment]
Okay the bug was fixed, you should now be ejected from all the control.

**Comment by ggrdk5478** [comment]
I can still recreate this issue on 17w44a.  My apologies if it's because a patch hasn't been issued.

**Comment by CyaNox** [comment]
17w44b was released can you check if this still happens (you may have to switch to the experimental branch for this)?

**Comment by ggrdk5478** [comment]
Confirmed reproducible in 17w44b.  

Here's some more details and findings.  I ended up using the tutorial building because the guns were no longer able to hit the monitor in the mech.

I went to the **Let's Build a Turret!** room.

1. Set up the turret controls at the entrance to the room so that it could hit them [fig 1]
2. Took control
3. Shot and destroyed the **Quad Enter Gate**

Results:
At this point I could no longer exit the camera/turret control.  
Hitting 'F' caused the inventory bar to return, but I could not scroll or select items on it.  
The mouse moved the turret while WSAD moved the character. [fig 2]

Also:
Shooting either the **Left Mouse Button** control or the **Turret Computer** caused the linked function to stop working.  However, shooting the **Joystick** did not affect input.

An additional wrinkle:  
At one point I exited to the title screen and reloaded.  I could not look around or select any items.  The mouse was not moving the turret either even though it had been before the exit to title screen.  I had to quit to desktop and restart the game to regain control.

![20171104101217_1](https://user-images.githubusercontent.com/33104013/32406557-c209f2bc-c148-11e7-9b6e-b8eb0c4b43d3.jpg)

![20171104101253_1](https://user-images.githubusercontent.com/33104013/32406558-c5592ab4-c148-11e7-91a3-98834be3caa9.jpg)

**Comment by tsunamayo** [comment]
Okay thanks for the detailed test case, it is indeed a new case I need to deal with. The exit to desktop is also a different issue, 
I will do big refactor of the way system works in my code to deal with all those case naturally, I keep you posted. Cheers

**Comment by tsunamayo** [comment]
This issues should have been fixed now (hopefully). Dont hesitate to tell me if you found another test case. Thanks!

**Comment by ggrdk5478** [comment]
Well... it looks to be mostly fixed. (sorry!)

build 17w45c

When I destroy the Quad Enter Gate, I go back to my body, but cannot control it or have access to the inventory.  However, I can hit 'F' and fully "exit" back into the character.

Figures:
1. Wired up
2. In control of turret
3. Destroyed gate, back in character; note no inventory bar; at this point I can pan but not move
4. Hit 'F', now have full control again

![20171116212156_1](https://user-images.githubusercontent.com/33104013/32927792-5ae0e9da-cb14-11e7-8fbb-22027ae0fbf8.jpg)

![20171116212202_1](https://user-images.githubusercontent.com/33104013/32927794-5d51f31c-cb14-11e7-8f5f-6e9d1037a73e.jpg)

![20171116212214_1](https://user-images.githubusercontent.com/33104013/32927800-60b41b0c-cb14-11e7-8f05-fd115e0f5f06.jpg)

![20171116212220_1](https://user-images.githubusercontent.com/33104013/32927803-63388390-cb14-11e7-9737-22ae0e4dc826.jpg)

**Comment by tsunamayo** [comment]
It should be fixed in latest build. Thanks!
