### ISSUE TITLE
[BUG] Changing selected block to empty while rotating one causes the location indication to stay

### ISSUE THREAD

**Issue by ggrdk5478** [tsunamayo/Skywanderers#199]
When switching between blocks while in rotation of one (hold RMB) causes the placement indicator to stay after mouse button release if the selection is empty.

Steps to reproduce:
1. Select a block to place
2. Hold RMB
3. Select an empty inventory slot
4. Release RMB

Result:
The indicator of the block location stays even when selecting a different block.  You have to RMB to dismiss it.

![20171025162730_1](https://user-images.githubusercontent.com/33104013/32024266-7e40f552-b9a1-11e7-85c7-c8e916825273.jpg)

![20171025162733_1](https://user-images.githubusercontent.com/33104013/32024268-81312a52-b9a1-11e7-8941-494a57504efd.jpg)

![20171025162737_1](https://user-images.githubusercontent.com/33104013/32024272-83e194a8-b9a1-11e7-9c6f-592e902d86d4.jpg)

![20171025162747_1](https://user-images.githubusercontent.com/33104013/32024276-872bc9f8-b9a1-11e7-9c6b-61dfdb433ead.jpg)

![20171025162851_1](https://user-images.githubusercontent.com/33104013/32024309-a06f9c1e-b9a1-11e7-9291-c4a552fc5073.jpg)

**Comment by tsunamayo** [comment]
Very nice finding indeed! I am on it.

**Comment by tsunamayo** [comment]
Okay it is fixed - thanks!
