### ISSUE TITLE
[Low][Visual] Grainy effect when in/around planetary rings, especially noticeable on bloom

### ISSUE THREAD

**Issue by clmd58** [tsunamayo/Skywanderers#20]
The effect is everywhere when you're in the rings, but it's particularly noticeable when you've got contrasting bloom. it's all checkered and stripped and stuff, and shutters and changes as you look around. I assume it's something to do with the texture of the rings when viewed from far away in space... but when you're inside them, it doesn't go away or change or something, so it's still just all in your face. 

![image](https://cloud.githubusercontent.com/assets/12486156/22216395/8ee4dde4-e164-11e6-84f9-c2972bab2947.png)

**Comment by tsunamayo** [comment]
ok this weird, I dont see that of course on my pc. Could you please tell me your GPU, os and if your driver are up to date ? Also do you notice that only in the rings ? For example when you are near a powerfull light source with  a lot of glow, do you see this ?

**Comment by tsunamayo** [comment]
This issue should have been fixed on recent build. Cheers
