### ISSUE TITLE
Overlapping small sliding extension blocks slider

### ISSUE THREAD

**Issue by Gadget100** [tsunamayo/Skywanderers#200]
If small sliding extensions overlap each other or the small sliding brick, rather than being placed perfectly end-to-end, then the slider can't move along the overlapping part.

I've found it easier to place extensions which overlap each other than to place them properly end-to-end, and there's no obvious visual clue that this is a problem, until you try to operate the slider.

One solution would be to make it impossible to place overlapping extensions; another would be for overlapping extensions to work the same as end-to-end ones.

**Comment by tsunamayo** [comment]
Hi, yes you are right, this is something that will be addressed when I do a refactoring of the sliding block.

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
