### ISSUE TITLE
Hull block appears to have zero thickness when viewed through glass block

### ISSUE THREAD

**Issue by Gadget100** [tsunamayo/Skywanderers#201]
![20171025222224_1](https://user-images.githubusercontent.com/26575681/32024440-76ac64e2-b9d4-11e7-9aed-9dd322e075e9.jpg)

If you placing a glass block next to a smooth hull block, the hull block appears to have zero thickness.

**Comment by tsunamayo** [comment]
Thanks for spotting that one! It is fixed. Cheers
