### ISSUE TITLE
Stuck in the elevator of the tutorial building

### ISSUE THREAD

**Issue by ggrdk5478** [tsunamayo/Skywanderers#202]
When taking the elevator to the second floor, the character "twitches" and ends up feeling like it's about a block down from where it starts out on the elevator.  I.E. you've sunk into it.

When I arrive at the second floor, I'm stuck in elevator square.  I can move around in it, but I can't get over the lip onto the floor.  Jumping does not work.

Taking the elevator back to the first floor "pushes" me out of whatever state I'm in and I can then move around freely.

This also happens if you're floating about the elevator and it rises under you.

**Comment by tsunamayo** [comment]
Okay indeed I managed to reproduce this issue. I will improve my character collision detection now that Unity gives me more flexibility - but not on the short term so this case might stay open a bit. Thanks

**Comment by AfterRebelion** [comment]
Since the torus isn't re-implemented yet, and the tutorial is bound to change, this issue is not longer valid in recent versions (19w23b)
