### ISSUE TITLE
Brick System will latch onto hidden bricks

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#204]
Im building my first proper ship and having to fight the build system. Sometimes the Bricks will "latch" onto something behind the one I wish to place. In some cases, 1 block areas are impossible to place the Brick onto correctly.

Another issue is that Bricks will sometimes randomly lack their blue Nodes. Without them, its impossible to place bricks onto them (standard 6-sided cube). 

It might be related to deleting the brick starter stud grid. After deleting all bricks and adding the starter stud grid, while I could still place bricks THROUGH others, I was able to complete the goal I was wanting to.

**Comment by tsunamayo** [comment]
Yes it is seems there is problem with studs behinds that sometime gets hit - I will def have a look into that.

For the bricks studs missing, people get often confused by this. bricks are not voxel, there is no studs on the bottom of bricks like the mini cube. So the stud you want to use is in fact taken by the cube you want to build on. It is definitely confusing for newcomer, I guess people are expecting bricks to be just smaller voxel - not sure what I can do against that - I will wrap my head around this a bit.

Not sure to understand this: 1 block areas are impossible to place the Brick onto correctly.

**Comment by Napther** [comment]
I see now. The bricks act like lego 1 block studs. They have attachment points on 5 faces but the base which is thr connector. Therefore best to Always build the base onto a stud grid so that the bottom brick face is not exposed. I did see that the wedged corner brick lacked Studs but didn't put 2 and 2 together.

When placing bricks they will often select every brick.  Inside and outside. Even placing new o es clipping exactly in other bricks on the same Stud grid. It is this behaviour that makes it impossible to place bricks into some locations. I can press several times oN a slot that is clearly free, but the game will place thr brick inside the one I wanted to build on and then refuse further brick building if the mouse isn't moved. Moving it again tends to place bricks inside thr structure than on its surface as before.

**Comment by Hanfree85** [comment]
I think you say somthing like this no?
![20171027031003_1](https://user-images.githubusercontent.com/33139962/32083638-826bc9bc-bac4-11e7-9dd7-151e8455fea9.jpg)
![20171027031012_1](https://user-images.githubusercontent.com/33139962/32083643-89e9ce64-bac4-11e7-9207-ea864a338f5d.jpg)
![20171027031020_1](https://user-images.githubusercontent.com/33139962/32083651-9170432a-bac4-11e7-8d3c-ce6401c5d7a1.jpg)

**Comment by Napther** [comment]
Pretty much exactly that. I often don't get screen shots because I collate bugs to the end of a play session which usually means I've frozen or broke the game before then.

**Comment by tsunamayo** [comment]
Hi, the issue should be fixed now! I tracked down too case not dealt with previously: when a studs was behind geometry, it is now no longer detected. Also in some case a stud further away could be detected instead of the closed one. It should be less painful now. Cheers
