### ISSUE TITLE
Paint tab can be Empty

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#205]
Sadly no reproduction, after a while I come to want to colour some parts for clarity or looks, game has been open a very long time (Graphics card hates me and now at 83*C but thats besides the point) and havent yet accessed the paints tab. But when I do its empty and the Scrollbar is "missing"

Upon clicking the scroll bar and fiddling with it, all the paints pop back into existence in the tab.

**Comment by tsunamayo** [comment]
Thanks! I am pretty sure you faced #173, which is fixed now - will be up in the next build. Thanks!
