### ISSUE TITLE
Glass is invisible when behind the 2x1 wedge blocks

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#207]
When behind the 2x1 wedge blocks (The 2 blocks that make up the 2x1), the glass is invisible
![20171025201625_1](https://user-images.githubusercontent.com/28989460/32030568-69431282-b9c1-11e7-8c6b-bb714bb3818c.jpg)

EDIT: Just did some testing, it seems to be when it is behind any sort of wedge

**Comment by tsunamayo** [comment]
Duplicate of #130 . Thanks!
