### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by Corvixin** [tsunamayo/Skywanderers#208]
After downloading the update I could not load the game. In windowed it would get through the Unity screen, then my screen would flash black and the game would crash. When in fullscreen, the unity screen would show and then become unresponsive. I did try verifying the integrity of the game files and even uninstalling and reinstalling the game but this did not help. Crash file below.
[error.log](https://github.com/tsunamayo/Skywanderers/files/1416941/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1416942/output_log.txt)

**Comment by tsunamayo** [comment]
It should not be related to the latest upgrade. What is the exact model of your R5 gfx card? Also could you please make sure that your driver are up to date, and retry after a windows restart. What kind of recent game do you run on your card? Regards

**Comment by Corvixin** [comment]
Well I'm not sure on the exact model as I cant remember and this is a factory built computer. I will try updating my drivers and as for games run recently, Deus Ex: Human Revolution, Elite: Dangerous, and Rimworld.

**Comment by Corvixin** [comment]
Alright @tsunamayo , my friend Nien Nunb and I just did some work to find the problem because after some digging, I found that it was absolutely not my computer. What we found was that the ship file for Torus was the problem, after deleting it, not only did the game load but it loaded in seconds while previously it had been taking up to 5 minutes to load if it loaded at all. I hope this helps to find a bug with that file.

**Comment by tsunamayo** [comment]
Yes for sure the torus is causing some problem, removing this file will simply remove the torus from the world, making the scene much easier to load for low-end gfx cards. I will give you a save file soon, I still need you test with the torus. I will just have you start a bit further away, so initial load is smaller. Thanks

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by Corvixin** [comment]
Thanks for the explanation, yeah my gfx is a bit low-end lol so it makes sense. Thanks for the help.

**Comment by Corvixin** [comment]
Sorry for such a late reply @tsunamayo some stuff came up. After following those steps, oddly, the game ran fine. I could see the galaxy background, I could see the torus without crashing however I did experience a bit of lag(probably due to my computer) and I could see the asteroids.

**Comment by tsunamayo** [comment]
Okay glad to hear that, but could you confirm if you are still having the bug when starting directly on the torus, or does it run fine (you can create a new character to test). Thanks!

**Comment by Corvixin** [comment]
Well I loaded a save where I was on the torus and I havent crashed yet.

**Comment by tsunamayo** [comment]
Okay glad to hear that! Cheers
