### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by Water-Cat1** [tsunamayo/Skywanderers#209]
Game crashes on startup.

Logs:

[error.log](https://github.com/tsunamayo/Skywanderers/files/1416993/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1416994/output_log.txt)

It is an old laptop, so can understand if that's what is the issue.
GPU: NVIDIA GeForce GT 540M
CPU: Intel Core i7-2670QM
Memory: 16 GB DDR3 RAM
OS: Windows 10 Pro

2 Screens
1366x768 Laptop Screen
1920x1080 External screen (running game on this one)

Attempted to run both full screen 1920x1080 and windowed 1280x720
Drivers are up to date, and tested after a fresh restart.

**Comment by tsunamayo** [comment]
Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1420287/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by Water-Cat1** [comment]
I have set up what you asked, but I still crash on startup. I see "Made in Unity" which then fades out, then nothing else until the error message pops up saying the log has been created.

Therefore I can't test any of the files due to not even reaching a menu.

**Comment by CaptainCJH** [comment]
I will add I have the same issue too. Adding the characters.zip to the folder does not work. I have 2 PCs one a Dell Optiplex 755 2nd gen pentuim dual core with Win 7 pro 16gb ram and Nvidia GT730 gpu. Other is a Dell 4 core pentium 16gb ram with same Nvidia GT730 gpu. Both have latest drivers version 6.88. I also suspect gpu memory to be the issue.

**Comment by CaptainCJH** [comment]
Upon attempting to run the game today 10/27/2017 the game now seems to load ok. Not sure if the characters.zip helped or it was an update.

**Comment by Water-Cat1** [comment]
Assuming it was an update as game now runs for me too! everything loads fin and can join multiplayer games.
