### ISSUE TITLE
[BUG] Sliding Block shifts position

### ISSUE THREAD

**Issue by Wraith0070** [tsunamayo/Skywanderers#210]
I built an elevator in my ship and when I use the elevator, single or repeated use, the items on the slide block (as well as the block itself) shift forward.
![elevatorbug](https://user-images.githubusercontent.com/33112226/32035655-4c5087bc-b9e0-11e7-8f51-3797c0670318.png)

Edit: Added zipped blueprint.
[explo2-Test.zip](https://github.com/tsunamayo/Skywanderers/files/1417009/explo2-Test.zip)

**Comment by Name11ess** [comment]
I confirm. I did build a V12 engine and after some time I've seen that some of the pistons got out of their cylinder. I can check how long it takes if it can help.

**Comment by tsunamayo** [comment]
Okay this issue is finally fixed. Thanks for reporting that and sending the blueprint! Cheers
