### ISSUE TITLE
Disappearing colors

### ISSUE THREAD

**Issue by HadesDeadlyTom** [tsunamayo/Skywanderers#212]
When you go all the way down in the third menu : 
![ss 2017-10-26 at 11 32 36](https://user-images.githubusercontent.com/33090879/32045913-ceef2884-ba41-11e7-906d-b98f1aac0beb.jpg)

And then go to the color tab, it's empty : 
![ss 2017-10-26 at 11 32 49](https://user-images.githubusercontent.com/33090879/32045933-dda2a7de-ba41-11e7-8be7-1a6c3f39035b.jpg)

You can manage to catch a really small slider if you try hard enough.

![sans tiddddtre](https://user-images.githubusercontent.com/33090879/32046129-64b9376a-ba42-11e7-981a-7a0b96087f22.png)

**Comment by tsunamayo** [comment]
Thanks, actually this bug was fixed yesterday and fix will be on the next build! Thanks!
