### ISSUE TITLE
[Bug] "infinite" loading time

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Skywanderers#213]
when I try to create me first universe, the loading time is like "infinite" (I tryed multiple time and rage quit because it'sn't loading (I wait 1 hour) )

I have an Intel core i7 860 2.8 Ghz
and an Nvidia geforce GT620
(I have windos 10)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that! No need to wait 1h ... a few min max should indicate that something is wrong. Could you please send me your output_log file inside the Steam application direction of the game?

Also could you try the following:

Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? Do you see the galaxy background?
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by Citronix** [comment]
Here is the output_log ​
 output_log.txt
<https://drive.google.com/file/d/0B6Rq-16INMVpcDYyU2R1eVVuMmc/view?usp=drive_web>
​1.I wait a bit more than 5 min but still loading :/
2.It don't seems to work (I wait 7 min) :/
4.It don't seems to work to, but if I presse Tab my inventorie open, the
only "working" category is the paint (the textures are good) but only for
the paint :/

2017-10-27 6:47 GMT+02:00 Francois Duret <notifications@github.com>:

**Comment by Citronix** [comment]
![20171027161219_1](https://user-images.githubusercontent.com/33103748/32109921-6b161250-bb36-11e7-86e3-c3699b5c6db0.jpg)

**Comment by tsunamayo** [comment]
Hi, you clearly have issue with your gfx card. Could you please make sure that your drivers are up to date? Also, could you please drag and drop the output_log over there, no need to upload it on Google Drive (it was not working). Thanks!

**Comment by Citronix** [comment]
I can't drop the output_log here, it's bigger than 10MB :/
And for my graphique card , I was wrong, I don't have a geforce gt 620, I have a geforce gt 260 ...

**Comment by CaptainCJH** [comment]
Gateway Laptop with Intel I5-2450M 2.5 Ghz with 4GB RAM and built in Intel HD3000 with driver 9.17.10.4459 stays on loading screen forever. If this game uses OpenGL version 4= then that is the problem. The HD3000 series supports up to vesrion 3.1 and does not support OpenGL 4+. Only the HD4000 series+ supports OpenGL 4+.

**Comment by tsunamayo** [comment]
Yes sorry those card are way too much below the minimum specs, and dont even support Directx11 ... Thanks

**Comment by CaptainCJH** [comment]
I disagree. I can run Men of War Assault Squad 2 which IS a DirectX 11 game on my Gateway laptop I5 with Intel HD3000.
