### ISSUE TITLE
Deleting a Mirrored linked Pipe then reconnecting it locks all character interactions

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#214]
![image](https://user-images.githubusercontent.com/33023316/32065597-17131dcc-ba75-11e7-95b6-2fbc0937d824.png)

After linking one side and checking the other I realise the hose was very not what I wanted. So I went and deleted the unlinked mirrored hose and placed a new one. Going back to the other side, the linked hose had a ghost connection. Thinking nothing of it, the game allowed me to link from the original master hose brick to the new hose brick while the ghost link was still there... bad idea that was to trust it..

Now unable to load any menus, restricted to character movements only. Not even able to scroll the hotbar or build/destroy

**Comment by tsunamayo** [comment]
Hi, this bug was booked and fix a day ago - fix will be up in the next build (or is already in experimental). Thanks!
