### ISSUE TITLE
[BUG] Holo-Map freezing

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Skywanderers#217]
The molo-map consistently freezes when zoomed into the galactic centre.
While I can still play the game as normal, the holo-map becomes unusable with a hourglass when i mouse over it.
It's also worth noting I get no fps drops with the map zoomed into the galactic centre so it is unlikely to be due to my computer.

**Comment by tsunamayo** [comment]
Hi, I do not reproduce on my side - as you seems to be able to reproduce could you please give me details on how you proceed (do you assign yourself the focus point)? Also if you could send you your output_log file. Thanks!

**Comment by alxnns1** [comment]
Hi, I zoom into the centre of the galaxy until I can individual stars then I try to move the focus point nearer one of the stars...I then get an endless hourglass loading symbol...I am unable to send the output log atm but as soon as I am I will post it here

**Comment by Hutzlipuh** [comment]
Same Problem for me , but im not zooming in center but on custom set point near my location.
https://imgur.com/a/uuwPj.

Initialize engine version: 5.6.0b11 (a13db154d9f7)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4058 MB
    Driver:   22.21.13.8541
Begin MonoManager ReloadAssembly
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-UnityScript.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Assembly-UnityScript.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\AmplifyBloom.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\AmplifyBloom.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\AmplifyOcclusion.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\AmplifyOcclusion.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Vectrosity.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\Vectrosity.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\TextMeshPro-1.0.55.56.0b12.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\TextMeshPro-1.0.55.56.0b12.dll into Unity Child Domain
- Completed reload, in  0.040 seconds
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Skywanderers\Skywanderers_Data\Managed\System.dll (this message is harmless)
OnLevelWasLoaded was found on LineManager
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 375)

desktop: 1920x1080 144Hz; virtual: 3840x1080 at 0,0
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.034129 ms
SETTINGS Loaded
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

RESTARTING THE GAME
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading all textures
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TEXIM LOADED 391
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fonctionnal Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Hull Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Functional Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Logical Components
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Paints
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading player 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 18.908062 ms
RESTARTING THE GAME
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading all textures
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TEXIM LOADED 391
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fonctionnal Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Hull Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Blocks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Functional Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Logical Components
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Construction Bricks
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Paints
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading player 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 5998 unused Assets to reduce memory usage. Loaded Objects now: 4463.
Total: 8.886680 ms (FindLiveObjects: 0.648765 ms CreateObjectMapping: 0.441237 ms MarkObjects: 5.025058 ms  DeleteObjects: 2.770343 ms)

LOADING CHARACTER : MPW
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

network adress 0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

OnPlayerConnected
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Level 0 computation finished 107606
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Level 0 computation finished 109528
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 2.154143 ms
Loading player 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

There has been an awakening. From the Block Entity Manager.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Local player Start sequence.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 90 unused Assets to reduce memory usage. Loaded Objects now: 8162.
Total: 10.101838 ms (FindLiveObjects: 0.569904 ms CreateObjectMapping: 0.173365 ms MarkObjects: 9.267255 ms  DeleteObjects: 0.090673 ms)

Active Slot is : 0 / Starter Block
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

remove particle
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NEW SYSTEM
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LOAD c[64 0 30]l0n0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

RADIUS 10430.38 | DEPTH 2048
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

total stars 39451
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command already existing voxel : (1 0 4) stud : (-4 13 -14)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command already existing voxel : (1 0 4) stud : (-4 8 -14)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Galaxy Skybox compute finished
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Enabling or adding a Renderer during rendering; this is not allowed. Renderer 'Cube' will not be added.
 
(Filename:  Line: 290)

Enabling or adding a Renderer during rendering; this is not allowed. Renderer 'Cube' will not be added.
 
(Filename:  Line: 290)

Active Slot is : 1 / Identity Unit
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 2 / Spaceship Core
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 3 / Hull Basic
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 4 / Hull Basic
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 5 / Hull Basic
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 6 / Hull Basic
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 7 / Hull Basic
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Active Slot is : 8 / Flat Hull Corner
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Enabling or adding a Renderer during rendering; this is not allowed. Renderer 'Cube' will not be added.
 
(Filename:  Line: 290)

Enabling or adding a Renderer during rendering; this is not allowed. Renderer 'Cube' will not be added.
 
(Filename:  Line: 290)

Enabling or adding a Renderer during rendering; this is not allowed. Renderer 'Cube' will not be added.
 
(Filename:  Line: 290)

new star level 2|25000|44945
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 2|25000|43633
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 3|12500|55210
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 4|6250|27467
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 5|3125|10660
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 6|1562.5|5460
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Set new system target System : [64|0|30]:0:0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Set new system target System : [64|0|30]:0:0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

IndexOutOfRangeException: Array index is out of range.
  at World.Galaxy.GalaxyStarLevel.CheckForNebula (Int32 zoomTarget) [0x00000] in <filename unknown>:0 
  at World.Galaxy.GalaxyStarLevel.OnNewFocusPoint () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at Game.Device.HoloNavigator.GalaxyHolo.SetNewFocusPoint (Vector3 position) [0x00000] in <filename unknown>:0 
  at Game.Device.HoloNavigator.GalaxyHolo.SetNewZoomFocus (Vector3 focusPointTarget, Int32 newZoomTarget) [0x00000] in <filename unknown>:0 
  at Player_NetworkSetup.RpcHolomapGalaxyNewZoomFocus (VoxelCoordNet voxelCoordNet, Vector3 focusPointTarget, Int32 zoomTarget) [0x00000] in <filename unknown>:0 
  at Player_NetworkSetup.InvokeRpcRpcHolomapGalaxyNewZoomFocus (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkIdentity.HandleRPC (Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.ClientScene.OnRPCMessage (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkConnection.InvokeHandler (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.LocalClient.ProcessInternalMessages () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.LocalClient.Update () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkClient.UpdateClients () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

new star level 6|1562.5|5641
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 5|3125|10828
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 4|6250|27520
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Spawn stars
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 3|12500|53588
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Spawn stars
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 2|25000|43076
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

IndexOutOfRangeException: Array index is out of range.
  at World.Galaxy.GalaxyStarLevel.CheckForNebula (Int32 zoomTarget) [0x00000] in <filename unknown>:0 
  at World.Galaxy.GalaxyStarLevel.OnNewFocusPoint () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at (wrapper delegate-invoke) World.PlanetarySystem/OnNewSystem:invoke_void__this__ ()
  at Game.Device.HoloNavigator.GalaxyHolo.SetNewFocusPoint (Vector3 position) [0x00000] in <filename unknown>:0 
  at Game.Device.HoloNavigator.GalaxyHolo.SetNewZoomFocus (Vector3 focusPointTarget, Int32 newZoomTarget) [0x00000] in <filename unknown>:0 
  at Player_NetworkSetup.RpcHolomapGalaxyNewZoomFocus (VoxelCoordNet voxelCoordNet, Vector3 focusPointTarget, Int32 zoomTarget) [0x00000] in <filename unknown>:0 
  at Player_NetworkSetup.InvokeRpcRpcHolomapGalaxyNewZoomFocus (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkIdentity.HandleRPC (Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.ClientScene.OnRPCMessage (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkConnection.InvokeHandler (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.LocalClient.ProcessInternalMessages () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.LocalClient.Update () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkClient.UpdateClients () [0x00000] in <filename unknown>:0 
  at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

new star level 6|1562.5|5527
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 5|3125|10811
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Spawn stars
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 4|6250|27501
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 3|12500|54410
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

new star level 2|25000|43522
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

EXIT TO DESKTOP
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 16dc -> priority: 1 
  Thread -> id: 47c -> priority: 1 
  Thread -> id: 24a4 -> priority: 1 
  Thread -> id: 27c8 -> priority: 1 
NullReferenceException: Object reference not set to an instance of an object
  at Common.Rendering.RenderingPipeline.OnEnable () [0x00000] in <filename unknown>:0 
UnityEngine.Transform:set_parentInternal(Transform)
UnityEngine.Transform:set_parent(Transform)
PlayerCommandManager:UnlockParentEntity()
TorusLeaf:OnDisable()
 
(Filename:  Line: -1)

unparenting camera from torus
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
