### ISSUE TITLE
Block Codex variants indicator (type, size) incorrectly identifies wrong variant

### ISSUE THREAD

**Issue by ggrdk5478** [tsunamayo/Skywanderers#218]
If you choose a different variant from the first and then switch to another block, the indicator stays on that index rather than resetting to the first one of the group.

Steps to reproduce:
1. Select a block with multiple variants
2. Select a variant that's not the default
3. Select another block with multiple variants

Result:
The selection shows the same index as from Step 2 even though the block selected is the default.

Also, this occurs if you go back to the block in Step 1.

Screenshots showing the Engine Unit after selecting the cylindrical one, switching to another block, and back.  The square EU is displayed but the cylindrical one is shown selected.

![20171026172044_1](https://user-images.githubusercontent.com/33104013/32080019-e898368c-ba72-11e7-816f-f89fb0c4108a.jpg)

![20171026172050_1](https://user-images.githubusercontent.com/33104013/32080021-eb21ea92-ba72-11e7-9ab3-2c0e3526b8e1.jpg)

**Comment by tsunamayo** [comment]
Thanks! Will be fixed in upcoming update. Cheers
