### ISSUE TITLE
[Low] [Visual] Wireframe in a Moving Ship

### ISSUE THREAD

**Issue by Avahlina** [tsunamayo/Skywanderers#22]
When travelling at any speed the block wireframe starts to hop and jitter behind the block you hover over. The faster you go, the further behind the block the wireframe appears. This happens on every block while the ship is moving. 

Happens consistently for me in build 2017-01-25, not sure about earlier builds since I haven't been moving around too much in space previously.

I prepared a gif to illustrate:
https://gfycat.com/ClosedDeafeningIberianmidwifetoad

**Comment by tsunamayo** [comment]
Thanks, issue should  be fixed in the next build.
