### ISSUE TITLE
[BUG] Overlapping Options Menu

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#220]
Sometime when bringing up the menu, there will be multiple menus overlapping with each other.
![2017-10-26 4](https://user-images.githubusercontent.com/26584892/32083358-9ce6d4b8-ba87-11e7-99f5-0257d1c73f55.png)

**Comment by tsunamayo** [comment]
This was reported and will be fixed in next update. (or in experiemental) Thanks!
