### ISSUE TITLE
Ship Hologram Window Bug

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#221]
When a ship hologram is in front of a window, the ship is hidden in the solid lines of said window.

![20171026211213_1](https://user-images.githubusercontent.com/28989460/32085068-a5126e94-ba92-11e7-8ab0-8c82b12e556f.jpg)

![20171026211519_1](https://user-images.githubusercontent.com/28989460/32085091-c96785d6-ba92-11e7-963b-f1d13e520a32.jpg)

**Comment by tsunamayo** [comment]
It should be fixed in the next build. I wasnt able to reproduce as I think the occurence is random, so if you still see the issue please re-open it. Build will be live soon. Cheers!
