### ISSUE TITLE
GPU Usage 

### ISSUE THREAD

**Issue by Badwolf15002** [tsunamayo/Skywanderers#222]
Iv got a GTX 1050ti GPU. And when i start the game it pushes the entire GPU to its max. Idk if itd optomized or what not. But im sure this shouldnt happen.

**Comment by tsunamayo** [comment]
Hi. Could you activate vsync in graphical options?

**Comment by Badwolf15002** [comment]
Isnt Vsync to get rid of screen tearing? And i do have it active. But lime i said it uses my entire GPU. And i can hear the GPU fan (a jet engine) at full power xP. 

I could use this is heat my room in the winter xP.

**Comment by LeMinaw** [comment]
Would be useful to know at how many FPS you run.

**Comment by Badwolf15002** [comment]
Idk what the FPS it is but it runs smoothly. Also can i keep this version of the game? I can use this version to purposely heat up my GPU to warm up my room xP.

**Comment by LeMinaw** [comment]
Running smoothly or not is not the point. Tsuna suspects that this overconsumption is due to a lack of framerate limitation (your GPU computing too much frames per second).

(Btw, no need for skywanderers to keep your GPU hot, run any benchmark or stress test tool you can found on the internet)

**Comment by Badwolf15002** [comment]
Ah i see. Cool. I’ll keep playing and see what else i run into.
