### ISSUE TITLE
light shader bug

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#223]
was working on a build that had a rotor in it to give 8 points of symetry
parts of the build were illuminated with red lights
i placed a while light block directly onto the rotor and i cannot say if it happened immediately but it caused 1 quarter of my build (everything attached to the rotor) to be illuminated differently. upon seething this i started removing light sources thinking it just need an update to the lighting in the area and when i removed the light block from the rotor and replaced it with a standard block the lighting issue was fixed

**Comment by tsunamayo** [comment]
Could you take a screenshot of the issue that would really help! Thanks

**Comment by Mellcor** [comment]
here you go
https://pasteboard.co/GQOl4Pi.png
also messaged you on discord if you wish to talk there

**Comment by tsunamayo** [comment]
Hi, these lighting artifact should have been fixed with the new Light update. Thanks!
