### ISSUE TITLE
Transparent microblocks stud glitch

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#227]
The 0.25m transparent cube has the stud inside the block, rather than on the outside.
![20171027012523_1](https://user-images.githubusercontent.com/33016249/32089116-12f8750c-bab6-11e7-8e04-241ede098b5a.jpg)

**Comment by tsunamayo** [comment]
Thanks for the spot! It will be fixed in the next update. Cheers!
