### ISSUE TITLE
[Experimental Build] Turrets don't correctly point to cursor

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#228]
Turrets don't seem to want to correctly point to where you are looking. Both are controlled from sitting in a chair and controlling the ship as if you were to fly it etc. They worked just fine when I finished working on my AAT but now they've gone bonkers.
![untitled](https://user-images.githubusercontent.com/32974671/32089111-ab46c380-baad-11e7-9e31-33b5be145623.png)
![untitled1](https://user-images.githubusercontent.com/32974671/32089112-ab550dfa-baad-11e7-8add-e39c9310b345.png)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1420863/output_log.txt)

**Comment by tsunamayo** [comment]
Hi! Could you please send me your blueprint? Amazing build btw ;-) Thanks.

**Comment by tsunamayo** [comment]
I guess it is fixed now ;) Thanks for being one of the top booker from the start!
Cheers
