### ISSUE TITLE
[LOW] [Block Request] 45 degree angle Fence block

### ISSUE THREAD

**Issue by trekfan42** [tsunamayo/Skywanderers#23]
![ejwnymsnwyamanbdgadzq4uzdsiuizqawu6p6u7to76pea_lbozqnbib7kfusxyrolzpbnsy7eiyt7f13fbusz1u7ioqnj7midemr0q5j_pxwvagrocxedmx4cw9srezn_p9aen_ihg](https://cloud.githubusercontent.com/assets/14896909/22399610/42b2af6a-e56e-11e6-90e3-3301a512a710.png)

**Comment by AfterRebelion** [comment]
There are now Fence Corners.
