### ISSUE TITLE
Tooltip delay too long

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#230]
When browsing the codex the tooltip delay is just too long to make it easy to identify what is what quickly.

Having to wait 1 second to see if this brick I'm holding is a Not gate or a Dual link gate is a tad bit too long and when frantically moving your mouse to find the right brick this delay is just too long.

I'd make the delay 0 ms so that you see it instantly.

**Comment by tsunamayo** [comment]
I agree, I did the change and actually improve a bit how the tooltip was displayed, now it lock on top of the item icon. Thanks!
