### ISSUE TITLE
Allow for logic wires to be all made visible 

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#231]
Allow for logic wires to be all made visible regardless of what type of block/brick you are holding so we can more easily debug more complex logic setups.

One way could be for instance when holding the ALT key it just makes them all visible. Or perhaps make it a toggle.

**Comment by tsunamayo** [comment]
I am now seriously considering the use of a wiring tool for doing link assignment. I will do a post in the forum soon.

**Comment by AfterRebelion** [comment]
Link tool is already avaliable, but there is no way to make all connections visible atm in the most recent version (19w23b)
