### ISSUE TITLE
Destroying Camera with Player viewing it, causes controls to lock.

### ISSUE THREAD

**Issue by JennyLeeP** [tsunamayo/Skywanderers#234]
When the camera is destroyed, the player viewing from the camera loses all control input.
Everything in the game stops rendering, except for the skybox? [see image] .  
[The image](http://steamcommunity.com/id/JennyLeeP/screenshot/852730190922524856)

Sounds can still be heard.

**Comment by JennyLeeP** [comment]
Fixed image link.

**Comment by CyaNox** [comment]
Reproducible test ship:

Use the joystick then kill the camera using the left mouse key and bug happens there.

[Camera Stuck Bug.zip](https://github.com/tsunamayo/Skywanderers/files/1421050/Camera.Stuck.Bug.zip)

**Comment by tsunamayo** [comment]
Thanks for reporting the bug and many thanks for the blueprint test case, very precious 🥇 ! It is fixed now, default behaviour is that you will be ejected from all entered command on destroy (including the seat ...)
