### ISSUE TITLE
Escape key does not work in all interfaces as expected

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#235]
In the following interfaces "Escape" does not close the window prior to opening the main menu:

- Construction Identity
- Custom Paints
- Constant Gate
- Mix Gate

In most of these interfaces double tapping Escape (to escape the main menu) captures the mouse again making it not possible to interact with the existing interface (which is still visible) until you open the main menu again.

Also the Blocks Codex can be opened in the main menu.

This seems to also happen in the experimental branch.

Addendum: Almost all interfaces where the escape key messes up the Blocks Codex can be opened as well.

**Comment by tsunamayo** [comment]
Thanks indeed there was a regression - and I added the ability to Escape all the menu cited. Thanks again! Cheers
