### ISSUE TITLE
Make current build and branche visible

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#236]
Currently it is near impossible to see what version or even what branch you are on.

Especially during testing and frequent updates it is handy to know in game exactly what version you are running. This will also assist in debugging or catching any update issues if they arise.

If for instance the version number and branch is always visible in the bottom right corner any screenshots will clearly state what branch and version they are on.

**Comment by tsunamayo** [comment]
Yes I am looking into a way to do that automatically. Thanks for being an precious tester ;-)

**Comment by tsunamayo** [comment]
Okay I will do it manually for now, starting from next build it will be available. Cheers

**Comment by CyaNox** [comment]
I'd love to have the version always visible during the development cycle as this might make things simpler. Here is a quick mockup of what I mean:
![2017-10-28-17-36-14](https://user-images.githubusercontent.com/211381/32135895-a46fefbe-bc06-11e7-9722-52d33cbe955e.png)
