### ISSUE TITLE
[Bug][Build 2017-10-27][Minor]Player customization menu helmet and name.

### ISSUE THREAD

**Issue by Hanfree85** [tsunamayo/Skywanderers#237]
In the player customization menu if you put a name that contain H put and release the Helmet
![20171027100900_1](https://user-images.githubusercontent.com/33139962/32094243-5dfa8a56-baff-11e7-8d47-9fb12ffe7fd7.jpg)
![20171027100903_1](https://user-images.githubusercontent.com/33139962/32094246-5fbf4476-baff-11e7-89f4-1e2df4fd3c04.jpg)
![20171027100905_1](https://user-images.githubusercontent.com/33139962/32094249-60ad5f30-baff-11e7-8dc8-90b940b8c86b.jpg)
![20171027100906_1](https://user-images.githubusercontent.com/33139962/32094252-61a713cc-baff-11e7-9a9e-7a2f0ca45a47.jpg)

**Comment by tsunamayo** [comment]
Haha nice spot indeed! Thanks for that one. It is fixed now! Cheers
