### ISSUE TITLE
Bug when docking that causes docked ships to move. [Bug]

### ISSUE THREAD

**Issue by Magical-Male** [tsunamayo/Skywanderers#238]
Every ship that I have docked so far has this issue. When I have docked a ship to another ship this issue occurs, however I have not tried to recreate the issue with a station. When the ship begins to move the docked ship jumps away from the main ship but stays docked.
Video here:
https://www.youtube.com/watch?v=OQI1JQWRueU&feature=youtu.be

![20171027085529_1](https://user-images.githubusercontent.com/33147714/32095682-dccb3a82-bafb-11e7-8883-b6a9900f5401.jpg)
![20171027085537_1](https://user-images.githubusercontent.com/33147714/32095683-dce54f76-bafb-11e7-83f0-bd8ac2322ddc.jpg)
Example of another ship having this issue:
![20171027101446_1](https://user-images.githubusercontent.com/33147714/32096942-dcc72ac4-baff-11e7-9273-b32f20e792ba.jpg)
![20171027101450_1](https://user-images.githubusercontent.com/33147714/32096943-dcea196c-baff-11e7-9fe5-fbbc64cc3a28.jpg)
![20171027101508_1](https://user-images.githubusercontent.com/33147714/32096944-dd0c30b0-baff-11e7-998a-85ae453dec28.jpg)

This time the effect is not as bad but is still there and can be seen.

**Comment by Hanfree85** [comment]
I reproduce it 
![20171028163134_1](https://user-images.githubusercontent.com/33139962/32135350-00ea4054-bbfe-11e7-87ae-e38a3fdec4c0.jpg)
![20171028163230_1](https://user-images.githubusercontent.com/33139962/32135351-010de45a-bbfe-11e7-89ea-1e9c90be25bd.jpg)

**Comment by tsunamayo** [comment]
Okay thank you both for this detailed bug report! 👍  Issue should be fixed in the next update! Cheers
