### ISSUE TITLE
[LOW] [Block Request] flat 2x1 canopy block

### ISSUE THREAD

**Issue by trekfan42** [tsunamayo/Skywanderers#24]
marked in red
![ejwnyeeohcamamc_8acwfph6gwieszqsqpgw2b_vzne-6hmxotqp0udhtkoz8kh6co9qsi7m5cqh16kj3yaihhjeuck06w7o0shahyi8t_qv61a3iaduqei0mbe2xc_o3or6_gahzikr](https://cloud.githubusercontent.com/assets/14896909/22399619/6ddc9d22-e56e-11e6-85b9-72893d1c6231.png)

**Comment by Rizzo911** [comment]
+1 vote from me

**Comment by trekfan42** [comment]
Nice thanks. Haha

**Comment by AfterRebelion** [comment]
Canopy can be freform now, so this issue is no longer valid in recent versions (19w23b)
