### ISSUE TITLE
Hoses connections are not saved in blueprints.

### ISSUE THREAD

**Issue by HadesDeadlyTom** [tsunamayo/Skywanderers#240]
I guess you already know that, but I did not find any issue for it.

![ss 2017-10-27 at 12 03 56](https://user-images.githubusercontent.com/33090879/32099157-7bae84d4-bb0f-11e7-95ab-83835757a30a.jpg)
![ss 2017-10-27 at 12 03 20](https://user-images.githubusercontent.com/33090879/32099161-7fc44496-bb0f-11e7-912d-87dbef85c424.jpg)

**Comment by tsunamayo** [comment]
No I didnt knew that! Thanks for pointing that out! It is fixed now, fix will be available in build 17w43a .
Cheers
