### ISSUE TITLE
Attachment points on Rotating Brick invisible in certain angles

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#241]
In some angles the little nubbins never show up no matter the angle of the mouse while at other positions and even further away the nubbins do show up just fine.

Not visible (at any angle of the mouse):
![Not visible (at any angle of the mouse)](https://user-images.githubusercontent.com/211381/32103208-aaea6546-bb1f-11e7-8cf6-553c817b7a5a.png)
Working just fine:
![Working just fine](https://user-images.githubusercontent.com/211381/32103211-ae0bd3cc-bb1f-11e7-92b1-a207a5f0b7c6.png)

**Comment by CyaNox** [comment]
In this configuration it is nearly impossible to get the nubbins to show up at all on the rotor under the cursor:
![2017-10-27-14-15-18](https://user-images.githubusercontent.com/211381/32103585-5b99ed7a-bb21-11e7-9b34-808c47b2077d.png)

**Comment by tsunamayo** [comment]
This issue was fixed! Thanks for the clear report. Cheers
