### ISSUE TITLE
Beam Block inconsistencies or incorrect behavior?

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#242]
When trying out the beam block I randomly tried some configurations and found them to be inconsistent.

In the examples provided below I found that number 3 has the expected result while all the others are wrong when you consider number 3 actually works.

I'm not sure what the expected behavior should be though since it could be that number 3 is the wrong one and all the others are the expected result.

![2017-10-27-15-25-13](https://user-images.githubusercontent.com/211381/32106114-0d3dc610-bb2b-11e7-9750-f8c0919bc949.png)
![2017-10-27-15-23-54](https://user-images.githubusercontent.com/211381/32106119-107024d6-bb2b-11e7-81df-49a9a80b2a38.png)

[Beam Odities.zip](https://github.com/tsunamayo/Skywanderers/files/1422158/Beam.Odities.zip)

**Comment by tsunamayo** [comment]
Thanks a lot for the detailed test case, I will check that as soon as I can! Thanks for being such an amazing tester 🥇

**Comment by tsunamayo** [comment]
Okay I am just checking this now, in fact beam collisions is not working (not supposed to work), so I guess all case behave as expected... I might upgrade beam logic at one point when I have time, aka not on the short term ... Thanks
