### ISSUE TITLE
Mech Core Not Working

### ISSUE THREAD

**Issue by Captain-Wolfsburg** [tsunamayo/Skywanderers#243]
I've installed a mech core on a project, and when I try to access the menu, it flickers and I can't click anything. When i try to destroy it and place another, it won't break (and neither will anything else from that point on). Reloading my game allows me to break the core and place a fresh one, but they are continuing to glitch and flicker despite multiple reloads and complete reboots of the game.

**Comment by tsunamayo** [comment]
I am not reproducing this issue. Could you please send me your blueprint? Did you made anything specific on that project? Thanks!

**Comment by arkpaladin** [comment]
I'm getting the same error here, I do have a video showing how my mech is built. All I am doing is getting the leg joins in as well as a rotating block for the top section for it to freely rotate. And after that point I can no longer place blocks or break blocks.

[Unlisted Youtube Video](https://www.youtube.com/watch?v=PHQ_8rE5sVc)

**Comment by arkpaladin** [comment]
I actually discovered why it was actually glitching out! Its the placement of the mech core in relation to the rest of the mech itself when a rotating block is concerned seeing it doesn't seem to recognize that block as a valid part or some such like that!

[Mech Bug Troubleshooting](https://youtu.be/elAbHujtNSI)

**Comment by tsunamayo** [comment]
Okay thanks for your help, this is now fixed (now you cant build it on a children entity). Cheers
