### ISSUE TITLE
Some parts do not mirror correctly

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#246]
before

![image](https://user-images.githubusercontent.com/33023316/32115551-2c36e902-bb3f-11e7-814e-75c99741cf58.png)

after placing Flat Hull Piece triangle

![image](https://user-images.githubusercontent.com/33023316/32115572-4096a554-bb3f-11e7-98b5-cac806259d23.png)

This is the only part thus far I have found this issue on.

**Comment by tsunamayo** [comment]
Fixed, thanks! Btw I had to update the mesh of this block, so it you will have to rebuild it after the next update ... Cheers
