### ISSUE TITLE
Character interactions and movement not locked when accessing pop-up menus and then pressing Inventory or Pause menu

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#247]
![image](https://user-images.githubusercontent.com/33023316/32115756-f10cdca0-bb3f-11e7-8114-645c3ffc823c.png)

so for example pressing "i" will bring up the inventory tab underneath the Identity popup

**Comment by Napther** [comment]
This also works on ANY pop up menu I just noticed. You have a screen in front of you with buttons but you cant select any as the mouse looks the camera around instead after pressing Inventory and then exiting

**Comment by tsunamayo** [comment]
This regression was reported #235 and fixed and will be in 17w43a. It was messy sorry for that. Thanks!
