### ISSUE TITLE
Drill Unit will drill your own ship when held in hand

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#248]
...This luckily did not remove any important logic blocks but was a surprise.

Place the drill unit in hand and begin "waving" it against a ship. The drill unit will break blocks on the ship without any input from the player

**Comment by tsunamayo** [comment]
Ahaha seriously? Havent use it in age, thanks for the find.

**Comment by tsunamayo** [comment]
Okay fixed, contender for the derpest bug so far. Cheers!
