### ISSUE TITLE
Chairs Affect Player Orientation

### ISSUE THREAD

**Issue by Icarus-V** [tsunamayo/Skywanderers#252]
After building a chair on the wall that faced upward in the tutorial building, I sat in it. Upon getting out of the chair, walking forward made me ascend into the sky, as if my character's orientation was permanently affected by the chair's orientation. The only way I could solve this was building a chair on the floor and sitting in it. Upon leaving that chair, my orientation was corrected.

**Comment by tsunamayo** [comment]
Hi! You need to double-tap Q (or the key you assigned for crouch) in order to align to the surface.
