### ISSUE TITLE
Minor visual bug just above hotbar in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#255]
Just above each hotbar slot there is a small line: 
![2017-10-28-12-43-38](https://user-images.githubusercontent.com/211381/32133741-6c143120-bbde-11e7-9343-1e7d10d168d3.png)

**Comment by tsunamayo** [comment]
You are very good at spotting these kind of details! 👍  Yes it is an artifact due to the new name, I fixed it! Cheers
