### ISSUE TITLE
Z-Fighting in new Stud target highlighting in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#256]
The new red highlight for the targeted stud is z-fighting with the stud that was already there:
![2017-10-28-12-54-54](https://user-images.githubusercontent.com/211381/32133773-230ba1e2-bbdf-11e7-8385-3aa5c140c482.png)

**Comment by tsunamayo** [comment]
Thanks indeed - I dont see that on my side but it is making sense. I will fix it.

**Comment by tsunamayo** [comment]
Okay this issue is finally fixed. Thanks
