### ISSUE TITLE
[BUG] Can't Place Bricks On Command Panel

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Skywanderers#259]
When I place down a command panel (the bigger one) and try to place bricks on it, the little blue square highlights red but I am unable to place the brick.

**Comment by CyaNox** [comment]
I can confirm this in 17w43a.

**Comment by tsunamayo** [comment]
Okay make sense - with the new geo check on stud this block is messing with us. This is a limitation due how Unity handle the convex mesh collider for this particular shape (collider will look exactly like the Bevel shape). I had a workaround planned, but now I will make it top priority. Thanks

**Comment by tsunamayo** [comment]
Okay fixed, will be in 17w44a. Thanks!
