### ISSUE TITLE
Holo interface interaction improvements

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#260]
The holo interface that pops up on `SHIFT + RMB` seems to behave in a slightly derpy way which is not exactly obvious.

The holo interface that I'm referring to:
![The holo interface](https://user-images.githubusercontent.com/211381/32133953-c346dc46-bbe2-11e7-8eac-960c26506235.png)

Currently `LMB` is the button that will interact with the holo interface once it is opened. To me it seems more logical that the interaction with the holo interface is bound to the same button that opened it thus `RMB`. This would also prevent accidentally breaking things behind the holo display (Accidentally placing things is less of a issue since that does not break logic connections).

As a side note I think the holo display should have a clearer background so that it is easier to see when you are clicking within its bound or just outside (here is a quick visual of what I'm thinking about): 
![2017-10-28-13-34-19](https://user-images.githubusercontent.com/211381/32134113-27974250-bbe6-11e7-8679-c9f7b7b92664.png)

**Comment by tsunamayo** [comment]
Thanks, actually I am not satisfied at all with that holo display - on paper it is nice and fancy, but it seems to not work that well in reality. I could spend more time and fix it, but I am now considering to use a static wheel menu option, with several features.
You middle click, and then can quickly choose between several action, including Pick block, Pick color, name, reset ect... 
For the preview name, I am not sure if I want to keep it or not.
I dont know if you have a though on that.

**Comment by CyaNox** [comment]
If by preview name you mean this: 
![2017-10-28-14-56-51](https://user-images.githubusercontent.com/211381/32134589-2f7b5538-bbf0-11e7-9d95-7fa748c4cae3.png)
Then I think it is a useful feature and fairly heavily used already in many places by many people. In the startup world I can already see many places it is actively being used to indicate various useful buttons. The text makes it really easy to identify what button does what.

It could possibly do with a darker background so that the text contrast gets slightly higher for those situations where visibility and contrast are desired.

**Comment by CyaNox** [comment]
With regards to the radial menu idea ... I like that ... so long as it does not get as confusing as Ark's radial menu mess.

**Comment by tsunamayo** [comment]
Okay, if you could tell me what is wrong with Ark I can try to avoid it ;-).
What I plan to do: 

- Limited number of actions
- Only low frequency, 0 stress actions 
- Always same actions disposition, even when a given action is not present (for muscle memory)
- Have icon and a name on hover
- Hold MMB by default => it is a lot better if it is on the mouse

**Comment by CyaNox** [comment]
I've already elaborated more on what was bad in Ark's wheel menu design on the forum: https://www.skywanderersgame.com/forum/viewtopic.php?f=11&t=206&sid=e4c8f67d5281c94c0be0cccafb2a339d#p1301 .

Beyond that I think most of what you've said thus far seems to indicate to me that your current stance on the wheel design is good and I'm looking forward to its actual implementation.

**Comment by AfterRebelion** [comment]
Holo interface is no longer avaliable, and a radial menu is used instead (Althought the configure option is not working right now), so this issue no longer valid in recent versions (19w23b)

**Comment by tsunamayo** [comment]
No configure action, all the block were redesigned to account for that. Cheers
