### ISSUE TITLE
'round' thruster block visual issue

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#262]
with 'round' thrusters it is assumed that should they be placed next to each other on the same axis then the light emitting part of the thruster should join, however when done this is not the case, byt when placed on the diagonal the visual change happens tho not at the correct angle

https://steamuserimages-a.akamaihd.net/ugc/858359955732568286/0268240576F964B8A9CE7F8141B4A3F9748CBB8E/
https://steamuserimages-a.akamaihd.net/ugc/858359955732572139/37857021AEA6CD3B12634FCA2E5A187C52ABE055/

**Comment by tsunamayo** [comment]
Thanks, the texture and UV are now fixed! Cheers
