### ISSUE TITLE
Button Tooltips phase out of position during hyperspace jump.

### ISSUE THREAD

**Issue by AlexCory** [tsunamayo/Skywanderers#263]
In this example, I am driving one of the prebuilt ships thru hyperspace.  Notice the "Seat" tooltip way over in the distance.  It's supposed to be over the red button in the bottom right of the screenshot.  The button still functions normally however, so its a relatively minor issue.

Screenshot: https://imgur.com/UnMaHdj

**Comment by tsunamayo** [comment]
Hi, are you using Warp or the Hyper Drive ? Thanks!

**Comment by AlexCory** [comment]
It occurs while using the Hyper Drive.  In mid jump sequence.

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
