### ISSUE TITLE
Various interfaces don't block the Undo and Redo keys in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#267]
While messing about in the Text Screen I found out that `CTRL + Z` (and also `CTRL + Y`) actually function as undo and redo keys ... however not on the text but rather the placed blocks.

This was kind of suprising as I was in an interface that should have captured such world modifying key combinations in the first place. Also it should have performed actions on the text rather than the world.

So far just about any interface that I've tested allow the undo and redo keys to act on the world. Some of these interfaces are:

- Construction Identity
- Custom Paints
- Constant Gate
- Mix Gate
- Storage Unit
- Text Screen

Furthermore the Undo and Redo keys also act on the world if you are controlling a craft, camera or turret.

I was happily surprised that there were undo and redo keys so please don't remove those ... just improve them ;)

**Comment by tsunamayo** [comment]
Okay it is fixed now! Thanks a lot!
