### ISSUE TITLE
Undo and Redo fail to restore data in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#268]
When trying to undo a logic tile that was connected that was broken, the logic wire will not reappear.

When placing a Text Screen, editing its text, then pressing the Undo key followed by the Redo key the text in the Text Screen will be reset to default.

When breaking a Text Screen with modified text in it and then pressing the Undo button does not restore the text on the Text Screen to what it should have been.

All of the above also apply to the Constant Gate, Mix Gate and Storage Unit.

I'm sure this will affect other blocks as well that store any extra data.

**Comment by tsunamayo** [comment]
Yes indeed, have a fully working Undo / Redo stack is indeed a big task... I wont put it high priority unfortunately =(

**Comment by AfterRebelion** [comment]
Undo/redo as far as I know is no longer avaliable, so this issue no longer valid in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Yes, this is actually too much work to maintain, that is why I got rid of that. Cheers
