### ISSUE TITLE
Block placement orientation bug

### ISSUE THREAD

**Issue by Deamonsins** [tsunamayo/Skywanderers#269]
When i place i halfblock or any block that's not full size i can't get the orientation right on one axis, the straight one. See picture for context and look at the cursor focus.
![placement error](https://user-images.githubusercontent.com/33181273/32136004-57dde6cc-bc08-11e7-8e51-3ec820d13061.png)

**Comment by tsunamayo** [comment]
Hi, I am not sure to understand the problem - I tested it an it was working fine. If you cant click on top at first, just hold click on the middle at first and then move the cursor a bit to the top, that will do the trick! Thanks
