### ISSUE TITLE
[BUG] speed not updated after collision

### ISSUE THREAD

**Issue by Deamonsins** [tsunamayo/Skywanderers#270]
[speed not updating.zip](https://github.com/tsunamayo/Skywanderers/files/1424410/speed.not.updating.zip)
After a ships collides with a mountain, surface or other big object (ship etc.) speed is reduced (or the ship fases through) as expected with a collision but the speed bar in third person isn't updated.

**Comment by AfterRebelion** [comment]
This issue no longer valid in recent versions (19w23b)
