### ISSUE TITLE
[Enhancement] Enter Logic Gates Need Reverse Logic

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#271]
The current turret system seems to only allow you to build turrets on the top of ship objects. When mounted on the bottom, the controls are reversed and don't work correctly. I think this could be fixed if we could place an inversion brick between the turret control block and the rotors. This would force the rotors to turn the opposite way they normally would when controlling the turret. Here is an example turret of this configuration.

![20171028135120_1](https://user-images.githubusercontent.com/33043997/32137118-ce801e74-bbe7-11e7-96b8-dd6485887a86.jpg)

**Comment by Hanfree85** [comment]
I support this

**Comment by tsunamayo** [comment]
Yes this is something that I wanted to fix by having a turret GUI screen with various options. You will have the option to inverse axes separately - and control more than two rotators.
Thanks!

**Comment by tsunamayo** [comment]
You now can inverse axis in the rotator config screen. Thanks!
