### ISSUE TITLE
Linking the Light Indicator brick to logic will cause crash

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#272]
Ill get an image as soon as possible, but essentially the Light Indicator logic brick does NOT like having a logic link shoved up it from a State Detector (Callback??) logic brick, in my case, I have 2 logic Callbacks linked to landing gear and their hatch. I was wanting the light to show when any part of the gear assembly was in motion directly from their current state using the dynamic/checking logic bricks.

1) Place 2 sliders, no need to add anything to them
2) Place 2 Logic Callback gates, and 1 OR gate. Link 1 slider to each callback, and the Callback2 into the OR gate input
3) Place down the Light Indicator brick. Link it to one of the sliders
4) take the Output of the OR gate and link it to the Light indicator
5) create a basic circuit to move the pieces, hopefully the game will crash at this point.

Due to issues getting the game started (#118 grumble grumble) , I think this variant of the Fighter has a similar callback->Light Indicator feedback. Press "activate" manually on the left-side gear assembly sliders should do the trick and crash the game. (same side as logic panel) 

[KDI Light Fighter lagswitch variant.zip](https://github.com/tsunamayo/Skywanderers/files/1424624/KDI.Light.Fighter.lagswitch.variant.zip)
Otherwise, Pressing some of the buttons on the logic panel should cause a brief hang up when the gear assembly is being stowed.

**Comment by tsunamayo** [comment]
Thanks a lot for the blueprint! I just fixed the bug, I dont think it was really linked to the Light Indicator but more to the callback doing an instant feedback loop as I guess. Now I added a delay to the callback, so if you push the same value over it will wait a bit and dont go into a feedback in the same frame.
Thanks!
