### ISSUE TITLE
Beam Unit in hotbar does the visual firing animation in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#273]
While holding the beam unit in the hotbar (in this case slot 9) and repeatedly pressing the 9 key will "fire" the beam unit in your hand.

So far I've not seen it affect other blocks or make any sound it is just the visuals:
![2017-10-29-02-06-49](https://user-images.githubusercontent.com/211381/32139607-28c82c62-bc4e-11e7-8838-48e968645f4b.png)

Addendum: It seems to also visually fire a short beam when you've just place the Beam Unit (again this makes no sound or seems to affect anything).

**Comment by tsunamayo** [comment]
Okay issue is fixed! Thanks again ;-)
