### ISSUE TITLE
Mouse left & right click inputs malfunction upon exiting & re-entering a vehicle control stick

### ISSUE THREAD

**Issue by chunkblaster** [tsunamayo/Skywanderers#274]
Having an issue where upon I load up a creation, when I first enter the vehicle, everything works, but upon exiting and entering again, the left & right click inputs cease to function.  they are hooked to a logic system controlling weapons. The logic systems beyond the inputs for left & right click function if you manually click the inputs for them, but the left & right click buttons must be replaced to restore functionality, or re-loading the vehicle also works.

**Comment by tsunamayo** [comment]
Thanks for reporting that! Issue is now fixed. Cheers!
