### ISSUE TITLE
Turret mouse controls fail to work when entering a turret the second time in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#275]
First time entering left and right mouse button work as expected. Once you leave and enter the turret again none of the mouse buttons work.

[Bug Turret Mouse Control Failure.zip](https://github.com/tsunamayo/Skywanderers/files/1424711/Bug.Turret.Mouse.Control.Failure.zip)

![2017-10-29-02-21-05](https://user-images.githubusercontent.com/211381/32139652-db46497c-bc4f-11e7-941f-ba781b123697.png)

Related: #274

**Comment by tsunamayo** [comment]
Thanks indeed! Issue is now fixed. Cheers!
