### ISSUE TITLE
[BUG] Constructions disapears

### ISSUE THREAD

**Issue by Tisscl** [tsunamayo/Skywanderers#276]
Hello there,

I played few hours and i have build a beginning of a ship 2 days ago , today after the update, my ship is gone.
I saved my game with "f1" of course, and my ship was still visible before the update even if i shutdown and load my game.

**Comment by tsunamayo** [comment]
Okay, could you please go over 
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\PlayerEntities
and tell me if you see a file with the name you gave?
Thanks

**Comment by Tisscl** [comment]
No, any file, i did'nt named my ship

**Comment by tsunamayo** [comment]
But did you ever loaded you ship once successfully? Or did you build it the other, and then on your second build session it was not there?

**Comment by Tisscl** [comment]
Yes, in the same day i have done few build sessions and load it successfully every time i restarted the game, but since the last update no more ship

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
