### ISSUE TITLE
[BUG] Issue when creating a new character

### ISSUE THREAD

**Issue by Tisscl** [tsunamayo/Skywanderers#277]
Hello there,

When i loaded my save and saw my ship have disapear ( see #276), i wanted to create a new character, so everything is ok for the creation (name etc...) but after the loading screen , i am not on my new charcater but on the old one(with the old char name) in the old save.

**Comment by tsunamayo** [comment]
Okay I am not 100% if you are talking about the character and/or the player appearance. Where did you spawned after having created the new character? Thanks

**Comment by Tisscl** [comment]
I'm talking about character name, i spawned at the usual spawn point but with the previous character name and in the other character game

**Comment by tsunamayo** [comment]
How do you check your character name in game? Also, worlds are shared between every character, that is why I am saying create a new character and not create a new world unlike Minecraft. Thanks
