### ISSUE TITLE
Swapping hotbars

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#278]
When using shift+scroll to switch between hotbars, it does not go in order, it often choose a random hotbar to switch to when you shit+scroll instead of the next or previous.

**Comment by Breezebuilder** [comment]
Not having this bug.  Have you tried using a different mouse?

**Comment by tsunamayo** [comment]
Hi Tom, thanks for booking a case ;-) 👍 
Not sure about that one, I think what is confusing is the fact that from the 4th and the 1st you get a big jump in another direction (as you are looping)
Also it might go too fast, I might add something that wait for you to actually be on the new hotbar before switching.
Thanks

**Comment by AfterRebelion** [comment]
This is no longer an issue in recent versions (19w23b)
