### ISSUE TITLE
[Bug] Stuck in Blueprint Menu

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#280]
Sometimes when attempting to paste a child entity using an identity block, I'll become stuck in the BP menu. Selections and buttons will light up, but nothing will actually work. Attempting to close the menu via the Escape key will only dismiss the menu for a brief moment before it reappears. Saving still works, so I've done that before using Alt-F4 to restart the game.

**Comment by talrey** [comment]
Forgot to mention, when I reloaded the game all of the blueprint names were messed up - whatever name I'd given them was gone, and replaced with the coordinates (I think? It was a set of 3) of the blueprint - the default name. Renaming these blueprints worked as expected.

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
