### ISSUE TITLE
[Possible Regression] Deleting Child Entity Blueprints deletes parent hinge

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#281]
As per title. This is especially noticeable on mirrored builds, where using the blueprint menu to copy and paste child entities is a common workaround to child entities not being mirrored with the parent.

**Comment by tsunamayo** [comment]
Hi! So this is by design, once you remove a child entity it will remove the hinge/rotator, as this block is no longer useful. Thanks!
