### ISSUE TITLE
Hot key loss of connection.

### ISSUE THREAD

**Issue by Susslord** [tsunamayo/Skywanderers#283]
I've link a "hot key" to a missile launcher that is riding on a hinge and a rail system. When I first apply the "hot key" the missile launcher shoots when the key is pressed, but when I activate the mechanical parts the "hot key" stops working.

[I've tried all the weapons, and "hot keys", coming to the same result.]

I believe this is happening because of the weapons position updating, the "hot key" is almost getting desynked after the first movement of the weapon.

[Buttons, switches, etc... are not effected by this glitch, only "hot keys"]

**Comment by Susslord** [comment]
I forgot to mention

**Comment by CyaNox** [comment]
This seems related to #274 and #275 so this might be fixed in the next build however you are describing a slightly different situation.

**Comment by Susslord** [comment]
Those sound like they're being caused by the same issue, after the mechanical bits update the the "hot keys" stop working. They're just using turrets instead of fixed sliding guns.

**Comment by tsunamayo** [comment]
I think it should be fixed in next update. Please re-open then when it is delivered. Thanks!
