### ISSUE TITLE
Cannot Place Rotating Brick.

### ISSUE THREAD

**Issue by ComradeJenkens** [tsunamayo/Skywanderers#285]
I am unable to place the rotator brick on studs at all. Tried several orientations, and even relogged all were no help. The placement node itself is showing.

Tried on blocks to check as well and that doesn't work either.

**Comment by tsunamayo** [comment]
I tried and I cant reproduce. On what bricks / block did you tried to place it? I did a few fixes recently. What is the version you used? Thanks

**Comment by tsunamayo** [comment]
Okay I guess this issues was fixed, please re-open a case otherwise! Cheers
