### ISSUE TITLE
Black screen after game boot up when changing from windowed to Fullscreen mode

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#286]
As titles, I somehow get better success booting the game at 600x resolution, but if it loads in Windowed mode, changing to 1360x fullscreen causes a black screen and just the mouse pointer to be there. Requiring a game reboot and then struggle to get back in to play. 17w43a

**Comment by tsunamayo** [comment]
Thanks, yes it seems that change to fullscreen cause a black screen, I will force the game to restart for this setting. It seems to be a Unity regression, as I was not having that sometime ago. Thanks!

**Comment by tsunamayo** [comment]
This issues was finally fixed. Thanks!
