### ISSUE TITLE
Entering Pilot seat (cushion brick) can sometimes cause spinning

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#288]
![image](https://user-images.githubusercontent.com/33023316/32146276-8fe52bd8-bccc-11e7-84d2-f942e676d9fb.png)

After testing the bed alignment a few times, I dont this is how you sleep...

Was using Q+Q to re-align with the ship after "sleeping", alignment has a few bugs like taking a very circular route to align the character, and sometimes aligning them incorrectly

**Comment by tsunamayo** [comment]
Okay just to be clear, you spin while you are seated? I fixed a bug a few days ago on that, on what version are you?

Alignment to ship is wonky for sure, I will improve it (as the command, I will move it to the MMB quick action wheel)

Thanks!

**Comment by Napther** [comment]
this was on 17w43a. And yeah, spinning while seated. My GFX pretty much is maxed so attempting to run a .gif or a video in the background might not be possible for now. But it was a pretty obvious circular, orbiting motion as opposed to a flat spinning on the spot.

Similar to the process of getting into a seat not in your default alignment, but the camera never finding the proper resting point 1/2 way through

**Comment by tsunamayo** [comment]
Hum, I fixed this bug the other day, it should be fine in 17w43a... Could you please zip me your blueprint if this is something you reproduce often? Thanks

**Comment by AfterRebelion** [comment]
Since cushions are no longer avaliable, this issue is no longer valid in recent versions (19w23b)
