### ISSUE TITLE
Can't use buttons through collision boxes (despite being hollow)

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#289]
Most notably the Canopy Long Wedge has a large hitbox underneath it as it comes with 2 sides as standard. An easy fix for this common case would be to add a canopy wedge Long that is only the sloping face with appropriate rescaled collision box, rather than making the hitbox of it change based on if it has Long Tetras adjacent to it.

![image](https://user-images.githubusercontent.com/33023316/32146664-bf8a29be-bcd2-11e7-93c2-51335a2e3b73.png)
![image](https://user-images.githubusercontent.com/33023316/32146679-f3ebe832-bcd2-11e7-8b52-ea65cbd5c304.png)
![image](https://user-images.githubusercontent.com/33023316/32146682-f9868a54-bcd2-11e7-9b6d-e3976bfe78fb.png)

**Comment by tsunamayo** [comment]
Thanks! Yes indeed that is a crappy thing linked to canopy. I did a a change that fix 90% of the problem though, situation will be much better albeit not perfect. 

I might add a wedge canopy alone + separate side, but if I do this, I would need two sides block as the 2x1 is not symmetrical... Or I can make it in brick. Anyway canopy seems not that much. but it is one of the hardest think to design, I have redone it 4 time and I am still not satisfied with it.
I am also considering much radical solutions (free form shape). 

Will mark it closed for now, to see if it is enough for now or not.
