### ISSUE TITLE
[BUG][MAYBE] seat cushion brick misaligned

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Skywanderers#290]
The seat cushion (the one with the headrest) is aligned so that the cushion clips into the base of the pilot seat and leaves two empty brick spaces in the top corners of the pilot seat.

**Comment by Napther** [comment]
this is semi-intentional as that is actually an entirely new seat unto itself (a standing one for mechs)

You may create a headrest from bricks and some inventiveness, and the normal cushions

**Comment by tsunamayo** [comment]
Yes this brick might confusing. I think it would be better to have a standing seat, and let people use a cushion... But I am not really sure. I want to have "saddle" seat also, for hover bike. So it might refactored at some point to get a cohesive approach.

**Comment by AfterRebelion** [comment]
Seat cushion is no longer avaliable, so this is no longer an issue in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Thanks for the clean-up @AfterRebelion , I saw you were on killing spree ^^. I will close all these case. Thanks!
