### ISSUE TITLE
Painting with Mirror Mode will duplicate blocks onto other plane

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#292]
![image](https://user-images.githubusercontent.com/33023316/32148585-3063a200-bcf1-11e7-98ec-ca7834112395.png)

![image](https://user-images.githubusercontent.com/33023316/32148620-b4ddb494-bcf1-11e7-9a20-de73f96754f7.png)

**Comment by Ar-Gent** [comment]
Ironic, look at the issue below this one :)

**Comment by Napther** [comment]
I made this one of the back of another, didnt get to see the list at all...

**Comment by Ar-Gent** [comment]
Closed my issue since yours is more demonstrative. :)

**Comment by tsunamayo** [comment]
Hah yes, this issue is back... Will fix it asap, it is derp indeed. Thanks

**Comment by tsunamayo** [comment]
Okay guys, lets say you paint a block with mirror on, on there is other side there is already a block that is different than the one you painted on. You want on this block or not?

**Comment by CyaNox** [comment]
I'd say only if that block is the same as the one on the mirrored side else it might be unexpected.

**Comment by tsunamayo** [comment]
Okay this is the behaviour I coded. It is fixed now, thanks!
