### ISSUE TITLE
Beam weapons are not doing any damage in 17w43a

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#294]
Firing a beam weapon at a block does not do any damage in 17w43a, but other weapon types are working properly.

**Comment by Mellcor** [comment]
yea this is known, the beam gun dose damage but you can not converge those lazers where as the beam block dosnt do damage but can converge

**Comment by tsunamayo** [comment]
Yes I somehow remove damage for the beam, as it was too powerfull. Anyway weapon will get a complete overhaul - so I will mark it as closed until I redo them. Thanks!
