### ISSUE TITLE
Main Menu and Blocks Codex not capturing inputs in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#296]
While controlling a turret or a craft you can open the main menu and blocks codex (which is fine) however many of the keys that should be captured by these user interfaces are not.

For instance in a turret any keys bound using the hotkey links or mouse button links will still activate even when you are in the main menu or the blocks codex.

Similarly while controlling a craft and you have opened the main menu or the blocks codex various controls are still active. This is particularly annoying when you are in `STD` mode and you start moving forward while navigating the menu.

For the turret this also affects just the mouse movements.

**Comment by tsunamayo** [comment]
Okay thanks indeed. Btw I wont allow codex opening when in turret - but menu was requested and I agree with that. Thanks again!

**Comment by tsunamayo** [comment]
Okay I fixed this one. Dont hesitate to book another one if I forgot an interface. Cheers
Francois
