### ISSUE TITLE
Scroll wheel in Blocks Codex unexpected behavior in 17w43a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#297]
The scroll wheel always switches which hotbar you are on and does not scroll the main codex page no matter where your cursor is.

In the screenshot below I even have the cursor over the side scroll bar and it still switches the hotbar.

![2017-10-30-08-29-19](https://user-images.githubusercontent.com/211381/32159278-1c3039b8-bd4d-11e7-8f87-4492ebb6e243.png)

The scrolling of the hotbar should be kept consistent in or outside of the blocks codex so `SHIFT + SCROLL` should change it not just `SCROLL`.

**Comment by tsunamayo** [comment]
Yes I agree with that. Thanks!

**Comment by tsunamayo** [comment]
Okay it is fixed, now the scroll wheel is controlling the view. Cheers
