### ISSUE TITLE
Hotkey buttons fail after leaving flight seat

### ISSUE THREAD

**Issue by Gov55** [tsunamayo/Skywanderers#298]
when I get out of a ship and re-enter  the flight seat hotkey inputs stop working. I have created BP and deleted world re-imported BP and problem still exists. I have done file verification in steam, same issue. I removed game via steam, rebooted computer, re-installed game used starter ships problem still exists with out importing my BP.

**Comment by CyaNox** [comment]
This is most likely related to #274 and #275 and is probably already fixed in the next build.

**Comment by tsunamayo** [comment]
Yes this issue should be fixed in the next update! Thanks!
