### ISSUE TITLE
Dual Enter Gate breaks Hotkey Links

### ISSUE THREAD

**Issue by AlexJHockley** [tsunamayo/Skywanderers#299]
This may be a hard one to explain, so bear with me. I was making a turret that sequence fires laser units. I linked my "hotkey 1" to a Dual Link Gate to start the fire sequence. I then linked this Hotkey 1 to a Dual Enter Gate, along with a link to the turret control block. 

When using a dual link gate in this way, the Hotkey will not work. Moreover, AFTER linking the Hotkey block with a Dual Enter Gate, the Hotkey block will not work when you enter it individually. That is to say, prior to Dual Enter Gate connection, you can press "F" to enter the Hotkey block and it will function, but AFTER linking, this does not work, even though the logic still appears to be connecting the Hotkey Block to the Dual Link Gate I was using for sequencing.

After removing the Dual Enter Gate and replacing it with a Quad Enter Gate to do the same function, I was able to use the turret and hotkey as planned.

If you want me to cover this in better wording I am happy to, given that my explanation may not have been great.

**Comment by AlexJHockley** [comment]
(Update) Just noticed that I am now having this issue with quad link gates as well. I may be cursed.

**Comment by tsunamayo** [comment]
I think this is a duplicate issue of an issue that was fixed. Could you check it in the next build? Issue was you cannot enter hotkey a second time. Thanks!

**Comment by AlexJHockley** [comment]
I can definitely do that, I'll post back here when I test it on the next build!

**Comment by AlexJHockley** [comment]
Sorry for the late reply, but I just tested the ship I was having this issue on and it is solved now, no problems at all.
