### ISSUE TITLE
Sliding Block Doesn't Undo Creation Correctly

### ISSUE THREAD

**Issue by timgauthier** [tsunamayo/Skywanderers#3]
If you place a slider and then hit undo (ctrl+z) it removes the base, but not the part that slides, and you can't remove this piece in any way either.

**Comment by IronicMollusk** [comment]
I've gotten this bug if i build some blocks on a slider, and then delete the slider track. the blocks that were previously on the slider cant be deleted. i feel its part of the same issue, but i was able to reproduce it without the use of ctrl+Z.

**Comment by tsunamayo** [comment]
Actually fixed.
