### ISSUE TITLE
[BUG] Building on the ring-world

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Skywanderers#300]
When trying to build a structure on the ring-world I found that extended too far in a direction would cross some border that would split my build.
I tried building across this border using symmetry and my fps dropped to 1 from 30, the blocks I placed were also not rendering and I couldn't destroy them

**Comment by tsunamayo** [comment]
Hum yes symmetry wont work on Torus for now. You just fund the limit of a Torus chunk (64x64). Could you send me your output_log? Thanks.

**Comment by alxnns1** [comment]
As soon as i get to my computer i will get that to you

**Comment by Harlekin13** [comment]
that seems to be the reason for a issue i had. wanted to build a space elevator starting on Torus, used the strg+RMB command to build, tried to overcome the limit by using it again, building messed up, used shift+LMB to delete, now there are blocks, which are no blocks, floating in the air, that i cannot delete nor use.

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
