### ISSUE TITLE
Hose connection visibility culling incorrect

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#301]
The hose connection visibility check is only being done on one side of the connection. The screenshots below demonstrate that only the left hose connector is doing the "should the hose connection be rendered" logic:

Right connector not visible but connection renders fine:
![2017-10-30-11-20-58](https://user-images.githubusercontent.com/211381/32165934-9bbb2960-bd64-11e7-86e9-4d2312bef79e.png)
Both connectors visible:
![2017-10-30-11-21-02](https://user-images.githubusercontent.com/211381/32165937-9e3465d0-bd64-11e7-980c-4f429293e93e.png)
Left connector just offscreen and hose connection stopped rendering:
![2017-10-30-11-21-08](https://user-images.githubusercontent.com/211381/32165938-9f763f40-bd64-11e7-9266-c911af87cf08.png)

**Comment by Hanfree85** [comment]
I reproduce it 
Here i connect the 3 styles of hoses from left to right (place of hoses are indiferent only when you connect is when you can see that
If i look to the left the hoses connections banish
but if i look to the right the hoses connections stay there
![20171030124757_1](https://user-images.githubusercontent.com/33139962/32169478-edbe627a-bd70-11e7-9207-68e03dbd0335.jpg)
![20171030124808_1](https://user-images.githubusercontent.com/33139962/32169481-f227b94c-bd70-11e7-938c-f7172aa09854.jpg)
![20171030124812_1](https://user-images.githubusercontent.com/33139962/32169488-fae1e9fe-bd70-11e7-8600-65701b9a2d72.jpg)
![20171030124817_1](https://user-images.githubusercontent.com/33139962/32169498-07662af0-bd71-11e7-8f8a-158b91c31ec0.jpg)
![20171030124852_1](https://user-images.githubusercontent.com/33139962/32169621-a453ba1c-bd71-11e7-9a91-f05bd925105e.jpg)
![20171030124855_1](https://user-images.githubusercontent.com/33139962/32169629-aa04926a-bd71-11e7-803f-f13b0caf9f3b.jpg)
![20171030124901_1](https://user-images.githubusercontent.com/33139962/32169649-bd988804-bd71-11e7-8acc-c37e5662f084.jpg)


Now i connect this hoses from right to left 
If i look to the left the hoses connections stay there
but if i look to the right the hoses connections banish

![20171030124930_1](https://user-images.githubusercontent.com/33139962/32169658-c55073ae-bd71-11e7-9a7c-010ce3fc8c04.jpg)
![20171030124933_1](https://user-images.githubusercontent.com/33139962/32169679-d2bd8d88-bd71-11e7-97f3-1df14529f660.jpg)

**Comment by tsunamayo** [comment]
Thanks for all the screenshot guys! Yes I know this issue and I know why it happens, but I might just redo the way those are rendered actually - to make them for efficient. So it is gonna be broken like for a bit of time unfortunately. Thanks!

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
