### ISSUE TITLE
It is possible to go out of bounds with the Slider Control

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#302]
It is possible to go above 1 or below 0 using the slider. This seems to always happen but on my first attempt to create a quick and easy blueprint it happened so I suspect it is not that hard to reproduce.

1. Essentially I placed all the blocks first
2. Connected the Slider Control to the hinge
3. Pulled the slider down
4. And this resulted in exactly this:
![2017-10-30-12-29-56](https://user-images.githubusercontent.com/211381/32168896-8dc216c0-bd6e-11e7-823d-1af487aa7fa3.png)

[Bug Over Extended Slider.zip](https://github.com/tsunamayo/Skywanderers/files/1427003/Bug.Over.Extended.Slider.zip)

**Comment by tsunamayo** [comment]
Thanks! Issue was fixed. Cheers
