### ISSUE TITLE
[BUG] Brick hinge works in tens of degrees, not degrees

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#304]
When connected to a mix/constant command, the 1x1 brick hinge accepts values up to 9, rather than 90 degrees. It seems to work in tens of degrees, so if you input 5 degrees into the command logic, the hinge will turn to 50 degrees rather than the 5 that is specified.

**Comment by tsunamayo** [comment]
Hah indeed nice catch! It is fixed now, thanks! Cheers
