### ISSUE TITLE
Booting game in low-res causes menu elements to appear off screen

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#307]
![image](https://user-images.githubusercontent.com/33023316/32186546-44ddd77e-bd9a-11e7-92c1-904fe51e49e9.png)

I think the image says most of that, 640x480. Then again, i never lived with an ancient monitor where this is its native resolution (mine is 1360x740 ish) where it might appear perfectly fine.

**Comment by tsunamayo** [comment]
You are right, I should specify that the game require a minimum resolution. I force a minimum resolution inside the game, for outside it will have to wait when I get rid on the launcher entirely (need to work on control first). Thanks!
