### ISSUE TITLE
Circular Thruster texture merge non-sensical

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#308]
![image](https://user-images.githubusercontent.com/33023316/32194239-ba1616a2-bdb1-11e7-9840-8f9d6e0f31ac.png)

I have no clue what its "trying" to do here. There is indeed a hole down the middle, the blocks havent merged in that regard.
![image](https://user-images.githubusercontent.com/33023316/32194299-e1caa438-bdb1-11e7-990a-0b4a5199975f.png)
and looks even odd-er with mixed circle and square thrust.

Now that I think of it, those block thrusters are kinda big and bulky for the look I am after but thats personal preference. Be amazing for decorative brick thrusters that give that bloom effect... On second thought I think some child entity trickery will get me what I want in this build. Hope systems will chain down like that in future.

**Comment by Ar-Gent** [comment]
I use this quite a bit in my builds to add a unique look to my thrusters. Though I agree they should be adjusted so it doesn't look so odd.
![20171030181413_1](https://user-images.githubusercontent.com/33102709/32198363-345ffd4c-bd9e-11e7-94d4-f3b9b9b936fb.jpg)

**Comment by tsunamayo** [comment]
Yes this issue was actually fixed yesterday. A new build is coming is soon. Thanks a lot!
