### ISSUE TITLE
Bricks interfere with Cone Hollow placement 14w42a

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#309]
![image](https://user-images.githubusercontent.com/33023316/32196143-990bc5be-bdb7-11e7-90e3-76e39b05d370.png)

![image](https://user-images.githubusercontent.com/33023316/32196294-11e66782-bdb8-11e7-9f24-7b621a8b6b07.png)

![image](https://user-images.githubusercontent.com/33023316/32196308-1bf42ce6-bdb8-11e7-94a0-5dae16ed4f76.png)

Actions taken sequentially. Place brick grid, then place down any brick in the middle prefereably.
Try to place down Cone Hollow block on the same block and centred on the brick
releasing the build action will not place the Cone.
Pressing Undo will delete the brick, CTRL+Y will place down the cone, but not the brick. Trying to place a brick down in the centre of the placed cone now will yield a failed place, but undo/redo will swap the cone out for the brick.

A little confusing but hope the image helps

**Comment by tsunamayo** [comment]
Hum yes indeed, the reason is that the cone is trying to occupy the same stud as the little brick. This is a legitimate use case for this partical brick (as it is hollow), so I will find a workaround. It might mess up with all existing cone in all current blueprints though...

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
