### ISSUE TITLE
Two light rods? [17w43a] 

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#310]
![20171030180854_1](https://user-images.githubusercontent.com/33102709/32198196-819e1be4-bd9d-11e7-9c0f-288688eaa820.jpg)
![20171030180855_1](https://user-images.githubusercontent.com/33102709/32198197-81c9a278-bd9d-11e7-8b29-415021320c7e.jpg)

**Comment by Napther** [comment]
I noticed that a while ago, but assumed that it was already kinda known due to how obvious it was (since what do you name that block anyway, its like a half-wedge thing)

**Comment by Ar-Gent** [comment]
I've looked for such a issue, but it never popped up in Git. Guess a lot people didn't notice it?

**Comment by tsunamayo** [comment]
Okay I changed it indeed! No problem if you spot something like that for you to book an issue, up until recently name where not as visible as they are today. Thanks!
