### ISSUE TITLE
Invisible Bricks 17W43A

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#312]
I am not sure why it is happening but all I know for sure is anything that uses the stud system (bricks, logic etc.) has turned invisible in a section of my WIP ship. I have tried reloading the game, reloading the ship from a blueprint, and it still comes back as having the same area of bricks being invisible.
![20171031121016_1](https://user-images.githubusercontent.com/33239800/32202967-81ef14b2-be34-11e7-9e8a-a83ca7c45254.jpg)
As you should be able to see, I have a guided missile arrangement on my ship. And it was complete, but now it is missing a section of bricks. The bricks are still there, but are invisible. 
Just underneath the surface of the ship I have the logic setup for the bricks. 
![20171031121005_1](https://user-images.githubusercontent.com/33239800/32202994-ae8db230-be34-11e7-8c56-ab01450cb34f.jpg)
It was a wall of substantial logic, and now it is all invisible. If i flick the switches (the little lights visible) then the logic still works. Its just invisible. 

![20171031121303_1](https://user-images.githubusercontent.com/33239800/32203032-de38d53c-be34-11e7-885b-839865f910f5.jpg)

In this picture I am looking at a pipe arrangement I made. Its still there, just invisible. 

System specs - 
i7 7700K 
Geforce GTX 980Ti
32GB Ram
1TB SSD.

If anymore info is needed, please let me know. :)

**Comment by tsunamayo** [comment]
Hi, you just hit the bricks limit I guess. Once you start to pop a lot of bricks on a ship it will bug like that. I didnt fixed this bug yet simply because I will do a big refactoring regarding the rendering of bricks, and it will be fixed naturally. Thanks!

**Comment by Sullos** [comment]
Ah okay. Good to know. Do you know when we might be able to see this change take effect? This ship is my big project currently, and I just love working on it all the time :) 
That's all. Thanks

**Comment by Sullos** [comment]
Update: I tried removing houses from the ship, as I recalled placing houses down at the time of the disappearing bricks. And by simply removing some of the hoses, and reloading the world, the problem was fixed. Not sure if it was a high amount of hoses in an area, or some other issue. But it now seems hose related?

**Comment by tsunamayo** [comment]
Hum not sure, but I still think it is 99% the brick limit bug. Will keep you posted when it will live, but most likely in about a month...

**Comment by tsunamayo** [comment]
Okay I am closing this issue as the fix is on the roadmap. Thanks!
