### ISSUE TITLE
re-non logical placement of blocks ect (#253)

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#313]
if your reply you gave the reason of why the block placement is how it is in regards to the click and drag system 

> it is like that because you always want the slope to face you, and it is much easier to hit the closest quadrant of the surface that is near to you

which is fine, however there are some cases in witch i beleive the blocks do not follow this, i have been going on the premise that the thinnest/smallest edge/side should face towards the direction you drag

the first frame in each pic is how it is currently, the second is how i believe it should be in order to provide a consistent user interface

![cube2a](https://user-images.githubusercontent.com/33142373/32208167-a2054c2c-be65-11e7-8f40-7cdb905bc468.jpg)
![cube5b](https://user-images.githubusercontent.com/33142373/32208169-a38db5de-be65-11e7-8e6e-5fef0a110cf5.jpg)
![cube4b](https://user-images.githubusercontent.com/33142373/32208170-a4d8f21e-be65-11e7-84e2-732c9d20d346.jpg)
![cube1](https://user-images.githubusercontent.com/33142373/32208172-a6567d3c-be65-11e7-87ed-c244a966bc0a.jpg)

**please note there are more shapes that similar to these that would benifit from the same change, these are just the shapes i belive best show what i am trying to say**

**Comment by tsunamayo** [comment]
Yes, the reason corner shape are like that is that very often you want to build a tetra in a corner. Having it this way make it possible to hit whatever of the three facing plane you want.  Also very often there is just void, so you cant hit the surface: just look at your first example (Tetra block), if you place it on top of a tri, you wouldnt be able to do it with your method (or you would have to place it backward first, and then rotate your cursor around - painful)
It seems illogical but I can tell you it is the best and fastest way to do it. You have to think of not only the block itself but how it fit with adjacent blocks. 
That being said a few block are misaligned by 180 deg, like seats for example. Thanks
