### ISSUE TITLE
Bricks not placing

### ISSUE THREAD

**Issue by Nero-Akavar** [tsunamayo/Skywanderers#314]
Right after updating the game today I began building on my ship again with bricks only every so often I would try to place a brick on a transparent 4x4 panel and it would not place. I tried deleting it and replacing and still no good. I restarted the game and it was ok for a moment but soon there after it happened again and would not let me place bricks.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1429658/output_log.txt)

**Comment by talrey** [comment]
Can confirm this is happening to me as well. It only happens with the `Flat Panel` type as opposed to the normal (visible) Panel type.

**Comment by tsunamayo** [comment]
Hum I cant reproduce this issue. Could you please send me a screenshot of when that happen, or send a blueprint. Is it random or does it appears all the time for a given location? Thanks!

**Comment by tsunamayo** [comment]
Okay never mind I just managed to reproduce, it seems a bit random, let me check this out! Thanks

**Comment by JRL101** [comment]
Confirmed. 
Details:
New Z fighting on studs hologram.
CAN place bricks on side of studs.
CAN place bricks on studs pre-existing on the underside of blocks.
NO placement ontop of the studs box.
SOME placement on old studs facing upwards.
Studs on the inside of the plate, and inaccessible. 
Looks almost like multiples are being placed.

![20171031203123_1](https://user-images.githubusercontent.com/33255536/32224295-d25d7852-be7b-11e7-9dcf-2a5e5f7da6f1.jpg)
![20171031202626_1](https://user-images.githubusercontent.com/33255536/32224304-da2fc4e0-be7b-11e7-9666-1af8b11af69b.jpg)

Possibly "Z fighting" is related?
![20171031202410_1](https://user-images.githubusercontent.com/33255536/32224380-26dcc9fa-be7c-11e7-9351-efdf5b7bdd04.jpg)
![20171031202412_3](https://user-images.githubusercontent.com/33255536/32224399-30707be2-be7c-11e7-913f-e28069eef17f.jpg)

Example of stud Z fighting.
![image](https://user-images.githubusercontent.com/33255536/32224414-467842bc-be7c-11e7-8e6d-6b3dc48d99d0.png)

**Comment by JRL101** [comment]
Noticed small rails having a slight Z fight too, so checked the underside of big rails. 
![image](https://user-images.githubusercontent.com/33255536/32224558-e9101568-be7c-11e7-8121-3fe68a7b9dcd.png)
Quite vigorous. can confirm this wasn't happening before the new update.

**Comment by JRL101** [comment]
Update: more testing confirms its mostly to do with the full block grid. 2/4 studs seems to be fine.

**Comment by tsunamayo** [comment]
Issue was fixed! Thanks for your help! Cheers
