### ISSUE TITLE
unable to place logic on studs

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#315]
building a ship out of full cubes, it has zero micro blocks on it, added some hinges for the engines and was going to set them at a 45degree angle but it wouldnt let me place the logic
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1429766/output_log.txt)
![ship](https://user-images.githubusercontent.com/33142373/32210707-15a3a6f2-be74-11e7-8f66-f420a7d28b65.jpg)

sent u the ship i was trying to build on via PM as i cant upload it here
also this is in 17w44a

**Comment by Mellcor** [comment]
upon restart no change to situation

**Comment by CyaNox** [comment]
This may be related to #314.

**Comment by JRL101** [comment]
17w 44a
Side placement possible
![image](https://user-images.githubusercontent.com/33255536/32224670-66aa7e50-be7d-11e7-9897-edfb606ffc58.png)

Underside placement possible
![image](https://user-images.githubusercontent.com/33255536/32224694-77ee4aac-be7d-11e7-9b1b-da66baae640e.png)

Z fighting on studs on any side except underneath (might be related but is present on new and old rails and logic.)
![image](https://user-images.githubusercontent.com/33255536/32224728-91d81880-be7d-11e7-9b61-c3d55bed7ff6.png)

**Comment by JRL101** [comment]
Different restarts does not cause a temporary fix.
All studs act the same.

**Comment by tsunamayo** [comment]
Okay thanks for reporting this guys! Issue is now fixed! Cheers
