### ISSUE TITLE
The tween gate (Suggestion)

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#316]
While playing around with the various blocks and bricks that provide motion to the game I found myself to be slightly disappointed in all the linear motions.

This here is a suggestion to add a new gate that allows us to create motions depicted below:
![tween-graphs](https://user-images.githubusercontent.com/211381/32208824-539fd9e0-be05-11e7-8cf1-d9e00b887d0a.png)

Pretty much any door mechanic that I've seen so far would benefit greatly from being affected by for instance the Quadratic InOut tween, making it speed up and slow down its motion instead of just linearly sliding open.

I also can't wait to see what people would do with the more _fun_ tweens like Elastic and Bounce.

In the image below I'm imagining a simple setup using just a button, the tween gate and a sliding door:
![2017-10-31-06-30-38](https://user-images.githubusercontent.com/211381/32209037-7fa88d74-be06-11e7-9363-803600737a2a.png)
(Note: I'm using the delay gate as an example)

The UI could be something along the lines of:
![sw_tween_window_mockup](https://user-images.githubusercontent.com/211381/32210755-b564eb20-be0f-11e7-894d-1a28e339e209.png)

In addition if a "Linear" option is also added this can also be used to adjust the speed of the motions of hinges and rotors.

Here is a library from the unity wiki that has pretty much all the mentioned and depicted tweening in there already: http://wiki.unity3d.com/index.php?title=Tween

**Comment by tsunamayo** [comment]
Hum actually gates are only pushing values as a pulse (single frame), they are not doing any interpolation. It is the system behind that is moving toward the target value. I could indeed add something a bit more sexy than a lerp movement, but that would dependent on context. Thanks

**Comment by tsunamayo** [comment]
Not really possible with the current tech. Tx
