### ISSUE TITLE
GPU Crash during navigation of the Galaxy Map

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#318]
While playing around and figuring out the control of the galaxy map I managed to crash my GPU. It happened at the 3rd zoom level (the one before the final zoom level). 

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1430417/output_log.txt)

This issue is probably related to #126 with the exception that I was not clicking rapidly in fact I was taking things real slow so I could identify when it happened.

**Comment by tsunamayo** [comment]
Okay I know galaxy map is a bit fidly, I have a huge refactoring of it on the roadmap to adress all that - so I will most certainly only look at this when I will do that. Thanks.

**Comment by tsunamayo** [comment]
Deprecated for now. Thanks
