### ISSUE TITLE
Base Joint disappearing when saving

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#321]
When using a `Base Joint` alone as a decorative element, it sometimes disappear when saving (F1).

In case it had an impact, said Base Joints were set as child entities on a slider.

**Comment by tsunamayo** [comment]
Hello, so you mean it disappeared during the saving process, or after reloading? Thanks

**Comment by tsunamayo** [comment]
The bug should have been fixed! Thanks for reporting that. Cheers!

**Comment by Name11ess** [comment]
During the saving process. Thank you!
