### ISSUE TITLE
[REQUEST] Windowed mode: resizable window

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#322]
The ability to resize the game viewing area in windowed mode would be appreciated, thank you.

**Comment by CyaNox** [comment]
I kinda already do resize my window but using external means and I have yet to see any issue happen so in theory this should be relatively easy to implement and should not incur any negative effects.

**Comment by Nexusdog** [comment]
It would be helpful, at least for people like me who have several windows open - I have a video chat window open with my gf who's in another country, so being able to have both scaled onscreen would be appreciated.

**Comment by tsunamayo** [comment]
By resize you mean change the resolution of the game to match your window? What other 3D game is doing that ? I dont think it is standard nor possible with Unity. Why are you not changing the resolution of the game to get a different windows size?

**Comment by CyaNox** [comment]
Resize as in change the viewports resolution yes.

I'm using Autohotkey to resize my window to a specific size and position on my screen. I'm doing this for pretty much all games I play however this approach is somewhat advanced and not readily available for other people.

Here are just a few reason why one would want to change their resolution to something other than the launcher or the ingame resolution settings allow:
- Streaming; Most streamers have a very specific setup where they want the chat to be close to the game in which case they want to be able to resize the window to fit a specific resolution that isn't provided as a standard resolution.
- Non 16:9 displays when people still want to play 16:9 but windowed mode resolutions don't show full width windows. Example: on a 1280x1024 screen the highest windowed resolution in the launcher is: 1024x768 even though 1280 width is possible (and in fact works fine (see my many screenshots)).
- People with just one monitor that want to be able to multi task (watch videos, have chats open, etc) might want a custom resolution to put all their windows in specific places.

As to how possible it is in Unity I'll let the documentation speak for itself: https://docs.unity3d.com/ScriptReference/PlayerSettings-resizableWindow.html

**Comment by tsunamayo** [comment]
Okay I will activate this setting for the next build, it cost nothing to give it a shot. After a few test it seems that there is different behavior on the UI side and 3D side, but so far it was not that bad. Cheers

**Comment by Nexusdog** [comment]
Much appreciated, thank you.

**Comment by AfterRebelion** [comment]
You can freely change windows size, so this issue is no longer valid in recent versions (19w23b)
