### ISSUE TITLE
[BUG] Arrow keys hard coded to direction

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#323]
Unable to remap arrow keys to perform other functions, despite confirmation in editing menu

**Comment by tsunamayo** [comment]
Hi! I had no trouble to remap them. What is your exact test case? (is editing menu the Key Mapping menu?) Thanks

**Comment by Mellcor** [comment]
attempted to reproduce this also unable HOWEVER, i bound WSAD movement to the arrow keys yet even after binding WSAD still worked as movement as well as the arrows

**Comment by tsunamayo** [comment]
Yes it is because those are binded inside the launcher. It is something that is a bit crappy with Unity since forever but nothing blocking, I will remove the launcher altogether soon. Thanks

**Comment by JRL101** [comment]
Also can not reproduce. 
Key Mapping seems to function correctly.
Are we talking about remapping WASD to the arrow keys? or Mapping the Arrow keys specifically.
OR are you talking about the D-pad of a controller?

**Comment by tsunamayo** [comment]
Hi, so finally the launcher will be removed from next build on. Now all control will have to be assigned inside the game - so there will be no confusion. Thanks
