### ISSUE TITLE
Stuck in Blueprint Identity Menu when using child entities

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#325]
![image](https://user-images.githubusercontent.com/33023316/32240201-9ac36396-be64-11e7-81d7-f99fbbc76a74.png)

just Before this point, an Entity called "spaceship one" appears as the only item on this list. This is not a blueprint I have made at all. Always occurs after at least 1 use of Child Entity saving of BP and then cloning it onto a free rail/hinge

**Comment by tsunamayo** [comment]
This is no longer applicable. Thanks
