### ISSUE TITLE
Unable to use hotkey and left mouse link (17w43a)

### ISSUE THREAD

**Issue by PeterTheHacker** [tsunamayo/Skywanderers#327]
A hotkey/left mouse button link (on a turret for example) will work, but only until you stop co trolling and takr control again. At that point clicking/pressing the hotkey will have NO effect at all.

**Comment by tsunamayo** [comment]
Hello, on what build are you? This issue was fixed recently (it is now fine on my side). Thanks!

**Comment by PeterTheHacker** [comment]
My bad; I didn't update. Thanks for fixing things so quickly!
