### ISSUE TITLE
Mouse wheel cycles through toolbar items when placing stud blocks [17w44a]

### ISSUE THREAD

**Issue by Gadget100** [tsunamayo/Skywanderers#328]
The new behaviour, whereby the mouse wheel changes the rotation plane of a non-stud block works well.

However, if you're placing (i.e. holding RMB) a stud block - whose rotation plane cannot be changed - and spin the mouse wheel, this moves to the next item on the toolbar. I'd expect the mouse wheel to either do nothing, or do something related to the block being placed.

Also, if you end up selecting a non-stud block, the mouse wheel will then switch to changing its rotation plane as you'd expect.

**Comment by tsunamayo** [comment]
Thanks indeed! It is now fixed. Cheers!
