### ISSUE TITLE
Almost impossible to select stars on the holomap [17w44a]

### ISSUE THREAD

**Issue by Gadget100** [tsunamayo/Skywanderers#329]
I'm finding it almost impossible to reliably select stars (or planets) on the holomap if there are blocks close behind the map. It appears that the game is interpreting any clicks as being directed at the block behind the star.

**Comment by tsunamayo** [comment]
Okay thanks for pointing that out. Holomap interaction is crappy af, and will be completely refactored. Thanks

**Comment by tsunamayo** [comment]
No longer applicable.
