### ISSUE TITLE
new block rotation ui doesn't align axis for mass placing blocks

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#330]
When placing down a block, then orienting it to a different plane using the scroll wheel on the mouse, then pressing ctrl to extend the blocks in a given direction, it inherits the directions of extension of the surface the block was put on prior to using the scroll wheel, where it should change to the directions theoretically available on the new plane.

sorry for the wordy explanation but it's quite difficult to explain. To see what i mean, try mass place blocks after altering the block orientation with the scroll wheel.

**Comment by tsunamayo** [comment]
Okay I got it, yes I havent redone the line/plane function yet to acomodate for that

**Comment by AfterRebelion** [comment]
Since placement and rotation systems have been reworked, this issue is no longer valid in recent versions (19w23b)
