### ISSUE TITLE
Panels overwrite rounded pieces when placed on the side [17w44a]

### ISSUE THREAD

**Issue by youeyoue** [tsunamayo/Skywanderers#332]
1. Place a **short arm** somewhere (or go to red striped tutorial room where one already exists)
2. Place a **panel 4x4** on the rounded side of short arm until you hear the placement sound
3. You'll hear the sound of the panel being placed but you won't see it
4. Undo will cause the short arm piece to disappear
5. Redo after the Undo will cause the panel to appear where the short arm used to be

You can remove the already existing "short arm" piece in the tutorial room by doing this.

This can be reproduced on many other small pieces such as **pipe** and **mug**.  And also on some of the angled faces of the various **studs brick**.

This can be reproduced using all the different **panels**, **light bricks**, **hinges**, and probably more.

**Comment by tsunamayo** [comment]
Okay this problem is fixed! Thanks for the detailed test case. Cheers
