### ISSUE TITLE
Specific microblocks that emit light cause far away things - habitat ring to be lit up

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#333]
When  you get close to a microblock bushing light and look at the dark side of a ring, the area the bloom covers on your screen is lit up, as shown in the attached image.
![image](https://user-images.githubusercontent.com/31857052/32265448-fdbe0a66-beda-11e7-9bf0-00f1197f8b67.png)

**Comment by tsunamayo** [comment]
Hum thanks for spotting this indeed, I guess the weird stuff if more the area that stays black. I will have a look at it thanks!

**Comment by tsunamayo** [comment]
Hi, okay I finally fixed this issues. Thanks for reporting it! Cheers
