### ISSUE TITLE
[BUG] Remapped Keypad/Arrow keys Issues

### ISSUE THREAD

**Issue by BeeTLe-BeTHLeHeM** [tsunamayo/Skywanderers#334]
Hi, 
I have remapped the keys on the keypad and arrow keys, and I have noticed a few things:
- Mapping a key on the keypad Enter key, show no label on screen (the field remains empty), but entering in game the key get remapped on [F]
- Mapping a key on the keypad Minus key, show no label on screen either.
- I have mapped movement on Keypad 8/4/2/6, and inventory on Keypad 7: if BLOC_NUM is on, I can't move, but if BLOC_NUM is off, I can't open the inventory.
- Plus, mapping the flashlight on the Right Arrow key, if I move right (with BLOC_NUM off), the character moves and the flashlight is switched (both key get activated).

**Comment by CyaNox** [comment]
Could you clarify where exactly you are setting these mappings as there are currently two ways (launcher and in game) to set some of these?

Partially related issues: #323.

**Comment by BeeTLe-BeTHLeHeM** [comment]
Sure, I remap the keys from the main menu, options -> controls -> key mapping, I haven't touched the launcher settings.

I attach two images with the specific settings I've used. Note: the Activate key has reverted to F, and the Drive- key is mapped to the Keypad Minus.
![20171101115730_1](https://user-images.githubusercontent.com/568593/32271869-2428c012-befc-11e7-8016-9f822a5af568.jpg)
![20171101115748_1](https://user-images.githubusercontent.com/568593/32271872-29133d32-befc-11e7-8172-14c4fc2067bf.jpg)

**Comment by tsunamayo** [comment]
Fixed: Enter and Return key, Minus key.
For the keypad, to make it work you need to have it active (BLOC_NUM on).
When BLOC_NUM is off, it maps to the same control as the Arrow key.
You cant reassign movement key from in game for now as this setting is inside the Unity Launcher, soon to be removed. I guess yours were still at Arrow keys, so this is why when having BLOC_NUM off you where able to move the character (it had nothing to do with your assignment, hence the confusion!)
Thanks
