### ISSUE TITLE
Logic suggestion

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#335]
a transistor logic style board would be great and super usefull

summary:
a gate that has 2 inputs and one output
there will only be an output if both inputs are powered
due to the fact skywanderers uses fuzzy logic you may want to preserve the power strength of one particular signal, so the primary input (c) should be clearly distinguishable from the bridge (b), the power strength of the bridge would be lost in this gate, should the bridge be receiving power then only the inputs signal will be outputted 
![image](https://user-images.githubusercontent.com/33142373/32271010-f876b17a-bf5c-11e7-969e-4b121bdf8a65.png)

think of it as a person or a croud trying to cross a river, if there is lots of people but no bridge, no-one gets accross, is there is a bridge but no-one to cross the bridge, still no-one gets to the other side, but if there is a bridge and people to cross it then people can get to the other side

**Comment by CyaNox** [comment]
I fully support something like this however I think the majority of what you want already exists in the Mix gate. However currently even though you can connect a slider to the white logic studs it does not actually set the value.

If we can connect sliders and other logic outputs to these white parts this Mix gate becomes even more versatile than adding a transistor like gate.

**Comment by tsunamayo** [comment]
What do you mean "Powered"? Logic in skywanderers does not work like minecraft. You just send a manipulate pulse.

**Comment by CyaNox** [comment]
This conversation that happened on discord may be relevant:
> Mellcor: @ Noxy mix gate is more for setting angles and move lengths on rotors and rails, I don't understand how it would function as a transistor

> Noxy: if you can set the white bits through logic you can make it work like one.
> Noxy: What I'm proposing is that the white bits also become inputs, not just static values.
> Noxy: @ Mellcor this could also work for the constant gate (though it would need to be renamed since it wouldn't be constant anymore) just the mix gate makes it even more versatile due to the two values you could use.

> Mellcor: @ Noxy could you explain how it would work tho, I can't figure it out, I get as far as have white A set as 0 and white B set as 1 or 0, but the blue input uses a pulse to change between White A and white B where as a transistor requires a constant input

> Noxy: @ Mellcor In this setup; the switch connected to the mix gates input would be our transistor's "base" the top white connection which is connected to the slider would be our transistor's "collector" and the output would be the "emitter" (granted this does not work right now). If the mix gates input were altered to accept the input signal we should be able to set the rotor to 0 with the switch off and 0.5569977 if on. While the switch is on the changes to the slider would immediately affect the rotor but while off it wouldn't.
![2017-11-01-12-24-21](https://user-images.githubusercontent.com/211381/32275603-2cbd9b20-bf0c-11e7-83c1-5181f7641313.png)
![2017-11-01-12-24-27](https://user-images.githubusercontent.com/211381/32275606-2e11307c-bf0c-11e7-9921-3834b4970c69.png)

> Mellcor: Still the collector with mix uses a pulse not a constant signal
> Noxy: Nothing in logic uses a constant signal.
> Mellcor: Power on = constant
> Mellcor: Oh rip nvm
> Noxy: yeah but its not constant its only pulsed once when activated.
> Mellcor: I must be tired

**Comment by tsunamayo** [comment]
Okay so to sum up, you want to be able to push a new value into the constant gate? If it is that I could make the change indeed. Cheers

**Comment by CyaNox** [comment]
Yes in both the constant gate and mix gate :+1: (And yeah I know the "constant" name won't be as correct anymore).

**Comment by tsunamayo** [comment]
Yes, I could rename it to capacitor, I might ask the community about that. I definitely needs to open a discussion with some circuit wizard out there to improve it.

**Comment by tsunamayo** [comment]
Deprecated with the new logic system. Thanks!
