### ISSUE TITLE
Teleportation or Spawn Point User Interface Problems

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#336]
The user interface to teleport around to various places can not be closed with the `Escape` key.

There are visual bugs as seen in the screenshot below:
![2017-11-01-16-11-53](https://user-images.githubusercontent.com/211381/32281500-46fd1430-bf1f-11e7-9f6f-3bd46336a162.png)

The buttons that are out of the UI are not clickable.

**Comment by tsunamayo** [comment]
Hi, Scroll issue was fixed the other day, and I just added Escape support and a close button. Thanks!
