### ISSUE TITLE
[Bug][Interface] Hotbar displays wrong number when first loading [17w44a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#337]
When a save first loads, the hotbar defaults to the first panel (#1). However, when pressing Tab, the hotbar displays a "3" next to this panel. Scrolling the hotbar causes the correct numbers to be displayed, but the interface bug shows up the next time the save is loaded.

![20171101142720_1](https://user-images.githubusercontent.com/33041786/32293490-4c5f26a6-bf11-11e7-9718-ca9208db5c23.jpg)

**Comment by tsunamayo** [comment]
Thanks! That bug should be fixed now. Cheers!
