### ISSUE TITLE
Mechs falling through floors

### ISSUE THREAD

**Issue by Corvixin** [tsunamayo/Skywanderers#338]
I started to experience this a while ago but didnt think about it till I started messing with mechs. When piloting mechs, I fall through floors and have even fallen through the ground where the gray mountains are and water. I've also had the same problem with hovercars. I didnt know if this was a collision problem or not but I did ask around on the discord and found that so far one other person is having the issue.

**Comment by tsunamayo** [comment]
Okay, could you please send me your output_log file? It seems that you have issues with collision and the torus. Are you able to collide your character with the torus ground? Can you place blocks on it? Thanks

**Comment by Corvixin** [comment]
I'll send you that file when I get home. Yes I collide with the torus, as for placing blocks, I have yet to try but will when I get home

**Comment by tsunamayo** [comment]
Okay, are your falling though the ground sometime, or 100% of the time as soon as you get in the mech?

**Comment by Corvixin** [comment]
For mechs, it is only when in certain areas of the torus or on ships, but when in those areas, it is 100%. With hovercars, its 100%. I have yet to have this happen with a ship and I tested, I'm able to place blocks on the torus without problem. And heres the output_log you asked for.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1443821/output_log.txt)

**Comment by tsunamayo** [comment]
Issue deprecated, new tech is different. Thanks!
