### ISSUE TITLE
Rotation axis is not being recalculated at all

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#339]
There various ways that games tend to determine the rotation axis center point though the most common one seems to be the center of mass.

In Skywanderers the rotation axis is never recalculated or repositioned to reflect the changes to what you've build. And is thus stuck on the first block you've created (the Starter Block).

If you do something like this:
![2017-11-02-09-48-18](https://user-images.githubusercontent.com/211381/32317465-2a3cf8ac-bfb4-11e7-8f82-5dd35695dadd.png)

Where you build out a decent bit at first and then remove all the grey bits and keep the blue bit to put your mirror blocks and identity block and build your craft at the red blocks. This technique was suggested as a good way to do things in this video: https://youtu.be/TFn9redeE4c?t=145 .

Even after removing everything aside from your creation at the red part the rotation axis will still be at where the Starter Block used to be.

Reloading does not change this at all and any craft created where the starter block wasn't near the center of mass will have odd rotational motions.

I'd like to see the rotation axis to be at the center of mass of the craft.

**Comment by tsunamayo** [comment]
Hi, it is supposed to be the center of mass already, so it is a bug. I will check this out. Thanks!

**Comment by tsunamayo** [comment]
Okay I fixed it. RotateAround native function was colliding with my way of dealing with position (it have to be custom because of massive distance) - but it is all good now. Cheers
