### ISSUE TITLE
[Visual Glitch] Screen flicker near a star. 

### ISSUE THREAD

**Issue by mrabow** [tsunamayo/Skywanderers#34]
Build 2017-02-20 [Experimental]
Hyper jumped to a star and and this visual glitch. 
First jump from a fresh reload of the game visit blue start system 
https://streamable.com/gjkvs
Visual glitch persist in all star systems. 
The glitch disappears when moving away from the star

**Comment by tsunamayo** [comment]
Hello, I dont reproduce this issue in latest build, could you please tell me if you get this in next build ? I would like to know if this issue is specific to your GPU. What is your GPU by the way ?
Thanks !

**Comment by mrabow** [comment]
I cant recreate it myself anymore, so it seems to have been fixed. I Flew
around a blue sun a good five minutes, there were no artifacs of any kind.
My graphic card is a Sapphire Radeon R9 290 Tri-X.

2017-04-11 12:25 GMT+02:00 Francois Duret <notifications@github.com>:
