### ISSUE TITLE
Hose will link to incorrect entity if spawned on a Child Entity

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#340]
![image](https://user-images.githubusercontent.com/33023316/32317852-363bcec8-bfad-11e7-8af2-5c5917d1bf70.png)

the hose has cross-linked to the other leg, rather than to itself. Also looks like I have to completely rebuild that leg from scratch...

**Comment by tsunamayo** [comment]
Hi, you mean it happens at reload of the blueprint, or straight away when you link it? Thanks

**Comment by Napther** [comment]
So the Left Leg has a Hose attached to it. I wanted to dupe the left leg (behind) onto the other side to make the Right leg (Foreground). However, the pipe connection from the foot to the shin on the left leg got confused when I duped if from the Thigh, causing the right foreground leg here to create an incorrect attachment to the original leg immediately after being spawned onto the leg joint

**Comment by tsunamayo** [comment]
Okay I am not sure to understand the test case, did it involved child entity copying? How you made the leg switch part is unclear to me (the dupe ;-)). Thanks

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks!
