### ISSUE TITLE
Logic on rails disappearing when saving

### ISSUE THREAD

**Issue by AlexJHockley** [tsunamayo/Skywanderers#341]
Sadly I cannot seem to accurately reproduce this issue, but will give all the information I can.

For awhile now, my logic boards placed on constructions on rails disappeared randomly. Today, I have twice had this issue specifically when looking at either the rail or the logic on said rail as soon as I hit the save button.

That is to say, when I hit "save", these rail placed logic blocks entirely dissapear, along with the "source" rail itself (not the extensions though).

I can't seem to replicate this directly sadly.

**Comment by AlexJHockley** [comment]
I've attached some screenshots of the affected and my output.log file (although I am not entirely sure it is the correct one, appologies if not. 

Also, credit to Noxy on Discord, they reminded me I should do this. Think I'd remember after doing software and product development at uni for ages but nope, you'd be wrong.

# Screenshots
![image](https://user-images.githubusercontent.com/20553073/32319881-dded0ba0-c020-11e7-987c-c96456546536.png)
![image](https://user-images.githubusercontent.com/20553073/32319892-e53a8310-c020-11e7-8bde-8eaf9097ac71.png)
![image](https://user-images.githubusercontent.com/20553073/32319911-f032d2cc-c020-11e7-924c-e1a584b1afeb.png)

## I also have had rails and their logic disappear from this area too:
![image](https://user-images.githubusercontent.com/20553073/32319930-00d7baac-c021-11e7-8f19-fca51e491cfb.png)
![image](https://user-images.githubusercontent.com/20553073/32319939-04f5630a-c021-11e7-895e-fac9bdcd564a.png)


# Output Log
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1437210/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
I have encountered this as well. There doesn't seem to be any single "trigger" for it. It'll save for a number of times, then at some apparently random point, disappear. Very odd.

**Comment by tsunamayo** [comment]
Okay thanks I will look into this. I keep you posted.

**Comment by Dwarf-LordPangolin** [comment]
If it helps any with reproducing this, I noticed today that it only happens if the logic has been edited recently; connecting, reconnecting, naming, or renaming logic, then saving, causes it to happen (but only sometimes). If the error doesn't happen **right** after you've edited it, you seem to be safe from it. I haven't found anything that reproduces it 100% of the time, but it seems to only happen right after editing the logic on the child entity in some fashion.

**Comment by tsunamayo** [comment]
Okay the bug have been fixed! Thanks
