### ISSUE TITLE
Speedometer showing wrong speeds

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#342]
While playing around and just flying off in a random direction I found that Speedometer is highly inaccurate when it comes to Hyperdrive speeds.

![2017-11-02-10-36-24](https://user-images.githubusercontent.com/211381/32319185-f9f22e96-bfb9-11e7-8a92-b4f098ee17cc.png)

In the screenshot I'm going full blast on the hyperdrive and I can see the sun and ring planet disappear quite rapidly suggesting that I'm going much much much faster than 15m/s.

The Speedometer isn't stuck at this number it rapidly fluctuates its number so fast I can't actually read what it says unless I make a screenshot.

**Comment by tsunamayo** [comment]
Yes sorry this is a notorious bug, but now I have no excuse to not fix it ;) . Thanks!

**Comment by EthanNar** [comment]
this bug still persists with latest experimental. Is contantly jumping around during acceleration in std flight, and is wholly inaccurate in hyp

**Comment by AfterRebelion** [comment]
This issue is already fixed in recent versions (19w23b)
