### ISSUE TITLE
Holding a light block will illuminate child entities

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#343]
![image](https://user-images.githubusercontent.com/33023316/32321800-47108d1c-bfba-11e7-9b1b-c1f5aeb9371a.png)

![image](https://user-images.githubusercontent.com/33023316/32321804-4baff0d8-bfba-11e7-9f01-1e3322151a77.png)

The colour is locked to being white-ish light. Note how the legs have their shadows removed but the cocpit does not

**Comment by tsunamayo** [comment]
Ah nice catch I got it, will fix it soon. Btw for the "light only on children entity" it is a limitation due to the current lighting system, that will be refactored soon (this month) to get a coherent lighting between main, children entity and players. Thanks!

**Comment by tsunamayo** [comment]
Thanks, issue was fixed. Cheers
