### ISSUE TITLE
Deleting a child entity that has a hose connection to parent will cause Spaghetti

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#344]
![image](https://user-images.githubusercontent.com/33023316/32326526-0e5f7b5c-bfcb-11e7-88fb-16ed04de3eb9.png)

While still unable to get my damned mech working as it should, I deleted the foot ball joint as it may have been the cause by being "out of line" of the others. There was a connection from the foot to the Shin of the robot, and now it looks like the image above.

**Comment by tsunamayo** [comment]
Okay thanks indeed this is a case I need to care of. You can send me your mech if you want me to have a look at it - it looks very neat btw. I designed the system to be easy and effortless for the builder, so I guess I have still more work to do on that...

**Comment by Napther** [comment]
I found the exact issue: Visually, the foot ball joint was perfectly fine and "acted" fine. There was no feedback that ALL the ball joints have to be, when straightened, besides the hip, top to bottom. The knee and ankle have to be placed onto the "bottom" of a Brick/block in order to function correctly.

![image](https://user-images.githubusercontent.com/33023316/32356269-f086edfc-c02b-11e7-902d-f84ec3db155c.png)

The red mech layout is what I had: What threw me through a loop was the fact the thing was WALKING in space just fine as I was building it, which is very confusing indeed, or would walk on 1 leg only, among other things. I built the Mech after cycling the legs to be connected, meaning all the ball joints settled into their working positions as seen on the diagram.
As for the finished Mech, Ill have it up soon to add to all the collections and such but at that point it would be "fixed"

**Comment by tsunamayo** [comment]
Okay this issues is finally fixed. As for the Limb configuration, I decided to switch back to usual 2D gui in order to provide a lot more customization options. So I will let the player do join rotation tweaking as the maths behind is quite hairy to handle all the case (if not simply impossible in some case). Thanks!
