### ISSUE TITLE
Crash Screen resolution

### ISSUE THREAD

**Issue by DocTyger** [tsunamayo/Skywanderers#346]
Je lance Skywanderers, j'arrive sur le premier écran, je change la "**screen resolution**" j’appuie sur "**play**" et le jeu plante, je relance mon jeu sans changer la résolution, et il se lance correctement. J'ai essayé avec plusieurs résolutions différentes et ça a toujours lieu.

I launch Skywanderers, I arrive on the first screen, I change the " **screen resolution** " I press " **play** " and the game crashes, I relaunch my game without changing the resolution, and it launches properly. I tried with severals resolutions and it always happens.

Test 1 :
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1438011/output_log.txt)
Test 2 :
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1438014/output_log.txt)
Test 3 :
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1438015/output_log.txt)

**Comment by tsunamayo** [comment]
Okay merci! Le launcher va disparaite lors de la prochaine update. Que ce passe-t-il lorsque tu change la resolution a l interieur du jeu? Merci

**Comment by DocTyger** [comment]
Pre Alpha 17w44a

Aucun Crash ou Bug quand je change en jeu. (Mais pour pour avoir re tester le bug, il ne fonctionne plu)

**Comment by CaptainCJH** [comment]
This is similiar to #311 and #317.

**Comment by tsunamayo** [comment]
Should be fixed with the new build as the launcher disappeared. Thanks
