### ISSUE TITLE
Placing starter block, faces player body alignment not head or camera alignment. 17w44a

### ISSUE THREAD

**Issue by JennyLeeP** [tsunamayo/Skywanderers#347]
When placing a starter block, the block appears to be placing in alignment to the players body not the head or camera as I would have expected.
(Likely as intended , does not feel intuitive though)

I even managed to get a block placed behind me.
Easy to confirm this placement in 3rd person mode.

**Comment by tsunamayo** [comment]
Hi, yes it is supposed to have the same alignment as your body, but not to appears behind you... I will check this, thanks!

**Comment by tsunamayo** [comment]
Hi, it seems that I cant reproduce that issue. Can you tell me how you manage to place it behind your body? Thanks!

**Comment by JennyLeeP** [comment]
I am unable to reproduce this in Single Player.
When I first noticed this I was in Multiplayer with Cyanox. I can confirm it will happen in MP, which makes sense.
Consider this closed, and now more of a suggestion.
