### ISSUE TITLE
Connecting hoses in multiplayer does not synchronize to other players

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#348]
The client connected to me has connected all of these hoses. I could see the linking happen but no hose connection actually shows up.

![2017-11-02-21-55-08](https://user-images.githubusercontent.com/211381/32349781-8083871c-c018-11e7-99cd-715e2efa2c97.png)

**Comment by tsunamayo** [comment]
Issue deprecated. Thanks
