### ISSUE TITLE
[BUG] Ship Orientation Not Based on Current Ship Core

### ISSUE THREAD

**Issue by Slyrae** [tsunamayo/Skywanderers#351]
**Issue:** Starship core, once placed, determines the direction of the ship. However, if an additional ship core is accidentally placed, the ship then assumes the second core's direction even after deleting or undoing it.

**How to Reproduce:** Make a basic starship. Place it's ship core in one direction, then place another ship core in a different direction. Destroy the second ship core. The original one is still there, facing the intended direction, however the ship still uses the (now destroyed) second core's direction instead of the remaining original core's direction.

**Comment by tsunamayo** [comment]
Thanks for reporting that! I fixed it, now the orientation used is the one from the core you just activated. So that way it should be possible to do a Slave One kind of moving configuration. Cheers!

**Comment by Slyrae** [comment]
Thank you! 🤔
