### ISSUE TITLE
game breaking mech issues

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#352]
im unsure how to explain what the bug is so ill do a bullet point style list of what i did
was trying to make a mech
testing out things in different orientations and setups
had a mech with the core on it set to east style
the legs were set to west style
also had a camera on a ball join as well as a turret computer that wasnt hooked up to anything yet
had a quad input gate linked to a control stick, the turret block and  the mech block and the camera
got in mech to test it out, worked fine, went to leave mech and couldnt leave mech, could press ESC and the block menu key and could click the blocks but no response, was able however to return to the start screen. 
upon returning to the world i was still in the mech however now i could no longer use the mouse to look around and could only move left right, up down and side to side
restarted the game
mech now works fine
i keep messing around with mechs
want to make a mech with a moving waist
put small rotor on base with legs, put arms on top half with mech core
when accessing the mech core menu was unable to select anything
closed menu
opened it again and it started rapidly flashing
am no longer able to break any blocks or interact with anything
closed game
restarted game from desktop
got into the mech, now im unable to leave like i nthe previous bug but due to not being able to link any arms or legs i cant move at all
restarted game again from dekstop
saved the mech so i could send to you
deleted the mech for fear of its buggyness

**so yea i sent you the mech file via PM on discord**

**Comment by tsunamayo** [comment]
Hi, could you zip the mech file over here, it will be a lot easier for me to track down the issue. Thanks

**Comment by Mellcor** [comment]
[breaker.zip](https://github.com/tsunamayo/Skywanderers/files/1440249/breaker.zip)

**Comment by tsunamayo** [comment]
Okay I think your bug was because the mech core was put on the moving waist as you said. This is now prevented in latest build. Thanks!
