### ISSUE TITLE
[Bug] Holograms move at high speed/warp

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#353]
When a ship is moving at very high speeds within a system, or traveling through warp to another system, the holograms do not always appear where they should. Sometimes they appear ahead or behind where they should, other times they do not appear at all (possibly too far ahead/behind the ship to be seen).

![20171102220553_1](https://user-images.githubusercontent.com/33041786/32363173-f11bb170-c03b-11e7-96c7-97725b2a1353.jpg)

**Comment by tsunamayo** [comment]
Issue deprecated. Thanks
