### ISSUE TITLE
Mech Core deletion breaks Game

### ISSUE THREAD

**Issue by Nero-Akavar** [tsunamayo/Skywanderers#355]
Once I placed a mech core down on an entity and deleted it then place it down again, If I delete the new mech core or try to the mech core will continuously glitch in and out rapidly 
and I am no longer able to place anything down or save.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1440454/output_log.txt)

**Comment by Mellcor** [comment]
#352

**Comment by tsunamayo** [comment]
I fixed a bug concerning mech core on children entity, that should prevent from happening. Btw I was not able to reproduce your test case, is this something you can reproduce? Thanks
