### ISSUE TITLE
[Visual] Switches visually reset when loading a save file (17w44a)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#356]
Switches reset to a halfway-toggled position when a save is loaded, regardless of what their position was when the game was saved. This is only a visual issue, as the output value of the switch seems to be saved and loaded properly.
The only actions performed between the pictures below were saving, exiting to the title screen, and reloading the save file. Left side is before, right side is after:
![switch bug](https://user-images.githubusercontent.com/33088776/32372286-9927918a-c06a-11e7-93fc-0f39e95dad1d.png)

**Comment by AfterRebelion** [comment]
This is no longer valid in recent versions (19w23b)
