### ISSUE TITLE
Connected texture visual bugs

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#357]
A minor visual bug appears in some corners of the textures when placing blocks in specific orders.

This video demonstrates a few ways to make this bug appear: https://youtu.be/KOGfeHRenIw

This seems to apply to all connected textures I've tested with so far:
![2017-11-03-14-44-06](https://user-images.githubusercontent.com/211381/32376634-a41de928-c0a5-11e7-8fec-7a39ad2ca731.png)
![2017-11-03-14-44-33](https://user-images.githubusercontent.com/211381/32376638-a54da310-c0a5-11e7-86bb-50b630c670f9.png)

**Comment by AfterRebelion** [comment]
This is no longer valid in recent versions (19w23b)
