### ISSUE TITLE
Block Codex oddities with lower resolutions

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#358]
I'm not certain what the lowest resolution is that Skywanderers is going to support but to start off I personally think 720p should be fully supported. With that in mind I found some minor visual oddities with the Block Codex:
![sw_block_codex_oddities](https://user-images.githubusercontent.com/211381/32390067-375dca1a-c0cd-11e7-8623-6ad3ec62440e.png)

To preserve extra screen space for the actual block codex and hotbar I think the margin at the top (marked with ![a](http://cyanox.nl/text?f=inversionz&s=24&t=a&c=d00 "a")) should be minimized as much as possible.

The hotbar switcher indicator (marked with ![b](http://cyanox.nl/text?f=inversionz&s=24&t=b&c=d00 "b")) is partially behind the Blocks Codex.

Some parts of the hotbar render behind the Blocks Codex ![c](http://cyanox.nl/text?f=inversionz&s=24&t=c&c=d00 "c").

All of this highly depends on what the smallest resolution is going to be that will be fully supported an whether or not UI scaling is going to be a thing in the future or not.

**Comment by tsunamayo** [comment]
Hi, I wanted to have a look at that, I can have UI scaling below a certain resolution. Thanks

**Comment by CyaNox** [comment]
I don't think the UI scaling implemented in 17w44c is the right way to go. It creates a lot of visual artifacts that just irk me in the lower resolutions:
![2017-11-05-13-36-47](https://user-images.githubusercontent.com/211381/32414981-f5733de0-c231-11e7-9780-7cead6ff0e47.png)

This was in 720p (1280x720). Note that there is plenty of room (even unscaled) for the UI to move up.

I think UI scaling should go in discrete steps, this way artifacts are minimized. For example Minecraft, Starbound and similar games do UI scaling in discrete steps.

**Comment by tsunamayo** [comment]
Yes you are right, this is drawback of doing a retro pixel art gui ... I will improve it indeed, by moving it up and doing a smarter scaling, but maybe not on the short term though. Thanks!

**Comment by AfterRebelion** [comment]
UI at 1280x720 still has problems in recent versions (19w23b)
![imagen](https://user-images.githubusercontent.com/559819/59042514-e02ddb00-887a-11e9-876a-15fe2b7bb15c.png)

**Comment by tsunamayo** [comment]
Thanks, yes it is the 3 row hotbar that is causing some trouble.

**Comment by tsunamayo** [comment]
Okay this issue is finally fix, available in next update. Thanks
