### ISSUE TITLE
Ctrl + Drag button order

### ISSUE THREAD

**Issue by Cornflakes91** [tsunamayo/Skywanderers#36]
Ctrl + drag only works when right mouse button is pressed first and then ctrl is pressed.
expected would be that i can leave ctrl pressed and rightclick + drag multiple times without releasing ctrl.
or with pressing ctrl before rmb

**Comment by tsunamayo** [comment]
Okay sorry I missed this issue, it is in fact quite logical to do it your way, I will talk with other builder to see what they think.

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
