### ISSUE TITLE
Impossible to create a Hepta in Canopy pieces (Wedges ignore Mirror)

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#360]
![image](https://user-images.githubusercontent.com/33023316/32396006-7df21fc2-c0db-11e7-9ce4-589d98011f16.png)

![image](https://user-images.githubusercontent.com/33023316/32396056-b7429eb4-c0db-11e7-906e-48d532ec2fcb.png)

Happens with both forms of Canopy Glass Wedge. It appears they ignore mirror and are otherwise whacked.

**Comment by tsunamayo** [comment]
Yes there is already a bug for this, but I think what you would need a true hepta cockpit block right?

**Comment by Napther** [comment]
"Yes there is already a bug for this, but I think what you would need a true hepta cockpit block right?"

Yes please! that will do wonderfully. Reducing the number of "odd-gaps" that are extremely tricky to fill (for the likes of a more battle-system-minded person like myself especially) is always a nice change to see

**Comment by tsunamayo** [comment]
The new triangle windows can now mirror correctly. Thanks!
