### ISSUE TITLE
Incorrect Texture display on Hepta-tetra slopes

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#361]
Left side (facing)
![image](https://user-images.githubusercontent.com/33023316/32396992-8a95fefc-c0df-11e7-86e8-f9ead906817f.png)

Right side (facing)
![image](https://user-images.githubusercontent.com/33023316/32396976-77af9e38-c0df-11e7-9f21-da237e7289d2.png)

Both sides are identical in all ways due to mirror, yet the right and left side show different textures for the slope back from the Cockpit

**Comment by tsunamayo** [comment]
Yes this is case where the border logic is giving up. I am currently considering a more radical approach for doing border, but I wont look into it before a bit of time, so this bug is gonna stay open for quite a bit. Thanks

**Comment by AfterRebelion** [comment]
This is no longer valid in recent versions (19w23b)
![imagen](https://user-images.githubusercontent.com/559819/59041527-11a5a700-8879-11e9-912e-4dac18b9e32a.png)
