### ISSUE TITLE
Remaining in control of Turret axis while having full character control

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#362]
![image](https://user-images.githubusercontent.com/33023316/32400416-ac37e422-c0f7-11e7-8727-c4e91809b08f.png)

![image](https://user-images.githubusercontent.com/33023316/32400421-bae50aea-c0f7-11e7-83de-ecaf62a0295b.png)

Might take a little squinting to see but I am in a pause menu, and that turret is still going wild.

I was trying to link up a MB1 link with a joystick and Turret Computer and a dual-enter Logic. I somehow attached the Stick to the Input for enter, then the output of the Dual Enter to the Turret and attempted to link it to the MB1 brick, but the output did not connect. However I realised that the MB1 brick will connect to the OUTPUT of the Dual-enter. 
![image](https://user-images.githubusercontent.com/33023316/32400477-99ee0ae8-c0f8-11e7-9d29-0f78efa3dd14.png)
![image](https://user-images.githubusercontent.com/33023316/32400480-a915ab3e-c0f8-11e7-91b0-b7f96dc1767a.png)

**Comment by tsunamayo** [comment]
Okay I tried the test case - the weird assignment of the hotkey is unfortunately normal at this point (I will try to change that for sure), but turret was behaving correctly. Is the issue that the turret was still moving on the menu ? (this one have been fixed in 17w44b) Thanks

**Comment by Napther** [comment]
![image](https://user-images.githubusercontent.com/33023316/32415251-90dfb2bc-c22e-11e7-8386-8632c0e5dbc9.png)

![image](https://user-images.githubusercontent.com/33023316/32415253-97dabac6-c22e-11e7-91e8-3f648f4d85e7.png)

Within build 17w44c, All I did here was activate the Turret control computer and press F to try and get out. It doesnt ket me get out the first time, but another F or two eventually escapes the Turret control and gives me character control: But the Turret is still following my movements.

**Comment by tsunamayo** [comment]
Okay, could you please send me your very sexy turret blueprint ^^ ? Thanks

**Comment by tsunamayo** [comment]
Hi, when you have time if you could give me the blueprint so I can investigate this, I am not reproducing on my side... Thanks!

**Comment by tsunamayo** [comment]
This is issue is deprecated. Thanks
