### ISSUE TITLE
[BUG] Volume changes at main menu and in-game not retained [17w44b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#363]
The game does not save changes to the volume from either the main menu or the in-game menu.

**Comment by tsunamayo** [comment]
Cant reproduce the issue, are you doing something specific? Thanks

**Comment by Dwarf-LordPangolin** [comment]
Unfortunately I can't think of anything specific I'm doing when it happens. It occasionally remembers volume changes, but it resets most of the time, and under all circumstances. I'll keep trying to see if there's a pattern to it.

**Comment by Segdis** [comment]
I can confirm this is happening to me in version 17w45c. 
In my experience, volume changes from the main menu are lost when a save is loaded, and volume changes from the in-game menu only persist while you are still in the same session that the change was made. They reset when exiting to the title screen.

I discovered after some further testing that changes ARE retained if you exit to the desktop after setting the volume in the main menu, and will be correct on the next launch of the game. However, both volumes are still reset to full after actually loading a save. This bug also affects changes made by manually editing the `masterLevel` and `musicLevel` values in the `SETTINGS.ini` file. Changing the values before loading the game will work and show the new values in the main menu, but they are reset after loading a save, and reopening the `SETTINGS.ini` file shows both as 100 again.

**Comment by tsunamayo** [comment]
Issue was fixed some time ago. Thanks!
