### ISSUE TITLE
[EXPERIMENTAL] 17w44b character Movement Binds regression

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#364]
By pressing the Back key, the character walks in a diagonal line based on my original 17w44a keybindings.
![image](https://user-images.githubusercontent.com/33023316/32404236-f5166da2-c143-11e7-8467-781534895ebc.png)
It seems like the game bound an extra S key onto my Left control. Activating both appears to strafe the character as though both are pressed. As well as swapping the control of Right movement to the A key (normally Left)

**Comment by CyaNox** [comment]
I had to rebind all my movement keys for them to be correct again in 17w44b however @Napther in your screenshot you have `S` bound to both `Move Left` and `Move Backwards`. So beyond having to rebind my keys I'm not sure if there actually is a bug here just some oddities in the conversion (`Move Left` and `Move Right` being swapped).

**Comment by tsunamayo** [comment]
Yes sorry it was not very clear, you had indeed to remap all controls from the in-game now.
Hope it is all good for now. Cheers
