### ISSUE TITLE
[EXPERIMENTAL] Mousewheel in control menu sluggish

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#365]
When using the Options menu where there are sliders, using the mousewheel when the mouse pointer is over a config box will cause the mousewheel to not effect the scrolling movement of the Options menu.

If mousewheel is not on a config box, then it can take many, many scrolls of the mousewheel to reach the bottom of the controls page for example

**Comment by tsunamayo** [comment]
Okay, indeed this needs more work, I made it work on the codex but not yet on the config key. 
For the speed I also need to have a look, it is a bit slow in game, but super fast in start menu, and okay when I work in the editor... Where you in game or on start menu?

**Comment by Napther** [comment]
In game, when using this menu 
![image](https://user-images.githubusercontent.com/33023316/32410851-771473c0-c1c2-11e7-9ea4-f240007785f9.png)
In fact, its a little sluggish in all places, even in the block Inventory especially visible where the construction blocks are.

**Comment by tsunamayo** [comment]
Okay it should be better in next version, it is faster and now you can scroll when hovering a button. Thanks!
