### ISSUE TITLE
[EXPERIMENTAL] Ship thrust requires discrete input if bound to a Key

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#366]
Most games typically have Forward slowly increment the bar forward and Back do the opposite. Currectly you need to spam the Forward/back keys to get any effect in velocity, which will mess with activation of other controls associated with movement for a player flying a ship.

Suggest having double tap of forward/back keys do Max/Min speed, and holding a button down will automatically increment the speed forwards/back every interval period so as to match functionality/performance to a Joystick's thrust tab control

**Comment by tsunamayo** [comment]
Yes I was hesitating with this at first, I will add it indeed as it is cumbersome to mash the button when you want to go to max (which is all the time). Thanks

**Comment by tsunamayo** [comment]
Okay I just made this change. Thanks!
