### ISSUE TITLE
[EXPERIMENTAL] Mirror Plane undo/redo regression

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#367]
![image](https://user-images.githubusercontent.com/33023316/32404476-192811a6-c148-11e7-92bf-90ed11aff7e8.png)

Corner wedges are added by placing them down
![image](https://user-images.githubusercontent.com/33023316/32404479-2564f31c-c148-11e7-9b95-12c3f863173f.png)

Corner wedges removed by Destroy keybind
![image](https://user-images.githubusercontent.com/33023316/32404481-2ec55758-c148-11e7-9f64-4d8b81b5a969.png)
![image](https://user-images.githubusercontent.com/33023316/32404482-33538b96-c148-11e7-9e42-23d22f6f2364.png)

CTRL+Z PRESSED
![image](https://user-images.githubusercontent.com/33023316/32404488-3e70130a-c148-11e7-91b3-c9727d92721e.png)

CTRL+Z Pressed again
![image](https://user-images.githubusercontent.com/33023316/32404498-5a78c308-c148-11e7-8a54-97930f22f71b.png)

Same thing occurs when using CTRL+Z to remove the placed wedge, then CTRL+Y to replace it

Blocks that were mirrored do NOT reappear after undo/redo
![image](https://user-images.githubusercontent.com/33023316/32404529-d8a095b2-c148-11e7-9a02-2cb8ac447a88.png)

And sorry for the image spam, but it feels easier to visually go through what I am doing than to type out a bunch of paragraphs

**Comment by tsunamayo** [comment]
Okay it was the same issue as #475 so it is fixed now. Thanks
