### ISSUE TITLE
[EXPERIMENTAL] Thrust goes to -100% at neutral throttle with joystick

### ISSUE THREAD

**Issue by Beschaulichkeit** [tsunamayo/Skywanderers#368]
I am using a Logitech Extreme3D Pro joystick with throttle control. I have the acceleration keys bound to Joystick Axis 4 with inverted: ON. I am flying the green starter ship and the blue starter ship.

When I push the throttle control knob to a neutral position (centered) then the speed bar on the HUD jumps to the bottom position. For [STD] that is 0 and for [HYP] that is -100%. As soon as I transition beyond neutral, normal control returns and I have full control range +/-100.

When I change to inverted: OFF the behavior is the same.

**Comment by tsunamayo** [comment]
Okay I reproduced the bug, my joystick neutral zone is not straightforward to get so I didnt spotted it. I will fix it, thanks!

**Comment by tsunamayo** [comment]
I fixed the issue, it will be available in 17w45a. Thanks!
