### ISSUE TITLE
[EXPERIMENTAL] Options menu does not reset on exit

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#369]
If the player clicks on "Options," and then one of the sub-menus ("Game," "Graphics," etc), then presses ESC, the game remembers which sub-menu was active the next time "Options" is clicked. "Done" must be pressed to return to the general Options menu.

**Comment by tsunamayo** [comment]
Yes indeed. Thanks for reporting that!

**Comment by tsunamayo** [comment]
Okay it is now fixed! Thanks ;-)
