### ISSUE TITLE
(Visual issue) Invisible Slider Control 

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#37]
![image](https://cloud.githubusercontent.com/assets/25937107/23181238/2059a408-f86c-11e6-9520-c2e32f6085c6.png)

I am not 100% sure what caused this.

When I booted up initially it worked fine, then I adjusted the resolution which caused the icons in the inventory to disappear so I restarted my game. When I restarted and placed a slider control beside the control stick it became invisible.

**Comment by tsunamayo** [comment]
Tell me if you ever reproduced that issue! Other wise I will close the case, it was so long ago maybe issue dont exists anymore...
