### ISSUE TITLE
Custom paint Doesn't like child entities

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#370]
![image](https://user-images.githubusercontent.com/25937107/32409823-2a060bb4-c1ab-11e7-967f-697593fb0d29.png)

Dark = recoloured
Light = standard

Had this issue occur a couple of times with custom colours not changing to the adjusted versions on child entities.

**Comment by tsunamayo** [comment]
Thanks. You had any thing specific with this child entity or the way it was built?

**Comment by AfterRebelion** [comment]
You can freely use custom paints in child entities, so this issue is no longer valid in recent versions (19w23b)
