### ISSUE TITLE
Cannot warp when using a galaxy map on a child entity (17w44a)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#372]
Using a galaxy map that is on a separate child entity (such as a slider or hinge) to set a warp target does not work. It will visually show on the map that a destination was set, but the hyperdrive block will do nothing when activated. It will only perform warps that are targeted with a galaxy map that is part of the same entity as the hyperdrive block.

**Comment by tsunamayo** [comment]
Okay thanks for pointing that one out. I keep you posted!

**Comment by tsunamayo** [comment]
Okay this issue should be fixed now (will be in next build). Thanks!
