### ISSUE TITLE
duplication bug and theory on what is happening

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#374]
i made **build A**
**Build A** has **child A** and everything attached to that child will be **subchild A**
i made **build B** with the purpose of attaching **Child B** it to **Subchild A** with the ID block Copy paste Method
when i attach **Child B** to to the **Subchild A** , i think that it is using the same idenfying or something code as **Child A**
thats why when i attach **Child B**, it loads the first part of Child B , then it starts loading the **subchild A** of **Build A** instead of **subchild B** of **Build B**
and since i have now attached **Child B** to **Subchild A** of **Child A**, **Child B** is also now considered **subchild A** and hence it will load the new additions making a infinate loop

**Comment by Mellcor** [comment]
![station](https://user-images.githubusercontent.com/33142373/32413815-61334be6-c27e-11e7-8382-7ca0e88f7306.png)
![untitled](https://user-images.githubusercontent.com/33142373/32413820-6a2bf11c-c27e-11e7-9aed-bd0c9e56a655.png)

**Comment by tsunamayo** [comment]
Sorry, this is no longer applicable. Thanks
