### ISSUE TITLE
[EXPERIMENTAL] Issues in placing down multiple mirror planes

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#376]
After deleting a vertical mirror plane a while ago, I was unable to replace the vertical plane block at all. Or any other mirror for that matter. The ship currently has 1 horizontal mirror plane (left right symmetry), and the ship wont accept any other mirrors to be placed down.
![image](https://user-images.githubusercontent.com/33023316/32415768-a0ceeb2c-c236-11e7-83a1-60da1589561d.png)

A brand new ship/entity is also blocking placing down mirror plane blocks.
![image](https://user-images.githubusercontent.com/33023316/32415771-c6987bd4-c236-11e7-839f-f86abe95eea1.png)

**Comment by tsunamayo** [comment]
Thanks indeed, issue was fixed. Cheers
