### ISSUE TITLE
[EXPERIMENTAL] Cannot shift items on Hotbar - items removed from hotbar

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#377]
![image](https://user-images.githubusercontent.com/33023316/32416416-a4af8e2c-c240-11e7-8e22-21e3d478fba8.png)

![image](https://user-images.githubusercontent.com/33023316/32416420-b2c75440-c240-11e7-8bdb-5e2f3a1622ee.png)

![image](https://user-images.githubusercontent.com/33023316/32416424-b81dbcfe-c240-11e7-8e03-5d450a16e6d8.png)

So when dragging a new item from the Inventory and replacing something on the hotbar, the game automatically picks up the replaced piece. However this replaced piece cannot be set back onto the hotbar in a different location than it was. It is deleted. 17w44c

**Comment by tsunamayo** [comment]
Okay, I fixed it. Thanks for being so active and for the neat presentation! Cheers
