### ISSUE TITLE
[EXPERIMENTAL] Blocks sometimes will not be painted

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#379]
![image](https://user-images.githubusercontent.com/33023316/32419444-ba52dd20-c271-11e7-8ea2-2f528952bb3e.png)

ala this 1 block of armour that apparently does not want to take a spray can directly. Did get it painted by waving the cursor to the adjacent blocks in the end.

**Comment by tsunamayo** [comment]
Yes this is an old bug, I will leave it a bit like that as I planned a big refactoring on the way geometry is pushed to the GPU that will solve it (among other things). Thanks for reporting it!

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks!
