### ISSUE TITLE
[Experimental] Can't place symmetry blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#382]
I opened my game, flew to a new section to work on a new idea, placed a starter block then one hull and thus couldn't place a symmetry block on the starter block nor the hull block.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1444583/output_log.txt)

**Comment by CyaNox** [comment]
Duplicate of #376.

**Comment by tsunamayo** [comment]
Thanks indeed, issue was just fixed. Cheers
