### ISSUE TITLE
Distant stars trembling and seem too close [17w44c]

### ISSUE THREAD

**Issue by youeyoue** [tsunamayo/Skywanderers#385]
1. Distant stars tremble at various high zoom levels
* NOTE: Shaking the camera a lot at high zooms causes trembling to stop

2. Distant stars "appear" closer than solar system star (i.e. they disappear before the solar system star when zooming out)

See unlisted video for example:
https://youtu.be/6zFxvRsxVww

**Comment by tsunamayo** [comment]
Okay I fixed this by simply restricting the view distance in 3rd person as it had other implication and was not made for that. Thanks for noticing! Cheers
