### ISSUE TITLE
Can't Plot Jump Course With Small Holo Projector.

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#386]
I'm not 100% sure this hasn't been reported yet. But basically it isn't possible to plot a jump course using the hyper drive via the small holo projector. Myself and at least one other person has been able to recreate this issue. On a ship with no large holo projector linked to a hyper drive, and only a small holo. It isn't possible to jump.

**Comment by Segdis** [comment]
Could be related to #372.
Is your holo-projector mounted on a child entity, such as a hinge, slider, or rotator? I have been able to successfully use a small holo-projector to jump, but only when it is mounted on the same entity as the hyperdrive block.

**Comment by tsunamayo** [comment]
Okay, I do not have issue with the small holoprojector, so I think @Segdis is correct, it must have been the children entity issue. It is now fixed. Thanks!
