### ISSUE TITLE
Controls on experimental default WASD to keys that aren't WASD

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#388]
Every time the game is reloaded W and S stay bound, D goes left and A does nothing, after changing these controls back they reset after every restart no matter how the game is exited.

**Comment by CyaNox** [comment]
Related to #381 and #364.

**Comment by tsunamayo** [comment]
Okay I am totally not reproducing this... Could you check if the file 
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\SETTINGS.ini is not in read-only?
Also could you send me this file? Thanks

**Comment by schlid** [comment]
Settings.ini isn't read only, and i reset back to none experimental to get some building done, which resolved the bug, so it's definitely an experimental issue.

[SETTINGS.zip](https://github.com/tsunamayo/Skywanderers/files/1447008/SETTINGS.zip)

**Comment by schlid** [comment]
My friend caumen also had the exact same bug A= right and back+left is on S - here is his settings.ini from the experimental build 
[caumens settings.zip](https://github.com/tsunamayo/Skywanderers/files/1447234/caumens.settings.zip)

**Comment by JennyLeeP** [comment]
Did you press "Done" at the bottom of the keybinds menu?
I had the same problem till I pressed done, then they were saved.

**Comment by tsunamayo** [comment]
Okay fair enough, the issue was the game didnt save on Escape key pressed. I actually corrected that yesterday, so it should be all good in next update 17w45a. Thanks!
