### ISSUE TITLE
Ship speed locked [17w45a]

### ISSUE THREAD

**Issue by ColdSpiral** [tsunamayo/Skywanderers#390]
New in 17w45a. 
Entering a ship core / control system sets and locks the ship speed to 50%. 
This happens regardless of 
-accessing core via controller or directly
-sitting or standing
-new or existing ship core
-presence or absence of thrusters
-using default [ ] keys or re-binding thrust control

Could it be possible it's related to the fix for issue #368? It seems to be the opposite of Beschaulichkeit's problem, although I don't have a joystick or other controller attached.

**Comment by tsunamayo** [comment]
Yes indeed thanks, I have just fixed that, as it is a blocking bug I will repush a new version now. Thanks

**Comment by ColdSpiral** [comment]
Working fine now!
