### ISSUE TITLE
No longer able to place the various stud panels (regular or flat) on brick surfaces)

### ISSUE THREAD

**Issue by chunkblaster** [tsunamayo/Skywanderers#391]
since the most recent patch, the ability to place the various stud panels on brick surfaces is no longer possible. Placing on half-blocks and other surfaces similar to such are still possible. it only applies to brick surfaces. All types of stud panels are affected as far as i can tell.

**Comment by tsunamayo** [comment]
Okay this issue is now fixed and will be available in next build. Cheers
