### ISSUE TITLE
[REQUEST] Codex Screen Shape View & Drag

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#393]
When viewing shapes in the Codex, we get the thumbnail size, to the right of the bigger view - could we drag/double click from the bigger view to place in our hotbar? As far as I can tell, we have to drag from the thumbnail.

Thank you

**Comment by tsunamayo** [comment]
Actually you can press space key and have it replace an empty space automatically if you want to go fast. But I will add that feature also. Thanks

**Comment by tsunamayo** [comment]
No longer applicable with current codex. Thanks
