### ISSUE TITLE
[BUG] Missing texture

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#394]
This occurred after deleting block next to it which was obscuring the missing texture.

[https://steamuserimages-a.akamaihd.net/ugc/861738332839031857/DF2D10CA79B54F01A5E35E480EB8D2870F56FFEA/](https://steamuserimages-a.akamaihd.net/ugc/861738332839031857/DF2D10CA79B54F01A5E35E480EB8D2870F56FFEA/)

If that doesn't work, try this [https://i.gyazo.com/77f233b0e8548688c0ea2e8d17107693.jpg](https://i.gyazo.com/77f233b0e8548688c0ea2e8d17107693.jpg)

**Comment by CyaNox** [comment]
Note: You can drag and drop your images into these issues.

**Comment by Nexusdog** [comment]
From Steam?

**Comment by tsunamayo** [comment]
Hi! Are you building on the torus and are you using Mirroring?

**Comment by Nexusdog** [comment]
I was on the torus

**Comment by tsunamayo** [comment]
This should be fixed now. Cheers
