### ISSUE TITLE
[REQUEST] GUI - Back To Game option

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#395]
As title.

Thank you.

**Comment by CyaNox** [comment]
I have no idea what you mean could you clarify what this is about?

**Comment by Nexusdog** [comment]
In the GUI menu, to return to game you press X, yes? Or am I being stupid? (4 a.m. here)

**Comment by tsunamayo** [comment]
Yes you just need to press X or Escape key. Will check with other people if it is confusing or not, it would not be a big change to do. Thanks

**Comment by LeMinaw** [comment]
I support this idea. Actually this is not a big deal, but it always add 1/2 seconds of confusion to me.

**Comment by AfterRebelion** [comment]
This issue was never valid.
