### ISSUE TITLE
Invisible Bricks

### ISSUE THREAD

**Issue by oojimaflip** [tsunamayo/Skywanderers#396]
![20171107095805_1](https://user-images.githubusercontent.com/33450683/32489075-b06420a4-c3a6-11e7-91cc-52f5eda3366c.jpg)
![20171107095826_1](https://user-images.githubusercontent.com/33450683/32489087-ba694250-c3a6-11e7-8b32-70935df855b5.jpg)
Whilst building detail (pipe bricks) inside the room behind these engines a number of bricks became invisible, the invisible bricks can still be raycast to and deleted but they cannot be painted. Deleting affected bricks does not appear to affect the remaining invisible bricks; they stay invisible.
The ship has also become un-paintable.
The issue appears to be localised in that one area.

After having deleted the ship, all subsequent starter blocks are invisible.

Available log files... also worth noting is that my GFX card is being misreported as a GTX 960 when it is a GTX 980
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1449612/output_log.txt)

[error.log](https://github.com/tsunamayo/Skywanderers/files/1449613/error.log)

System specs:
Core i7 4770  3.6GHz
16Gb DDR4
GTX 980

**Comment by CyaNox** [comment]
Diplicate of #312.

In short: A refactor of the brick system is planned and should fix this issue in the future.
