### ISSUE TITLE
Key Mapping

### ISSUE THREAD

**Issue by Surac** [tsunamayo/Skywanderers#399]
if i try to map a key my game tell me to center a joystick, even if i havend attached a joystick

![screenshot 2017-11-07 17 29 45](https://user-images.githubusercontent.com/33027716/32505127-b055598a-c3e1-11e7-966e-ab427842b6b3.png)

**Comment by CyaNox** [comment]
Do you have a joystick or controller (like xbox controller) installed and/or connected?

**Comment by Surac** [comment]
Yes there is a USB Gamepad attached.

 

I have attached a screenshot. Gamepad seams to function normal and appears to be in neutral state

 

Lg

Surac

 

 

 

Von: Mark Sanders [mailto:notifications@github.com] 
Gesendet: Dienstag, 7. November 2017 18:36
An: tsunamayo/Skywanderers <Skywanderers@noreply.github.com>
Cc: Surac <mfischhaber@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [tsunamayo/Skywanderers] Key Mapping (#399)

 

Do you have a joystick or controller (like xbox controller) installed and/or connected?

**Comment by Surac** [comment]
![screenshot 2017-11-07 19 43 24](https://user-images.githubusercontent.com/33027716/32511540-585f1f3c-c3f4-11e7-9f76-5c216884fec4.png)

**Comment by CyaNox** [comment]
Hhhmm maybe the mentioned deadzone in #383 that still has to be implemented may fix this issue.

**Comment by Surac** [comment]
Yes i think this will help

**Comment by Captain-Wolfsburg** [comment]
I'm having the same issue. Tried disconnecting my Thrustmaster and my Xbox controller and it still occurred. Also, my keymap changed without my changing it.

**Comment by tsunamayo** [comment]
Okay can you tell me your controller model? Also it should not happen when you unplug it. Can you exit the game and do the unplug, then come back in and retry? Thanks
@Captain-Wolfsburg When did you disconnected your controller? Also what keymap changed? If it is the FPS movement it is normal. Thanks!

**Comment by Surac** [comment]
I can confirm:
unpluging USB Gamepad while Game is runnung does not prevent the bug. Seems the Game enumerates the usb contollers while the startup and does not see the controller unplugged

**Comment by tsunamayo** [comment]
Okay, so does that means that there is no issue when you restart the game? When did you unplug the controller, during assignment? Thanks

**Comment by tsunamayo** [comment]
Okay now you can disconnect your joystick during the assignment and it will be detected. Also I added the real name of the joystick / gamepad for less confusion. Thanks for reporting the issue! Cheers

**Comment by Surac** [comment]
Works perfekt
Thank you!
