### ISSUE TITLE
[Medium Priority][Visual] Icons on "inventory bar" dissapear after resolution change in game.

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Skywanderers#4]
Description of issue: 
When changeing resolution in the game, the icons on the "inventory bar" becomes invisible.

Frequency of issue:
Every time.

Steps to replicate issue:
Change resolution, ingame.

Possible Workaround:
None, to my knowledge

<iframe width="560" height="315" src="https://www.youtube.com/embed/ARW-PflZirE" frameborder="0" allowfullscreen></iframe>

**Comment by clmd58** [comment]
just discovered this. additionally, codex category icons disappear.

**Comment by Garrett-C** [comment]
Very good, Thank you tsuna

**Comment by AfterRebelion** [comment]
This no longer happens in recent versions (19w23b)
