### ISSUE TITLE
Ship Save broken - After Blocks start to disapear

### ISSUE THREAD

**Issue by Leadershinji** [tsunamayo/Skywanderers#40]
See Dropbox Leadershinji Save folder.

I was building a Gun Batterie -> And was trying to make the barrel longer -> then the blocks started to vanished and become invisible -> i saved and restarted as this fixes it normally...
Now it cant load the save. It gets stuck in the loading screen for ever.

[Aurora Class.zip](https://github.com/tsunamayo/Skywanderers/files/834547/Aurora.Class.zip)

**Comment by tsunamayo** [comment]
I fixed issue with one of your save, it will be available in next update !
Thanks
