### ISSUE TITLE
Visual bug on glowy parts

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Skywanderers#400]
There are white lines in the transition between glowy texture and non glowy texture:
![2017-11-07-21-32-41](https://user-images.githubusercontent.com/211381/32516331-461d7c56-c403-11e7-935f-3d36ac6e2398.png)

Especially on the darker more contrasty colors it is most noticeable. I found that the red in the screenshot above highlights this issue the most.

**Comment by EthanNar** [comment]
Issue is apparent in certain colors with the striped blocks as well

**Comment by tsunamayo** [comment]
This issue is no longer there. Thanks
