### ISSUE TITLE
Stud Nodes will appear in places you cannot place a Stud

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#402]
![image](https://user-images.githubusercontent.com/33023316/32520192-0eef944a-c407-11e7-893e-176c1086412e.png)

Here the Stud is appearing through the Wing Half Wedge brick, but cannot be placed as its occupied by the Wing piece and so will not accept a new brick. 17w45a2

**Comment by tsunamayo** [comment]
Okay thanks for spotting this one, it is now fixed. Thanks!
