### ISSUE TITLE
Cannot place stud grids/panels on Bricks

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#403]
![image](https://user-images.githubusercontent.com/33023316/32524072-fd6f4efe-c415-11e7-8265-ec1ab4ccf61f.png)

This is especially a problem on Wing pieces. Which dont naturally have a node. This would be a regression from the prior builds where stud grids were a valid placement on wings/bricks

**Comment by tsunamayo** [comment]
Yes it is indeed a regression and is already fixed. As this bug popup quite a bit I will do build this morning. Thanks.
