### ISSUE TITLE
Unable to interact with holo-interfaces for buttons/switches (17w45a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#404]
The holo-interfaces for buttons/switches (accessed by `SHIFT + RMB`) are not responding to `LMB` while opened, making it impossible to add labels or reset their logic links. The mouse clicks seem to pass through to whatever is behind it, which is damaging blocks.

Example: https://youtu.be/QFolaFH905Y

**Comment by tsunamayo** [comment]
Okay this have just been fixed. Thanks!
