### ISSUE TITLE
[BUG] cant place studs on half block

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#406]
you cant place studs on a half block if it has a rotor on it

**Comment by CyaNox** [comment]
Could you provide a screenshot of what you mean and what build you are experiencing this issue?

**Comment by Mellcor** [comment]
![untitled](https://user-images.githubusercontent.com/33142373/32533094-6f46073c-c4b3-11e7-9b8d-4b142f01db02.png)

**Comment by tsunamayo** [comment]
Sorry I am not reproduced your issue, I am not sure to understand 100%, what bricks you want to place and where? Also are you in the latest experimental there was a bug for flat brick that have been fixed. Thanks

**Comment by Mellcor** [comment]
what you see in the pic is all the setup is, im trying to place the micro block studs (hotbar 5&6) on the half block, but i can not, however if i remove the rotor i am able to

**Comment by tsunamayo** [comment]
Okay I cant reproduce, what is your version ? In the menu it is written on the bottom right.

**Comment by Mellcor** [comment]
17w45a2

**Comment by CyaNox** [comment]
Can you test in 17w45b (Experimental branch) to see if it is fixed or not?

**Comment by Mellcor** [comment]
it is fixed on experimental

**Comment by CyaNox** [comment]
Then this is a duplicate of #391 and is fixed already.
