### ISSUE TITLE
[BUG/SUGGESTION] delay logic gate values

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#408]
currently the delay logic gate can not be set to a value higher than one, i dont know if it is intended or not, if it is i suggest that you allow it to be set higher otherwise players have to spam the block in order to get longer delays, if not intended you have thus been informed

**Comment by tsunamayo** [comment]
Hum I mark that as a bug as I want to have longer delay indeed. Thanks

**Comment by EthanNar** [comment]
I believe this is fixed.

**Comment by AfterRebelion** [comment]
The Timer Command brick can be set to any amount of seconds, so this issue is already fixed in recent versions (19w23b)
