### ISSUE TITLE
Invisible Blocks on ship, consistent

### ISSUE THREAD

**Issue by JLAMontoya** [tsunamayo/Skywanderers#409]
I saw the other "invisible blocks" bug report, but I believe this is different. I've been told I might've hit the block limit, so that might be the issue.

I'm placing stud blocks, mirrored once, and suddenly the group of blocks I'm working on turns invisible- I can still see the blue placement squares and the blocks still have collision. This is consistent- even relaunching the game from desktop does not solve the issue entirely. Even if some do reappear, not all of them do, and as soon as I start placing blocks again, they vanish.

![20171107233523_1](https://user-images.githubusercontent.com/13087952/32535941-23e8bafc-c42a-11e7-945c-7a9f7e434c9a.jpg)

**Comment by tsunamayo** [comment]
Yes you hit the bricks limit, you are using way to many bricks unfortunately, there are not made for what you are trying to do... There are larger brick to use if you want it to be less painful.

**Comment by CyaNox** [comment]
Duplicate of #312.
