### ISSUE TITLE
Keymap reversed - Hyperjump flying sideways

### ISSUE THREAD

**Issue by DutchWorkingMan** [tsunamayo/Skywanderers#410]
Pre-Alpha 17w45a2

Somehow the ship keys are reversed now and in a few cases I couldn't even change the keys. The example ship with the only working hyperdrive is flying sideways when activated. I think both problems are linked.

This is for keys Q and E, W and S.

**Comment by tsunamayo** [comment]
Thanks for reporting the bug.
Okay I need more info in order to reproduce, what ship are you using exactly? Did you updated the spaceship core?
Did you change the configuration (like adding a joystick for example)
What do you mean you couldn't change the keys?
Thanks

**Comment by Name11ess** [comment]
It happened to me using the `Corellian Shuttle2`.

**Comment by DutchWorkingMan** [comment]
It's not exactly easy to explain. It was changed the next day when I wanted to play. I thought that it was an update.
 
What I so far have done. I work on a big ship with three decks with a lot of doors button and other gimmicks that I'm trying out and was testing. Sometimes a function just stops working, like a second laser detection system. _Before that all I had changed the speed brackets to mouse button 1 and 2. Nothing special happens after that, but it doesn't work well while flying and need to push some buttons. At this point I haven't tested the joystick configuration, and haven't plugged in any joystick._ 

I started with small test ships, because somehow I don't get the hyperdrive working. That means I created a ship, tried out a few things that just didn't worked. Then I used the only working hyperdrive ship that you build. Activated hyperdrive. Checked the connections and even stripped the ship from all the blocks. Even removing the hyperdrive blocks and putting it back somewhere else and linking it with the navigation hologram. Why does it only work on that ship?
Left the game without saving, because I don't like stranded in nowhere space. _Leaving the game without saving is what I often do. Maybe that could have corrupted something?_

_After that I started the game yesterday and suddenly the keys where reversed with the avatar. I changed them. Then I found out that the ship keys where also reversed. Tried to change them but only the '><' happened and couldn't change it after that._ 

_Stopped playing and next day I checked it. The player keys where somehow correct again, but the ship keys where still reversed but I could change them now. Only the sideways flying in hyperspace hasn't changed._ 

_I saw that there where also files from a crash yesterday, probably from the moment that I couldn't change the keys anymore. I put them as an attachment. Maybe it has to do with that._ 

So, a lot of things were done, but I can't figure out what it has to do with, or if it is even to duplicate, unless it happens also to another player. I can only guess that it happened when I left the game unsaved, on the normal way via ESC.

[crash.rar.zip](https://github.com/tsunamayo/Skywanderers/files/1453450/crash.rar.zip)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1453404/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1453405/output_log.txt)

**Comment by DutchWorkingMan** [comment]
Update:

Found out how to get the Banshee working.

Hyperdrive Bansee: flying backwards.
Hyperdrive Correlian Shuttle3: flying sidewards.

Deleted all the savefiles and reinstalled game, and created new character. The reversed problem is gone, but strangely enough not the problem with the hyperdrive!

Tried it with a joystick, but still no change.

**Comment by tsunamayo** [comment]
When you say hyperdrive, are you referring to interstellar jump or the Hyper mode when flying? Thanks

**Comment by DutchWorkingMan** [comment]
Interstellar jump. 

Sorry for the mistake. The block that is used for Interstellar jump is called Hyperdrive, that creates some confusion.

**Comment by tsunamayo** [comment]
Okay, I made some change to the spaceship core flying direction, it should be fixed now, if not please tell me (I wasnt able to reproduce your issue) Cheers
