### ISSUE TITLE
Weapon Units only fire every second mouse click

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#411]
As title, place down the Laser brick weapon (or beam unit) and mouse click. It will fire 1x. Mouse click again and you will find that the weapon doesnt activate again. Pressing for the 3rd time will cause it to fire.

Not sure if intended behaviour or not, hence reporting.

Behaviour is as normal with each click firing the weapon when using logic link/mouse button hotkey

**Comment by tsunamayo** [comment]
Hi, yes it is somewhat normal: when you activate something with the mouse you will send 1 then 0, so you can flip flop hinge, slider without a button at first. Laser will only fire with 1 as input, so you have the reason... I might change it at one point though, and make it a bit smarter. Thanks

**Comment by Napther** [comment]
Odd, could have sworn this wasnt the behaviour before. I'd have known sluggish activation of the lasers because it was the ONLY way I could fire them before 14w45b...
