### ISSUE TITLE
Using weapons to break blocks on an entity checks through the Mirror Plane

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#412]
![image](https://user-images.githubusercontent.com/33023316/32550635-cb7e18a6-c485-11e7-9546-2a737ad71537.png)

![image](https://user-images.githubusercontent.com/33023316/32550653-d9bb3e1c-c485-11e7-8e6e-5e49595bd539.png)

![image](https://user-images.githubusercontent.com/33023316/32550648-d3eb9d7e-c485-11e7-9bb6-e9f381e768d0.png)

The weapons made 4 blocks destroyed on the right side of the image. The mirror plane just visible behind the identity block on the ahead ship made the weapon destroy the 4 blocks on the LEFT side of the ship as you view it.

**Comment by tsunamayo** [comment]
Okay I guess you mean it is a behaviour you would not like to see? I agree with that, and there will be a blueprint / instance save refactoring to accommodate to that. Build being made by the player will be committed to the blueprint while damage would not, hence allowing for automatic repairs of several sort (auto, at station, repair ship coming on distress signal activation ect) Thanks

**Comment by Napther** [comment]
Yeah, definitely not having weapons effected by the mirror would mean that if someone left a mirror in their ship later down the line, they arent taking double damage from nowhere, etc.

**Comment by tsunamayo** [comment]
Okay it is now fixed with the new block HP update. Cheers
