### ISSUE TITLE
Ship ignoring thrust keybinds entirely

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#413]
![image](https://user-images.githubusercontent.com/33023316/32550901-a7c7168c-c486-11e7-96d4-53185d4d3b22.png)

With this set of keybinds, the ship in STD mode does not move forwards.

Changing binds to this also does not make the ship move forwards in STD mode
![image](https://user-images.githubusercontent.com/33023316/32550971-dd73238e-c486-11e7-8722-7f26de9d59e9.png)

I have not found a working combination.

**Comment by tsunamayo** [comment]
Hi, could you please send me your SETTINGS.ini in
C:\Users\[USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers
Thanks

**Comment by tsunamayo** [comment]
Ok nevermind I had a look at it and fixed it. One temporary fix will be to assign the same key as the Alternate keybind, while waiting for next build. Thanks a lot for being on the ball!
