### ISSUE TITLE
Add more options for glass blocks

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#414]
Currently we are pretty limited by the types of clear blocks we have. I would personally like to see a wider variety of shapes, kind of like the ones we have for hull blocks. I.E; individual blocks to make tetras, rather than having premade tetras.

**Comment by CyaNox** [comment]
Probably a duplicate of #384 since it does show all the missing blocks for the glass blocks as well.

**Comment by SkellyBard** [comment]
Thanks for pointing that out!
