### ISSUE TITLE
High memory stack

### ISSUE THREAD

**Issue by kayupla** [tsunamayo/Skywanderers#415]
hi, 

since the last update , but i can't be 100% sure this produce only since that time, i encounter a high RAM usage. 
after 1 or 2 hours playing, skywanderers take over 7.5 giga of RAM. 
I am in the asteroid ring near the Torus ring ( starting point).
here is my  output log
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1455168/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for reporting this. Regarding your position, are you on the torus itself, or are you on the asteroids? Did you moved a lot during your play session, or did you stayed at the same place. Thanks!

**Comment by kayupla** [comment]
i'am playing in the asteroid field in the ring of the blue planet . i didn't move , just building some ships around.

**Comment by tsunamayo** [comment]
Card below spec... Thanks

**Comment by tsunamayo** [comment]
Okay this issue is very old - I am not sure if you played recently and had issue again. If yes please tell me! Cheers
