### ISSUE TITLE
Unable to select monitor to Boot on in full screen

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#417]
Now that the unity launcher is no longer used to boot the game, I can't seem to get the game to swap to my secondary monitor, adding the option in would be great. :D

**Comment by tsunamayo** [comment]
I see, thanks for pointing that out I will add this back! Sorry for the inconvenience in the meantime. Thanks

**Comment by AfterRebelion** [comment]
You can change to windowed, change to the secondary monitor, and go back to fullscreen, and it will stay on the secondary monitor, so this issue is mostly fixed in recent versions (19w23b)
