### ISSUE TITLE
Can place/remove blocks on hidden hotbars

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#421]
Very peculiar, I have only managed to get it to swap onto the hotbar below by dragging the item BELOW the active hotbar, only managed to test thus far on slot 2 and 6:
![image](https://user-images.githubusercontent.com/33023316/32655117-379b3c9c-c604-11e7-9efd-3a6869bdc5ea.png)

![image](https://user-images.githubusercontent.com/33023316/32655074-03450798-c604-11e7-94ff-fca033043f7d.png)

![image](https://user-images.githubusercontent.com/33023316/32655094-146b60e4-c604-11e7-9b67-dab9b2aded0c.png)

I think there needs to be a clause that locks those hidden hotbars, you have to be VERY pixel-accurate to get it to work. Might be different for those with different screen resolutions and GPU size

**Comment by tsunamayo** [comment]
Interesting test case indeed, as I increased the clipping zone to display the text I think now slot collider are a slightly accessible. I will fix that! Thanks

**Comment by EthanNar** [comment]
Having the same issue.

**Comment by tsunamayo** [comment]
Hi, this issue should now be fixed. Thanks!
