### ISSUE TITLE
Pressing CTRL to drag blocks when the cursor is "out of bounds" completely cancels block placement

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#423]
![image](https://user-images.githubusercontent.com/33023316/32672162-ee23a16a-c641-11e7-8991-3c6d1bbd9248.png)
 When placing a block, it disappears when you stray too far, essentially allowing you to cancell it.
However, returning will allow you to place it again: Unless you hit control key before then

![image](https://user-images.githubusercontent.com/33023316/32672192-0fec968a-c642-11e7-83d0-4c8eb2547975.png)

**Comment by tsunamayo** [comment]
Thanks, it is now fixed. Cheers
