### ISSUE TITLE
Data screens show incorrect angles for hinges (17w45a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#424]
When connected to a hinge, data screens are treating their movement range as a value from 0 to 360 degrees, regardless of the hinge's actual movement range. Closed hinges properly display as 0 degrees, but fully open hinges are displayed as 360 degrees (instead of the expected 90 or 270, depending on which hinge is used). 
Example: https://youtu.be/y-zeGLlRB8M

**Comment by tsunamayo** [comment]
Ah yes indeed, thanks I will fix it. Cheers!

**Comment by tsunamayo** [comment]
Okay issues is fixed. Thanks!
