### ISSUE TITLE
[Visual] Vertical line in data screen texture when using darker colors (17w45a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#425]
There is a faint vertical line running through the middle of data screens when a darker color is applied to them. The color black was used in the picture below:
![20171110183937_1](https://user-images.githubusercontent.com/33088776/32683086-984e1892-c646-11e7-8636-79363fcd9fad.jpg)

**Comment by tsunamayo** [comment]
Yes it is something I noticed also in a few other instances, it is due to the glow is processes in the game. Will work on that, but not on the short term. Thanks!

**Comment by AfterRebelion** [comment]
Screens have new models and textures, so this issue is no longer valid in recent versions (19w23b)
