### ISSUE TITLE
Odd behaviour when "cancelling" dragging items off the hotbar

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#426]
Very low priority bug I'd say:

![image](https://user-images.githubusercontent.com/33023316/32689180-972c1f90-c6d7-11e7-8f9c-ca757664cfd1.png)
![image](https://user-images.githubusercontent.com/33023316/32689184-a3853308-c6d7-11e7-9911-d5bea4aa6697.png)
![image](https://user-images.githubusercontent.com/33023316/32689187-a963219a-c6d7-11e7-90a9-7f7e13581971.png)
![image](https://user-images.githubusercontent.com/33023316/32689192-b4f2d564-c6d7-11e7-802f-f1d086974474.png)
![image](https://user-images.githubusercontent.com/33023316/32689204-deb5fa5c-c6d7-11e7-8816-ad5378311295.png)

When dragging something and then cancelling with the Escape menu, the hotbar will have an empty slot appear. However sometimes it will stay empty, other times the block that was drag-cancelled will reappear in the now-empty slot beside where it was when the character starts taking actions. 17w45b

**Comment by tsunamayo** [comment]
Thanks for noticing that one. Low priority but easy fix nonetheless, so it is now fixed ;-) Cheers
