### ISSUE TITLE
Beam Block resultant Vector incorrect

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#427]
![image](https://user-images.githubusercontent.com/33023316/32689590-87d4b932-c6df-11e7-8be8-90882d8c57cf.png)

While doing some tests to try and help someone on the Discord, I found that 17w45b has the beam resultant vectors incorrect. The image shows 4 mirrored beams (top/bottom left/right), and firing just the left side to get convergence on themselves. Even though the values for both beam focus are identical, the exit angle only corresponds to the entry angle of one of the beam lasers, or one of them is receiving far higher priority over the other.

**Comment by tsunamayo** [comment]
Hi, issue is now fixed. Thanks!
