### ISSUE TITLE
Game Crashes upon Launch

### ISSUE THREAD

**Issue by Jump-Suit** [tsunamayo/Skywanderers#428]
My game can't load the 2d textures, it then restarts again to try a 2nd time and fails then errors. I will have a log attached for info to fix please asap
[error.log](https://github.com/tsunamayo/Skywanderers/files/1464377/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1464378/output_log.txt)

**Comment by CaptainCJH** [comment]
If you have an Nvidia GPU, you may try doing a clean driver install (select custom install then check clean install). I found the latest versions 3.88 seem to not install properly for Win 7 and 10. Other games may run ok just not Skywanderers.. I have also found that if the game crashes in game, it then crashes on startup. When I do a total reboot it loads ok. This may have something to do with something persisting I think in the GPU memory.

**Comment by tsunamayo** [comment]
Hi, sorry to hear that, could you first make sure that your GFX driver are up to date? What operating system are you using? Thanks

**Comment by tsunamayo** [comment]
Card below spec... Thanks
