### ISSUE TITLE
Mouse Wheel Unbound and Has no Binding Options

### ISSUE THREAD

**Issue by Tourist50** [tsunamayo/Skywanderers#429]
I use the mouse wheel a lot for changing hotbars in the inventory, but recently that seems to have unbound itself. I tried looking in "Controls" to see if I could rebind it, but it doesn't seem to have a binding option.

**Comment by CyaNox** [comment]
Are you holding `SHIFT` while scrolling?

(related: A change of behavior coming from: #297)

**Comment by tsunamayo** [comment]
Hello, yes I changed it to SHIFT scroll to be  coherent with in-game. Now you can scroll down the codex instead with the mouse wheel. Thanks
