### ISSUE TITLE
Issues when interacting with deleted ships.

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#430]
When in experimental mode, it can take a few seconds to unload then reload a BP form an identity block. When interacting with the "deleted" ship (even though it still appears for a few seconds after deletion) such as sitting in the seat, can cause the player to be stuck in the seat after the vessel has been fully removed.

**Comment by tsunamayo** [comment]
Thanks, I made some change to the delete process, now the entity is hidden a bit before the deletion, so it should no longer be possible. Cheers!
