### ISSUE TITLE
drive + and drive - no longer working

### ISSUE THREAD

**Issue by comwilson** [tsunamayo/Skywanderers#431]
I've tried a fresh install of the game with removing all data from AppData and steam directory. I've also tried remapping the function to different keys. Nothing seems to work.

**Comment by Tomatart** [comment]
Can confirm i also have this issue. you have to spam click the keys in order to increase or decrease speed, and remapping does not work for drive + and dive - .

**Comment by tsunamayo** [comment]
Okay guys, could you please tell me:
Your version
The mapping you use for primary and secondary
Thanks!

**Comment by comwilson** [comment]
Version: 17w45b

It turns out that it's just the primary keys mapped that don't work. Currently I have it set to [ and ], but I tried with ',' and '.' and others and nothing worked. However, the secondary key mappings do work.

**Comment by tsunamayo** [comment]
Yes this is fixed in experimental 17w45c (already available). You can simply assigned a second command for the time being. Thanks!
