### ISSUE TITLE
Blueprints don't save properly after a while

### ISSUE THREAD

**Issue by Tankman95** [tsunamayo/Skywanderers#432]
It seems that after a while a blueprint file can't be overwritten again, eventhough the game shows the saving icon.
Workaround: You need to save the ship under a new blueprint name in order to save your progress.

Several players confirmed that bug happening

**Comment by tsunamayo** [comment]
Hello, thanks it is indeed a bad issue. Could you please tell me more about it? You mention the saving icon, does it stay up a long time? Could you please send me this given blueprint? Also when you exit and come back into the game, are you able to save the blueprint again? Thanks

**Comment by Tankman95** [comment]
The save icon stays up for around one second, so apparently the game does save something.
Also no, restarting the game doesn't fix it. It seems like the blueprint file got corrupted in some way.
I don't have the blueprint file anymore, because I wiped my saves and re-installed the game :/

**Comment by tsunamayo** [comment]
Okay, did you cleared this directory also? 
C:\Users\[USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\PlayerEntities

Thanks

**Comment by Tankman95** [comment]
Yes, I've cleared that directory aswell

**Comment by tsunamayo** [comment]
Issue should be deprecated. Thanks!
