### ISSUE TITLE
[Experimental] [Bug] Mousewheel scroll for toolbar reversed in tab menu [17w45c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#433]
While in-game, holding Shift and scrolling the mousewheel down moves the toolbar in normal order (1,2,3,4). However, when the Tab menu is open, holding Shift and scrolling the mousewheel moves the toolbar in reverse order (4,3,2,1).

**Comment by tsunamayo** [comment]
Thanks for noticing that one! It is now fixed. Cheers!
