### ISSUE TITLE
Pick block and pick color behavior unexpected when all hotbars are full

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#434]
While trying to pick colors or blocks that are not in any of the 4 hotbars while all 4 hotbars are completely filled nothing will happen.

When asking to pick a block I'd rather have it override my currently active slot instead of doing nothing.

In the video below I scroll through my hotbar to show they are all full followed by trying to pick colors but it fails to pick the colors:

https://youtu.be/pyrbJh2g5ts

This is particularly annoying when working with a color palette like: 
![2017-11-13-02-30-17](https://user-images.githubusercontent.com/211381/32706257-4a418062-c81c-11e7-85c3-b3c6438f1cd5.png)

Blueprint: [Noxys Color Wheel.zip](https://github.com/tsunamayo/Skywanderers/files/1465328/Noxys.Color.Wheel.zip)

**Comment by Napther** [comment]
Aaah, you beat me to it! I was too sleepy to suggest that it Overwrites the active slot with the block, this means I can replace the common blocks on my hotbar and then Pick-Block them when needed.

IOtherwise there is a LOT of hotbar management in this game when building a hull due to lack of Multislot

**Comment by tsunamayo** [comment]
Okay I agree, I will update this. Also yes I want to add some kind of family shape where you get all 5 shapes of a block to limit hotbar management. Not sure exactly what it will look like if you want to suggest something go ahead. This will also be important for survival, so you dont need to craft many different shape, you will be able to simply craft and store a family of block.

**Comment by CyaNox** [comment]
I'm not sure what method Skywanderers should follow. 

I do know that Starmade's multislot method is very awkward and not that good. If you have a multislot block in your hotbar scrolling will scroll through all variations first before going to the next slot in the hotbar. This becomes cumbersome when you want to scroll from slot 5 to 1 and having to go through 32 slots just to move 4 slots. Starmade also has a wheel kind of thing that is even more cumbersome to use because it has 8 shapes in its multi slot block and the 4 cardinal directions are in between choices and you have to click before it selects:
![kuupmfj](https://user-images.githubusercontent.com/211381/32841943-1c364732-ca1c-11e7-91f3-02b916d63efe.png)

Space Engineers does it better where you need to hold a modifier key to scroll through the variations of a multislot block. (Space engineers also allows you to go directly to specific hotbars with `ctrl+number` (it also has 9 hotbars instead of 4)).

Beyond this I don't know many other games that have multislot blocks.

**Comment by Napther** [comment]
Remember Starmade doesn't have discrete hull sets. In fact it has far more types of hull than Skywanderers due to basic. Standard and Advanced of all the colours. Starmade also only has 1 active build hot bar and Skywanderers has 4. 
Also starmade is worse as you can add the 3 slabs to the multi slot too. A total of 8 blocks to scroll through to get past them

**Comment by AfterRebelion** [comment]
This is still an issue in the current version (19w23b)

**Comment by tsunamayo** [comment]
Okay I will have a look at it. Cheers

**Comment by tsunamayo** [comment]
Okay I finally fixed this issue... (Will be in 19w31a). For the multi slot I wont go in that direction though, as with the new scaling tech and paint the shape creeping is more limited. Cheers
