### ISSUE TITLE
Collision box of bricks/character issue

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#436]
Build: pre-alpha 17w45b

The bounding box of bricks (or character) seems out of line with the actual character size. With no bricks, a character can pass through a 1x2 space. In this example, the space is 2x2 with a edge of bricks to spruce it up. However, despite appearing as though the character should fit... he gets stuck:

![20171112211415_1](https://user-images.githubusercontent.com/33043997/32706941-8c58175a-c7ee-11e7-925e-37084f079a90.jpg)

**Comment by tsunamayo** [comment]
Hi, character capsule size seems right to me, maybe it is linked to the shape of your entry. Could you please send me the blueprint so I can check it more deeper? Thanks!

![unity 2017-11-14 09-57-58-95](https://user-images.githubusercontent.com/6604318/32757359-7f3a3b72-c922-11e7-89f4-e3971da04ce8.png)

**Comment by Rizzo911** [comment]
[Resolute v.1.swbp.zip](https://github.com/tsunamayo/Skywanderers/files/1473180/Resolute.v.1.swbp.zip)

**Comment by Rizzo911** [comment]
Hi Tsuna,
I've attached the work in progress ship. I can occasionally get through the door wriggling a lot now, but it still feels like the character model should be able to walk right though. The doors in question are the round airlock doors on each side (either between the red or green lights depending on what side you are on). Thanks for looking!

**Comment by tsunamayo** [comment]
Thanks mate you where 100% right there was an issue with bricks - it is now fixed. Thanks for point this out, and nice ship btw ;-) ! Cheers
