### ISSUE TITLE
Certain faces not visible for some blocks

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#437]
All of the blocks in the image below have missing faces (usually on their bottom):
![2017-11-13-03-15-19](https://user-images.githubusercontent.com/211381/32706993-3cecfc20-c821-11e7-9018-bd62affb3f8e.png)

Below a screenshot from the other side showing all kinds of missing faces:

![2017-11-13-03-19-17](https://user-images.githubusercontent.com/211381/32707015-65c8af22-c821-11e7-91a3-af021aa77ed9.png)

Blueprint of the above: [Bug Invisible Faces.zip](https://github.com/tsunamayo/Skywanderers/files/1465401/Bug.Invisible.Faces.zip)

When loading the blueprint some of the faces that appear invisible in the screenshot may not be invisible when just loaded. To reproduce those you'll have to place the blocks yourself and remove their supporting block to see the missing faces.

**Comment by tsunamayo** [comment]
Thanks, yes indeed this is something I need to fix.

**Comment by AfterRebelion** [comment]
The shown blocks are no longer avaliable in this form on the game, so this issue is no longer valid in recent versions (19w23b)
