### ISSUE TITLE
Scrolling too slow in Blocks Codex

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#439]
While scrolling in the blocks codex is now possible it is arguably slow. I was expecting a single scroll tick to scroll as much as 1 entire row of items instead it scrolls a very minute amount of pixels

The video below show me scrolling in 1 tick intervals and ... well me scrolling using the bar:
https://youtu.be/zJN3dZn65mw

As it is right now it is too slow to be useful and I generally still move my mouse over to the bar on the side instead of using my scroll wheel.

**Comment by tsunamayo** [comment]
Yes it is more fidly to make it work due to GUI plugin I am using, on my side it is much faster btw. I will improve it, now it is useless indeed in yoru case. Thanks

**Comment by tsunamayo** [comment]
Okay I made some change, it should be better now, tell me if that works for you in next update (17w46a) Cheers
