### ISSUE TITLE
[Experimental] [Bug] F11 function persists in Tab menu after turned off [17w45c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#440]
If the F11 key is pressed, and the Tab menu is opened, and then the F11 effect is turned off, the textureless effect persists on some icons after the effect is turned off, even after the Tab menu is closed and reopened.

![20171112212817_1](https://user-images.githubusercontent.com/33041786/32708661-db266dee-c7f0-11e7-8c81-0d91a414131d.jpg)

**Comment by tsunamayo** [comment]
Okay it make sense actually - this will be low priority as this a debug feature more for me when I am working on the game, hence I will also move it from F11 key. Thanks

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
