### ISSUE TITLE
Various blocks can be clicked through

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#441]
Various blocks can be clicked through and cause actions to blocks not in sight.

Video demonstrating the clicking through: https://youtu.be/z1D8_HCJyrI

Screenshot of the test case: ![2017-11-13-04-41-22](https://user-images.githubusercontent.com/211381/32708895-31081bcc-c82d-11e7-9cb0-cb82db9f4dca.png)

Blueprint of the test case: [Bug Clicking Through Blocks.zip](https://github.com/tsunamayo/Skywanderers/files/1465547/Bug.Clicking.Through.Blocks.zip)

**Comment by tsunamayo** [comment]
Thanks a lot for the super helpful testcase, I think the pattern here is enter block in front of other system (could work the other way around). I will fix it! Thanks

**Comment by tsunamayo** [comment]
Okay it is now fixed! Thanks as always!
