### ISSUE TITLE
Holo text orientation incorrect on child entities or on ceilings

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#442]
It seems that the holo text has incorrect orientations when on child entities especially those that are rotated. 

Pretty much all red buttons have incorrect orientations of their holo text:

![2017-11-13-05-08-45](https://user-images.githubusercontent.com/211381/32709465-ec8c188c-c830-11e7-9afc-829d3a1cc942.png)
![2017-11-13-05-13-34](https://user-images.githubusercontent.com/211381/32709531-608fe042-c831-11e7-8e37-bdc9f5c56e26.png)

Since you can't see more than one holo text at the same time I highly recommend checking the blueprint below.

The holo text is also completely wrong when the buttons are placed on a ceiling:

![2017-11-13-05-09-18](https://user-images.githubusercontent.com/211381/32709468-ee091af2-c830-11e7-983f-609f8773eb79.png)

[Bug Holo Text Orientation Wrong.zip](https://github.com/tsunamayo/Skywanderers/files/1465573/Bug.Holo.Text.Orientation.Wrong.zip)

**Comment by tsunamayo** [comment]
Yes it tricky to make it work, and tbh I will remove the feature in its current implementation.
I will move the text indication by default to the 2D gui, but I will also provide a holotext brick for when you really want an holo display. 
I think having a holo text is not always great, for example cockpit with a lot of button. And sometime people might want a text holo without it to appears or disappear on over. 
Thanks!
