### ISSUE TITLE
Visual bug with text screen rendering

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#443]
While building my color wheel I noticed a color oddity with the rendering of darker text on the screens:

Below an image at one angle and one at a slightly different angle but with a drastically different color:
![2017-11-13-05-55-27](https://user-images.githubusercontent.com/211381/32710290-48d0a33c-c837-11e7-9ab3-0607d828b6b3.png)
![2017-11-13-05-55-33](https://user-images.githubusercontent.com/211381/32710296-4c88c23e-c837-11e7-8746-334e3fda834e.png)

The top most screenshot is the correct color as I used pure black for the text.

Blueprint of test case: [Bug Text Visual Oddities.zip](https://github.com/tsunamayo/Skywanderers/files/1465642/Bug.Text.Visual.Oddities.zip)

**Comment by tsunamayo** [comment]
Okay I had a look at it is just the standard issue of z-sorting on transparent materials. It is always gonna be an issue in a game where it is the player who create the geometry, so I will leave it like that, maybe one day I will do something much more refined for transparency but not on the short term unfortunately ... Thanks!
