### ISSUE TITLE
[Suggestion] Please add a block to fit here

### ISSUE THREAD

**Issue by Piston1937** [tsunamayo/Skywanderers#444]
![screenshot 2017-11-13 16 51 21](https://user-images.githubusercontent.com/33643293/32757381-12464f30-c894-11e7-8b19-ae5f9300adef.png)

Please add a block or two that will fit there.

**Comment by Tomatart** [comment]
This would be amazing

**Comment by tsunamayo** [comment]
Hi, yes of course there is a need for an exponential number of shape to fit every configuration. To stop this endless rise of the number of block I plan to create a magic free form block (tentative), where you can drag face / edge / vertex to conform to the shape you want. I close this as it is planned on the roadmap - and I will keep you posted. Thanks!
