### ISSUE TITLE
[Unexpected feature] Ringworld spawns nearby whenever I load up the game after travelling to a system

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#447]
I just loaded into a world after giving myself a break from the game, and when I load in, a new ring is spawned in nearby. I did this in another system as well and it did the exact same thing. I am currently running on the latest experimental version.

![20171115222355_1](https://user-images.githubusercontent.com/28989460/32873853-04ab6a7e-ca54-11e7-8f57-1a4fca62136a.jpg)

**Comment by tsunamayo** [comment]
Hi, could you please zip me the content of C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
and send it to me? Thanks!

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
