### ISSUE TITLE
Ver 17w45b [Glitch] Phasing through blocks when Holding the Down key and placing blocks.

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#449]
This is possibly a duplicate report here, but I have found if I stand on a construct and hold down the down/crouch key then place I block I phase through the floor this happens 100% of the time I try it.

**Comment by tsunamayo** [comment]
Yes indeed nice spotting, I think it happens when you place the block close to you in a colliding position with the character capsule. Will keep you posted, thanks!

**Comment by tsunamayo** [comment]
Okay now the new behaviour is that you cant place the block if you potentially collide with it, like in Minecraft. If it is the case the build preview will turn red. Cheers!
