### ISSUE TITLE
Aiming at triangle stickers 

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#450]
When aiming at a block underneath a triangle sticker it paints the sticker not the block under it, even tho the block under it is the selected block. Version 17w45c

**Comment by tsunamayo** [comment]
Hi Tom, yes this is a limitation of the current system. The good news is I just switched the game to deferred rendering, which means that now I am gonna be able to create much better stickers, so this will be fixed in the future. Thanks!

**Comment by AfterRebelion** [comment]
This is no longer an issue in recent versions (19w23b)
