### ISSUE TITLE
[BUG] Relay Gate with Logic (AND/OR) circuit can cause short circuit and crash the client.

### ISSUE THREAD

**Issue by jamesleonis** [tsunamayo/Skywanderers#452]
The short circuit detection logic prevents most circular spamming of packets in a logic circuit. However, with clever settings of logic gate attached to a Relay can allow the relay to connect back to one of the logic gate inputs. [I've attached an album of images of various gates and their inputs (marked with switches) and how the relay responds.](https://imgur.com/a/m5Gdq) Note that this does not itself crash the client.

However, the circular nature of the circuit can cause it to self-spam infinitely, and triggers when the conditions of the circuit align. Because the circuit needs to be triggered first, the player might not experience a crash until much later.

Client: 17w45b

Steps to reproduce:

1. [Build this AND-Relay circuit.](https://i.imgur.com/5nwNZGj.jpg)
2. Set both inputs to 1
3. Get popcorn as client drops to a crawl.
4. Witness crash.
5. ???
6. PROFIT!

Suggestions for the fix:

1. Timing. It seems like the logic gates run at full tilt of the host computer. Introducing a small sleep would likely prevent a client slowdown and crash.
2. Investigate Minecraft's Redstone short-circuit logic. Redstone is not immune to short circuits. It explicitly allows them. However too many changes in a given time frame causes the particular circuit to "fizzle" and stop working. The fizzle indicates the problematic part of the circuit, and the block is prevented from spamming itself infinitely.

**Comment by tsunamayo** [comment]
Hi, thanks for the detailed case, indeed this is a weak area of the current logic state, I need to improve that side. I will look at it and keep you posted. Are you an experience Red stone builder? (it look like so). Cheers

**Comment by tsunamayo** [comment]
There is now a slight delay in system call back (equivalent to the old relay command) that should prevent this. Thanks!
