### ISSUE TITLE
Custom Color Issues

### ISSUE THREAD

**Issue by AlexJHockley** [tsunamayo/Skywanderers#455]
I have run into a number of issues with custom paints, and two quick suggestions for them. I will split these up to make them easier to read.

### 1 - Changing certain block colours between custom paint's mixes or resets colour to the default custom paint value
Okay, my wording here is awful. Let's say I have custom paint 1 and 2. Custom paint 1, when the game starts for the first time, is red, and custom paint 2 is green. Say I paint a hose (or another block, like a light, that exhibits the same behaviour) with custom paint 1. Then, I change the colour of custom paint 2 to blue, and paint the hose custom paint 2. This hose should be blue, but instead it defaults to the colour it started off as, which was green.

If you need me to explain this better I am happy to give it another shot.

### 2 - Weapon blocks do not update
When a weapon block is painted a custom colour, it acts the same as above. It's visual colour will be the custom paint value, but it's firing effect will be the DEFAULT colour of that custom paint.

![image](https://user-images.githubusercontent.com/20553073/32987885-403c2500-cd5c-11e7-8994-8dffbf85282d.png)

### 3 - Lights, hoses, etc, do not update.
I was going to mention issues with custom paints not changing light blocks, hoses, etc, but that issue has been posted before https://github.com/tsunamayo/Skywanderers/issues/129
It should not noted that not ALL light emitting blocks do this. As far as I can tell, engines do change colour, but I could be wrong or not noticing light changes.

### 4 - Picking a colour from a block does not update to match custom colour
This effect is the same as #1 and #2, basically the colour you can select from the colour wheel does not display the colour of the block currently, nor the colour of the custom paint currently, but instead shows you the default value.

![image](https://user-images.githubusercontent.com/20553073/32987928-5ebb4e92-cd5d-11e7-826e-7eedb0480edf.png)

### Overall
These bugs are mostly in the same value, excluding issue 3 which is described elsewhere. Updating a custom colour does not update references to it in the quick access bar, or the firing / lighting colours methods. 

I could have summed this up much faster but felt extra detail would help. I have also attached my game log if that helps.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1485329/output_log.txt)

## Suggestions
Some quick suggestions to make the colour selection process faster. These are excluding changes that may happen based on the paint tool.

### 1 - Tab selection in custom colour menu
It would be easier if I could select one of the number values for RGB (Say red), and then press "Tab" to move to the one after (move from red to green), if that makes sense.  Would make it faster to change the colours.

### 2 - Copy colours within the custom paint menu
If there was an option to change custom colours by copying other custom colours, or even by using the default colour values given in the paints menu, that would make things slightly more streamlined. This could be done using a colour palette type display, or dragging and dropping colours, or a copy paste button set.

Sorry for dumping this info all in one place, but I did not want to clog up the issue log :)

**Comment by tsunamayo** [comment]
Thanks a lot for the detailed case, yes indeed custom color are not yet working with prefab, like weapon or even light. I will definitely correct it in the future when I have the time! Thanks

**Comment by tsunamayo** [comment]
Custom paint are a still a big pain, I am gonna have to get rid of them... Cheers

**Comment by tsunamayo** [comment]
Okay now custom color are dead, that was actually too complex to make everything works. Thanks
