### ISSUE TITLE
Ship Alignment Bug

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#456]
When you align to a ship, if you look around, the alignment will warp in some weird way, kind of like its following the cursor. Here's a video of the glitch: https://youtu.be/dDAnXSm4A6Y

The glitch happened after I placed a teleport block on a rotated object, teleported to it, then reset my alignment to the regular position of the ship.

**Comment by tsunamayo** [comment]
Hum weird I will try to reproduce and keep you posted. Do you manage to reproduce  that 100% on the time ? Thanks

**Comment by SkellyBard** [comment]
I haven't been able to reproduce the bug after restarting my PC, I will keep trying with different methods and see how it goes.

**Comment by JRL101** [comment]
I cant tell what causes this, it happens sometimes when i float below my build, i assume we're auto aligning to the habitat ring some how. but it's not consistent enough to be able to tell what it is, its a very slight tilt most of the time too.

**Comment by tsunamayo** [comment]
In fact I think it is the player that is slightly moving. I havent time to look at it, but will def do. Cheers

**Comment by tsunamayo** [comment]
Alignment tech is now different, this issue is deprecated. Thanks
