### ISSUE TITLE
[suggestion] New character models for future versions

### ISSUE THREAD

**Issue by probka** [tsunamayo/Skywanderers#457]
trying to develop some character system 
![coat1](https://user-images.githubusercontent.com/16438515/33009674-40a74914-cde0-11e7-8bec-6aa035710ada.gif)
![coat2](https://user-images.githubusercontent.com/16438515/33009676-426ecb8c-cde0-11e7-88b9-985fa6699e35.gif)
![coat3](https://user-images.githubusercontent.com/16438515/33009678-43d94e2a-cde0-11e7-90f6-bcafadbf2017.gif)
![scaf1](https://user-images.githubusercontent.com/16438515/33009685-46ff9fe6-cde0-11e7-9758-123e3c320482.gif)
![scaf2](https://user-images.githubusercontent.com/16438515/33009686-489c78d8-cde0-11e7-92a3-1a3fa2e214f3.gif)
![scaf3](https://user-images.githubusercontent.com/16438515/33009687-4ab8308a-cde0-11e7-821a-e45936d2a35b.gif)
![pilot](https://user-images.githubusercontent.com/16438515/33009691-4ca4b864-cde0-11e7-95a5-4244a83b407b.gif)
![pilot1](https://user-images.githubusercontent.com/16438515/33009694-4df1ccd4-cde0-11e7-961f-e905cce02aff.gif)

can do full pipeline including unity animator, constraining, etc
as model itself as mapping/texturing is not even preproduction. It was created fastly just for preview. Any feedback for mesh, style, resolution, animations, attachments will be improved. All mapping will be reworked to avoid pixel stairs and systemized for fractioning, stencils, bodyforming (fatness, aliennes). 

good to have feedback and agreement for further dev (for free of course;)

**Comment by tsunamayo** [comment]
Amazing! Did you made the animation yourself also? Do you have any portfolio? Cheers

**Comment by probka** [comment]
thanks! I did all stuff)
i am tech artist at wargaming and dont have good portfolio for show. I do actually designs and implementations of mechanics with game engines. But here is some animations i did for myself
https://www.dropbox.com/s/0day1mu6oc4a8l5/s1.gif?dl=0
https://www.dropbox.com/s/qanqhmhufmy537i/s2.gif?dl=0
https://www.dropbox.com/s/a0jyc4pkcbfxbey/s3.gif?dl=0
https://www.dropbox.com/s/4vps4kaal2sftfg/s4.gif?dl=0
https://www.dropbox.com/s/6gbbf4kc3c8ol9p/s5.gif?dl=0

**Comment by Balibalou** [comment]
really nice !

**Comment by Napther** [comment]
Pretty damned neat models right there. I am surprised you "specialise" in Unity when the Wargaming company use a lot of the BigPoint software? Unless the tank and ship models are tested in Unity first before going onto the main game engine... either way, great work. Be nice to see a voxel game that has characters that are more like these. Minecraft was good for its "Universal" application with skins, compared to Starmade's horrible-to-skin for beginner's model with odd bendy shoulders...

**Comment by probka** [comment]
Napther, i completely share Ur oppinion to have easy-skinning character in a sandbox game so player can be absolutely indivitual and recognizeable. Ive been unhopely waited for game like this - neat, stylish, stable, unlimited. So my tasks are :
- simple and straight textures logically mapped. So player can do simple mouse swipes to have good skin
- stickers that can be placed on body or clothes
- body and head forming by few parameters: width, height, fittnes
- wearable cloth and armor system
- hardpoints for mobile stuff (backpacks, holsters, watches, headsets, etc)
- animation system for standart and additional movements

**Comment by tsunamayo** [comment]
Hi, sorry I wanted to come back on you early on that, but I have been busy with many things. I really love the proportions and the low-poly feel and you seems to be a very talented animator on top of that. I'd say the best thing at this point could be to simply do a test in game, to get a better feel for it - if that works for you. Thanks!

**Comment by tsunamayo** [comment]
We now have a new character look! Cheers
