### ISSUE TITLE
17w47a Mapped keys for vehicle movement not working

### ISSUE THREAD

**Issue by Surac** [tsunamayo/Skywanderers#459]
Regardless of what keys I mapped to be used for vehicle movment, the game still used the default keys W A S D E Q. I tried to use 1-9 on the Number keypad. I can map them. Game still uses default keys.
Mapping Numberblock 1-9 to character movement works as expected

**Comment by tsunamayo** [comment]
Hi, by vehicle you means spaceship, hovercraft or mechs? Or all of them? Thanks

**Comment by Surac** [comment]
I only tried mech and Hovercraft

**Comment by tsunamayo** [comment]
Okay I did the change for hovercraft indeed, and I improved a bit how the throttle works (now you can move slowly ...). For the mechs I put the player control by design - as it fit more. Thanks!
