### ISSUE TITLE
[Suggesstion] - Some blocks have more options than others

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#46]
When building out an area the Hull Tech block only has 5 options

![image](https://cloud.githubusercontent.com/assets/8591667/24108776/419c19c8-0d54-11e7-924c-e2aa6e200a6d.png)

What would be ideal, especially when working towards a smoother circle area is to have the additional blocks that the Hull Tiled block has also within the Hull Tech block and or all the other Square type blocks, this would remove the need to have separate block entities.

![image](https://cloud.githubusercontent.com/assets/8591667/24109037/14873f7a-0d55-11e7-935a-c20a9a09ec68.png)

Thoughts?

**Comment by gdarling** [comment]
Doh nevermind, kinda, I just noticed the mid size Hull Tech block had those entries

![image](https://cloud.githubusercontent.com/assets/8591667/24109111/4d7195ba-0d55-11e7-93dd-70fa021176de.png)

Would still like to have them all merged into one block entity vs 3 separate ones.

**Comment by tsunamayo** [comment]
Now we have freeform! Yay! Cheers
