### ISSUE TITLE
Lights on child entities do not emit any light

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#460]
Any lights on child entities do nothing:

![2017-11-20-10-39-43](https://user-images.githubusercontent.com/211381/33011746-2884d1c2-cddf-11e7-9d7f-7193a885ecb2.png)

Bluaprint: [Bug Lighting Child Entities.zip](https://github.com/tsunamayo/Skywanderers/files/1487103/Bug.Lighting.Child.Entities.zip)

**Comment by tsunamayo** [comment]
Hi, yes it is normal for now, I want to do some more optimization and check how it run on old config before I add children entity light back. Thanks
