### ISSUE TITLE
Sound keeps looping in some situations with the Sliding Brick

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#461]
When loading the following blueprint and activating the button the sound will continuously loop:

[Bug Continues Noise From Moving Parts.zip](https://github.com/tsunamayo/Skywanderers/files/1487238/Bug.Continues.Noise.From.Moving.Parts.zip)

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
