### ISSUE TITLE
Initial state of ship controls incorrect.

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#464]
When building a new ship the initial state is incorrect making the ship fly off at 50% thrust.

A video demonstration: https://youtu.be/48YZDXuYYag

In the video I create a new ship, activate the core and it immediately sets me off without me pressing any keys. I then stop and show that I have no controller/joystick at all and my keybinds should be fine.

(This might only happen if you've just started the game)

**Comment by Segdis** [comment]
I am having this bug on existing ships as well (version 17w47a) , and it keeps happening only on the first flight of each game session, regardless when the ship tested was actually built.

**Comment by tsunamayo** [comment]
Yes I will change the behaviour to reset the axis to -1 when using keys. Thanks

**Comment by tsunamayo** [comment]
Okay it is now forced to no thrust. Thanks!
