### ISSUE TITLE
17w45c Mirror bug with diagonal lights

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#465]
Hey tsuna, 

So just started using diagonal lights on my build and have discovered that there is a mirror issue with them, instead of mirroring the light the duplicate placed is a clone of the 1st.

Image below to show you what I mean.
https://steamuserimages-a.akamaihd.net/ugc/867369171930814222/5B6B0A498EE81D747AE2E023DF3AFEE887BCAFE2/

**Comment by tsunamayo** [comment]
Hi, thanks for reporting this. Issue is now fixed! Thanks
