### ISSUE TITLE
If I jump while moving very fast, I can't stop afterwards.

### ISSUE THREAD

**Issue by EthanNar** [tsunamayo/Skywanderers#466]
When at 100% throttle in hyper and warp, I cannot stop after I leave warp tunnel.

**Comment by CyaNox** [comment]
Are you slowing down with your hyperdrive first? In other words are you decelerating with your hyperdrive at -100% until you can switch back to `[STD]`?

**Comment by EthanNar** [comment]
yes, I'll sit at -100% throttle and I can switch to std, then lower the throttle all the way, I can switch to mnv, then get the speedometer reading at 0, I'll step off my ship and it will whiz into the distance.

**Comment by CyaNox** [comment]
Did you decelerate as long as you accelerated?

**Comment by EthanNar** [comment]
I can get slow enough to switch to [MNV] which only happens when you are below 3m/s or some similar number.

**Comment by CyaNox** [comment]
So even in `[MNV]` you can't fully stop?

**Comment by EthanNar** [comment]
in MNV it will tell me I'm stopped, and when I leave the ship it will carry on drifting away

**Comment by tsunamayo** [comment]
Okay I will check, warp is very bugged and wip at the moment. Thanks

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
