### ISSUE TITLE
With default controls, the throttle doesn't work. 

### ISSUE THREAD

**Issue by EthanNar** [tsunamayo/Skywanderers#467]
Changing primary binding doesn't fix, but leaving primary binding and binding secondary to something else fixes. reproducible with second player.

**Comment by tsunamayo** [comment]
Hi, what version of the game are you using? Thanks

**Comment by EthanNar** [comment]
was 17w47a

**Comment by tsunamayo** [comment]
Okay can you tell me you assigment, they are working with me I am not reproducing the issue. Thanks

**Comment by EthanNar** [comment]
from a fresh install, the [ and ] don't change throttle, changing primary binding to + and - doesn't work if you replace the primary bindings, but leaving them at  [ and ] and putting + and - to secondary works.

**Comment by AfterRebelion** [comment]
This issue is already fixed in recent versions (19w23b)
Or at least for me. I change default keybinds since my keyboard layout doesn't have [ or ] buttons
