### ISSUE TITLE
Laser Sensor changes?

### ISSUE THREAD

**Issue by EthanNar** [tsunamayo/Skywanderers#468]
The laser sensor would be many times more useful if it could detect non-player entities like blocks

**Comment by tsunamayo** [comment]
Yes but then it would always detect something when place indoor right? What would be your use for it? Thanks

**Comment by probka** [comment]
1. it might be distance sensor and output to screen
2. detect signal change (for ships passing)
3. return distance to router block (automatic extend landing gears when close to ground)
3. detect material (scan distant planet and see what a ground is there,  or asteroids or athmosphere)
4. if object has ID block - return name, mass, weapon bloocks count or even entire ship hologram (pirate scan ships)
5. laser input block can be placed to ship hull and can detect scanning from other ships

may be reduce ray visibility a bit for less recognisability (traps).

**Comment by EthanNar** [comment]
Make it require the other side with a laser sensor pad thing.

My use for it was going to be triggering logic cross ship, for docking stuff.
Dock to a docking arm with a standardized laser sensor interface, and use small brick arms to trigger lasers for extending an umbilical to the ship.

**Comment by tsunamayo** [comment]
Okay I could change the behaviour of the laser and its plate: by default laser detect everything, but if you put the receiving plate it will stop the laser while not triggering it. So we get all use: depth sensor like you explained, or just player detection to open doors. 
Also I could make them paintable, so if you paint it black it would become transparent allowing traps.

**Comment by EthanNar** [comment]
You're amazing!

**Comment by tsunamayo** [comment]
No longer applicable.
