### ISSUE TITLE
[Experimental] Throttle setting is persisting between ships (17w47a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#469]
Ship throttle setting is not being reset when the player enters different ships. This is normally not an issue if the ship is brought to a stop before exiting, but if the player exits a moving ship, the throttle setting from that ship is carried over to the next one entered.
Example: https://youtu.be/fg1KrPnrbsI

Note: I do not have a joystick or controller.

**Comment by CyaNox** [comment]
This is likely related to #464.

**Comment by Segdis** [comment]
I agree. These both appear to be caused by throttle values being attached to the player (or something else) instead of the individual ships. Wherever it is saved to, it is starting with an incorrect value when the game is launched (as you reported), and then any changes to the throttle are being passed along between different ships regardless of what they were doing before.

**Comment by tsunamayo** [comment]
Yes throttle value is assigned to the axis. I will force it to -1 when entering a ship, pb is that it does not fit well when a Joystick and keys are assigned at the same time. Thanks

**Comment by tsunamayo** [comment]
Okay it is now fixed as new behaviour is to force throttle at 0 when entering a ship. Cheers
