### ISSUE TITLE
[Issue] Crash to Desktop when pushing on the inverse brick

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#47]
So last night I was trying to figure out how to create push buttons for an elevator system and in part of my testing I tried to use the Call Back Command brick

![image](https://cloud.githubusercontent.com/assets/8591667/24109559/9fe24690-0d56-11e7-90f9-25a7c11a1314.png)

While doing so, I connected the red button to the lift, then I noted the blue button had to be connect to something (no clue what still) so I connected it to the lift as well, I assumed the red button would make it go one way and the blue would make it go the other.

The moment I pressed either I crashed to desktop.  I can recreate anytime so if you need something from me let me know.

Thanks

**Comment by tsunamayo** [comment]
Ok so this is not how callback work, I will fix the issue in next build. Thanks for reporting the bug !

**Comment by tsunamayo** [comment]
Issue will be fixed in next build. Thanks !
