### ISSUE TITLE
[Experimental][Visual] Flight mode GUI gets confused when switching ships (17w47a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#470]
The ship below was in standard flight mode at the time of this picture:
![flight mode bug](https://user-images.githubusercontent.com/33088776/33073819-200a941a-ce92-11e7-9652-39b068ead32a.png)
 Pitch, yaw, roll and throttle responded as they normally do (aside from the lack of throttle display), and the lateral/vertical movements of manuever mode were not active.

**To reproduce:**
Exit a ship that is in Maneuver flight mode
Enter a different ship that is in Standard flight mode

**Comment by tsunamayo** [comment]
This will be fixed in the next patch. Thanks!
