### ISSUE TITLE
[EXPERIMENTAL] Light leaking through some corners

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#471]
![image](https://user-images.githubusercontent.com/33023316/33082809-91da386e-ced5-11e7-91cb-911f660a914a.png)

The grey block above is this 
![image](https://user-images.githubusercontent.com/33023316/33082892-d0115af4-ced5-11e7-9197-86e935439ace.png)

**Comment by tsunamayo** [comment]
Hi, the situation should be much better now regarding to leaking, albeit still not 100% perfect. Could you tell me if the issue is better now on your build? Thanks

**Comment by JRL101** [comment]
when you place blocks on the other side the light tends to not "leak" This is a typical wedge calculation error in most games.

I also experience this. As i expect most are.

**Comment by Harlekin13** [comment]
I encounter lights shining through multiple layers of hull blocks (and then over a few hundred metres and through about a dozen other hull blocks. Same problem?

**Comment by Napther** [comment]
Like, after the patch the lights just outright shine THROUGH the hull not the corner ahahahah
![image](https://user-images.githubusercontent.com/33023316/33721513-29ba9382-db5f-11e7-83f6-2d87272b56e3.png)

**Comment by Napther** [comment]
![image](https://user-images.githubusercontent.com/33023316/33724595-bf727cde-db67-11e7-8bc7-592ceb19e8d3.png)

The star is almost directly along the line of the wedges (Parallel to their angled slope) and causing this odd leaking of light

**Comment by JRL101** [comment]
The light leaking comes from a calculation to do with thin edges from angled blocks.
I'll show you with a demo of images, if you put a block on the face the side the lights coming from it blocks it. Strangely enough it comes from specific orientations of wedges
light coming from the wedge side project onto the block next to it.
but light coming from a flat face of the wedge tends to just leak.

Example one: This has lights in the same places inside of each shape. The one on the far left is ALL blocks and slabs. 
The middle one Is pink and has wedges on the top edge and wedges filling the roof except the hazard blocks. The one on the right has a wedged inside using heptas and wedges, BUT a one block opening in the centre that a block has been placed above.
You can see the blue light is only on the two sides the lights are located but for some reason not near the wedges on the other two faces. 
![20171208071234_1](https://user-images.githubusercontent.com/33255536/33743713-f0811598-dbe8-11e7-8649-f9c42445f43f.jpg)
![20171208071235_1](https://user-images.githubusercontent.com/33255536/33743833-755bf454-dbe9-11e7-83d5-034203244d76.jpg)
**-------------------------------------------------**
If i turn all the top of the pink one into wedges with the angles surface facing the light.. then fill the hole with the same. It seems to not leak no matter what i put near it. 
![20171208071329_1](https://user-images.githubusercontent.com/33255536/33743897-bbe1eae6-dbe9-11e7-95d9-ae4ae8eaeee1.jpg)
![20171208071326_1](https://user-images.githubusercontent.com/33255536/33743869-958e3b9c-dbe9-11e7-93d4-219dd78aeb9b.jpg)
**-------------------------------------------------**
Here's and example with all blocks except the wedge facing up between the hazards. 
![20171208071428_1](https://user-images.githubusercontent.com/33255536/33743917-ce58dea0-dbe9-11e7-89a4-bf1f42d5a177.jpg)
**-------------------------------------------------**
OMG i love the lighting. But as you can see they all have simular light placements, with different colours to show them apart.
Here's the cross-section.
![20171208071726_1](https://user-images.githubusercontent.com/33255536/33743946-f1503f52-dbe9-11e7-8154-d01328afcea0.jpg)
F11
![20171208071725_1](https://user-images.githubusercontent.com/33255536/33744003-14d23228-dbea-11e7-9f0f-17bd435c3c74.jpg)
**-------------------------------------------------**
Test using other thicknesses of block. On the left one.
![20171208071937_1](https://user-images.githubusercontent.com/33255536/33744022-2c19de36-dbea-11e7-9e0c-c7d44859382d.jpg)
**-------------------------------------------------**
**_-SUMMARY-_**
So if you want to try lighting tests like this i suggest having several cubes in a dark giant box, 
Each Should should have different tops.
Another set should have cubes made from the same block facing the light the same way, in a sealed cube.

**Comment by tsunamayo** [comment]
@Napther and @JRL101 could you please zip and send me your blueprint so I can have a look at them? The new system is very different compared to the older one in regard on the way to interpolate the light from the light grid (the way we fill that grid is similar though), but on my side I have much less leaking compared to before.

**Comment by JRL101** [comment]
Gladly let me name it and upload it.

**Comment by JRL101** [comment]
Here is the Light Tester created in **[EXPERIMENTAL] 17w49a**  @tsunamayo 
[Light Tester.zip](https://github.com/tsunamayo/Skywanderers/files/1542917/Light.Tester.zip)

**Comment by Napther** [comment]
[KDI Journeyman MK1.zip](https://github.com/tsunamayo/Skywanderers/files/1544688/KDI.Journeyman.MK1.zip)
the fighter that originally showed this issue, Dont mind the blue, its always been like that as its inside Bricks, which, do not stop light

**Comment by Harlekin13** [comment]
That's three layers off hull... and light bricks on the other side.
![light](https://user-images.githubusercontent.com/34014817/33800711-2b10526a-dd46-11e7-9fbd-34180d55620d.png)

**Comment by JRL101** [comment]
As in three layers of full block hull?
Or three layers or 1/4 block hull?

**Comment by JRL101** [comment]
Because placing a single block between the light and the leaky surface in any situation for me blocks the light.

**Comment by tsunamayo** [comment]
@Harlekin13 could you send me your blueprint as I dont reproduce at all, it should not leak  like that for sure

**Comment by Harlekin13** [comment]
But I'm using 17w48a2.
Sure it's attached. Yes, by the way it's three layers of full block hull... With that issue i only need half of the lights to light the interior, so i won't complain. but it is a bit confusing.
Screenshot above is from in the hangar. But I had the issue that the lights of the far away station (ca 500-1k distance) shone (?) through some unfinished decks (of the station) over that distance through the outer hull (another three layers of full block hull) of the carrier, too. The last one is better since the carrier is mostly finished (need to do some more interior and a reactor) and lighted. First i thought it were some reflection of the sun over torus, but after a while i recognised the interior layout of the station, sadly I lost the screenshots of that...
[Carrier.zip](https://github.com/tsunamayo/Skywanderers/files/1546044/Carrier.zip)

**Comment by tsunamayo** [comment]
Sorry are you using children entity? I see some border pattern in the middle of it, hinting at children entities. Light can only be blocked by block from its own entity, not other entity.

**Comment by JRL101** [comment]
@Harlekin13 I'm going through the blueprint now. and i cant find the lighting error.
Oh that note i can't figure out the location of your screen shot. I assume its this hanger? 
![20171211084431_1](https://user-images.githubusercontent.com/33255536/33811531-932eb814-de4f-11e7-817f-0ab8a3692148.jpg)
![Uploading 20171211084433_1.jpg…]()

**Comment by JRL101** [comment]
Loaded into **[EXPERIMENTAL] 17w49a** @tsunamayo  Yes the lighting problem he's describing seems to be on child entities.
![20171211084716_1](https://user-images.githubusercontent.com/33255536/33811554-e77847dc-de4f-11e7-8774-5b45af3ca887.jpg)
![20171211084714_1](https://user-images.githubusercontent.com/33255536/33811555-e7af2bbc-de4f-11e7-9994-c7f3930c58b3.jpg)

**Comment by Harlekin13** [comment]
yes, i use child entities. But the light seems not even being blocked by blocks of the same entity.

**Comment by JRL101** [comment]
The light i see is ambient fall off from your light placement, if its too bright you can always adjust it with a slider. at 50% they will be at the original brightness before the lighting update

**Comment by tsunamayo** [comment]
Okay I finally took time to fix that, it should be good now I see no leak on all the issue I was having! Cheers
