### ISSUE TITLE
[EXPERIMENTAL] Light on planes has striations

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#472]
![image](https://user-images.githubusercontent.com/33023316/33083167-8aec720a-ced6-11e7-88ae-68e732d2a8e5.png)

Not sure if its an issue or not, or just a a simple limit to the engine. But at certain light incidence agles there can be slight oddities.
![image](https://user-images.githubusercontent.com/33023316/33083230-b5ddfbf0-ced6-11e7-9cb7-6a7960df45ac.png)

Might just be an effect of my set up and settings,

**Comment by tsunamayo** [comment]
Hum I think it is an artifact introduced by the shadow map. I cant use a very high quality shadow map as being a voxel game it could be really expensive when player spawn a lot of ships. So yes for now it is a limit of the engine =( Cheers
