### ISSUE TITLE
[EXPERIMENTAL] Weird lighting bug through surfaces.

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#473]
Strangely enough THIS ship. is causing some weird lighting.
![20171122084451_1](https://user-images.githubusercontent.com/33255536/33104351-88c15a40-cf62-11e7-8312-7a674e326507.jpg)
![20171122084449_1](https://user-images.githubusercontent.com/33255536/33104352-88f8b134-cf62-11e7-98ab-3cff29697645.jpg)

![20171122084228_1](https://user-images.githubusercontent.com/33255536/33104362-9eecce76-cf62-11e7-8234-47cbd74638d4.jpg)
![20171122084232_1](https://user-images.githubusercontent.com/33255536/33104363-9f2369b8-cf62-11e7-9655-39cb51ac50f9.jpg)
![20171122084409_1](https://user-images.githubusercontent.com/33255536/33104364-9f59dc96-cf62-11e7-9322-424cc41e049c.jpg)
![20171122084414_1](https://user-images.githubusercontent.com/33255536/33104365-9f9301a6-cf62-11e7-865f-ffd3bb3f6af7.jpg)
It seems to be the box outline of the ship dimensions behind the entity im looking at.
Might be lighting related. But its not happening with everything. and only at a certain range.

Both files are pre-current patch.
I've attached a zip with the ship and a copy of one of the things i was seeing it through.
[PlayerEntities.zip](https://github.com/tsunamayo/Skywanderers/files/1493533/PlayerEntities.zip)

**Comment by tsunamayo** [comment]
Hum yes for some reason it is fetching a light value, I will check this, thanks!

**Comment by tsunamayo** [comment]
Issues is fixed. Btw your door is one of most if not the most ridiculous thing I have seen in the game, I was speechless.

**Comment by JRL101** [comment]
Thanks, i mean i wouldn't have been able to do it without your awesome game.
