### ISSUE TITLE
[EXPERIMENTAL] Mirror mode undo/redo regression

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#475]
Strange how this gets effected every update; Might want to add this in as a standard check before pushing the pre-releases/Experimental branches. In fact, a "core checklist" to rattle off on to check each update on pre-release might not be a bad idea so that we don't clog the GitHub with common regressions.

![image](https://user-images.githubusercontent.com/33023316/33151317-86778486-cfcf-11e7-8170-bcf217e9cf27.png)
Blocks on mirror place fine...
![image](https://user-images.githubusercontent.com/33023316/33151323-8b9f1e38-cfcf-11e7-9f58-f8427efce6af.png)
Deleting 1 block...
![image](https://user-images.githubusercontent.com/33023316/33151332-93d6c9ca-cfcf-11e7-8bac-f855419e8635.png)
Undoing that delete
![image](https://user-images.githubusercontent.com/33023316/33151338-996fabae-cfcf-11e7-968f-5ae7e8e79c80.png)

17w??a2

**Comment by tsunamayo** [comment]
It was fine before? I remember one of your case on that, but I hadnt time to fix it. Thanks

**Comment by tsunamayo** [comment]
Hi, okay this issues has been fixed now, sorry for breaking stuff over and over ^^ Thanks
