### ISSUE TITLE
[Suggestion] Block placing highlight

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#476]
The highlight preview for placing multiple blocks was changed to white instead of the blue it was previously, however the hud that tells you how many blocks are being placed was already white, and it is now hard to see. I propose either the preview be changed back to blue, or the hud be changed to another color.

**Comment by tsunamayo** [comment]
Oh okay indeed, I will change that (I wanted to update the bulk placement preview also it is buggy). Thanks!

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
