### ISSUE TITLE
17w45c: Docked Entity Disconnected on World Load

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#477]
I've noticed each time I start my saved game back up, my docked shuttle is not connected to the main ship any longer. When I try to move the larger ship, the shuttle stays behind and then I have to reconnect it. I accidentally jumped once not remembering and left the shuttle behind. It seems like a bug and the game should retain docked entity information for things docked via the docking cone. 

Also, in my case I have a slider block involved to offset the dock to center. That structure also has it's own entity block. So the actual construction would be.

entity1:entity2:entity3 where entity 1 is my main ship, 2 is my docking arm and entity 3 is the shuttle. Let me know if you need any more details.

**Comment by tsunamayo** [comment]
Yes this was not yet coded into the game but will definitely do it. Thanks.

**Comment by tsunamayo** [comment]
Okay now the docking connection is saved and restored at save load. Thanks!
