### ISSUE TITLE
17w45c - [bug] Rails er... derailing kinda

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#478]
Ok so I'm constructing a station and have built several elevators in it, however I have noticed a strange little bug.  after a couple of uses the elevators on the rails kinda drift of center or derail.

The lift will still work and after a reload of the world the glitch will fix itself, however it comes back after a couple of uses. I have attached a link to a picture showing what I mean, the elevator was built centered, but as you can see the blocks have shifted slightly to the side.

https://steamuserimages-a.akamaihd.net/ugc/870747131748028752/B4A38530F5E6296A280A56F425F98AF6483DF1DE/

**Comment by Harlekin13** [comment]
Seems as if the issue doesn't need multiple uses of the slider. on a 500m slider the issue occurs on the first use, after some uses the gap spans over about half a block but seems to not expand further, instead the ride gets let's say uncomfortable.

**Comment by tsunamayo** [comment]
Okay thanks I need to fix that one. I keep you posted.

**Comment by tsunamayo** [comment]
Okay guys I cant really reproduce the issues, could you please send me the faulty blueprint if you reproduce that every time? Are you building on the torus? Thanks

**Comment by tsunamayo** [comment]
Okay I fixed the issue, another case was booked with a bp so I was able to reproduce. Thanks!
