### ISSUE TITLE
Changing hotbars resets active slot to slot 1

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#480]
Low priority, but it would be nice to swap upwards. Ive often preemptively selected the item on the slot above, then scrolled only for the position to be reset to 1 again and I have to scroll though to the slot on the new hotbar.

**Comment by tsunamayo** [comment]
Hi, that seems like a valid feature indeed, I am putting at bug so I do it shortly.

**Comment by tsunamayo** [comment]
Okay change is done. Cheers
