### ISSUE TITLE
[Experimental] Placing a large line with a custom color changes a section to it's default color

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#481]
This was rather odd since I've been placing large lines all over the place on this ship (The Invisible Hand). I placed 1m thick and about 130m long line with custom color 1 set to this grey tone and it made a larger section on one side of the mirror it's default red color. If I place a block in the red area it is also placed as red. But it keeps the custom grey tone on the other side of the mirror. If I place a block outside of this red zone it keeps the custom grey tone. 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1500364/output_log.txt)
![20171123183600_1](https://user-images.githubusercontent.com/32974671/33191359-30f1b7de-d07e-11e7-8638-076ac13dd109.jpg)

**Comment by Xerma** [comment]
**Update:** It seems to be fixed after saving and reopening the game

**Comment by tsunamayo** [comment]
Hum weird indeed. Is this the same entity? Thanks

**Comment by Xerma** [comment]
It's only happened on that one child entity so far. The ship has many and it's going to have more but all of the others seem normal

**Comment by tsunamayo** [comment]
Okay it is child entity issue then. Paint are gonna be refactored soon, and this issue should be fixed. Thanks!

**Comment by tsunamayo** [comment]
This issue should be fixed in recent versions! Cheers
