### ISSUE TITLE
Docking Probes Can't Be Placed On Child Entities

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#482]
I'm not sure that this is a bug, but I know that it is making some building designs I would like to achieve impossible without the ability to place a docking probe on a slider/rotator. 

Otherwise building certain things would be possible if it were possible to activate the docking sequence via activating only the docking cone.

I'm not sure this is a bug or if it is a planned thing. But it would be very useful if it were changed.

**Comment by CyaNox** [comment]
Duplicate of #405.
