### ISSUE TITLE
Build Place Preview lacks "Holographic base" when placing opposite the starting block

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#484]
![image](https://user-images.githubusercontent.com/33023316/33234986-a8d58028-d227-11e7-9ed1-9088522e7a49.png)

![image](https://user-images.githubusercontent.com/33023316/33235010-1ae09464-d228-11e7-892b-04b1498cc840.png)

as titled, a little bit odd that it appears for all options except the opposite to where you initially click to drag/orientate the block

**Comment by tsunamayo** [comment]
Okay I added the missing plane, thanks for reporting that! Cheers
