### ISSUE TITLE
3rd LongSlope block has extra drawn line when selected

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#485]
![image](https://user-images.githubusercontent.com/33023316/33235161-9676b82c-d22a-11e7-83aa-86bf0d5f2758.png)

![image](https://user-images.githubusercontent.com/33023316/33235178-cec5cd9e-d22a-11e7-8b1c-023a908713cd.png)

3rd row, first block

In the first image, you can see a triangle is drawn onto the block connecting 2 of the sides.... its a little hard to explain and Im not sure if that connection should be drawn

**Comment by tsunamayo** [comment]
Hi, so I had a look and it is indeed my algo to remove center line that is giving up on that shape. As I plan to remove that shape with the Magic free-form block I wont take time to fix it ... Thanks!
