### ISSUE TITLE
[suggestion] Player Set Router Gate Midpoint

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#486]
I've been desperately trying to pare a signal down to be able to open the outer elevator doors of my elevator only when it is at that floor. Unfortunately, I can't seem to get the logic right without an equals block or similar. However, it occurred to me that if we could set the midpoint of the router gate (currently default .5) we could create more fine tune routing. Since this block is already in the game and the logic for it already exists, it would just be a matter of exposing the midpoint variable to the player on the gate.

Example:

Let's say I have a slider that stops at .25 .65 and 1.0. I then pipe that signal via a callback switch to a system. I can use the default logic on router gates to split the signal in half using .5 sending .25 down one path and .65,1.0 down another. If I could then set another router gate on the second path with my own midpoint (let's say .75) I could split the other half of the signal between .65 and 1.0 which would finally allow me to properly work the doors.

**Comment by CyaNox** [comment]
As awesome as a setting for the Router gate would be ... it is not that complicated to combine a mix gate with a router gate to achieve your desired result.

To make this even more easy I made this little gem: https://docs.google.com/spreadsheets/d/1XbOK9Ktt6H4W3hEQGUGw24JHp3L36apoJVifscpuMiY

Hope it helps you in your multifloor elevator :smiley_cat:

**Comment by Rizzo911** [comment]
@CyaNox thanks for this tip and calculator... it worked perfectly. I think I had been thinking about mix gates differently. So, I was able to do what I needed, but it still might be a valid suggestion.

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
