### ISSUE TITLE
switching back from default color to no color

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#487]
i encountered quite some time the problem, that because of paints working otherwise (LMB to use, RMB to set as default color) than the rest (RMB to use), i had set the color as default. the only solution that helped was to exit to desktop and start skywanderers anew, as it doesn't reset when only quitting to title and loading the game.

I very much look forward to the new paint tool, but perhaps there is alsready a solution to the problem?

**Comment by tsunamayo** [comment]
Actually what we call default paint is just a paint called Blueish Gray. So you can just equip that color and RMB on it. It will all be refactored at one point for the paint tool updateand the crafting update. Thanks!
