### ISSUE TITLE
Placing an asteroid block causes all blocks to show as invisible

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#488]
Was in multiplayer with schlid and I went to place an asteroid block but it showed as invisible so I broke it. Later found that the rest of the blocks placed after that asteroid were also invisible. Restarted the server and I placed another asteroid block and the same issue occurred.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1504546/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks indeed, this block is a remnant of the old asteroid tech and should no longer be there. I just removed it! Cheers
