### ISSUE TITLE
[EXPERIMENTAL] Light not working when set on child entities

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#489]
It seems like light blocks don't emit light when set on child entities.

![ydy](https://user-images.githubusercontent.com/33256107/33290324-a26eeb06-d3c2-11e7-96e2-340577cdd046.gif)
![image](https://user-images.githubusercontent.com/33256107/33290353-b48b7f98-d3c2-11e7-9844-e2a60ea13f6a.png)

**Comment by CyaNox** [comment]
Duplicate of #460.
