### ISSUE TITLE
[EXPERIMENTAL] Vertical lines when looking at object from distance

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#490]
![image](https://user-images.githubusercontent.com/33256107/33290826-34a3a1e6-d3c4-11e7-98d4-ed32fc2a009a.png)
![image](https://user-images.githubusercontent.com/33256107/33290834-3be59734-d3c4-11e7-9922-1e310ece2a6c.png)

**Comment by tsunamayo** [comment]
Hi, it seems that AO is still causing some issues. How large is this plane? Do you confirm you turned AO on?
Thanks

**Comment by Name11ess** [comment]
AO is turned on.

I don't remember the size of the plane but it doesn't have any effect on the lines, they appear on every entities and child entities.

- The lines appear to be fadding away depending on the distance from objects.
- The lines are invisible when looking to the top, or to the horizon.
- The lines seems to be the strongest when looking at a 45° angle.
- The issue doesn't affect every player.
![sans titre](https://user-images.githubusercontent.com/33256107/33409306-05c88504-d57b-11e7-9acc-d0b601f51b9a.png)
- I didn't have this issue when playing in the non-experimental version of the game.

Here you can find a quick video of the issue: https://www.youtube.com/watch?v=jlkDgZHM99A

**Comment by Name11ess** [comment]
Hi! I've got a GTX 980. Cheers.

**Comment by tsunamayo** [comment]
Okay I had a similar issue, but not on voxel, only of the far terrain patch. This issue is fixed, but I cant reproduce your exact issue. Are your gfx driver up to date? 
AO was deactivated in previous build, this is why you didnt had any issue with it.
Thanks

**Comment by Name11ess** [comment]
Yes they are. I was wrong earlier though, the lines are not invisible when looking at the horizon, only when looking upwards.

**Comment by JRL101** [comment]
FYI thats "Horizontal" lines. 
And i've just noticed them with bright objects, might be related to the lens flair or the screen dirt. 
you can see slightly grey lines in the top third of the screenshot. 
Only seems apparent when looking at bright things.
![20171211085038_1](https://user-images.githubusercontent.com/33255536/33811624-b30f1e98-de50-11e7-97bf-b78d5bbf83dd.jpg)

**Comment by JRL101** [comment]
Clearer screen shot

![image](https://user-images.githubusercontent.com/33255536/33811651-e4c1b59a-de50-11e7-85a5-bb8a343944c1.png)
![image](https://user-images.githubusercontent.com/33255536/33811653-e9504e32-de50-11e7-9907-5e777b116674.png)

**Comment by JRL101** [comment]
My assessment seems to be wrong about bright stuff, its a bit random but its defiantly linked to orientation. 
![image](https://user-images.githubusercontent.com/33255536/33909411-8aa99c40-dfc6-11e7-9421-19022b2ee362.png)

**Comment by tsunamayo** [comment]
It seems this issue is fixed from a patch of my AO solution (not sure 100%, at least I cant reproduce it on my side - please re-open if you are still seing this!) Cheers
