### ISSUE TITLE
[Experimental] Issue copying/pasting child entities

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#491]
I'm not sure there's a direct cause to this but it seems to happen often enough. I go to merely copy an entity, in order to paste it, and the menu will either not show any other entities or it will show some but the list will be offset. It also displays the current main save name for the entire entity instead of the child entity I'm trying to copy. When I try to exit out of the menu it just flickers and stays on my screen. The only temporary fix to this is to restart the game but then it might happen again in the next session. I also had an instance in the next session where the pasted entity was offset vertically by at least 40m. In this picture I tried changing the entity name to save but the standard flickering occurs.
![20171127190621_1](https://user-images.githubusercontent.com/32974671/33297359-26521334-d3a6-11e7-9328-88f5f81ed45e.jpg)
Also my output_log is about 27 mb so I'll have to send that another way

**Comment by tsunamayo** [comment]
Thanks I will check this out! Usually when the game is unresponsive (you cannot interact but still move) and slow, it means that it is spitting out the same error to the logs ;-) so you can exit before log become too big, as you should not be able to play anymore anyways. Cheers

**Comment by tsunamayo** [comment]
Okay issue is now fixed! Cheers
