### ISSUE TITLE
Could we get nsc bots?

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#492]
We need simple NSCs, Just some ragdolls to sit in front of a desk with screens and blinking lights, some faceless masses to walk coridors. I don't want them to be some complex things or getting named, think storm troopers marching in the hangar or some irrelevant crewmembers, in the end i don't want them to have more function than decoration.

**Comment by Balibalou** [comment]
personnaly I'd prefer npc droid which you would set a task to do (turret, repair, guard, mine ...)

**Comment by Harlekin13** [comment]
In the long run that could be a possible advancement for them but at the moment i just want some crewmen for things no player will ever want to do; just sit there for hours looking at a blinking light that's only decorational too for example or walking along a hallway just because else it would be too empty or laying in bed, sitting on a toilet, just the things protagonists don't do but are needed that a space station doesn't look lifeless.

How does one set labels? Can't find a way, but am not too motivated to get to know github better too.

**Comment by tsunamayo** [comment]
No worries I set labels ;-) Yes I want NPS to make the world more living, and programmable droids to add more possibilities. It will come, but not on the short term! Cheers
