### ISSUE TITLE
Weird colors when loading the game with vertical lines in the distance

### ISSUE THREAD

**Issue by DamianDrazhar** [tsunamayo/Skywanderers#494]
I opened the game after the update and was presented with this 
![image](https://user-images.githubusercontent.com/34104789/33390772-3af9f2c4-d537-11e7-8de5-621178f57f66.png) colorful display

**Comment by tsunamayo** [comment]
Hi, this bug should be fixed in the experimental build. You can either use the experimental build, or wait a few day that I put experimental into default. Thanks!
