### ISSUE TITLE
can't start game anymore

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#495]
Since the update today the game self is starting, but everytime i try to start the saved game or a new one the loading never ends.

**Comment by tsunamayo** [comment]
Hi, could you please send me your output.log file, and also tell me your version? Are you on experimental?

output.log directory 
C:\Users\[USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers

**Comment by Harlekin13** [comment]
it's version 17w47a2, I'm not on experimental.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1517404/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, could you please make sure your driver are up to date? Thanks

**Comment by Payday02** [comment]
I had this problem, if you make a new character and let that world load up, then close the world and try to join your original one it works (for me at least). I’m not sure if this will help other people but it worked for me. One problem tho, every time you wanna reload the worlds you may have to do it again

**Comment by tsunamayo** [comment]
Hum it is weird, one thing you need to remember is that there is no several world like in minecraft, just a single one. You create character, not worlds.
If you build a ship on the starting torus with a character and then start a new character you will see the same ship.
@Harlekin13  did you warped to another system? Is it working with a new character like @Payday02 said? Thanks!

**Comment by Harlekin13** [comment]
I did not warp anywhere (to be more correctly i did it once but didn't save after it and therefore it should not count) i used the teleport a few times in 17w46c but i don't think that would impact much now.
The issue is the same for a new character.
I already have the latest drivers for my hardware (at least every automatic update process says that, let me check for graphic card at the manufacturers site).

**Comment by Harlekin13** [comment]
deleting the savegame as you  (@tsunamayo ) suggested in #502 did the trick.
Now to try which parts of it where responsible, hopefully not the wip-entities i have not created blueprints for.

**Comment by Harlekin13** [comment]
okay that's new, I did not try out anything from the former savegame. I started the game, remembered i wanted to try out some parts of the former savegame, game crashed on quitting from the menu.
I am able to recreate the new crash most of the time.
start skywanderers, any key to get to the menu, play, single player, back, back, quit game, crash.

**Comment by tsunamayo** [comment]
Okay, good to see you pinpoint the issue. Could you please send my your  blueprint, I will check them and hopefully fix the issue with the problematic one. Thanks!

**Comment by Harlekin13** [comment]
i do not even have any blueprint in the new save game, the world isn't yet generated.

**Comment by tsunamayo** [comment]
Sorry I was referring to the issue you had when using your blueprint. For the crash I will see, all I can tell is that the game was upgrade to a new version of Unity, so it might explain the issue with your anti-virus. Thanks

**Comment by Harlekin13** [comment]
Okay, the loading issue seems to be connected to at least the following blueprint.
[Space Elevator Station.zip](https://github.com/tsunamayo/Skywanderers/files/1525208/Space.Elevator.Station.zip)

**Comment by Harlekin13** [comment]
Without that entity everything works fine, perhaps it's to big already (and i've just begun building that testarea)?

**Comment by tsunamayo** [comment]
@Harlekin13 what is the size of your station? Thanks

**Comment by Harlekin13** [comment]
can't say for sure, but it should have been a few hundred x a few hundred x 100, with two extensions of about 500 to reach to ground.

**Comment by tsunamayo** [comment]
Issue should no longer be applicable (ping me if you still have issues) Cheers
