### ISSUE TITLE
[Experimental] Issues with the new lights on child entities build

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#496]
Maybe I'm just missing something but the new build doesn't seem to have done anything for me. Lights don't work on already existing children entities, they don't work on new ones built off of ships already in the game and they don't work on new ships with new child entities. I even did a clean install and loaded in a ship with lights on child entities as well as a new ship, in the clean install, with lights on new child entities and still no luck. Also glow blocks don't glow anymore, not even on the main entity. They act as regular blocks.
![20171130023238_1](https://user-images.githubusercontent.com/32974671/33421656-6b9829be-d578-11e7-8797-76af280b1e82.jpg)

**Comment by tsunamayo** [comment]
Light block must be a separate issue (there is a light block and a glow block, these are different as the glow is not supposed to emit light). Are you using Big Rotator or Big Slider to spawn your child entity? Thanks

**Comment by Xerma** [comment]
Ahhh, don't know why I didn't see it before. Lights must not work on child entities that are on hinges then. That would explain why my elevators have lights working and other parts don't. I'm assuming that's intended then?

**Comment by tsunamayo** [comment]
Yes it is intended, as the new light system is a more costly fps wise. See https://www.skywanderersgame.com/forum/viewtopic.php?f=2&p=1707#p1707 for more details. I will introduce several other limitations like on mass, energy or subsystem, the idea is not to use hinge for massive/fonctionnal part of the ship. Cheers
