### ISSUE TITLE
Memory Leak? - Game Crashes After Placing Too Many Blocks

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#498]
So from what I can devise this issue has only been occurring since the most recent update to the main version of the game. 
I have tried playing the game on its newest release version, and having experienced a crash, I decided to try the experimental version, only to find it still happens.

The best way i can describe as to how I have triggered the crash, is after a large amount of block placing, the game crashes. I presume it is a memory leak.
The more blocks I place, the sooner the crash occurs. 
After the game crashes a window opens showing an option to open the folder where the crash report is located, and so I have added those files the crash has produced.

[error.log](https://github.com/tsunamayo/Skywanderers/files/1520325/error.log)

I can provide the crash.dmp file if needed. Github by default doesn't support that file type and wouldn't let me upload it.

I'm not 100% sure why this is happening but I do know that it is a problem caused in the most recent update, as this wasn't happening before.

**Comment by Harlekin13** [comment]
how many are too many? perhaps that's related to my  #issue495? As I had worked on two massive spacestations before the update.

**Comment by Sullos** [comment]
No I checked out your issue and many there issues before making this new report. It is unrelated to anything anyone has posted about. The game works no problem, I place 1000’s of blocks, I’m not sure how many, but I’m guessing after placing around 20,000 the game crashes. I’m working on one of the bigger builds the game has being worked on, so I expected Issues.

In the previous version of the game everything worked fine. I could play for 8 hours straight, only save once, place 100,000 blocks no problem. I went into experimental version in the previous version of the game and I started crashing. So I went back to standard version. Then the game updated, and now I’m stuck with a version of the game that crashes after a bit of light building :P 
I read the update log for what was fixed and added, in the new version of the game and I presume that it’s a memory leak due to a previous memory leak being found and fixed. I imagine my memory using over 16gb whilst playing skywanderers would cause Issues.

**Comment by tsunamayo** [comment]
Okay could you please send me your blueprint? How long does it take to reach 16go memory in a normal build session?

**Comment by Sullos** [comment]
So I just did a test boot,  and loading into the world where I have my Space Station being built, it took me 7 minutes, and it brought my Skywanderers memory up to 9,500MB in that time, just to load into the world. All of this was done after a fresh computer boot too. 
I have 32 GB of memory so it takes a while to reach a bad spot. 
Just watching my computer resources now, with Skywanderers open in the background doing nothing, my memory is being used at about 0.2MB per second.
I tried placing a plane of blocks ~30 x 15 standard blocks, also using 1 mirror block, and my game memory usage shot up another 300MB. I don't know if this is standard behavior but it is chewing my memory up.
I have attached a link to Dropbox of my Blueprint file for my space station. But be warned it is a very big build, and may take quite a while to load into the game. 1000x1000x700 ish blocks..
https://www.dropbox.com/s/gsvv52yluqv1utz/Sullosian%20Space%20Hangar%201.swbp?dl=0
If you need anything else please let me know, I am keen to figure out why this is happening! :)

**Comment by tsunamayo** [comment]
Thanks, when you did your test did you placed the block outside the area of the station or inside (I want to know if it triggered the creation of new chunks). Game is not yet optimized for massive build for sure, but if there is a leak I would like to find it.

**Comment by Sullos** [comment]
I was building inside the cargo container storage area within the station. 
Oddly after the first hour, the game started to drastically lower memory usage, and then if I we wefe to continue building at a standard rate, then the memory would shoot back up very quickly.
So after 30 minutes of continued building, more or less the exact same standard of building, placing rows of blocks, pre painted with a custom colour, and placing individual blocks too - the memory went down to less than 2000MB usage. Then whilst doing the exact same stuff, it went back up to over 7000MB at a steady rate. It’s quite odd, I can’t seem to get a standard memory usage, nor can I truly recreate the crashing, it just happens after a while.
The only thing I know for certain is that this crashing problem only started after the implementation of the new lighting update. That’s the only suggestion I have to look into for a change in rendering of things perhaps, or the way the game handles block placement?

**Comment by tsunamayo** [comment]
To be sure the game will generate some garbage as you build, and since your build is ridiculously big the mem allocation swing are also large. I did some math taking into account your station size, you are well over what the game can handle (and you gfx card) if your station where fully lit. (I guess you didnt put light everywhere yet?) 

If you want to continue to build this please be aware that the game will most likely give up at one point, so I would suggest build smaller if you really want to see your station finished one day. If it is not that important for you then you can continue at push the limit of the game, on my side it is always very informative ;-).

Do you have another project going on, as it is impossible for me to debug this. What I am most concerned is the fact that you mentioned memory was rising when doing nothing, this should not happen.

The memory increase of 300mb given the current light implementation and you build size is not surprising. I will eventually tackle this.

**Comment by Sullos** [comment]
Okie dokie! Well I guess I'm happy to say I'm building one of the largest builds in the game yet.  But that is disappointing I may not be able to finish it without death to the game or my computer. 
I will definitely continue my build. Because if I manage to finish it, to some extent, then that would be awesome! 
I haven't put light everywhere yet, no. I'm trying to finish one section at a time, and I was awaiting development of the docking system to see what I could do with it.
And unfortunately I don't have so much of another project going on, as I have spent my last 100 or so hours in game building this station. 
I will continue this build and see how things go. Hopefully the game doesn't die, but I guess I was hopeful the game could handle such a large build.
Thanks

**Comment by Harlekin13** [comment]
Perhaps it will later on be able to handle that large builds (please? I want to build that WH40K Battlecruiser) after it is more optimiced? I'm not quite sure, but the voxels don't have texture where they cannot be seen? How about rendering only the parts a player character sees (perhaps a bit more just to make sure, but not everything), that should have quite an impact on performance and therefore should make bigger builds easier handlable, right?

**Comment by tsunamayo** [comment]
@Harlekin13 haha of course I am using Frustrum culling like every 3D game since the beginning of 3D games. Texture is not really the bottleneck in voxel game, the amount of geometry is. The last update was an improvement for FPS. Some more improvement are planned, but please keep in mind my goal was not make an engine made for mega structure, otherwise I would have done many things differently. Instead I have been focusing a lot of micro building with the brick system, because it can give gameplay possibility. 
Also in my experience most people tend to never finish massive build...

**Comment by Harlekin13** [comment]
Damnit again being part of a minority, i normally finish want i begin (or pause it if i encounter a problem, which i am not able to tackle at that moment and finish it when i learned how)...
But every capital Star Wars ship built in scale would be such a mega structure, therefore I thought...
Does the system for matters of physics and such (but not for building or damage) merge the blocks to bigger units already, i have no idea of game programming, but that could have an impact on geometry, right? And one should be able to use the same technique for bricks resulting in a small (perhaps even big) raise of the bricklimit. one could make the built modular, meaning built modules docking to each other (wanted to dock armour sections to the hull, making it easier to repair damage), if it's a problem of being a to massive built when only one part, perhaps such modules could be a workaround?

**Comment by Name11ess** [comment]
My game crashed three times now while working on a large ship a building or deleting a good amount of blocks at once.

Probably the same issue as op, so here is the crashlogs from the last crash (I was deleting 3552 blocks at once, multiple times in a row)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1575513/error.log)

**Comment by tsunamayo** [comment]
@Sullos @Harlekin13 @Name11ess So I made massive change in recent version, that should reduce considerably the memory size and management of ship geometry (50x gains!). If you had had the opportunity to build in recent version could you please tell me if you are still having issues with massive build? Thanks a lot!

**Comment by Name11ess** [comment]
I've [been building an Acclamator](https://cdn.discordapp.com/attachments/416013956331601930/598671541017772062/unknown.png) (~750m) for the past few months and everything it working smoothly (and no child entities so far). There is always some freezing time when I build larger set of blocks (+mirroring) but no crash so far.

**Comment by tsunamayo** [comment]
my god you are a committed builder! Yes the bottleneck now is clearly the lighting texture, that is gonna be massive for your ship... Actually it might change one day, we will see if I have time to work on that! I am closing this. Thanks all!
