### ISSUE TITLE
[BUG] Ghost Chairs

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#50]
If you put down a chair, then put a 4x4 stud tile on the ground in the same area the chair occupies, the chair turns invisible. You are unable to fully get rid of the chair; even if you break it and the tile, it will still act as if it is there and let you place studs on it. This also occurs if you use the bed instead of the 4x4 tile. Pic included:
![2017-03-21 1](https://cloud.githubusercontent.com/assets/26584892/24177260/a7ab89b4-0e77-11e7-82c0-e0da055e9655.png)
So far, it occurs with both chair types, and only occurs with the two 4x4 tiles, none of the smaller ones from what I've seen.

**Comment by tsunamayo** [comment]
Will be fixed in next build. Thanks !
