### ISSUE TITLE
Re: More options for the Paint Tool

### ISSUE THREAD

**Issue by Javidac** [tsunamayo/Skywanderers#500]
Due to the last one being way to poorly worded on my part, i'm writing a new issue on this subject. I'm sorry for any inconvinience short rants written at 4am may have caused.

I'm currently a couple of million blocks into a build, and due to using f.lux the entire thing is in the wrong basic colour. Had i started building it with a custom colour from the start, this wouldnt be a problem. Some strands of hair pulled out of my forehead later, I've given the entire system some thought.

Considering the current system with the spraypainting only being able to colour a single block at a time, that would effectively mean i would have to spend hours and hours repainting every single block by hand. I've come to the conclusion that some simple tools would help greatly in this endevour.

1. An option to increase brush size. so the paint area is adjustable from 1x1 blocks to 10x10.

This one is quite basic in consept. A simple ability to paint a larger area with the paint tool.

2. An option to completely repaint an entity.

This is simple enough in theory, I have no idea how difficult it may be to implement. Works similarly to the way custom colours work now, exept that this overwrites any colour already on the build. In effect you could turn say, Blueish gray into Yellow on the entire grid with a click of a button. For example Ctrl-Shift-Click

3. An option to repaint only specific blocks.

In effect this would probably be the hardest of the three to integrate into the game. The idea is to have an option to repaint for example only buttons, or only tech hull, into a certain colour.

Again, i apologize for any inconvinience my last post on the subject caused.

**Comment by tsunamayo** [comment]
Hi, no pb and no bother at all, I like suggestions ;-)
In that case I still think the custom color is answer. To be honest painting is fast, I did myself repaint huge ships and it took not that much time, and only a fraction of the time it take to build the ship, the interior and so on. How large is your ship?

**Comment by Sullos** [comment]
I kind of agree with the need for other painting areas. I too am several million blocks(or more?) into my build, and I am fine with punting the blocks at the moment, but my hangar bays could really use some better method to paint. 
I like the idea of option 1 for sure. Maybe by having a particular pint selected, hold ctrl, and scroll between the size of the ‘brush’. 
I do like the other two options, but I feel like the issues they create would be quite unworthy of implementing. At the moment just remembering to use custom colours first, then deciding colours later is the best way to suit options 2 and 3. But if they can be get implemented easily enough, I’d love them too!

**Comment by Javidac** [comment]
Its about star destroyer size, about halfway done in the wrong colour, and around 1.5 million blocks.

**Comment by tsunamayo** [comment]
Yes maybe option 1 will come, but again if you guys are starting massive build of that size you have to be willing to spend the time and plan things accordingly... Option 2 and 3 wont be implemented because it is too specific and would take time and add complexity. Cheers

**Comment by Javidac** [comment]
Thanks! :)
