### ISSUE TITLE
Weapons seem to fire on receiving any pulse 

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#502]
It occured until 17w46c to me that weapons fired even when receiving a 0 (and yes i used an AND-gate which i hoped to be able to use as safety). Would love to test it again, but as the world doesn't load i can't.
Anyone other having that issue?

**Comment by tsunamayo** [comment]
Okay I will check for weapon. If doesnt load could you please backup you save directory 
C:\Users\[USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
Then delete it, and start a new character and see if it works.
Thanks

**Comment by tsunamayo** [comment]
Okay I tested it the beam indeed that is always firing, other weapon are okay. I will fix it. Thanks

**Comment by Harlekin13** [comment]
I would have sworn it were rockets and lasers too (but perhaps there was some bugged logic on my side).

**Comment by tsunamayo** [comment]
Okay I fixed this issue. Thanks!
