### ISSUE TITLE
[EXPERIMENTAL] 17w48a Rails not extending correctly

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#503]
The rails seem to be acting weird, i tried changing the orientation of everything same thing happens, the zero end of the glow rail refuses to recognise the basic rail and stops as if its not there. 
Images for demo.

![20171203182009_1](https://user-images.githubusercontent.com/33255536/33524354-ee66b3c0-d856-11e7-9b92-cab4f752d6a2.jpg)
![20171203181527_2](https://user-images.githubusercontent.com/33255536/33524355-eea2c298-d856-11e7-84ec-f8d6816d241b.jpg)
![20171203181857_1](https://user-images.githubusercontent.com/33255536/33524356-eedd1ab0-d856-11e7-9b35-5ed42cd7e356.jpg)

**Comment by JRL101** [comment]
I hope this is the right file
[Entity_6a2d6fca.zip](https://github.com/tsunamayo/Skywanderers/files/1524659/Entity_6a2d6fca.zip)

**Comment by JRL101** [comment]
A game restart seems to have fixed it. But placing new rails does the same thing.

**Comment by JRL101** [comment]
**[Experimental] 17w49a**
Bug still present, same solution, game restart.
![image](https://user-images.githubusercontent.com/33255536/33744454-2c77c5f8-dbec-11e7-9c89-0ca5345bd593.png)

**Comment by Harlekin13** [comment]
I encounter the exact same issue sometimes too, but not everytime i place a slider.

**Comment by AfterRebelion** [comment]
The Sliding Brick is freeform, so this issue is no longer valid in recent versions (19w23b)
