### ISSUE TITLE
Resolution Error

### ISSUE THREAD

**Issue by Incapelli** [tsunamayo/Skywanderers#504]
As I try to load the game from Steam, the window comes up, but an error message is the only thing displayed. This happens as soon as the game loads. Error message claims that the resolution switch has failed.

https://i.imgur.com/EKQ11S7.png -screen shot of the error message.

**Comment by tsunamayo** [comment]
Hi! Could you please give me the resolution you where using before the patch? Did you change anything with you monitor of gfx card - and are your GFX drivers up to date ? Thanks

**Comment by Incapelli** [comment]
1440x900 I believe, and no, I haven't changed anything. Also, I updated my driver yesterday to see if that would fix the problem, but no luck.

**Comment by tsunamayo** [comment]
Okay, also could give me your video card reference? Did you tried to uninstall the game from steam? Thanks

**Comment by Incapelli** [comment]
https://i.imgur.com/h4TeTCF.gif -screenshot taken using GPU-Z

And uninstalling and reinstalling was one of the first things I tried.

**Comment by tsunamayo** [comment]
Thanks. Could you please go into the steam folder, right click on Skywanderers.exe, go to compatibility and tick Disable Fullscreen Optimizations ?

**Comment by Incapelli** [comment]
I don't have that option.

**Comment by tsunamayo** [comment]
Okay, what OS are you using? (XP?) Is your OS up to date (I guess DirectX update are important)

**Comment by Incapelli** [comment]
I'm using Windows 7, and it probably isn't. I'll go update it now.

**Comment by Incapelli** [comment]
Okay, I've loaded it up and it's working now.

**Comment by tsunamayo** [comment]
Glad to hear that! I guess it was the switch from Unity 5.6 to Unity 2017.3 that needed a more up to date Directx. Thanks!
