### ISSUE TITLE
Lights seem only to be able being turned off or on not both someplaces

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#505]
I encountered the problem turning a light off is no problem, but it isn't possible to turn it on again.
Switching the switch makes the area darker, but switching it again doesn't relighten it.

**Comment by tsunamayo** [comment]
Could you send me your blueprint and tell me which light to switch as it is working fine on my PC. Thanks

**Comment by Harlekin13** [comment]
now it is working. Perhaps it had something to do with the logic behind it. I search for it next time i'm building in the crew quarters, have something to build in mind first.

**Comment by Harlekin13** [comment]
After a restart it's working. I think there must be some bug somehow, 'cause else it should be working everytime, not after restarting the game first.

**Comment by tsunamayo** [comment]
This issue should no longer be applicable as light tech is new. Cheers
