### ISSUE TITLE
Lighting for a moving platform is 'odd'.

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#507]
After lowering a platform a certain distance, the light from the area disappears. This seems to affect the blocks themselves as well lit blocks will instantly turn black after passing through the threshold.

![20171205201919_1](https://user-images.githubusercontent.com/33102709/33639556-d5264e62-d9f9-11e7-931f-78aa352ab94d.jpg)

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint? Thanks!

**Comment by Ar-Gent** [comment]
The latest update fixed the issue. Thanks.
