### ISSUE TITLE
[Experimental] Paint changes not applying to symmetry. [17w48a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#508]
When a ship is built with a symmetry plane, the selected paint is applied to blocks placed. However, if a new paint color is applied to blocks on one side, this change is not reflected on the other side.

![20171206173008_1](https://user-images.githubusercontent.com/33041786/33690864-265de31a-daab-11e7-8881-bd590fff01bc.jpg)

**Comment by tsunamayo** [comment]
Hi this issue was already fixed in 17w49a. Thanks!
