### ISSUE TITLE
[EXPERIMENTAL] Scrolling in Pause menu causes zoom changes when in 3rd person mode

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#509]
As title, scrolling in pause menu should not change the zoom level

**Comment by AfterRebelion** [comment]
This still happens in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Okay thanks, issue is (finally) fixed. Cheers

**Comment by tsunamayo** [comment]
Will be in 19w31a.
