### ISSUE TITLE
[Suggestion] RPM display for rotors on speedometer

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#51]
When speedometers are linked to a rotor, the current rotors rpm is tracked and displayed.

**Comment by tsunamayo** [comment]
Hello, thanks for the suggestion. On the label : no need to put [Suggestion] in the title, putting the labels called Suggestion was the way to go.

**Comment by tsunamayo** [comment]
Deprecated as no more rotor for now. Thanks
