### ISSUE TITLE
[Experimental] [BUG] Graphical glitch on stacked stairs [17w49a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#510]
When stairs are placed next to each other, the middle support bars disappear as they should, but the "foot" of the bar is still visible.

![20171207124944_1](https://user-images.githubusercontent.com/33041786/33732850-618b4002-db4d-11e7-84c4-38e0c24c56f2.jpg)

**Comment by Harlekin13** [comment]
it's in 17w48a2 too, and was in former versions i think, but i did not see it often, as i have not built free stairs til now as i clipped right through them.

**Comment by tsunamayo** [comment]
No longer applicable, thanks!
