### ISSUE TITLE
[Experimental] ID block issues

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#511]
I'm not sure if that fix you made for #491 is live yet but I might as well post about it just in case because I'm still experiencing the same issue in the current experimental build.

**Comment by tsunamayo** [comment]
It is supposed te be live yes, could you please send me your log it must be a different issue. Thanks

**Comment by Xerma** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1541463/output_log.txt)
Not nearly as big as the other output_log file but still pretty large

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
