### ISSUE TITLE
Docking Glitch

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#512]
If you place a docking cone on a child entity (sliders, rotators, hinges) , and dock it to a probe, once the signal to the docking probe turns off, the entire entity with the probe will disappear. I was able to recreate this with the regular rotator, and the regular slider, but did not test with the other variants.

Video link: https://youtu.be/sx9x-FSBuP4

edit: the entities weren't disappearing, they were being teleported away, roughly 150 meters
![20171208162328_1](https://user-images.githubusercontent.com/33016249/33785715-50e5a642-dc34-11e7-8061-ee6027cee344.jpg)

edit 2: after reloading my game, the glitch stopped

**Comment by AfterRebelion** [comment]
The docking block is no longer in the game, so this issue is no longer valid in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Docking will be back for sure! Thanks

**Comment by AfterRebelion** [comment]
But we expect it doesn't come with nasty bugs this time :D
