### ISSUE TITLE
Unable to connect to Mtuliplayer

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#513]
whenever I try to connect to my brother's game, the load of the game fails, leaving me in the loading screen, able to TAB to show the block menu, ESC will toggle between the menu and the broken game, but not show the UI, although it it clickable.

the log shows thousands of errors of the following form:

NullReferenceException: Object reference not set to an instance of an object
  at EntityCulling_Manager.AddBoundingSphere () [0x00000] in <filename unknown>:0 
  at Voxel.Entity.LightVolume..ctor (.BlockEntity entity) [0x00000] in <filename unknown>:0 
  at BlockEntity.Initialize () [0x00000] in <filename unknown>:0 
  at BlockEntity.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.Object:INTERNAL_CALL_Internal_InstantiateSingle(Object, Vector3&, Quaternion&)
UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
UnityEngine.Networking.ClientScene:OnObjectSpawn(NetworkMessage)
UnityEngine.Networking.NetworkConnection:HandleReader(NetworkReader, Int32, Int32)
UnityEngine.Networking.NetworkConnection:HandleBytes(Byte[], Int32, Int32)
UnityEngine.Networking.NetworkConnection:TransportReceive(Byte[], Int32, Int32)
UnityEngine.Networking.NetworkClient:Update()
UnityEngine.Networking.NetworkClient:UpdateClients()
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()

output log is 139Mb, too big to attach.

**Comment by Vicomt** [comment]
Confirmed to occur even in a new empty world.

**Comment by tsunamayo** [comment]
Thanks for reporting that, issue is now fixed (available in next patch)! Cheers
