### ISSUE TITLE
fence bricks should be more like light bricks

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#514]
I think fences like lights should be able to overlap in the corner of a block, at the moment there always is a gap in the corner of the plattform.
![fence - light](https://user-images.githubusercontent.com/34014817/33800337-316168be-dd3e-11e7-8069-fd2f78882e6a.png)
![fence](https://user-images.githubusercontent.com/34014817/33800348-8c2cc7fc-dd3e-11e7-80b4-67460ba6973e.png)

**Comment by AfterRebelion** [comment]
There is a fence corner, so this issue is no longer valid in recent versions (19w23b)
