### ISSUE TITLE
[Experimental] 17w49a Canopy blocking interactions.

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#516]
Not sure if this is possible, but can you mask the collision box as well at the textures when they join?
![20171214180202_1](https://user-images.githubusercontent.com/33255536/33986771-9398254a-e0f9-11e7-9896-881026ae7b23.jpg)
"Canopy Long Wedge" 
As you can see anything under the canopy is impossible to access. happens with everything under them. 
If the backs are at all in the way, they act like a solid surface.
is it possible to turn off those collisions triangles when the textures connect? same rule maybe?

**Comment by JRL101** [comment]
**-OFF TOPIC IDEA-**
If you can mask the collision mesh, is it possible to select a bunch of connected bricks and tell them to be a single mesh? it doesn't have to keep its studs or be able to be turned back into bricks. It just might be a cool option for players to lower their poly count with a finalised ship. Its a ridiculous idea, but this just ma=de me think of it sorry to be off-topic :)

**Comment by tsunamayo** [comment]
Yes this is one of the many issues I have with Canopy, they are a bit of a pain to deal with. I might create a freeform canopy block instead...

**Comment by JRL101** [comment]
After seeing your xmas present a canopy version of that block would be amazing!

**Comment by AfterRebelion** [comment]
Since the freeform rework, this issue does not happen in recent versions (19w23b)
