### ISSUE TITLE
[Experimental] Freeform block glitch on skewed vertices placement

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#518]
Freeform block doesn't correctly join faces when working on long angles.

The front face should be flat, and I've rotated the vertices multiple times and this is theoretically the correct position, however it joins through the middle on the "front" and back" whereas the top and bottom are produced correctly.

![image](https://user-images.githubusercontent.com/31857052/34325050-3b990026-e87e-11e7-9529-13e1fedb6b45.png)
reference for front^
![image](https://user-images.githubusercontent.com/31857052/34325055-70712eb8-e87e-11e7-8d56-481dd129973a.png)
reference for back^

Also it's a shame there's no freeform block for the "Hull" texture whereas there is for Hull basic & Hull Tech, seems like a quick addition.

**Comment by tsunamayo** [comment]
Not sure to understand what you did, if you could send me your bp that would help. Also yes as explained on the forum I will add other hull, for now it is more for testing rather that anything. Also fyi plain Hull will likely disappear.

**Comment by schlid** [comment]
I'm on discord atm, and can host for a few mins if you want to hop on

**Comment by schlid** [comment]
Since it seems you're not going to make it online before i head off i sent the ship file in discord, It's a project I'm trying to keep on the low hence why i'm not publically uploading it.

**Comment by tsunamayo** [comment]
Hi yeah sorry I am in the middle of the Xmas preparations, party is about to start ;-)

**Comment by schlid** [comment]
No problem, enjoy the festivities, thanks for the update and merry Xmas!

**Comment by JRL101** [comment]
FYI i know what's causing this. the Freeform block is asymmetrical, so the direction the diagonal vertices across each face isn't mirrored. so when you place a block the left and right side face break is not mirrored. 
just remember which face you place the block on decides which way around the block is. Hopefully this wont matter when the mirroring works. 
![image](https://user-images.githubusercontent.com/33255536/34855160-1f073bc6-f779-11e7-9c37-416d789f6f77.png)
![image](https://user-images.githubusercontent.com/33255536/34855263-9d499f1a-f779-11e7-93b9-6e42352c0395.png)
Placing it on a surface, you can see the faces are all identical meaning if you place one next to it you will not be able to mimic the other side the same. (unless its rectangular)
Placing a block on the side of the other one can how ever help for now. 
Pretty much rotating the block 90 degrees and mirroring the block
![image](https://user-images.githubusercontent.com/33255536/34855216-68d359ba-f779-11e7-9a9a-ff8fcfeaf01e.png)
![image](https://user-images.githubusercontent.com/33255536/34855252-93a43646-f779-11e7-8019-8604dda69f78.png)

It folds the mesh depending on the vector lines. so if the vector line goes from top left to bottom right on both blocks, consider them to never copy eachother.
![image](https://user-images.githubusercontent.com/33255536/34855333-fb373d9e-f779-11e7-9752-55a45bc68fee.png)

When you place one on the side of the other. 
![image](https://user-images.githubusercontent.com/33255536/34855367-23fa3e20-f77a-11e7-9720-5afe66c12e64.png)

**Comment by schlid** [comment]
one way to alleviate this issue shown by jack would be to make the vertex draw along the face connectr between the two opposing dots that are furthest apart, which would make mirrored designs a lot easier.

**Comment by JRL101** [comment]
OR a vertex in the centre of each face. 
Sadly that would make the processing of each cube more expensive. 
![image](https://user-images.githubusercontent.com/33255536/34902910-8e58a20c-f860-11e7-8853-fc7881db54b4.png)
Alternatively, you could have a front and back face with the X for a face.

**Comment by tsunamayo** [comment]
Okay so if I understand it is not an issue, just a tricky thing to take care when you are using the block?

**Comment by JRL101** [comment]
It can be solved with some visuals to indicate direction. and being able to rotate it like other blocks.

**Comment by Nauvran** [comment]
Normal 3D triangulation issue.
3D programs "fixes" this with smoothing groups (would be bad idea in this case since it's a voxel game)
and by allowing the user to change the triangulation of the blocks.
Im not sure if that is possible to do in unity but it would fix the issue.
Would need to find a way to allow players to choose two vertices and "connect" them to change the triangulation.
Reference from 3DS Max, stapled lines are the hidden triangulation (all 3D programs sees everything in tris but usually displays things in quads to make it easier for us)
http://puu.sh/zDPwA/7d52bd43bd.png
https://puu.sh/zDPwt/e262b27afb.png

**Comment by tsunamayo** [comment]
Issue no longer valid. Thanks!
