### ISSUE TITLE
[Experimental] Freeform block visual bug

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#519]
![20171224144045_1](https://user-images.githubusercontent.com/32974671/34329116-c511b3e0-e8b8-11e7-981a-0b6a35584c4f.jpg)
It was working just fine last night but now it seems like there are two in the same space and the effect is fairly static-looking. No mirrors are on so it should just be a simple visual bug.

**Comment by tsunamayo** [comment]
Hum could you please send me you bp, I will have to take a look at it! Thanks

**Comment by JRL101** [comment]
Looks like a mirrored block? There's a problem with mirroring Freeform blocks currently.

**Comment by JRL101** [comment]
if its not mirror it sure looks like it. Im assuming you tried to paint it?
I find painting some freeform blocks causes freeform blocks to spawn when painting wast the mesh edge.

**Comment by tsunamayo** [comment]
This issue should be fixed now. Thanks!
