### ISSUE TITLE
[Experimental] Glass painted black is solid black and overlaps UI [17w51b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#520]
Canopy bricks, sail slabs, and some of the canopy blocks that are painted black are
 no longer merely heavily tinted glass, but is pure black. Furthermore, the black color overlaps the interface instead of staying in the background.

![20171224153027_1](https://user-images.githubusercontent.com/33041786/34329285-3a8ef09a-e8c0-11e7-80a6-eff06af363e3.jpg)

![20171224153043_1](https://user-images.githubusercontent.com/33041786/34329286-3bef487c-e8c0-11e7-9d7c-deac4e8a6417.jpg)

![20171224154211_1](https://user-images.githubusercontent.com/33041786/34329313-2281baa4-e8c1-11e7-8ed3-fdfcf3f39c85.jpg)

**Comment by tsunamayo** [comment]
Very very weird indeed... I am not reproducing that issue.  What happen when you paint it with a different color? did you used the default black? Thanks

**Comment by Dwarf-LordPangolin** [comment]
I've only seen the problem occur when using a specific shade of black (0,0,0). All other colors show up normally (1,1,1 will show up as normal, heavily tinted glass).

**Comment by tsunamayo** [comment]
Okay I was able to reproduce with a custom black. Issue is fixed, now the min color is 1,1,1 (still pretty black  no worries). Cheers
