### ISSUE TITLE
Freeform block causing pre-existing blocks to dissapear in certain situations.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#521]
To reproduce this i'm going to walk you through the steps of how it happens.
![image](https://user-images.githubusercontent.com/31857052/34347285-7ef6c1ce-e9f9-11e7-9f10-f50fb7357a8e.png)
To begin, I had the freeform block in the top left, and the destination point in the bottom right, as shown above.
![image](https://user-images.githubusercontent.com/31857052/34347367-3fcb5414-e9fa-11e7-94d4-dc0f4dda5fbd.png)
I then connected the two points together to result in the shape above (vertices are in correct location aside from the visual bug present)
![image](https://user-images.githubusercontent.com/31857052/34347378-71e110e2-e9fa-11e7-85fb-ea28ce8c60aa.png)
After this is done, the whole diagonal section becomes unavailable to interact with, and creates a "ghost entity" where placing a block in the nearest surface which would cause a block to be adjacent to the ghosting area(purple block), resulting in a portion of the ghost area to disappear, with the remaining ghosted area having the surfaces next to the removed portion to have no texture.
![image](https://user-images.githubusercontent.com/31857052/34347430-0751c41e-e9fb-11e7-9cd0-4882ef1e6a1e.png)
The final image above shows what placing blocks did in regards to updating the ghosted area. Prior to getting rid of the ghosted area there was no visible  clipping from the freeform block, and when making the freeform block it allowed the creation without issues. A separate blueprint for yourself to replicate this is uploaded on discord as I don't wish to publically share this ship design.

**Comment by tsunamayo** [comment]
Hi, sorry to getting late on this, is this something you are still reproducing in recent build? Thanks

**Comment by AfterRebelion** [comment]
Freeformhad a rework, so this issue is no longer valid in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Issue no longer valid indeed. Thanks!
