### ISSUE TITLE
Can't launch game: "DX11 could not switch resolution". Unity issue I think

### ISSUE THREAD

**Issue by Cilvaa** [tsunamayo/Skywanderers#523]
Hello

I cannot launch the game on my desktop (but I can successfully launch the game on my laptop (which isn't viable as it's low-end and can barely run games)), every time I try I get this error:

![skywanderers issue](https://user-images.githubusercontent.com/12950850/34371458-16875f38-eb19-11e7-9d48-c4fb975681f4.png)

My searches on Google show it happens with a lot of games and is either a Unity issue or a driver issue. I've updated my AMD driver, and fiddled with the settings, to no avail.

Thoughts?

**Comment by tsunamayo** [comment]
Hi, somebody had this issue recently, he had to update its windows to fix it. I think it is linked to an out of date Directx on your windows (if it is the same issue). Thanks!

**Comment by tsunamayo** [comment]
Hi, please re-open if this issue was not fixed! Cheers
