### ISSUE TITLE
Colours on freeform blocks not being illuminated correctly.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#524]
When viewed in the sun they are seen correctly, as shown below 
![image](https://user-images.githubusercontent.com/31857052/34429812-59f19c1a-ec55-11e7-8d25-4ae88f7351ac.png)
Whereas the other side clearly shows how how it is incorrectly lit, with the dark areas being the freeform blocks.
![image](https://user-images.githubusercontent.com/31857052/34429826-8f9be9a6-ec55-11e7-8f05-793ad6e4c498.png)

**Comment by tsunamayo** [comment]
Thanks, issue was fixed. Cheers!
