### ISSUE TITLE
Lighting Bug with Symmetry

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#525]
When painting lights after placing them, the symmetrical blocks adjacent to the blocks being painted are changed on their actual model to the color that you set it as; however, only the side you physically paint change color for the lighting itself. 

I am running on version 17w51b

![20171231023430_1](https://user-images.githubusercontent.com/28989460/34460435-935ba2aa-edd3-11e7-9eda-53068d812f17.jpg)

(EDIT : Reloading the game appears to have fixed the issue, and I am unable to duplicate it as I do not know what originally caused it)

**Comment by tsunamayo** [comment]
Okay I not reproducing either - so I guess it was something else. Thanks!
