### ISSUE TITLE
[Crash][Graphical hardware support] 3440x1440 resolution not supported

### ISSUE THREAD

**Issue by clmd58** [tsunamayo/Skywanderers#526]
can't launch game on new 21:9 aspect ratio monitor, regardless of whether I set my resolution in windows back to 1920x1080. I'm running the game from steam, opted out of beta.
![image](https://user-images.githubusercontent.com/12486156/34465492-c820e3f0-ee74-11e7-9233-cdc60316fc1a.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1595561/output_log.txt)

**Comment by clmd58** [comment]
Seems to not be an issue after I opted into beta experimental version

**Comment by tsunamayo** [comment]
Hello, it seems that this issue is caused by a windows not up to date. Could you please update your windows and tell me if this fixed the bug? Thanks
