### ISSUE TITLE
Problem deleting child entities.

### ISSUE THREAD

**Issue by oojimaflip** [tsunamayo/Skywanderers#527]
deleting child entities appears to be broken/unreliable:
![20180104170446_1](https://user-images.githubusercontent.com/33450683/34575404-9384f57c-f172-11e7-9dfd-cf9a327e480e.jpg)

The entities floating above the main structure were deleted, their current position is not the position they were in when they were deleted. Some entities were deleted by using an ID block and others by deleting the hinge/rotor they were attached to. It was not clear if either of these methods produced more or less of the erroneous child entities. I have not yet found a way to delete these erroneous entities.
Also during the process of deleting (many, I know) child enitities some strange mirroring behaviour was observed, some times the deletion would result in the child entity next to the one I was actually deleting, being deleted, but not the symmetrically opposite child entity as one would expect.

[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/1604106/Save_Data.zip)

**Comment by Vicomt** [comment]
This appears to happen when a child that has sub-children is replaced. I posit that the sub-child are "oprhaned" and not cleaned up properly.

**Comment by tsunamayo** [comment]
This should be fixed. Thanks!
