### ISSUE TITLE
Hinges and their Child Entities' weight

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#529]
Hi!

When using two brick hinges in a row to have a child entity turn more than 90°, the first hinge doesn't take in account the weight of the child entity built from the second hinge.

In this example, 
_HINGE1_ will move 1Kg
_HINGE2_ will move 100Kg.

_HINGE1_ logistically should have to move 101Kg instead of 1Kg.

![sans titre-2](https://user-images.githubusercontent.com/33256107/34874866-16b29c1e-f79b-11e7-98e5-3fde2308c0b2.jpg)

**Comment by tsunamayo** [comment]
Yes this is something I didnt had time to code yet. Will keep you posted, cheers

**Comment by Name11ess** [comment]
Thank you!

**Comment by tsunamayo** [comment]
This should be fixed now. Thanks!
