### ISSUE TITLE
Application responds to mouse input when alt-tabbed out

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#530]
Start skywanderers in full screen mode with two people so that one can watch
start piloting a ship
hit tab to go into free-look
hit alt+tab to switch to another desktop application
observe the ship moving.

this behaviour is not normal, needed, or wanted for ANY reason I can think of.

**Comment by tsunamayo** [comment]
Hi, sorry to get back to you late, I am not sure to understand your test case.
Do you mean that the ship is not longer moving in a straight line but still responsive to player control?
In my test it was only moving in a straight line, which is the expected behaviour.
Thanks

**Comment by tsunamayo** [comment]
Okay nevermind I managed to reproduced indeed, and I fixed the issue. Thanks for reporting it! Cheers
