### ISSUE TITLE
Issues when buildings on Rings

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#531]
Hi! I've noted a few issues when building on rings:

1- Freeform block have an offset when placing them.
![ydy](https://user-images.githubusercontent.com/33256107/34959718-09f4a91e-fa38-11e7-8bbd-30163695131d.gif)

2- Game randomly crashes when building. But instead of a standard crash, it's a "Skywanderers has stopped working" from Windows.

3- In certain situations, the hitbox of blocks is wrong and the selection is only partial.
![ydy](https://user-images.githubusercontent.com/33256107/34959973-29df389c-fa39-11e7-9e33-dbaf37b6434b.gif)

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
