### ISSUE TITLE
[Experimental] Free-form paint issue

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#532]
I was replacing various hinge section in the ship with free-form blocks, saved, and exited the game as usual. Loaded back up to find the vast majority of the blocks got set to the default color.
![20180116154627_1](https://user-images.githubusercontent.com/32974671/35013883-745d436e-fad4-11e7-9775-ce5441debc2a.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1636959/output_log.txt)

**Comment by Xerma** [comment]
Apparently painting one updates few around it but not all

**Comment by JRL101** [comment]
Confirmed this happen to me too. The colour info doesn't seem to be updating on load.

**Comment by tsunamayo** [comment]
Okay issue is now fixed - thanks for reporting! Cheers
