### ISSUE TITLE
The color brown

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#534]
Not sure if this was brought to your attention before but the browns in this game seem to be very red
![20180118201842_1](https://user-images.githubusercontent.com/32974671/35132086-1cc5f6f2-fc8f-11e7-92ed-949f9ac3320f.jpg)

**Comment by schlid** [comment]
I believe tsuna used some of the lego colours, hence why we have bluish grey. I agree it is quite a clay coloured brown, maybe a darker one would be more appropriate

**Comment by tsunamayo** [comment]
Yes the color palette for now is not very good and has no inner logic in it. I will redo it when I work on the paint tool update, so I will close it for now. Thanks!
