### ISSUE TITLE
2 in 1 : Triangular Freeform & Freeform texture disapear

### ISSUE THREAD

**Issue by Clest1** [tsunamayo/Skywanderers#535]
English:
The creation of 2D triangle with freeform hull doesn't have a hitbox, we cannot either modify them, or delete them.
<a href="https://imgur.com/mvyXMkV"><img src="https://i.imgur.com/mvyXMkV.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/xVjlD7o"><img src="https://i.imgur.com/xVjlD7o.jpg" title="source: imgur.com" /></a>
Also, hull tech in version Freedom loses their textures and one random bloc get hull Basic texture each time I reloading a save.
<a href="https://imgur.com/Pmd9Uzx"><img src="https://i.imgur.com/Pmd9Uzx.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/QEwJniR"><img src="https://i.imgur.com/QEwJniR.jpg" title="source: imgur.com" /></a>
French:
La création de triangle en 2d avec les freeform hull ne possède pas de hitbox , on ne peut ni les modifier, ni les supprimer.
Aussi, les hull tech en version Freedom perdent leurs textures et deviennent des hull basic à chaque rechargement de sauvegarde.

**Comment by tsunamayo** [comment]
Okay issue is now fixed, now there is a check so you cant create a shape with 0 volume. The random hull tech disappearing is also fixed. Merci ^^
