### ISSUE TITLE
Toggling mirror mode on a mirror block results in mirrored blocks still being deleted

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#537]
Fig1: The mirror block is turned on and a block is placed, resulting in it mirroring on both sides 
![image](https://user-images.githubusercontent.com/31857052/35247155-3fa2c86e-ffc1-11e7-9196-f444f3a5c726.png)
Fig2: The mirror is turned off
![image](https://user-images.githubusercontent.com/31857052/35247173-4cae24e0-ffc1-11e7-9d74-934e170ac991.png)
Fig3: The block placed is destroyed, yet the mirrored block is also destroyed while the mirror isn't active.
![image](https://user-images.githubusercontent.com/31857052/35247193-62857a98-ffc1-11e7-919b-9ee2293a4214.png)

**Comment by Gamingclone** [comment]
I can verify that this happens (build 18w05a).

**Comment by tsunamayo** [comment]
Okay this issue is now fixed, thanks for reporting it! Cheers
