### ISSUE TITLE
[Suggestion] Align pilot camera with ship core rather than pilot body

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#538]
Would it be possible to set the locked view camera while flying to face the direction of the ship core, rather than the direction the pilot is facing? If the pilot's seat is tilted back at all, or oriented anything other than straight ahead, the external view is of the underside of the ship, and the in-cockpit view makes flying and aiming rather difficult, as the area directly ahead of the ship is not in the middle of the screen.

![20180122214141_1](https://user-images.githubusercontent.com/33041786/35257127-2802de64-ffbd-11e7-845d-fe5e6db39201.jpg)

**Comment by tsunamayo** [comment]
Thanks indeed, the game is now dealing with case like these , or when you are not seated at all. Thanks!
