### ISSUE TITLE
[Bug] Ringworld came along for the ride [18w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#539]
After starting up a new character, I jumped to a new star system. After saving the game and reloading, I discovered that the ringworld, along with all the ships and structures near it, had apparently come with me on the trip.

![20180123133308_1](https://user-images.githubusercontent.com/33041786/35296655-5aec891c-0042-11e8-883e-e5155e3c4874.jpg)

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
