### ISSUE TITLE
[Experimental] Mirror block visual bug

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#540]
![20180126090116_1](https://user-images.githubusercontent.com/32974671/35445538-8e47a238-0277-11e8-9625-a6d878b672f9.jpg)
The mirror block seems to show that it's off after you reload the game but still functions as it should. A simple fix is to just click it twice. Should note that it's on a child entity. To be exact: Main entity>child>child>child>child>child that has the mirror block
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1668142/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, mirror is saving its status now. Cheers
