### ISSUE TITLE
new hyper drive going plaid[Experimental]

### ISSUE THREAD

**Issue by BinHawkins42** [tsunamayo/Skywanderers#542]
so I've been testing the experimental branch and I went to try the new Hyper drive and the game frizzes and goes all sorts of strange colors. thought maybe it was my drivers but still did the same thing after installing the latest drivers. 
![20180203023903_1](https://user-images.githubusercontent.com/36099433/35765613-4a546fc2-088d-11e8-8003-a02b275ec3a3.jpg)
I have a nvidea GTX 970, I also have the latest drivers like I said. Here is the game log if that helps
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1691560/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
This can be reproduced when you get too far out of the system. Once you get to the edge of the system, the acceleration continues to increase, going up past the speed of light very rapidly. Let it go too high, and the game can't render things anymore.

![20180203113401_1](https://user-images.githubusercontent.com/33041786/35769831-d05d2c78-08d6-11e8-94ff-76b4fc0d439e.jpg)

This is the last picture I got before my computer gave up. Some sort of speed cap might be in order; even without the graphical bug, it's very easy to overshoot planets at the edge of the system.

**Comment by tsunamayo** [comment]
Oh okay thanks for reporting that, yes indeed I will need to do something so you dont get too far away too fast. I keep you posted, thanks.

**Comment by tsunamayo** [comment]
Hi, okay fixed it, now there is an actual limit. Thanks!
