### ISSUE TITLE
[EXPERIMENTAL] Hyperspace sound continues to play after button released early + Visual feedback suggestion

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#543]
This can lead to disorientation, as there is no other obvious physical stimuli to show if one is in normal space, or in Hyperspeed.

Perhaps some freedom to drop in and out quickly should be replaced with a very small "visual warp window" to allow a player to acclimatise first. In elite dangerous, this is usually the rendering/loading time but it certainly does help show that you have changed with the "warp tunnel" effect for a few seconds as you enter Supercruise.

**Comment by tsunamayo** [comment]
Hi, yes there indeed a bug with the sound, I think I will have to add a mini timer like in Elite to solve it neatly... Also I added a bit of a feedback with a shockwave and a change in FOV, plus some (subtle - not NMS like) to the hyperspeed itself, but I agree it still too subtle I will see what I can do. There is a different sound effect for thruster and a little HYP on the hud. Thanks

**Comment by AfterRebelion** [comment]
There is a visual indicator on the UI, so this issue is no longer valid in recent versions (19w23b)
