### ISSUE TITLE
[Bug] Multiple Turret Cores renaming themselves [18w05a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#545]
When multiple turret cores are placed on a ship, and one of them is named, the other will rename itself to match whatever was entered in the previous core's name box.

Naming the first core:
![20180205123546_1](https://user-images.githubusercontent.com/33041786/35822271-558d376c-0a71-11e8-8214-577ec5a14e14.jpg)

Opening the other core, everything looks good so far:
![20180205123550_1](https://user-images.githubusercontent.com/33041786/35822289-64d3c40c-0a71-11e8-9aee-2250bea4b260.jpg)

However, when the other core's name field is selected, it changes to this:
![20180205123551_1](https://user-images.githubusercontent.com/33041786/35822296-6ea197b6-0a71-11e8-94ca-ee61d4f76e6f.jpg)

Edit: as an update, the workaround for this is to name one core, save, exit the game, reload, name the second core, save, exit, and reload.

**Comment by oojimaflip** [comment]
can confirm, have seen this.
Turret cores on child enitites seem to be especially prone to odd behaviour: just entering configuration mode can clear the name

**Comment by tsunamayo** [comment]
Issue should be fixed now, thanks for spotting that! Cheers
