### ISSUE TITLE
[Bug] Joint turrets pointing wrong way [18w05a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#546]
When linking a turret core to a joint, the turret that is made will sometimes pitch 90 degrees back from where it ought to be pointed. The game appears to be taking the orientation of the player's head and adding 90 degrees to it, tilting the turret back. Sometimes the joint turrets appear to roll their orientation 180 degrees as well.

This bug is not occur on all joint-based turrets; some will display the bug, some will not.

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
