### ISSUE TITLE
[bug] Conflict of colliding standard and freeform from child entity [18w04a]

### ISSUE THREAD

**Issue by Clest1** [tsunamayo/Skywanderers#547]
Bonjour
When you create a Freeform block, create a child entity and build some blocks colliding with the freeform bloc of the mother entity, the block is placed on child entity but the graphics entity can't get showed with news blocks you add. After you set the block in the other freeform you can set one cube and then you can't editing nothing.
Exemple: I set a bloc colliding with freeform block
<a href="https://imgur.com/jBZteuu"><img src="https://i.imgur.com/jBZteuu.jpg" title="source: imgur.com" /></a>
Then i get this...
<a href="https://imgur.com/wgCsspy"><img src="https://i.imgur.com/wgCsspy.jpg" title="source: imgur.com" /></a>
I can add one more block... but i can't destroy anything
<a href="https://imgur.com/it84lJo"><img src="https://i.imgur.com/it84lJo.jpg" title="source: imgur.com" /></a>
When i save and restarting the game I can see it.
<a href="https://imgur.com/jtoexdp"><img src="https://i.imgur.com/jtoexdp.jpg" title="source: imgur.com" /></a>

**Comment by Clest1** [comment]
I got news.
Apparently is also arrive when you change the orientation of the thruster block before build it and remove some hull next.

**Comment by tsunamayo** [comment]
Issue is not longer applicable. Thanks!
