### ISSUE TITLE
[EXPERIMENTAL] Controlling a ship from a rotating chair points the wrong way

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#548]
In my shuttle03 and LongRangeFighter01 that both have a rotating pilot's chair, when I enter the ship the camera points 90 degrees to the left for the shuttle, and 90 degrees to the right for the longrangefighter. Flying the ship is still the same controls as if I was oriented correctly though.

**Comment by Womble-TC** [comment]
If it helps, I have noticed it can sometimes be related to the orientation in which the rotor block/brick was placed. Happens on quite a few ships of mine too.

**Comment by tsunamayo** [comment]
Okay yes it was a bug introduced with the new lock view feature. It is now fixed, thanks!
