### ISSUE TITLE
[Experimental] Ship went invisible but left nonexistent ghost in it's place. 

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#549]
Not sure how to explain this one. Basically I got into the ship to fly it, My player model flew away and it looked like the ship stayed. Returned to it but it was just a ghost.  

[error.log](https://github.com/tsunamayo/Skywanderers/files/1714432/error.log)

**Comment by tsunamayo** [comment]
Hum, not sure what happens, also the true log is output.log, error.log is not really interesting (yes it is confusing =( haha) Cheers

**Comment by tsunamayo** [comment]
issue should be deprecated. Thanks
