### ISSUE TITLE
[BUG] Random holes when placing large amount of blocks

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#55]
![image](https://cloud.githubusercontent.com/assets/8591667/24338975/79b2f50e-1266-11e7-8361-4c28af0e94f7.png)

Have this happening, they are large areas however when i save/exit and come back in, some are gone and some new ones show up at random areas.

Same location after load (load times are quite significant as well atm.  CPU/Mem/HD are all low however)

![image](https://cloud.githubusercontent.com/assets/8591667/24339095/e90931b6-1266-11e7-92f6-c62bfba309a0.png)

**Comment by Eldriken** [comment]
What is odd, is that with Mirror blocks on, the spot is identical in each region

![image](https://cloud.githubusercontent.com/assets/8591667/24339144/385c0c66-1267-11e7-9c12-ca3c3d344a10.png)

**Comment by Eldriken** [comment]
Fyi in addition to my bug report for the invisible blocks, those 4 spots remain constant which is odd as the others never cam back.  I notice that when I deleted the area, the outside blocks have only the top visible the sides and bottoms are invisible.  When I delete a block from the row the all come back, but only for that row.  As soon as I place a block however over the area, the side of the initial block is invisible but yet the next block is fully invisible and the block it connected to is also now invisible except for the top

I have a video but it wont upload to git

Think i found the combo that makes this happen, so laying a bunch of bricks over and over in big areas and every now and then an area glitches where they become invisible.  When I delete the area, the mirror block doesn't always delete the other spots, so when i lay it back down it glitches.  

After clearing all the areas that glitched, i saved, exited and came back in, I then found that some of the areas I deleted were back with invisible blocks.  So i delete those and some times after a restart I can fill them in, othertimes they are still invisible.

very odd behaviour

**Comment by Eldriken** [comment]
So more to this story,  After completing the fill in for the circle I have noticed that some areas can be cleaned up after you close the app and come back in (this is with the mirror blocks removed).  While some still can't until a second or third restart.  I also notice that more crop up after a restart that were not there before or that were just filled in.

Not really sure what the deal is, anything I can do to help troubleshoot let me know.

**Comment by tsunamayo** [comment]
Hello, could you please send me your save file, I would like to use it to investigate this issue. This is a chunk issue that have been bugging me for a while, it dont happen enough to investigate cleanly, but you seems to be able to reproduce often which could be great for me. 
Thanks !

**Comment by Eldriken** [comment]
Didn't​you get my email with the attachment??  Ok I will send again as soon
as I am at my computer this morning

**Comment by tsunamayo** [comment]
Ok thanks a lot for your help, thanks to the blueprint provided I was able to track down and fix the issue. Now I need to optimize loading time and also the rendering as it was very slow on my computer. ^^

**Comment by Eldriken** [comment]
Yea I noticed the slow down as well. It got progressively worse the more I
did.
