### ISSUE TITLE
[Experimental] Missing blocks forms

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#550]
Hello! It seems that with the last update, some blocks have been rendered unaccessible.
After a quick look, the 1/4 and 3/4 sized Hull Block aren't available anymore. Same for the 1x4 slope.

Since the Hull Block texture isn't available yet as a Freeform Block, those shapes aren't possible anymore.

**Comment by tsunamayo** [comment]
Yes I need to add those as freeform block, I did a bit of codex cleaning (and plan to do more...) Thanks

**Comment by Name11ess** [comment]
Alright, thank you!

**Comment by AfterRebelion** [comment]
This issue is no longer valid in recent versions (19w23b)
