### ISSUE TITLE
Lighting still bleeds after patch

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#551]
I reloaded the entity and save just to be sure, but the light bleeds as shown below 
![image](https://user-images.githubusercontent.com/31857052/36080193-422dd27c-0f84-11e8-94db-5549292eebed.png)

**Comment by schlid** [comment]
[ship download.zip](https://github.com/tsunamayo/Skywanderers/files/1714985/ship.download.zip)

**Comment by tsunamayo** [comment]
Hi! So I had a look, in fact you build the light on top of a children entity and not the main frame, and light is only blocked by block belonging to the same entity (One of the reason to limit children entity bonenza). You can build the light at the same spot but on top of the main hull and it will work.
Thanks!
