### ISSUE TITLE
Important stuff

### ISSUE THREAD

**Issue by LeMinaw** [tsunamayo/Skywanderers#552]
Hey,
Sorry for bothering you here, but something important is coming.

@tsunamayo tu peux checker tes mails rapidos s'il te plaît?
(Insupportable ces gens, on peut être tranquille nulle part :v)

**Comment by tsunamayo** [comment]
haha desole oui j ai renew la sub pour le site ;-).
Desole je recevait mes parents pour une semaine...
A +
