### ISSUE TITLE
my hovercraft i built rotated "orientation" after the most recent update and now flies the wrong direction.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#553]
![image](https://user-images.githubusercontent.com/31857052/36334161-44822184-1373-11e8-989d-1b4053903854.png)

**Comment by schlid** [comment]
[jetpack.zip](https://github.com/tsunamayo/Skywanderers/files/1733135/jetpack.zip)

**Comment by tsunamayo** [comment]
Okay I am not sure why your (absolutely lovely) jetpack is now going in the wrong direction, it seems that the block is simply not oriented correctly. But it is crappy I know, I must have something better to highlight and change the direction, I will work on a solution.

**Comment by schlid** [comment]
The point I tried to make is that it flew straight forward without an issue pre update, But now, it goes sideways. I've even rebuilt the jetpack absolutely checking i was going in the correct orientation, and it still goes sideways.

**Comment by tsunamayo** [comment]
No longer applicable. Cheers
