### ISSUE TITLE
[Suggestion] Toggle Double crouch to align with object

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#557]
Hello!

Would that be possible to have an option to toggle the ability to align with an object using the double-crouch shortcut?

The option is now available using the middle mouse menu, which can make the second option redundant.
The double-crouch shortcut can also be a pain in the ass when trying to build while being upside-down.

**Comment by tsunamayo** [comment]
Yes actually I will remove it completely it is redundant. Thanks

**Comment by tsunamayo** [comment]
Okay it is now removed from the game. Cheers

**Comment by Name11ess** [comment]
Thank you!
