### ISSUE TITLE
Please add more normal Window blocks vs Canopy windows

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#56]
Currently with the existing window block you can only have it go one way, and even then the corners do not connect up so you have a space.

It would be very cool, if like the hull blocks you had the slopes and angles for the Window block then alot more could be done.

I know you chatted about Force fields, I do think even still more windows are needed.

Thanks

**Comment by tsunamayo** [comment]
edited title and added correct label

**Comment by tsunamayo** [comment]
Okay we have more window option with tile, wedge and tetra. Thanks!
