### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by mahmedov** [tsunamayo/Skywanderers#561]
Hello! Is it possible to make this game compatible for MacOS in the future? It would be nice to play with my other friends who only have Mac computers.

**Comment by CyaNox** [comment]
This is answered on the [skywanders kickstarter page](https://www.kickstarter.com/projects/skywanderers/skywanderers)

## Will the game be released on Mac, Linux or Consoles?

Skywanderers makes heavy use of DX11. Porting to other platforms is out of scope of this kickstarter as it would take me too much time at the detriment of the game. It might change in the future though!
