### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by devdot4** [tsunamayo/Skywanderers#562]
This repo needs a readme.md, do you accept contributions by other developers to make a well written readme.md? Thanks.

**Comment by LeMinaw** [comment]
I'm not sure we really need one.

What to submit here is quite straightforward plus we don't use a specific or recurrent template.

People will likely never land on this repo without knowing what Skywanderers is.

**Comment by tsunamayo** [comment]
Hi @devdot4 sorry I just saw this. Yes we could add one that wouldnt hurt! If you want to submit something  I will gladly add it. Cheers

**Comment by devdot4** [comment]
Hello @tsunamayo , Thank you for giving permission to contribute onto the repo. Is it possible for you or someone who has access to the repo to generate readme.md? Thanks.

**Comment by CyaNox** [comment]
This has been created now. Thanks.

https://github.com/tsunamayo/Skywanderers/blob/master/README.md
