### ISSUE TITLE
Deleting blocks can delete unintended blocks.

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#563]
When deleting blocks (definitely using shift+delete, not sure about normal delete, I never use it) if you raycast through the empty space in another block infront, the block in front is sometimes deleted along with whatever else you select.

It's fairly reproducible, but not consistently, and depends greatly on where the raycast goes through the block in front, and can be very frustrating when it happens to a freeform block that's taken ages to get just right.

**Comment by tsunamayo** [comment]
Okay this issue is now fixed! Cheers
