### ISSUE TITLE
While using the maneuvering controls, quickly switching to an opposite key causes the ship to keep moving in the first direction.

### ISSUE THREAD

**Issue by etn249** [tsunamayo/Skywanderers#568]
Steps
1-Enter a ship's cockpit.
2-Press the right maneuvering key.
3-As the ship is moving to the right, let go of the right key and quickly press the left maneuvering key before the ship stops moving completely.
4-Notice that the ship now keeps moving to the right while the left key is pressed.

precisions:
-This happens in every direction.
-While pressing the opposite key, the ship re-accelerates towards the first direction as if the original key had been pressed.
-While the opposite movement is happening, rotating or moving the ship causes the movement to slowly correct itself and return to normal.

**Comment by tsunamayo** [comment]
This is issue was fixed some time ago. Thanks
