### ISSUE TITLE
[18w09b] Specific blueprint spawns transparent except for switches, attempting to reload world results in "infinite load" hang

### ISSUE THREAD

**Issue by peanutthegreat** [tsunamayo/Skywanderers#569]
I restarted the game after working on a ship for a while and found that any world with that ship spawned in it won't load. In a fresh world the ship will spawn transparent except for it's switches and that world will no longer load after restarting the game.

[GSV Triumph.zip](https://github.com/tsunamayo/Skywanderers/files/1777169/GSV.Triumph.zip)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1777170/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
That sounds a lot like an issue I ran into before. Looks like it might have made a comeback; good catch!

https://github.com/tsunamayo/Skywanderers/issues/420

**Comment by tsunamayo** [comment]
Issue should no longer happens. thanks
