### ISSUE TITLE
Custom paint:  Child entity copy issue

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#57]
![image](https://cloud.githubusercontent.com/assets/25937107/24519291/90560d0a-157c-11e7-8077-17f12ef58af9.png)

Apparently if an entity has been painted in a custom colour and you copy it some colour issues appear.

![image](https://cloud.githubusercontent.com/assets/25937107/24519352/c59367c4-157c-11e7-824a-f2eddef179d8.png)

**Comment by tsunamayo** [comment]
Issue will be fixed in next build. Thanks !
