### ISSUE TITLE
Removing seat glitches player into the ground

### ISSUE THREAD

**Issue by AUTplayed** [tsunamayo/Skywanderers#573]
As you can see in the video, removing a seat glitches the player into the ground far away.

https://i.imgur.com/CVsRbbE.mp4

**Comment by CyaNox** [comment]
Possibly a duplicate of #570 or perhaps a regression? What version are you experiencing this in?

**Comment by AUTplayed** [comment]
18w09b

**Comment by tsunamayo** [comment]
Hi, yes it was a duplicate and the fix is live now, thanks for reporting that @AUTplayed. @CyaNox glad to see you, hope you are doing good! Cheers
