### ISSUE TITLE
Adding complexity to the structure results in custom colour loss

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#575]
adding geometrical complexity to a structure can result in custom coloured object reverting to their default colour, this seems to be on child entities only.

![20180311230219_1](https://user-images.githubusercontent.com/7197427/37259648-e29628d8-2580-11e8-8a99-a117c4eae681.jpg)
![20180311230223_1](https://user-images.githubusercontent.com/7197427/37259649-e2adaa6c-2580-11e8-9b25-43751ce16ec9.jpg)
![20180311230233_1](https://user-images.githubusercontent.com/7197427/37259650-e2c549c4-2580-11e8-9b87-217633169b93.jpg)
![20180311230249_1](https://user-images.githubusercontent.com/7197427/37259651-e2dd477c-2580-11e8-9482-3e78d4f2e43f.jpg)

[Leviathan.zip](https://github.com/tsunamayo/Skywanderers/files/1800977/Leviathan.zip)

**Comment by tsunamayo** [comment]
Issue should now be fixed! Thanks
