### ISSUE TITLE
Missile Launchers Can't Fire a Moving Missile

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#576]
As the title would suggest, when a missile launcher is activated, as of the latest patch, a missile is spawned at the nose of the missile block, but the missile has no momentum. It simply sits in front of the missile block. I cant be 100% sure missile launchers aren't working, however, I am positive guided missiles aren't working.

**Comment by tsunamayo** [comment]
Issue no longer applicable.
