### ISSUE TITLE
[BUG] Light bricks have rotated themselves [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#577]
After the latest update, it appears that some of the light bricks have decided to rotate themselves 90 or 180 degrees. 

![20180312130142_1](https://user-images.githubusercontent.com/33041786/37301368-6270223c-25f6-11e8-9c6c-d944ec6d00af.jpg)

![20180312130150_1](https://user-images.githubusercontent.com/33041786/37301371-654b248e-25f6-11e8-8a08-82c37aae96e1.jpg)

**Comment by tsunamayo** [comment]
Do you have by any chance the blueprint of back then? I never saw this issue so I cant reproduce... Cheers

**Comment by LeMinaw** [comment]
I experienced this too.
This looks kind of erratic, but it happens quite frequently when placing lights on grid panels.
The light stand in good orientation, but after adding or removing a few blocks next to it, it rotates by 90°.

**Comment by tsunamayo** [comment]
Issue should no longer happen right? If not please ping me! Thanks
