### ISSUE TITLE
Game dies when spawning ships

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#579]
On occasions I have noticed that when loading in a ship into a world with a number of ships already loaded the game will drop to unbearable frames and nothing happens with the ship spawning. Then when you attempt to place a new block in this state the screen freezes. The game is still running in the background as if you press space the menu sound is heard and the mouse appears but no menu appears. 

I have noticed this twice in particular. While trying to load the nebulon B frigate and while trying to load the ISD. It does seem size is a factor and I do wonder if it is to do with how many ships already exist in the save.

Here is the output.log which does seem to show some form of errors.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1803982/output_log.txt)

**Comment by Vicomt** [comment]
we call this the black hole effect - when the ship is spawned, it seems to start attempting to build, then it just gets locked in a loop somewhere, continuously allocating memory and chewing up FPS. the longer you leave it, the lower the FPS goes. we've seen it when attempting to spawn EITHER Leviathan when Mephistopheles is in the playfield, OR Mephistopheles when Leviathan is in the playfield.

**Comment by tsunamayo** [comment]
Hi, I think you guys are hitting the entity limit... There is a limit of 1000 (!) entities, it seems you are breaching that sometime. I will put a safeguard that will prevent a loading for now so the game dont crash. 
But moving forward I will have to put all sort of limits so the game dont lag in multi for example. Locally you would be able to edit a config file just for you but on a server that would not be possible. I will also show them in the identity screen so it is clear for the builder.

I am curious how did you get to these massive number of children entity? Do you have screenshot to share? Cheers

**Comment by Vicomt** [comment]
That limit of 1000 entities, is that within the entire playfield, or within a single parent? there's no way we hit that within a single parent, but it's possible that we could hit it in multiple ships. the latest versions seem to not do the same thing however, when we see issues bringing ships in, they lose their parent and only bring in some of the children.

**Comment by gmunga5** [comment]
I get this when trying to spawn the ISD which kind of explains why it would hit the max entity limit. When was that introduced?

**Comment by Vicomt** [comment]
we've actually counted up all our entities and can't get anywhere near 1000, maybe 500 tops with almost every single ship we've ever made

now, we USED to have this when we spawned both Mephistopheles and Leviathan, however NOW, we can spawn Meph, Lev, and other ships before seeing this kind of issue. I'll get hold of the BP's that cause it and them to this report if I can.

**Comment by tsunamayo** [comment]
@gmunga5 @Vicomt Could you please send me a few of these large blueprint so I can handle the limit breach nicely in the game?

Actually the torus is eating quite a bit of them (300), so that could explain going to over 1000. I will bump up the limit temporarily but just please be aware guys that I will have to fight this as the number of entity have implication on the rendering load but also the physics computation, so I will have to take measure to keep it down.  I guess I should have been more careful at first :-p
I created the freeform block to give freedom in an optimized way. I want to create a cylindrical freeform shape also, as I saw a big offender was when you guys want to create rounded shape.
Cheers

**Comment by gmunga5** [comment]
this is the isd had to zip it due to the file type

[ISD Updated state new november 5.zip](https://github.com/tsunamayo/Skywanderers/files/1859604/ISD.Updated.state.new.november.5.zip)

**Comment by oojimaflip** [comment]
here is our largest/most complex...

[TWS Leviathan.zip](https://github.com/tsunamayo/Skywanderers/files/1861723/TWS.Leviathan.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
