### ISSUE TITLE
[BUG] Changing paint colors locks the system up on Child objects

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#58]
This only happens with Child object.

What this pic doesn't show is the blue arrow mouse in the middle, I can move the mouse, drag and drop items on the bar, but hitting escape or tab doesn't work at all, I have to click the X to close the game.

![image](https://cloud.githubusercontent.com/assets/8591667/24527604/22fb44bc-1560-11e7-946d-34ed68607df5.png)

**Comment by tsunamayo** [comment]
I fixed this issue on a new build, did you redownloaded the build ? Cheers
