### ISSUE TITLE
[BUG] Right Clicking Only Gives Output of -1

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#583]
Unlike before where right-clicking toggled buttons, lights, and mirror blocks, now it will only turn stuff off/output -1. For example, if you right-click a mirror block, you can turn it off, but not turn it on again.

**Comment by Sullos** [comment]
Also the same as my post #571 :)

**Comment by CyaNox** [comment]
Duplicate of #571.
