### ISSUE TITLE
Logic Connection Lines Bug

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#584]
I don't know how to explain this too well, but I made a very short video hopefully showing you as best as I can, just what is happening..
https://youtu.be/pGKigZaflPs

**Comment by talrey** [comment]
This is happening for me as well, in the experimental branch.

**Comment by tsunamayo** [comment]
Yes I saw that also, I will have a look at it, also Link and Command will get a big overhaul. Thanks!

**Comment by tsunamayo** [comment]
It should not happen with the (not so) new logic link tool. Thanks
