### ISSUE TITLE
Shields Blocks Not Connecting as Part of a Network When Capacitors Inbetween

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#585]
A long and convoluted title, but I will do my best to explain,
![screenshot_95](https://user-images.githubusercontent.com/33239800/37386236-ab4a0002-27ab-11e8-9664-e829379f2c7e.png)
The image should give a general idea of the problem. It could be intended to be this way, but what it means is that if someone tries to disable their shields with a switch.. and they have a fancy design, like so..
![20180314170202_1](https://user-images.githubusercontent.com/33239800/37386279-cfa9f31c-27ab-11e8-86b0-c47f57afd91c.jpg)
It means that to disable the shields, you have to connect a switch to every single grouped set of shield blocks, and in the conditions of the above picture, 100's of switches / logic lines would need to be connected in a massive network to simply disable the shields of a ship.

As best I can tell, all that needs to happen is IF a switch is connected to one Shield Block, it should also 'network' with Shield Blocks around it, as well as Shield Blocks connected to Capacitors which are connected to Shield Blocks. Meaning that Capacitors no longer separate Shield Blocks but also act as a Conduit connecting multiple Shield Block groups.

**Comment by tsunamayo** [comment]
Issue no longer applicable in the new framework. You cant make sexy stuff like that anymore but the code is much more manageable for me!
Thanks!
