### ISSUE TITLE
Game crashed when placing hose

### ISSUE THREAD

**Issue by LeMinaw** [tsunamayo/Skywanderers#587]
I tried to redo the things I've done in order to provide a test case, but since the crash occured a lot of time after my last save, I was unable to do this.

Here's the err log and the dump.
 
[error.log](https://github.com/tsunamayo/Skywanderers/files/1813479/error.log)

[crash.zip](https://github.com/tsunamayo/Skywanderers/files/1813480/crash.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
