### ISSUE TITLE
[Bug] Some freeform shapes no longer possible [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#588]
Since the most recent update, certain shapes can no longer be made with the freeform block. Here are some examples:

![20180315173951_1](https://user-images.githubusercontent.com/33041786/37532261-7ea46526-290c-11e8-8e4f-b41aca0f3dd1.jpg)

![20180314225930_1](https://user-images.githubusercontent.com/33041786/37532281-900fe8d0-290c-11e8-9d59-8326bd364648.jpg)

![20180314231142_1](https://user-images.githubusercontent.com/33041786/37532282-92d03700-290c-11e8-96bc-a92741bb6d7d.jpg)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
