### ISSUE TITLE
Strange effects happen when destroying the last shield block on a ship. [18w11a]

### ISSUE THREAD

**Issue by etn249** [tsunamayo/Skywanderers#589]
Steps (2 ways to produce the same issue):

first way
1-Place a shield block on the outside of a ship, where it can easily be shot.
2-Drive a ship that has at least 1 laser brick and aim at the shield block.
3-Shoot rapidly until the shield goes down, then keep shooting until the shield block is destroyed.
4-As the shield block is destroyed, keep firing rapidly. 
5-You will notice that as you keep firing, the animation of the shield disappearing cannot play properly and that the shield bubble now visually remains around the ship forever, even after you stop shooting.

second way
1-Place a shield block on the outside of a ship, where it can easily be shot.
2-Drive a ship that has at least 1 laser brick and aim at the shield block.
3-Take down the shield, shoot until you destroy the shield block with a single shot, then stop shooting and wait for the shield bubble to finish disappearing.
4-After the animation of the shield disappearing has finished playing, shoot again at the ship. You will notice that even though the last shield block has been destroyed, the shield bubble will still be there and that you can destroy it a second time.
5-After that second shield bubble has disappeared, go put a new shield block on the ship.
6-Notice that a shield bubble visually appears, which lasts forever.

details:
-The eternal bubble effect is only visual, the shield has no effect on weapons.
-The eternal bubble effect disappears when saving and reloading.

**Comment by tsunamayo** [comment]
Okay this issue seems to be now fixed. Thanks
