### ISSUE TITLE
Camera orientation issue on control block

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#590]
[Sublime.zip](https://github.com/tsunamayo/Skywanderers/files/1823036/Sublime.zip)

[pre-alpha 18w11a]
I'm having an issue with this ship build. I've got several working ships, so I'm not sure what's going on here. I've got the cockpit setup on this build and linked to the ship core block. When I sit in the cockpit (or simply enter the control block) the camera rotates up and left as if the ship orientation is completely different from the core. I can't seem to figure out why this is happening, so I think it might be a bug.

**Comment by tsunamayo** [comment]
We now have a new ship orientation logic. Thanks
