### ISSUE TITLE
lighting glitch in hyperspeed

### ISSUE THREAD

**Issue by Greenjoe12345** [tsunamayo/Skywanderers#594]
so, i was testing around with ship controls, and when I made a ship go into hyperspeed, and then look around the bridge of it, when I look to the sides, the lighting on the ship seems to go out, making everything dark except for the glow of the control panels
the name showing on a button also did not show
https://imgur.com/a/2yXxh
Here is an image of the error

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks
