### ISSUE TITLE
Invisible block

### ISSUE THREAD

**Issue by Sloooth** [tsunamayo/Skywanderers#595]
![image](https://user-images.githubusercontent.com/37549685/37616316-6affc478-2ba7-11e8-9360-b1e0e652d4e3.png)
![image](https://user-images.githubusercontent.com/37549685/37616328-74217a88-2ba7-11e8-9c5e-8b466455414e.png)

**Comment by tsunamayo** [comment]
Hi, do you remember what you did to have this? Thanks

**Comment by tsunamayo** [comment]
Okay I have been able to reproduce this bug (it was on delete)! It is now fixed, cheers
