### ISSUE TITLE
Slider Extension Glitch

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#596]
So this glitch has been in the game for a few updates now and no one posted it here. I think everyone though someone else would do it.

In a nutshell, when placing down slider extensions, it always stops at one before the end. To get it to the place you wanted, you have to put down one extra and update the slider. After it is updated, you can delete the extra slider. This is for both the normal slider (in the gif) and the thin slider

[https://media.giphy.com/media/lpGT9FpPW7ZIfwXIto/giphy.gif](url)

**Comment by ZachZent** [comment]
Apparently that link has been said not to work for all so here is an updated link using a different source
https://imgur.com/a/xuZp0

**Comment by tsunamayo** [comment]
I cant reproduce this bug. Are you able to reproduce 100% of the time? Thanks

**Comment by ZachZent** [comment]
The bug was fixed during the last update. Intentional or not, it working so good job :D

**Comment by tsunamayo** [comment]
haha I like it when issue are fixing themselves :-p
