### ISSUE TITLE
[Bug] Ship has -150 shields [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#597]
For some reason, placing a single shield unit on a ship gives it a negative shield value of -150 points. Placing a second brings it up to 0, while attaching a capacitor gives it 50 points. I'm attaching the blueprint, as I cannot find another way to reproduce the error.

[Negative shield blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/1826824/Negative.shield.blueprint.zip)

**Comment by tsunamayo** [comment]
Hi, I cant reproduce your bug. Are you able to reproduce it with any new ship? Your ship reads 50hp when I load it. Thanks

**Comment by tsunamayo** [comment]
Okay I just fixed a few issues that could have explained the weird behaviour, mainly if you add and remove new shield block many time. Please re-open if issue is not actually fixed! Cheers
