### ISSUE TITLE
Key Mappings

### ISSUE THREAD

**Issue by Tarnadas** [tsunamayo/Skywanderers#599]
I just installed the game and my initial key mappings had two issues:
- left and right were inverted. Left was set to D, right was set to A
- I expected the jump / move up key to be set to space and the crouch / move down key to be set to left shift or ctrl but they were only set to Q and E. I don't find this intuitive

**Comment by tsunamayo** [comment]
Okay noted, I think I will do the change for crouch / jump. For Left and Right the issue was fixed but the fix is in experimental, so it will have to wait for the next release to be in main. Cheers
