### ISSUE TITLE
Resolution settings and GUI scaling

### ISSUE THREAD

**Issue by Tarnadas** [tsunamayo/Skywanderers#600]
While being in-game, I wasn't able to select all resolution settings:

![resolution bug](https://i.imgur.com/P5NO8NQ.jpg)

After changing the resolution from 4k to 1080p, my GUI was much bigger and I couldn't navigate through the whole GUI. This only happens while in-game. When I'm at the title screen, the GUI scaling is fine:

![gui scaling bug](https://i.imgur.com/Q3fNzLZ.jpg)

I have a 4k monitor FYI

**Comment by tsunamayo** [comment]
Okay this should be better now, the scaling will be like on the start menu. But me only having an 1080p I am not sure of the end result - like do you prefer scaling or have just smaller GUI element for example? Cheers
