### ISSUE TITLE
Two suggestions - Freeform, Weapon Crafting (future)

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#601]
1. Freeform
Right now, the freeform blocks are great, but they don't replace the speed of normal blocks. It takes much more time then it would to just place normal blocks. So rather then having one freeform block, make every block freeform-able. Let any (base) block be freeformed. Little modifications will become easy when you can just modify a half slab rather then form it though one normal block. The codex will be simplified and freeform will become more then just an extra shape maker.

2. Weapons crafting
I know that it was taken out and planned to be added much later. We did see it on your devlog for shields. Though I know it are still problems, one of the biggest problems (besides it working) is in how you build it. With only bricks, there is a very limited number of creations you can make without it getting super big. Bricks have their limits for detailing a small space. All weapons one could make will come out looking blocky and crude. So rather then having a player build with only blocks, minimize the normal game. Players can place down normal blocks in the weapon crafting table, except it will be brick size. With that, bricks will now become mini-brick sized. Enough to fine detail a hand held weapon to something that looks really good. Especially with glowing tubes. Though this is more design, if it would bring a new creative element to gun building. Something no other game has done

**Comment by tsunamayo** [comment]
Hi,
1) Yes I was thinking about that, but I will need to optimize the way they are stored first.
2) I wont do that but yes one of the reason I didnt release the weapon craft is because I need more interesting looking bricks.
Cheers

**Comment by ZachZent** [comment]
1. Glad to hear it
2. That is a shame, but as a quick "before the fact," it is not the amount of bricks that is one of the main issues. The amount of detail you can put into three or four bricks of space is very limited, unless you plan to make the bricks very small for weapon crafting. If you look at your "pistol" (one handle, one brick, one laser) you can tell that it is already quite large and that there isn't much more room to add detail before the weapon becomes way too long or way too thick. People want to hold a rifle, not a BFG :D . Maybe you have a solution in your head for this or maybe you will cross the bridge when it comes to it (both justified and acceptable) 

Can't wait to see what is next

**Comment by Psyckosama** [comment]
I'll second ZachZent on both issues. 

Though I'd like to suggest to Tsunamayo that perhaps he should consider reintroducing them now and optimizing later?

I'd also add that this system would allow for the use of logic blocks in weapons, allowing for things like burst fire, scoped weapons (if camera zoom is ever added), and manpack seeker missiles. 

Though along those lines, the damage output should scale down appropriately.

**Comment by tsunamayo** [comment]
We now have free-scale block like you suggested! Hand-held weapon are still on the roadmap. Thanks
