### ISSUE TITLE
Tried to change keybindings, then couldnt move

### ISSUE THREAD

**Issue by TheFlyingFart** [tsunamayo/Skywanderers#602]
read title

**Comment by tsunamayo** [comment]
Hi, could you please tell me which key did you keybind to which action, and also send me the log file from
C:\Users\{USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\output_log.txt
Thanks

**Comment by TheFlyingFart** [comment]
A was strafe right and D was strafe left, and I switched them, and it
jammed, then I opened a new world, did the same thing and it was fine.

**Comment by tsunamayo** [comment]
Is it something you can reproduce? When you cannot move did you tried to move forward and backward also? Thanks

**Comment by TheFlyingFart** [comment]
I tried again on a new world, and the character controls worked fine, but
then I couldn't move vehicles.
