### ISSUE TITLE
Teleported in ring's ground when removing block

### ISSUE THREAD

**Issue by john-gros** [tsunamayo/Skywanderers#603]
![bug](https://user-images.githubusercontent.com/20044552/37671906-0798ab04-2c6d-11e8-982b-c32f7349e424.png)

As you can see in the screenshot, I was teleported underground when I tried to remove a chair from a new building.

The two builds in the screenshot are the initial hovercraft and the small blue mech, not touched since the start of this world, meaning I was moved near the starting position (maybe the "origin" of the world ?).

**Comment by john-gros** [comment]
After more test, I can give blocks' name that cause this problem: the chair and the seats (the 2 with this name). I thought this happened when placed on a panel/brick but it's the same on normal blocks.

I did not checked all blocks but I can if asked.

**Comment by ProPeach** [comment]
I believe this is the same issue as #573, which is fixed in the experimental version of the game. Thanks for the report!

**Comment by john-gros** [comment]
I just switched to experimental to test it and it is fixed.

Thank you!
