### ISSUE TITLE
Mech Base Joints

### ISSUE THREAD

**Issue by XinBane** [tsunamayo/Skywanderers#605]
When placing a Base Joint it puts the part to attach to where the starter block is/was no matter where it is/was in turn can't build legs, arms, or heads.

**Comment by XinBane** [comment]
Experimental and non experimental by the way.

**Comment by Senakysam** [comment]
Respawning the blueprint will spawn the child entity in the correct position. Here's a pic of what's happening:
![20180322141221_1](https://user-images.githubusercontent.com/26584892/37792968-4e9e14de-2ddb-11e8-929f-ce106af28717.jpg)

**Comment by tsunamayo** [comment]
Okay this one will be fixed in next update. Thanks!
