### ISSUE TITLE
[Bug] Game not spawning tutorial buildings on torus in new game [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#606]
The various tutorial buildings are not showing up when new games are created. This occurs even with a completely fresh installation. The ships, mechs, and other creations are, however.

I'm attaching the Instance file and WorldEntities directory in case they're relevant.

[No tutorial buildings bug.zip](https://github.com/tsunamayo/Skywanderers/files/1835107/No.tutorial.buildings.bug.zip)

**Comment by tsunamayo** [comment]
I fixed this issue is the new update, in experimental. Thanks!
