### ISSUE TITLE
Game forzen when zooming on galaxy map

### ISSUE THREAD

**Issue by Xxxsquidlover101xxX** [tsunamayo/Skywanderers#607]
I've seen some slight improbements on the game's Galaxy map. Allthough, lately, the Galaxy map can be opened. The problema comes in when zooming in, you can place the eye marker but if you zoom in it crashes

**Comment by tsunamayo** [comment]
Hum it dont crash for me but Holomap will get a complete overhaul and be less buggy. Thanks

**Comment by Napther** [comment]
This bug is related to, if not the same as, #126 

If your GPU is bad, then you're out of luck for now.

![image](https://user-images.githubusercontent.com/33023316/38707681-3c626772-3eaa-11e8-9230-33b6ef0c96ea.png)

**Comment by tsunamayo** [comment]
Deprecated. Thanks
