### ISSUE TITLE
[Bug] Multiple directories created in WorldEntities directory [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#609]
After a short time playing, the game generates multiple folders in the game's WorldEntities folder. This error has occurred multiple times after fresh reinstallations. I have not pinned down the precise conditions that cause this to occur, but it appears to be connected to creating multiple characters that have traveled to different systems. It may also be connected with the bug that causes the torus to "follow" the player.

![Uploading Multiple WorldEntities Bug.JPG…]()

**Comment by tsunamayo** [comment]
Hi, how many directory? Yes it will create a folder for each system, real issue is more the torus following you. I will fix that. Cheers
