### ISSUE TITLE
[SUGGESTION] Afterburners

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#611]
I think every ship should have access to afterburner. Holding shift or some other key would give you a speed boost. It would be great for taking off, escaping the atmosphere, or combat maneuvers, at the cost of a higher fuel consumption.

**Comment by BruceLeedleLeedleLeedleLee** [comment]
and a short burst of massive heat generation maybe!

**Comment by tsunamayo** [comment]
So I have think again on spaceship control, what I will try is the following:
Base control would be 6dof. This will be mandatory for exploring, mining, and of course docking/landing. Compared to now it means that Maneuver will be more powerfull. 
Max speed would be lower but still workable (like 100m/s)
Then when boosting control change to the plane control. So you have a better control of your trajectory, can dogfight and be harder to shoot ect. Max speed would be much higher of course.
That way I could get rid of throttle control, as when you want to boost you usually wants to go full speed.
In the game I call 6dof = Momentum Cancelling, and plane like = Momentum Vectoring.
I keep you posted.

**Comment by tsunamayo** [comment]
We now have boost, kind of an after burner except there is no real fuel yet. Thanks!
