### ISSUE TITLE
Hovercraft not aligning to the ground in the torus structure.

### ISSUE THREAD

**Issue by BruceLeedleLeedleLeedleLee** [tsunamayo/Skywanderers#614]
What the title says. (i am on experimental branch)
I tried driving a hovercraft along the torus, and ended up with this https://imgur.com/a/4hLqR , because it didnt update the alignment.
This issue doesnt apply for mechs.

**Comment by tsunamayo** [comment]
This should not happen with the new Hovercraft tech. Cheers
