### ISSUE TITLE
[Experimental] [Bug] Sections of paint randomly not showing on big blocks.

### ISSUE THREAD

**Issue by BruceLeedleLeedleLeedleLee** [tsunamayo/Skywanderers#615]
It seems that blocks occasionally do not show their color when painted, and appear in standard color.

Examples:
Original:
https://imgur.com/a/XdyRE
With Bug:
https://imgur.com/a/HSLn1

**Comment by Dwarf-LordPangolin** [comment]
To add to this: sometimes when this occurs, repainting a single block in a standard color section will cause what appears to be the entire chunk to "remember" its color. However, this may also cause another chunk to sometimes revert to the default color.

Thus, painting the small grey strip on the right in this picture:
![20180323215036_1](https://user-images.githubusercontent.com/33041786/37859618-7e755dc0-2ee4-11e8-8dc0-00acee6c6584.jpg)


Results in this; the strip gets fixed, but another large section turns grey.
![20180323215038_1](https://user-images.githubusercontent.com/33041786/37859620-81b758c6-2ee4-11e8-86ac-4f973c44fd16.jpg)

**Comment by tsunamayo** [comment]
It seems related to a freeform issue. Is it something that you reproduce often?
@BruceLeedleLeedleLeedleLee @Dwarf-LordPangolin  as I am having trouble to reproduce that issue could you please send me your (nice looking) ship? thanks

**Comment by BruceLeedleLeedleLeedleLee** [comment]
It's a bug that sort of accumulates over time, it currently happens in stable build. the more ships you have in your world, the more often it appears. It doesnt seem to be related to specific ships. 
[Type-4.zip](https://github.com/tsunamayo/Skywanderers/files/1847609/Type-4.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
