### ISSUE TITLE
Suggestion: Weapon Customization

### ISSUE THREAD

**Issue by weylin6** [tsunamayo/Skywanderers#618]
Settings menu for blasters, lasers, and rocket launchers.

For blasters, Accuracy, Velocity, and Rate of Fire as adjustable sliders or input boxes.
Weapon damage would be determined by the above traits, so a weapon with high accuracy, velocity, and fire rate, would do less damage than one that has slow shots with terrible accuracy.

Settings like this would allow a single weapon type to fulfill many roles and specializations, such as launchers ranging from slow unguided torpedos, to varying degrees of homing capability at the cost of warhead strength.

**Comment by tsunamayo** [comment]
Hi, I dont want to put sliders but more addons block/bricks that will change the way the weapon will behave. It will all be in the weapon update - so it is on the roadmap yes. Cheers

**Comment by weylin6** [comment]
Even better than I hoped for then! Keep up the amazing work, you're making outstanding progress.
