### ISSUE TITLE
[Bug] Freeform highlight disappearing into infinity [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#619]
When highlighting larger freeform blocks, the preview outline sometimes extends off from the edges of the block, appearing to disappear into the distance.

![20180323161144_1](https://user-images.githubusercontent.com/33041786/37853507-ff99e5e0-2eb4-11e8-8ee3-e201821ebff7.jpg)

**Comment by tsunamayo** [comment]
Yes I noticed this... Unfortunately it is linked to a plugin I am using, so I cant fix it myself. I think it was always there but since freeform can be elongated we only see it now...
Thanks

**Comment by tsunamayo** [comment]
Okay issue is now fixed now! Cheers
