### ISSUE TITLE
BUG - Painting block issue

### ISSUE THREAD

**Issue by Eldriken** [tsunamayo/Skywanderers#62]
Seems when I paint using the new paint blocks there is a bug that paints the orig color instead of the changed .  

You can see the captured video here [2017-04-14 20-40-22.mp4](https://www.dropbox.com/sh/pnfrsx3toy2rzhu/AABo9N6TY-lN0tn52dWd2pDCa?dl=0)

**Comment by Eldriken** [comment]
Added a couple more example videos

**Comment by tsunamayo** [comment]
Thanks a lot for the bug report! This issue should have been fixed some time ago actually.
