### ISSUE TITLE
[Bug] Freeform blocks cannot be placed on hinges [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#621]
While the freeform block can be placed on rotators and sliders just fine, the game will not respond to attempts to place them on hinges.

**Comment by Name11ess** [comment]
This is not a bug:
![image](https://user-images.githubusercontent.com/33256107/37863907-a5fdc378-2f66-11e8-87a3-787c3a3bfd15.png)
