### ISSUE TITLE
BUG - interaction

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#625]
when you interact with things such as hinges, rotors ect you can only toggle them one way
by that i mean you can only open hinges not close them, you can only make rotors go clockwise not anti clockwise.
 you can still use logic you toggle between open and closed ect

**Comment by Sullos** [comment]
This was a bug fixed in the most recent update. I reported over a week ago as the bug where the players hand only produces a -1 when you right click on things.
Be sure to check the GitHub for similar issues :)

**Comment by Mellcor** [comment]
if it was fixed, then howcome i found it yesterday on both main and experimental #thinking

**Comment by Sullos** [comment]
As I said.. fixed in the most recent update (which was all of a few hours ago). but reported well over a week ago. :/
