### ISSUE TITLE
ISSUE - Inverted scroll wheel

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#627]
the scroll wheel interaction for all the menus and hotbars is inveted
in what id say is 99% of all other applications ive used, scroll up means the page/hotbar goes up and the opposite of scroll down moves the page/ hotbars down
currently it is the opposite of this and a friend i got the game for even commented on how its confusing.
people shouldn't have to get used to a system when the systems can be easily changed IMO

**Comment by Name11ess** [comment]
If I don't make a mistake, it was an intended when the item bar was modified back in December.

Might be this update: https://forum.skywanderersgame.com/viewtopic.php?f=2&t=292

**Comment by tsunamayo** [comment]
Page and hotbar scolling direction seems fine to me. To which page are you referring if you can describe more?
Maybe to item scrolling? If yes it was changed as people agreed it was more standard like that.

**Comment by Mellcor** [comment]
hmm i cant exactly remember, i may have made a mistake here
