### ISSUE TITLE
[Bug] - Unable to load profile

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#63]
Upon connecting a rotating brick to a turret computer, my fps dropped dramatically, and stayed that way. 

To try and fix this, I quit to menu, and tried to reload my profile. Now, when I try to load a profile the game get's stuck on your beautiful "loading ..." screen, even when trying to load the default Francois profile.

I've attached the output_log file below, I hope this can be of help!

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/947114/output_log.txt)

**Comment by tsunamayo** [comment]
This issue should have been fixed! Cheers.
