### ISSUE TITLE
BUG - Keybinding

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#631]
accidentily set mouse 1 as the alternative keybind for increase player speed, was no able to set another key to the alternative bind slot and due to lack of defult keybindings button had to manully edit the keybinds file

**Comment by tsunamayo** [comment]
Hum I am not reproducing this one, have you wait a bit before trying another key? There is like a second of latency. Thanks

**Comment by Mellcor** [comment]
no one i had set the alternative bind to left click, it wouldnt allow me to set anything else, also i clsoe the menu and reopened it a few times looking for a reset keybinds button so it wasnt lag ect

**Comment by tsunamayo** [comment]
Okay I did some change to the code to remove that latency, hopefully it wont happen again, could you please re-open if it does ? :-p (I was not able to reproduce...)
