### ISSUE TITLE
SUGGESTION - Block selection

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#634]
when swapping blocks into ur hotbar
it would be really nice if you didnt have to put the block u swaped back into the block selection window
currently if u have a full hotbar, and you swap 1 of the blocks with a new one, you then have to click to discard that block, it would be more streamline and nicer to use if the block was discarded on mouse release

**Comment by tsunamayo** [comment]
Hum not sure what to think about this one, Minecraft is not doing this for example... Cheers

**Comment by tsunamayo** [comment]
No it dont, but I will make sure you can discard it when dropping on the codex windows as you cant atm. Thanks

**Comment by tsunamayo** [comment]
Codex is now working like you suggested. Thanks!
