### ISSUE TITLE
[Suggestion] Brick sized identity unit.

### ISSUE THREAD

**Issue by BruceLeedleLeedleLeedleLee** [tsunamayo/Skywanderers#635]
It's a pain to place a identity unit on really small builds, such as exosuits, so a brick version of the identity unit could help with that.

**Comment by tsunamayo** [comment]
Yes this is planned, as a smaller version of the spaceship core.

**Comment by tsunamayo** [comment]
Identity unit is no longer needed in-game! Thanks
