### ISSUE TITLE
[Bug] Alt-Tab to desktop glitch

### ISSUE THREAD

**Issue by Varraka** [tsunamayo/Skywanderers#636]
Seems alt-tab to desktop/media player/steam msgs is sending the mouse cursor to the top left corner of the screen where it stays. Untill you go back to the game, where it corrects itself and starts working again. Sometimes if i go real fast to what i wanted to click i can get to it before the bug sets in so it seems like there is some kind of 3-5 second delay on the glitch right after I alt-tab but after that it gets trapped in the top left corner.

**Comment by tsunamayo** [comment]
Okay so I can reproduce, could you tell me if you are playing in fullscreen mode? Are you in game or in a menu of the game when alt-tabbing? Do you have a secondary display?
It is working fine for me. Cheers

**Comment by Varraka** [comment]
Heya, yes, I was playing in fullscreen mode. Have tried bolth menu alt-tab
and in game alt-tab and bolth seem to produce the glitch. I do not have a
secondary screen (althoe i use to use one 5 years ago) but the option is
avail, currently off. Nothing pluged in except one 21" monitor LG. The
wierd thing about the glitch is it gives me about 3 sec to work normally
then the bug starts. Also, it seems every 5-10 attempts at alt-tabing it
works normally and lets me use the desktop. (thankfully i have some verry
crappy music on my pc that forced me to learn about this bug lol).  Running
windows 7, direct x 11, background apps: Windows media player, team speak,
steam, spybot. Thats it. Shoot more questions if ye gotz em! Ps: prop`s for
workin sunday, love yer ethic. might jump on your discord tonight to get
some help with paddle directions on a space rowboat. lol.  found f1 save
state button, a blog/msg about full list of key commands may help newcomers
alot. :D

**Comment by tsunamayo** [comment]
There is a mini tuto when starting and a help but they are lame for now...
I will add an auto-save soon, so now F1 will be needed. 
For the issue as I am  not reproducing it is gonna be hard to fix. Do you have this only in Skywanderers?
Thanks

**Comment by Varraka** [comment]
Got time to test tonight and am happy to say, new standard version is
working alt-tab for me! Im litterally alt-tab`d right now. :D Switching
tunes and everything.

**Comment by tsunamayo** [comment]
Okay maybe it was related to the state of your windows then! Cheers
