### ISSUE TITLE
[Experimental][18w11a] [Bug] inventory display when pick up color glitch

### ISSUE THREAD

**Issue by Clest1** [tsunamayo/Skywanderers#637]
I just pick up a paint on a entity when my inventory get the block where I was picking the color on each inventory case.
<a href="https://imgur.com/O1JhYws"><img src="https://i.imgur.com/O1JhYws.png" title="source: imgur.com" /></a>
The block was a slab.
<a href="https://imgur.com/ulTyzAS"><img src="https://i.imgur.com/ulTyzAS.png" title="source: imgur.com" /></a>
Then I check what happen with another blocks...
<a href="https://imgur.com/n0jj8Ls"><img src="https://i.imgur.com/n0jj8Ls.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/ANSKSCg"><img src="https://i.imgur.com/ANSKSCg.png" title="source: imgur.com" /></a>
That even show it in cargo block.
<a href="https://imgur.com/BhF0S8L"><img src="https://i.imgur.com/BhF0S8L.png" title="source: imgur.com" /></a>
Some cool blocks can be made in inventory... but when you place it on a ship it's a normal block.
<a href="https://imgur.com/iJxn4WX"><img src="https://i.imgur.com/iJxn4WX.png" title="source: imgur.com" /></a>

**Comment by tsunamayo** [comment]
Whoaa trippy, I will try to reproduce this one... Thanks
