### ISSUE TITLE
Hyperspace in... warp

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#638]
https://gfycat.com/GracefulVengefulHippopotamus

This is what happens when when you activate hyperspace in... hyperspace. It can be easily fixed by disabling the ability to go to hyperspace in... hyperspace. In the Discord, we called it Ultraspace :D
Now you could just disable it or consider later adding a bit of gameplay to it. Make it so it will randomly teleport to to a random system. Or drop you back into the system you were in at the expense of damaging your ship. Never hurts :D The important thing is the glitch and below.

This brings up another issue. The between system warp is called hyperspace just like the between planet drive is also called hyperspace which is very confusing. Renaming shouldn't be too hard and would get rid of a lot of confusion. This post has a few options to consider
https://www.skywanderersgame.com/forum/viewtopic.php?f=5&t=41816

**Comment by tsunamayo** [comment]
Yeah I know it is bugged and will get a complete overhaul soon ;-). Yes naming was confusing, I want to rename both interstellar and interplanetary travel mode. Cheers

**Comment by tsunamayo** [comment]
Okay I fixed this one, now you are forced to a view unlocked state and cant fly your ship. Thanks!
