### ISSUE TITLE
New update is gamebreaking

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#639]
Tsuna, the new update has gone out and the game is unable to load at all. Logs state many "index out of range exceptions" errors. Me and several others have tried full re installs with empty folders and no existing files from pre-update. 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1845100/output_log.txt)

**Comment by tsunamayo** [comment]
okay let me check that, I will take down the update until fixed. Cheers

**Comment by tsunamayo** [comment]
Okay issue is fixed now! Thanks for testing so quickly, cheers!
