### ISSUE TITLE
[Bug] Building line of blocks through Left/Right Mirror Block makes mirroring permanent

### ISSUE THREAD

**Issue by Rufarnd** [tsunamayo/Skywanderers#64]
I built a line of hull bricks through the side of a mirroring block that was placed centrally. The line of blocks overwrote the mirroring block, and it became impossible to turn off left/right mirroring, even after placing and deleting another left/right mirror block.

**Comment by tsunamayo** [comment]
Issue fixed! Now block wont be overridden.
