### ISSUE TITLE
Can't align to the torus (Experimental build)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#640]
![image](https://user-images.githubusercontent.com/31857052/37875412-a606a404-3036-11e8-8534-6d698fc79ff1.png)
When attempting to align to the torus there's no option.

**Comment by schlid** [comment]
To develop upon this further, I can align to the buildings, just not the ground or the voxel mountains

**Comment by tsunamayo** [comment]
Deprecated issue, now you align directly to the torus depending on your locomotion mode. Thanks
