### ISSUE TITLE
[Experimental][18w12a] Freeform block placement bug

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#641]
In my game whenever I place a freeform block it causes the model of the freeform block with a random system block clipped inside to be placed instead, deleting the random system block results in the model of the freeform block to stay and it cannot be targeted by middle clicking. 

I have a recording of this saved to google drive:
https://goo.gl/Vo2QYd

**Comment by tsunamayo** [comment]
Indeed I can reproduce. Nasty bug! I am on it. Thanks

**Comment by tsunamayo** [comment]
Okay issue is now fixed, thanks!
