### ISSUE TITLE
Blocks are always broken instantly when hit once (Experimental)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#642]
Shift clicking acts no differently to clicking normally.
Having the normal click where blocks had "durability" was useful for doing precise building where you may accidentally hit another block.

**Comment by tsunamayo** [comment]
Yes it was scrapped entirely as I now use block HP. I will do a system where you have to hold the button like a short amount of time to minimize misclick - with some visual indication.
Thanks

**Comment by tsunamayo** [comment]
Block are now destroyed on click release. Thanks
