### ISSUE TITLE
[Expiramental][Bug] invisible small blocks

### ISSUE THREAD

**Issue by early000** [tsunamayo/Skywanderers#643]
I found this bug when I was trying to make a large ship out of only small blocks. Blocks turned invisible, but the connection points remain. Only the small blocks are the ones that disappear; the full sized blocks do not disappear.
https://imgur.com/gallery/BRkN3

**Comment by tsunamayo** [comment]
Yes you are using too many bricks, it is a known issue. Bricks are not made for that unfortunately :-( Cheers
