### ISSUE TITLE
Can't load in older .swbp files 

### ISSUE THREAD

**Issue by Gearsarts** [tsunamayo/Skywanderers#644]
I am unable to load in some ship models, specifically older .swbp files. For example I placed "scaled-ISD.swbp" into my blueprints folder and loaded up the game. I selected the blueprint block, right clicked and it loaded the drop down menu of ships within my blue print folder, however when I choose to spawn in the file mentioned, it will either load in as invisible or it doesn't load in at all. The game will also freeze during this process. Newer uploads have worked fine however. 
This would also occur before the latest update.  

The file in question was uploaded to the Skywanderers discord,  #showcase page on 12/29/2017 Submitted by discord user ShogunateTom#7777 
File name: scaled-ISD.swbp

**Comment by tsunamayo** [comment]
Hi, could you please send me the blueprint in question? Thanks

**Comment by LeMinaw** [comment]
Here it is [scaled-ISD.zip](https://github.com/tsunamayo/Skywanderers/files/1847121/scaled-ISD.zip)

**Comment by tsunamayo** [comment]
Thanks, so I am in fact able to load the ship. Did you have a lot of other ship loaded when trying to load it? Could you please send me your output.log when it fails? Thanks
