### ISSUE TITLE
[Bug] Freeform texture uses system block textures [18w12a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#645]
When loading ships into the world from pre-existing blueprints, any freeform blocks on the ship are textured with various textures from system blocks. However, if the world is saved and reloaded, the freeform blocks display the correct texture. Once this bug has occurred with a particular blueprint, and that blueprint has been saved within the new version of the game, that blueprint will not display this bug again; this may mean that the bug is a temporary one resulting from the new blueprint system.

![20180325154235_1](https://user-images.githubusercontent.com/33041786/37879828-406a45e8-3044-11e8-8a40-84ba159ebb7b.jpg)

**Comment by tsunamayo** [comment]
Yes I had to update the way freeform data is stored, but it was supposed to be smooth even on a first load. You still have that old blueprint? Is it only on children entity or something? Anyway not a big bug I'd say. Thanks

**Comment by LeMinaw** [comment]
As requested, here's a file suffering from the same issue.
[Dragon.zip](https://github.com/tsunamayo/Skywanderers/files/1847111/Dragon.zip)

**Comment by tsunamayo** [comment]
Okay I will close it as it is not deal breaking ;-)
