### ISSUE TITLE
[Suggestion] A.i Identity block

### ISSUE THREAD

**Issue by Varraka** [tsunamayo/Skywanderers#646]
Hoyz wanderers. Prepp n for essential parts in pre alpha and just popp n an idea super early. A block to controll how a.i treets the ship for purposes of running scripts by its creator.  Ive played more hrs of starmade than id like to admit and from a designer perspective, the "new power system" then cuddling upto fans of the old power system seems to have broken that game. Therefore I see it as essential to get every core aspect started right from the get-go, and the heart of most gamers lay not within countless builds, but within experiance countless builds can offer. :D  Being somewhat combatitive irl then try`n to make tactics work in that starmade game (whereas every ship orbits in fear mode, pulsing weapons out of range like a kid shooting birds with a nerf gun) made me shed a tears not that of joy. XD Therefore I propose it be essential that a space be reserved in the form of a block to tell the game that the ship i just made is a mining vessle and will run to the nearest station if in trouble. Or that the little fighter doesnt launch from its mother ship untill the mothership is in trouble. Or that the mother ship is so bad ass with long range gear that it should try to always orbit at 3km. Or even fun (tecnicly gm) options like "if cpu spawns for player engagement, spawn no more than <5 crew members on this ship. This type of entry options in a a.i identity block could lead to some wicked r.p adventures later on eg: "This type of blueprint is good for landing on planets that are being blockaded and hold this type of mission... ... ."  ;)   Im only suggesting this now cause i have a fetish with d20s an event spawning!!! :P have this un-dying urge to player-a.i generation as creative and expansive as our builds will be... So its gotz to get in early I say.  Thanks for the timespace. :)

**Comment by tsunamayo** [comment]
Will see when I get to AI ships! Cheers
