### ISSUE TITLE
SUGGESTION - Sprint

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#648]
give us an assignable keey that lets us 'sprint'
ideally it would be a press to toggle or a hold to toggle key that when in use would let us go as fast as we set with '[' and ']' keys and when not it use we would be at a set 'walking' speed

this would be usefull for those who want to build faster as it would give u 2 speeds at the press of a button instead of having to speed up movement to get some were then slow it down again once you are there

**Comment by tsunamayo** [comment]
We now have a run key (by default SHIFT) with the new locomotion update. Thanks
