### ISSUE TITLE
Freeform Ghostblocks

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#649]
After updating to 18w12a, any freeforms I place become ghost blocks. They can't be interacted with in any way; isn't solid and can be walked through, can't place blocks on them, can't break them, etc.

I also tried respawning my ship, and even making a new ship, freeforms still became ghostblocks.

Could even reproduce after restarting my PC, re-installing Sky1 and deleting the Sky1 folder.
https://i.imgur.com/WAoeRqI.gifv

**Comment by Tomatart** [comment]
I can confirm this issue
![screenshot 125](https://user-images.githubusercontent.com/26846110/37929403-c0d31344-30f4-11e8-90a4-f1559216cd36.png)
The blocks are ghosts

**Comment by Creepthefrenchpastery** [comment]
i was having the same problem with that

**Comment by schlid** [comment]
This issue is a pretty huge problem as freeform is unusable on Experimental currently. A hotfix would be greatly appreciated as there are lots of bugs on normal branch that were fixed on experimental that many people don't want to return to.

**Comment by tsunamayo** [comment]
Yes, I fixed it already as it was already reported. Dont use freeform for now, I will put a patch up soon! Dont roll back to default as the save is not compatible. I keep you posted.

**Comment by tsunamayo** [comment]
I just pushed the fix,  I will do a forum post soon. Thanks - sorry that was a rocky one, but yeah I changed a lot of very deep stuff in the code! Cheers

**Comment by SkellyBard** [comment]
Papa bless this dev 🙏
