### ISSUE TITLE
bug-Issue with spawing in a blueprint with freeform blocks

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Skywanderers#651]
So when i spawn a ship with freefrom blocks in it spawns without the freeforms colored
![20180326155916_1](https://user-images.githubusercontent.com/37814990/37930371-946cc1bc-3110-11e8-85c2-4284c8e2836e.jpg)

**Comment by tsunamayo** [comment]
Hi, on which build are you? Could you please give me the blueprint? Thanks!

**Comment by tsunamayo** [comment]
Okay this issue is only temporary I think you can simply save once, exit the game and reload and it will be fixed! Please re-open if it dont!
