### ISSUE TITLE
Suggestion - Deadzones in mouse ship control should be larger.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#652]
Even at 90% the deadzone in ship control (with a mouse - I have heard that with a joystick they're much better) is very small, being able to have a tick box for mouse control with expanded deadzones would help greatly.

**Comment by tsunamayo** [comment]
Hi, there is a deadzone setting already, you are using it? I will have a look maybe it is not working at all. Cheers

**Comment by schlid** [comment]
It is working, I can feel it, but the effect is not very severe when using a mouse, compared to a joystick from what I can tell.

**Comment by tsunamayo** [comment]
Okay it is working now, will be in the next patch! Thanks for reporting all these bugs :-p! Cheers
