### ISSUE TITLE
[Bug] Freeform blocks only selectable in original voxel [18w13a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#653]
When a new freeform block is placed, it can only be selected for editing by mousing over the voxel that it was originally placed in. This also means that the other voxels occupied by the freeform block cannot be painted or built on.

In this picture, I am mousing over the original spot on the ship where the freeform block was placed (the part painted red). The freeform block is highlighted and can be selected.
![20180326204642_1](https://user-images.githubusercontent.com/33041786/37942050-d5ff617c-3136-11e8-833d-95efa7eb8812.jpg)

In this picture, I am mousing over the same block, but in the adjacent voxel. The block is no longer highlighted and cannot be selected; pressing the middle mouse button gives a message "No block targetted."
![20180326204648_1](https://user-images.githubusercontent.com/33041786/37942053-d93c4e2c-3136-11e8-953f-ed2daec03ccc.jpg)

**Comment by tsunamayo** [comment]
Okay just fixed that bug, and also update it to experimental. Cheers
