### ISSUE TITLE
[Bug] First freeform block placed on new creation cannot be interacted with [18w13a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#654]
When creating a new ship, the first freeform block that is placed on it cannot be interacted with. Freeform blocks placed after this can be. This also applies to the first freeform block placed on an object since the most recent update.

![20180326204956_1](https://user-images.githubusercontent.com/33041786/37942128-40e7b458-3137-11e8-839f-f6b6ee000a58.jpg)

**Comment by schlid** [comment]
This is very similar to the "ghost block" bug that was fixed before the hotfix you just pushed. To add to this, ships created before the big update that added the blueprints folder allow you to place freeform just fine, it's newly created ones that have the ghost block problem.

**Comment by Napther** [comment]
I will also add it does not interact with Blasters. Havent checked missiles yet to see if splash calculates a kill on them.

**Comment by tsunamayo** [comment]
Okay I fixed this one. Will be in the next patch. Cheers
