### ISSUE TITLE
[Suggestion] Docked entities save as whole.

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#66]
If you dock an entity to another, and save the main entity (the one being docked to) the save should include the docked entity. the same way child entities save. That way you can save a carrier with all its fighters docked and spawn it in that way.

**Comment by nokturnihs** [comment]
Or have a checkmark in the blueprint to toggle

**Comment by tsunamayo** [comment]
Finally this is have been added. Thanks!
