### ISSUE TITLE
[EXPERIMENTAL] Undo/Redo mechanic sometimes is broken

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#660]
As titled.
I have been unable to reliably replicate this camera-shy bug. Every time I go to record a Gif for proof, it fixes itself, or the break has happened and it correctly undo/redo's everything but 1 item.

**Comment by Napther** [comment]
So my GIFs are too big to embed, but placing a 4x4 stud grid, and wing 2x4 on that, removing the stud grid then pressing Undo to regenerate the stud grid will just delete the Wing 2x4 brick instead.

**Comment by tsunamayo** [comment]
Hi, thanks for reporting that. On the short term I will remove that undo/redo feature as it is taking me too much time to make it works, on the paper it is simple but there is too much edge case to deal with. It will come back at a later point! Cheers

**Comment by Napther** [comment]
Hahah, yeah, probably for the best during large update cycles as each new patch seems to shift it just enough to not work as intended.

**Comment by tsunamayo** [comment]
Now deprecated! Thanks
