### ISSUE TITLE
Bug- The torus terrain is ghosting for some reason

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Skywanderers#661]
when ever i try to align to the torus the quickwheel it dosent show up and the stone like blocks are able to be phased through also flying a ship at low speed through the torus terrain and then get out of the pilots seat the ship phases through the terrain 
https://gyazo.com/b442bf21373365f783fa599f18d4f640
![20180327222948_1](https://user-images.githubusercontent.com/37814990/38005593-53ed305e-320f-11e8-830f-ed9e98d741f8.jpg)
![20180327221932_1](https://user-images.githubusercontent.com/37814990/38005607-5f17deac-320f-11e8-9ca8-40f6defe7162.jpg)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
