### ISSUE TITLE
[Bug] Loading world, quitting to menu, then loading again results in freeze [18w13a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#662]
When after loading a world, then exiting to the title screen, attempting to load that world again results in an infinite loading screen. This is also true if trying to load a different world, or trying to create a new one. I'm attaching the most recent output_log.txt in case that's helpful.

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/1854404/output_log.zip)

**Comment by tsunamayo** [comment]
Okay this is have been fixed! Thanks a lot!
