### ISSUE TITLE
Suggestion: Engine module for adding traction, but newtonian flight by default.

### ISSUE THREAD

**Issue by weylin6** [tsunamayo/Skywanderers#663]
Engines would be newtonian by default, but could get the currently implemented flight-like traction with an engine add-on, allowing for sharper turns at high velocities.

Energy cost and strength based on ship mass would allow small fighters to easily get the desired effect, while larger ships would need a larger investment to get the effect.

The primary purpose of this suggestion is to allow newtonian and aircraft flight models (and everything in between the extremes) to exist in the same game as a matter of player preference and ship design choice.

**Comment by BruceLeedleLeedleLeedleLee** [comment]
Dont make this the same driftfest as SE please

**Comment by tsunamayo** [comment]
What do you mean by Newtonian? Like more 6dof control like (you release the key and it will stop), or really realistic physics? 
I will move to 6dof as basis and Plane like only when boosting / hyperspeed. So you get best of both worlds, precision control at low speed, and control of your trajectory at high speed.
Thanks

**Comment by tsunamayo** [comment]
We now have better tuned ship control, with a 6dof mode and a plane-like effect. Thanks
