### ISSUE TITLE
Suggestion - Adjustable Engine Trail Lengths

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#664]
Whilst it's certainly not very high on the to-do list, I was talking with another player earlier and we had the idea of making the engine trails possible to turn off. However, we still like them so I thought to have it adjustable per ship to make them more fitting for the type of ship.

So the idea is similar to how the custom paints work. 
The player opens the GUI of the Identity Unit, and next to the paints menu button, there would be a new button labelled 'trails' or something relevant.
GOing into this menu brings up a new screen with (possibly engine colour) the option to change the engine trail lengths. 
Going between the value of 0-100, 100 would make the lengths what they currently are, and 0 would simply disable them. 
The idea is that people can further customise their ships. I could have a stealth ship with a dimly coloured engine, mostly hidden with bricks, but with the current trails, people could see me from light years away ;D
So if I could lower them, I could have a soft glow to them with a 1% engine trail, giving an almost tip of a flame style of trail.
Or for a more TRON styled build, I could have the trail at 100 and have it very long and bright making for a TRON Light Bike styled Trail.

I think with having adjustability instead of just on or off would add a nice level of customisation that would satisfy many players. :)

**Comment by tsunamayo** [comment]
Not sure if I will do this, as I plan to refactor (again) ship control a bit, trail will only show when flying at high speed. Thanks

**Comment by tsunamayo** [comment]
Trail have now been removed. Thanks
