### ISSUE TITLE
[BUG] [EXPERIMENTAL] Different Engine Unit behavior when mounted on rotors vs hinges

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#668]
I discovered that while Engine Units on hinges are counted towards total thrust, the effect of them is less than when the same amount of Engine Units are mounted on rotors. Here are my two test cases:

Test 1, 9 engines on rotating blocks, 1 on the parent entity. Top speed of 187m/s
<a href="https://imgur.com/UAvtGTN"><img src="https://i.imgur.com/UAvtGTN.png" title="source: imgur.com" /></a>

Test 2, 9 engines on hinges, 1 on the parent entity. Top speed of 88m/s
<a href="https://imgur.com/duzF3Xm"><img src="https://i.imgur.com/duzF3Xm.png" title="source: imgur.com" /></a>

As a side note, I understand this kind of extreme rotor/hinge use might not work forever, the ship is for looking pretty and cinematics rather than balanced gameplay. The bug described could be a problem for any ship however.

In both cases the mass of the ship is the same
I've attached the two ship files below:

[Test cases rotor vs hinge Engine Unit bug.zip](https://github.com/tsunamayo/Skywanderers/files/1856842/Test.cases.rotor.vs.hinge.Engine.Unit.bug.zip)

**Comment by tsunamayo** [comment]
Hi, this issue was fixed (it was not related to hinge vs rotor) but more adding remove engine that was not working properly. Thanks
