### ISSUE TITLE
[Bug/Suggestion] UI Scaling Setting

### ISSUE THREAD

**Issue by XRey360** [tsunamayo/Skywanderers#67]
Simple as that, I noticed the game UI does not change with the resolution. When playing at 720p windowed (for streaming purposes) it appears too big and the windows will end overlapping or slipping outside of the game screen.

![example](https://cloud.githubusercontent.com/assets/28604994/25912619/3790726c-35b8-11e7-8e10-91ea28c84958.png)

Having the UI scale automatically with the resolution would be nice. Even better if we had a setting to change it between Normal, Small and Large to fit ones preference.

**Comment by tsunamayo** [comment]
Actually the gui will now re-adjust. Thanks!
