### ISSUE TITLE
[Bug] Game not saving changes on child entities unless parent entity also changed [18w13a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#670]
When changes are made to child entities, these changes are not retained sometimes unless the parent entity is also changed. Pressing F1 will not display the saving icon, and exiting the game and reloading will show that the changes made to the child entities have not been saved (although player position will be, interestingly). To make changes to these child entities persistent, the parent entity must also be changed in some way; if this is done, the game will correctly save changes to both the parent and child entities.

**Comment by tsunamayo** [comment]
It is now fixed, thanks for being so active! Cheers
