### ISSUE TITLE
[EXPERIMENTAL] Placing FFB onto child entity that covers multiple blocks, will occupy those slots on removal

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#672]
![image](https://user-images.githubusercontent.com/33023316/38109356-c8978630-338f-11e8-82ea-4d24cd1ba834.png)

![image](https://user-images.githubusercontent.com/33023316/38109363-cf87f3c6-338f-11e8-91cd-8a95540bbeb4.png)

You cannot place any blocks from the child entity into those slots, and they interfere with delete/remove block that ray-trace through their "ghosts"

**Comment by tsunamayo** [comment]
Freeform have been deprecated. Thanks!
