### ISSUE TITLE
Suggestion : Logic Hoses and Power Hoses/Conduits

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#674]
The suggestion is fairly straight forward, lets just say with the way you connect hoses, they could also act as a 'solid' sort of logic connection.
![logic hoses idea](https://user-images.githubusercontent.com/33239800/38118151-98e5fbae-3404-11e8-9d41-b0ddb3571018.png)
So as seen in this picture here, the idea is that you could effectively, physically, reroute a logic signal, by connecting a hose from one hose connector, to another.
The way it would work is, you would connect the output of the top link gate, into one of the hoses, then link that hose into the other end of the hose connector which would be linked up to a logic input.
It may seem like its just using a hose to move the logic signal from one spot to another. But the idea is this could open up the possibilities of rerouting logic signals from one source to another, adding to a bit of a role play effect.

For example, a scenario could be that you are on your ship, under attack, most of your weapons are inoperable, but their independent power grid is just laying there being un used. However, your shields are dying and they could really use the additional power! You send your engineer to engineering, they open up the logic trays. They unplug the logic hose from the weapons power source (which would usually be going into the weapons system) and plug it into the shields.
It may sound like this isn't logic being transferred, but rather power, whilst it could work that way, power grids still operate with logic, to be turned on and off.
But by activating a logic signal to go into the shields power source, you are disabling the weapons logic which would allow the weapons to operate, and instead allowing shields to operate with that power.
Actually upon writing this idea out, I have mostly realized that each system would need to have an independent power grid for say weapons, shields, engines etc to have that scenario work.

But that broken scenario aside, I feel it could still be a cool system having physical logic lines that could potentially be damaged from being shot or broken.

Onward to the Power Hoses and Conduits, well it is mostly explained in that odd scenario above.
The idea is that You could potentially have independent power grids, and to join the power grids together to have one massive power source, you could use conduits.
Currently, the ship just knows that there is 20 void generators on board and so many capacitors. And its all accessible and dispersed depending on what is active, like the engines or shields.
By having independent power sources, the player can hook up conduits making a direct line to a fuse box, which can then go to different systems. Instead of having invisible power cables like the game currently uses, the player could have the option to hook up their ship with conduits that direct power to different areas. This means that if a missile hits a part of a ship where a conduit is, the receiving end of the conduit would no longer receive the power. 
By having a fuse box, the power hoses come into effect, Similar to the logic hoses, and it works a bit better in this case, the power hoses could actually redirect power at a fuse box of sorts. All power hoses would have a base connection, but if a particular main conduit was broken, the hoses could be reconnected into different hose slots to redirect the flow of power to ensure particular systems still receive the power they require.
Hopefully that all makes sense ;D
![20180330104641_1](https://user-images.githubusercontent.com/33239800/38118622-c12b8608-3407-11e8-8be5-f258da4f8bca.jpg)
For example in this picture, the power is flowing blue, green, red and white.
Example blue is shields, green is weapons,
![20180330104720_1](https://user-images.githubusercontent.com/33239800/38118634-db8d7704-3407-11e8-9f48-28ff04529e0d.jpg)
You could redirect primary shield power to weapons, which may have much more energy available,
and instead redirect the relatively low power of the weapons systems to the shields. So that you may dish out more attacks because you may not be getting attacked by very powerful weapons, and so shields aren't so important.
Whilst all this might be done in the future by screen terminals, I think having the physical hose connections makes things very realistic and quite cool ;D

Just an idea

**Comment by BruceLeedleLeedleLeedleLee** [comment]
Please not. Ships will become a mess of cables

**Comment by Sullos** [comment]
I think you misunderstand my suggestion.
It would be in addition to the current logic systems.
People could pass logic connections into, through, and out of the hoses. This would be an optional addon for people who want more of a roleplay setting and functionally sophisticated ships.
As for the energy, it works the same way. Everything works the same as is, but if you want to have directed power instead of using the currently 'invisible' power connections, you could place conduits and power would only go through the conduits instead of being magically everywhere.

**Comment by tsunamayo** [comment]
Hose are deprecated... Also while I get the idea and the need for it I do not wish to add complexity code-wise and player wise (could be confusing). Thanks!
