### ISSUE TITLE
[Bug] Freeform block verticles and edges no longer visible through other blocks [18w13b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#676]
The vertices and other elements of freeform blocks are no longer visible through other blocks. They can, however, still be selected for editing.

![20180329211241_1](https://user-images.githubusercontent.com/33041786/38121688-94576910-3396-11e8-9838-f433025d9ff4.jpg)

**Comment by tsunamayo** [comment]
Actually I made this by design, how did you managed to get them superposed like that it should have turned red...

**Comment by Dwarf-LordPangolin** [comment]
So, the freeform block that I'm editing is on a rotator; that's how they're superposed. That's not what bug I'm referring to.

This is probably a better picture to demonstrate what I'm talking about. We can't see the vertices and other handles for freeform blocks when they're on the other side of blocks. This is how it is now, after the bug:
![20180330121245_1](https://user-images.githubusercontent.com/33041786/38146579-3513d884-3414-11e8-94f5-9563c26b636a.jpg)

And this is how it was before the bug:
![20180319214824_1](https://user-images.githubusercontent.com/33041786/38146578-32b18f0a-3414-11e8-9db2-1cfbd8354cd8.jpg)
Before, you could see all the vertices, making editing ships much easier. And you can still achieve this effect with glass blocks:
![20180330121819_1](https://user-images.githubusercontent.com/33041786/38146649-7b48947a-3414-11e8-96ad-9e67c4245951.jpg)
^That's how it used to be with all blocks, glass or metal, and it made editing a lot easier. Basically, the game is treating the freeform editing tools like they're hidden behind walls, when they used to be visible at all times.

If the vertices are hidden like they are now, the only way to edit shapes will be to move the player character to have direct line-of-sight on those vertices, which can be problematic when editing small ships that might not have enough space to fit the player character.

**Comment by Name11ess** [comment]
I agree, it was better when we were able so see all edges through other blocks.

**Comment by tsunamayo** [comment]
Freeform are deprecated. Thanks
