### ISSUE TITLE
It's possible to keep controlling a ship without a control stick if the stick gets destroyed while it's being used. [18w13b]

### ISSUE THREAD

**Issue by etn249** [tsunamayo/Skywanderers#678]
steps to reproduce:
1-Create a ship with weapons pointing at the driver's control stick.
2-Drive the ship, shoot and destroy the control stick while you are using it.
3-Notice that you can keep flying and controlling the ship without a control stick.

**Comment by tsunamayo** [comment]
This should be fixed now! Thanks for pointing this out! Cheers
