### ISSUE TITLE
[EXPERIMENTAL] Ships spawned via Blueprint block delete on next world reload

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#679]
Other ships are completely unneffected, when I come back the ship is gone but is respawnable from the blueprints to continue progress if I had force saved the BP before logging out.

[Havoc III WIP4 - Deleting every world load BUG.zip](https://github.com/tsunamayo/Skywanderers/files/1865466/Havoc.III.WIP4.-.Deleting.every.world.load.BUG.zip) (File no longer needed with extra information)

I am certain the world is saving, as a repaint on the Original ship created via starter block has kept its colours, while the ship spawned via BP block has been deleted again.

**Comment by BrickMacklin** [comment]
Happening to me with all spawned ships. Even if newly created. Can't save either.

**Comment by Napther** [comment]
"Happening to me with all spawned ships. Even if newly created. Can't save either."
Ah-Ha! Thats the kicker: this one was clone-spawned from the original 3rd WIP because I messed something up immediately after saving (FFB onto entity became ghosted). And its only that one thats been effected thus far.

Saving is working, Ill edit that out as the Original has kept the lick of yellow paint I pasted on it to test.

**Comment by tsunamayo** [comment]
Hi, I can load your ship, hit F1, and it is there and respawn. I think it is somehow related to the fact that some of you are using versions and have several instance of the ship in a world, if you could tell me more so I can try to reproduce. Thanks!

**Comment by tsunamayo** [comment]
Never mind I just managed to reproduce! I keep you posted, thanks!

**Comment by tsunamayo** [comment]
Okay issue is finally fixed, thanks for the test case. Cheers

**Comment by tsunamayo** [comment]
I should add that you will need to re-export your blueprint to make sure you can load several instance at once. Thanks!

**Comment by Napther** [comment]
Brilliant stuff! Was getting maddening respawning the thing, heheh.
