### ISSUE TITLE
[Suggestion] Brick Sized Hinges

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#68]
While hinges are excellent for all manner of uses, in their current form they are awkward to use with bricks due to the way they place in line with the full block grid. To remedy this, I suggest a brick sized hinge that can be placed anywhere a brick can, with a size of 2x1 bricks, or better 1x1 bricks. I hope I've explained this clear enough, and I look forward to any feedback regarding this suggestion.

Thanks!

**Comment by AfterRebelion** [comment]
Current hinges are for most purposes brick friendly, as in recent versions (19w23b)
