### ISSUE TITLE
[18w13b] lighting and texture glitch.

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#681]
Ok so I loaded my world up just now and I'm having some strange issues. 1st I'm having a lighting issue my hangers are super dark now, last time i was playing it was well lit. 

this is how it used to look..

https://steamuserimages-a.akamaihd.net/ugc/929299633103422719/CBF93C301072990AFCE1BBECB18B513E8ABD3951/

and this is how it now looks.

https://steamuserimages-a.akamaihd.net/ugc/922550307741926516/DEF11717C94DFE4B777B7F82A5D8538765678987/

the other glitch I'm having is a texture issue with the free form blocks. they seem to have textures from some other blocks on them, where they used to be just one plain colour. pic below..

https://steamuserimages-a.akamaihd.net/ugc/922550307741924103/CA405FD6ED5693B5AB34F32D8147B86567308E35/

Did a quick verify files in steam just to see if i had some broke files but that didnt help either.

**Comment by tsunamayo** [comment]
Okay, for the light could you please activate them by hand, save, reload and tell me if they are still enabled?
For the texture glitch you just need to save and reload that will be it.
Thanks!

**Comment by MrBester** [comment]
Ok ill give it a go but it might take a while there is literally thousands of lights on that station. ill get back to you.

**Comment by MrBester** [comment]
Ok so... yeah.. the ffb textures did indeed fix after a save and reload, however the lights all turned off again. they in fact even more lights turned off after the reload. is there a quicker way of turning the lights on other than going round clicking them all one by one?

**Comment by MrBester** [comment]
So.. i came back to my world today and all the lights are now back on without me doing anything, seems the game fixed itself.

**Comment by tsunamayo** [comment]
Okay, glad to hear that, that was an issue that was supposed to be fixed. Thanks!
