### ISSUE TITLE
[EXPERIMENTAL] Renaming a Button/switch and pressing escape key will lock all game input

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#682]
![image](https://user-images.githubusercontent.com/33023316/38173640-de31f896-35b9-11e8-99ed-c853df841c4b.png)

After linking the Hotkey thing to a laser, I was trying to configure it to use left click to fire so that I can view how it looks from the cockpit... Unfortunately I tried renaming it, and am now stuck like this and cannot save, losing progress on the build due to the Blueprint deleting bug.

EDIT: Somehow anfter tabbing out in this situation I come back and its got text in the box, and I could hit enter to close it and continue as normal. Peculiar.

EDIT: Just tried to rename a switch... Instantly locked up

Addendum: My normal reaction to get out of menus is to hit escape. Hitting escape locks me out.

**Comment by tsunamayo** [comment]
Hi, sorry I slept on this. The way we rename command will change (how to be decided), so I dont apply anymore. Thanks
