### ISSUE TITLE
[Bug] Left-clicking on mech core UI deletes whatever's behind it [18w13b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#685]
When interacting with the mech core, left-clicking on some of the options will cause the game to read this as left-clicking on whatever is behind the UI screen (which is typically the mech core). This does not happen for all options, but seems to only happen when clicking on options in the drop-down menus in the mech core UI.

Thus, selecting the options up until this point is fine:

![20180401160032_1](https://user-images.githubusercontent.com/33041786/38177725-4df38c88-35cb-11e8-9aab-c0bcb642f91a.jpg)

But clicking on the selected option destroys the mech core.
![20180401160034_1](https://user-images.githubusercontent.com/33041786/38177726-5813cf70-35cb-11e8-8f39-6f1908571623.jpg)

**Comment by tsunamayo** [comment]
I am gonna get rid of that holo UI, it was a stupid idea, and I will use a 2D UI instead. Cheers
