### ISSUE TITLE
[Suggestion] Welding child entities to the main entity

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#687]
People very commonly use hinges to get certain angles on their ships. This is different than freeform because by using hinges you have a flat surface you can build off of, unlike freeform. However if the hinge itself is destroyed the entire child entity is destroyed.
There are 2 issues with this method that i believe my idea will solve.
Issue 1: blocks clip, when doing this blocks often clip and cause texture flickering which looks bad
Issue 2: this method creates child entities which increases file size and increases lag when used in large amounts. 
Now my idea:
Make it so that you can "weld" or "fuse" clipped blocks together. This could be done by hand per block with a special tool. By doing this it would turn the 2 clipped blocks into one block with the same shape. I believe that because it is done by hand the new block is generated by itself so wont cause alot of stress on the game/server to calculate and generate the new block. (see attached image)
![screenshot 144](https://user-images.githubusercontent.com/26846110/38178463-782926aa-35c8-11e8-9305-91ec187c9c4f.png)

Because the newly fused blocks would become one block they could have merged texture to stop the texture flickering. 
Another thing is that once you fuse 1 block all connected blocks that were on the child entity could then become apart of the main entity thereby removing the child entity itself while leaving the blocks.

**Comment by tsunamayo** [comment]
Hi Tom! Unfortunately it is not really possible ;-) Because how do you deal with collisions? How you merge the block in code? I any case you will need a different grid.
I created the freeform for that reason, but yeah there is some limitations unfortunately... Cheers
