### ISSUE TITLE
Mini block bug

### ISSUE THREAD

**Issue by ThatFungiNub** [tsunamayo/Skywanderers#689]
I seem to be having an issue where I cant place mini blocks at times, I'm not sure what causes it other than typical building 

and the blocks that do place place within each other, having multiple blocks in one slot...

**Comment by Tomatart** [comment]
I also am having trouble placing bricks, sometimes im aiming at stud and it turns red showing its selected but nothing places on it. Also the outline of selected bricks will often flash rapidy as if it is selecting bricks behind what im aiming at

**Comment by tsunamayo** [comment]
I cant reproduce the issue, is it something you see often? Could you please send me a screenshot next time so I understand the configuration. Does it happens with a specific brick?
Thanks

**Comment by JRL101** [comment]
@Tomatart @ThatFungiNub is that for the public release? or Experimental? because that sounds like the same issue i was having on the previous Experimental build _18w13b_
i also can not reproduce it Tried all kinds of combinations etc. 
Are you using Mirror block? or building through freeform blocks?

**Comment by Tomatart** [comment]
From what i've noticed this occurs mostly on child entities. 
It is also fairly random, sometimes it doesn't happen at all, other times it does. Other than being on child entities i don't know of other causes

**Comment by JRL101** [comment]
Hmm i shall experiment more with child entities then, because the issue i was having disappeared with 18w15 so i'll attack that part and see if i can replicate it.

**Comment by Tomatart** [comment]
I should add that this occurs in multiplayer, thats probably a big factor

**Comment by tsunamayo** [comment]
Issue deprecated.
