### ISSUE TITLE
[Suggestion] Inversed Tetra Block

### ISSUE THREAD

**Issue by XRey360** [tsunamayo/Skywanderers#69]
We are still missing a key piece! There is no block which can fill this gap between slopes:

![immagine2](https://cloud.githubusercontent.com/assets/28604994/26025445/1ca0ccb8-37e8-11e7-9cb6-b946ffe4a524.png)

It would be very nice having a block shaped like that for the purpose, as well as the variation for the other slopes :)

![immagine3](https://cloud.githubusercontent.com/assets/28604994/26025454/6965e6a0-37e8-11e7-9b1f-adb2c91251ce.png)

**Comment by Senakysam** [comment]
With the way bricks can clip through blocks, you can easily make that shape.

**Comment by tsunamayo** [comment]
Yes I dont wish to go overboard with block shape, but you should be able to use brick to get to the same result. Thanks!
