### ISSUE TITLE
nothing working [Bug]

### ISSUE THREAD

**Issue by Sloooth** [tsunamayo/Skywanderers#691]
not sure what I did other than place engine blocks. It has happened a few times.

https://media.giphy.com/media/1xOQ8NjhTRCFWNGUJC/giphy.gif

**Comment by tsunamayo** [comment]
Okay I need your log file to investigate. File is called output_log.txt and is located here:
C:\Users\[USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers
Thanks

**Comment by Sloooth** [comment]
Sent from Mail for Windows 10
