### ISSUE TITLE
Steam friends playing Sky1 are no longer displayed.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#692]
![image](https://user-images.githubusercontent.com/31857052/38225824-a84cf3f8-36ee-11e8-8152-97e6ed2b31a1.png)
I'm aware this sometimes happens when the steam servers are down but it has been like this for quite a few weeks for me now. It's kinda useful and if it was mistakenly disabled I'd appreciate being able to see it again.

**Comment by ProPeach** [comment]
I believe this is actually a change Steam itself has recently made, Friends will no longer be shown playing games that are not available on the Steam Store.

**Comment by tsunamayo** [comment]
Hi, yes I have no control over this! Cheers

**Comment by schlid** [comment]
Understandable, thanks
