### ISSUE TITLE
[EXPERIMENTAL] Infinite delay-loop clocks linked to beam weapon overrides player interaction

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#694]
After a minute of leaving this mechanism on aimed at a shielded ship to test the damage, I realised I couldn't really do anything anymore...

![image](https://user-images.githubusercontent.com/33023316/38280137-a2ed423e-379b-11e8-8a2f-b39d65b73077.png)

Was testing to see how many rounds per second I could fire from it originally.

**Comment by tsunamayo** [comment]
Issue deprecated. Thanks
