### ISSUE TITLE
EXPERIMENTAL 18w13b Freeform block selection malfunction

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#695]
Weirdness with selecting Freeform blocks in any configuration, seems fine with other blocks, but looking/aiming at a freeform block will select the block through or under it, the outline when you highlight the block flickers as it does this. causing accidental deleting or the wrong block. 

[18w13b-FreeformSelectionBug.zip](https://github.com/tsunamayo/Skywanderers/files/1874629/18w13b-FreeformSelectionBug.zip)

![20180404144944_1](https://user-images.githubusercontent.com/33255536/38292891-1403845c-3818-11e8-874f-a24984e3c29f.jpg)
![20180404145602_1](https://user-images.githubusercontent.com/33255536/38293073-b76d0cbc-3818-11e8-8846-b091b4b166c2.jpg)

**Comment by tsunamayo** [comment]
Hi, this issue should have been fixed in a previous experimental build - please re-open if it is not the case! Cheers

**Comment by JRL101** [comment]
**Confirmed:** bug seems to be fixed In the new experimental version. **18w15**  :)
