### ISSUE TITLE
18w11a Walker control keys seam to be hardcoded 

### ISSUE THREAD

**Issue by Surac** [tsunamayo/Skywanderers#698]
After entering the blue walker at the spawn point in a new world, the control keys seem to be hardcodet to WASD.

i suggest using the normal keybindings for walking around. I am using the Numberblock of my keyboard, as i am disabled (only one arm)

please make Walker to use bindable keys not WASD

**Comment by JRL101** [comment]
You can rebind your movement keys in the options under "controls"

**Comment by Surac** [comment]
yes i can rebind my movement keys. But inside a walker vehicle the program still uses WASD, regardless how i rebind my keys

**Comment by tsunamayo** [comment]
Okay it is now fixed, thanks!
