### ISSUE TITLE
[Suggestion] Scroll Wheel rotating Axis

### ISSUE THREAD

**Issue by XRey360** [tsunamayo/Skywanderers#70]
I think I'm not the only one who finds somehow unconfortable that when holding RMB you can rotate a block only around one axis (depending on the reference face you are using). This often leads to the need of placing "temporary" blocks around needed only to place your actual block at the desired position.

I would suggest to simply allow the scroll wheel to change the axis it rotates around (during the held RMB moment), making the block placement easier and allowing to directly find the correct position regardless of what reference block you are looking at. Of course, the hotbar should be locked while that action is performed.

**Comment by tsunamayo** [comment]
Nice idea I will explore it, I just have to make sure it feels right. Thanks for your suggestion !

**Comment by AfterRebelion** [comment]
The rotating mechanics changed completely since then, but the issue with not having a way to change rotation axis, and having to use temporary blocks is still there.
The proposed solution seems reasonable, only if we ignore that holding LMB nows make you enter freeform, not change rotation.

**Comment by tsunamayo** [comment]
Actually I will make rotation switch to different orientation when pressing rotate key. But it will only be for block that make sense (with no natural base), like the wedge. Thanks
