### ISSUE TITLE
[Enhancement] Rename "Join" in Turret Core to "Ball Joint"

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#701]
A small suggestion, but one I feel would eliminate any confusion about what the "Add Join" function is for, and how to use a ball joint for making a turret.
<a href="https://imgur.com/UVms5QO"><img src="https://i.imgur.com/UVms5QO.png" title="source: imgur.com" /></a>

**Comment by tsunamayo** [comment]
No longer valid. Thanks!
