### ISSUE TITLE
Hover vehicles don't align to the torus when flown around it. (Experimental)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#702]
![image](https://user-images.githubusercontent.com/31857052/38463402-28b3ec70-3af2-11e8-8582-4f428008829f.png)

As you can see in the image, if i fly further from where the vehicle was entered on the ring, it won't continue to stay parallel to the ground. 
This may be linked to the bug where you can't place voxels on the ring anymore, you clip through the mountains and can't align to anything except the man made structures.

**Comment by BruceLeedleLeedleLeedleLee** [comment]
Also reported this some time ago, may be worth noting that mechs actually turn with the torus

**Comment by JRL101** [comment]
Which Experimental version is this for? Please put it in the title so i can gather testing samples.

**Comment by tsunamayo** [comment]
Not happening with new Hovercraft tech. Thanks
