### ISSUE TITLE
18w11a Mech joints spawn secondary part in wrong location

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#704]
When placing any of the three mech joints, the secondary part ( the piece I could build the arm / leg / head on ) appears in a wrong location, usually glitching into the mech's main body in the center, or hovering in the air below it.

<a href="http://www.kepfeltoltes.eu/view.php?filename=453mechjointproblem01.png" target="_blank"><img src="http://www.kepfeltoltes.eu/images/hdd1/2018/04/08/453mechjointproblem01_tn.jpg" alt="Képfeltöltés ingyen"></a>

Every time. No exceptions.

Can't build mechs until this is fixed.

**Comment by Cpt-Fortius** [comment]
[http://www.kepfeltoltes.eu/view.php?filename=453mechjointproblem01.png](url)

Uploaded a pic to show what's going on.

**Comment by tsunamayo** [comment]
Hi, can you post the picture over here, for some reason I cant see it. Just drag the  picture in github, that will work! Thanks

**Comment by Churrosaur** [comment]
@Cpt-Fortius  , saving as a blueprint and pasting it has been a work-around for the problem in the past. That said, it's still a major issue.

**Comment by tsunamayo** [comment]
Hi, this issue was fixed in 18w13a, so it should be good now as this is in main. Thanks
