### ISSUE TITLE
[Experimental] Laser Sensors only work in certain directions

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#705]
The direction a Laser Sensor faces appears to affect the degree to which it works, if at all. I've posted screenshots of a test blueprint I made, constructed from a starter block on the bottom and building upwards / outwards. I've also tried connecting slides and rotating blocks to the Laser Sensors, and they don't respond on this blueprint (but I've had them working on other blueprints in the same save).

![20180408135936_1](https://user-images.githubusercontent.com/6946291/38472472-8bae2fa0-3b35-11e8-8400-97abdccfe90a.jpg)
![20180408135943_1](https://user-images.githubusercontent.com/6946291/38472473-8bc704bc-3b35-11e8-93be-abc3392d89fd.jpg)
![20180408135948_1](https://user-images.githubusercontent.com/6946291/38472474-8bdf81c2-3b35-11e8-8f9d-a32998ebbca4.jpg)
![20180408135953_1](https://user-images.githubusercontent.com/6946291/38472475-8bf5cd42-3b35-11e8-9016-2165d944a1e5.jpg)

**Comment by talrey** [comment]
Update: restarted the game and all four lasers were pointing out to infinity until I broke one of the laser receivers, which caused the lasers to update and return to the state seen above.

**Comment by JRL101** [comment]
Which version was this bug related to? Could you put it in the title please?

**Comment by tsunamayo** [comment]
Okay I fixed this one, it took longer than expected there was several bugs :-p. Cheers
