### ISSUE TITLE
18w13b Game world wont load. 

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#706]
I've tried all sorts of things, including full wipes of the game and installing it in different locations.
For some reason it's refusing to load with and without a world/blueprints.
**I'm attaching the two crash files, and the save data i was using.** 
The game was working about 24hours ago. i was working on a freeform ship and had the default entities and 2 to 3 of my own builds.

_[NOTE] When the game crashed and the dialogue to open the folder for the crash logs popped up, i couldn't select it as the crashed game refused to minimise without minimising the dialogue box._

[Crashes.zip](https://github.com/tsunamayo/Skywanderers/files/1890692/Crashes.zip)
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/1890693/Save_Data.zip)

**Comment by tsunamayo** [comment]
Hi, sorry to see that, do you have the file output_log.txt by any chance? Do you still crash 100% of the time? Thanks

**Comment by tsunamayo** [comment]
Not sure if it is always happening on your side if you are still playing the game. Tell me if yes! Cheers
