### ISSUE TITLE
[Exp.] Paint tool particules and custom colors

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#709]
Hello!

The particules' color of the Paint Tool show the original custom color even after it has been modified.

Here's an exemple, the particules are green instead of grey.
![20180410133434_1](https://user-images.githubusercontent.com/33256107/38554727-ff60b32a-3cc3-11e8-965a-44cc3cccb3eb.jpg)

**Comment by tsunamayo** [comment]
You where building on a children entity right? I fixed the issue for children entity (it was working with the parent one). Thanks!

**Comment by Name11ess** [comment]
I was probably building on a child entity indeed.
