### ISSUE TITLE
[Exp.] Multitool size after switching from TPS

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#710]
Hello!

It seems like there is an issue on how the multitool is displayed after the view come back from TPS to FPS. It appear smaller after switching from TPS.

Cf. following gif:

![13](https://user-images.githubusercontent.com/33256107/38559012-2804224a-3cd2-11e8-8fc7-f30eb6c14f0a.gif)

**Comment by tsunamayo** [comment]
Indeed, this issue is now fixed! Thanks
