### ISSUE TITLE
experimental is being funky

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Skywanderers#711]
so when i try to load my saved world this happens

![20180410152632_1](https://user-images.githubusercontent.com/37814990/38581878-0d817cd8-3cdc-11e8-9399-c47ed156b086.jpg)
 when i span into a new world there is no taurus and when i check my inventory there is no blueprint block and  the old power generator i think experimental is switching me to a older version of skywanderers

**Comment by tsunamayo** [comment]
Hi, are you sure you are using experimental, and not debug for example? Thanks

**Comment by JRL101** [comment]
@Creepthefrenchpastery can you confirm the version number in your title screen please?
