### ISSUE TITLE
[EXPERIMENTAL] Blocks highlighted for deletion on entities that are Blueprints of eachother

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#712]
https://puu.sh/A0w5o/593b8d6675.mp4

the grey is the original, the Orange-ridged is the "child" blueprint of it.

**Comment by tsunamayo** [comment]
Hah nice spot, yes I knew this could happens but it is gonna wait some heavy rendering refactor to be fixed... Hope it is not too disturbing for now.
Thanks

**Comment by Napther** [comment]
That's fine. A little creepy at first but as long as its a documented issue and doesn't destroy the cloned build.

**Comment by JRL101** [comment]
Is this **18w15?**

**Comment by Napther** [comment]
At the time of posting, assume I am on the current version of the Release at that time. As I cant check from in-game menus. And exiting the game is a chore. The method I have used in past for bug reporting has not had any issues.

If Tsuna has pushed an update since last night/few hours, then its 18w14.

Otherwise this bug will be here a long time while other systems are being worked on first as I understand Tsuna needs to "refactor the render engine" to get rid of it.

**Comment by JRL101** [comment]
Current Experimental is **18w15** as of _9th or 10th of April_.
Version number is in the title screen. if you version number is less then you are not using the "Experimental" version.
The experimental version is in the "Beta branch access" of steam and is for people willing to loose most if not all of their stuff if an error occurs. But it will display in there if you have it.

I just haven't encountered this bug, and to test if i also have it, i need the version number. To see if its still present.

_(a suggestion has been made to put the version number somewhere visible in game.)_

**Comment by tsunamayo** [comment]
@JRL101 no need to be that pushy, if I am not asking it is because I know what version it is ;-) . I know exactly why we are having this bug and I should be able to fix it soon. Thanks

**Comment by JRL101** [comment]
@tsunamayo i sound pushy? sorry. I didnt mean to.

**Comment by tsunamayo** [comment]
@JRL101 hehe no pb, it is just I saw you posting a bunch of similar messages. Okay I did the change, and issue is now fixed! Cheers
