### ISSUE TITLE
[EXPERIMENTAL] Ships with only single thruster have severely limited boost mobility compared to 6DoF base mobility

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#715]
https://puu.sh/A0xvC/8c1009e642.mp4

Using the "microdrone" thats too small for a seat but should show at the start in boost I wasnt going anywhere compared to the kick of activating 6DoF

**Comment by tsunamayo** [comment]
Okay it was fixed a few version back actually. Thanks
