### ISSUE TITLE
[EXPERIMENTAL 18w15]  Block Delete, Shift+Block Delete Mirror Issues, other Mirror Issues

### ISSUE THREAD

**Issue by oojimaflip** [tsunamayo/Skywanderers#718]
Deleting a block using the default control (Right-Click?) no longer respects active mirror blocks.

Deleting blocks using Shift DOES respect active mirror blocks.

**Comment by Napther** [comment]
This issue has been reported already and subsequently fixed, #713

**Comment by JRL101** [comment]
Can you put the Version number in the title when stating experimental versions please? That way it stays organised.

**Comment by Napther** [comment]
Create a new issue for that, then to keep things consistent. Ill check this myself with Even-mode symmetry but Freeform Blocks have always ignored mirrors and needed manual rotation tuning.

**Comment by Napther** [comment]
Im seeing no issues in placing blocks otherwise not reported for my issue that I reported earlier. Might be that Odd was fixed, but even symmetry was not. Peculiar.

**Comment by JRL101** [comment]
@oojimaflip I was having that for the previous build of Experimental 18w13b but after some testing i cant replicate it. Do you have a blueprint its happening to?

**Comment by tsunamayo** [comment]
Hi, the first issue was already fixed as @Napther said, but if you have a test case for the mirror rotation issue I will have a look at it. Thanks
