### ISSUE TITLE
[Bug] Unable to cancel flexible pipe connection

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#72]
While trying to connect two of your wonderful new flexible pipe bricks, I realized that you can't cancel when trying to form a connection. You can't open inventory, or the menu, the only option is to quit the game by closing the window.

Gmunga also reported that he was having the same issue when trying to disconnect the ball joint, he was unable to interact with anything too.
I hope this has been helpful!

![image](https://cloud.githubusercontent.com/assets/27857711/26214202/67a06c8c-3bf3-11e7-82b6-ea62b56382b0.png)

**Comment by tsunamayo** [comment]
Issue is fixed and will be available in the next build. Thanks for your help.
