### ISSUE TITLE
[EXPERIMENTAL] Deleting thruster blocks very rarely triggers a large plume

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#720]
Managed to catch this one on record while recreating a separate bug... Its very low priority this one but still happened and is unintended behaviour, so...
Ship is a new starter block placed down with the thrusters on it, not part of any other assembly.

https://puu.sh/A0UPS/736287de7c.mp4

Funny that you can see my confusion unfold...

On thought, this sounds similar to my old stretchy-hose issue, #344 in that the plumes reach out to a far away point.

**Comment by tsunamayo** [comment]
hah, it looks silly indeed, I will fix it... Thanks

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks
