### ISSUE TITLE
[EXPERIMENTAL] Starter block interfering with remove-block mechanics

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#721]
This includes interfering with SHIFT+Delete and places a new block down.

https://puu.sh/A0VxP/a720bb4adb.mp4

With my settings, a new Starter block is placed down with RMB, and more starter blocks are added to a build itself with LMB

**Comment by JRL101** [comment]
I can confirm that this is present currently in **[EXPERIMENTAL] 18w15**, right clicking will place a ship starter block, it also can cause them to paste inside of eachother.

**Comment by tsunamayo** [comment]
Thanks, issue is now fixed! Cheers
