### ISSUE TITLE
[EXPERIMENTAL] 18w15 Light not emitting in specific conditions.

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#722]
Any form of light emitting block seems to be having issues with being placed on:
Freeform blocks _(no light on either child or parent entity)_
ANY child entity block. 

Lighting works fine on any parent block that isnt a freeform block.

![20180411230937_1](https://user-images.githubusercontent.com/33255536/38625846-ebdd6e7c-3ddd-11e8-8589-40c263147ede.jpg)
![20180411230938_1](https://user-images.githubusercontent.com/33255536/38625848-ec1a1f2a-3ddd-11e8-90b8-177951eb3512.jpg)
# ^PARENT _Freeform_
--------------------------------------------
![20180411230944_1](https://user-images.githubusercontent.com/33255536/38625854-f3067842-3ddd-11e8-95ab-e01ccc35748d.jpg)
![20180411230943_1](https://user-images.githubusercontent.com/33255536/38625855-f33fc016-3ddd-11e8-8dcf-443ac91945bf.jpg)
# ^CHILD _Block, upper one is on a brick_
--------------------------------------------
![20180411230920_1](https://user-images.githubusercontent.com/33255536/38625870-fd9360c2-3ddd-11e8-9306-8adf536ff80c.jpg)
![20180411230919_1](https://user-images.githubusercontent.com/33255536/38625871-fdda3c04-3ddd-11e8-9951-5b9e00d7265c.jpg)
# ^PARENT _normal block_
------------------>>
Strangely reloading a blueprint makes ALL of the parent lights work no matter what block they are on. 
The child will still not light up.
_I swear you already fixed this issue previously. am i imagining that?_ O ,0?

Here's a little test entity/ship i used.

[Ex18x15 - LightingChildIssue.zip](https://github.com/tsunamayo/Skywanderers/files/1899452/Ex18x15.-.LightingChildIssue.zip)

**Comment by Vicomt** [comment]
I've noticed something similar - it might be to do with the fact that the light is placed within the voxel of an FFB? the lighting code might check to see if the light is occluded?

**Comment by JRL101** [comment]
i thought the same, but the lights are either placed outside of a FFB's dimensions or away from it. Although it might still be doing that check just from contact with the FFB. I think if i work out whats different on parent object FFB's i might be able to define the problems occurrence more. 

Because i'm noticing _Lights on FFB of parent entities_ follow the bug or not without a definable reason at the moment. As I'm experimenting, i found that was the only changing factor with the bug.

**Comment by tsunamayo** [comment]
It is normal for hinge, but it should work on rotator, I will make something to make it clear for the player, or I will prevent the brick placement (but people will be mad). For freeform yes a voxel should block the light entirely, but it should work on the side, I need to check. Thanks

**Comment by tsunamayo** [comment]
I checked your blueprint and did some test with freeforms, I have now issue with them... Are you doing something specific? Thanks

**Comment by BonnyORG** [comment]
@tsunamayo Light on Freeform Blocks is not shown, when the light block is inside the voxel grid of the freeform block.

Also, why shouldn't player be allowed to place light blocks on hinges? :( is there really no other solution? Does this also mean Freeform Blocks will never be able to be placed on hinges?

**Comment by tsunamayo** [comment]
Hi, sorry for coming back late. For freeform it is a technical reason as they use the light grid. For light it is for performance reason, light grid are not cheap to render having a lot of overdraw could kill fps.
