### ISSUE TITLE
[EXPERIMENTAL] 18w15 Multiplayer viewpoint and synch issues

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#723]
MP player viewpoint is offset, character model doesn't display in external camera, character customisation is not loaded upon joining a game... sorry, multiple problems with MP currently.

![20180411202438_1](https://user-images.githubusercontent.com/7197427/38638681-f1c67d7c-3dc6-11e8-9287-7d9a8d1dcd13.jpg)

on game join, my viewpoint was wrong, the host's was correct, switching to external camera view made the character disappear, apart from the multi-tool, switching back did not correct it, and broke the host's viewpoint.

The green line is seen on each character by the host or client

the host's character customisation is not being communicated to the client on game load, but if the host  modifies his customisation, the entire customisation is synched with the client.

If you need any specifically MP testers, please don't hesitate to ask ;)

**Comment by tsunamayo** [comment]
Okay I fixed a lot of issues and added more sync for the multi-tool and sfx. I didnt fixed yet the character customization as I want to do a big refactor of this and it will come later on. Thanks!
