### ISSUE TITLE
[EXPERIMENTAL] Deleting Hinge Mini attachment node can cause deletion of itself and child entities when saving

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#726]
https://puu.sh/A1Bie/ee1c02f96c.mp4

As titled, in this case I was using a mirror plane so 2 hinges were placed down. After removing the hinge mini node that was unused and pressing F1 to save, the hinges were deleted.

**Comment by tsunamayo** [comment]
Hum, in the test case it looks like you are desactivating the mirror and reactivating it, then you delete the unused brick that will delete the master one, which seems normal to me? Maybe I am missing something. Thanks

**Comment by Napther** [comment]
I am toggling the Mirror to emphasise the mirror being active. But I have had it happen without mirrors and such.

https://puu.sh/A2gSh/9f7009c8f4.mp4

**Comment by tsunamayo** [comment]
Ah okay I misunderstood the bug at first, thanks for the clarification.

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks
