### ISSUE TITLE
[EXPERIMENTAL] Applying mouse movement while opening any menu may lead to "You Spin me Right Round baby right round like a record"

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#727]
https://puu.sh/A1Fg7/7f9a74ea3a.mp4

As titled, tested with paints and with Escape menu

**Comment by tsunamayo** [comment]
Ah I saw that once but never was able to reproduce, are you able to reproduce at will? Thanks

**Comment by Napther** [comment]
Pretty much, a flick of the wrist and pressing the button halfway through the movement should do it.

**Comment by tsunamayo** [comment]
Okay this issue is now fixed! Cheers
