### ISSUE TITLE
Blocks and the Codex

### ISSUE THREAD

**Issue by Psyckosama** [tsunamayo/Skywanderers#728]
Please add the blocks removed from the Codex back into the Codex. While I understand the desire to streamline and how the shapes are possible using the Freeform block, having them accessible allows for two major advantages for gameplay. 

First, they're rather fundamental forms and when constructing large objects, having to re-shape them constantly is extremely frustrating and time consuming when simply having them on the toolbar would allow for it to be built with speed.

Second, simply seeing them as an option will encourage creativity as people tend to get ideas they might not otherwise have had from seeing new shapes.

**Comment by tsunamayo** [comment]
Yes I agree it is too time consuming for the basic shape, so I have an idea to fix that and make them super fast to build (like the drag line/plane feature). I def dont want to re-introduce the shape creeping we add, sorry :(
Thanks

**Comment by Psyckosama** [comment]
How about something like this then. Have it so all the existing shapes are technically available, but possibly introduce some form of favorites option? Basically you either have to go into an expanded menu to find them, or enable them. And generally I'm not suggesting adding more shapes, just enabling the ones that already exist. 

To me at least the engine's pre-existing blocks handle 95% of construction jobs, and most of the remaining 5% can be handled by the Freeform block.

**Comment by tsunamayo** [comment]
The free scale mode tech I was mentioning is live for a while now, it should have got you covered! Thanks
