### ISSUE TITLE
Painting controls are inconsistent with the bound keys 

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#729]
Even if you rebind keys. left click will still remove colour, and right click will apply the desired colour. I have no issues with people running this setup if they wish, but having these two keys in line with your place/delete would be helpful - somewhat related to #714

**Comment by tsunamayo** [comment]
Hi, I think it is just the same issue as #714 and you got confused by the wrong label, as you can switch paint settings. Thanks
