### ISSUE TITLE
[EXPERIMENTAL] It ain't a glow block if it ain't glowin'

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#731]
Rare, random bug on start up, all blocks with glow aspect will not have a glow attached to it, Including glow cubes, logic bricks, and hoses, etc.

![image](https://user-images.githubusercontent.com/33023316/38737007-bd2d8a6e-3f25-11e8-8238-ce809f61a75a.png)

**Comment by JRL101** [comment]
Currently having this issue in 18w15b glow bricks are not glowing, and lights on child entities arent working.
Glowing stuff also seems to glow when there is a light present on the parent entity

**Comment by tsunamayo** [comment]
Issue should be fixed as of today. Thanks
