### ISSUE TITLE
If moving while pressing Q (colour-picker) continue spinning

### ISSUE THREAD

**Issue by kesuke** [tsunamayo/Skywanderers#733]
As described, if you rotate the character with the mouse for example and then press Q to open the colour-picker the player continues spinning

**Comment by ProPeach** [comment]
Sounds like the same base issue as #727, cheers for the report!

**Comment by kesuke** [comment]
Yes, thanks for the link ProPeach. I did search before posting but for some reason didn't see #727. I am going to close this to keep the list concise for Francois.
