### ISSUE TITLE
[EXPERIMENTAL 18w15b] Raytrace regression for certain items (Stickers, studgrids)

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#737]
https://puu.sh/A2W7w/043e1b8e10.mp4

![image](https://user-images.githubusercontent.com/33023316/38768308-acf77a3c-3fe9-11e8-9751-14adb5606f1e.png)

Only this specific angle is effected thus far. Placing the sticker on top of the block allows it to be removed.

**Comment by tsunamayo** [comment]
This issue should be fixed now! Cheers
