### ISSUE TITLE
[BUG] Delay logic bricks don't save values above one second

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#74]
When inputting a value into a delay logic brick, any value larger than 1 second is reset back to 1 second after closing the GUI

![skyw delay brick bug](https://user-images.githubusercontent.com/27857711/27012746-46bbd676-4ece-11e7-9a45-6df2609b03b2.gif)

**Comment by khowhl** [comment]
Yes, I noticed this as well

**Comment by tsunamayo** [comment]
Sorry, it was fixed a while back! Thanks for the super pro reporting ;-)!
