### ISSUE TITLE
[EXPERIMENTAL] Paint tool menu is same as movement control

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Skywanderers#741]
Holding the paint tool, the Q button is bound to both moving down and opening the paint tool's color selection menu.

![image](https://user-images.githubusercontent.com/38392651/38775349-4203c874-404e-11e8-8e25-76314771fdb7.png)

**Comment by Napther** [comment]
Debbie, that's only because we use Starmade control scheme!

The default is Space and Control for ascend and descend respectively.

It can be changed in the options for the Rotate Base Axis feature in the actions area of the Keymapping

**Comment by FlyingDebris** [comment]
![image](https://user-images.githubusercontent.com/38392651/38782276-fd3db62a-40be-11e8-8c3e-e653bf6012d7.png)
