### ISSUE TITLE
[EXPERIMENTAL] 18w15b - Custom colours not working on child entities - until restart

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#743]
Custom colours appear to be not working of child entities at all - the simple hinges, or rotators combined with brick rotators to create a turret
![20180415200136_1](https://user-images.githubusercontent.com/7197427/38782209-efab4be8-40e7-11e8-901f-d917b8a2ee2a.jpg)
the child entity (with the beam blocks) and the parent entities above were both painted with a modified custom colour #2

90% of this is fixed by restarting the game - the hoses however are still painted in the default custom colour

**Comment by FlyingDebris** [comment]
![image](https://user-images.githubusercontent.com/38392651/38840203-78a31984-41ac-11e8-9eea-9639d3603b3c.png)
Happened to me too. It corrects itself when you reset the color, but seems to revert if you right click on the child entity (to remove a block)

**Comment by tsunamayo** [comment]
Okay the issue on children was fixed, and I just fixed the issue for hose bricks. Thanks!
