### ISSUE TITLE
[EXPERIMENTAL] 18w15b Mechs can fly!

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Skywanderers#745]
![image](https://user-images.githubusercontent.com/38392651/38840358-30887f76-41ad-11e8-86fa-b4d239248bef.png)
Holding the jump button just lets a mech sail off into the sunset.

**Comment by tsunamayo** [comment]
Yes it was supposed to be a proper feature one day, I just left it because sometime you might get stuck in the ground but it looks silly I agree ^^
