### ISSUE TITLE
1/2 block wedges can't be extended using the mass placement tool (Experimental)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#747]
![image](https://user-images.githubusercontent.com/31857052/38906992-7768fcea-42b1-11e8-8a2f-b3b383034230.png)
As you can see, when trying to extend this block in the given axis, it won't place more than 1.  This is true with both parts of the half block wedge, the one that starts at the bottom of a block and the one that starts half way up, as shown above.

Normal wedges extend in one axis fine.

To add to this, I do heavily recommend to revert the single axis choice for types of wedges to two axis of extension, as it can be really useful for making heat-syncs, grilles and venting on bigger ships as shown below.
![image](https://user-images.githubusercontent.com/31857052/38907067-dff707d4-42b1-11e8-86d7-01a452677695.png)

**Comment by tsunamayo** [comment]
Sorry this was fixed for a while. Cheers
