### ISSUE TITLE
[EXPERIMENTAL 18w15b] Mechs Rotate Around Incorrect Point

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#748]
With my most recent mech built, I built it several blocks away from the starter block. When using A and D to rotate the mech, it rotates around the point where the starter block was, instead of the center of mass or between the feet.

**Comment by JRL101** [comment]
is the starter block still present at a distance away?

**Comment by Senakysam** [comment]
Nope, all extraneous blocks are removed, it's completely done.

**Comment by JRL101** [comment]
Hmm i'll give this a test. 
How far away roughly did you have the starter block? so i can mess around with distance etc.

**Comment by Senakysam** [comment]
About 5-10 block behind where the mech is now.

**Comment by JRL101** [comment]
Yea confirmed it happens. no freeform involved, and so far tested with EAST mech. 
Will give more detail later as i play with it and figure out its limits etc.
![20180422110929_1](https://user-images.githubusercontent.com/33255536/39090988-02697cba-461e-11e8-9ef9-911a2d5c8c3b.jpg)
![20180422110934_1](https://user-images.githubusercontent.com/33255536/39090989-02a05c1c-461e-11e8-9263-cb6a7f228a7b.jpg)
![20180422110936_1](https://user-images.githubusercontent.com/33255536/39090990-02d96ade-461e-11e8-9ea0-dea3fb22e5a4.jpg)
With Starter block ^
-----------
![20180422111010_1](https://user-images.githubusercontent.com/33255536/39091007-37ce3f4e-461e-11e8-95f6-bbfbf16449f9.jpg)
![20180422111013_1](https://user-images.githubusercontent.com/33255536/39091008-38071cc4-461e-11e8-94d6-d81abd91eaa4.jpg)
![20180422111016_1](https://user-images.githubusercontent.com/33255536/39091009-383e5a36-461e-11e8-82bd-2354bb7214b6.jpg)
Without Starter Block ^

**Comment by tsunamayo** [comment]
Okay I know why it happens, I will fix this. Mechs need a big push on their walking logic. Thanks

**Comment by tsunamayo** [comment]
Issue deprecated, mechs will be back!
