### ISSUE TITLE
[EXPERIMENTAL] Ghost Free Form Block

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#749]
Sometimes, I don't know when exactly, just sometimes Free Form Blocks appear to be unremovable Ghost Blocks. They'll just stay there unconfigurable for ever. Sometimes you can remove them physically and glide through there texture but the last times this bug occured their hitbox was weird and you were not able to interact with them in any way. Also the texture mostly is colored white.

![20180418172012_1](https://user-images.githubusercontent.com/38502325/38941749-85eba8a4-432d-11e8-900e-771edf9049d6.jpg)
![20180418172219_1](https://user-images.githubusercontent.com/38502325/38941750-8605f6c8-432d-11e8-815f-2f56c7412200.jpg)
![20180418172257_1](https://user-images.githubusercontent.com/38502325/38941751-861fd2a0-432d-11e8-9828-5fdee7625c4a.jpg)
![inked20180418172228_1_li](https://user-images.githubusercontent.com/38502325/38941752-86388dea-432d-11e8-9ef3-5afb234291c2.jpg)

Version: 18w15b

**Comment by JRL101** [comment]
Have you got a way to replicate this? does this happen in mirror mode?

**Comment by BonnyORG** [comment]
Yeah mirror mode was active.

**Comment by JRL101** [comment]
I've been having similar issues when placing freeform in mirror mode. If you could mess around and try recreate the scenario that would be awesome.
More specific the better, i'll do my own fiddling to get something specific.

**Comment by tsunamayo** [comment]
Okay, I know for sure freeform are not working with mirroring yet, I will try to see if I can reproduce this. Thanks!

**Comment by gundamaceNC** [comment]
I'm experiencing this issue as well.  At first I assumed that it was the result of having too many freeform blocks on one ship, but even after removing some other freeform blocks, the problem persisted.  For this ship only I am experiencing this issue every time I attempt to place a freeform block.  Is there a work around?

**Comment by JRL101** [comment]
@gundamaceNC 
Can i grab your version number please?

**Comment by tsunamayo** [comment]
Freeform were deprecated. Thanks
