### ISSUE TITLE
[BUG] No control in flying mode

### ISSUE THREAD

**Issue by khowhl** [tsunamayo/Skywanderers#75]
~~Okay so I don't know what caused this but~~ at some point I've been unable to fly ships. I can activate shipcore and yoke/joystick linked to shipcore and the HUD changes to flight mode (with STD as default). But the movement keys and the mouse buttons do nothing when pressed.
Ok, I encountered this issue again after deleting the yoke/joystick and shipcore and replacing them both on a ship and relinking them. After that, the problem appears again.

**Comment by khowhl** [comment]
Ok after reading the output log file, I found the real cause and it's not related to shipcore deletion (not in my case at least :P )
The issue is caused by key mapping and special characters. I'm using an AZERTY keyboard (like most people from France I guess) and the "2" key is also the key for the character "é" which is not recognized by the game as a valid key. So basically I can play and build with that mapping but not control ships as it throws errors everytime I get into flight mode.

**Comment by tsunamayo** [comment]
Hello, so you want to use key 2/é for your ship? I should not allow this at first, as those can be linked to actions like firing laser by the player. But let me try to fix the issue first. Could you please send me a log?
