### ISSUE TITLE
[EXPERIMENTAL] Save Issue

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#750]
Doesn't matter how often I hit F1, mostly my world doesn't get saved. Or to be more precise: the entities. When rejoining the world, my position stayed the one it was when I left, but all entities got reset to an old position/state.

Version: 18w15b

**Comment by JRL101** [comment]
For now i would recommend saving your ships with an ID block, ans anything with one of those seems to let F1 do its job.

**Comment by BonnyORG** [comment]
I always save the ships but still it's pretty annoying to always have to summon them all back in

**Comment by JRL101** [comment]
You should have to summon them back in, from my experience i save the blueprint and then F1 and it usually saves, but that said its not 100% guaranteed i wish it was a "force save" and not a "changed state save". I also do hard saved of ships i want to keep in-case i have to wipe the world. It is experimental after all.

**Comment by tsunamayo** [comment]
ID block should not be required... Does it happens all the time for all entities? Thanks

**Comment by JRL101** [comment]
For myself the F1 save feature randomly wont work. Sometimes updating other blocks helps. Sometimes saving the Blueprint help. but on my end i cant figure a precise reason F1 doesnt always save.

BonnyORG will have to explain his version of the problem.

**Comment by Napther** [comment]
It maybe perhaps is related to #679

**Comment by BonnyORG** [comment]
@Napther Oh yes, that sounds pretty similar. @JRL101 I know created a new world file, and there it does work as it should. As you said it's pretty random. @tsunamayo It did happen all the time with all entities, but it had to be working at some point, because the position/state it was reset to was a previous save from about 10 days ago. Maybe it also has to do with leaving the world to early? If you hit F1 and then enter the ESC-Menu to exit to your desktop, the saving may be interrupted and deletes the saves you made during your play session... 
Luckely it worked just fine in the new save the last times.

**Comment by JRL101** [comment]
@Napther I agree its very similar, if not the same problem.

**Comment by tsunamayo** [comment]
This issue should have been fixed. Thanks
