### ISSUE TITLE
[EXPERIMENTAL] Extending Tool Not Working

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#751]
For most Blocks (Blocks that can be placed in more than one direction), the extending Tool doesn't work. The arrow symbol inside the previewed gets displayed but you moving the mouse does not affect the amount of blocks being placed.

Version: 18w15b

**Comment by tsunamayo** [comment]
Okay for which blocks/shape you noticed this? I want to only activate it when it makes sense, ie not on tetra hepta or corner for example. Thanks!

**Comment by ZachZent** [comment]
The 1 to .5 slop and the .5 to 0 slope is one

**Comment by BonnyORG** [comment]
@tsunamayo What? oh! I didn't know this was intended... It really is a pain when you want to fill a long plane of slab blocks, etc. ... Extending does not work for all blocks that are no full cubes.. Half slabs, wedges or small planes like the metal plane or the airvent planes etc.. I recommand reimplementing the functionality to be able to also extend those blocks on a large area.

**Comment by tsunamayo** [comment]
Hi, functionality is now per shape as it is a bit smarter than before, so dont hesitate to point out shape where it is missing. Thanks

**Comment by tsunamayo** [comment]
Sorry this was fixed for a while. Cheers
