### ISSUE TITLE
[SUGGESTION] God Mode / Creative Mode / DEV Mode for users

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#752]
Refering to the multitool update, it just became worse for players to build. Yes, the Multitool may be a step into survival / more logical gameplay, but having to color every single block afterwards can be quite annoying. The removal of blocks from the inventory like the Gravity Block, the Quarter Blocks or the weapon build block is also not very good in my opinion. We as testers should also be able, just like you as the developer, to test what happens when you shoot at your ship or when you apply gravity.

**Comment by Vicomt** [comment]
survival mode should have been created as a separate entity before modifying the interaction mechanism, that way, the survival-type things could go in survival, and creative type things in creative. destroying creative mode to implement some survival-type stuff is :pysduck: imo

**Comment by tsunamayo** [comment]
Sorry, actually a lot of the changes are not related to survival / creative.
CTRL+Z -> it was a chore to code, as there is way too many edge cases to deal with, so I want to spend my time on more important features as it was taking too much time to maintain.
Gravity - weapon blocks, these where bugged or wip feature that require more time on my side. They will get back for sure! No need for me to have you "test" features that I know for sure are bugged. It would waste my time and yours.
Color -> It is deeper than creative, it will impact the way the codex is structured. I have painted very large surface, it was a bit long for sure but quite frankly negligible compared to the time spend to make proper ship detailing and interior. If you build ships over 100m you have to be ready for it ;-)
