### ISSUE TITLE
[EXPERIMENTAL] Lighting Bug

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#753]
Sometimes, when summoning an entity like a ship, it has no light effect at all. All the light blocks don't seem to do anything then.
Another time, it just works fine.
![20180419173911_1](https://user-images.githubusercontent.com/38502325/39002361-ac861780-43f8-11e8-98b5-1243112f8d5a.jpg)

Version: 18w15b

**Comment by tsunamayo** [comment]
I never saw that issue, could you please send me the faulty blueprint? Thanks

**Comment by tsunamayo** [comment]
Issue should be deprecated. Thanks
