### ISSUE TITLE
[EXPERIMENTAL] Freeform Block Color

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#754]
When summoning a ship, sometimes the Freeform Blocks don't show the correct color and can't be painted either. Another time they do.

![20180418213341_1](https://user-images.githubusercontent.com/38502325/38953839-469021f8-4350-11e8-9ae7-ab9e22b7fea6.jpg)

Version: 18w15b

**Comment by tsunamayo** [comment]
Freeform were deprecated. Thanks!
