### ISSUE TITLE
[EXPERIMENTAL] Weird Engine Lighting

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#755]
I did not do anything in particular. It just occurred and it wasn't the first time. I guess this is unintended
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38502325/38959078-8456eb3e-435f-11e8-9fd1-7b01420bbf4c.gif)

Version: 18w15b

**Comment by BonnyORG** [comment]
No it has nothing to do with the sun. This system is just quite near to the center. I can't reproduce it for now, still this was not the first time the bug occured and the last time there was no direct sunlight. I'll try to experience with it the next times it appears

**Comment by JRL101** [comment]
I can confirm light issues all round this patch, but this ones strange, i don't recognise the pattern being projected onto the floor. So im having trouble analysing how its happening. That shouldnt be coming from the thruster block as far as i know. Weird one. got the blueprint of the ship? so i can explore the bug?

**Comment by BonnyORG** [comment]
Yeah it has nothing to do with the specific blueprint, its the engine block (they are on subentities, maybe this matters). This bug occoured in an older version before on another ship (which also had the engine blocks on rotators). I'll try to experiment a little with it when it reoccoures.

**Comment by tsunamayo** [comment]
Hum weird, could you please send me your blueprint so I can investigate? Thanks!

**Comment by tsunamayo** [comment]
Issue deprecated.
