### ISSUE TITLE
[EXPERIMENTAL] Hovering over logic blocks no longer shows their value.

### ISSUE THREAD

**Issue by Caumen** [tsunamayo/Skywanderers#758]
The new prompts to [PRESS F TO LINK] and [PRESS F TO ACTIVATE] has taken over the place where we'd usually be able to see the value of a certain bit of logic.

![capture](https://user-images.githubusercontent.com/37751575/39032410-b3336608-446d-11e8-9e82-f30702549d5a.PNG)

**Comment by tsunamayo** [comment]
Hi, this feature has been depracted: systems now shows more data on the right side of the screen, and other logic brick or button will show cue of their input in the brick texture. Thanks
