### ISSUE TITLE
[SUGGESTION] Crawling

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#760]
Suggestion is simple enough, when in gravity, the ability to crawl giving one access to one block high areas. Like vents or Jefferson tubes adding an entire dimension to the building without needing to change too much. Plenty of other arguments for, but it is late and the point is made

**Comment by Vicomt** [comment]
we have miles of air-vents and ductwork waiting for this ;)

**Comment by tsunamayo** [comment]
I will add back crouch, but not crawling I am afraid it is not a tactical fps ;-) Thanks
