### ISSUE TITLE
Suggestion: Increased max drag size

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#762]
Would it be possible to increase the plane size with the build tool. I mean I understand you probably don't want us building 1000 x 1000 planes but 32 x 32 is a bit small don't you think? Even returning to the 201 x 201 from the previous builds would be great.

**Comment by Napther** [comment]
I'd suggest doing the starmade route: allow it to be individually configurable on server/single player to meet the demands/strains on the system.

...Though then again us builders just make it 200m then use 50x50x50

**Comment by gmunga5** [comment]
I do see what you are saying there with the performance and the likes however I would argue that 32x32 is just too small in general. Even taking it up to a nice round number like 50 or something would be helpful as counting in 50s is a lot more viable than counting in 32s. Ideally I think napther’s point about having the limit being configurable in some configuration file would be the most universally accepted option. I mean I think it’s fair to say people will build big no matter what. To an extent it just comes across as you punishing people for building anything longer than 32 meters which I understand is not the idea.

**Comment by CyaNox** [comment]
Remember that Starmade had its limit locked at 10 for the longest time before it became configurable. 32 is already quite big for this stage of development.

**Comment by gmunga5** [comment]
The issue isn’t that it’s 32 the issue is that it went from 200 to 32 and the fact that 32 is such a weird number to use. Counting up in 32s is rarely going to get the desired length.

**Comment by CyaNox** [comment]
I agree on that it is a weird number in the non *power of two* world we nerd inhibit so much however it is roughly derived from the chunk size and I can see that.

To make it non *power of two* one may have to go to something akin to 25 or 50. 25 being the "more performance oriented" choice and 50 being a more rounded number. Even then both of these options are not clean numbers. To get clean numbers one must go to further extremes which puts us at 10 or 100 and I think you can agree that smaller one of these two is worse than 32. Now I'd love to see 100 but I can also understand the performance implications.

*(Reopened so @tsunamayo will see this conversation)*

**Comment by tsunamayo** [comment]
So after the big free scale refactoring the new limit is "only" 16m. This being too deeply nested in the code and being to performance critical I have no leeway on changing this. Thanks for your understanding!
