### ISSUE TITLE
Suggestion: Lighting control block

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#763]

**Comment by Sullos** [comment]
So it may sound like a weird name, but I thought of it a couple of weeks back whilst lighting a ship, then just before on the discord I saw people mentioning a very similar idea.
Its somewhat basic, what would be good is if we had a lighting block, that a logic line can be connected to, and this lighting block controls all lights on the ship.
Having a switch hooked up to this lighting block would mean, turn the switch off, turn all lights off.
And reverse etc. It would be just like dragging a logic line to every light on the ship and having them all be turned off that way, but this way adds a much larger scale option.

An addon to this suggestion is that the light control block which controls the activation of all lights, can be coloured, and depending on the colour, if the colour is the same as the colour of the lights, then it only affects those lights.
This means people can have all white lights turn off, and not have all the blue or orange lights turned off if the control block is white.
Hopefully makes sense. And hopefully, you like the idea, as it adds a larger scale light activation-deactivation method for large ships. This would replace any other methods of lighting working with logic, but adds mass light altering options :)

**Comment by tsunamayo** [comment]
Okay I get the need for this, unfortunately it takes time to recompute light so it would  make the game lags too much. What I can do and most likely will do is have a master switch that would deactivate all systems including the lights, because that would be quite cheap on the opposite (no computation needed). Thanks!
