### ISSUE TITLE
Bug: Holo display data screen sub type broken

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#764]
I noticed this in the stable version, basically you can link the holo-screen data screen subtype to a block like the identity unit or a shield unit, but it can't be activated. You can link a switch to it, and flick the switch but the holo-screen won't activate. 
Basically just using the data screen, small holo screen brick, it doesn't work. It appears to be broken.

**Comment by tsunamayo** [comment]
Issue is now fixed, Thanks!
