### ISSUE TITLE
[EXP.] Brick Hinges offset when building on the ring

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#765]
Hi! It seems like the brick hinges are offset when set on a building built from the ring.

![12](https://user-images.githubusercontent.com/33256107/39257311-7fbb0180-48b1-11e8-9715-d40facee94bd.gif)

**Comment by JRL101** [comment]
What version are you using? and do you mean build on a habitat ring? 
|Does this happen with any other hinges or rotors? 
Does this happen on different faces of a block? (as in is does it slide the same axis no matter the orientation or does it keep it orientated to the brick?
Will test and respond later. This is similar to an old bug from ages ago.

**Comment by Name11ess** [comment]
I'm playing on 18w15b. Yes on a habitat ring.
The surface is indeed one block thin but it's around 10 to 15 meters above the surface of the ring.
It only seem to affect the brick hinge and whatever the orientation of said brick hinge, the rotating part will be offset the same way.

Left hinge is facing my left, right hinge is facing me :

![image](https://user-images.githubusercontent.com/33256107/39310751-8252dfca-496b-11e8-9781-63fcdb8a3e32.png)

**Comment by JRL101** [comment]
Ahh yes same direction offset, thats extremely similar to an old release bug. I'm sure Tsuna knows how to squash that one 😄 

In the image it looks like the height is opposite though.
Excellent image!

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
