### ISSUE TITLE
[Suggestion] [Fix] Block dragging (cont.)

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#766]
I know it has been said before, but I would like to note three block types that can't be dragged forcing one to place blocks one at a time. These three are quite critical to building and if I may be so bold, a patch to allow dragging again for these three sooner then later would be greatly appreciated. First is the engine block. Second is the 1-0.5 slope block. Third is the .5-0 slope block. All three are critical to building for everyone and require large amount of blocks to be placed. Placing one by one is really aggravating when you need to place 1500 of them... If you can add these back sooner then later, that would be greatly appreciated. I don't want to wait a month and I doubt others do either

**Comment by tsunamayo** [comment]
Okay gotcha, I will try to do a fix asap, but I am in the middle of something so it might wait a few days. Thanks!

**Comment by tsunamayo** [comment]
Okay this issue is fixed, I am uploading the new build now. Thanks!
