### ISSUE TITLE
[(Hopeful) Suggestion] 6DoF Alterations - Traditional Flight System Solution

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#767]
So as the game works for the moment I am having a lot of trouble enjoying or liking the way the new flight model works. However, over extensive talks with other players on the discord, I have done my best to try and suggest a solution that allows the people who actually like the newer 6DoF system, and a solution for those (including myself) who dislike it.

Problem:
So initially the problem seems to be 6DoF, whilst it may work for some ships, seriously reduces creative freedom of people trying to create specific ships, and also massively changes the way a lot of ships work.
For example, I have been building a large bomber, it's about 100m long, but with the new 6DoF system, I can fly it around like its a tiny fighter. Spinning it around, strafing sideways at 70m/s.. and that's it.
The system works great for fighters, you can do everything a fighter would be expected to be able to do because it's small and nimble. Hence what a fighter is.
However, 6DoF simple does not look natural, feel natural, or make any sense whatsoever on any ships that are mildly larger.

Solution: Have the ship core configurable. 
Similar to the mech core, how you can change it between eastern and western mech style, I suggest the ship core have a similar system allowing for a system where all ships start out as 6DoF system ships. But if you configure it, you can change it to Traditional.
'Traditional' would simply be the way of reverting the ship back to the original flight model.

The problem then stands that people could make their capital ships utilize the 6DoF system, maneuvering through an asteroid field like a ship from space invaders. The solution to this would be over a certain weight, a ship stops having the ability to utilize 6DoF flight systems. The weight scale would progress on a scale. So 100,000 kilo's is the max weight of a 6DoF fighter for example. Then for every 10,000 kilo's over, it loses 10% of its 6DoF speed. And so once a ship reaches 200,000 kilo's 6DoF not longer works at a reasonable speed, meaning people will need to switch to the 'Traditional' flight model.
So capital ships get the traditional flight system, fly forward, slow maneuvering thrusters, and a throttle that makes it go forward quickly or slowly.
Whereas fighters get the awesome maneuverability that the 6DoF system offers.
This seems like a way to please people on both sides of the argument.
And personally, I would feel 1000 times better if I still had the ability to use the 'Traditional' flight systems, as the new one simply doesn't feel right for me at all. And despite efforts to get used to it, I cant.

I would ask people think of this from a logical point of view. That fighters are not exactly the same as a capital ship in the way they move. Instead, Capital ships are able to move forward at great speeds, the same as how the traditional flight model worked, and that fighters be able to use the 6DoF just as would be expected of a space-age fighter.
On top of this, a problem with the newer 6DoF flight system is that inertia no longer exists because speeds return to normal if you let go of the key. The traditional flight model meant that you could set speed and just keep on going. Now coasting along isn't an option. I imagine it will be more desirable once planets and stellar objects are more openly available in the game. But for the moment I only notice its gone because I like to fly around and explore (what limited stuff there is). It makes more sense, especially in larger ships that aren't confining the players to a cockpit, that they be able to set a speed and leave the console without the ship slowing down. The traditional flight mode used this but the new 6DoF mode doesn't allow for this.

Separate to this solution, there is an issue with 6DoF right now where the throttle appears to be at 100 all the time. Because of this strafing is always done at super speed, and boost mode brings the ship up to maximum speed and keeps it there, instead of allowing for alterations of speed. Might not be a bug though?

**Comment by ZachZent** [comment]
One of the other problems with 6DoF, not including the capital ship lateral movement issue, is the removal of a maneuvering mode. Though the maneuvering mode is slow, it is best for... maneuvering. Getting in position to dock with a docking port or landing. With the 6DoF, doing that is near impossible when you instantly jump to 70 m/s. So when one can change the speed again (something disabled during the last update) adding this to the 6DoF, the ability to change speed, will allow one to maneuver slowly or normal fast 6DoF. This makes it so you won't have to add another mode to allow for maneuvering

**Comment by talrey** [comment]
I disagree that making the Core configurable is the right solution here. If the ship's mass / thrust were to affect the 6 DoF mode's speed and acceleration, there would be no need for a menu on the Core because large ships would make the 6 DoF mode useless just by being large.

That being said, I definitely support mass affecting 6 DoF mode's speed and acceleration; that only makes sense given that mass already has an effect on "Boost" or traditional plane flight mode.

As Sullos mentioned, the throttle setting on the pilot UI appears to be at 100 at all times (in both modes). While I'm wary of adding too many key binds to the game, being able to set the throttle percentage would solve two concerns I've heard recently (and have been mentioned here): 6DoF mode being hard to move precisely in (high acceleration), and Boost mode being impossible to slow down in.

**Comment by tsunamayo** [comment]
For sure the 6dof will use the ship mass / thrust ratio! It was just an experimentation on the control scheme, before spending too much time tweaking values and such I want to add proper gameplay. I was also thinking of separating the different mode, not sure how and if I will do it or not, again I will wait for more gameplay to pop in. It might be a different core, or different engine (or nothing)
For the maneuver yes this is something that must be adressed. First I will reduce the effectiveness of lateral thrust compared, which will help. Then I could have a landing mode when landing gear are deployed, but that would not help for docking... We will see. 
For thrust I want to simplify the control, if you want to boost, you want full thrust ;-)

**Comment by Sullos** [comment]
Okay, good to hear a lot of these things. Of course, I stand by where you take things, however, I am of the belief the Flight System currently on the Stable branch worked better.
I do look forward to a lot of the other things you have mentioned.
Thanks Tsuna :)

**Comment by MrBester** [comment]
Couldn't we just have 2 types of thrust? stick with the engines we have now for fast forward momentum and add some kind of RCS style thruster that needs to be used for maneuvering, make it so they have to be pointing in a direction to apply force from that direction? small ships wouldn't need many to apply sufficient force to push their small mass but a capital ship would need a lot for shift its huge bulk? This method would prevent huge mass ships from being able to out maneuver a fighter.

**Comment by Tomatart** [comment]
I personally think that the 6Dof does not feel good for any ship, even with small fighters it just feels cheaty to be able to move like that. Before it felt natural. That's my opinion on this; I prefer the old flight model.

**Comment by tsunamayo** [comment]
Lets close that discussion and open a new one with latest flight model improvement if necessary. Thanks
