### ISSUE TITLE
[Bug] Disappearing of brick placement hologram

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#77]
Often when removing bricks, the blue placement hologram disappears with it, meaning you can't replace a broken block, or replace it with a different one

Before:
![sky1 brick](https://user-images.githubusercontent.com/27857711/27233569-c6847f66-52b1-11e7-9492-10b9dc2ee326.png)

After centre block deletion
![sky1 brick 2](https://user-images.githubusercontent.com/27857711/27233613-f90a82c8-52b1-11e7-8c1d-fa1cda94eb5d.png)
Here I wouldn't be able to replace the broken brick if the brick below it wasn't there

We all appreciate your hard work!

**Comment by tsunamayo** [comment]
This annoying bug should have been fixed !
