### ISSUE TITLE
[Bug] Multi-Tool bug

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#771]
### Environment
- Skywanderers version: 18w15b
- Graphics Card: GTX 1060 6gb

### Expected behavior:
The little hologram of the canopy floating over the multi-tool.

### Actual behavior:
It isn't hovering over the multi-tool.

### Additional information:

[boop](https://drive.google.com/file/d/1rJERK_f5ipHOeOeOajy27xgmM8TwwjNz/view)

**Comment by tsunamayo** [comment]
Okay this is one of the weirdest bug I have saw, I wont spend more time on it though as this block will disappears and be replaced by a freeform one. Thanks!
