### ISSUE TITLE
[EXPERIMENTAL] Custom Color Not Displayed Properly On Hinges

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#772]
### Environment
- Skywanderers version: 18w15b

### Expected behavior:
Display Custom Color

### Actual behavior:
Displays default custom color

NOTE: Respawning the ship makes the color reappear correctly
### Additional information:
![20180501005635_1](https://user-images.githubusercontent.com/38502325/39454341-f4a1efa4-4cda-11e8-844f-c53079ff2082.jpg)
![20180501005654_1](https://user-images.githubusercontent.com/38502325/39454342-f4bc29be-4cda-11e8-9bd1-88a067117ab9.jpg)

**Comment by ProPeach** [comment]
I've also experienced this issue on all sizes of rotors as well as hinges ans sliders. Reloading will cause the paint to be displayed correctly, but then when you delete a block on that child entity, the custom paints revert back to their default colours again.

**Comment by tsunamayo** [comment]
Okay this issue is now fixed, it was introduce because of the new delete effect. Thanks!
