### ISSUE TITLE
[EXPERIMENTAL] Default Player Motion

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#773]
### Environment
- Skywanderers version: 18w15b

### Behavior:
There is a constant upward player motion. It's just a bit but it's constantly there

### Additional information:
Speed x5
![ezgif com-crop](https://user-images.githubusercontent.com/38502325/39469552-1e39c00e-4d39-11e8-8a56-a751c88a9da4.gif)

**Comment by Sullos** [comment]
I can confirm. I made a timelapse with Tomatart recently, hard to notice at normal speed, but sped up several times over with video editing, you can clearly see it.
https://www.youtube.com/watch?v=ByCSZszFa6Q&lc
Thats the video, most noticeable at ~3:13 when the cockpit is being built.

**Comment by tsunamayo** [comment]
I think this issue should have been fixed. Thanks!
