### ISSUE TITLE
No collision on freeform blocks

### ISSUE THREAD

**Issue by SkellyBard** [tsunamayo/Skywanderers#774]
### Environment
- Skywanderers version: 18w15b
- Graphics Card: NVIDIA GeForce GTX 770

### Expected behavior: 
You should be able to bump against freeform blocks when you place them

### Actual behavior: 
You pass through the freeform, it can still be interacted with however

### Additional information: 
This only seems to happen when placing a freeform block directly on a slider, when placing a regular hull block and then a freeform, this issue doesn't happen.

https://youtu.be/sE_e52Bsxds

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1965766/output_log.txt)

**Comment by tsunamayo** [comment]
Freeform were deprecated. Thanks!
