### ISSUE TITLE
Cannot exit chairs

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#777]
### Environment
- Skywanderers version: Experimetal
- Graphics Card: GTX 1070

### Expected behavior:
Exiting chair
...

### Actual behavior:
Cannot exit chair
...

### Additional information:
Holding F after leaving "pilot" mode will not let me leave the chair i'm sitting in. After exiting the Pilot mode you cannot re-pilot the ship while stuck in the chair.
_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1966043/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Sullos** [comment]
It also seems you cant exit anything that you 'enter'. So a ship core for example can be entered, flown, but exiting it, the circle appears and fills up, then you no longer have control of the ship, but still cant move.
As well as no longer being able to re-enter the shipcore.

**Comment by Sullos** [comment]
Actually further testing shows its only happening in multiplayer as far as I can tell.

**Comment by tsunamayo** [comment]
Hi, I cant reproduce this, it seems it was an error when you started to fly a ship. What ship did you fly? Do you get that with all the ships? Thanks

**Comment by Tomatart** [comment]
it happened with every ship we tried

**Comment by tsunamayo** [comment]
Okay, I cant reproduce the issue. When you say it happened with every ship, did you talk about the initial "enter the spaceship core", or the chair one? The chair issue is just a by-product of the initial bug - once the game break I guess yes not a lot of thing will work.
Do you have that in multi? 
I need a test case to reproduce. Like once you load the game, which ship do you enter? Thanks!

**Comment by Tomatart** [comment]
This was in multiplayer.
Every ship caused the same break; after exiting a ship core, you cannot
exit the chair or re enter the ship core.
However you can still trigger logic such as buttons
I proved this because i could open and close the canopy of my fighter after
the game broke.

**Comment by tsunamayo** [comment]
I cant reproduce the issue, even on multiplayer. Do you remember which ship do you try first? Do you close the game and restart a multi session each time before testing a new ship? Once the game break, each new ship you try will bug, which might wrongly indicate that all ship are bugged (in the case it is a ship dependent bug - not sure at this stage).

**Comment by Tomatart** [comment]
After further testing i also cannot reproduce this. I'm sorry for the late response, you can close this issue
