### ISSUE TITLE
Bug?: Selecting own players ship shows ship from players perspective on target cam

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#778]
### Environment
- Skywanderers version: Experiemental
- Graphics Card: 980Ti

### Expected behavior:
I imagine it either shouldnt be possible to select your own ship, or to at least see it from the outside perspective?

### Actual behavior:
When middle clicking, if you select your own ship as the target you can see the ship on the target cam, as well from a reverse players perspective. In the image below you can actually see the bridge of the ship I'm on which is behind me in the targeting cam area.

### Additional information:

![711980_20180502163252_1](https://user-images.githubusercontent.com/33239800/39508735-e58c0142-4e26-11e8-8077-44c7c1d46939.png)

**Comment by tsunamayo** [comment]
Okay this one is now fixed, thanks!
