### ISSUE TITLE
[EXPERIMENTAL 18w18a] Paint Blob will pause animation when interacting

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#779]
### Short Description of the issue:

As title, paint blob will pause when activating items like Blasters. Does not effect full blocks and bricks.

### Steps to reproduce the issue:

go to any interaction point, or build a starter block with a laser blaster on it

add a Paint to hotbar and select it

Press the activate key and hold it down while selecting the placed blaster. 
The paint will stop moving.

### Environment
- Skywanderers version:  18w18a
- Graphics Card: Nvidia GTX1060-6GB; MSI

### Additional information:

_https://puu.sh/AeFHl/e1762b7e63.mp4_

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1968097/output_log.txt)
`

**Comment by tsunamayo** [comment]
Thanks for noticing this, issue is now fixed! Cheers
