### ISSUE TITLE
[BUG] Build 2017-06-11 - Unable to connect hotkeys blocks with weapons and enter logic blocks

### ISSUE THREAD

**Issue by khowhl** [tsunamayo/Skywanderers#78]
As said in the subject, in the 2017-06-11 build, it is impossible to connect enter dual and quad command enter blocks and weapons to hotkeys blocks.

The virtual linking beam does appear when the hotkey block is right-clicked but it remains red even when hovering the pointer over weapons or command enter blocks.

The opposite is also true, right-clicking a command enter block and aiming the beam at a hotkey block doesn't turn the beam from red to green.

**Comment by tsunamayo** [comment]
This have been fixed ! Thanks for reporting the bug.
