### ISSUE TITLE
[Missing Feature] Missing sliding blocks part 2

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#780]
The critical ones are out of the way, but since you are looking for blocks that don't have the sliding which should (in my opinion) here is the wave 2 of unslidable blocks

First one is the hull tiled and normal hull .5-.5 slope
![Uploading zeropointfive.png…]()

Next are the Armature, both the cube and the angle
![armaetur](https://user-images.githubusercontent.com/36980446/39559000-e4c4e438-4e47-11e8-97c9-84da01757dd5.png)

Finally is the window and all canopies
![glass](https://user-images.githubusercontent.com/36980446/39559064-52c5efe0-4e48-11e8-81b0-1c88bc1368a1.png)

Like I said, not the most important blocks that need sliding but a list is a list :D

**Comment by ZachZent** [comment]
![zeropointfive](https://user-images.githubusercontent.com/36980446/39563695-13d1a9dc-4e66-11e8-9fce-0dbfb0769bef.png)
the 0.5 to 0.5. Picture didn't load

**Comment by tsunamayo** [comment]
Deprecated. Thanks
