### ISSUE TITLE
[Experimental 18w18a] Visual bug when upside down on torus

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#781]
When oriented "upside down" on a torus, a series of transparent lines appear on screen. They only seem to appear over the torus grass and sand textures

<a href="https://imgur.com/jdKi5ia"><img src="https://i.imgur.com/jdKi5ia.png" title="source: imgur.com" /></a>

Here is a gif showing the transition, you can see them form on the top left of the screen. They're particularly visible over the sand texture
https://i.imgur.com/VUHhe7R.gifv
OutputLog:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1972548/output_log.txt)

**Comment by tsunamayo** [comment]
It is an artifact linked to Ambiant Occlusion, that does not appears on the Editor, only in build, so it is a bit hard to track down... I will keep you posted! Cheers

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks
