### ISSUE TITLE
[18w18a] Unable to activate blocks after shooting at a ship with lasers in a world where shields have not yet been used.

### ISSUE THREAD

**Issue by etn249** [tsunamayo/Skywanderers#782]
steps
-Drive a ship with a laser brick (the projectile ones, as the beam and missiles do not cause the issue).
-Shoot a ship.
-Notice that it is no longer possible to use weapons, activate buttons and switches, or place and delete blocks.

notes
-This happened in a world where no shield block was present when the game was loaded.
-Once a shield block is placed on any ship, the bug no longer happens, even if the shield block is then removed.
-If all shield blocks are removed and the game is then saved and reloaded, the bug can happen again.

**Comment by tsunamayo** [comment]
Hum, okay could you retest in the new 19a version? Bug should be gone, but I would prefer to test on your world. Thanks!

**Comment by etn249** [comment]
I tested and the bug does seem to be fixed.

**Comment by tsunamayo** [comment]
Okay, glad to hear that! Thanks
