### ISSUE TITLE
Crashing when placing Engines

### ISSUE THREAD

**Issue by ThatFungiNub** [tsunamayo/Skywanderers#783]
### Short Description of the issue:

Not sure if this is an game bug or just me getting some bad luck, however when i place engine blocks my game decides to crash, not quite sure why

### Steps to reproduce the issue:

Just place blocks in a long line and eventually it happens not sure about the correct procedure of recreating it

### Environment
- Skywanderers version: 18w18a
- Graphics Card: GTX970 4gb

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1974343/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, this error should have been fixed! Cheers
