### ISSUE TITLE
light block and brick not lighting up nearby blocks

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Skywanderers#784]
in experimental light blocks wont work

![20180504214809_1](https://user-images.githubusercontent.com/37814990/39658629-2d66b95c-4fe5-11e8-81f5-2e67690ddafc.jpg)

In experimental spawn a blueprint and place a light generating block

**Comment by Senakysam** [comment]
Make sure the light is turned on. For some reasons my large ship has all the lights turned off when spawned in, might be similar.
