### ISSUE TITLE
Game stops working when loading ship

### ISSUE THREAD

**Issue by gmunga5** [tsunamayo/Skywanderers#786]
### Short Description of the issue:

So I have no idea why but for some reason when I attempt to spawn in this blueprint the game just dies all the time. It doesn't even properly crash it freezes up and produces the stopped working message box.

### Steps to reproduce the issue:

To reproduce the issue load in the attached blueprint and wait for a couple of seconds.

### Environment
- Skywanderers version:  Both stable and exprerimental as of 06/05/18
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1977173/output_log.txt)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1977174/error.log)
Ship Blueprint:
[Obsidian Class 2018.zip](https://github.com/tsunamayo/Skywanderers/files/1977175/Obsidian.Class.2018.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by gmunga5** [comment]
[error.log](https://github.com/tsunamayo/Skywanderers/files/1993451/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1993452/output_log.txt)
Just an update if the ship is already loaded you can usually open the word however some sections appear invisible and shortly after loading the blocks wont place and soon after the game will crash.

**Comment by tsunamayo** [comment]
Okay the ship can load now! Another beast by gmunga ;-)
