### ISSUE TITLE
[EXPERIMENTAL 18w18a] Weird canopy tool hologram behavior

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#787]
**Short Description of the issue**

Hologram glass canopy pieces orbit 'spawn' or the place where you loaded in after selecting a world. (at least Canopy Wedge, Canopy)

**Steps to reproduce the issue**

Mostly unknown recreation, the glass pieces orbit around where I loaded in after picking a save. Putting them in the hotbar prior to leaving the world may work or simply reloading in after creation results in the same thing. Afterwards just spin your character until you see the pieces fly around.

**Environment**

- Skywanderers version: 18w18a (also present in stable branch)
- Graphics Card: R9 390x

**Additional information**

Doesn't seem to happen on some other canopy pieces.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1982402/output_log.txt)

![20180508005613_1](https://user-images.githubusercontent.com/33102709/39739210-c205fda0-525d-11e8-91fc-80b3f594201c.jpg)
![20180508005627_1](https://user-images.githubusercontent.com/33102709/39739211-c21d3132-525d-11e8-8c69-da9dcd52e4eb.jpg)
![20180508005601_1](https://user-images.githubusercontent.com/33102709/39739212-c232380c-525d-11e8-9b55-2f92b4af3986.jpg)

**Comment by tsunamayo** [comment]
Hi, yes this is known issue and a very weird bug, and as I will replace canopy with some sort of freeform I wont spend much time on it... Thanks
