### ISSUE TITLE
[EXPERIMENTAL 18w18a] Canopy pieces are invisible from the inside

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#788]
### Short Description of the issue:

Placing the canopy blocks as I have done results in the inside of the glass being invisible in the corners, however, the outside is fine. I suspect it's from how you have set up canopy pieces to turn invisible in some situations to prevent some cosmetic oddities.

### Steps to reproduce the issue:
Placing the canopy pieces at the corners using flat blocks and a bottom small wedge should work as I have done.

### Environment
- Skywanderers version: 18w18a (also present in stable)
- Graphics Card: R9 390x

### Additional information:

Note how there is no glass tint in the corners at all, indicating its completely invisible from the inside view.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1982414/output_log.txt)

![20180508010135_1](https://user-images.githubusercontent.com/33102709/39739431-d2b839e6-525e-11e8-9733-28ecff0a08f6.jpg)
![20180508010140_1](https://user-images.githubusercontent.com/33102709/39739432-d2ce0960-525e-11e8-9e71-f4d8716a50fa.jpg)
![20180508010154_1](https://user-images.githubusercontent.com/33102709/39739434-d2f5afe2-525e-11e8-9c18-fe671d39094f.jpg)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
