### ISSUE TITLE
[EXPERIMENTAL 18w18a] Hose shenanigans when creating a child entity

### ISSUE THREAD

**Issue by Ar-Gent** [tsunamayo/Skywanderers#790]
### Short Description of the issue:

Hoses from a duplicated child entity want to connect to the original child entity, replacing the bricks fixes this issue. Persists on reload of the world unless replaced.

### Steps to reproduce the issue:

Creating a ship, place a rotate block, add a block, add studs, add a connecting hose, then on the same ship add another rotating block, duplicate from a save child blueprint of the other rotating block and watch them stretch and connect to the original.

### Environment
- Skywanderers version: 18w18a
- Graphics Card: R9 390x

### Additional information:

A before and after, showing a 'normal' duplicate, and the latter that replaced the afflicted hose. Notice on the fixed hose version, the original (on the left) hose little brick has dissappeared on fix of the hose. Probably another result of this issue.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1982901/output_log.txt)

![20180508040456_1](https://user-images.githubusercontent.com/33102709/39745413-270c1ba0-5275-11e8-9d20-fce1ed8063b5.jpg)
![20180508040503_1](https://user-images.githubusercontent.com/33102709/39745410-26da4f62-5275-11e8-8ffa-e47773c3835a.jpg)
![20180508040519_1](https://user-images.githubusercontent.com/33102709/39745411-26ec4f6e-5275-11e8-8331-e39241a480f9.jpg)
![20180508040522_1](https://user-images.githubusercontent.com/33102709/39745412-26fd9f80-5275-11e8-9ef2-f54e205d9908.jpg)

**Comment by tsunamayo** [comment]
Hose are deprecated. Thanks!
