### ISSUE TITLE
[18w19a][BUG] Freeform Custom Color on Child Entity not Working Correctly

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#792]
Freeform blocks painted a custom color on child entities isn't working. It stays the default custom color.
In the picture, you can see a mech and a ship. The red part of the mech should be the same blue-green as the rest, but it is a freeform block on a rotator. On the ship, the green section is a freeform block on a slider that is supposed to be the same grey as the rest of the hull.
![20180510090000_1](https://user-images.githubusercontent.com/26584892/39874536-9cfe9dd2-5433-11e8-8316-e980bde05778.jpg)
- Skywanderers version: 18w19a

Here's the two entities in question: 
[Hobgoblin and Mech11.zip](https://github.com/tsunamayo/Skywanderers/files/1991945/Hobgoblin.and.Mech11.zip)

**Comment by tsunamayo** [comment]
Okay issue is fixed! One day there will be no longer any freeform/custom paint/child entity issues. One day... Cheers
