### ISSUE TITLE
Engines are on by default when world is loaded (Experimental)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#793]
### Short Description of the issue:
After the most recent update, any ship in the save will have its engines turned on when the world is open.
...

### Steps to reproduce the issue:
On experimental build, leave ships in the save, and reload the save by closing the game and opening it again. All ship engines will be glowing, turned on.
...

### Environment
- Skywanderers version: Experimental 
- Graphics Card: GTX 970

### Additional information:
![image](https://user-images.githubusercontent.com/31857052/39899792-d3c5c124-54b5-11e8-9f82-c56281e71c38.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
yes I did that for testing I forgot to put it back at normal ;-) It is fixed now, thanks!
