### ISSUE TITLE
Third person flying "Press F to activate" bug - Experimental

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#795]
### Short Description of the issue:
When in third person, the "Press F to activate" prompt will appear if there is a block you can interact with in between the third person camera and your character. When turning it flashes and moves around which is very irritating when flying. In third person these pop ups don't need to appear at all.

...

### Steps to reproduce the issue:
Place an interactive block - in the case of the attached ship; a switch, directly behind the position the pilot would sit. When flying in third person the aforementioned pop up will appear and wiggle in the centre of the screen.

(to replicate this with the attached ship, put the seats down first to enter the cockpit)
...

### Environment
- Skywanderers version: Experimental 18w19a
- Graphics Card: GTX 970

### Additional information:
![image](https://user-images.githubusercontent.com/31857052/39952116-252a31b6-5589-11e8-89f6-24107f500746.png)
[Kite Shuttle Final.zip](https://github.com/tsunamayo/Skywanderers/files/1997219/Kite.Shuttle.Final.zip)
^ Ship I have encountered this issue on. Gady has also had this issue in the past.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
I see. I need to desactivate the ability to interact in 3rd person view, as you dont really see what the character head is looking at. Thanks

**Comment by tsunamayo** [comment]
This issue should have been fixed in recent build. Thanks!
