### ISSUE TITLE
Bug: Sheilds Remain Active even after being disabled

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#796]
### Short Description of the issue:

In simplest terms, if a shield block is hooked up to a switch you can turn it on and off normally. Since the most recent update, even after disabling the shields on a ship with a switch, and confirming they are turned off by linking a screen to the shields, the first shot taken at the ship still hits a shield. On occasion the shield will dissipate straight after being shot once, however on a larger ship with much higher shielding capability, the shields acted as if they were still on. I could shoot a ship and the effect of the shield going offline (bubble completely illuminates and then begins to disappear) would play after each shot taken. I could shoot 100 times and each time the shield would illuminate and then stay active, if shot enough occasionally the bullet would get through. In both cases the shield was turned off via switch and the data screens confirmed the shields were at 0.

### Steps to reproduce the issue:
Turn the ships shields off via a switch linked to the generator, shoot the ship with the shields supposedly turned off, and watch the shots hit the shield which shouldn't be there.

### Environment
- Skywanderers version: Experimental 18w19a
- Graphics Card: 980Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
This issue has been fixed for 19w32a. Cheers
