### ISSUE TITLE
Bug: Weapons Freeze State if a Ship is Shot Enough

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#797]
### Short Description of the issue:

When shooting a ship with a standard laser turret (pew pew kind), the new damage debris effect shows and it seems that shooting a ship enough will cause the game to go into a strange weapons free freeze..
In this stage, the weapons you were firing can no longer be fired, the damage debris effect plays continuously from the last point shot. Tested on 2 different ships after reboots. The game freezes and debris is constantly being ejected on an infinite loop, weapons can't be fired until game restart.
### Steps to reproduce the issue:
Shoot a ship without shields, keep shooting.. spam shooting seems to be somewhat required. Keep shooting the ship until guns cant be fired any more, and the damage debris appears to be emanating continuously from the same spot.

### Environment
- Skywanderers version: 18w19a? Experimental
- Graphics Card: 980Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ZachZent** [comment]
Out of curiosity, does this happen when the other ships hp is completely depleted? With the "new" combat update, ship health goes down when you shoot it

**Comment by Sullos** [comment]
I don't believe so. I believe it is only just having been shot, or perhaps its the same as just entering the turret. The same as someone else's issue?

**Comment by Lythnic** [comment]
Only 2 shots from a laser unit is enough to "freeze" the game, spamming does not seem to have an effect. it doesn't have to be a ship, it can be any block on any craft or buildings. in the freeze stage you can't activate any unit, like flying ships or pressing buttons. trying to delete blocks in this stage will just result in the block glowing more and more, eventually turning the block into a bright glowing white block.

**Comment by tsunamayo** [comment]
Hi, I have made some change in 20a, is this something you reproduce in these build? I cant reproduce on my side. Thanks

**Comment by Lythnic** [comment]
Hi Tsunamayo!
I could not reproduce the bug after the update.
By the way, I'm a big fan of your work :)
________________________________

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks!
