### ISSUE TITLE
[BUG] Ships all spawn on top of each other when loading worlds

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#80]
When I loaded my profile, all the ships seemed to have spawned in the same spot, like they've forgotten the coordinates they were previously at

![ships spawn at origin error](https://user-images.githubusercontent.com/27857711/27886085-71ddae44-61d2-11e7-8065-16df5914fbc6.png)

Hope it's an easy fix!

**Comment by tsunamayo** [comment]
Not sure what happens, tell me if you faced that once more!
