### ISSUE TITLE
[BUG] Unable to place bricks beyond a certain point on grids

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#801]
Sometimes when placing bricks, you can't place them beyond a certain plane. To fix this, you can place a larger brick piece in such a way that it brides this plane, and this will allow you to place bricks as normal. I've seen this happen on multiple grids, both child entities and main entities. 
...

I haven't been able to nail down exact steps yet, it seems random. I'd love to hear from anyone else who has a better lead though
...

Singleplayer and Multiplayer
- Skywanderers version: 18w19a
- Graphics Card: Nividia 1050M

https://i.imgur.com/i529KS1.gifv
Here you can see that I can't place any more than one brick closer to me as the stud does not turn red, until I place the larger wing piece.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2002375/output_log.txt)

You can see for yourself by attempting the same as you see in the gif above with the lower wing pieces on this blueprint
[Brick Placement Bug BP.zip](https://github.com/tsunamayo/Skywanderers/files/2002382/Brick.Placement.Bug.BP.zip)

**Comment by tsunamayo** [comment]
This issue is no longer valid as stud are deprecated. Thanks!
