### ISSUE TITLE
[BUG] Unable to do almost anything besides flying around after controlling turret

### ISSUE THREAD

**Issue by BratPfanneTV** [tsunamayo/Skywanderers#802]
# Short Description & Steps to reproduce

As soon as I control the turret in the tutorial building, I can fire exactly two times,
before everything just stops working. I can't control anything, I can't break or place anything, but I still
can fly around and save the game...

# Environment

- Skywanderers version:  18w18a
- Graphics Card: Radeon RX 580 Series

# Additional Info

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2010252/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I cant reproduce on my side, is this something you can reproduce all the time? Also the output.log would be useful in that case but it has to be taken after you actually have the issue, this one looks like it was taken at another time. Thanks!

**Comment by BratPfanneTV** [comment]
I have just done the exact same thing again in another world, on another day, so yes, I can reproduce it, without exception, every time. I can't upload the current output_log to github, because it tells me the file would be too big. I can upload it to my own webserver, though.

http://jriedel.info/files/output_log.txt

and this one was definitely taken after the issue appeared.

**Comment by Sullos** [comment]
Sounds similar to my issue from recently too.
https://github.com/tsunamayo/Skywanderers/issues/797

**Comment by UltraSabreman** [comment]
Just did the same thing in my game:

1) Build the tutorial turret
2) Started shooting the example turret to the left of it
3) As soon as it destroyed the stud plate, I couldn't shoot or build anymore but I could interact and configure items.

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks
