### ISSUE TITLE
Bug: Custom paint resets when deleting blocks

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Skywanderers#803]
### Short Description of the issue:

When the multi-tool is in the process of deleting a block, all blocks painted with a custom color reset to their original color; in this case, red.

### Steps to reproduce the issue:

Paint some blocks with a custom color and delete a block.

### Environment

- Skywanderers version: 18w18a stable

### Additional information:

The link below shows a video of the bug
[bleep bloop](https://drive.google.com/file/d/15kTpptBdImP6_qNpR0Sn-mKMQleC2S7H/view?usp=sharing)

**Comment by Senakysam** [comment]
What build are you using?

**Comment by PopkaAkula** [comment]
I was using the nonexperimental version 18w18a of Skywanderers

**Comment by Senakysam** [comment]
It should be fixed in the experimental version 18w19a.

**Comment by tsunamayo** [comment]
Thanks, indeed issue was fixed. Cheers
