### ISSUE TITLE
new AA causes texture artefacts.

### ISSUE THREAD

**Issue by oojimaflip** [tsunamayo/Skywanderers#805]
### Short Description of the issue:
the new Anti-Aliasing mechanism can cause some quite severe artefacts, I have disabled it for the time being as some strobing can occurr under certain conditions like rapid camera rotation.
![20180520102634_1](https://user-images.githubusercontent.com/33450683/40278213-fd794916-5c24-11e8-8d45-4a0d6262b587.jpg)
screenshot shows a banding effect on some textures.
![20180520102927_1](https://user-images.githubusercontent.com/33450683/40278216-1138648c-5c25-11e8-8907-593241067160.jpg)
screenshot show extreme darkening of texture detail at certain angles.
![20180520103143_1](https://user-images.githubusercontent.com/33450683/40278218-22987c44-5c25-11e8-9936-ff1d48e6a8b8.jpg)
screenshot show the same area with AA turned off.
...

### Steps to reproduce the issue:
Turn on AA, fly around some things.
...

### Environment
- Skywanderers version: 18w20a
- Graphics Card: 980gtx

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Issue is no longer relevant as TAA is not the AA solution anymore. Cheers
