### ISSUE TITLE
[BUG] Covering a hinge (2x1) causes the hinge to 'teleport' to the origin.

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#81]
Covering a 2x1 hinge with a wing block (attempted with a 4x1x1 and 4x1x0.5) causes the hing to teleport to the ship origin on blueprint reload. https://cdn.discordapp.com/attachments/271383633409998849/332628690720522240/small-hinge-bug.jpg

**Comment by tsunamayo** [comment]
Okay this is fixed, now you cannot overwrite an existing brick. Thanks
