### ISSUE TITLE
Suggestion - Add a temporary link to this Github repo in the game menu

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#810]
Seeing as the majority of players likely don't frequent the Discord server or forums, it's probable that they also don't know how and where to submit bug and crash reports. 
During this closed testing period, a main menu link to this forum could vastly increase the number of bugs reported. Of course, this comes with the increased likelihood of bug duplications and a much longer list of bugs to fix, but it's something to consider, although it's quite possible you already have!

Feel free to close this if it's no longer relevant
Cheers

**Comment by tsunamayo** [comment]
Yes I was thinking about this also, what would be really great is a way to book a case from the game ;-) I will see if I can do this one day. Thanks

**Comment by tsunamayo** [comment]
So there now a link from the start menu. I should also add a link from in game!
