### ISSUE TITLE
[Visual Glitch] - Trails

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#811]
I know that the version is changing sooner then later, but I have had this issue for awhile and now experimental, 18w20a, seems to be worse then usual

https://media.giphy.com/media/408xI9mxWhuO7YU2uG/giphy.gif

**Comment by ZachZent** [comment]
Also painting the engine a color doesn't always change the trail color

**Comment by tsunamayo** [comment]
Weird this should have been fixed, and I dont reproduce the issue. Is this something you are still having in 22a? Do you get this all the time? Thanks

**Comment by tsunamayo** [comment]
Trail are no longer in-game. Thanks!
