### ISSUE TITLE
Canopy texture isnt aligned 

### ISSUE THREAD

**Issue by Purpsy** [tsunamayo/Skywanderers#813]
### Short Description of the issue:
On the canopy wedge with the sides, the inside of the texture isnt properly lined up
...

### Steps to reproduce the issue:
Place a normal canopy wedge and place and canopy wedge with sides together 
...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: RX480 4gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![1](https://user-images.githubusercontent.com/39638696/40573393-39c3ea78-6104-11e8-83e1-90042d832d76.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2041398/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, all canopy will be replaced by a freeform version, so I can get rid of all that weird logic. Thanks!
