### ISSUE TITLE
[experimental 18w20a] [bug] [hovercraft] forward movement without input

### ISSUE THREAD

**Issue by LazyZarra** [tsunamayo/Skywanderers#815]
### Short Description of the issue:

for reasons unknown, the hovercraft speeds up to 16 m\s when I take control of it, without me telling it to do anything. At best I can tell it to stop by holding down the S key but as soon as I let go again, off it goes.

### Steps to reproduce the issue:

sit down in the default hovercraft and take control of it.

### Environment
- Skywanderers version: 18w20a
- Graphics Card: NVIDIA GeForce GTX 970

**Comment by tsunamayo** [comment]
Issue fixed with the new hovercraft tech. Thanks!
