### ISSUE TITLE
Glass Canopy Wedge Not lining up 

### ISSUE THREAD

**Issue by ahawke123** [tsunamayo/Skywanderers#818]
### Short Description of the issue:
Glass Canopy Wedge Not lining up with slanted blocks on one side
...

### Steps to reproduce the issue:
Place Down a canopy wedge attached to a slanted hull.
... 

### Environment
- Skywanderers version: 18w18a
- Graphics Card: NVIDIA GTX 1080  

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![20180527004043_1](https://user-images.githubusercontent.com/39649684/40576290-9a07f81e-6147-11e8-8f7a-dc41df0d2c81.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2041611/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, yes canopy are a nightmare to make it work, I will do a complete refactoring of them using the freeform block. Thanks
