### ISSUE TITLE
[Bug] Shooting something with with the tutorial turret prevents you from doing anything.

### ISSUE THREAD

**Issue by UltraSabreman** [tsunamayo/Skywanderers#819]
### Short Description of the issue:

Basically if you build the tutorial turret and shoot something with it, it'll "lock up" your game and prevent you from doing anything other then flying around. This is 100% reproducible. 

Here's a video: https://www.youtube.com/watch?v=2ZLOLGa0a8M

### Steps to reproduce the issue:

1) Load into tutorial world
2) Go to turret build room and make the second turret
3) Shoot the other turret twice
4) You wont be able to shoot or do anything anymore.

### Environment
- Skywanderers version: 18w18a
- Graphics Card: 1080Ti

### Additional information:

Here's a link to my entire skywanderes save/log directory. Figured this was easier then trying to find individual files: https://mega.nz/#!Jl0UTb5C!IHnRgnhW7wIMTI8tEbME_fIjkU9lku39O9Npcu0DCxM

Here's a copy of my DxDiag incase it helps: https://gist.github.com/UltraSabreman/6af854e57ee14de98c8eaac3b22e9570

**Comment by tsunamayo** [comment]
Thanks for the clear test case, I will keep you posted. Cheers

**Comment by Abyfall** [comment]
It happen if you use any sort of weapon with any vehicle on the tutorial, you shoot twice and nothing work anymore

**Comment by tsunamayo** [comment]
This issue should be fixed. Thanks
