### ISSUE TITLE
[SUGGESTION]  Light indicator color change

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#82]
It would be great to have a version of the sloped light indicator that toggled between two different colors (EX: Red to Green and back) Based on the input, 0=Red 1=Green for example

**Comment by tsunamayo** [comment]
Okay I see the need, maybe once multi colored brick are implemented it could be feasible.

**Comment by AfterRebelion** [comment]
Duplicate of https://github.com/tsunamayo/Skywanderers/issues/92
