### ISSUE TITLE
No textures

### ISSUE THREAD

**Issue by EpicJ155** [tsunamayo/Skywanderers#820]
### Short Description of the issue:
Nothing in the game world has textures besides the UI. The charatcer in the character customisation menu has no textures, and the star background in the menu can disappear also.

### Steps to reproduce the issue:
As far as i can tell, applying settings with a resolution set that isn't the default one causes this to happen. Resetting to the default resolution does not fix it. Re-installing hasn't fixed it either.

### Environment
- Skywanderers version: Latest? Not sure how to check. I bought and downloaded it yesterday.
- Graphics Card: Intel GMA x4500 (read off the side of my machine, i'm pretty sure i don't even have a card. Yes, the game does run very badly.)

### Additional information:
game looks like this:
https://i.imgur.com/iCaeONl.png
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

Output log: (reading this, it makes me feel like my old useless computer can't handle any of the shaders.)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2041928/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, yes unfortunately your card is well below the minimum required, it is not DirectX11 for a start.
What kind of game you usually play on it?

**Comment by EpicJ155** [comment]
In the log it states 'direct3D 11.0' but i guess that's not what i think it is. My computer usually handles 5-10 year old games with varying degrees of success. Newer games are a mixed bag, sometimes they'll run fine on low settings and sometimes stuff like this happens. I should be getting a newer more capable computer soon, so i guess i can try this again on that one.

**Comment by tsunamayo** [comment]
Okay glad to hear that! keep me posted if you have any issue with the new hardware. Cheers
