### ISSUE TITLE
infinite loading screen

### ISSUE THREAD

**Issue by eric123890** [tsunamayo/Skywanderers#823]
Whenever you start a new game after playing an old one the loading screen never stops.

create character, play, exit to title, create new game, loading.........

 -Skywanderers version: Current(?)
- Graphics Card: AMD r7 370

**Comment by Hayaweh** [comment]
Had the same when:
- Play single player
- Return to main menu
- Load another or similar save
- Experience serenity (infinite loading)

i7-4790k, GTX 980, game installed on a MX500 Crucial SSD

**Comment by swodaddy74** [comment]
I have exactly the same problem. There is an infinite loading screen after I get to it. Help!!!! I would love to play this game, but I haven't been able to yet.

**Comment by tsunamayo** [comment]
When this happens a work-around fix is to exit the game and relaunch it. In the meantime I will fix the issue. Thanks!

**Comment by tsunamayo** [comment]
Okay issue is fixed, now we can exit and reload. Cheers

**Comment by Dwarf-LordPangolin** [comment]
Looks like this bug is still happening for me. The workaround of quitting, restarting the game, and loading is still working. Here's the output_log if it helps.

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2091633/output_log.zip)
