### ISSUE TITLE
Can't place and break blocks after firing turrets

### ISSUE THREAD

**Issue by bub-lemon** [tsunamayo/Skywanderers#824]
### Short Description of the issue:
after using turrets, I cannot place blocks, break blocks, or activate some things.

...

### Steps to reproduce the issue:
Activate turret core and fire turrets

...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: AMD Radeon HD 7700 series

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2042682/output_log.txt)

**Comment by eric123890** [comment]
I'm having the same issue, it's like after I use a mech or ship, I can't build or destroy anything until I quit and come back.

**Comment by Napther** [comment]
This Bug already known, as per #819.

Remember to check at least the first page to see if issues pop up for others, and someone was faster! Some issues might even be related in ways not quite so obvious. Always good to keep an eye out.

**Comment by tsunamayo** [comment]
Hi, could you confirm that you dont get the issue is the new 20a version? Thanks!
