### ISSUE TITLE
Chunked up asteroids outside the asteroid ring

### ISSUE THREAD

**Issue by Einsdelwoben** [tsunamayo/Skywanderers#825]
### Short Description of the issue:
Asteroids are visually chunked up, some in a line outside the ring.
...

### Steps to reproduce the issue:
Fly towards the asteroid ring until just situated near the inside of the ring.
...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: Radeon HD 6750M

### Additional information:
![image](https://user-images.githubusercontent.com/39674590/40587672-70963272-620d-11e8-9075-b8861e68721d.png)
![image](https://user-images.githubusercontent.com/39674590/40587675-7a199258-620d-11e8-8d0e-b9c362aa3790.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2042757/output_log.txt)

**Comment by tsunamayo** [comment]
Issue was fixed. Thanks
