### ISSUE TITLE
Bug - Can not place freeform block on child entity

### ISSUE THREAD

**Issue by gundamaceNC** [tsunamayo/Skywanderers#827]
### Short Description of the issue:

After using a hinge I discovered that I am not able to place freeform blocks on the child entity.  I was not certain if this was a bug or an intentional limitation of the freeform block

...

### Steps to reproduce the issue:
Create a structure
place a hinge on the structure
Attempt to place a freeform block either on the hinge or on a block connected to the hinge.  It will not place.  The block will still place on the parent side of the hinge

...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, this is actually not an issue but a limit of hinge, hopefully I can fix it in the future. What was the kind of build you wanted to achieve ?(I am always interested in understanding user build case)

**Comment by gundamaceNC** [comment]
I was building a disk shape (currently working on a reproduction of the USA enterprise) using the hinges and I wanted to use the freeform block to create a longer wedge at the edges of the individual pieces on order to reduce clipping.

**Comment by tsunamayo** [comment]
Okay I see, thanks for your answer. I close the case it is not really an bug. Cheers
