### ISSUE TITLE
freeformblock becomes visible but is unresponsive to anny interaction

### ISSUE THREAD

**Issue by Kranot** [tsunamayo/Skywanderers#829]
### Short Description of the issue:
the "hull basic freeformblock" will not allow any interaction with it if placed sometimes. it does not allow me to:
-paint it
-delete it
-build on it
-edit it

and it has nomore hitbox and allows the player to phase through

...

### Steps to reproduce the issue:
it seems to happen at random when placing the beforementioned block. restarting the game, making a news save or even restarting the entire PC seem to have no effet on fixing or mitigating new appearences of this bug
...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: GTX 970

### Additional information:
![sqr](https://user-images.githubusercontent.com/39743393/40678016-a14febb0-637f-11e8-8434-ccddfd171d9a.PNG)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2049978/output_log.txt)
`

**Comment by tsunamayo** [comment]
Thanks, if you could send your blueprint that could help me reproduce the issue. Thanks!

**Comment by tsunamayo** [comment]
Freeform was deprecated. Thanks!
