### ISSUE TITLE
Unrecoverable state from pressing F on turret controller block

### ISSUE THREAD

**Issue by Cornflakes91** [tsunamayo/Skywanderers#83]
placed a turret controller and clicked F on it, couldnt move, couldnt press ESC, removed all UI.
could still interact with objects around me by pressing F.

also my view control range is limited to some cone (90x90 degree ish)
persisted when i entered and left a chair after the bug was triggered, cone rotated to line up with the center of the chair limited view cone
(seems to be related to https://github.com/tsunamayo/Skywanderers/issues/76)

only way i found to "recover" was to alt-F4 out of the game

**Comment by tsunamayo** [comment]
Hello, I am not reproducing the issue so I guess it was fixed. Dont hesitate to re-open the case if you see it again. Cheers
