### ISSUE TITLE
[BUG]Messed up Skybox

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#832]
### Short Description of the issue:
While warping I selected different destinations just before the jump ended and it messed up the skybox.
...

### Steps to reproduce the issue:
Look at screenshots
...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: GTX 1050 ti

### Additional information:
![20180526183201_1](https://user-images.githubusercontent.com/39653820/40689565-a283821a-639a-11e8-8d6a-1a5b9aa03f64.jpg)
![20180526183204_1](https://user-images.githubusercontent.com/39653820/40689567-a477921e-639a-11e8-8063-e61d949423c7.jpg)
![20180526183214_1](https://user-images.githubusercontent.com/39653820/40689575-abda4178-639a-11e8-8ba4-94fbfa75e555.jpg)
(also a bug)
![20180526183222_1](https://user-images.githubusercontent.com/39653820/40689584-b4a5a93c-639a-11e8-9039-9f36c6b5439d.jpg)
![20180526183223_1](https://user-images.githubusercontent.com/39653820/40689588-b7a5c446-639a-11e8-9a54-216001c80fd3.jpg)
![20180526183225_1](https://user-images.githubusercontent.com/39653820/40689591-b95db154-639a-11e8-8fa4-c48d8bda204f.jpg)
![20180529234126_1](https://user-images.githubusercontent.com/39653820/40689593-bd6526e2-639a-11e8-9ca4-92ff3560e1a1.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2051597/output_log.txt)

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
