### ISSUE TITLE
another crash, this one had a folder (experimental 14w20a)

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#833]
### Short Description of the issue:
don't remember what this one was but it was a successful crash that actually created the crash file
...

### Steps to reproduce the issue:
play the game? / be unlucky
...

### Environment
- Skywanderers version: 
- Graphics Card:  VEGA 64

### Additional information:
dont have an output log as it is an older crash
[error.log](https://github.com/tsunamayo/Skywanderers/files/2052310/error.log)

_(Screenshots, Videos, Error logs, Related iss
[crash.zip](https://github.com/tsunamayo/Skywanderers/files/2052311/crash.zip)
ues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, as said in the template:
Please also include the output_log.txt file. You can find your log here: %UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\
I need this file to investigate. Thanks!

**Comment by tsunamayo** [comment]
Cannot investigate. Tx
