### ISSUE TITLE
[Suggestion] Skywanderers Roadmap

### ISSUE THREAD

**Issue by SsynoO** [tsunamayo/Skywanderers#835]
I think it would be interesting to follow the development of Skywanderers in real time with common updates to a development roadmap much like Star Citizen's: https://robertsspaceindustries.com/roadmap/board/1-Star-Citizen

**Comment by ProPeach** [comment]
Have you checked out the roadmap on Kickstarter here?
https://www.kickstarter.com/projects/skywanderers/skywanderers/description

**Comment by SsynoO** [comment]
@ProPeach  No I hadn't, but I'm thinking something more like a detailed checklist that gets checked every so often just so we know exactly whats going on.

**Comment by tsunamayo** [comment]
Hi, I am doing regular video and a monthly update on kickstarter with what I have been up to and my planning for the next month.
I dont want to share too much on my internal planning - it is shifting too often to make sense for me, I dont think people are realizing that gamedev is not an exact science.
Also I am a single man studio so I dont have the same management constrain as a 100 millions dollars game - but that is actually great it means that I am way more efficient and flexible like that.
