### ISSUE TITLE
[Bug] Freeform blocks don't correctly show textures when extruded at 45* on certain entities

### ISSUE THREAD

**Issue by cmcarey** [tsunamayo/Skywanderers#837]
### Short Description of the issue:
The texture of a FFB will sometimes show incorrectly when at a 45* angle on only certain entities.

---

### Steps to reproduce the issue:
I struggle to reproduce this issue on any entity other than the large one that I initially discovered the bug on.  I have uploaded the blueprint of the build where I discovered the issue, and it is easily visible.

---

### Environment
- Skywanderers version: 18w18
- Graphics Card: GTX 1050

---

### Additional information:

*Demonstrating the issue. From left to right - a slope block showing expected type of texture at that angle, then an FFB at >45\*, then FFB =45\*, then FFB <45\*, then finally a slope block.*  The broken texture of the middle FFB is clearly visible.*
![image](https://user-images.githubusercontent.com/32423458/40742596-efb4f3d2-6446-11e8-9682-003aef6a0354.png)

*Side-on view of the above demonstration.*
![image](https://user-images.githubusercontent.com/32423458/40742612-ffd3ca2c-6446-11e8-9f4b-c6b6b778be8d.png)

*Demonstrating the same setup but on a new entity - all textures are as expected.*
![image](https://user-images.githubusercontent.com/32423458/40742706-38bd38d2-6447-11e8-945b-1b251effa42a.png)

*Side-on view of second demonstration.*
![image](https://user-images.githubusercontent.com/32423458/40742712-3ed82c68-6447-11e8-81b2-60ea5fb254f5.png)

---

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2055343/output_log.txt)

[Forger.zip](https://github.com/tsunamayo/Skywanderers/files/2055347/Forger.zip)

**Comment by HUBO-ZA** [comment]
i've noticed this especially on larger FFBs, not as visible on smaller ones, but trying to go large usually mess up the textures at certain angles and sizes, making it just look like large lines instead of an appropriate Texture

**Comment by tsunamayo** [comment]
Freeform were deprecated. Thanks!
