### ISSUE TITLE
[Suggestion] 1x4 Tetra blocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#84]
To compliment the 1x4 block slopes we have ingame, 1x4 tetras would provide even more building opportunities for players.

Additionally, the 1x4 set of blocks should be available in different hull types, such as the textured hull.

Thanks, and keep up the good work!

**Comment by AfterRebelion** [comment]
Tetra can be freeform in recent versions (19w23b)

**Comment by tsunamayo** [comment]
That was the reason I pushed for freeform, to limit the exponential explosion of blocks shapes ^^
