### ISSUE TITLE
[EXPERIMENTAL 18w20a] Unable to rotate some system blocks

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#841]
### Short Description of the issue:
It is currently impossible to rotate blocks like Thruster. I believe they used to be able to be rotated, but, that feature was conflicting with multi-place... Which now overwrites its rotate.
...

### Steps to reproduce the issue:
Attempt to change the orientation of thruster using mousewheel and default bind for paint menu.
...

### Environment
- Skywanderers version:  18w20a
- Graphics Card: NVIDIA GTX 1060-6GB: MSI Aero

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Ah the base plane orient you mean? I will likely change the way we rotate for various reasons, I just need to test that first. So I might not fix this bug hope it is not too painful ^^

**Comment by tsunamayo** [comment]
Issue was fixed some time ago. Thanks!
