### ISSUE TITLE
Blueprint turns partly invisible then crashes game

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#843]
### Short Description of the issue:
Spawning in ship blueprint causes game to crash or one side of the rear engines to become invisible
...

### Steps to reproduce the issue:
1. spawn in the ship
2. crash
...

### Environment
- Skywanderers version: current and experimental
- Graphics Card: Vega 64

### Additional information:
tried re installing, no luck. hotkeys don't work on all turrets except the bottom one as well.
_(Screenshots, Videos, Error logs, Related issues)_
[shippy18.zip](https://github.com/tsunamayo/Skywanderers/files/2065393/shippy18.zip)
![20180602141301_1](https://user-images.githubusercontent.com/14081996/40880998-937f1102-6670-11e8-8e5a-1b00ea1ffcbd.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2065398/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay I fixed the issue, you should be able to load your ship starting from next update! Thanks
