### ISSUE TITLE
[BUG/EXPERIMENTAL] Cannot link Control Sticks to Ship Cores

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#845]
Title sums it up pretty well, I cant seem to connect any type of control stick or panel to a ship core.

I tried this in an old world file and a new world file, however, they both did not function.

(Im not really sure what other information I can give, let me know if you need anymore)

![image](https://user-images.githubusercontent.com/29961381/40886834-0b81dbfa-6737-11e8-92a4-85f570116549.png)

**Comment by tsunamayo** [comment]
Okay this one is fixed. Thanks!
