### ISSUE TITLE
[Bug/Experimental] Unable to link control sticks to spaceship core

### ISSUE THREAD

**Issue by cmcarey** [tsunamayo/Skywanderers#846]
### Short Description of the issue:
Attempting to link any type of control stick to a spaceship core does not work.  
It seems the link tool does not recognize the spaceship core as a valid target.

----

### Steps to reproduce the issue:
- Attempt to link control stick to spaceship core
- Observe bug

---

### Environment
**Skywanderers version** 18w22a.  
**Graphics card** GTX 1050.

---

### Additional information:

![image](https://user-images.githubusercontent.com/32423458/40886894-07d9502c-6738-11e8-998b-9d04a0941007.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2065973/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this one is fixed. Thanks!
