### ISSUE TITLE
[Bug][Experimental] Old issue of not being able to toggle mirror blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#849]
Can no longer toggle mirror blocks on or off... again... xD

- Skywanderers version: 18w22a
- Graphics Card: GTX 970

I would upload my output log buttttt it's... big

**Comment by tsunamayo** [comment]
Hi, I cant reproduce the issue, could you please give me a test case? Can you reproduce all the time? If the log file is big it might means that there was another issue, and the game broke, so it might not be mirror related. Thanks

**Comment by Xerma** [comment]
Forgot to mention it was during multiplayer. I'll see if someone can help me reproduce

**Comment by Xerma** [comment]
Worked 12 hours today so I'm pretty wiped out atm but issue #858 seems to explain it better

**Comment by tsunamayo** [comment]
So as we have a new symmetry workflow this is no longer applicable. Thanks!
