### ISSUE TITLE
[BUG]  Full size pipe blocks are rotated incorrectly

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#85]
Some pipe block models appear to be rotated incorrectly, only the full size ones that I noticed, Example: http://i.imgur.com/ZXWfY4G.png

**Comment by Tomatart** [comment]
Can confirm this is an issue,.

**Comment by tsunamayo** [comment]
Thanks, the blocks have now been updated to confirm with the new pipe format!
Cheers
