### ISSUE TITLE
[Bug/Experimental] Removing a logic gate does not remove links

### ISSUE THREAD

**Issue by cmcarey** [tsunamayo/Skywanderers#851]
### Short Description of the issue:
Difficult to recreate but occasionally I have noticed that removing a logic block will not remove any output links from the block (see the screenshot).

---

### Environment
**Skywanderers version** 18w22a.
**Graphics card** GTX 1050.

---

### Additional information:
![image](https://user-images.githubusercontent.com/32423458/40890368-d0159576-676c-11e8-9523-0a93e59ee9b5.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2066294/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I cant reproduce that issue, was it used only with the logic gate (the AND / OR) or any logic component?
Thanks

**Comment by talrey** [comment]
I can confirm having the same issue. The deleted brick in the screenshot below was the Logic Command brick.

![20180603112516_1](https://user-images.githubusercontent.com/6946291/40898950-11a88c26-6779-11e8-8997-a984e38a716b.jpg)

**Comment by tsunamayo** [comment]
Okay I was able to reproduce indeed, and I fixed the issue. Thanks!
