### ISSUE TITLE
18w20a Game volume resets to maximum after Quitting to Title Screen

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#852]
### Short Description of the issue:

The volumes of sound and music reset to their maximum value after quitting to the title screen from the game world.

### Steps to reproduce the issue:

Set the desired volumes in "options / sound". Enter the game world. Press escape. Click "Quit to title screen". You'll hear maximum volume button clicks. Check "options / sound" again. You'll see the sliders are on their maximum setting.

### Environment
- Skywanderers version: 18w20a
- Graphics Card: Sapphire Radeon R9 290 Vapor-X

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

Initialize engine version: 2018.2.0b3 (0a6b93065060)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon R9 200 Series (ID=0x67b1)
    Vendor:   
    VRAM:     4072 MB
    Driver:   21.19.407.0
Begin MonoManager ReloadAssembly
- Completed reload, in  0.106 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.585266 ms
SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

RESTARTING THE GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading all textures
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

TEXIM LOADED 401
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

DAMAGE DEPTH8
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Fonctionnal Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Hull Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Functional Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Logical Components
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System GFX memory 4072 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System memory 16283 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Suport sparse texture?  False
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Level 0 computation finished 106710
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Level 0 computation finished 107127
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

EXITING GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 17d4 -> priority: 1 
  Thread -> id: 1168 -> priority: 1 
  Thread -> id: 728 -> priority: 1 
  Thread -> id: e28 -> priority: 1

**Comment by tsunamayo** [comment]
Thanks, yes it is an old bug appearing randomly for some people, I was never able to reproduce. I will keep you posted! Thanks

**Comment by Cpt-Fortius** [comment]
Bug's still active.

One thing to add; Setting the volume in the main menu also has no effect on the volume in-game.

**Comment by tsunamayo** [comment]
This issue should now be fixed. Thanks
