### ISSUE TITLE
Bug: Low Resolution Inventory Textures

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#855]
### Short Description of the issue:
It seems as of the graphics update, the textures of the blocks/items in the inventory have gone to a lower resolution.
I play on a 3840x2160 monitor, and its like I am going blind almost due to everything else being high resolution, except for the blocks on the hotbar and the ones in the inventory.

### Steps to reproduce the issue:
Be on 3840x2160 resolution and look at blocks on the hotbar or in inventory.

### Environment
- Skywanderers version: Stable & Experimental
- Graphics Card: 980Ti Nvidia

### Additional information:
Kinda hard to show it, as screenshots are generally down-scaled to be only 1080p and so the images look normal. And unless you have a 4k monitor you wouldn't be able to see it either. :(

**Comment by tsunamayo** [comment]
I would need a screenshot to see what is up ;-) I only have a 1080p monitor. Thanks

**Comment by Sullos** [comment]
I took a high quality screenshot, and hopefully it still retains its quality. But as you can see, (hopefully) the block in the preview area is normal quality. 4k resolution for me.
Where as the blocks and everything in the actual inventory and hot bar, they're all blurry..
<img width="1920" alt="skywanderers 2018-06-05 11-06-30-102" src="https://user-images.githubusercontent.com/33239800/40949374-24c79c3c-68b1-11e8-8e98-7d2e3e1fc5bf.png">

That's the best way I can describe it :/
Thanks

**Comment by tsunamayo** [comment]
Okay it is clear, it has something to do with UI rescale. I dont have a 4K monitor so I cant have a feel for it, but would you prefer to have a smaller UI or a rescaled like that? What other game are doing (is their UI super small) thanks

**Comment by Sullos** [comment]
I would prefer having the UI the same size as it currently is, if its possible. Its current UI scaling method for resolution seems to be great. But since the more recent graphical changes - the inventory is low res.
If the textures can be made to be higher resolution again, whilst keeping the gui the same size that would be wonderful.
It was working in 4k for a long time, only since the recent stable and experimental branch updates has it been like this.
But if nothing can be done, i think a smaller UI would be the best option, it strains the eyes having two different resolutions on top of each other otherwise.
Thanks :)

**Comment by tsunamayo** [comment]
I think it should be fixed in newer version. Thanks!
