### ISSUE TITLE
[Bug] Engine Trails Not Right Color

### ISSUE THREAD

**Issue by Sh4d0wNut** [tsunamayo/Skywanderers#856]
### Short Description of the issue:
The engine trail on my new ship isn't keeping its color for 3/4 of the engines.
...

### Steps to reproduce the issue:
Not really sure how to make it happen on other ships, but on this ship it happens whenever I reload the game or spawn in a blueprint of the ship, might be since not all the engines are colored just the back ones?
...

### Environment
- Skywanderers version: 18w20
- Graphics Card: Nvidia 1060 6gb

### Additional information:

_(Screenshots
![capture](https://user-images.githubusercontent.com/39914402/40923195-6184a146-67d1-11e8-903c-b2c25991063b.PNG)
, Videos, Error logs, Related issues)_

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2068645/output_log.txt)

Blueprint:
[Constellation.zip](https://github.com/tsunamayo/Skywanderers/files/2068669/Constellation.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
