### ISSUE TITLE
[BUG]declaring an ID on a identiy block on a child entity causes crash and 3 other issues

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#857]
### Short Description of the issue:

1.  When trying to set up a name on a child entity (usually the second try) you will be unable to close the id menu and will be forced to force quit the game, you are still able to save after the glitch has happened so it isn't a full freeze but it is frustrating

2. Experimental Logic problems:
Hoses cannot be linked,
ALL cores cannot be linked to a controller, holograms have issues linking to id blocks. 
Sequencer values change when entering it after activating, usually a bizarre number between 2 and 3, thus defaulting to 1 if you do not fix it every time you try to look at a value. (occurs on small sliders)

3. Hitbox issues on the thin line sticker, (impossible to break from the front, have to get on the side)

4. Dock floating, placing the docking needle on the dock insert and activating it causes the ship to float off. 

The end of the ship became invisible again on logging back on. this was fixed by saving the blueprint and pasting in another copy. 
...

### Steps to reproduce the issue:
1.Try and create a blueprint of a child entity, having done so, try and paste it. try the same after deleting the original blueprinted version. or simply try renaming the blueprint after trying to link it. It will happen eventually.

2. 
try linking a hose with the link tool.
try linking a core
set up a small slider and a sequencer and play with the values, check the sequencer each time 

...

### Environment
- Skywanderers version: Experimental
- Graphics Card: VEGA 64

### Additional information:
thanks for fixing the last issue. it's nice to be able to work on my ship again!  Now all I need are my hoses back!
_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2070847/output_log.txt)
[shippy21.zip](https://github.com/tsunamayo/Skywanderers/files/2070848/shippy21.zip)
if you aren't able to recreate the ID block crash, don't hesitate to let me know and I will try to record it.

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi! So the basic rule of thumb is one Issue per case, so I can track them better, close them ect. Thanks for being an active tester!

**Comment by pinesh** [comment]
would you like me to make this into 4 individual reports?

**Comment by tsunamayo** [comment]
Issues fixed or no longer applicable. Thanks
