### ISSUE TITLE
[BUG]Player activation only passes value of 1

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#858]
### Short Description of the issue:
activating anything in the game causes a 1 value to be passed instead of the previous 1 and 0. thus everything can only be toggled on and not off again "mirror blocks stuck on" "holo blocks stuck on" "sliders only able to move one way and not back" this is mitigated by a switch so the effect isn't permanent but it is frustrating.
...

### Steps to reproduce the issue:
activate pretty much anything a switch can. 
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: VEGA 64

### Additional information:
realized I really need to report more bugs I encounter as many slips through the cracks on the discord.

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2070863/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by JRL101** [comment]
I was finding i couldnt activate ANY thing unless it was a button hooked thorough the new logic.

**Comment by tsunamayo** [comment]
This was fixed in recent build. Thanks!
