### ISSUE TITLE
Ship spawns with missing chunks

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#859]
### Short Description of the issue:
Ship spawns with missing chunks. This started occurring after I placed engine blocks, I'm not sure if that is the cause.
![screenshot 52](https://user-images.githubusercontent.com/26846110/41015953-6629856e-6901-11e8-90f1-f047f344f3fe.png)

...

### Steps to reproduce the issue:
Spawn the ship with a blueprint block, it happens in new worlds, existing worlds and both singleplayer and multiplayer.
...

### Environment
- Skywanderers version: stable
- Graphics Card: GTX 1070

### Additional information: After deleting and re spawning the ship several times sometimes it will spawn without any missing chunks, but this is not guaranteed and doesn't seem to have a pattern of why it happens.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2074222/output_log.txt)

`%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Tomatart** [comment]
I forgot to attach the ship file, lol
[Ship in question.zip](https://github.com/tsunamayo/Skywanderers/files/2074224/Ship.in.question.zip)

**Comment by gmunga5** [comment]
I have the same issue with my obsidian class

**Comment by tsunamayo** [comment]
Should be fixed in recent versions. Thanks!
