### ISSUE TITLE
[BUG] Canopy edges laying on top of holograms

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#86]
In this instance, I have a small hologram displaying a ship placed within a canopy block
(Don't mind the airship in the background, it only has, uh, 2 child entities hehe)
![visualbug1](https://user-images.githubusercontent.com/27857711/28928869-572df108-7866-11e7-97ab-4bf501f45cae.jpg)

I noticed that even though the hologram is in front of the canopy, the canopy edges still overlay the hologram

![visualbug3](https://user-images.githubusercontent.com/27857711/28928919-78cc9b70-7866-11e7-87e9-862b6bbd270a.jpg)
![visualbug2](https://user-images.githubusercontent.com/27857711/28928922-7ac9b368-7866-11e7-9510-099d791259c2.jpg)

Thanks for reading :)

**Comment by ProPeach** [comment]
I've now also noticed this happen with translucent bricks
![rendering error](https://user-images.githubusercontent.com/27857711/28977171-e6c7ac0a-7938-11e7-93d1-58506d7a3340.png)

**Comment by tsunamayo** [comment]
Yes, unfortunately correct transparency order is a problem very hard to solve... 
It might be a bit improved one day during the rendering refactoring planned, but dont expect miracle =(
