### ISSUE TITLE
[BUG] black line on planet rings

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Skywanderers#860]
### Short Description of the issue:
seems to be a visual bug when close to a planets ring when looking at the said planet. 
...

### Steps to reproduce the issue:
go to planetoid rings, look at planet
...

### Environment
- Skywanderers version: experimental
- Graphics Card: Vega 64
![20180606150746_1](https://user-images.githubusercontent.com/14081996/41068061-c25e03e6-699c-11e8-94b3-b161cfdbb79a.jpg)
![20180606150714_1](https://user-images.githubusercontent.com/14081996/41068066-c7de7b48-699c-11e8-8561-6e0d3273c4ef.jpg)

### Additional information:
sorry about the fancy pics, but the visual bug is visible in them
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can fi
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2078337/output_log.txt)
nd your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Yes indeed it a known issue of my crappy hacky ring cloud rendering... Thanks

**Comment by tsunamayo** [comment]
Issue is fixed with the new ring rendering tech. Thanks!
