### ISSUE TITLE
Large Freeform

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#862]
### Short Description of the issue:
When attempting to shape a freeform block into an excessively large panel the game lags horribly.
This is known but i'm wondering if this is planned to be fixed, or if i should expect to not be able to use large freeform at all as there will be an alternative/not be possible in the future.
...

### Steps to reproduce the issue:
make a large freeform block
...

### Environment
- Skywanderers version: Stable
- Graphics Card: GTX 1070

### Additional information:
The attached picture shows the panel in question. The red triangle is the panel outline, and the pink lines mark 32 block segments. This shape is only possible by using freeform or child entities, i chose freeform because it is what you want us to use instead.
_(Screenshots, Videos, Error logs, Related issues)_
![screenshot 56](https://user-images.githubusercontent.com/26846110/41084585-7c1f63dc-69e9-11e8-9734-da29e707edf8.png)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2079339/output_log.txt)
`%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ZachZent** [comment]
Potentially instead of the partially translucent texture, maybe a simple wireframe of area. Edges and cross. Should remove the lag of the large size

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
