### ISSUE TITLE
Pressing [F]-"Interact" is disabled.

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#865]
### Short Description of the issue:
Unable to "Use [F] To interact" on logic or lights and some other things, including old logic bricks
...

### Steps to reproduce the issue:
press [F] or hold [F] on any switch or logic. 
Buttons still seem to work.
Chairs work.
Hinges/Rails/lights seem to be ON only.
Switches don't seem to activate even if they are off.
...

### Environment
- Skywanderers version: 18w22a (experimental)
- Graphics Card: Nvidia GTX1080 (not Ti)

### Additional information:
![image](https://user-images.githubusercontent.com/33255536/41181551-b75035f0-6ba4-11e8-91b7-dbade2ae7a72.png)
Uploading a blueprint of the "TEST BED" showing the issue off.
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2086132/output_log.txt)

[Ex18w22a_PressF.zip](https://github.com/tsunamayo/Skywanderers/files/2086134/Ex18w22a_PressF.zip)

**Comment by JRL101** [comment]
Possible relation to https://github.com/tsunamayo/Skywanderers/issues/858

**Comment by tsunamayo** [comment]
Issue was fixed some time ago. Thanks!
