### ISSUE TITLE
Bug? / Suggestion: Plate B Textures Don't Connect Horizontally

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#866]
### Short Description of the issue:

Plate B block vent lines connect vertically but not horizontally similar to blocks of a similar style.

### Environment
- Skywanderers version: Experimental
- Graphics Card: 980 Ti

### Additional information:
![711980_20180609121824_1](https://user-images.githubusercontent.com/33239800/41186818-9c36687a-6be0-11e8-8812-dd05f99ebc24.png)
As you can see the lines and vent texture connects with the same block above it, but when placed next to it, the textures don't connect. I think they used to? But in any case it would be good if they did connect,

![711980_20180609122600_1](https://user-images.githubusercontent.com/33239800/41186829-c69b4cac-6be0-11e8-8465-e852514e5fd8.png)
Plate C I believe it is does connect in the desired way, and that's what I would hope to see of Plate B

Just a cosmetic issue/change.

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
