### ISSUE TITLE
[Bug][Experimental] Connections to anything other than logic bricks is broken

### ISSUE THREAD

**Issue by ComputerCake** [tsunamayo/Skywanderers#868]
### Short Description of the issue:
When attempting to connect any systems other than logic bricks, moving parts and inputs the link tool doesn't allow it. For example Trying to connect a control stick to a ship core, or a hyperspeed block to a holo display.

### Steps to reproduce the issue:
Attempt to connect a ship system block (Ship Core, Reactor, Shield, Hyperspeed Block etc) to a display or otherwise compatible block.

### Environment
- Skywanderers version: Experimental (18w22a)
- Graphics Card: Nvidia GeForce GTX 760

### Additional information:
I am aware that this issue has been brought up before by others, however I wanted to expand on it slightly.

 [output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2091447/output_log.txt)

**Comment by tsunamayo** [comment]
Display/holo link have been added back, enter command link is fixed. Thanks!
