### ISSUE TITLE
[Bug] Invisible blocks

### ISSUE THREAD

**Issue by TheValiantColonel** [tsunamayo/Skywanderers#870]
While building a large ship, I discovered that blocks were beginning to go Invisible, or not render properly, Towards the back of the ship blocks rendered slowler and the the situation worsened.
![major problemo](https://user-images.githubusercontent.com/28892486/41321685-05da2334-6e9d-11e8-9edc-8d4440c8e339.jpg)
![problemo](https://user-images.githubusercontent.com/28892486/41321689-0ad83f88-6e9d-11e8-9333-0bc18c1bfd56.jpg)
Unless this is an Issue already encountered, is there a way to fix it?
Thanks!

**Comment by tsunamayo** [comment]
This issue should be fixed in most recent versions. Thanks!
