### ISSUE TITLE
[Bug] Blocks painted with darker colors look pure black

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#871]
### Short Description of the issue:
Many blocks do not have the correct colors, but instead look completely black. This is not universal, but tends to apply to darker colors. This is true for both default and custom paint colors. The block's proper color can be seen if the flashlight is turned on, and the block is examined at very close range.

### Steps to reproduce the issue:
Paint any block with a darkish color.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20180612192112_1](https://user-images.githubusercontent.com/33041786/41323765-4471e036-6e76-11e8-9167-3a5005719720.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2096210/output_log.zip)

**Comment by Dwarf-LordPangolin** [comment]
Additional note: it looks like this bug also changes the color of bricks.

![20180613134437_1](https://user-images.githubusercontent.com/33041786/41371451-fb04eba6-6f0f-11e8-962a-bf535ceaa70c.jpg)

**Comment by tsunamayo** [comment]
Hey @Dwarf-LordPangolin , I am catching up on older issues. Is this something you encountered in recent issues? Thanks!

**Comment by tsunamayo** [comment]
Issue should be fixed. Thanks
