### ISSUE TITLE
[Bug] Pasting a child object with logic links has broken links

### ISSUE THREAD

**Issue by commandertaggart** [tsunamayo/Skywanderers#873]
### Short Description of the issue:
When pasting a child element from a blueprint, any links from bricks in the copy will point to the bricks in the original, not in the copy.

### Steps to reproduce the issue:
1. Create a child entity.
2. Create logic links between bricks within the child entity.
3. Add an ID block and create a child blueprint.
4. Paste a copy of the blueprint nearby the original.
5. Note logic links from bricks in the copy lead to the target bricks in the original.

### Environment
- Skywanderers version: pre-alpha 18w24a
- Graphics Card: Nvidia GeForce 1080

### Additional information:
![20180613093906_1](https://user-images.githubusercontent.com/6404354/41365370-141dca58-6eee-11e8-9f3e-a387209f7696.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2099063/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
