### ISSUE TITLE
Right-ALT key movement with no key-mapping

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#874]
### Short Description of the issue:
my right-ALT key moves me down. I have no keymappings set to right-ALT, or either ALT key.

### Steps to reproduce the issue:
no idea.... be me?

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX970

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2099534/output_log.txt)

**Comment by Vicomt** [comment]
Additionally, unmapping LEFT CTRL from down movement stopped this happening, and made it happen when mapped. I believe the LEFT CTRL and RIGHT ALT key mappings are linked.

**Comment by tsunamayo** [comment]
Issue must have been fixed. Thanks
