### ISSUE TITLE
[BUG][EXPERIMENTAL]paint on basic hull freeform blocks

### ISSUE THREAD

**Issue by sqeesqad** [tsunamayo/Skywanderers#876]
### Short Description of the issue:
when i place a basic hull freeform block, the paint is all weird and way too blue
...

### Steps to reproduce the issue:
place a basic hull freeform block
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: MSI gtx 1050 TI

### Additional information:
screenshot: 

https://cdn.discordapp.com/attachments/416013956331601930/457172384017940480/unknown.png
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2106245/output_log.txt)

**Comment by MrBester** [comment]
can confirm i have this problem too, every FFB i have in game has gone almost black, its almost like the colour filter or something is borked for ffbs.

**Comment by tsunamayo** [comment]
Issue is not longer applicable. Thanks!
