### ISSUE TITLE
[BUG] Turrets Can't Be Linked

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#877]
Currently, you can't link the turret to the different rotators and camera with the new logic system. You click on the link icon and it closes the menu like normal, but you don't actually have a link to connect to anything.

Skywanderers version: 18w24a

**Comment by Lord-Asage** [comment]
I am currently having the same issue.

**Comment by Senakysam** [comment]
This also applies to mechs, hoses, and the flat sliders.

**Comment by tsunamayo** [comment]
Issue was fixed sometime ago. Thanks
