### ISSUE TITLE
[BUG] [EXPERIMENTAL] Unable to Place Freeform Blocks on Child Entities

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#878]
Short Description of the issue:
Unable to place free form blocks on child entities.

 Steps to reproduce the issue:
Try to place a free form block on a child entity

 Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050 ti

 Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2130335/output_log.txt)

**Comment by tsunamayo** [comment]
Issue not longer applicable. Cheers
