### ISSUE TITLE
[BUG] [EXPERIMENTAL] Slider Nob moves to the Right

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#879]
### Short Description of the issue:
When using the slider the nob moves to the right instead of up

### Steps to reproduce the issue:
Place the slider

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050 ti

### Additional information:
![20180624175643_1](https://user-images.githubusercontent.com/39653820/41821420-5e081a86-77d8-11e8-9fd2-fc278e58a28d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2131007/output_log.txt)

**Comment by JRL101** [comment]
if you place another slider near it does that move with the knob?

**Comment by TheCuriousSkeleton** [comment]
Unfortunately the new update made it impossible for me to open skywanders so I don’t know.

**Comment by JRL101** [comment]
Have you tried Steam Verification?

**Comment by tsunamayo** [comment]
Hi, I think this issue should have been fixed. Thanks!

**Comment by tsunamayo** [comment]
btw @TheCuriousSkeleton do you still have issue to open the game?

**Comment by JRL101** [comment]
Nope this bugs gone.

**Comment by TheCuriousSkeleton** [comment]
No the game opens fine it’s just a bit slow, could be my computer.
