### ISSUE TITLE
game freezes when starting new game

### ISSUE THREAD

**Issue by Rinzik** [tsunamayo/Skywanderers#881]
### Short Description of the issue:

...
I try to start a new game and then it freezes if I tab out then come back in it gives me a blank screen with a box on the top left-hand corner of my screen
### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: Skywanderers pre-alpha 18w20a
- Graphics Card: 

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2153139/output_log.txt)

![image](https://user-images.githubusercontent.com/40743134/42138215-8b26d114-7d2e-11e8-9f19-faa94a9a236a.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
GFX card below min spec... Thanks
