### ISSUE TITLE
[Removed Feature] [Bug] Flying while not in joystick

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#882]
This used to be a thing awhile back that was removed. Right now when you exit the joystick while flying, the ship quickly slows to a stop. Same thing if you go into the menu while flying. The ship will quickly stop flying just to start when you get out of the menu. Awhile back, you could leave the joystick or go into the menu and the ship will keep flying. Fly straight, but fly it did. I don't know if this was removed by accident or removed for a reason, perhaps it did with the 6dof update, but it is a missing/removed feature so may as well post it.

**Comment by tsunamayo** [comment]
This is still an issue for the menu part... I am on it.

**Comment by tsunamayo** [comment]
Issue is now fixed for the menu, and for the control exit we have autopilot now. Thanks!
