### ISSUE TITLE
[Experimental] [Bug] Cannot link screen to camera [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#883]
### Short Description of the issue:
Screens cannot be linked to cameras.

### Steps to reproduce the issue:
Use the link tool to click-drag from a screen to the camera; the link will remain orange even when the camera is high-lighted.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20180708104829_1](https://user-images.githubusercontent.com/33041786/42421540-c5b145a8-829c-11e8-8fe0-897bfb339e3c.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2173871/output_log.zip)

**Comment by tsunamayo** [comment]
Issue was fixed sometime ago! Thanks
