### ISSUE TITLE
[Bug?] Recording Issues Ever Since Graphics Feature Update

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#884]
### Short Description of the issue:
I've been toying with this for days now, and I honestly didn't even notice it at first, but it turns out all my YouTube video recordings with Skywanderers have been extremely 'choppy' ever since we received the graphics feature update. The one that added all the new graphics menu options like v-sync, chromatic aberration etc.
I don't experience any issues in game, no frame rate drops, with things running at a smooth 120+ fps. However in task manager, looking at my GPU usage, it seems its at 100% or within 4% of that at all times, with all of that usage being consumed by Skywanderers. This leaves little to none in terms of resource availability for anything else, for example OBS, the recording software.
I cant be sure but its possible Skywanderers is using way too much GPU than it needs to be? 
I can only narrow it down to that all recordings after the Graphics Update have been affected.

Steps I have tried to fix: Reinstalling the game, complete clean reinstall, deletion of tsunamayocorp, reinstall of game from steam, update of windows, complete graphics drivers re-installation.

I realise this may not seem like an issue relevant to you, however, I have tried everything I can think of outside of my still fairly new graphics card being broken at the same time as that update.

### Steps to reproduce the issue:
I'm not entirely sure, it seems to just be an issue with recordings not affecting gameplay, but the overall encoded video output file.

### Environment
- Skywanderers version: Experimental
- Graphics Card: Nvidia 980Ti

### Additional information:
I will provide any information I can. Though it seems I can only narrow the issue down to the game sadly :(
Thanks

Edit: Update, I inadvertently moved my windowed version of Skywanderers to a different monitor. and the issue is fixed. So it seems ever since the Graphics update, the game has been having problems with 4k monitors.
I still have this issue, a problem regarding 4k monitors, https://github.com/tsunamayo/Skywanderers/issues/855
and now it seems I can't record the game on my main monitor due to some kind of bug. GPU usage dropped by 80%, recordings come out fine, and all this still remains with the game still on 3840x2160 resolution, however on a 1080p monitor. (Note the issue persists if I have the game set to 1080p resolution and it is played on my 4k monitor. Its not just a problem from having the resolution at a level suited for the monitor.)
I suppose for now I can record videos on one of my other monitors, however it is quite a nuisance considering something that was working months ago with no issues.

I guess my request if anything would be to change back whatever changed in the graphics update those several weeks ago. Things seem to be very broken for anyone using a 4k monitor ever since then.

Thanks.. again :P :)

**Comment by tsunamayo** [comment]
Sorry I didnt catch the issue in time... Are you still encountering this? What are your v-sync setting? If there is no v-sync and if the game is GPU bound (likely at 4k), then it is normal to see your GPU used at 100%, you need to turn off v-sync to run at a lower fps rate but stay at below 100% GPU.
Thanks!
