### ISSUE TITLE
No Freeform brick in menus

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#885]
### Short Description of the issue:
Missing Freeform brick from the menus, is this on purpose or a bug?
...

### Steps to reproduce the issue:
Load game
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX1080

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Womble-TC** [comment]
Unless you mean the free-form block, the update isn't out yet.

**Comment by JRL101** [comment]
Oh, usually he releases the update soon after the videos.  my mistake.
