### ISSUE TITLE
Hotkey Command Block Issue

### ISSUE THREAD

**Issue by ZombiePlaysHD** [tsunamayo/Skywanderers#886]
### Short Description of the issue:
After a few hours of playing the Hotkey Command block stoped working. Dosn`t change after reloading the game save.
...

### Steps to reproduce the issue:
Play for some time and build turrets. After a short amount of time it stoped working for me.
...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Issue should no longer be applicable. Thanks
