### ISSUE TITLE
[Bug] [Experimental] New freeforms placed on blueprint cannot be interacted with

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#887]
### Short Description of the issue:
New freeform blocks placed on ship cannot be interacted with, have an oversized collision box, and show the "f" prompt when mousing over them.

### Steps to reproduce the issue:
Place a new freeform block on the attached blueprint.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20180715184704_1](https://user-images.githubusercontent.com/33041786/42739639-7ffad154-8860-11e8-9677-b2f9054ef782.jpg)

[AAM Riptide Destroyer 3.zip](https://github.com/tsunamayo/Skywanderers/files/2196254/AAM.Riptide.Destroyer.3.zip)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2196252/output_log.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable as old freeform has been replaced with resize tech. Thanks
