### ISSUE TITLE
[BUG] Position of light in certain places

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#888]
### Short Description of the issue:
The light was invisible but I could still hover over it or was submerged halfway into a block.

### Steps to reproduce the issue:
It only happened once and was fixed after I reloaded the game. I thought I would submit the issue as it might be a problem with how the game is loaded.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050 TI

### Additional information:

![20180724203636_1](https://user-images.githubusercontent.com/39653820/43162296-7ba46c68-8f82-11e8-93bf-6b0ee9e3b983.jpg)
![20180724203648_1](https://user-images.githubusercontent.com/39653820/43162309-816e1838-8f82-11e8-822c-3cc8be157392.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2225105/output_log.txt)

**Comment by tsunamayo** [comment]
Issue should have been fixed. Thanks
