### ISSUE TITLE
[BUG] Beam colour of the beam block

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#889]
### Short Description of the issue:
When I was working with the laser beam I had 3 of them and I deleted the one in the middle and the beam colour changed.

### Steps to reproduce the issue:
Put 3 beam blocks on top of each other. Fired it. Deleted the middle one and fired it again.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050 TI

### Additional information:
![20180725182335_1](https://user-images.githubusercontent.com/39653820/43217495-b37cd186-9039-11e8-9f25-77dca49d5f94.jpg)
![20180725182347_1](https://user-images.githubusercontent.com/39653820/43217499-b6e64352-9039-11e8-8d1e-1f486a63a9b6.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2228944/output_log.txt)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks!
