### ISSUE TITLE
[BUG] [18w20a] Stud Bricks Hitbox Issues *REDUNDANT*

### ISSUE THREAD

**Issue by Slyrae** [tsunamayo/Skywanderers#890]
****NOTICE*****

Seeing as studs are going to be removed in the coming update, I believe this issue is now redundant.

******************

### Short Description of the issue:
Stud bricks, for placing bricks, can only be broken from behind once placed. It seems that viewing it from behind is the only way to target the hitbox for the stud bricks.
...

### Steps to reproduce the issue:
Using stable and current "main" version of the game available to non-developers.

Place any block, then place any stud with dimensions of 1x1, 1x2, 1x3, or 1x4 onto it. To see results more directly, place stud so part of it extrudes over the edge of the block. Anomaly does not seem to occur with studs of at least 2 bricks in width, i.e; 2x2 or larger.
...

### Environment
- Skywanderers version: 18w20a
- Graphics Card: (2x SLI) EVGA Nvidia GeForce 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2255297/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed! Thanks
