### ISSUE TITLE
Game has not updated since 18w20a

### ISSUE THREAD

**Issue by SwaggerWagon** [tsunamayo/Skywanderers#893]
### Short Description of the issue:

My game has not updated since version 18w20a, I have verified the integrity of the game cache and no problems appear, I've checked for updates yet they don't seem to be missing, and I've completely reinstalled the game multiple times to see if it will update, yet it does not. simply just booting up the game still runs but I'm stuck playing a really old version.

### Environment
- Skywanderers version: 18w20a
- Graphics Card: Nvidia1070

### Additional information:
Initialize engine version: 2018.2.0b3 (0a6b93065060)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1be1)
    Vendor:   
    VRAM:     8109 MB
    Driver:   22.21.13.8278
Begin MonoManager ReloadAssembly
- Completed reload, in  0.100 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.537162 ms
SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

RESTARTING THE GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading all textures
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

TEXIM LOADED 401
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

DAMAGE DEPTH8
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Fonctionnal Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Hull Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Functional Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Logical Components
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System GFX memory 8109 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System memory 12244 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Suport sparse texture?  True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Level 0 computation finished 106109
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Level 0 computation finished 105864
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

EXITING GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 151c -> priority: 1 
  Thread -> id: 2a6c -> priority: 1 
  Thread -> id: 3afc -> priority: 1 
  Thread -> id: 2880 -> priority: 1

**Comment by TheCuriousSkeleton** [comment]
Don't worry. No one has got an update. Tsunamayo has said in his dev logs that he currently refactoring a lot the game, as well as changing the look the HUD and blocks. But if you want to, you can get into the experimental mode of the game (18w24a). Just follow the instructions here https://www.skywanderersgame.com/forum/viewtopic.php?f=2&t=190

**Comment by tsunamayo** [comment]
new version is now 19w31a.
