### ISSUE TITLE
skywanderers.exe detected as ransomware

### ISSUE THREAD

**Issue by SelectedLime375** [tsunamayo/Skywanderers#894]
### Short Description of the issue:
I use Trend Micro for virus protection and it marked skywanderers.exe as ransomware for "modifying or encrypting files." It's only done this once and I've had Skywanderers installed since March.

I have Skywanderers installed on a separate drive than the rest of my Steam games. Here's a list of the files Tend Micro says it tried to change. They're from another game I have on Steam.

c:\program files (x86)\steam\steamapps\common\staxel\content\staxel\ui\optionscontainer.html
c:\program files (x86)\steam\steamapps\common\staxel\content\staxel\ui\version.html
c:\program files (x86)\steam\steamapps\downloading\405710\content\staxel\ui\optionscontainer.html

### Steps to reproduce the issue:
Not sure. Happened when I got on my laptop this morning. I wasn't trying to run Skywanderers at the time.

### Environment
- Skywanderers version: pre-alpha 18w24a
- Graphics Card: Intel UHD 620, Radeon 530

### Additional information:
I'd been trying to troubleshoot #891 this past week. I had tried updating/reinstalling my graphics cards and changing the Launch Options in Steam to use different versions of DirectX. I had set the Launch Options back to normal before this happened.

**Comment by tsunamayo** [comment]
Thanks for letting me know! So I dont think I can do anything about it, it must some steam internal magic I have no control over... Cheers
