### ISSUE TITLE
[BUG] [EXPERIMENTAL]Can't click off the child entity identity block placement screen

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#895]
Well basically I noticed one of my ships was available to be spawned on a child entity, so after I clicked on it, left, the screen would be un-leavable, and I would have to alt f4

Steps to reproduce the issue:
1)Place child entity block like hinges
2)Place identity block on it
3)Have a ship in the world with its own id block, and it must be saved(Not sure if the ID block can be deleted)
4)Attempt to spawn said non-child entity entity on child entity ID block
5)Exit out of screen (it wont spawn either)
6)Go back to identity block screen
7)Attempt to leave or delete entity, nothing at all will work, and the only thing that will be available to be spawned is the entity you attempted to spawn (Pressing ESC to get to the menu will not work aswell)

Skywanderers version: 
18w24a

**Comment by tsunamayo** [comment]
Issue is no longer applicable. Thanks
