### ISSUE TITLE
[BUG][EXPERIMENTAL] F11 Problems

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#896]
### Short Description of the issue:
Problems with the Index after using F11

### Steps to reproduce the issue:
When I was using F11 I went into the HUD and all the blocks where white

### Environment
- Skywanderers version:18w24a 
- Graphics Card: GTX 1050 Ti

### Additional information:

![20180910203425_1](https://user-images.githubusercontent.com/39653820/45320219-f439eb80-b539-11e8-9fca-3bab6ccde2c9.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2368159/output_log.txt)

**Comment by tsunamayo** [comment]
This issue is no longer applicable as of latest version. Thanks!
