### ISSUE TITLE
Game Crashes On Launch

### ISSUE THREAD

**Issue by NathanInThailand** [tsunamayo/Skywanderers#898]
### Short Description of the issue:
Game crashes on launch. Drivers are updated, game has been reinstalled.
...

### Steps to reproduce the issue:
Launch the game.
...

### Environment
- Skywanderers version: 2018.2.0b3
- Graphics Card: GeForce 940mx

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2374052/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by talrey** [comment]
Mystery seemingly solved via Discord, though the issue is still present.

He was able to load the game on another PC (remote desktop server with a Radeon R7 200) so we believe it 's his laptop's graphics card that's the issue.

**Comment by NathanInThailand** [comment]
Telling my laptop to run the game with it's integrated card led to the same result.

**Comment by tsunamayo** [comment]
Hi, sorry to being super late on this, are you still having issues as of latest version 19w31a? Thanks!
