### ISSUE TITLE
[Bug] [Experimental] Mass not correctly accounted for in flight model

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#899]
### Short Description of the issue:
It appears that the mass of child entities is not getting correctly "rolled-up" to the flight model - a ship with no child entities is slower than a ship where most of the mass is build on children, even when thier mass is the same.
...

### Steps to reproduce the issue:
Build 2 ships of the same mass, but one with the majority of that mass on a child. Alternatively use the ships in the zip. Mass is within 2kg. "mass test 1" reaches 377 m/s top speed, but "mass test 2" gets to 400.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2377022/output_log.txt)

[Mass test ships.zip](https://github.com/tsunamayo/Skywanderers/files/2377016/Mass.test.ships.zip)

...

### Environment
- Skywanderers version: 18W24a
- Graphics Card: GTX 1060

### Additional information:

Screenshot
![skywanderers 12_09_2018 22_54_22](https://user-images.githubusercontent.com/40872394/45455704-e8882980-b6df-11e8-85a8-17f6ada519a2.png)

**Comment by tsunamayo** [comment]
This issue should have been fixed some time ago. Thanks a lot!
