### ISSUE TITLE
[BUG] Hyperspace wobble increases endlessly 

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Skywanderers#901]
### Short Description of the issue:
Hyperspace wobble increases endlessly, even at constant or low speeds and even after exiting Hyperspace and slowing down or stopp
...

### Steps to reproduce the issue:
every time me or my friend use the hyperspace
it lasts ca. 10-20s depending on Hyperspeed and the holy ship wents in a Flummi
Seems that the intended wobbling gets out of control.
(Sry for bad language, Googeltranslater tried it`s best^^)
...

### Environment
- Skywanderers version: 18w20a and also Experimental
- Graphics Card: Nvidia 750M 
Nvidia 1050 (Mobile)<- my friend

### Additional information:

it goes the same in Experimental

The issue ends if I leave the seat for a short moment 
--> We had to take a Hyperbreak every 10-15s to dont crash the game
_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/43222403/45457911-74568180-b6f1-11e8-9d12-754cb33d3ce6.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2377155/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue should be fixed in 19w25a. Cheers
