### ISSUE TITLE
[BUG] [EXPERIMENTAL] Slider Nob moves to the Right - 2

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Skywanderers#904]
### Short Description of the issue:
I found a bug awhile ago that When using the slider the nob moves to the right instead of up, but this time its also moves to the left in one direction and moves up normally in another, as well as moving away in another.

### Steps to reproduce the issue:
Place them like in the photo.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050 Ti

### Additional information:

![20180918213648_1](https://user-images.githubusercontent.com/39653820/45715192-802bc300-bb8b-11e8-9eba-9e7c8d626a7d.jpg)

![20180918213716_1](https://user-images.githubusercontent.com/39653820/45715196-8326b380-bb8b-11e8-93cc-b95ee07a566f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2394394/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I think this issue should now be fixed. Thanks!
