### ISSUE TITLE
Engine texture incorrect in inventory display

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#905]
The texture for the Engine Unit is showing a plain texture where it should show that circle bit

### Environment
- Skywanderers version: 18w24a

![20181003001530_1](https://user-images.githubusercontent.com/32974671/46391355-260a2200-c6a2-11e8-8676-85a1e0006781.jpg)

**Comment by tsunamayo** [comment]
Issuue was fixed sometime ago. Cheers!
