### ISSUE TITLE
Hotbar unsynced with number keys

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#907]
### Short Description of the issue:
When you press a number key, it selects the wrong hotbar slot
...

### Steps to reproduce the issue:
press number key
...

### Environment
- Skywanderers version: Private version
- Graphics Card: gtx 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Xerma** [comment]
Pressing 9 for me cleared the hotbar/switched to a new hotbar but I can't figure how to switch back

**Comment by tsunamayo** [comment]
Okay fixed, I dont how to count =(
