### ISSUE TITLE
pressing esc while in the codex menu will not close the codex menu, and opens the pause menu behind the codex

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#908]
### Short Description of the issue:
when you open the codex, then press escape it does not close the codex menu, and opens the pause menu behind the codex.
...

### Steps to reproduce the issue:
press number key press Tab, then press Esc
...

### Environment
- Skywanderers version: Private version
- Graphics Card: gtx 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay this one was fixed. Thanks!
