### ISSUE TITLE
UI doesn't display numbers for build selection size (large output log)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#909]
### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

![20181003003748_1](https://user-images.githubusercontent.com/32974671/46391885-b6496680-c6a4-11e8-9d46-3dd84bbbcda0.jpg)
NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by Xerma** [comment]
I'm pretty sure that UILinkSound.Update is a reference to a sound not playing when placing blocks

**Comment by tsunamayo** [comment]
This issue should be fixed as of today. Cheers
