### ISSUE TITLE
[Suggestion] Keep old rotation for some things

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#911]
I personally think it better to keep the way we rotated things via holding and moving for rotation rather than pressing buttons for things that don't interact like freeform such as chairs and mirror blocks

**Comment by tsunamayo** [comment]
That would be confusing no? You think you can get used to the new way? It might be a bit slower but as you get a preview for bricks placement it is actually more friendly I think.

**Comment by Xerma** [comment]
Having 2 methods of rotation does seem confusing. The old way you created just felt more fluid and faster. Might need to play around more with it to see how it feels then

**Comment by Breezebuilder** [comment]
Please reconsider this change.  The old method of dragging to rotate blocks was extremely intuitive and one of the best building features of the game.  Removing this would be a huge shame.

**Comment by LeMinaw** [comment]
My grain of salt :
I liked the old way too. Having both modes at the same time looks very confusing but perhaps adding a setting to select one single mode would be a solution?

**Comment by tsunamayo** [comment]
So @Xerma did you get used to the new way after this time? I think it was an hard call but I think that resizing with hold the mouse is best. Cheers
