### ISSUE TITLE
Scrolling in the hotbar odd interaction

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#912]
Scrolling in the hotbar with the link tool in it seems to mess up the display for the hotbar.
Say my active slot is 1 and link tool is in 2. If I scroll towards 3, anything past the link tool doesn't show as active. If I scroll backwards to 9 it works fine until I scroll past the link tool.
### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

NullReferenceException: Object reference not set to an instance of an object
  at UILinkOver.Update () [0x00000] in <filename unknown>:0

**Comment by Xerma** [comment]
Scrolling from 1 to the link tool and backwards at all resets the active slot to 1

**Comment by Xerma** [comment]
Removing the link tool from the hotbar fixes the issue

**Comment by tsunamayo** [comment]
Hi, this will be fixed in next build. Thanks!
