### ISSUE TITLE
Can't paint hull

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#914]
### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

![20181003013241_1](https://user-images.githubusercontent.com/32974671/46393887-ab92cf80-c6ac-11e8-9b97-f852c7e4e410.jpg)
![20181003013249_1](https://user-images.githubusercontent.com/32974671/46393889-acc3fc80-c6ac-11e8-885b-935ba34c298b.jpg)

Couldn't find an issue in the log file in regards to this, fairly large file as well

**Comment by tsunamayo** [comment]
Are you painting on a torus on the ground? Thanks

**Comment by Xerma** [comment]
Ah yes my bad, that is one of the starter buildings on the torus. Will need to update those along with the tutorial itself

**Comment by tsunamayo** [comment]
Okay I fixed an issue with paint on child entity, but as I will change the way torus works I wont fix this one :p
