### ISSUE TITLE
Odd visual bug on the hull blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#916]
I'm seeing this strange line across these I have just placed
### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

![20181003014729_1](https://user-images.githubusercontent.com/32974671/46394352-7edfb780-c6ae-11e8-8779-54295f865124.jpg)
![20181003014741_1](https://user-images.githubusercontent.com/32974671/46394354-80a97b00-c6ae-11e8-88d9-234c0cadda67.jpg)
![20181003014748_1](https://user-images.githubusercontent.com/32974671/46394355-81daa800-c6ae-11e8-95bb-83e7c7aba14d.jpg)

It only displays the line while hovering over the placed blocks

**Comment by tsunamayo** [comment]
Hi, it is a bug linked to the way torus work atm, but as it is gonna change it will be fixed over time. Thanks!
