### ISSUE TITLE
Transparency issues with blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#917]
Some blocks are making blocks they touch become see through

In these images it occurs with trans hull penta and the armature
### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

![20181003015203_1](https://user-images.githubusercontent.com/32974671/46394887-23162e00-c6b0-11e8-9212-094e9d5f9988.jpg)
![20181003015407_1](https://user-images.githubusercontent.com/32974671/46394892-24dff180-c6b0-11e8-9962-b9e3cd8bfc70.jpg)
![20181003015424_1](https://user-images.githubusercontent.com/32974671/46394897-27424b80-c6b0-11e8-9ad6-d29b7ae6519d.jpg)

**Comment by tsunamayo** [comment]
This issue can no longer happens since the rescale refactor. Thanks!
