### ISSUE TITLE
SUGGESTION: dynamic color system for lights and monitors

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Skywanderers#92]
A logic block similar in nature to the mix block but for color. So when it receives a signal of 0 it outputs color a, and 1 is color b. The output could be sent through either a special quad or a normal quad if you want to do it that way, but it can be linked to things like lights and monitors. This gives us a cool way to do lighting switches and things like "red alert". For example, you could rig up a color palette of yellow and red. When you open your interior airlock door, the lights and screen inside would be yellow. When you close the inner door, the lights turn red as does the monitor. You could also more simply control lighting this say by setting up a black (off) and white (on).
Alternatively you could make the mechanism work just like a mix command, with a special color selection in the middle. Then you could have the range be based off the RGB code. So if I wanted to have a dimmer switch in my captains quarters for example, i would set Grey in the color selection and then a would be #000000 while b would be #FFFFFF. with a slider I could have a dimmer switch and an off/on (black or white, with ranges changing the values of each 0-255 range evenly. (so you could have anything from black to ultra bright blue if you set the middle color (0.5) to blue.

One other thought is the same color tricks could be used for thrusters.

**Comment by tsunamayo** [comment]
Although I very like the idea and the possibility offered by it, it is too far from current color implementation philosophy to be feasible. But when I do the light refactoring it will be possible to toggle  lights ON / OFF (and maybe put a value in between, not sure yet), so red alert would be possible.

I was also thinking of a native red alert feature for gameplay purpose: when the ship is in danger, like overheating, damage critical, power failure/overload ect, to basically override all light of a ship to get the player in the mood.
