### ISSUE TITLE
1x2 slope remnant in new codex

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#921]
Might have missed this block when removing things from the codex

### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970

![20181003023605_1](https://user-images.githubusercontent.com/32974671/46396570-5d35fe80-c6b5-11e8-9d83-a8df32b9e35a.jpg)

**Comment by tsunamayo** [comment]
Good spot indeed! It is fixed, cheers
