### ISSUE TITLE
Hollow Pipe dragging issue

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#922]
Dragging the hollow pipe like the normal pipe instead moves it along the wrong axis and releasing places as seen here

### Environment
- Skywanderers version: 18w24a
- Graphics Card: gtx970
![20181003024331_1](https://user-images.githubusercontent.com/32974671/46396980-8dca6800-c6b6-11e8-9504-b55cf1d6bcf0.jpg)

**Comment by tsunamayo** [comment]
Okay this one will be fixed in next update! Cheers
