### ISSUE TITLE
Endless UILinkSound.Update entries in log file

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#923]
### Short Description of the issue:
Log file becomes flooded with entries of 

```
NullReferenceException: Object reference not set to an instance of an object
  at UILinkSound.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

as soon as a world is loaded, which continues until the world is closed, causing the log file to become excessive.
Log file was >800MB after 30 minutes.

A fresh `output_log.txt` from 30 seconds of playtime can be found here:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2441222/output_log.txt)

### Steps to reproduce the issue:

Occurs on all existing and newly-created saves.

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: NVIDIA GTX 1050

**Comment by tsunamayo** [comment]
Okay I fixed the issue, it was something only in the build and not in the editor. Will push a new build asap. Cheers
