### ISSUE TITLE
[BUG] Pressing the "1" key selects the second item in your toolbar, not the first

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#926]
Previously you could press a number key corresponding to the toolbar item you wanted to select, for example pressing the 1 key would select the first item> Now, pressing a key selects the next toolbar item along, for example 1 key = position 2, 4 key = position 5.

Pressing the "9" key selects the next toolbar

### Steps to reproduce the issue:

Press any number key and note the tool bar item that is selected

### Environment
-Skywanderers version: 18w24a
-Graphics Card: GTX 1050M

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2441883/output_log.zip)

**Comment by ProPeach** [comment]
Looks like this is similar to Xermas #912

**Comment by Breezebuilder** [comment]
Identical to #907, already closed
