### ISSUE TITLE
[BUG] Pressing the "9" key 3 times removes your ability to select different items on your toolbar

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#927]
Linked to issue #926 , pressing the 9 key will switch your toolbar instead of selecting the 9th item on your toolbar. If you do this 3 times, which would normally cycle from the 4th toolbar to the first, your toolbar instead locks up making you unable to change the selected tool through the number keys or scrolling like usual.
...

### Steps to reproduce the issue:
Press the 9 key 3 times, ideally with items in each of the 4 toolbars to make it easier to see them scrolling, then try to switch tools with the number keys or mouse scroll wheel. 

...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTW 1050M

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2441913/output_log.zip)

**Comment by tsunamayo** [comment]
Issue is fixed. Cheers!
