### ISSUE TITLE
[BUG] Minor codex issues

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#930]
### Short Description of the issues:

1. After clicking the **x** icon to dismiss the Codex, upon opening the Codex again, the **x** is not displayed until the button is moused over again.

1. Codex menu can be opened at any time, including while in pause menu and others.

1. Codex menu remains when pause menu is opened.

1. Movement keys still work while codex is open.  Especially a problem when typing into the search bar.

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: NVIDIA GTX 1050

**Comment by tsunamayo** [comment]
Issue should be fixed now. Thanks!
