### ISSUE TITLE
[BUG] Minor hotbar issues

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#931]
### Short Description of the issues:

1. Hotbar selection indicator and arrows are no longer displayed.

1. Hotbar is not hidden by the F2 key.

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: NVIDIA GTX 1050

**Comment by tsunamayo** [comment]
Hi, I have added the functionality back. Thanks!
