### ISSUE TITLE
[BUG] Minor pause menu issues

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#932]
### Short Description of the issues:

1. Cursor remains on screen after pause menu is closed.

1. If player customization menu is dismissed with ESC instead of the 'Done' button, it will show on top of the options menu the next time it is opened.

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: NVIDIA GTX 1050

**Comment by tsunamayo** [comment]
All issues should be fixed. Thanks!
