### ISSUE TITLE
[SUGGESTION] UI improvements

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#933]
Before editing
![image](https://user-images.githubusercontent.com/31857052/46450961-f1729500-c78b-11e8-901a-2b9c25ede263.png)

After editing
![image](https://user-images.githubusercontent.com/31857052/46450753-d94e4600-c78a-11e8-9809-50497633581b.png)

In the image above I've made some changes working off the feedback of those who currently have access to the build.  

The most noticeable change is the additional bar above the filters - this would display a title/overview for the filter you're hovering over with your mouse, as the icons are not very intuitive, but could stay as compact as they are if this was added.

Another change to the interaction of the filters would be that clicking the "all" filter would also reset any currently applied filters and display everything.

As far as aesthetic changes go, some of the colours have been altered to make the general appearance of the ui more consistent, with colour consistency throughout (I had to diverge and use a different colour for the block backgrounds as it was far too bright otherwise.) 

The corners that were on each block "display" have been removed from the codex, but these would appear when you hover over a block to emphasise which block you're looking at whilst glancing between the block information panel on the right and the main codex page..

A small nitpick improvement would be blocks that create child entities; rails, rotators and rotors and so on all only display the base portion of the block and are hard to distinguish apart from one another. Being able to see the full block would make this much clearer.

If the UI was altered to appear like this, it would have a much cleaner appearance, with a sleek look to compliment a space-age game.

**Comment by schlid** [comment]
If you're on board with these improvements I'd be happy to transfer them over to the image assets to save you some time btw.

**Comment by tsunamayo** [comment]
Hi, actually the recent Codex UI looks a lot closer to what you had suggested. Thanks!
