### ISSUE TITLE
Shadows are messed up with the new tech.

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#934]
### Short Description of the issue:
When using the new drag tech some shadows are messed up.
...

### Steps to reproduce the issue:
Use grills or armatures with the new tech.
...

### Environment
- Skywanderers version: Private
- Graphics Card: GTX 1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/46494977-1ad30580-c80c-11e8-82f7-fb26751bae29.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay this should be fixed! Thanks
