### ISSUE TITLE
[BUG] New Invisible Freeform and Breaking Wrong Block

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#935]
Was test building a ship and putting down a freeform corner. Instead of placing the corner, it placed an invisible version of it. When I try to break the invisible block, the block painted orange disappears instead. 

Blueprint and output_log: 
[Invisble Freeform.zip](https://github.com/tsunamayo/Skywanderers/files/2447801/Invisble.Freeform.zip)
![711980_20181004140653_1](https://user-images.githubusercontent.com/26584892/46497425-1d1f6a80-c7e0-11e8-90e2-7750d8af724e.png)

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: GTX 1060 6gb

**Comment by tsunamayo** [comment]
It is working well on my side, I see the block. Is it still there after a reload? I will push a new build soon, if you can retry with it. Cheers

**Comment by tsunamayo** [comment]
I think this issue should be fixed in recent version - tell me if it is not the case! Cheers
