### ISSUE TITLE
Can't walk through hollow pipes. 

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#936]
### Short Description of the issue:
The gap in the inside of the hollow pipe cannot be walked through. It looks like it should be possible and you can walk through the gap of the large cone.
...

### Steps to reproduce the issue:
Make a large hollow pipe, walk through it
...

### Environment
- Skywanderers version: New private
- Graphics Card: GTX 1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/46571355-72d44e00-c96b-11e8-8c29-dd2009dd76b0.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Yes this is a known issue due to my player collision algo, I plan to improve that. Thanks

**Comment by tsunamayo** [comment]
Deprecated issue. Thanks
