### ISSUE TITLE
Can't use the drag tech on some more shapes

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#937]
### Short Description of the issue:
The new drag tech doesn't work on the following shapes.
small corner brick
cone hollow
pipe light
engine unit round
***engine unit (The cube one seems to have the texture drag but not the block)***
Ladder(This one is rather unlikely but just felt like including it)
Light rod
Armour plate
Plates A-D
wall slabs
studs 1 to 2 brick
...

### Steps to reproduce the issue:
Place any of these and try to drag them
...

### Environment
- Skywanderers version: New Private
- Graphics Card: GTX 1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/46571409-77e5cd00-c96c-11e8-94e2-2ed1860d346e.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay most of them are fixed, for those which are not it is because they are dependent on other upcoming changes. Cheers
