### ISSUE TITLE
Can't place "stairs scaffolding"

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#938]
### Short Description of the issue:
Can't place "stairs scaffolding" block
...

### Steps to reproduce the issue:
Try to place it
...

### Environment
- Skywanderers version: New private
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
It is now fixed. Thanks!
