### ISSUE TITLE
Corner Lights and Hinges place in the centre of the block, instead of the edge.

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#939]
When placing a corner light or a hinge, they will appear to be in the centre of the block instead of the edge/corner. 
![image](https://user-images.githubusercontent.com/29961381/46571732-2dffe580-c972-11e8-9e7e-728fb3b53a7c.png)

(Version: revenge of the clip)

**Comment by Womble-TC** [comment]
(plz fix soon, I need to make a ramp) 👍

**Comment by tsunamayo** [comment]
Sorry ;-), issue is fixed and will be in next update. Cheers
