### ISSUE TITLE
[Fix/Suggestion] Resize the "Diagonal Brick" to fit on a 1m block

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#94]
![skywanderers brick size issue](https://user-images.githubusercontent.com/27857711/30119656-5dbab2d6-931e-11e7-9ece-cd4aca181966.png)

From this image you can see that the Diagonal Brick piece is 1.125m x 1.125m. I think the brick would be much more useful it it were 1m x 1m, so fitted in line with the standard block size.

Thanks for reading

**Comment by tsunamayo** [comment]
Yes indeed. It was made this size so the inner diagonal is indeed 1m, and you can stack them on without needed a small wedge brick. I will check with other builder what is their take on that, I could change it quite easily.

**Comment by tsunamayo** [comment]
Okay after having talk with a few builder that used it we agree this is better so I did the change. Thanks!
