### ISSUE TITLE
Pressing tab whilst in control of a vehicle opens the codex

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#940]
### Short Description of the issue:
When flying a ship, press tab (note when the bug occured I was not in a pilot seat, just going directly into the yoke.)

### Steps to reproduce the issue:
Enter ship yoke, press tab.
...

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: gtx 970

### Additional information:

![image](https://user-images.githubusercontent.com/31857052/46572397-f21e4d80-c97c-11e8-84d7-8b799b02b42b.png)

**Comment by tsunamayo** [comment]
Thanks, it is now fixed. Cheers
