### ISSUE TITLE
Minor UI bugs

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#941]
### Short Description of the issue:
1. Pressing ESC while the inventory is open doesn't do anything but should close the inventory and open the ESC menu.

2. Can't shift + scroll while the inventory is open

### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: gtx970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2453233/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this will be fixed in next update. Now in the codex you can see all 3 rows, so thats more convenient to use. Cheers!
