### ISSUE TITLE
Suggestion: Keep some legacy shapes for their other uses

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#942]
### Short Description of the suggestion:
I know you are trying to tidy the codex up and I know that the new stretchy slope tech removes the need for some of these slope blocks as slopes but some of these shapes can be used for other purposes. I would suggest perhaps putting them in some sort of advanced shapes tab or something that way they don't clutter the codex but can still be used. I have included some screenshots of situations where the ability to use these shapes like this is useful. Also, a lot of what is shown here could be achieved with the new brick system but that would mean a lot of bricks so I think some of these shapes being added back could help reduce the number of bricks used. Finally, there is a brick with the same shape as the block with one sloped edge but no block seems like an odd choice there.

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/46575030-7edd0180-c9a5-11e8-9a49-7600ef7b4c5b.png)
![image](https://user-images.githubusercontent.com/43644633/46575034-843a4c00-c9a5-11e8-9688-9cdc2d5968e0.png)
![image](https://user-images.githubusercontent.com/43644633/46575036-8ac8c380-c9a5-11e8-9416-ccf6d921d256.png)
![image](https://user-images.githubusercontent.com/43644633/46575039-9ddb9380-c9a5-11e8-8ea0-137d51fb1cac.png)
![image](https://user-images.githubusercontent.com/43644633/46575050-dd09e480-c9a5-11e8-98a5-27e8a42840ee.png)
While you can do something similar to this one you can't quite get that angle with the new tech. Not the biggest one of these issues but still a loss of creative freedom none the less.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Breezebuilder** [comment]
Suggestion: retitle this suggestion to contain the contents of this suggestion.

**Comment by Garrett-C** [comment]
Oops sorry Yeah I could have sworn I did. My bad.

**Comment by Garrett-C** [comment]
Looks like he has a plan for this so we will have to see. Hopefully it’s just as fast in the long run.

**Comment by tsunamayo** [comment]
Yes the prefab tool will make these possible without taking too much blockids and cluttering the codex. I keep you posted on that!
