### ISSUE TITLE
Tooltips do not reflect keybinds

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#949]
### Short Description of the issue:

Tooltips that are shown after hovering over an interactable block do not reflect the user's keybinds.
With the 'Activate / Enter' action mapped to **[f]** (the default keybind), and Rotate Left and Rotate Right mapped to **[z]** and **[x]** respectively, the tooltips still refer to **[e]** and **[q]** / **[e]**, despite the keys functioning correctly according to the mapping.
Additionally, on all blocks with the simple 'activate' command, the tooltip contains two instances of **[e]**.

![tooltips](https://user-images.githubusercontent.com/28330882/46579787-0d17bd00-ca64-11e8-8829-cc0ab4bee802.png)

### Environment
- Skywanderers version: revengeoftheclip v2

**Comment by tsunamayo** [comment]
This issue will be fixed in next update. Thanks!
