### ISSUE TITLE
Logic for control of lighting

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#95]
Allow logic for control of lighting - if it's not too complicated then instead of having the binary states of 1 and 0 for on and off, through use of a slider, constant or mix command the values in between could be selected for a specific brightness.

**Comment by tsunamayo** [comment]
Light will be toggable after the light refactoring planned. Whether they will adjust between 0 and 1 is unknown yet, I will def give it a shot we will see how it turns out.

**Comment by tsunamayo** [comment]
The Light update is live, now you can toggle light ;-) Cheers
