### ISSUE TITLE
Void reactor texture is messed up

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#950]
### Short Description of the issue:
The void reactor block's texture needs some realignment
### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: gtx970

### Additional information:
![20181008111901_1](https://user-images.githubusercontent.com/32974671/46621235-92df4b00-caec-11e8-8ef5-11e0228e1a64.jpg)

**Comment by tsunamayo** [comment]
Okay this is now fixed. Thanks!
