### ISSUE TITLE
Unable to interact after trying to place a core on a child entity

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#953]
### Short Description of the issue:
I placed a ship core on a child entity in order to test some stuff, it didn't place as expected but afterwards, I was unable to place blocks and unable to interact with the ID block.
...

### Steps to reproduce the issue:
Place a ship core on a child entity.
Try to place a block somewhere else after.
...

### Environment
- Skywanderers version: Revengeoftheclip
- Graphics Card: GTX 1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2466594/output_log.txt)
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Placing a core on a child entity is now prohibited. Thanks!
