### ISSUE TITLE
Blueprint blocks do not load ships with the new file extension (.mps)

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#954]
Blueprint blocks do not load ships with the new file extension (.mps). When saving a ship in the latest build (revengeoftheclip), the '.mps' file does not appear in the blueprint list, therefore, cannot be spawned. However, '.swbp' files still work fine.

**Comment by tsunamayo** [comment]
That issue was fix some time ago. Thanks Womble!
