### ISSUE TITLE
[Bug] The tutorial structure is loading in space

### ISSUE THREAD

**Issue by chunkblaster** [tsunamayo/Skywanderers#956]
### Short Description of the issue:
upon loading into a new world on the experimental branch's newest update, I found the tutorial structure floating in space
...

### Steps to reproduce the issue:
I simply made a new world (which landed me in void space with nothing around) & teleported to "LongrangeFighter01_T1" and upon getting out of the vehicle I found it & most of the other stock vehicles floating in space
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GeForce GTX660

### Additional information:
![20181025214710_1](https://user-images.githubusercontent.com/33188327/47542119-91aa6e00-d8a1-11e8-8626-3bb462016777.jpg)
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2517489/output_log.txt)

**Comment by tsunamayo** [comment]
This issue is deprecated. Thanks!
