### ISSUE TITLE
[Bug] Unable to load profile save

### ISSUE THREAD

**Issue by chunkblaster** [tsunamayo/Skywanderers#957]
### Short Description of the issue:
My world save that was created several versions ago no longer will load, I am perpetually trapped on the load screen
...

### Steps to reproduce the issue:
Unknown. It may be an issue on my end for all I know, but others have stated that their world files load just fine on the new update
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GeForce GTX660

### Additional information:
Here's the save file in case it's of any use
[Chunkblaster.zip](https://github.com/tsunamayo/Skywanderers/files/2517508/Chunkblaster.zip)

_(Screenshots, Videos, Error logs, Related issues)_
Loading *any* world seems pretty buggy for me, including new ones. sometimes they won't load at all
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2517510/output_log.txt)

**Comment by chunkblaster** [comment]
Not that it changes much but I have tried reinstalling a couple times now, as well as verifying the integrity of the game cache with no success in fixing it unfortunately.

**Comment by tsunamayo** [comment]
Okay this will be fixed in upcoming patch today. Thanks!
