### ISSUE TITLE
[Bug] - Codex page not displaying blocks correctly

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#958]
### Short Description of the issue:

... when I 1st open the block codex I can see all the blocks, however if I move my cursor over the category tabs at the top the game auto scrolls through the categories even if I don't select/click them. after this happens, even if i click the all tab the codex will only display the colour/link and repair tool. 

### Steps to reproduce the issue:

... happens every time I reload the game and try it.

### Environment
- Skywanderers version: legacy 18w24a
- Graphics Card:dual gtx 1080's

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
That was a bug, also you dont need to click on the tab just hover on them. Thanks!
