### ISSUE TITLE
[BUG]Star Lighting changes colour upon re-load.

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#96]
Skybox lighting colour changes do default "white" once reloading the game, here is an example: 

BEFORE:
![image](https://user-images.githubusercontent.com/29961381/30286194-a120dac0-9718-11e7-80cf-3e9f8ebc8e8b.png)

AFTER:
![image](https://user-images.githubusercontent.com/29961381/30286213-b68bf9c6-9718-11e7-86ee-e848a1a9cc66.png)
 
I have tried this in multiple locations, and it still managed to persist.

**Comment by Womble-TC** [comment]
Forgot to mention, this is how the star looks: 
![image](https://user-images.githubusercontent.com/29961381/30286261-eb7fe890-9718-11e7-8743-8f683cc944d9.png)

**Comment by tsunamayo** [comment]
Thanks. I fixed it, but now all light color are white, cause it really looks odd even with a slight redish tint. Btw your ship/ station looks amazing ;-)
