### ISSUE TITLE
[UI-bug] - Interaction wheel stays on screen if not filled

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#960]
### Short Description of the issue:

... When interacting with a object like a seat/control stick, the interaction wheel will popup, however if I stop interacting before the wheel fills it remains on screen until it is filled

### Steps to reproduce the issue:

... happens every time I stop using a object with the f key and stop half way.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
This issue seems to be fixed. Thanks!
