### ISSUE TITLE
[Save-Bug] - Torus vanishes after reloading world

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#961]
### Short Description of the issue:

... Bit of a weird bug here, when I 1st load the game I start as normal in the tut zone, however if I leave the game then reload the world later I load in, in space with anything ive built around me however the torus and all the tut buildings/ships are gone. Also if i press f7 to select spawn point nothing is listed there. i will include a copy of the save folder below.
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/2519383/Save_Data.zip)

### Steps to reproduce the issue:

... can be repeated everytime I start a new world, I remove all the files in \AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data. start a new world and do something in the world, save -> quit ->reload and boom torus gone and im in deep space.

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
We have a new torus workflow, this issue should be deprecated. Thanks
