### ISSUE TITLE
Character Model Bug

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#963]
https://media.giphy.com/media/fBM6axBOqrOil3yphS/giphy.gif

I have not made a full list of all the bugged hairstyles yet, but this should get you started

**Comment by Dwarf-LordPangolin** [comment]
Confirmed; this is also showing up for me.

![20181027163624_1](https://user-images.githubusercontent.com/33041786/47609578-38f4e580-da07-11e8-838b-66cbdf8f8f6b.jpg)

**Comment by tsunamayo** [comment]
This is no longer applicable. Thanks!
