### ISSUE TITLE
(Multiplayer issue) Host cannot interact with anything after connected players interact with world

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#964]
### Short Description of the issue:
When a connected player starts building/destroying, the host will lose the ability to interact with anything in the world. However, the connected players will still see the what the host is placing/destroying/interacting with.
...

### Steps to reproduce the issue:
Host a game, then get one of the connected players to place/destroy blocks.
...

### Environment
- Skywanderers version: "Legacy"
- Graphics Card: GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Output log of host: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2521001/output_log.txt)

**Comment by ProPeach** [comment]
Here's the output.log file from the connected player's perspective:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2521012/output_log.txt)

**Comment by InCrIpTiOn** [comment]
lol only 970 noob

**Comment by tsunamayo** [comment]
Okay this will be fixed on next update. Cheers
I only have a 960 btw hehe ^^
