### ISSUE TITLE
Toolbar Number Select Bug

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#965]
### Short Description of the issue:
When using the toolbar, if it is empty and place a new block into a slot, you can use the number key as normal to select that block. If you later place a different block (replacing one in the toolbar) suddenly hitting numbers just replaces the toolbar slot for that number with a random block.

### Steps to reproduce the issue:
- Load the game as normal
- Open the block selector and fill toolbar slots with blocks
- Go to build mode
- Reopen the block selector
- Replace one of the blocks you already placed in the toolbar with a different block while holding shift
- Go back to build mode
- Hit the number as if you want to select a block from the toolbar
- The slot for the number you pressed replaces the block in the toolbar at that number with a random block (for me the 1/2 brick, I also had this randomly load a color)

...

### Environment
- Skywanderers version: legacy 18w24a
- Graphics Card: GeForce GTX 960

### Additional information:
![20181026200910_1](https://user-images.githubusercontent.com/33043997/47597403-5f117b80-d95c-11e8-9e5b-b45dfa243cc6.jpg)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2521279/output_log.txt)

**Comment by tsunamayo** [comment]
Weird, I am not reproducing that at all... You are sure about your test case? Thanks

**Comment by Rizzo911** [comment]
So it seems that shift dragging has something to do with this. In the old system you could swap which toolbar was up WHILE still being able to select a block. So my fingers are in the habit of holding shift, using the scroll wheel on the mouse a lot still trying to swap the toolbar to another and dragging blocks onto the toolbar. This seems to start the issue. I was able to reproduce it far more often this way.

**Comment by JRL101** [comment]
I THINK i might have figured out how to reproduce this;

Go into TAB
Hit escape
Hit escape again
_(if block menu is gone bug is present)_
SHIFT+Scroll bar change or slot selection is disabled. (or both)

My fix so far, works some of the time.

Open TAB
Hit ESC
then CLICK the "X" in the top right
(when bug is still present a restart will fix or try again)
Success for this fix is 1 in 3 of tries, so not sure what else is interacting with the bug yet.
I will attempt to find an alternate bypass.

**Comment by tsunamayo** [comment]
Okay thanks to your help guys I was able to solve this! Better late than never. Fix will be in 19w32a! Cheers
