### ISSUE TITLE
Can't delete triangular wedge

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#966]
### Short Description of the issue:
I am unable to delete one of the legacy blocks (the smaller part of the 2 block triangular wedge). As you can see from the picture, I've tried deleting everything around it and can't seem to select the block to 
delete it. It seems to be invisible or maybe has no collision box left to select.

### Steps to reproduce the issue:
- Load a build with the legacy 2 block triangles
- Find the small wedge portion of the duo
- Attempt to delete the smaller wedge
- Note that you can't select the block or delete it.

### Environment
- Skywanderers version: legacy 18w24a
- Graphics Card: GeForce GTX 960

### Additional information:

![20181026202422_1](https://user-images.githubusercontent.com/33043997/47597537-8ae13100-d95d-11e8-924d-5541efe67507.jpg)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2521293/output_log.txt)

**Comment by tsunamayo** [comment]
Okay, the bad news is I cant fix the bug on Legacy, as it is now frozen. The good news is that on the next update this block will basically disappear, so you wont have any issue. Thanks
