### ISSUE TITLE
Can't load/create worlds

### ISSUE THREAD

**Issue by InCrIpTiOn** [tsunamayo/Skywanderers#967]
### Short Description of the issue:

Can't load into any worlds or create any new ones. Game stays on loading screen indefinitely for as long as I left it (20 minutes). Will wait longer to see if anything else happens

### Steps to reproduce the issue:

Uninstalled, Reinstalled the game. 

### Environment
- Skywanderers version:  18w20a
- Graphics Card: gtx 1050ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2521746/output_log.txt)

**Comment by tsunamayo** [comment]
Okay weird, do you confirm it was working fine before? No need to wait too much, it wont work at this point. Can you zip your save folder and send it to me?
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers
Thanks!

**Comment by InCrIpTiOn** [comment]
Yes, will do once I get onto my PC tomorrow :)

**Comment by tsunamayo** [comment]
I hope you are doing fine on recent build! If not could you tell me? Thanks
