### ISSUE TITLE
[Experimental & Legacy] [Bug] Moving parts & freeform bugged when loading world [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#968]
When loading a world in either experimental or legacy branches, creations with freeform blocks show those blocks as invisible. They can still be collided with, and the voxels that make them up can be highlighted, but the blocks themselves are untextured. Additionally, all hinges and rotators reset themselves to their initial starting position, and do not remember what position they were in when the game was saved last.

Interestingly, the first time a world is loaded, these creations retain both the freeform and the moving parts correctly. However, after being loaded in the new versions, then saved, and reloaded, the errors manifest themselves.
...

Load an old or new world, save it, exit the game, then load it up again. Works for both old worlds and newly created worlds.

...

### Environment
18w24a
NVIDIA GeForce GTX 1060 6GB

### Additional information:

![20181027161357_1](https://user-images.githubusercontent.com/33041786/47609500-6771c100-da05-11e8-9142-6e63f411da52.jpg)

![20181027162832_1](https://user-images.githubusercontent.com/33041786/47609499-63de3a00-da05-11e8-98d6-ffe75a811862.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2522208/output_log.zip)

**Comment by Garrett-C** [comment]
Freeform blocks are being removed anyway so that’s not a major issue.

**Comment by Dwarf-LordPangolin** [comment]
This is true, but it does prevent us from using the grace period allowed by the legacy branch to transfer our designs to the new building system. I'll have to build everything from scratch. Which is fine, just inconvenient.

**Comment by tsunamayo** [comment]
Yes sorry it was too hard to keep the freeform because of saving issue, so this why it no longer work once you reload from the new save. Same for the slider/rotator value. Sorry for the inconvenience!
