### ISSUE TITLE
[Experimental & Legacy] Red only color paint selectable [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#969]
Short Description of the issue:

The only color of paint that can be selected in the codex at the moment is red. Colors already in use can be selected by middle-mousing over the blocks and selecting it via the wheel menu, but the codex only shows red.

Steps to reproduce the issue:

Codex only shows red paint under tools.

Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

Additional information:

![20181027163942_1](https://user-images.githubusercontent.com/33041786/47609570-fd5a1b80-da06-11e8-9fb9-89a0413251fa.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2522221/output_log.zip)

**Comment by Garrett-C** [comment]
If you equip the red colour and press the toggle button “q” by default for me you open the paint menu with all the colours.

**Comment by tsunamayo** [comment]
Yes sorry it is confusing because of the color red. I will improve the icon for sure it was temporary, also I will add some kind of UI help to teach the player what happen with q and e as they all have different functions. Thanks!
