### ISSUE TITLE
[Bug] Character customization - broken textures

### ISSUE THREAD

**Issue by Bejasc** [tsunamayo/Skywanderers#97]
applies to Tarkin, Kraboutzob, and Bagoulin.

Heads appear white and not UV mapped.

Any hair combination will _also_ appear white with the same models. 

![image](https://user-images.githubusercontent.com/12091874/31847663-37bdeb40-b667-11e7-9cc1-a733be056429.png)

![image](https://user-images.githubusercontent.com/12091874/31847666-454b1080-b667-11e7-9fd5-0a6600de4d59.png)

![image](https://user-images.githubusercontent.com/12091874/31847668-4fde75dc-b667-11e7-8e23-c83552db0dda.png)

**Comment by tsunamayo** [comment]
Thanks for reminding me this! ;-) it is fixed now...
