### ISSUE TITLE
[Experimental & Legacy] [Bug] Cannot use seats or buttons/switches near freeform blocks [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#970]
Short Description of the issue:

Trying to highlight a seat, switch, or button to use it when it occupies the same voxel as a freeform block results in highlighting the freeform block instead. Since the FFB is going to be replaced with a different one, this may not be something that needs to be addressed, but I thought I'd mention it just in case.

Steps to reproduce the issue:

See screenshot below.

Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

Additional information:

![20181027164328_1](https://user-images.githubusercontent.com/33041786/47609615-0f888980-da08-11e8-816d-901a67873504.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2522225/output_log.zip)

**Comment by tsunamayo** [comment]
Okay sorry the freeform are being quite buggy, that is the last scream of the beast before it gets slashed ^^ This is why I made it evolve, it was such a huge nest of bugs.
I hope you guys love the rescaled shape, and I am sure you will like the upcoming prefab freeform.
How is it with the new rotation? 
Thanks

**Comment by Dwarf-LordPangolin** [comment]
The new rotation is great! Combined with the click-and-drag system, building is very fast after a little practice.

**Comment by Garrett-C** [comment]
Personally I did prefer the drag rotation. It was a lot faster. However I can see that with the new resizable shapes the old style wouldn’t work. Only suggestion would perhaps be a way to see how the block is oriented. Not an issue for most blocks but could be good for something like the engines.

**Comment by tsunamayo** [comment]
With the time I think the switch to a full stretching and key rotation was very positive for the building experience!
Thanks
