### ISSUE TITLE
Capacitors don't delete

### ISSUE THREAD

**Issue by Doehg** [tsunamayo/Skywanderers#971]
### Short Description of the issue:

Basically, when deleting a long capacitor, it refuses to comply and the delete effect goes on forever.  I'm unable to build anything else.

### Steps to reproduce the issue:

Make a  l o n g  capacitor block, wait a bit, then delete it. (or at least try to)
also if you re-load the world, you can't scroll through the hotbar

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050Ti

ill add pictures and output files when I screw up again, cuz im busy and don't want to have to restart my game again

**Comment by tsunamayo** [comment]
This issue should be fixed. Thanks!
