### ISSUE TITLE
Mirror issues and drag to place cut out

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Skywanderers#973]
Description of the issue:
On attempting to drag and place blocks, it cuts out, and spams blocks as I drag instead of the whole thing. After deleting these blocks, and either successfully or unsuccessfully dragging and placing blocks, they will not mirror on one side, if you have 2 mirror planes. Also, if you delete a block by dragging into it (Like if there is a wedge on a 3x3 block plane, but you want to drag a 3x3 one, and it deletes the single normal wedge), that will not mirror either

Steps to reproduce the issue:
1)Attempt to drag blocks. It may cut out
2)Re-try until it works
3)Its not mirrored on one side. smh

 Environment
- Skywanderers version: The legacy one 18w24a
- Graphics Card: AMD Raedon HD 7500 series

Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2522431/output_log.txt)
Top
![20181028162529_1](https://user-images.githubusercontent.com/43084360/47611633-0e219480-dace-11e8-987e-ee0991d2a252.jpg)
Bottom
![20181028162653_1](https://user-images.githubusercontent.com/43084360/47611634-124db200-dace-11e8-89c6-8d1c837a5932.jpg)

**Comment by tsunamayo** [comment]
I am not sure to understand your issue. Is this still happening with a single mirror and no mirror at all or only 2 mirror planes?
"Also, if you delete a block by dragging into it " -> this I dont understand.
Thanks

**Comment by ultrak2k** [comment]
> I am not sure to understand your issue. Is this still happening with a single mirror and no mirror at all or only 2 mirror planes?
> "Also, if you delete a block by dragging into it " -> this I dont understand.
> Thanks

The dragging issue is universal, but it doesnt happen if you attempt to do it with one mirror, and what I mean is when there is a singular block or a few in the way of your dragging selection, when you place that said freeform down the block being overlapped will dissapear, and that freeform will not mirror no matter what, since it doesnt seem to be able to place a freeform block on the otherside, since said block being overlapped would be on the other side due to mirror anyway

**Comment by tsunamayo** [comment]
Closing this. tx
