### ISSUE TITLE
[Experimental & Legacy] [Bug] Cannot save blueprints [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#974]
### Short Description of the issue:
Attempting to save a ship as a blueprint does not work. This is true when trying to create new blueprints, as well as when trying to overwrite old blueprints.

### Steps to reproduce the issue:
Open identity block, save blueprint, load blueprint.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2523285/output_log.zip)

**Comment by Rizzo911** [comment]
I am also having this issue on all builds. It is making it hard to update our blueprints after we remove offending old blocks, because we can't save out the fixed blueprint.

**Comment by ultrak2k** [comment]
It does save it, it just saves it in the new format, the problem is the fact we cant load the new format (the save icon doesnt show either)

**Comment by tsunamayo** [comment]
This issue was fixed (it was a loading blueprint issue - it was loading the old format, which is was mandatory for the LEGACY update) Thanks
