### ISSUE TITLE
[Experimental] [Bug] Button acts like block instead of brick [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#975]
### Short Description of the issue:
The button brick does not occupy brick spaces, but centers itself on a voxel.

### Steps to reproduce the issue:
Try to place button anywhere other than middle of a block.

### Environment
Skywanderers version: 18w24a
Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:

![20181028185609_1](https://user-images.githubusercontent.com/33041786/47623878-42a04b00-dae4-11e8-94cd-5d30a5a1e903.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2523344/output_log.zip)

**Comment by tsunamayo** [comment]
Indeed, issue is now fixed! Thanks
