### ISSUE TITLE
[Experimental] [Bug] Rotator brick placement offset from grid [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#976]
### Short Description of the issue:
The rotator brick does not snap to the normal brick grid, but appears to be offset from it by .125 meters.

### Steps to reproduce the issue:
Place rotator brick on block.

### Environment
Skywanderers version: 18w24a
Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20181028192117_1](https://user-images.githubusercontent.com/33041786/47624109-ad528600-dae6-11e8-9636-b1d44fc3589b.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2523364/output_log.zip)

**Comment by Dwarf-LordPangolin** [comment]
Update: This appears to be the case for a number of other bricks as well, including:

Rocket launcher
Guided missile launcher
Cushion

**Comment by JRL101** [comment]
This is possibly an issue with LEGACY branch only. A lot of the old way of alignment with blocks and bricks isnt on the same grid. I would suggest replacing most of the ship if this is happening. I cant find a way around this issue without using sliders, the block collision check makes clipping things into place difficult for now.

**Comment by Dwarf-LordPangolin** [comment]
This is not an issue with Legacy branch only. I tagged it as Experimental because I found it in Experimental.

**Comment by JRL101** [comment]
I didnt experience this in Experimental before legacy, did experimental update at the same time? or is this after installing legacy?

**Comment by tsunamayo** [comment]
Yes sorry codex need a bit of cleaning. Now experimental is ahead of legacy, so it make sense to have this on both (I know exactly why we are having the issue). Your list will greatly help me to fix, thanks!

**Comment by tsunamayo** [comment]
Okay it is fixed! Thanks
