### ISSUE TITLE
Ruler Guide Missing [18w24a]

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#977]
### Short Description of the issue:
The old ruler guide (block counter) was very useful when dragging out long blocks and creating planes of blocks. It seems to be missing from the latest build. This would be incredibly useful with the new block and brick system.

### Steps to reproduce the issue:
- Place a starter block or use an existing build
- Attempt to click add a standard block and drag it out in either a plane or row
- Note the guide is missing to tell you how many blocks you've dragged 

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GeForce GTX 960

**Comment by tsunamayo** [comment]
Yes it will be back for sure, now things are a bit wip and rough sorry...
Cheers

**Comment by tsunamayo** [comment]
So it was introduced back a few build ago. Thanks!
