### ISSUE TITLE
[Experimental] [Bug] Cannot attach most blocks to sliding brick [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#978]
### Short Description of the issue:
Many blocks cannot be placed on the moving part of the sliding brick, while some can only do so at certain angles.

### Steps to reproduce the issue:
Place sliding brick, then attempt to place larger block on it.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20181029013934_1](https://user-images.githubusercontent.com/33041786/47633450-f07b1c00-db1b-11e8-9b5b-98d083213b25.jpg)

![20181029013954_1](https://user-images.githubusercontent.com/33041786/47633567-58c9fd80-db1c-11e8-8462-25a85b66e747.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2524143/output_log.zip)

**Comment by tsunamayo** [comment]
Yes this is a by product of the collision check. The rail system is gonna be completely refactored, thanks!

**Comment by tsunamayo** [comment]
This is one of the reason I made a bug refactor of the rail block. Thanks!
