### ISSUE TITLE
[Experimental] [Bug] Logic bricks not saving values [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#979]
### Short Description of the issue:
The values entered for logic bricks are not saved, requiring them to be re-entered.

### Steps to reproduce the issue:
Place logic bricks, link them to systems, save, quit, and reload.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2530886/output_log.zip)

**Comment by tsunamayo** [comment]
This issue was fixed a while back, not sure if it was live in the drone patch of not though. Cheers, thanks for testing that much!
