### ISSUE TITLE
[Experimental] [Bug] Child entities moving to new places, attaching to different points [18w24a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#980]
### Short Description of the issue:
I was building a cockpit, and attached the seat to one hinge, and the frame for the canopy to another. However, on loading the world today, I found that the hinges had somehow swapped their attachment points; the chair was now connected to the hinge that had been used for the canopy, and the canopy frame was now attached to the chair's hinge.

### Steps to reproduce the issue:
Create a new ship, place a pair of hinges on it, attach different things to them to clearly distinguish between the two, save, and load.

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The hinge has been swapped somehow, and now the chair is attached to that hinge.
![20181030123852_1](https://user-images.githubusercontent.com/33041786/47739734-0ab01980-dc44-11e8-826f-7b78c46eae14.jpg)

A test demonstration before saving & reloading:
![20181030125712_1](https://user-images.githubusercontent.com/33041786/47739682-e7856a00-dc43-11e8-81c8-d8d298db752f.jpg)

And after:
![20181030125753_1](https://user-images.githubusercontent.com/33041786/47739689-eb18f100-dc43-11e8-86ab-3258e6f52a60.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2530982/output_log.zip)

**Comment by Rizzo911** [comment]
I'm also having this issue. Same result on old builds and new.

**Comment by Dwarf-LordPangolin** [comment]
Update: when this happens, it seems that the blocks & bricks formerly attached to the child entities might be re-attaching themselves to the area on the main entity where the starter block was placed.

**Comment by JRL101** [comment]
agreed looks extremely similar. but yours dont seem to be teleporting the subgrid to the closest outside point to the parent grid. also not sure whats moving in the later images.

**Comment by JRL101** [comment]
I always search it. Strangely enough this didn't come up.
I still cant figure out whats moved on your last few images.

**Comment by Dwarf-LordPangolin** [comment]
> I still cant figure out whats moved on your last few images.

Well, you're not the dev, so I don't honestly care. Please stop spamming bug reports with useless comments.

**Comment by tsunamayo** [comment]
Sorry for the bug guys, I made some change it seems fixed now - patch coming soon.

PS : thanks for your help all it is really helpfull to have dedicated tester, but please please keep it civil! ;-)
