### ISSUE TITLE
[Suggestion] Engine upgrades

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#981]
So you're upgrading engine, I assume you saw 2018.3 with this section :D 
Wonder if its possible to put planets and ship blueprints into nesting prefab hierarchies like this. Either way that Entity Component System (ECS) is helpful for running large amounts of AI
https://youtu.be/alZ6wmwvck0?t=5933

**Comment by tsunamayo** [comment]
Yes I saw that they are making huge progress, I will look into that at one point for sure - waiting for ECS to become a bit more mature. Cheers!
