### ISSUE TITLE
[BUG] Minimum FOV locked at 50

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#982]
When trying to lower your FOV, the slider in graphics options will behave as normal, but the value of the FOV will go no lower than 50
...

Open options ->graphics
Use the slider to lower FOV, notice the value gets stuck at 50. Maximum value of 100 is unchanged
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050M

<a href="https://imgur.com/BenccKJ"><img src="https://i.imgur.com/BenccKJ.png" title="source: imgur.com" /></a>

**Comment by tsunamayo** [comment]
Not really an issue, 50 is minimum value. Thanks!
