### ISSUE TITLE
cannot remove old 2x1 corner blocks

### ISSUE THREAD

**Issue by oojimaflip** [tsunamayo/Skywanderers#984]
### Short Description of the issue:
Cannot remove old 2x1 corner blocks, no mouse interaction
...

### Steps to reproduce the issue:
load a legacy blueprint with 2x1 corners and attempt to remove
![20181026083001_1](https://user-images.githubusercontent.com/33450683/47916213-501b5380-de9d-11e8-97a3-426f525239a1.jpg)
2x1 corner blocks also have an incorrect scaling.

...

### Environment
- Skywanderers version: legacy
- Graphics Card: gtx980

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Issue is now fixed! Thanks a lot.
