### ISSUE TITLE
[BUG] Alignment axis different from core direction

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#985]
### Short Description of the issue: 
My ship core is aligned to the forward area of my ship. If I enter the core I am facing exactly the direction I want and can move in my intended directions. However if I align my player to the ship I am instead oriented in a completely different direction. Instead of facing forward my character rotates to face up. Making a new core orientated in different ways does not fix this issue. It will change the ship control direction but not the player alignment.

...

### Steps to reproduce the issue:
Make ship cores and see if alignment is off from movable direction.
...

### Environment
- Skywanderers version: Pre-Alpha 18w24a
- Graphics Card: GTX 1080

### Additional information:

Way my core is facing and how I want my character to face.
![711980_20181103002005_1](https://user-images.githubusercontent.com/37836252/47948701-3a914280-df0c-11e8-9988-eb760af80b5c.png)

This is how I'm oriented when aligning myself.
![711980_20181103002128_1](https://user-images.githubusercontent.com/37836252/47948704-4c72e580-df0c-11e8-90cd-9d44f58aac31.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2544670/output_log.txt)

**Comment by tsunamayo** [comment]
Refactoring is done, patch coming soon. Thanks
