### ISSUE TITLE
[LEGACY][Experimental]-18w24a- Sub grid structures move to parent grid?

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#986]
### Short Description of the issue:
Entities on hinges or rotors seem to randomly teleport to the main body of the ship
after a game reload.
...

### Steps to reproduce the issue:
Save and reload game [Legacy]
...

### Environment
- Skywanderers version: 18w24a-**[L]**
- Graphics Card: GTX 1080

### Additional information:
![image](https://user-images.githubusercontent.com/33255536/48141247-726e0080-e2e5-11e8-93bf-0593a3943c63.png)
![image](https://user-images.githubusercontent.com/33255536/48141325-a3e6cc00-e2e5-11e8-8201-e32a56b5a152.png)

------------
[18w24aSubGridBug[Legacy].zip](https://github.com/tsunamayo/Skywanderers/files/2558040/18w24aSubGridBug.Legacy.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2558041/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by JRL101** [comment]
Parts of the entity which is now part of the main body are hidden inside the first block 
![image](https://user-images.githubusercontent.com/33255536/48141817-9847d500-e2e6-11e8-96d0-19ecb491a0b4.png)

Other ship this has happened to is here 
![image](https://user-images.githubusercontent.com/33255536/48141890-b7defd80-e2e6-11e8-8fb6-a600067980f2.png)
Pilots control panel is just up here, which if im right isnt the starting block location.

This is the original connection points for the misplaced sub grid and the other sub grid that didnt move.
along with a shot of the reset sliders and hinges. 
![image](https://user-images.githubusercontent.com/33255536/48142720-4607b380-e2e8-11e8-8d1d-b462b17e610c.png)

**Comment by JRL101** [comment]
The hinge/rotors with, missing subgrids, keep making sound when triggered also.

**Comment by Dwarf-LordPangolin** [comment]
This appears to be the same issue found here:

https://github.com/tsunamayo/Skywanderers/issues/980

**Comment by tsunamayo** [comment]
I think this issue should be fixed in recent builds. Thanks
