### ISSUE TITLE
[BUG] Game doesn't load with Nvidia 4xx drivers and/or RTX card

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#987]
### Short Description of the issue:
Recently swapped a new video card and latest Nvidia drivers. Game often does not load. Previously had a GTX 1080 and 399.xx drivers which loaded the game without fail. With an RTX 2080 Ti and various versions of Nvidia 4xx drivers the game is lucky to load after many attempts within an hour. Unsure if this is a video card issue or a driver issue. Other games (Unity engine based included) have no issues.
...

### Steps to reproduce the issue:
Use an Nvidia card with latest driver and try to load a save file. Or use an RTX card.
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: RTX 2080 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2568153/output_log.zip)

**Comment by BrickMacklin** [comment]
> 
> 
> Hehe I dont have an RTX card to reproduce I am on my GTX960 ;-) Will install latest drivers and see if I reproduce. Can you send the output_log to see if there is anything? Cheers

Thank you! Log has been uploaded.

**Comment by tsunamayo** [comment]
So that issue was a fixed a few month back, it was hard to fix but at last it should be fine now. Thanks!
