### ISSUE TITLE
[Experimental] [Bug] List of ships from "Load" button all default to "Spaceship 1" [18w45a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#990]
### Short Description of the issue:
When using the Builder Drone's "Load" menu, all ship names display as "Spaceship 1."

### Steps to reproduce the issue:
Summon drone with F5, press "Load" button.

### Environment
- Skywanderers version: 18w45a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20181109235320_1](https://user-images.githubusercontent.com/33041786/48299735-f0253e00-e496-11e8-81ae-e071da41b3c1.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2568256/output_log.zip)

**Comment by daOyster** [comment]
I'm also getting the same issue. Each different ship loads fine but they're all labeled Spaceship 1 in the list even though the blueprint has a different name once spawned.

**Comment by tsunamayo** [comment]
Hello, I am not reproducing this issue and I dont remember seing it / fixing it either. I will ping you when the new update is live, so you can tell me if it is fixed or not. Thanks!

**Comment by Rizzo911** [comment]
Still happening as of 18w47a:

![20181124120654_1](https://user-images.githubusercontent.com/33043997/48970956-8dc55500-efe1-11e8-8e44-0cd627a1a603.jpg)

**Comment by Tomatart** [comment]
I can confirm that this is still happening in the newest update.
![screenshot 313](https://user-images.githubusercontent.com/26846110/48976106-7021db00-f035-11e8-80b0-b55e5c56e00f.png)

**Comment by tsunamayo** [comment]
This issue was fixed already back then. Thanks
