### ISSUE TITLE
[Experimental] [Bug] Cannot place Starter Block [18w45a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#991]
### Short Description of the issue:
New ships cannot be started, as the Starter Block can no longer be placed, and there is no alternative method of starting a new ship.

### Steps to reproduce the issue:
Select Starter Block from codex, attempt to place.

### Environment
- Skywanderers version: 18w45a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2568257/output_log.zip)

**Comment by tsunamayo** [comment]
Sorry for the miss, this issue is fixed. Thanks!
