### ISSUE TITLE
[Experimental][Suggestion] Paint Selection Key Binding

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#992]
Currently, it seems that the key bind to select a paint color is linked to the same key as the "rotate block left" key bind. While it isn't terribly difficult to get used to this, it would be nice to have the option to bind the paint picker key to something else without changing the "rotate left" bind.

It would also help with documenting the game controls, because currently the paint picker is a hidden feature. Since there's only one paint option in the codex now, I've seen a bit of confusion as to how to get the other colors from people who don't know the color picker key bind exists!

**Comment by tsunamayo** [comment]
Now there is a paint feature in the codex, which makes it a bit more logical - you dont really to know about the color picker. But it would need some sort of hint, or a in-game help when paint is selected. Thanks!
