### ISSUE TITLE
[Suggestion] Red drone clipping and speed

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Skywanderers#993]
### Short Description of the issue:
When using symmetry with the red drone it very often gets stuck behind one block preventing it from building. This is especially noticeable on large ship builds. It also is very slow both with building and painting. Often I need to go check its progress. I believe it would be better to let the red drone clip through any object to get every block built. And increase its speed. 
...

### Steps to reproduce the issue: 
Build an object with symmetry and watch the drone get stuck.

...

### Environment
- Skywanderers version: 18w45a
- Graphics Card: RTX 2080 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2568744/output_log.zip)

**Comment by ProPeach** [comment]
Increasing the drones reach distance and "view cone" could also help with this so the drone doesn't have to be looking directly at the block to be painted/built

**Comment by ZachZent** [comment]
Based on the recent devlog, it would seem the FR-3N and PA-1 drones will mainly be used in shipyards rather then just by people. Increasing the reach distance and view cone will work, but when the ship gets larger, this issue will come right back.

I see two potential solutions. The first one is to allow the drones to no-clip and visually make them "holograms" which makes it seem a little more reasonable. The second way is rather then a drone that follows you around, a larger one that is a distance away from the ship. Still moving, but in a sphere around the ship. Like the shield bubble. It could use a "laser beam" which would place and paint. There is a third idea, but I think I will leave that for later on.

**Comment by Senakysam** [comment]
I also thinking clipping would be good instead of having it collide. There are too many ways for it to get stuck, and that is with a fully symmetrical ship. With a ship that has a lot of asymmetrical areas along with symmetrical areas, the drone will be trying to get to areas that it might not physically be able to reach.

**Comment by tsunamayo** [comment]
We now have a symmetry tool instead. Thanks!
