### ISSUE TITLE
[Experimental] [Bug] Bricks cannot attach to other bricks at starting location [18w45a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#994]
### Short Description of the issue:
Bricks cannot be attached to the spot that another brick was originally placed on. Trying to do so does not show the ghost brick image, and a new brick cannot be placed there.

### Steps to reproduce the issue:
Place a brick, then place another on top of it. Delete the first brick, and try to attach a new brick to the spot it was attached to on the second brick.

### Environment
-Skywanderers version: 18w45a
-Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Placing the initial bricks:
![20181111201245_1](https://user-images.githubusercontent.com/33041786/48322781-dd258180-e5ee-11e8-8cc4-c3633a1ac0ed.jpg)

Deleting the first one:
![20181111201247_1](https://user-images.githubusercontent.com/33041786/48322784-df87db80-e5ee-11e8-9fee-f9466161c8be.jpg)

Because the second brick was placed on the first brick on this face, a new brick cannot be attached there.
![20181111201251_1](https://user-images.githubusercontent.com/33041786/48322786-e1ea3580-e5ee-11e8-9484-7065408cc8dc.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2570249/output_log.zip)

**Comment by JRL101** [comment]
confirmed, this issue has been present for a long time now. Some new blocks/bricks in the new versions do ignore this old problem with initial placement faces being unbuild-able. 

Current work around uses scaffolding. to place a brick or block in the wanted space.

**Comment by JRL101** [comment]
Well some of the newer blocks seem to accept pining all sides, but then others don't. 
Is there a mask for each block/brick that give permission to pin another block/brick?
Just a thought; 
all you have to do to get the coordinates to place the stating cube right?
Can you calculate the positions using the face the player is looking at? then place the start point for the brick/block calculated by the face dimensions?

**Comment by tsunamayo** [comment]
@JRL101 yes this is exactly how I do to determine how to place a brick. But the issue was that bricks where stored in a dictionary stud / brick, so you could not have two bricks place as the same stud! Anyway this limitation is now gone as I changed the implementation. Thanks!
