### ISSUE TITLE
Suggestion: Leave the Mirror block as an option for creative

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#995]
### Short Description of the suggestion:
The new drone is quite cool but the use of the drone for the mirror is quite painful for creative. It is really slow at mirroring and you are limited to a single axis. I think they are a good addition for survival but survival is a long way off from the sounds of things so why compromise the creative side of the game for a survival that is a long way away.

**Comment by Xerma** [comment]
There is also near to no way to build near the mirror plane without moving it. And I do agree that it is very slow. It is important to work on survival aspects but they shouldn't be replacing creative things this early on.

**Comment by daOyster** [comment]
I would love for this as well. I don't mind not having them in survival eventually if that ever comes but in creative the old way worked well and allowed for some interesting mirroring setups that made building very quick. The new way feels more limiting for a creative mode.

**Comment by tsunamayo** [comment]
Hi, so I made an option to hide the plane so you dont accidentally move it (it was already in your version)

For the many building plane it is not linked to drone / block choice at all, it was just a messy and buggy part of the code, so it was cut in the refactoring. I will see if I can re-introduce it (in a clean way, I am now super careful on not creating too much technical debt as it could kill me and the game on the long term). As nobody is building stations (or at least finishing them haha) I though it would not be that much of a big of a deal, but I can think about it and put it on the roadmap again.

If it is too slow and cant keep up I will introduce a timer, like if it havent managed to execute the order after 3 sec it take the action no matter what. But I want to stress that actually it should not matter, the drone have a queue of orders, not just a single one, so you can build and forget.

But again it has nothing to do with survival, the old mirroring code was really dirty and bug prone (even more so after the rescale update) so I had to do a big refactor.

Thanks, and sorry for the frustration =( . The no collision patch is coming soon. Cheers

**Comment by gmunga5** [comment]
The issue with the speed is more when you take a step back to look at your ship and find out that the drone hasn’t even managed to do half of what you did so you are forced to wait for it to catch up. Kind of hard to build fast and review your work when it takes so long for the drone to do it.

**Comment by tsunamayo** [comment]
okay gotcha, I am gonna a fast mode of some sort. Maybe do like unqueue all the order at once? So instant catch-up.

**Comment by Rizzo911** [comment]
Thanks, the issue was that it wasn't clear that the button was a toggle. I will open a suggestion to toggle the text on the button so that it is clearer that it is actually a toggle.

**Comment by tsunamayo** [comment]
We now have a mirroring tool. Thanks!
