### ISSUE TITLE
Building drone cannot spawn new ships

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#996]
### Short Description of the issue:
The building drone has no option to spawn a new ship, only existing blueprints. Because the starter block is now disabled there is no way to spawn a new ship.
...

### Steps to reproduce the issue:
Open drone, and try to spawn a new ship.
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hey howdy @Tomatart ! Hope you are doing good!
Yes indeed it was a bug. It is now fixed - update coming today or tomorrow.
Cheers
