### ISSUE TITLE
Building drone breaks when switching sides.

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#998]
### Short Description of the issue:
Pretend the ship has a "left" and "right" side. If you spawn the drone and activate symmetry, when you place blocks on the right side the red drone will place blocks on the left side. If you then place blocks on the left side, the red drone starts spinning in circles and no longer places blocks unless you deactivate and reactivate symmetry. 
...

### Steps to reproduce the issue:
Spawn drone, activate symmetry, place blocks on both sides of the symmetry line. 
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hum sounds bad! I cant reproduce, is there anything special that I might not be doing? Thanks

**Comment by tsunamayo** [comment]
No longer applicable. Thanks!
