### ISSUE TITLE
[Experimental] [Bug] Multiple ship cores allow any direction to be "forward" [18w45a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#999]
### Short Description of the issue:
Because ship cores treat whatever direction they are facing as "forwards" for the ship, and multiple ship cores can be placed, ships can be flown at top speed in any direction simply by switching which ship core the vessel is currently controlled from, allowing ships to circumvent the restrictions on Boost mode.

### Steps to reproduce the issue:
Place two ship cores on a ship, one facing a different direction from the other. Control one, then the other.

### Environment
-Skywanderers version: 18w45a
-Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Weeeee!
![20181116212415_1](https://user-images.githubusercontent.com/33041786/48656172-f5c6da80-e9e6-11e8-8a04-e8fdc6c36846.jpg)

[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2591454/output_log.zip)

**Comment by tsunamayo** [comment]
Yes very true. Actually I was working on a spaceship core refactor, so  now you specify ship orientation manually in the block( block orientation no longer matter). But I need to store thrust along axis to cap maximum speed depending on the direction. Thanks

**Comment by tsunamayo** [comment]
No longer the case on the newer builds. Thanks for being active for so long ;)
